<?php

/**
 * BillLayoutPhraseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillLayoutPhraseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillLayoutPhraseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillLayoutPhrase');
    }
}