<?php

/**
 * BillBuildUpQuantityFormulatedColumnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillBuildUpQuantityFormulatedColumnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillBuildUpQuantityFormulatedColumnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillBuildUpQuantityFormulatedColumn');
    }
}