<?php

/**
 * BillTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillType');
    }
}