<?php

/**
 * BillElementTypeReference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BillElementTypeReference extends BaseBillElementTypeReference
{

    public function calculateEstimatedCost(Doctrine_Connection $conn = null){
        $billColumnSetting = $this->BillColumnSetting;

        //calculate estimated cost_per_metre_square
        $estimatedCost = $this->estimated_cost_per_metre_square * $billColumnSetting->total_floor_area_m2;

        if($estimatedCost != $this->estimated_cost)
        {
            $this->estimated_cost = $estimatedCost;
            $this->save();
        }

        return $this->estimated_cost;

    }

}
