<?php

/**
 * BillBuildUpFloorAreaEdgeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillBuildUpFloorAreaEdgeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillBuildUpFloorAreaEdgeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillBuildUpFloorAreaEdge');
    }
}