<?php

/**
 * BillItemLumpSumPercentageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillItemLumpSumPercentageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillItemLumpSumPercentageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillItemLumpSumPercentage');
    }

    public static function insertDefaultEmptyRow(BillItem $item)
    {
        $lumpSumPercent = self::getInstance()->findOneByBillItemId($item->id);

        if ( ! $lumpSumPercent )
        {
            $lumpSumPercent = new BillItemLumpSumPercentage();
            $lumpSumPercent->bill_item_id = $item->id;
            $lumpSumPercent->save();
        }
    }
}