<?php

/**
 * BillCollectionPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillCollectionPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillCollectionPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillCollectionPage');
    }
}