<?php

/**
 * BillBuildUpRateFormulatedColumnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillBuildUpRateFormulatedColumnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillBuildUpRateFormulatedColumnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillBuildUpRateFormulatedColumn');
    }
}