<?php

/**
 * ClaimCertificatePrintSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimCertificatePrintSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ClaimCertificatePrintSettingTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaimCertificatePrintSetting');
    }
}