<?php

/**
 * DebitCreditNoteClaimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DebitCreditNoteClaimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return DebitCreditNoteClaimTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DebitCreditNoteClaim');
    }
}