<?php

/**
 * ItemCodeSettingObjectBreakdownTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemCodeSettingObjectBreakdownTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ItemCodeSettingObjectBreakdownTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemCodeSettingObjectBreakdown');
    }
}