<?php

/**
 * MasterCostDataPrimeCostSumItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MasterCostDataPrimeCostSumItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MasterCostDataPrimeCostSumItemTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MasterCostDataPrimeCostSumItem');
    }
}