<?php

/**
 * PostContractClaimClaimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostContractClaimClaimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostContractClaimClaimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostContractClaimClaim');
    }
}