<?php

/**
 * PostContractSubPackageRemeasurementItemTypeReferenceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostContractSubPackageRemeasurementItemTypeReferenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostContractSubPackageRemeasurementItemTypeReferenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostContractSubPackageRemeasurementItemTypeReference');
    }

    public static function getByItemIdAndColumnId($itemId, $columnSettingId, $hydrate=null)
    {
        $query = DoctrineQuery::create()
        ->select('r.*')
        ->from('PostContractSubPackageRemeasurementItemTypeReference r')
        ->where('r.sub_package_post_contract_bill_item_rate_id = ?', $itemId)
        ->andWhere('r.bill_column_setting_id = ?', $columnSettingId)
        ->andWhere('r.deleted_at IS NULL')
        ->limit(1);

        if(!is_null($hydrate))
        {
            $query->setHydrationMode($hydrate);
        }

        return $query->fetchOne();
    }
}