<?php

/**
 * PostContractRemeasurementBuildUpQuantityFormulatedColumnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostContractRemeasurementBuildUpQuantityFormulatedColumnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostContractRemeasurementBuildUpQuantityFormulatedColumnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostContractRemeasurementBuildUpQuantityFormulatedColumn');
    }
}