<?php

/**
 * PreliminariesIncludeFinalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreliminariesIncludeFinalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreliminariesIncludeFinalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PreliminariesIncludeFinal');
    }
}