<?php

/**
 * ProjectUserPermission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjectUserPermission extends BaseProjectUserPermission
{
    const STATUS_PROJECT_BUILDER = 1;
    const STATUS_TENDERING = 2;
    const STATUS_POST_CONTRACT = 4;
    const STATUS_PROJECT_MANAGEMENT = 8;

}
