<?php

/**
 * ProjectMainInformationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectMainInformationTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object ProjectMainInformationTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('ProjectMainInformation');
	}

    /**
     * Find a project by the corresponding E-Project id and the project status.
     *
     * @param $eProjectId
     * @param $status
     *
     * @return mixed
     */
    public function findOneByEProjectIdAndStatus($eProjectId, $status)
	{
		$q = $this->createQuery()
			->from('ProjectMainInformation s')
			->where('s.eproject_origin_id = ?', $eProjectId)
			->andWhere('s.status = ?', $status);

		return $q->limit(1)->execute()->getFirst();
	}

    /**
     * Find a project by only the corresponding E-Project id.
     *
     * @param $eProjectId
     *
     * @return mixed
     */
    public function findOneByEProjectId($eProjectId)
    {
        $q = $this->createQuery()
            ->from('ProjectMainInformation s')
            ->where('s.eproject_origin_id = ?', $eProjectId);

        return $q->limit(1)->execute()->getFirst();
    }

}