<?php

/**
 * ProjectSummaryFooter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjectSummaryFooter extends BaseProjectSummaryFooter
{
    public function preSave($event)
    {
        if($this->isNew())
        {
            $projectSummaryDefaultSetting = DoctrineQuery::create()->select('s.id, s.first_row_text, s.second_row_text, s.left_text, s.right_text')
                ->from('ProjectSummaryDefaultSetting s')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();

            if($projectSummaryDefaultSetting)
            {
                $this->first_row_text = $projectSummaryDefaultSetting['first_row_text'];
                $this->second_row_text = $projectSummaryDefaultSetting['second_row_text'];
                $this->left_text = $projectSummaryDefaultSetting['left_text'];
                $this->right_text = $projectSummaryDefaultSetting['right_text'];
            }
        }

        return parent::preSave($event);
    }
}
