<?php

/**
 * ProjectRevision
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjectRevision extends BaseProjectRevision
{

	const ORIGINAL_BILL_VERSION = 0;

	public function save(Doctrine_Connection $conn = null)
	{
		$isNew = $this->isNew() ? true : false;

		if ( $isNew AND $this->version > 0 )
		{
			$pdo = $this->getTable()->getConnection()->getDbh();

			// set the previous revision's current_selected_revision status to false
			$stmt = $pdo->prepare("UPDATE ".ProjectRevisionTable::getInstance()->getTableName()." SET current_selected_revision = false, locked_status = true WHERE (project_structure_id = :projectStructureId)");
			$stmt->execute([
				'projectStructureId' => $this->project_structure_id
			]);
		}

		// recalculate addendum bill ref for affected page
		if ( $isNew )
		{
			// get last latest revision id
			$lastLatestRevision = ProjectRevisionTable::getLatestProjectRevisionFromBillId($this->project_structure_id);

			// create bill collection and bill pages record for original bill
			// NOTE : if $lastLatestRevision is not found, false will be returned
			// false['version'] evaluates to NULL, and (NULL == 0) will evaluate to true
			if ( $lastLatestRevision['version'] == 0 )
			{
				$sfBillRefGenerator = new sfBillReferenceGenerator($this->ProjectStructure, true);
				$sfBillRefGenerator->process();
			}
			else
			{
				// create bill collection and bill pages record for addendum
				if ( $this->version > 1 )
				{
					$sfBillAddendumRefGenerator = new sfBillAddendumReferenceGenerator($this->ProjectStructure, $lastLatestRevision);
					$sfBillAddendumRefGenerator->process();
				}
			}

			$this->current_selected_revision = true;
		}

		parent::save();
	}

}