<?php

/**
 * ProjectLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectLevel');
    }
}