<?php

/**
 * ProjectManagementCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectManagementCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectManagementCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectManagementCalendar');
    }
}