<?php

/**
 * ScheduleOfQuantityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScheduleOfQuantityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScheduleOfQuantityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScheduleOfQuantity');
    }
}