<?php

/**
 * StockInDeliveryOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StockInDeliveryOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StockInDeliveryOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StockInDeliveryOrder');
    }

    public static function getRecordsByStockInInvoice(StockInInvoice $invoice)
    {
        return DoctrineQuery::create()
        ->from('StockInDeliveryOrder t')
        ->andWhere('t.stock_in_invoice_id = ?', $invoice->id)
        ->orderBy('t.id DESC')
        ->fetchArray();
    }

    public static function deleteRecordsByStockInInvoice(StockInInvoice $invoice)
    {
        $records = Doctrine_Query::create()
        ->from('StockInDeliveryOrder')
        ->where('stock_in_invoice_id = ?', array($invoice->id))
        ->execute();

        foreach ( $records as $record )
        {
            $record->delete();

            unset($record);
        }

        unset($records);

        return true;
    }
}