<?php

/**
 * SubPackagePreliminariesTimeBasedClaimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubPackagePreliminariesTimeBasedClaimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubPackagePreliminariesTimeBasedClaimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubPackagePreliminariesTimeBasedClaim');
    }

    public static function getRecordsByLastRevision(Array $lastLatestRevision)
    {
        $query = DoctrineQuery::create()
        ->from('SubPackagePreliminariesTimeBasedClaim br')
        ->where('br.revision_id = ?', $lastLatestRevision['id'])
        ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);

        return $query->execute();
    }

    public static function insertRecordsByNewRevision(SubPackagePostContractClaimRevision $revision, Array $data)
    {
        if ( count($data) > 0 )
        {
            $pdo = self::getInstance()->getConnection()->getDbh();
            $sql = 'INSERT INTO '.SubPackagePreliminariesTimeBasedClaimTable::getInstance()->getTableName().' (sub_package_post_contract_bill_item_rate_id, up_to_date_duration, total_project_duration, total, revision_id, created_at, updated_at) VALUES ';

            foreach ( $data as $claim )
            {
                $sql_arr[] = '(' . $claim['sub_package_post_contract_bill_item_rate_id'] . ", " . $claim['up_to_date_duration'] . ", " . $claim['total_project_duration'] . ", " . $claim['total'] . ", " . $revision->id . ", NOW(), NOW())";
            }

            $sql .= implode(", ", $sql_arr);

            $statement = $pdo->prepare($sql);
            $result    = $statement->execute();
        }

    }
}