<?php

/**
 * SubPackageCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SubPackageCompany extends BaseSubPackageCompany
{
    public function getRateByBillItemId($billItemId, $hydrate=null)
    {
        $query = DoctrineQuery::create()->select('*')
            ->from('SubPackageBillItemRate r')
            ->where('r.sub_package_company_id = ?', $this->id)
            ->andWhere('r.bill_item_id = ?', $billItemId)
            ->limit(1);

        if(!is_null($hydrate))
        {
            $query->setHydrationMode($hydrate);
        }

        return $query->fetchOne();
    }

    public function delete(Doctrine_Connection $conn = null)
    {
        Doctrine_Query::create()
            ->update('SubPackage s')
            ->set('s.selected_company_id', 'NULL')
            ->where('s.selected_company_id = ?', $this->company_id)
            ->andWhere('s.id = ?', $this->sub_package_id)
            ->execute();

        parent::delete($conn);
    }
	
	public function flushExistingRates()
    {
        SubPackageCompanyTable::flushBillItemRatesBySubPackageCompanyId($this->id);
    }
}
