<?php

/**
 * TenderBillItemRationalizedLumpSumPercentageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TenderBillItemRationalizedLumpSumPercentageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TenderBillItemRationalizedLumpSumPercentageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TenderBillItemRationalizedLumpSumPercentage');
    }
}