<?php

/**
 * TenderBillItemRationalizedPrimeCostRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TenderBillItemRationalizedPrimeCostRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TenderBillItemRationalizedPrimeCostRateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TenderBillItemRationalizedPrimeCostRate');
    }

    public static function getByBillItemId($billItemId, $hydrate=null)
    {
        $query = DoctrineQuery::create()->select('c.*')
            ->from('TenderBillItemRationalizedPrimeCostRate c')
            ->leftJoin('c.TenderBillItemRationalizedRates ir')
            ->where('ir.bill_item_id = ?', $billItemId)
            ->andWhere('c.deleted_at IS NULL')
            ->limit(1);

        if(!is_null($hydrate))
        {
            $query->setHydrationMode($hydrate);
        }

        return $query->count() > 0 ? $query->fetchOne() : false;
    }
}