<?php

/**
 * VariationOrderClaimItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VariationOrderClaimItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VariationOrderClaimItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VariationOrderClaimItem');
    }
}