define("../../../dojo/_base/declare dojo/_base/lang dojo/aspect dojo/when dojo/currency buildspace/apps/ProjectBuilder/Builder buildspace/apps/Tendering/Builder ./ScheduleOfRateGrid ./buildUpSummary ./ProjectGrid buildspace/widget/grid/cells/Formatter buildspace/widget/grid/Filter dojo/i18n!buildspace/nls/ProjectImportRates".split(" "),function(l,m,t,w,x,u,y,z,A,B,h,n,d){var p=l("buildspace.apps.ProjectImportRates.ScheduleOfRateGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",
gutters:!1,project:null,gridOpts:{},pageId:0,postCreate:function(){this.inherited(arguments);m.mixin(this.gridOpts,{type:this.type,project:this.project});var a=this.grid=new z(this.gridOpts);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));var c=dijit.byId("projectBuilder-import_rates_"+this.project.id+"-stackContainer");if(c){var b=document.createElement("div"),b=new dijit.layout.BorderContainer({gutters:!1,title:buildspace.truncateString(this.stackContainerTitle,
60),id:this.pageId},b);this.region="center";var e=[];this.pageId&&(/^import_rate-page_sor_item-/.test(this.pageId)&&(e=[{description:d.description},{uom_symbol:d.unit},{"rate-final_value":d.rate}]),/^import_rate-page_sor_trade-/.test(this.pageId)&&(e=[{description:d.description}]));b.addChild(new n({region:"top",editableGrid:!1,grid:a,filterFields:e}));b.addChild(this);m.mixin(b,{grid:a});c.addChild(b);c.selectChild(this.pageId)}}}),C=l("buildspace.apps.ProjectImportRates.ScheduleOfRateContainer",
dijit.layout.BorderContainer,{project:null,region:"center",style:"padding:0px;margin:0px;width:100%;height:50%;",gutters:!1,postCreate:function(){this.inherited(arguments);var a=this,c=new h,b=dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportRate/getScheduleOfRates"}),c=p({stackContainerTitle:d.scheduleOfRates,pageId:"import_rate-page_sor-"+a.project.id,project:a.project,gridOpts:{store:b,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},
{name:d.title,field:"name",width:"auto"}],onRowDblClick:function(b){b=this.getItem(b.rowIndex);0<b.id&&null!==b.name[0]&&a.createTradeGrid(b)}}}),c=this.makeGridContainer(c,d.scheduleOfRates);this.addChild(c);c.startup()},createTradeGrid:function(a){var c=this,b=h(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportRate/getScheduleOfRateTrades/id/"+a.id});p({stackContainerTitle:a.name,pageId:"import_rate-page_sor_trade-"+c.project.id+"_"+a.id,project:c.project,gridOpts:{store:e,
structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.description[0]&&c.createItemGrid(a)}}})},createItemGrid:function(a){var c=this,b=h(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportRate/getScheduleOfRateItems/id/"+a.id});new p({stackContainerTitle:a.description,pageId:"import_rate-page_sor_item-"+
c.project.id+"_"+a.id,project:c.project,type:"item",gridOpts:{store:e,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:b.treeCellFormatter},{name:d.type,field:"type",width:"70px",styles:"text-align:center;",formatter:b.typeCellFormatter},{name:d.unit,field:"uom_id",width:"50px",styles:"text-align:center;",formatter:b.unitIdCellFormatter},{name:d.rate,field:"rate-value",width:"100px",
styles:"text-align:right;",formatter:b.formulaCurrencyCellFormatter},{name:d.importRate,field:"import_rate",width:"100px",styles:"text-align:center;",formatter:b.importRateButtonCellFormatter}],onRowDblClick:function(a){var b=a.cell.field;a=this.getItem(a.rowIndex);"import_rate"!=b&&0<a.id&&null!==a.description[0]&&a["rate-has_build_up"][0]&&c.createBuildUpGrid(a)}}})},createBuildUpGrid:function(a){var c=this,b=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;outline:none;",
gutters:!1}),e=new dijit.layout.AccordionContainer({region:"center",style:"padding:0px;width:100%;height:100%;border:0px;outline:none;"}),f=dojo.xhrGet({url:"scheduleOfRate/resourceList/item_id/"+a.id,handleAs:"json"}),g=new h,v=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});v.show().then(function(){w(f,function(f){var k=A({itemId:a.id,container:b});dojo.forEach(f,function(b){var c=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"scheduleOfRate/getBuildUpRateItemList/sor_item_id/"+
a.id+"/resource_id/"+b.id}),c=dojox.grid.EnhancedGrid({store:c,canSort:function(a){return!1},structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:g.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:g.linkedCellFormatter},{name:d.number,field:"number-value",width:"80px",styles:"text-align:right;",formatter:g.formulaCurrencyCellFormatter},{name:d.constant,field:"constant-value",width:"80px",styles:"text-align:right;",formatter:g.formulaCurrencyCellFormatter},
{name:d.qty,field:"quantity-value",width:"70px",styles:"text-align:right;",formatter:g.formulaNumberCellFormatter},{name:d.unit,field:"uom_id",width:"50px",styles:"text-align:center;",formatter:g.linkedUnitIdCellFormatter},{name:d.rate,field:"rate-value",width:"100px",styles:"text-align:right;",formatter:g.formulaCurrencyCellFormatter},{name:d.total,field:"total",width:"100px",styles:"text-align:right;",formatter:g.linkedCurrencyCellFormatter},{name:d.wastage+" (%)",field:"wastage-value",width:"70px",
styles:"text-align:right;",formatter:g.formulaCurrencyCellFormatter},{name:d.lineTotal,field:"line_total",width:"90px",styles:"text-align:right;",formatter:g.linkedCurrencyCellFormatter}]});e.addChild(new dijit.layout.ContentPane({title:b.name+'<span style="color:blue;float:right;">'+buildspace.currencyAbbreviation+" "+x.format(b.total_build_up)+"</span>",style:"padding:0px;border:0px;",doLayout:!1,id:"accPane-"+b.id+"-"+a.id,content:c}))});b.addChild(e);b.addChild(k);if(f=dijit.byId("projectBuilder-import_rates_"+
c.project.id+"-stackContainer"))k=document.createElement("div"),k=new dojox.layout.ContentPane({title:buildspace.truncateString(a.description,60)+" ("+d.buildUpRate+")",id:"sor_buildUpRatePage-"+a.id,executeScripts:!0},k),f.addChild(k),k.set("content",b),f.selectChild("sor_buildUpRatePage-"+a.id);v.hide()})})},makeGridContainer:function(a,c){var b=this.project.id,e=dijit.byId("projectBuilder-import_rates_"+b+"-stackContainer");e&&dijit.byId("projectBuilder-import_rates_"+b+"-stackContainer").destroyRecursive();
var e=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"projectBuilder-import_rates_"+b+"-stackContainer"}),f=new dijit.layout.BorderContainer({gutters:!1});f.addChild(new n({grid:a.grid,region:"top",editableGrid:!1,filterFields:[{name:d.title}]}));a.region="center";f.addChild(a);e.addChild(new dijit.layout.ContentPane({title:c,content:f,grid:a.grid}));var f=new dijit.layout.StackController({region:"top",containerId:"projectBuilder-import_rates_"+b+"-stackContainer"}),
g=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});g.addChild(e);g.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:f}));dojo.subscribe("projectBuilder-import_rates_"+b+"-stackContainer-selectChild","",function(a){var c=dijit.byId("projectBuilder-import_rates_"+b+"-stackContainer");if(c){var d=c.getChildren(),e=dojo.indexOf(d,a);if(d.length>e+1){a.grid.store.save();
a.grid.store.close();var f=t.after(a.grid,"_onFetchComplete",function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,c.removeChild(d[e]),d[e].destroyRecursive(!0)}});return g}}),q=l("buildspace.apps.ProjectImportRates.ProjectGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,project:null,gridOpts:{},postCreate:function(){this.inherited(arguments);m.mixin(this.gridOpts,{type:this.type,
project:this.project,region:"center"});var a=this.grid=new B(this.gridOpts);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));var c=dijit.byId("projectBuilder-import_rates_project_"+this.project.id+"-stackContainer");if(c){var b=document.createElement("div"),b=new dijit.layout.BorderContainer({gutters:!1,title:buildspace.truncateString(this.stackContainerTitle,60),id:this.pageId},b);this.region="center";var e=[];this.pageId&&(/^import_rate-page_project_element-/.test(this.pageId)&&
(e=[{description:d.description}]),/^import_rate-page_project_item-/.test(this.pageId)&&(e=[{description:d.description},{uom_symbol:d.unit},{"rate-final_value":d.rate}]));b.addChild(new n({region:"top",editableGrid:!1,grid:a,filterFields:e}));b.addChild(this);c.addChild(b);m.mixin(b,{grid:a});c.selectChild(this.pageId)}}}),D=l("buildspace.apps.ProjectImportRates.ProjectContainer",dijit.layout.BorderContainer,{project:null,region:"bottom",style:"padding:0px;margin:0px;width:100%;height:50%;",gutters:!1,
splitter:!0,postCreate:function(){this.inherited(arguments);var a=this,c=dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportRate/getProjectBreakdown/id/"+this.project.id}),c=q({stackContainerTitle:d.scheduleOfRates,pageId:"import_rate-page_project-"+this.project.id,project:this.project,gridOpts:{store:c,structure:[{name:"No.",field:"count",width:"40px",styles:"text-align:center;",formatter:r.rowCountCellFormatter},{name:d.description,field:"title",width:"auto",formatter:r.treeCellFormatter},
{name:d.billType,field:"bill_type",width:"120px",styles:"text-align:center;",formatter:r.billTypeCellFormatter}],onRowDblClick:function(b){b=this.getItem(b.rowIndex);0<b.id&&null!==b.title[0]&&b.type[0]==buildspace.constants.TYPE_BILL&&a.createElementGrid(b)}}}),c=this.makeGridContainer(c,buildspace.truncateString(this.project.title,100));this.addChild(c);c.startup()},createElementGrid:function(a){var c=this,b=h(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportRate/getElementList/id/"+
a.id});q({stackContainerTitle:a.title,pageId:"import_rate-page_project_element-"+this.project.id+"_"+a.id,project:this.project,gridOpts:{store:e,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.description[0]&&c.createItemGrid(a)}}})},createItemGrid:function(a){var c=h(),b=new dojo.data.ItemFileWriteStore({clearOnClose:!0,
url:"billManagerImportRate/getItemList/id/"+a.id});q({stackContainerTitle:a.description,pageId:"import_rate-page_project_item-"+this.project.id+"_"+a.id,project:this.project,type:"tree",gridOpts:{store:b,element:a,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:c.treeCellFormatter},{name:d.type,field:"type",width:"70px",styles:"text-align:center;",formatter:c.typeCellFormatter},
{name:d.unit,field:"uom_id",width:"50px",styles:"text-align:center;",formatter:c.unitIdCellFormatter},{name:d.rate,field:"rate-value",width:"100px",styles:"text-align:right;",formatter:c.formulaCurrencyCellFormatter}]}})},makeGridContainer:function(a,c){var b=this.project.id,e=dijit.byId("projectBuilder-import_rates_project_"+b+"-stackContainer");e&&dijit.byId("projectBuilder-import_rates_project_"+b+"-stackContainer").destroyRecursive();var e=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",
region:"center",id:"projectBuilder-import_rates_project_"+b+"-stackContainer"}),f=new dijit.layout.BorderContainer({gutters:!1});f.addChild(new n({grid:a.grid,region:"top",editableGrid:!1,filterFields:[{title:d.description}]}));a.region="center";f.addChild(a);e.addChild(new dijit.layout.ContentPane({title:c,content:f,grid:a.grid}));var f=new dijit.layout.StackController({region:"top",containerId:"projectBuilder-import_rates_project_"+b+"-stackContainer"}),g=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",
gutters:!1,region:"center"});g.addChild(e);g.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:f}));dojo.subscribe("projectBuilder-import_rates_project_"+b+"-stackContainer-selectChild","",function(a){var c=dijit.byId("projectBuilder-import_rates_project_"+b+"-stackContainer");if(c){var d=c.getChildren(),e=dojo.indexOf(d,a);if(d.length>e+1){a.grid.store.save();a.grid.store.close();var f=t.after(a.grid,"_onFetchComplete",function(){f.remove();
this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,c.removeChild(d[e]),d[e].destroyRecursive(!0)}});return g}}),r={rowCountCellFormatter:function(a,c){return 0<a?a:""},treeCellFormatter:function(a,c){var b=this.grid.getItem(c),d=16*b.level;a=null==a?"&nbsp":a;b.type<buildspace.constants.TYPE_BILL&&(a="<b>"+a+"</b>");return'<div class="treeNode" style="padding-left:'+d+'px;"><div class="treeContent">'+a+"&nbsp;</div></div>"},billTypeCellFormatter:function(a,
c){return buildspace.getBillTypeText(a)}};return l("buildspace.apps.ProjectImportRates",buildspace.apps._App,{type:null,win:null,project:null,init:function(a){var c=this.project=a.project;this.type=a.type;a=this.getModuleName();this.win=new buildspace.widget.Window({title:a+" > "+d.importRates+" - "+buildspace.truncateString(c.title,100),onClose:dojo.hitch(this,"kill")});var b=new dijit.layout.BorderContainer({style:"padding:0;width:100%;height:100%;",gutters:!1,liveSplitters:!0}),e=new dijit.Toolbar({region:"top",
style:"outline:none!important;border:0px;padding:2px;overflow:hidden;"});e.addChild(new dijit.form.Button({label:d.backTo+" "+a,iconClass:"icon-16-container icon-16-directional_left",style:"outline:none!important;",onClick:dojo.hitch(this,"openBuilderWin",c)}));b.addChild(e);b.addChild(C({project:c}));b.addChild(D({project:c}));this.win.addChild(b);this.win.show();this.win.startup()},openBuilderWin:function(a){this.kill();this.project=a;var c=this.getModuleName();this.win=new buildspace.widget.Window({title:c+
" > "+buildspace.truncateString(a.title,100)+" ("+d.status+"::"+a.status[0].toUpperCase()+")",onClose:dojo.hitch(this,"kill")});switch(this.type){case buildspace.constants.STATUS_PRETENDER:a=u({project:a});break;case buildspace.constants.STATUS_TENDERING:a=y({project:a});break;default:a=u({project:a})}this.win.addChild(a);this.win.show();this.win.startup()},getModuleName:function(){var a;switch(this.type){case buildspace.constants.STATUS_PRETENDER:a=d.ProjectBuilder;break;case buildspace.constants.STATUS_TENDERING:a=
d.tendering;break;default:a=d.ProjectBuilder}return a},kill:function(){"undefined"!=typeof this.win&&this.win.close()}})});
