define("dojo/_base/declare dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Form dijit/form/Button dijit/form/ValidationTextBox dijit/Toolbar dijit/form/FilteringSelect ./grid dojo/text!./templates/unitOfMeasurementUpdateForm.html dojo/i18n!buildspace/nls/UnitOfMeasurementMaintenance dojo/html buildspace/widget/grid/cells/Formatter dojox/layout/TableContainer dojox/form/Manager".split(" "),function(h,n,y,p,q,r,k,z,l,A,t,u,e,v,m){var w=h("buildspace.apps.UnitOfMeasurementMaintenance.UnitOfMeasurementDimensionGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",rowSelector:"0px",dimensionFilterSelect:null,canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);this.on("CellClick",function(b){var c=b.cell.field;b=a.getItem(b.rowIndex);("up"===c||"down"===c)&&b&&0<b.id&&a.updatePriority(c,b);"delete"===c&&b&&0<b.id&&a.removeDimension(b)})},updatePriority:function(a,b){var c=this,d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});d.show().then(function(){dojo.xhrPost({url:"unitOfMeasurement/unitOfMeasurementDimensionPriorityUpdate",
content:{id:b.id,dir:a,_csrf_token:b._csrf_token},handleAs:"json",load:function(a){a.success&&(c.store.close(),c._refresh(),c.unitOfMeasurementMaintenanceGrid.refreshGrid(),c.store.fetchItemByIdentity({identity:b.id,onItem:function(a){c.selection.clear();c.selection.setSelected(a._0,!0)}}));d.hide()},error:function(a){d.hide()}})})},removeDimension:function(a){var b=this,c=b.dimensionFilterSelect.store,d=buildspace.dialog.indeterminateProgressBar({title:e.deleting+". "+e.pleaseWait+"..."});a.can_be_deleted[0]?
buildspace.dialog.confirm(e.confirmationDimension,"<div>"+e.firstLevelDimensionDialogMsg+"</div>",60,280,function(){d.show().then(function(){dojo.xhrPost({url:"unitOfMeasurement/unitOfMeasurementDimensionDelete",content:{id:a.id,_csrf_token:a._csrf_token},handleAs:"json",load:function(a){a.success&&(b.store.close(),b._refresh(),b.dimensionFilterSelect.store.close(),b.dimensionFilterSelect.set("store",c),b.dimensionFilterSelect.set("value",""),b.unitOfMeasurementMaintenanceGrid.refreshGrid());d.hide()},
error:function(a){d.hide()}})})}):buildspace.dialog.alert(e.itemCannotBeDeleted,e.cannotRemoveDimension,60,300)}}),x=h("buildspace.apps.UnitOfMeasurementMaintenance.UnitOfMeasurementUpdateForm",[r,n,p,q,dojox.form.manager._Mixin,dojox.form.manager._NodeMixin,dojox.form.manager._ValueMixin,dojox.form.manager._DisplayMixin],{baseClass:"buildspace-form",nls:e,formValues:[],uomType:1,templateString:u,unitOfMeasurementMaintenanceGrid:null,postCreate:function(){this.inherited(arguments);var a=this.formValues.id,
b=new m,c=new dijit.layout.BorderContainer({style:"padding:0px;margin:0px;width:100%;height:240px;",gutters:!1}),d=this.addDimensionBtn=new k({label:e.addDimension,iconClass:"icon-16-container icon-16-add",style:"outline:none!important;",disabled:0<a?!1:!0,onClick:dojo.hitch(this,"addDimension")}),f=new l({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border:none;background:#fff;"}),g=this.filterSelectStore=new dojo.data.ItemFileReadStore({clearOnClose:!0,url:"unitOfMeasurement/getDimensionSelectList/uid/"+
a}),a=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"unitOfMeasurement/getUnitOfMeasurementDimensions/id/"+a}),g=this.dimensionFilterSelect=new dijit.form.FilteringSelect({store:g,searchAttr:"name",required:!1,style:"padding:2px;width:240px;"}),b=this.dimensionGrid=new w({store:a,region:"center",dimensionFilterSelect:g,unitOfMeasurementMaintenanceGrid:this.unitOfMeasurementMaintenanceGrid,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},
{name:e.name,field:"name",width:"auto"},{name:e.priority,field:"up",width:"60px",styles:"text-align:center;",formatter:b.moveUpCellFormatter},{name:e.priority,field:"down",width:"60px",styles:"text-align:center;",formatter:b.moveDownCellFormatter},{name:e.action,field:"delete",width:"80px",styles:"text-align:center;",formatter:b.removeCellFormatter}]});f.addChild(g);f.addChild(d);c.addChild(f);c.addChild(b);c.placeAt(this["dimensionBCNode"+this.uomType])},startup:function(){this.inherited(arguments);
this.setFormValues(this.formValues)},addDimension:function(){var a=this.dimensionFilterSelect.value,b=dojo.formToObject(this.id).id,c=this,d=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."});a&&0<a&&this.filterSelectStore.fetchItemByIdentity({identity:a,onItem:function(a){a&&d.show().then(function(){dojo.xhrPost({url:"unitOfMeasurement/unitOfMeasurementDimensionAdd",content:{did:a.id,uid:b,_csrf_token:a._csrf_token},handleAs:"json",load:function(a){a.success&&
(c.dimensionFilterSelect.store.close(),c.dimensionFilterSelect.set("store",c.filterSelectStore),c.dimensionFilterSelect.set("value",""),c.dimensionGrid.store.close(),c.dimensionGrid._refresh(),c.unitOfMeasurementMaintenanceGrid.refreshGrid());d.hide()},error:function(a){d.hide()}})})}})},submit:function(){var a=this,b=dojo.formToObject(this.id),c=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."});this.validate()&&c.show().then(function(){dojo.xhrPost({url:"unitOfMeasurement/unitOfMeasurementUpdate",
content:b,handleAs:"json",load:function(b){dojo.query('[id^="uom_'+a.uomType+'_error-"]').forEach(function(a){a.innerHTML=""});if(1==b.success&&a.unitOfMeasurementMaintenanceGrid){a.setFormValues(b.values);a.addDimensionBtn._setDisabledAttr(!1);var d=a.filterSelectStore=new dojo.data.ItemFileReadStore({clearOnClose:!0,url:"unitOfMeasurement/getDimensionSelectList/uid/"+b.values.id});a.dimensionFilterSelect.store.close();a.dimensionFilterSelect.set("store",d);a.dimensionFilterSelect.set("value","");
b=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"unitOfMeasurement/getUnitOfMeasurementDimensions/id/"+b.values.id});a.dimensionGrid.store.close();a.dimensionGrid.set("store",b);a.dimensionGrid._refresh();a.unitOfMeasurementMaintenanceGrid.refreshGrid()}else for(d in b=b.errors,b)a["uom_"+a.uomType+"_error-"+d]&&v.set(a["uom_"+a.uomType+"_error-"+d],b[d]);c.hide()},error:function(a){c.hide()}})})}});return h("buildspace.apps.UnitOfMeasurementMaintenance.UnitOfMeasurementMaintenanceFormContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,resource:null,param:null,postCreate:function(){this.inherited(arguments);var a=this,b=new m,c=dijit.byId("unitOfMeasurementMaintenance-stackContainer-"+a.param);c&&dijit.byId("unitOfMeasurementMaintenance-stackContainer-"+a.param).destroyRecursive();c=a.stackContainer=new dijit.layout.StackContainer({style:"width:100%;height:100%;",region:"center",id:"unitOfMeasurementMaintenance-stackContainer-"+a.param});
b=this.unitOfMeasurementMaintenanceGrid=new t({param:a.param,gridOpts:{store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"unitOfMeasurement/getUnitOfMeasurements/type/"+a.param}),unitOfMeasurementFormContainer:this,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:e.name,field:"name",width:"auto"},{name:e.symbol,field:"symbol",width:"80px",styles:"text-align:center;"},{name:e.dimensions,field:"dimensions",width:"200px"},{name:e.lastUpdated,
field:"updated_at",width:"120px",styles:"text-align:center;"}],onRowDblClick:function(a){this.unitOfMeasurementFormContainer.editUnitOfMeasurement(a.rowIndex)}}});b=new dijit.layout.ContentPane({title:e.unitOfMeasurementList,content:b});c.addChild(b);b=new dijit.layout.StackController({region:"top",containerId:"unitOfMeasurementMaintenance-stackContainer-"+a.param});b=new dijit.layout.ContentPane({style:"padding: 0px; overflow: hidden;",baseClass:"breadCrumbTrail",region:"top",content:b});a.addChild(c);
a.addChild(b);dojo.subscribe("unitOfMeasurementMaintenance-stackContainer-"+a.param+"-selectChild","",function(b){var c=dijit.byId("unitOfMeasurementMaintenance-stackContainer-"+a.param);if(c){var d=c.getChildren();b=dojo.indexOf(d,dijit.byId(b.id));for(b+=1;d.length>b;)c.removeChild(d[b]),d[b].destroyRecursive(!0),b+=1}})},makePane:function(a,b){var c=dijit.byId("unitOfMeasurementMaintenance-stackContainer-"+this.param),d=new dijit.layout.ContentPane({title:a,content:b});c.addChild(d);c.selectChild(d)},
unitOfMeasurementFormContainer:function(a,b){var c=this.unitOfMeasurementUpdateForm=new x({region:"center",formValues:a,uomType:this.param,unitOfMeasurementMaintenanceGrid:this.unitOfMeasurementMaintenanceGrid}),d=new l({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});d.addChild(new k({label:e.save,iconClass:"icon-16-container icon-16-save",style:"outline:none!important;",onClick:dojo.hitch(this.unitOfMeasurementUpdateForm,"submit")}));var f=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",
baseClass:"form",gutters:!1,region:"center"});f.addChild(d);f.addChild(c);this.makePane(b?e.addUnitOfMeasurement:e.editUnitOfMeasurement,f)},addUnitOfMeasurement:function(){var a=this,b=this.param,c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});c.show().then(function(){dojo.xhrGet({url:"unitOfMeasurement/unitOfMeasurementForm/t/"+b,handleAs:"json"}).then(function(b){c.hide();a.unitOfMeasurementFormContainer(b,!0)})})},editUnitOfMeasurement:function(a){var b=this,c=b.unitOfMeasurementMaintenanceGrid.grid.getItem(a);
if(c.id==buildspace.constants.GRID_LAST_ROW)return!1;var d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});c&&d.show().then(function(){dojo.xhrGet({url:"unitOfMeasurement/unitOfMeasurementForm/id/"+c.id,handleAs:"json"}).then(function(a){d.hide();b.unitOfMeasurementFormContainer(a,!1)})})},deleteUnitOfMeasurement:function(a){var b=this,c=b.unitOfMeasurementMaintenanceGrid.grid.getItem(a),d=buildspace.dialog.indeterminateProgressBar({title:e.deleting+". "+e.pleaseWait+"..."});
if(c&&!isNaN(parseInt(c.id[0])))return buildspace.dialog.confirm(e.confirmationUnit,"<div>"+e.firstLevelUnitDialogMsg+"</div>",75,320,function(){d.show().then(function(){dojo.xhrPost({url:"unitOfMeasurement/unitOfMeasurementDelete",content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(a){a.success?(b.unitOfMeasurementMaintenanceGrid.grid.store.deleteItem(c),b.unitOfMeasurementMaintenanceGrid.grid.store.save()):buildspace.dialog.alert(e.itemCannotBeDeleted,e.cannotDeleteUom,60,
300);b.unitOfMeasurementMaintenanceGrid.grid.disableToolbarButtons(!0);d.hide()},error:function(a){d.hide()}})})})}})});
