define("buildspace/apps/ProjectManagement/ImportProjectScheduleDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/on dojo/keys dojo/dom-style dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./templates/projectScheduleUploadForm.html dojo/text!./templates/projectScheduleImportInfo.html dojo/i18n!buildspace/nls/ProjectManagement dojox/form/Uploader".split(" "),
function(f,h,z,A,B,C,D,k,g,r,t,l,m,n,p,q,u,v,b,E){var w=f("buildspace.apps.ProjectManagement.ProjectScheduleImportInfo",[m,n,p,q],{templateString:v,baseClass:"buildspace-form",region:"center",style:"border:none;padding:5px;overflow:auto;",containerDialog:null,project:null,projectScheduleInfo:null,subPackage:null,importUrl:null,filename:null,filePath:null,subPackageTitle:"",nls:b,buildRendering:function(){this.projectScheduleInfo.title=this.projectScheduleInfo.title[0];this.projectScheduleInfo.start_date=
this.projectScheduleInfo.start_date[0];this.projectScheduleInfo.timezone=this.projectScheduleInfo.timezone[0];this.subPackage&&(this.subPackageTitle=this.subPackage.title[0]);this.inherited(arguments)},startup:function(){this.inherited(arguments);this.subPackage?g.set(this.scheduleFormSubPackageName,"display",""):g.set(this.scheduleFormSubPackageName,"display","none");this.importProjectScheduleForm.setFormValues({exclude_saturdays:this.projectScheduleInfo.exclude_saturdays[0],exclude_sundays:this.projectScheduleInfo.exclude_sundays[0],
_csrf_token:this.project._csrf_token[0]})},"import":function(a){var d=dojo.formToObject(this.importProjectScheduleForm.id),c=this;this.containerDialog&&this.containerDialog.hide();var e=buildspace.dialog.indeterminateProgressBar({title:b.savingData+". "+b.pleaseWait+"..."});e.show().then(function(){h.mixin(d,{pid:c.project.id,filename:c.filename,path:c.filePath,psd:a});c.subPackage&&h.mixin(d,{spid:c.subPackage.id});dojo.xhrPost({url:c.importUrl,content:d,handleAs:"json",load:function(a){e.hide();
a.success?c.reloadProjectScheduleList():buildspace.dialog.alert(b.error,"<div>"+a.errorMsg+"</div>",80,280)},error:function(a){e.hide()}})})},reloadProjectScheduleList:function(){var a=dijit.byId("projectManagement-projectScheduleListGrid");a&&a.reload()},close:function(){},onCancel:function(){}}),x=f("buildspace.apps.ProjectManagement.FileImportDialog",dijit.Dialog,{title:b.importProjectSchedule,style:"padding:0px;margin:0px;",project:null,subPackage:null,importUrl:null,projectScheduleInfo:null,
filename:null,filePath:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){g.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==k.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:740px;height:325px;",gutters:!1}),
d=w({project:this.project,subPackage:this.subPackage,projectScheduleInfo:this.projectScheduleInfo,importUrl:this.importUrl,filename:this.filename,filePath:this.filePath,containerDialog:this}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));c.addChild(new dijit.ToolbarSeparator);var e=new t({style:"display: none;"});
e.addChild(new l({label:b.useProjectStartDate,onClick:dojo.hitch(d,"import",!0)}));e.addChild(new l({label:b.useProjectScheduleStartDate,onClick:dojo.hitch(d,"import",!1)}));c.addChild(new r({label:b["import"],iconClass:"icon-16-container icon-16-import",dropDown:e}));a.addChild(d);a.addChild(c);return a}}),y=f("buildspace.apps.ProjectManagement.ProjectScheduleUploadForm",[m,n,p,q],{templateString:u,title:b.importProjectSchedule,baseClass:"buildspace-form",region:"center",dialogObj:null,project:null,
subPackage:null,nls:b,uploadUrl:"projectManagement/projectScheduleUpload",importUrl:"projectManagement/projectScheduleImport",style:"padding:5px;overflow:auto;",postCreate:function(){this.inherited(arguments);var a=this.fileUploaderNode;a.on("Complete",dojo.hitch(this,"uploadComplete"));a.on("Begin",dojo.hitch(this,"uploadBegin"))},startup:function(){this.inherited(arguments)},uploadBegin:function(a){this.pb=buildspace.dialog.indeterminateProgressBar({title:b.uploadingData+". "+b.pleaseWait+"..."});
this.pb.show()},uploadComplete:function(a){this.pb&&(this.dialogObj.hide(),this.pb.hide(),a.success?(self.importGridDialog=new x({project:this.project,subPackage:this.subPackage,importUrl:this.importUrl,projectScheduleInfo:a.projectScheduleInfo,filename:a.filename,filePath:a.filePath})).show():buildspace.dialog.alert(b.error,"<div>"+a.errorMsg+"</div>",80,280))},close:function(){},onCancel:function(){}});return f("buildspace.apps.ProjectManagement.ImportProjectScheduleDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",
title:b.importProjectSchedule,project:null,subPackage:null,buildRendering:function(){var a=this.createForm();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){g.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==k.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createForm:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:400px;height:80px;",
gutters:!1}),d=new y({dialogObj:this,project:this.project,subPackage:this.subPackage}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));a.addChild(c);a.addChild(d);return a}})});
