define("buildspace/apps/ProjectManagement/ProjectScheduleList","dojo/_base/declare dojo/_base/lang dojo/dom-style dojox/grid/EnhancedGrid dijit/PopupMenuItem dijit/MenuSeparator dojo/_base/event dojo/keys buildspace/widget/grid/cells/Formatter dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem ./ExportProjectScheduleDialog ./ProjectScheduleForm dojo/i18n!buildspace/nls/ProjectManagement".split(" "),function(f,y,k,l,z,A,B,m,n,r,t,p,u,q,d){var v=f("buildspace.apps.ProjectManagement.ProjectScheduleListGrid",
l,{project:null,workArea:null,style:"border:none;",region:"center",keepSelection:!0,rowSelector:"0px",currencySetting:buildspace.currencyAbbreviation,canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);this.on("RowClick",function(b){(b=a.getItem(b.rowIndex))&&0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)})},dodblclick:function(a){this.onRowDblClick(a)},onRowDblClick:function(a){this.inherited(arguments);var b=this.getItem(a.rowIndex);if(0<b.id[0]){var c=
this;dojo.xhrGet({url:"projectManagement/getNonWorkingDays",content:{id:b.id[0]},handleAs:"json"}).then(function(a){buildspace.app.launch({__children:[],icon:"project_sub_package",id:c.project.id+"-"+b.id[0]+"-project_management-Gantt",is_app:!0,level:0,sysname:"Gantt",title:"Gantt"},{project:c.project,projectSchedule:b,nonWorkingDays:a})})}},deleteRow:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});buildspace.dialog.confirm(d.confirmation,
d.deleteProjectScheduleAndAllData,90,310,function(){c.show().then(function(){dojo.xhrPost({url:"projectManagement/projectScheduleDelete",content:{id:a.id,_csrf_token:a._csrf_token},handleAs:"json",load:function(d){if(d.success){d=b.workArea.getChildren();for(var g in d)if("object"==typeof d[g].pane_info&&d[g].pane_info.id==a.id+"-project_schedule_tab"){b.workArea.removeChild(d[g]);break}b.reload()}c.hide();b.selection.clear();b.disableToolbarButtons(!0)},error:function(a){c.hide();b.selection.clear();
b.disableToolbarButtons(!0)}})})})},disableToolbarButtons:function(a){var b=dijit.byId("ProjectManagement"+this.project.id+"-ScheduleListDeleteRow-button"),c=dijit.byId("ProjectManagement"+this.project.id+"-ScheduleListEditRow-button"),d=dijit.byId("ProjectManagement"+this.project.id+"-ExportRow-button");b&&b._setDisabledAttr(a);c&&c._setDisabledAttr(a);d&&d._setDisabledAttr(a)},reload:function(){this.store.close();this._refresh()}}),w=function(a,b){return buildspace.getProjectScheduleTypeText(parseInt(a))},
h=f("buildspace.apps.ProjectManagement.ProjectScheduleFormDialog",dijit.Dialog,{style:"padding:0;margin:0;",title:null,project:null,projectSchedule:null,subPackage:null,buildRendering:function(){var a=this.createForm();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){k.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==m.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},
createForm:function(){var a=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:740px;height:325px;",gutters:!1});var b=this.projectSchedule?new q({projectScheduleId:this.projectSchedule.id,project:this.project,subPackage:0<this.projectSchedule.sub_package_id?{id:this.projectSchedule.sub_package_id,name:this.projectSchedule.sub_package_name}:null,subPackageName:0<this.projectSchedule.sub_package_id?this.projectSchedule.sub_package_name:null,dialogWidget:this}):new q({project:this.project,
subPackage:this.subPackage,subPackageName:this.subPackage?this.subPackage.title:null,dialogWidget:this});var c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({id:"ProjectManagement"+this.project.id+"-ImportRow-button",label:d.importFromEPMFile,iconClass:"icon-16-container icon-16-import",style:"outline:none!important;",onClick:dojo.hitch(b,"importProjectSchedule")}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.save,
iconClass:"icon-16-container icon-16-save",style:"outline:none!important;",onClick:dojo.hitch(b,"save")}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));a.addChild(c);a.addChild(b);return a}}),x=f("buildspace.apps.ProjectManagement.SubPackageListDialog",dijit.Dialog,{style:"padding:0;margin:0;",title:null,project:null,buildRendering:function(){var a=
this.createGrid();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){k.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==m.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createGrid:function(){var a=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:680px;height:350px;",gutters:!1}),b=this,c=new n;c=new l({style:"border:none;",region:"center",
structure:[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.title,field:"title",width:"auto"}],store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"postContractSubPackage/getSubPackageList/projectId/"+this.project.id}),canSort:function(a){return!1},onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id[0]&&null!==a.title[0]&&""!==a.title[0]&&(a=new h({title:d.createScheduleForSubPackage,project:b.project,subPackage:a}),b.hide(),
a.show())}});var e=new dijit.Toolbar({region:"top",style:"outline:none!important;border-bottom:none;padding:2px;overflow:hidden;"});e.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));a.addChild(e);a.addChild(c);return a}});return f("buildspace.apps.ProjectManagement.ProjectScheduleList",dijit.layout.BorderContainer,{region:"center",style:"padding:0;margin:0;border:none;width:100%;height:100%;",
gutters:!1,project:null,workArea:null,grid:null,postCreate:function(){this.inherited(arguments);var a=this,b=new n,c=this.grid=v({id:"projectManagement-projectScheduleListGrid",project:this.project,workArea:this.workArea,structure:[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:d.title,field:"title",width:"auto"},{name:d.type,field:"type",width:"120px",styles:"text-align: center;",formatter:w}],store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,
url:"projectManagement/getProjectScheduleList/id/"+this.project.id})});b=new dijit.Toolbar({region:"top",style:"outline:none!important;border:none;padding:2px;width:100%;"});var e=new t({style:"display: none;"});e.addChild(new p({label:d.createScheduleForMainProject,onClick:function(b){(new h({title:d.createScheduleForMainProject,project:a.project})).show()}}));e.addChild(new p({label:d.createScheduleForSubPackage,onClick:function(b){(new x({title:d.createScheduleForSubPackage+" ("+d.subPackageList+
")",project:a.project})).show()}}));b.addChild(new r({id:this.project.id+"ImportDropDownRow-button",label:d.createProjectSchedule,iconClass:"icon-16-container icon-16-add",dropDown:e}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"ProjectManagement"+this.project.id+"-ScheduleListEditRow-button",label:d.edit,iconClass:"icon-16-container icon-16-edit",disabled:!0,style:"outline:none!important;",onClick:function(){if(-1<c.selection.selectedIndex){var b=c.getItem(c.selection.selectedIndex);
0<b.id[0]&&(new h({title:buildspace.truncateString(b.title[0],35),project:a.project,projectSchedule:b})).show()}}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"ProjectManagement"+this.project.id+"-ScheduleListDeleteRow-button",label:d.delete,iconClass:"icon-16-container icon-16-delete",disabled:!0,style:"outline:none!important;",onClick:function(){if(-1<c.selection.selectedIndex){var a=c.getItem(c.selection.selectedIndex);0<a.id[0]&&c.deleteRow(a)}}}));b.addChild(new dijit.ToolbarSeparator);
b.addChild(new dijit.form.Button({id:"ProjectManagement"+this.project.id+"-ExportRow-button",label:d.export,iconClass:"icon-16-container icon-16-export",disabled:!0,style:"outline:none!important;",onClick:function(){if(-1<c.selection.selectedIndex){var a=c.getItem(c.selection.selectedIndex);0<a.id[0]&&(new u({projectSchedule:a,exportUrl:"projectManagement/projectScheduleExport"})).show()}}}));this.addChild(b);this.addChild(c)}})});
