define("dojo/_base/declare dojo/_base/lang dojo/dom-style dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dojo/_base/array dijit/_WidgetsInTemplateMixin dijit/form/Form dijit/form/Button dijit/form/ValidationTextBox dijit/form/CheckBox dijit/Toolbar dijit/TitlePane dojox/calendar/Calendar dijit/Calendar dojo/i18n!buildspace/nls/ProjectCalendarMaintenance dojo/text!./templates/eventForm.html dojo/store/Observable dojo/store/Memory dojo/data/ObjectStore dojo/store/DataStore dojo/data/ItemFileWriteStore dijit/form/Select dojo/html dojo/date".split(" "),
function(f,h,g,k,l,m,D,n,E,F,G,H,I,p,q,r,e,t,u,v,w,x,y,z,J,K){var A=f("buildspace.apps.ProjectManagement.ProjectCalendarMaintenanceForm",[k,l,m,n],{templateString:t,baseClass:"buildspace-form",region:"center",calendarObj:null,formContainerObj:null,nls:e,_csrf_token:null,style:"overflow:auto;",postCreate:function(){this.inherited(arguments);var a=this;this.isHolidayCheckBox.set("checked",!0);dojo.xhrGet({url:"projectManagementCalendar/getEventTypeOptions",handleAs:"json",load:function(b){a.eventForm.setFormValues(b.formValues);
a.eventTypeSelect=(new z({required:!0,name:"project_management_calendar[event_type]",style:"width:100%;padding:2px 0!important;margin-top:3px;",store:new w({objectStore:new v({data:b.eventTypeOptions})}),onChange:function(b){a.toogleIsHolidayDiv(b)}})).placeAt(a.eventTypeSelectDivNode)}});this.evtStartDate.on("change",function(){a.evtEndDate.constraints.min=this.get("value")});this.evtEndDate.on("change",function(){a.evtStartDate.constraints.max=this.get("value")});this.evtStartDate.set("value",new Date);
this.evtEndDate.set("value",new Date);this.saveItemButton.on("click",function(b){a.formContainerObj.save()});this.deleteItemButton.on("click",function(b){a.formContainerObj.deleteEvent()})},toogleIsHolidayDiv:function(a){a==buildspace.constants.EVENT_TYPE_OTHER?g.set(this.isHolidayDiv,"display","block"):g.set(this.isHolidayDiv,"display","none")}}),B=f("buildspace.apps.ProjectManagement.Calendar",q,{isItemEditable:function(a,b){return!1},isItemResizeEnabled:function(a,b){return this.isItemEditable(a,
b)&&a.resizeEnabled},isItemMoveEnabled:function(a,b){return this.isItemEditable(a,b)&&a.moveEnabled}});return f("buildspace.apps.ProjectManagement.ProjectCalendarMaintenanceFormContainer",dijit.layout.BorderContainer,{style:"padding:0;margin:0;width:100%;height:100%;border:0px;",gutters:!0,design:"sidebar",resource:null,project:null,postCreate:function(){this.inherited(arguments);var a=this,b=this.calendar=new B({store:new u(new x({store:new y({clearOnClose:!0,url:"projectManagementCalendar/getEventsByProjectId/pid/"+
this.project.id[0]})})),dateInterval:"month",cssClassFunc:function(a){return a.calendar},style:"position:absolute;left:10px;top:10px;bottom:30px;right:10px;"}),c=this.form=new A({formContainerObj:this}),b=new dijit.layout.ContentPane({content:b,region:"center",style:"border:0px;"}),d=new dijit.layout.ContentPane({splitter:!1,region:"leading",style:"border:0px;padding:10px;"}),C=this.datePicker=new r({value:new Date,style:"width:100%;",minDate:null,maxDate:null,getClassForDate:function(a,b){if(this.minDate&&
this.maxDate){var d=this.dateModule;if(0<=d.compare(a,this.minDate)&&0>=d.compare(a,this.maxDate))return"Highlighted"}return null}}),c=new p({title:e.eventProperties,content:c,region:"center",style:"padding:0;width:250px;margin-top: 10px;"});this.datePicker.on("change",function(b){b=a.datePicker.get("value");a.calendar.set("date",b)});d.addChild(C);d.addChild(c);this.addChild(b);this.addChild(d);this.configureCalendar()},onShow:function(){var a=this.datePicker.get("value");this.calendar.set("date",
a)},selectionChanged:function(a){var b=null==a;this.editedItem=b?null:h.mixin({},a);b?this.resetForm():(this.form.eventForm.setFormValues({"project_management_calendar[description]":a.summary,"project_management_calendar[start_date]":a.startTime,"project_management_calendar[end_date]":a.endTime,id:a.id}),this.form.isHolidayCheckBox.set("checked",a.isHoliday),this.form.eventTypeSelect.set("value",a.eventType),this.form.deleteItemButton.set("disabled",!1))},resetForm:function(){this.form.eventForm.setFormValues({"project_management_calendar[description]":"",
"project_management_calendar[start_date]":new Date,"project_management_calendar[end_date]":new Date,id:-1});this.form.isHolidayCheckBox.set("checked",!0);this.form.eventTypeSelect.set("value",buildspace.constants.EVENT_TYPE_PUBLIC);this.form.deleteItemButton.set("disabled",!0)},configureCalendar:function(){var a=this,b=this.calendar,c=this.datePicker.get("value");this.datePicker.set("value",b.get("date"));b.on("change",function(b){(b=b.newValue)&&b.editable?a.selectionChanged(b):a.resetForm()});b.on("timeIntervalChange",
function(b){var c=b.startTime;b=b.endTime;a.datePicker.set("currentFocus",c,!1);a.datePicker.set("minDate",c);a.datePicker.set("maxDate",b)});this.calendar.set("date",c)},makePane:function(a,b){var c=dijit.byId("ProjectCalendarMaintenance-stackContainer"),d=new dijit.layout.ContentPane({title:a,id:"GlobalCalendarForm",content:b});c.addChild(d);c.selectChild(d)},deleteEvent:function(){var a=this,b=dojo.formToObject(a.form.eventForm.id),c=buildspace.dialog.indeterminateProgressBar({title:e.deletingData+
". "+e.pleaseWait+"..."});b.id&&c.show().then(function(){dojo.xhrPost({url:"projectManagementCalendar/eventDelete",content:{id:b.id},handleAs:"json",load:function(d){d.success&&(a.calendar.store.remove(b.id),c.hide())},error:function(a){c.hide()}})})},save:function(){var a=this.form,b=dojo.formToObject(a.eventForm.id),c=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."});b["project_management_calendar[project_structure_id]"]=this.project.id[0];if(a.eventForm.validate()){var d=
this.calendar.store;c.show().then(function(){dojo.xhrPost({url:"projectManagementCalendar/eventAdd",content:b,handleAs:"json",load:function(b){b.success&&(b=b.values,a.eventForm.setFormValues({id:b.id}),d.put(b),c.hide())},error:function(a){c.hide()}})})}}})});
