(function(){define("buildspace/apps/PurchaseOrder/PurchaseOrderViewOnlyForm/PurchaseOrderViewOnlyForm","dojo/_base/declare dojo/_base/lang dojo/request dojo/dom-style dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/layout/BorderContainer dijit/Editor dijit/_editor/plugins/FontChoice dijit/_editor/plugins/AlwaysShowToolbar dijit/Toolbar dijit/form/FilteringSelect dijit/form/TextBox dijit/form/Textarea dijit/form/CheckBox dijit/form/RadioButton dijit/form/Select dijit/form/Button dojo/store/Memory dojox/form/Manager ../SupplierList/SupplierSelectionGridDialog dojo/text!./templates/purchaseOrderViewOnlyForm.html dojo/i18n!../../../nls/PurchaseOrder".split(" "),
function(k,p,l,m,q,r,t,u,v,w,C,D,x,y,E,F,G,H,n,g,h,I,z,A,e){var B=k("buildspace.apps.PurchaseOrder.PurchaseOrderViewOnlyForm",[q,r,t,u],{baseClass:"buildspace-form",poId:-1,templateString:A,region:"center",style:"overflow: auto;",formInfo:null,signatureEditor:null,subPackageSelections:[],poStatusSelections:[],currencySelections:[],nls:e,postCreate:function(){var a;this.inherited(arguments);0<this.subPackageSelections.length&&(this["subCon-"+this.poId].innerHTML=null,a=new h({idProperty:"id",data:this.subPackageSelections}),
(new n({name:"sub_package_id",store:a,labelAttr:"name",maxHeight:-1,style:"width: 180px;padding:2px!important;"})).placeAt(this["subCon-"+this.poId]));a=new h({idProperty:"id",data:this.poStatusSelections});(new n({name:"purchase_order_information[status]",store:a,labelAttr:"name",maxHeight:-1,style:"width: 180px;padding:2px!important;"})).placeAt(this["statusSelect-"+this.poId]);a=new h({idProperty:"id",data:this.currencySelections});(new y({name:"purchase_order_information[currency_id]",store:a,
labelAttr:"name",maxHeight:-1,style:"width: 173px;padding:2px!important;"})).placeAt(this["currencySelect-"+this.poId]);this.signatureEditor=(new w({name:"purchase_order_information[signature]",height:"25%",plugins:"fontSize | bold italic underline | indent outdent justifyLeft justifyCenter justifyRight".split(" "),style:"width:53.5%;font:81.25% arial,helvetica,sans-serif;border:1px solid #d3d3d3;",value:this.formInfo["purchase_order_information[signature]"]})).placeAt(this["signatureTextBox-"+this.poId])},
startup:function(){this.inherited(arguments);this["rfqForm-"+this.poId].setFormValues(this.formInfo)},clearErrorMsg:function(){var a,c,b,f,d;c="ref quo_ref attention_to company_address_1 company_address_2 company_address_3 supplier_address_1 supplier_address_2 supplier_address_3 ship_to_1 ship_to_2 ship_to_3 note".split(" ");d=[];b=0;for(f=c.length;b<f;b++)a=c[b],(a=dojo.byId("error-purchase_order_information_"+a))?(a.innerHTML=null,d.push(m.set(a,"display","none"))):d.push(void 0);return d},fillErrorMsgs:function(a){var c,
b,f,d;d=[];for(f in a)c=a[f],(b=dojo.byId("error-purchase_order_information_"+f))?(b.innerHTML=c,d.push(m.set(b,"display","block"))):d.push(void 0);return d},save:function(){var a,c,b;b=this;if(!this["rfqForm-"+this.poId].validate())return!1;a=dojo.formToObject(this["rfqForm-"+this.poId].id);c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});p.mixin(a,{poId:b.poId,"purchase_order_information[signature]":b.signatureEditor.value});c.show();this.clearErrorMsg();return l.post("purchaseOrder/updateWorkAreaInformation",
{data:a,handleAs:"json"}).then(function(a){a.success||b.fillErrorMsgs(a.errorMsgs);return c.hide()},function(a){return c.hide()})}});return k("buildspace.apps.PurchaseOrder.PurchaseOrderViewOnlyForm.PurchaseOrderViewOnlyContainer",v,{poId:-1,style:"padding:0px;margin:0px;width:100%;height:height:100%;",gutters:!1,data:null,postCreate:function(){var a,c,b;this.inherited(arguments);c=this;a=new B({poId:c.poId,formInfo:c.data.purchaseOrderForm,subPackageSelections:c.data.subPackageSelections,poStatusSelections:c.data.poStatusSelections,
currencySelections:c.data.currencySelections});b=new x({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});b.addChild(new g({label:e.save,iconClass:"icon-16-container icon-16-save",onClick:function(){return a.save()}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new g({label:e.assignSupplier,iconClass:"icon-16-container icon-16-add",onClick:function(){var b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});b.show();return l.get("purchaseOrder/getCompanyListing",
{query:{poId:c.poId},handleAs:"json"}).then(function(d){(new z({title:e.addSupplierToPO,poId:c.poId,poForm:a,supplierListContainer:c,data:d})).show();return b.hide()},function(a){return b.hide()})}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new g({label:e.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return window.open("PurchaseOrderPrintout/"+c.poId+"/"+c.data.purchaseOrderForm.printing_csrf_token,"_blank").focus()}}));this.addChild(b);this.addChild(a)}})})}).call(this);
