define("buildspace/apps/MasterCostData/Breakdown","dojo/_base/declare dojo/_base/lang dojox/grid/EnhancedGrid dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/cells/Formatter dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dijit/focus dojo/when dojo/aspect ./WorkCategoryGrid ./PrimeCostSumGrid ./PrimeCostRateGrid buildspace/widget/grid/cells/Textarea dojo/i18n!buildspace/nls/CostData".split(" "),function(q,t,u,v,F,G,H,I,r,J,K,w,x,y,L,e){var B=q("buildspace.apps.MasterCostData.BreakdownGrid",
u,{masterCostData:null,style:"border:none;",region:"center",keepSelection:!0,rowSelector:"0px",escapeHTMLInData:!1,borderContainerWidget:null,addUrl:"masterCostData/addNewProjectOverallCostingItem",updateUrl:"masterCostData/updateItem",constructor:function(a){this.inherited(arguments);this.rearranger=v(this,{})},canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);this.on("RowClick",function(b){b.cell&&(b=this.getItem(b.rowIndex),0<b.id[0]?a.enableToolbarButtons(!0):
b.id[0]===buildspace.constants.GRID_LAST_ROW&&(a.enableToolbarButtons(!0),dijit.byId(a.masterCostData.id+"-delete-button")._setDisabledAttr(!0)))})},enableToolbarButtons:function(a){dijit.byId(this.masterCostData.id+"-delete-button")._setDisabledAttr(!a);dijit.byId(this.masterCostData.id+"-add-button")._setDisabledAttr(!a)},dodblclick:function(a){this.onRowDblClick(a)},doApplyCellEdit:function(a,b,c){var d=this,f=d.getItem(b),g=d.store;if("description"==c){if(a!==f[c][0]){var n=buildspace.dialog.indeterminateProgressBar({title:e.savingData+
". "+e.pleaseWait+"..."}),k={id:f.id,attr_name:c,val:a,master_cost_data_id:d.masterCostData.id,_csrf_token:f._csrf_token?f._csrf_token:null},h=this.updateUrl;if(f.id==buildspace.constants.GRID_LAST_ROW){h=0<b?d.getItem(b-1):!1;var z=d.getItem(b);t.mixin(k,{prev_item_id:h?h.id:0,current_id:z.id});h=this.addUrl}var A=function(l,p){for(var m in l)f.hasOwnProperty(m)&&m!=p._getIdentifierAttribute()&&p.setValue(f,m,l[m]);p.save()};k={url:h,content:k,handleAs:"json",load:function(l){if(l.success){0<f.id?
A(l.data,g):(g.deleteItem(f),g.save(),dojo.forEach(l.items,function(m){g.newItem(m)}),g.save(),d.enableToolbarButtons(!1));var p=d.getCellByField(c);window.setTimeout(function(){d.focus.setFocusIndex(b,p.index)},10);n.hide()}},error:function(l){n.hide()}};n.show();dojo.xhrPost(k)}d.inherited(arguments)}},canEdit:function(a,b){return!0},reload:function(){this.store.save();this.store.close();this.sort();this._refresh()}}),C=function(a,b,c){a=this.grid.getItem(b);"row_separator"==a.id[0]&&c.customClasses.push("invalidTypeItemCell");
return 0<a.id[0]||a.id[0]==buildspace.constants.GRID_LAST_ROW?parseInt(b)-3:null},D=function(a,b,c){"row_separator"==this.grid.getItem(b).id[0]&&c.customClasses.push("invalidTypeItemCell");return a},E=function(a,b,c){b=this.grid.getItem(b);"row_separator"==b.id[0]&&c.customClasses.push("invalidTypeItemCell");return b.id[0]!=buildspace.constants.GRID_LAST_ROW&&"row_separator"!=b.id[0]?buildspace.apps.MasterCostData.getItemTypeText(a):""};return q("buildspace.apps.MasterCostData.BreakdownContainer",
dijit.layout.BorderContainer,{region:"center",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,masterCostData:null,grid:null,postCreate:function(){this.inherited(arguments);var a=this.createStackContainer(),b=this.createBreakdownGrid();b=new dijit.layout.ContentPane({style:"padding:0px;border:none;width:100%;height:100%;",region:"center",content:b,grid:b});var c=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",gutters:!1,title:buildspace.truncateString(e.overallProjectCosting,
60)});c.addChild(this.createToolbar());c.addChild(b);a.addChild(c)},createStackContainer:function(){var a="masterCostDataBreakdown"+this.masterCostData.id+"-stackContainer",b=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:a});dojo.subscribe(a+"-selectChild","",function(d){var f=dijit.byId(a);if(f){var g=f.getChildren();d=dojo.indexOf(g,d);d+=1;if(g.length>d)for(;g.length>d;)f.removeChild(g[d]),g[d].destroyDescendants(),g[d].destroyRecursive(),
d+=1}});var c=new dijit.layout.StackController({region:"top",containerId:"masterCostDataBreakdown"+this.masterCostData.id+"-stackContainer"});c=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"masterCostDataBreakdown"+this.masterCostData.id+"-controllerPane",content:c});this.addChild(b);this.addChild(c);return b},createToolbar:function(){var a=this,b=new dijit.Toolbar({region:"top",style:"outline:none!important;border:none;padding:2px;width:100%;"});
b.addChild(new dijit.form.Button({id:this.masterCostData.id+"-add-button",label:e.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<a.grid.selection.selectedIndex?!1:!0,onClick:function(){-1<a.grid.selection.selectedIndex&&a.addRow(a.grid.selection.selectedIndex)}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:this.masterCostData.id+"-delete-button",label:e.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:!0,style:"outline:none!important;",
onClick:function(){if(-1<a.grid.selection.selectedIndex){var c=a.grid.getItem(a.grid.selection.selectedIndex);0<c.id[0]&&a.deleteRow(c)}}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({label:e.refresh,iconClass:"icon-16-container icon-16-reload",style:"outline:none!important;",onClick:function(){a.grid.reload()}}));return b},createBreakdownGrid:function(){var a=this;a.grid=B({masterCostData:a.masterCostData,borderContainerWidget:a,structure:[{name:"No.",field:"count",
width:"30px",styles:"text-align:center;",formatter:C},{name:e.description,field:"description",width:"auto",cellType:"buildspace.widget.grid.cells.Textarea",editable:!0,formatter:D},{name:e.type,field:"type",width:"150px",styles:"text-align: center;",formatter:E}],onRowDblClick:function(b){b=this.getItem(b.rowIndex);switch(b.type[0]){case buildspace.apps.MasterCostData.ItemTypes.STANDARD:0<b.id[0]&&a.createWorkCategoryGrid(b);break;case buildspace.apps.MasterCostData.ItemTypes.PRIME_COST_SUM:a.createPrimeCostSumGrid(b);
break;case buildspace.apps.MasterCostData.ItemTypes.PRIME_COST_RATE:a.createPrimeCostRateGrid(b,1)}},store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"masterCostData/getBreakdown/id/"+this.masterCostData.id})});return a.grid},createWorkCategoryGrid:function(a){a=new w({title:buildspace.truncateString(a.description,60),stackContainer:this.stackContainer,masterCostData:this.masterCostData,projectCostingItem:{id:a.id,_csrf_token:a._csrf_token}});this.stackContainer.addChild(a);this.stackContainer.selectChild(a)},
createPrimeCostSumGrid:function(a){a=new x({title:buildspace.truncateString(a.description,60),stackContainer:this.stackContainer,masterCostData:this.masterCostData});this.stackContainer.addChild(a);this.stackContainer.selectChild(a)},createPrimeCostRateGrid:function(a,b){0<a.id||(a.id=0);a=new y({title:buildspace.truncateString(a.description,60),stackContainer:this.stackContainer,masterCostData:this.masterCostData,gridCreator:this,parentItem:a,level:b});this.stackContainer.addChild(a);this.stackContainer.selectChild(a)},
addRow:function(a){r.curNode.blur();r.curNode=null;var b=this,c=buildspace.dialog.indeterminateProgressBar({title:e.addingRow+". "+e.pleaseWait+"..."}),d=b.grid.store,f=b.grid.getItem(a),g=0<a?b.grid.getItem(a-1).id:0,n={master_cost_data_id:b.masterCostData.id,prev_item_id:g,current_id:f.id,_csrf_token:f._csrf_token};c.show().then(function(){dojo.xhrPost({url:b.grid.addUrl,content:n,handleAs:"json",load:function(k){k.success&&dojo.forEach(k.items,function(h){0<h.id&&(h=d.newItem(h),d.save(),h=b.grid.getItemIndex(h),
b.grid.rearranger.moveRows([h],a),b.grid.selection.clear())});window.setTimeout(function(){b.grid.selection.setSelected(a,!0);b.grid.focus.setFocusIndex(a,1)},30);c.hide()},error:function(k){b.grid.selection.clear();b.grid.enableToolbarButtons(!0);c.hide()}})})},deleteRow:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:e.deleting+". "+e.pleaseWait+"..."});buildspace.dialog.confirm(e.confirmation,e.confirmationMessage+"<br/>"+e.willDeleteAllChildItems+"<br/>"+e.cannotBeUndone,
80,300,function(){c.show().then(function(){dojo.xhrPost({url:"masterCostData/deleteItem",content:{id:a.id,_csrf_token:a._csrf_token},handleAs:"json",load:function(d){d.success?(b.grid.store.deleteItem(a),b.grid.store.save(),b.grid.reload()):buildspace.dialog.alert(e.cannotBeDeleted,d.errorMsg,80,300);c.hide();b.grid.selection.clear();b.grid.enableToolbarButtons(!1)},error:function(d){c.hide();b.grid.selection.clear();b.grid.enableToolbarButtons(!1)}})})})}})});
