(function(){define("buildspace/apps/MasterCostData/LinkProjectParticularsDialog","dojo/_base/declare dojo/aspect dojo/_base/array dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!buildspace/nls/CostData".split(" "),function(k,m,l,t,f,u,v,w,n,p,q,x,d){var r=k("buildspace.apps.MasterCostData.LinkProjectParticularsGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",
region:"center",selectedItemIds:[],deselectedItemIds:[],constructor:function(a){this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}};this.inherited(arguments)},canSort:function(){return!1},postCreate:function(){var a=this;this.inherited(arguments);m.after(this,"_onFetchComplete",function(){a.markedCheckBoxObject(a.selectedItemIds,!0)});this._connects.push(f.connect(this,"onSelected",function(b){(b=a.getItem(b))&&0<b.id[0]&&a.pushItemIdIntoGridArray(b,!0)}));
this._connects.push(f.connect(this,"onDeselected",function(b){(b=a.getItem(b))&&0<b.id[0]&&a.pushItemIdIntoGridArray(b,!1)}));this._connects.push(f.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)}))},markedCheckBoxObject:function(a,b){var c=this,e=this.store;l.forEach(a,function(g){e.fetchItemByIdentity({identity:g,onItem:function(h){h&&(c.pushItemIdIntoGridArray(h,b),c.rowSelectCell.toggleRow(h._0,b))}})})},pushItemIdIntoGridArray:function(a,b){var c=dojo.indexOf(this.selectedItemIds,
a.id[0]),e=dojo.indexOf(this.deselectedItemIds,a.id[0]);b?(-1===c&&this.selectedItemIds.push(a.id[0]),-1!==e&&this.deselectedItemIds.splice(e,1)):(-1!==c&&this.selectedItemIds.splice(c,1),-1===e&&this.deselectedItemIds.push(a.id[0]))},toggleAllSelection:function(a){var b=this;var c=b.selection;a?c.selectRange(0,b.rowCount-1):c.deselectAll();return b.store.fetch({onComplete:function(e){dojo.forEach(e,function(g,h){0<g.id&&b.pushItemIdIntoGridArray(g,a)})}})},refreshGrid:function(){this.selection.deselectAll();
this.beginUpdate();this.store.close();this._refresh();this.endUpdate()},destroy:function(){this.inherited(arguments);l.forEach(this._connects,f.disconnect);return delete this._connects}});return k("buildspace.apps.MasterCostData.LinkProjectParticularsDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:null,masterCostData:null,item:null,field:"",buildRendering:function(){this.title||(this.title=buildspace.truncateString(d.projectParticulars,80));var a=this.createContent();a.startup();this.content=
a;this.inherited(arguments)},postCreate:function(){p.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){if(a.keyCode===n.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a=this;var b=a.borderContainer=new dijit.layout.BorderContainer({style:"padding:0px;width:750px;height:380px;",gutters:!1});var c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;width:100%;"});
c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){a.hide()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.save,iconClass:"icon-16-container icon-16-save",onClick:function(){a.save()}}));b.addChild(c);this.createGrid();return b},createGrid:function(){var a=this;a.gridFormatter=new q;dojo.xhrGet({url:"masterCostData/getLinkedProjectParticulars",content:{id:a.item.id,master_cost_data_id:a.masterCostData.id,
field:a.field,_csrf_token:a.item._csrf_token},handleAs:"json",load:function(b){b.success&&(a.grid=new r({selectedItemIds:b.linked_project_particular_ids,deselectedItemIds:[],store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"masterCostData/getProjectParticularList/master_cost_data_id/"+a.masterCostData.id}),structure:[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.gridFormatter.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"},{name:d.unit,
field:"uom_id",width:"200px",formatter:a.gridFormatter.unitCellFormatter}]}),a.borderContainer.addChild(a.grid))},error:function(b){}})},save:function(){var a=this,b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show().then(function(){dojo.xhrPost({url:"masterCostData/linkProjectParticulars",handleAs:"json",content:{id:a.item.id,field:a.field,"selectedIds[]":a.grid.selectedItemIds,"deselectedIds[]":a.grid.deselectedItemIds,_csrf_token:a.item._csrf_token},load:function(c){c.success||
new buildspace.dialog.alert(d.savingUnsuccessful,c.errorMsg,80,400);a.grid.refreshGrid();a.grid.selectedItemIds=c.linked_project_particular_ids;a.grid.deselectedItemIds=[];a.grid.markedCheckBoxObject(a.grid.selectedItemIds,!0);b.hide()},error:function(c){b.hide()}})})}})})}).call(this);
