var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,f):$jscomp.polyfillUnisolated(a,b,c,f))};$jscomp.polyfillUnisolated=function(a,b,c,f){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];if(!(d in c))return;c=c[d]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,f){var d=a.split(".");a=1===d.length;f=d[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<d.length-1;l++){var u=d[l];if(!(u in f))return;f=f[u]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?f[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[d]&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):
$jscomp.POLYFILL_PREFIX+d),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[d],{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(d,l){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:l})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,f=function(d){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(d||"")+"_"+c++,d)};return f},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var f=$jscomp.global[b[c]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,f=!1,d={next:function(){if(!f&&c<a.length){var l=c++;return{value:b(l,a[l]),done:!1}}f=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b,c){return c})}},"es8","es3");
define("buildspace/apps/MasterCostData/PrimeCostRateGrid",["dojo/_base/declare","dojo/_base/lang","dojox/grid/EnhancedGrid","buildspace/widget/grid/cells/Formatter","dojo/i18n!buildspace/nls/CostData"],function(a,b,c,f,d){var l=a("buildspace.apps.MasterCostData.PrimeCostRateGrid",c,{style:"border:none;",region:"center",keepSelection:!0,rowSelector:"0px",escapeHTMLInData:!1,masterCostData:null,parentItem:null,addUrl:"masterCostData/addNewPrimeCostRate",updateUrl:"masterCostData/updatePrimeCostRate",
constructor:function(e){this.inherited(arguments)},canSort:function(e){return!1},postCreate:function(){var e=this;this.inherited(arguments);this.on("RowClick",function(g){if(g.cell){var h=!1;0<this.getItem(g.rowIndex).id[0]&&(h=!0);e.enableToolbarButtons(h)}})},enableToolbarButtons:function(e){dijit.byId(this.parentItem.id+"prime-cost-rate-delete-button")._setDisabledAttr(!e)},dodblclick:function(e){this.onRowDblClick(e)},doApplyCellEdit:function(e,g,h){var k=this,m=k.getItem(g),q=k.store;if(e!==
m[h][0]){var w=buildspace.dialog.indeterminateProgressBar({title:d.savingData+". "+d.pleaseWait+"..."}),v={id:m.id,attr_name:h,val:e,master_cost_data_id:k.masterCostData.id,parent_id:k.parentItem.id,_csrf_token:m._csrf_token?m._csrf_token:null},r=this.updateUrl;m.id==buildspace.constants.GRID_LAST_ROW&&(r=0<g?k.getItem(g-1):!1,b.mixin(v,{prev_item_id:r?r.id:0}),r=this.addUrl);var x=function(n,t){for(var p in n)m.hasOwnProperty(p)&&p!=t._getIdentifierAttribute()&&t.setValue(m,p,n[p]);t.save()};v={url:r,
content:v,handleAs:"json",load:function(n){if(n.success){0<m.id?x(n.data,q):(q.deleteItem(m),q.save(),dojo.forEach(n.items,function(p){q.newItem(p)}),q.save());var t=k.getCellByField(h);window.setTimeout(function(){k.focus.setFocusIndex(g,t.index)},10)}w.hide()},error:function(n){w.hide()}};w.show();dojo.xhrPost(v)}k.inherited(arguments)},canEdit:function(e,g){return!0},reload:function(){this.store.close();this._refresh()}}),u=function(e,g){return parseInt(g)+1};return a("buildspace.apps.MasterCostData.PrimeCostRateContainer",
dijit.layout.BorderContainer,{region:"center",title:"",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,masterCostData:null,parentItem:null,grid:null,stackContainer:null,level:null,gridCreator:null,unitsOfMeasurement:[],postCreate:function(){this.inherited(arguments);var e=this,g=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});g.show();dojo.xhrPost({url:"default/getAllUnits",handleAs:"json",load:function(h){e.unitsOfMeasurement.values=h.values;e.unitsOfMeasurement.options=
h.options},error:function(h){}}).then(function(){var h=e.createBreakdownGrid();h=new dijit.layout.ContentPane({style:"padding:0px;border:none;width:100%;height:100%;",region:"center",content:h,grid:h});e.addChild(e.createToolbar());e.addChild(h);g.hide()})},createToolbar:function(){var e=this,g=new dijit.Toolbar({region:"top",style:"outline:none!important;border:none;padding:2px;width:100%;"});g.addChild(new dijit.form.Button({id:this.parentItem.id+"prime-cost-rate-delete-button",label:d.delete,iconClass:"icon-16-container icon-16-delete",
disabled:!0,style:"outline:none!important;",onClick:function(){if(-1<e.grid.selection.selectedIndex){var h=e.grid.getItem(e.grid.selection.selectedIndex);0<h.id[0]&&e.deleteRow(h)}}}));return g},createBreakdownGrid:function(){var e=this;this.gridFormatter=new f;e.grid=l({masterCostData:e.masterCostData,parentItem:e.parentItem,structure:[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:u},{name:d.description,field:"description",width:"auto",cellType:"buildspace.widget.grid.cells.Textarea",
editable:!0},{name:d.unit,field:"uom_id",width:"70px",editable:!0,styles:"text-align:center;",type:"dojox.grid.cells.Select",options:e.unitsOfMeasurement.options,values:e.unitsOfMeasurement.values,hidden:3!=e.level,formatter:this.gridFormatter.unitCellFormatter}],store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"masterCostData/getPrimeCostRateBreakdown/masterCostData/"+this.masterCostData.id+"/parent_id/"+this.parentItem.id}),onRowDblClick:function(g){g=this.getItem(g.rowIndex);3>e.level&&
0<g.id[0]&&e.createPrimeCostRateGrid(g)}});return e.grid},createPrimeCostRateGrid:function(e){this.gridCreator.createPrimeCostRateGrid(e,this.level+1)},deleteRow:function(e){var g=this,h=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});buildspace.dialog.confirm(d.confirmation,d.confirmationMessage+"<br/>"+d.cannotBeUndone,80,300,function(){h.show().then(function(){dojo.xhrPost({url:"masterCostData/deletePrimeCostRate",content:{id:e.id,_csrf_token:e._csrf_token},
handleAs:"json",load:function(k){k.success?g.grid.reload():buildspace.dialog.alert(d.cannotBeDeleted,k.errorMsg,80,300);h.hide();g.grid.selection.clear();g.grid.enableToolbarButtons(!1)},error:function(k){h.hide();g.grid.selection.clear();g.grid.enableToolbarButtons(!1)}})})})}})});
