define("buildspace/apps/MasterCostData/WorkCategoryParticularSelectionDialog","dojo/_base/declare dojo/aspect dojo/_base/array dojo/_base/connect dojo/dom-style dojox/grid/EnhancedGrid dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!buildspace/nls/CostData".split(" "),function(k,m,l,f,n,r,t,e){var p=k("buildspace.apps.MasterCostData.WorkCategoryParticularSelectionDialog.Grid",dojox.grid.EnhancedGrid,{region:"center",style:"border-top:none;",selectedItemIds:[],deselectedItemIds:[],canSort:function(b){return!1},
constructor:function(b){this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}};this.inherited(arguments)},postCreate:function(){this.inherited(arguments);var b=this;m.after(this,"_onFetchComplete",function(){b.markedCheckBoxObject(b.selectedItemIds,!0)});this._connects.push(f.connect(this,"onSelected",function(a){(a=b.getItem(a))&&(0<a.id[0]||"provisional_sum"==a.id[0])&&b.pushItemIdIntoGridArray(a,!0)}));this._connects.push(f.connect(this,"onDeselected",function(a){(a=
b.getItem(a))&&(0<a.id[0]||"provisional_sum"==a.id[0])&&b.pushItemIdIntoGridArray(a,!1)}));this._connects.push(f.connect(this.rowSelectCell,"toggleAllSelection",function(a){b.toggleAllSelection(a)}))},markedCheckBoxObject:function(b,a){var c=this,d=this.store;l.forEach(b,function(g){d.fetchItemByIdentity({identity:g,onItem:function(h){h&&(c.pushItemIdIntoGridArray(h,a),c.rowSelectCell.toggleRow(h._0,a))}})})},pushItemIdIntoGridArray:function(b,a){var c=dojo.indexOf(this.selectedItemIds,b.id[0]),d=
dojo.indexOf(this.deselectedItemIds,b.id[0]);a?(-1===c&&this.selectedItemIds.push(b.id[0]),-1!==d&&this.deselectedItemIds.splice(d,1)):(-1!==c&&this.selectedItemIds.splice(c,1),-1===d&&this.deselectedItemIds.push(b.id[0]))},toggleAllSelection:function(b){var a=this;var c=a.selection;b?c.selectRange(0,a.rowCount-1):c.deselectAll();return a.store.fetch({onComplete:function(d){dojo.forEach(d,function(g,h){0<g.id&&a.pushItemIdIntoGridArray(g,b)})}})},refreshGrid:function(){this.selection.deselectAll();
this.beginUpdate();this.store.close();this._refresh();this.endUpdate()},destroy:function(){this.inherited(arguments);l.forEach(this._connects,f.disconnect);return delete this._connects}}),q=function(b,a){return parseInt(a)+1};return k("buildspace.apps.MasterCostData.WorkCategoryParticularSelectionDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:e.showHideColumns,gridUrl:null,masterCostData:null,projectCostingItem:null,selectedItemIds:[],buildRendering:function(){var b=this.createContent();
b.startup();this.content=b;this.inherited(arguments)},postCreate:function(){n.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},onHide:function(){this.destroyRecursive()},createToolbar:function(){var b=this,a=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;width:100%;"});a.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",onClick:function(){b.hide()}}));a.addChild(new dijit.ToolbarSeparator);
a.addChild(new dijit.form.Button({label:e.save,iconClass:"icon-16-container icon-16-save",onClick:function(){b.save()}}));return a},getGridStructure:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:q},{name:e.description,field:"description",width:"auto"}]},createContent:function(){var b=new dijit.layout.BorderContainer({style:"padding:0px;width:800px;height:350px;",gutters:!1}),a=this.grid=p({selectedItemIds:this.selectedItemIds,structure:this.getGridStructure(),
store:dojo.data.ItemFileWriteStore({url:this.gridUrl,clearOnClose:!0})});b.addChild(this.createToolbar());b.addChild(a);return b},save:function(){var b=this,a=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),c={url:"masterCostData/updateWorkCategorySelectedParticulars/id/"+this.projectCostingItem.id,content:{"selected_ids[]":this.grid.selectedItemIds,"deselected_ids[]":this.grid.deselectedItemIds,_csrf_token:this.projectCostingItem._csrf_token?this.projectCostingItem._csrf_token:
null},handleAs:"json",load:function(d){d.success&&b.hide();a.hide()},error:function(d){a.hide()}};a.show();dojo.xhrPost(c)}})});
