define("buildspace/apps/MasterCostData/WorkCategoryGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojox/grid/EnhancedGrid dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/cells/Formatter dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dijit/Menu dijit/CheckedMenuItem dijit/focus dojox/grid/enhanced/plugins/Menu dojo/when dojo/aspect ./ElementGrid ./LinkProjectParticularsDialog ./WorkCategoryParticularSelectionDialog dojo/i18n!buildspace/nls/CostData".split(" "),
function(q,t,E,u,v,w,F,G,H,I,J,r,K,L,M,x,y,z,d){var D=q("buildspace.apps.MasterCostData.WorkCategoryGrid",u,{style:"border:none;",region:"center",keepSelection:!0,rowSelector:"0px",escapeHTMLInData:!1,masterCostData:null,projectCostingItem:null,addUrl:"masterCostData/addNewWorkCategory",updateUrl:"masterCostData/updateItem",constructor:function(a){this.gridFormatter=new w;this.structure=this.getGridStructure();this.inherited(arguments);this.rearranger=v(this,{})},canSort:function(a){return!1},postCreate:function(){var a=
this;this.inherited(arguments);this.on("RowClick",function(b){b.cell&&(b=this.getItem(b.rowIndex),0<b.id[0]?a.enableToolbarButtons(!0):b.id[0]===buildspace.constants.GRID_LAST_ROW&&(a.enableToolbarButtons(!0),dijit.byId(a.projectCostingItem.id+"work-category-delete-button")._setDisabledAttr(!0)))})},enableToolbarButtons:function(a){dijit.byId(this.projectCostingItem.id+"work-category-delete-button")._setDisabledAttr(!a);dijit.byId(this.projectCostingItem.id+"work-category-add-button")._setDisabledAttr(!a)},
getGridStructure:function(){return[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:A.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",cellType:"buildspace.widget.grid.cells.Textarea",editable:!0}]},dodblclick:function(a){this.onRowDblClick(a)},doApplyCellEdit:function(a,b,e){var c=this,f=c.getItem(b),k=c.store;if("description"==e){if(a!==f[e][0]){var n=buildspace.dialog.indeterminateProgressBar({title:d.savingData+". "+d.pleaseWait+"..."}),h=
{id:f.id,attr_name:e,val:a,master_cost_data_id:c.masterCostData.id,parent_id:c.projectCostingItem.id,_csrf_token:f._csrf_token?f._csrf_token:null},g=this.updateUrl;if(f.id==buildspace.constants.GRID_LAST_ROW){g=0<b?c.getItem(b-1):!1;var B=c.getItem(b);t.mixin(h,{prev_item_id:g?g.id:0,current_id:B.id});g=this.addUrl}var C=function(l,p){for(var m in l)f.hasOwnProperty(m)&&m!=p._getIdentifierAttribute()&&p.setValue(f,m,l[m]);p.save()};h={url:g,content:h,handleAs:"json",load:function(l){if(l.success){0<
f.id?C(l.data,k):(k.deleteItem(f),k.save(),dojo.forEach(l.items,function(m){k.newItem(m)}),k.save(),c.enableToolbarButtons(!1));var p=c.getCellByField(e);window.setTimeout(function(){c.focus.setFocusIndex(b,p.index)},10);n.hide()}},error:function(l){n.hide()}};n.show();dojo.xhrPost(h)}c.inherited(arguments)}},canEdit:function(a,b){return!0},reload:function(){this.store.save();this.store.close();this.sort();this._refresh()}}),A={rowCountCellFormatter:function(a,b){return parseInt(b)+1}};return q("buildspace.apps.MasterCostData.WorkCategoriesContainer",
dijit.layout.BorderContainer,{region:"center",title:"",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,masterCostData:null,projectCostingItem:null,grid:null,stackContainer:null,postCreate:function(){this.inherited(arguments);var a=this.createBreakdownGrid();a=new dijit.layout.ContentPane({style:"padding:0px;border:none;width:100%;height:100%;",region:"center",content:a,grid:a});this.addChild(this.createToolbar());this.addChild(a)},createToolbar:function(){var a=this,b=new dijit.Toolbar({region:"top",
style:"outline:none!important;border:none;padding:2px;width:100%;"});b.addChild(new dijit.form.Button({id:a.projectCostingItem.id+"work-category-add-button",label:d.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<a.grid.selection.selectedIndex?!1:!0,onClick:function(){-1<a.grid.selection.selectedIndex&&a.addRow(a.grid.selection.selectedIndex)}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:a.projectCostingItem.id+"work-category-delete-button",label:d.deleteRow,
iconClass:"icon-16-container icon-16-delete",disabled:!0,style:"outline:none!important;",onClick:function(){if(-1<a.grid.selection.selectedIndex){var e=a.grid.getItem(a.grid.selection.selectedIndex);0<e.id[0]&&a.deleteRow(e)}}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({label:d.showHideColumns,iconClass:"icon-16-container icon-16-dial",style:"outline:none!important;",onClick:function(){a.createWorkCategoryParticularSelectionDialog()}}));b.addChild(new dijit.ToolbarSeparator);
b.addChild(new dijit.form.Button({label:d.refresh,iconClass:"icon-16-container icon-16-reload",style:"outline:none!important;",onClick:function(){a.grid.reload()}}));return b},createBreakdownGrid:function(){var a=this;a.grid=D({masterCostData:a.masterCostData,projectCostingItem:a.projectCostingItem,onRowDblClick:function(b){b=this.getItem(b.rowIndex);b.id!=buildspace.constants.GRID_LAST_ROW&&a.createElementGrid(b)},store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"masterCostData/getWorkCategoryList/masterCostData/"+
this.masterCostData.id+"/id/"+this.projectCostingItem.id})});return a.grid},createElementGrid:function(a){a=new x({title:buildspace.truncateString(a.description,60),stackContainer:this.stackContainer,masterCostData:this.masterCostData,workCategory:a});this.stackContainer.addChild(a);this.stackContainer.selectChild(a)},activateLinkedProjectParticularsDialog:function(a,b){(new y({masterCostData:this.masterCostData,item:a,field:b})).show()},addRow:function(a){r.curNode.blur();r.curNode=null;var b=this,
e=buildspace.dialog.indeterminateProgressBar({title:d.addingRow+". "+d.pleaseWait+"..."}),c=b.grid.store,f=b.grid.getItem(a),k=0<a?b.grid.getItem(a-1).id:0,n={master_cost_data_id:b.masterCostData.id,parent_id:b.projectCostingItem.id,prev_item_id:k,current_id:f.id,_csrf_token:f._csrf_token};e.show().then(function(){dojo.xhrPost({url:b.grid.addUrl,content:n,handleAs:"json",load:function(h){h.success&&dojo.forEach(h.items,function(g){0<g.id&&(g=c.newItem(g),c.save(),g=b.grid.getItemIndex(g),b.grid.rearranger.moveRows([g],
a),b.grid.selection.clear())});window.setTimeout(function(){b.grid.selection.setSelected(a,!0);b.grid.focus.setFocusIndex(a,1)},30);e.hide()},error:function(h){b.grid.selection.clear();b.grid.enableToolbarButtons(!0);e.hide()}})})},deleteRow:function(a){var b=this,e=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});buildspace.dialog.confirm(d.confirmation,d.confirmationMessage+"<br/>"+d.willDeleteAllChildItems+"<br/>"+d.cannotBeUndone,80,300,function(){e.show().then(function(){dojo.xhrPost({url:"masterCostData/deleteItem",
content:{id:a.id,_csrf_token:a._csrf_token},handleAs:"json",load:function(c){c.success?(b.grid.store.deleteItem(a),b.grid.store.save(),b.grid.reload()):buildspace.dialog.alert(d.cannotBeDeleted,c.errorMsg,80,300);e.hide();b.grid.selection.clear();b.grid.enableToolbarButtons(!1)},error:function(c){e.hide();b.grid.selection.clear();b.grid.enableToolbarButtons(!1)}})})})},createWorkCategoryParticularSelectionDialog:function(){var a=this,b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+
"..."}),e={url:"masterCostData/getWorkCategoryParticulars/id/"+a.projectCostingItem.id,content:{_csrf_token:a.projectCostingItem._csrf_token?a.projectCostingItem._csrf_token:null},handleAs:"json",load:function(c){c.success&&(new z({gridUrl:"masterCostData/getProjectParticularList/master_cost_data_id/"+a.masterCostData.id,masterCostData:a.masterCostData,projectCostingItem:a.projectCostingItem,selectedItemIds:c.selected_ids})).show();b.hide()},error:function(c){b.hide()}};b.show();dojo.xhrPost(e)}})});
