<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ScheduleOfQuantityVariationOrderItemXref', 'main_conn');

/**
 * BaseScheduleOfQuantityVariationOrderItemXref
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $schedule_of_quantity_item_id
 * @property integer $variation_order_item_id
 * @property integer $type
 * @property ScheduleOfQuantityItem $ScheduleOfQuantityItem
 * @property VariationOrderItem $VariationOrderItem
 * 
 * @method integer                                  getId()                           Returns the current record's "id" value
 * @method integer                                  getScheduleOfQuantityItemId()     Returns the current record's "schedule_of_quantity_item_id" value
 * @method integer                                  getVariationOrderItemId()         Returns the current record's "variation_order_item_id" value
 * @method integer                                  getType()                         Returns the current record's "type" value
 * @method ScheduleOfQuantityItem                   getScheduleOfQuantityItem()       Returns the current record's "ScheduleOfQuantityItem" value
 * @method VariationOrderItem                       getVariationOrderItem()           Returns the current record's "VariationOrderItem" value
 * @method ScheduleOfQuantityVariationOrderItemXref setId()                           Sets the current record's "id" value
 * @method ScheduleOfQuantityVariationOrderItemXref setScheduleOfQuantityItemId()     Sets the current record's "schedule_of_quantity_item_id" value
 * @method ScheduleOfQuantityVariationOrderItemXref setVariationOrderItemId()         Sets the current record's "variation_order_item_id" value
 * @method ScheduleOfQuantityVariationOrderItemXref setType()                         Sets the current record's "type" value
 * @method ScheduleOfQuantityVariationOrderItemXref setScheduleOfQuantityItem()       Sets the current record's "ScheduleOfQuantityItem" value
 * @method ScheduleOfQuantityVariationOrderItemXref setVariationOrderItem()           Sets the current record's "VariationOrderItem" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScheduleOfQuantityVariationOrderItemXref extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('soq_vo_item_xrefs');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('schedule_of_quantity_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('variation_order_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));


        $this->index('soq_vo_xref_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'schedule_of_quantity_item_id',
              2 => 'variation_order_item_id',
              3 => 'type',
             ),
             ));
        $this->index('soq_vo_xref_fk_idx', array(
             'fields' => 
             array(
              0 => 'schedule_of_quantity_item_id',
              1 => 'variation_order_item_id',
             ),
             ));
        $this->index('soq_vo_xref_unique_idx', array(
             'fields' => 
             array(
              0 => 'schedule_of_quantity_item_id',
              1 => 'variation_order_item_id',
              2 => 'type',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScheduleOfQuantityItem', array(
             'local' => 'schedule_of_quantity_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('VariationOrderItem', array(
             'local' => 'variation_order_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}