<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BillItemCostDataPrimeCostRate', 'main_conn');

/**
 * BaseBillItemCostDataPrimeCostRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bill_item_id
 * @property integer $cost_data_prime_cost_rate_id
 * @property BillItem $BillItem
 * @property CostDataPrimeCostRate $CostDataPrimeCostRate
 * 
 * @method integer                       getId()                           Returns the current record's "id" value
 * @method integer                       getBillItemId()                   Returns the current record's "bill_item_id" value
 * @method integer                       getCostDataPrimeCostRateId()      Returns the current record's "cost_data_prime_cost_rate_id" value
 * @method BillItem                      getBillItem()                     Returns the current record's "BillItem" value
 * @method CostDataPrimeCostRate         getCostDataPrimeCostRate()        Returns the current record's "CostDataPrimeCostRate" value
 * @method BillItemCostDataPrimeCostRate setId()                           Sets the current record's "id" value
 * @method BillItemCostDataPrimeCostRate setBillItemId()                   Sets the current record's "bill_item_id" value
 * @method BillItemCostDataPrimeCostRate setCostDataPrimeCostRateId()      Sets the current record's "cost_data_prime_cost_rate_id" value
 * @method BillItemCostDataPrimeCostRate setBillItem()                     Sets the current record's "BillItem" value
 * @method BillItemCostDataPrimeCostRate setCostDataPrimeCostRate()        Sets the current record's "CostDataPrimeCostRate" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBillItemCostDataPrimeCostRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bill_item_cost_data_prime_cost_rate');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('bill_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cost_data_prime_cost_rate_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('bill_item_cost_data_prime_cost_rate_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->index('bill_item_cost_data_prime_cost_rate_unique_idx', array(
             'fields' => 
             array(
              0 => 'cost_data_prime_cost_rate_id',
              1 => 'bill_item_id',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BillItem', array(
             'local' => 'bill_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CostDataPrimeCostRate', array(
             'local' => 'cost_data_prime_cost_rate_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}