<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubPackageResourceItem', 'main_conn');

/**
 * BaseSubPackageResourceItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sub_package_id
 * @property integer $resource_item_id
 * @property SubPackage $SubPackage
 * @property ResourceItem $ResourceItem
 * 
 * @method integer                getSubPackageId()     Returns the current record's "sub_package_id" value
 * @method integer                getResourceItemId()   Returns the current record's "resource_item_id" value
 * @method SubPackage             getSubPackage()       Returns the current record's "SubPackage" value
 * @method ResourceItem           getResourceItem()     Returns the current record's "ResourceItem" value
 * @method SubPackageResourceItem setSubPackageId()     Sets the current record's "sub_package_id" value
 * @method SubPackageResourceItem setResourceItemId()   Sets the current record's "resource_item_id" value
 * @method SubPackageResourceItem setSubPackage()       Sets the current record's "SubPackage" value
 * @method SubPackageResourceItem setResourceItem()     Sets the current record's "ResourceItem" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubPackageResourceItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_packages_resource_items');
        $this->hasColumn('sub_package_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('resource_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('spri_sub_package_id_idx', array(
             'fields' => 
             array(
              0 => 'sub_package_id',
             ),
             ));
        $this->index('spri_resource_item_id_idx', array(
             'fields' => 
             array(
              0 => 'resource_item_id',
             ),
             ));
        $this->index('spri_unique_idx', array(
             'fields' => 
             array(
              0 => 'sub_package_id',
              1 => 'resource_item_id',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SubPackage', array(
             'local' => 'sub_package_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ResourceItem', array(
             'local' => 'resource_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}