<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProjectStructure', 'main_conn');

/**
 * BaseProjectStructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                                          $id                                                                      Type: integer, primary key
 * @property string                                                       $title                                                                   Type: string
 * @property int                                                          $type                                                                    Type: integer
 * @property int                                                          $priority                                                                Type: integer
 * @property string                                                       $tender_origin_id                                                        Type: string
 * @property bool                                                         $bill_refreshed                                                          Type: boolean
 * @property int                                                          $project_revision_id                                                     Type: integer
 * @property ProjectRevision                                              $ProjectRevision                                                         
 * @property Doctrine_Collection|sfGuardGroup[]                           $ProjectGroups                                                           
 * @property Doctrine_Collection|sfGuardGroup[]                           $TenderingGroups                                                         
 * @property Doctrine_Collection|sfGuardGroup[]                           $PostContractGroups                                                      
 * @property Doctrine_Collection|sfGuardGroup[]                           $ProjectManagementGroups                                                 
 * @property Doctrine_Collection|BillColumnSetting[]                      $BillColumnSettings                                                      
 * @property BillMarkupSetting                                            $BillMarkupSetting                                                       
 * @property BillSetting                                                  $BillSetting                                                             
 * @property BillType                                                     $BillType                                                                
 * @property Doctrine_Collection|BillElement[]                            $Elements                                                                
 * @property BillLayoutSetting                                            $BillLayoutSetting                                                       
 * @property Doctrine_Collection|ContractManagementVerifier[]             $ContractManagementVerifier                                              
 * @property Doctrine_Collection|CostDataProject[]                        $CostDataProject                                                         
 * @property Doctrine_Collection|DebitCreditNoteClaim[]                   $DebitCreditNoteClaim                                                    
 * @property Doctrine_Collection|EditorProjectInformation[]               $EditorProjectInfo                                                       
 * @property Doctrine_Collection|ExportedFile[]                           $ExportedFiles                                                           
 * @property Doctrine_Collection|ImportedVariationOrder[]                 $ImportedVariationOrders                                                 
 * @property Doctrine_Collection|ImportedMaterialOnSite[]                 $ImportedMaterialsOnSite                                                 
 * @property Doctrine_Collection|ItemCodeSetting[]                        $ItemCodeSetting                                                         
 * @property ItemCodeSettingObject                                        $ItemCodeSettingObject                                                   
 * @property Doctrine_Collection|ProjectStructureLocationCode[]           $LocationCodes                                                           
 * @property MaterialOnSitePrintSetting                                   $MaterialOnSitePrintSetting                                              
 * @property Doctrine_Collection|MaterialOnSite[]                         $MaterialOnSites                                                         
 * @property PostContract                                                 $PostContract                                                            
 * @property NewPostContractFormInformation                               $NewPostContractFormInformation                                          
 * @property Doctrine_Collection|WaiverUserDefinedOption[]                $WaiverUserDefinedOption                                                 
 * @property PublishToPostContractOption                                  $PublishToPostContractOption                                             
 * @property Doctrine_Collection|PostContractClaim[]                      $PostContractClaim                                                       
 * @property Doctrine_Collection|SubProjectLatestApprovedClaimRevision[]  $SubProjectLatestApprovedClaimRevision                                   
 * @property Doctrine_Collection|NominatedSubContractorInformation[]      $NominatedSubContractorInfo                                              
 * @property Doctrine_Collection|ProjectRevision[]                        $ProjectRevisions                                                        
 * @property ProjectMainInformation                                       $MainInformation                                                         
 * @property ProjectLevel                                                 $Level                                                                   
 * @property Doctrine_Collection|ProjectCodeSettings[]                    $ProjectCodeSettings                                                     
 * @property Doctrine_Collection|ProjectSchedule[]                        $ProjectSchedules                                                        
 * @property Doctrine_Collection|ProjectManagementCalendar[]              $CalendarEvents                                                          
 * @property ProjectSummaryFooter                                         $ProjectSummaryFooter                                                    
 * @property ProjectSummaryBillStyle                                      $ProjectSummaryStyle                                                     
 * @property ProjectSummaryGeneralSetting                                 $ProjectSummaryGeneralSetting                                            
 * @property Doctrine_Collection|PurchaseOrder[]                          $PurchaseOrderRequests                                                   
 * @property Doctrine_Collection|PurchaseOrderProject[]                   $PurchaseOrders                                                          
 * @property Doctrine_Collection|RFQ[]                                    $QuotationRequests                                                       
 * @property Doctrine_Collection|RFQProject[]                             $Quotations                                                              
 * @property Doctrine_Collection|ScheduleOfQuantity[]                     $ScheduleOfQuantities                                                    
 * @property ScheduleOfRateBill                                           $ScheduleOfRateBill                                                      
 * @property Doctrine_Collection|ScheduleOfRateBillElement[]              $ScheduleOfRateBillElements                                              
 * @property ScheduleOfRateBillLayoutSetting                              $ScheduleOfRateBillLayoutSetting                                         
 * @property Doctrine_Collection|ProjectUserPermission[]                  $UserPermissions                                                         
 * @property Doctrine_Collection|StockInInvoice[]                         $StockInInvoices                                                         
 * @property Doctrine_Collection|StockOutUsedQuantity[]                   $StockOutQuantities                                                      
 * @property Doctrine_Collection|SubPackage[]                             $SubPackages                                                             
 * @property SupplyOfMaterial                                             $SupplyOfMaterial                                                        
 * @property Doctrine_Collection|SupplyOfMaterialElement[]                $SupplyOfMaterialElements                                                
 * @property SupplyOfMaterialLayoutSetting                                $SupplyOfMaterialLayoutSetting                                           
 * @property Doctrine_Collection|TenderAlternative[]                      $TenderAlternatives                                                      
 * @property TenderSetting                                                $TenderSetting                                                           
 * @property Doctrine_Collection|TenderCompany[]                          $Companies                                                               
 * @property Doctrine_Collection|TenderCompanyAttachments[]               $TenderCompanyAttachments                                                
 * @property Doctrine_Collection|VariationOrder[]                         $VariationOrders                                                         
 *  
 * @method int                                                            getId()                                                                  Type: integer, primary key
 * @method string                                                         getTitle()                                                               Type: string
 * @method int                                                            getType()                                                                Type: integer
 * @method int                                                            getPriority()                                                            Type: integer
 * @method string                                                         getTenderOriginId()                                                      Type: string
 * @method bool                                                           getBillRefreshed()                                                       Type: boolean
 * @method int                                                            getProjectRevisionId()                                                   Type: integer
 * @method ProjectRevision                                                getProjectRevision()                                                     
 * @method Doctrine_Collection|sfGuardGroup[]                             getProjectGroups()                                                       
 * @method Doctrine_Collection|sfGuardGroup[]                             getTenderingGroups()                                                     
 * @method Doctrine_Collection|sfGuardGroup[]                             getPostContractGroups()                                                  
 * @method Doctrine_Collection|sfGuardGroup[]                             getProjectManagementGroups()                                             
 * @method Doctrine_Collection|BillColumnSetting[]                        getBillColumnSettings()                                                  
 * @method BillMarkupSetting                                              getBillMarkupSetting()                                                   
 * @method BillSetting                                                    getBillSetting()                                                         
 * @method BillType                                                       getBillType()                                                            
 * @method Doctrine_Collection|BillElement[]                              getElements()                                                            
 * @method BillLayoutSetting                                              getBillLayoutSetting()                                                   
 * @method Doctrine_Collection|ContractManagementVerifier[]               getContractManagementVerifier()                                          
 * @method Doctrine_Collection|CostDataProject[]                          getCostDataProject()                                                     
 * @method Doctrine_Collection|DebitCreditNoteClaim[]                     getDebitCreditNoteClaim()                                                
 * @method Doctrine_Collection|EditorProjectInformation[]                 getEditorProjectInfo()                                                   
 * @method Doctrine_Collection|ExportedFile[]                             getExportedFiles()                                                       
 * @method Doctrine_Collection|ImportedVariationOrder[]                   getImportedVariationOrders()                                             
 * @method Doctrine_Collection|ImportedMaterialOnSite[]                   getImportedMaterialsOnSite()                                             
 * @method Doctrine_Collection|ItemCodeSetting[]                          getItemCodeSetting()                                                     
 * @method ItemCodeSettingObject                                          getItemCodeSettingObject()                                               
 * @method Doctrine_Collection|ProjectStructureLocationCode[]             getLocationCodes()                                                       
 * @method MaterialOnSitePrintSetting                                     getMaterialOnSitePrintSetting()                                          
 * @method Doctrine_Collection|MaterialOnSite[]                           getMaterialOnSites()                                                     
 * @method PostContract                                                   getPostContract()                                                        
 * @method NewPostContractFormInformation                                 getNewPostContractFormInformation()                                      
 * @method Doctrine_Collection|WaiverUserDefinedOption[]                  getWaiverUserDefinedOption()                                             
 * @method PublishToPostContractOption                                    getPublishToPostContractOption()                                         
 * @method Doctrine_Collection|PostContractClaim[]                        getPostContractClaim()                                                   
 * @method Doctrine_Collection|SubProjectLatestApprovedClaimRevision[]    getSubProjectLatestApprovedClaimRevision()                               
 * @method Doctrine_Collection|NominatedSubContractorInformation[]        getNominatedSubContractorInfo()                                          
 * @method Doctrine_Collection|ProjectRevision[]                          getProjectRevisions()                                                    
 * @method ProjectMainInformation                                         getMainInformation()                                                     
 * @method ProjectLevel                                                   getLevel()                                                               
 * @method Doctrine_Collection|ProjectCodeSettings[]                      getProjectCodeSettings()                                                 
 * @method Doctrine_Collection|ProjectSchedule[]                          getProjectSchedules()                                                    
 * @method Doctrine_Collection|ProjectManagementCalendar[]                getCalendarEvents()                                                      
 * @method ProjectSummaryFooter                                           getProjectSummaryFooter()                                                
 * @method ProjectSummaryBillStyle                                        getProjectSummaryStyle()                                                 
 * @method ProjectSummaryGeneralSetting                                   getProjectSummaryGeneralSetting()                                        
 * @method Doctrine_Collection|PurchaseOrder[]                            getPurchaseOrderRequests()                                               
 * @method Doctrine_Collection|PurchaseOrderProject[]                     getPurchaseOrders()                                                      
 * @method Doctrine_Collection|RFQ[]                                      getQuotationRequests()                                                   
 * @method Doctrine_Collection|RFQProject[]                               getQuotations()                                                          
 * @method Doctrine_Collection|ScheduleOfQuantity[]                       getScheduleOfQuantities()                                                
 * @method ScheduleOfRateBill                                             getScheduleOfRateBill()                                                  
 * @method Doctrine_Collection|ScheduleOfRateBillElement[]                getScheduleOfRateBillElements()                                          
 * @method ScheduleOfRateBillLayoutSetting                                getScheduleOfRateBillLayoutSetting()                                     
 * @method Doctrine_Collection|ProjectUserPermission[]                    getUserPermissions()                                                     
 * @method Doctrine_Collection|StockInInvoice[]                           getStockInInvoices()                                                     
 * @method Doctrine_Collection|StockOutUsedQuantity[]                     getStockOutQuantities()                                                  
 * @method Doctrine_Collection|SubPackage[]                               getSubPackages()                                                         
 * @method SupplyOfMaterial                                               getSupplyOfMaterial()                                                    
 * @method Doctrine_Collection|SupplyOfMaterialElement[]                  getSupplyOfMaterialElements()                                            
 * @method SupplyOfMaterialLayoutSetting                                  getSupplyOfMaterialLayoutSetting()                                       
 * @method Doctrine_Collection|TenderAlternative[]                        getTenderAlternatives()                                                  
 * @method TenderSetting                                                  getTenderSetting()                                                       
 * @method Doctrine_Collection|TenderCompany[]                            getCompanies()                                                           
 * @method Doctrine_Collection|TenderCompanyAttachments[]                 getTenderCompanyAttachments()                                            
 * @method Doctrine_Collection|VariationOrder[]                           getVariationOrders()                                                     
 *  
 * @method ProjectStructure                                               setId(int $val)                                                          Type: integer, primary key
 * @method ProjectStructure                                               setTitle(string $val)                                                    Type: string
 * @method ProjectStructure                                               setType(int $val)                                                        Type: integer
 * @method ProjectStructure                                               setPriority(int $val)                                                    Type: integer
 * @method ProjectStructure                                               setTenderOriginId(string $val)                                           Type: string
 * @method ProjectStructure                                               setBillRefreshed(bool $val)                                              Type: boolean
 * @method ProjectStructure                                               setProjectRevisionId(int $val)                                           Type: integer
 * @method ProjectStructure                                               setProjectRevision(ProjectRevision $val)                                 
 * @method ProjectStructure                                               setProjectGroups(Doctrine_Collection $val)                               
 * @method ProjectStructure                                               setTenderingGroups(Doctrine_Collection $val)                             
 * @method ProjectStructure                                               setPostContractGroups(Doctrine_Collection $val)                          
 * @method ProjectStructure                                               setProjectManagementGroups(Doctrine_Collection $val)                     
 * @method ProjectStructure                                               setBillColumnSettings(Doctrine_Collection $val)                          
 * @method ProjectStructure                                               setBillMarkupSetting(BillMarkupSetting $val)                             
 * @method ProjectStructure                                               setBillSetting(BillSetting $val)                                         
 * @method ProjectStructure                                               setBillType(BillType $val)                                               
 * @method ProjectStructure                                               setElements(Doctrine_Collection $val)                                    
 * @method ProjectStructure                                               setBillLayoutSetting(BillLayoutSetting $val)                             
 * @method ProjectStructure                                               setContractManagementVerifier(Doctrine_Collection $val)                  
 * @method ProjectStructure                                               setCostDataProject(Doctrine_Collection $val)                             
 * @method ProjectStructure                                               setDebitCreditNoteClaim(Doctrine_Collection $val)                        
 * @method ProjectStructure                                               setEditorProjectInfo(Doctrine_Collection $val)                           
 * @method ProjectStructure                                               setExportedFiles(Doctrine_Collection $val)                               
 * @method ProjectStructure                                               setImportedVariationOrders(Doctrine_Collection $val)                     
 * @method ProjectStructure                                               setImportedMaterialsOnSite(Doctrine_Collection $val)                     
 * @method ProjectStructure                                               setItemCodeSetting(Doctrine_Collection $val)                             
 * @method ProjectStructure                                               setItemCodeSettingObject(ItemCodeSettingObject $val)                     
 * @method ProjectStructure                                               setLocationCodes(Doctrine_Collection $val)                               
 * @method ProjectStructure                                               setMaterialOnSitePrintSetting(MaterialOnSitePrintSetting $val)           
 * @method ProjectStructure                                               setMaterialOnSites(Doctrine_Collection $val)                             
 * @method ProjectStructure                                               setPostContract(PostContract $val)                                       
 * @method ProjectStructure                                               setNewPostContractFormInformation(NewPostContractFormInformation $val)   
 * @method ProjectStructure                                               setWaiverUserDefinedOption(Doctrine_Collection $val)                     
 * @method ProjectStructure                                               setPublishToPostContractOption(PublishToPostContractOption $val)         
 * @method ProjectStructure                                               setPostContractClaim(Doctrine_Collection $val)                           
 * @method ProjectStructure                                               setSubProjectLatestApprovedClaimRevision(Doctrine_Collection $val)       
 * @method ProjectStructure                                               setNominatedSubContractorInfo(Doctrine_Collection $val)                  
 * @method ProjectStructure                                               setProjectRevisions(Doctrine_Collection $val)                            
 * @method ProjectStructure                                               setMainInformation(ProjectMainInformation $val)                          
 * @method ProjectStructure                                               setLevel(ProjectLevel $val)                                              
 * @method ProjectStructure                                               setProjectCodeSettings(Doctrine_Collection $val)                         
 * @method ProjectStructure                                               setProjectSchedules(Doctrine_Collection $val)                            
 * @method ProjectStructure                                               setCalendarEvents(Doctrine_Collection $val)                              
 * @method ProjectStructure                                               setProjectSummaryFooter(ProjectSummaryFooter $val)                       
 * @method ProjectStructure                                               setProjectSummaryStyle(ProjectSummaryBillStyle $val)                     
 * @method ProjectStructure                                               setProjectSummaryGeneralSetting(ProjectSummaryGeneralSetting $val)       
 * @method ProjectStructure                                               setPurchaseOrderRequests(Doctrine_Collection $val)                       
 * @method ProjectStructure                                               setPurchaseOrders(Doctrine_Collection $val)                              
 * @method ProjectStructure                                               setQuotationRequests(Doctrine_Collection $val)                           
 * @method ProjectStructure                                               setQuotations(Doctrine_Collection $val)                                  
 * @method ProjectStructure                                               setScheduleOfQuantities(Doctrine_Collection $val)                        
 * @method ProjectStructure                                               setScheduleOfRateBill(ScheduleOfRateBill $val)                           
 * @method ProjectStructure                                               setScheduleOfRateBillElements(Doctrine_Collection $val)                  
 * @method ProjectStructure                                               setScheduleOfRateBillLayoutSetting(ScheduleOfRateBillLayoutSetting $val) 
 * @method ProjectStructure                                               setUserPermissions(Doctrine_Collection $val)                             
 * @method ProjectStructure                                               setStockInInvoices(Doctrine_Collection $val)                             
 * @method ProjectStructure                                               setStockOutQuantities(Doctrine_Collection $val)                          
 * @method ProjectStructure                                               setSubPackages(Doctrine_Collection $val)                                 
 * @method ProjectStructure                                               setSupplyOfMaterial(SupplyOfMaterial $val)                               
 * @method ProjectStructure                                               setSupplyOfMaterialElements(Doctrine_Collection $val)                    
 * @method ProjectStructure                                               setSupplyOfMaterialLayoutSetting(SupplyOfMaterialLayoutSetting $val)     
 * @method ProjectStructure                                               setTenderAlternatives(Doctrine_Collection $val)                          
 * @method ProjectStructure                                               setTenderSetting(TenderSetting $val)                                     
 * @method ProjectStructure                                               setCompanies(Doctrine_Collection $val)                                   
 * @method ProjectStructure                                               setTenderCompanyAttachments(Doctrine_Collection $val)                    
 * @method ProjectStructure                                               setVariationOrders(Doctrine_Collection $val)                             
 *  
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectStructure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_structures');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('tender_origin_id', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('bill_refreshed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('project_revision_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('project_struct_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'root_id',
              2 => 'type',
              3 => 'lft',
              4 => 'rgt',
             ),
             ));
        $this->index('project_struct_fk_idx', array(
             'fields' => 
             array(
              0 => 'root_id',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProjectRevision', array(
             'local' => 'project_revision_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('sfGuardGroup as ProjectGroups', array(
             'refClass' => 'sfGuardProjectGroup',
             'local' => 'project_structure_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroup as TenderingGroups', array(
             'refClass' => 'sfGuardTenderingProjectGroup',
             'local' => 'project_structure_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroup as PostContractGroups', array(
             'refClass' => 'sfGuardPostContractProjectGroup',
             'local' => 'project_structure_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroup as ProjectManagementGroups', array(
             'refClass' => 'sfGuardProjectManagementGroup',
             'local' => 'project_structure_id',
             'foreign' => 'group_id'));

        $this->hasMany('BillColumnSetting as BillColumnSettings', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('BillMarkupSetting', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('BillSetting', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('BillType', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('BillElement as Elements', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('BillLayoutSetting', array(
             'local' => 'id',
             'foreign' => 'bill_id'));

        $this->hasMany('ContractManagementVerifier', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('CostDataProject', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('DebitCreditNoteClaim', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('EditorProjectInformation as EditorProjectInfo', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ExportedFile as ExportedFiles', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ImportedVariationOrder as ImportedVariationOrders', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ImportedMaterialOnSite as ImportedMaterialsOnSite', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ItemCodeSetting', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('ItemCodeSettingObject', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ProjectStructureLocationCode as LocationCodes', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('MaterialOnSitePrintSetting', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('MaterialOnSite as MaterialOnSites', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('PostContract', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('NewPostContractFormInformation', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('WaiverUserDefinedOption', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('PublishToPostContractOption', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('PostContractClaim', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('SubProjectLatestApprovedClaimRevision', array(
             'local' => 'id',
             'foreign' => 'main_project_id'));

        $this->hasMany('NominatedSubContractorInformation as NominatedSubContractorInfo', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ProjectRevision as ProjectRevisions', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('ProjectMainInformation as MainInformation', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('ProjectLevel as Level', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ProjectCodeSettings', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ProjectSchedule as ProjectSchedules', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ProjectManagementCalendar as CalendarEvents', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('ProjectSummaryFooter', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('ProjectSummaryBillStyle as ProjectSummaryStyle', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('ProjectSummaryGeneralSetting', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('PurchaseOrder as PurchaseOrderRequests', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('PurchaseOrderProject as PurchaseOrders', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('RFQ as QuotationRequests', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('RFQProject as Quotations', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ScheduleOfQuantity as ScheduleOfQuantities', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('ScheduleOfRateBill', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ScheduleOfRateBillElement as ScheduleOfRateBillElements', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('ScheduleOfRateBillLayoutSetting', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('ProjectUserPermission as UserPermissions', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('StockInInvoice as StockInInvoices', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('StockOutUsedQuantity as StockOutQuantities', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('SubPackage as SubPackages', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('SupplyOfMaterial', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('SupplyOfMaterialElement as SupplyOfMaterialElements', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('SupplyOfMaterialLayoutSetting', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('TenderAlternative as TenderAlternatives', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasOne('TenderSetting', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('TenderCompany as Companies', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('TenderCompanyAttachments', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $this->hasMany('VariationOrder as VariationOrders', array(
             'local' => 'id',
             'foreign' => 'project_structure_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'levelColumnName' => 'level',
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($softdelete0);
        $this->actAs($nestedset0);
    }
}