<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RecalculateBillItem', 'main_conn');

/**
 * BaseRecalculateBillItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bill_item_id
 * @property integer $type
 * @property BillItem $BillItem
 * 
 * @method integer             getBillItemId()   Returns the current record's "bill_item_id" value
 * @method integer             getType()         Returns the current record's "type" value
 * @method BillItem            getBillItem()     Returns the current record's "BillItem" value
 * @method RecalculateBillItem setBillItemId()   Sets the current record's "bill_item_id" value
 * @method RecalculateBillItem setType()         Sets the current record's "type" value
 * @method RecalculateBillItem setBillItem()     Sets the current record's "BillItem" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecalculateBillItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('recalculate_bill_items');
        $this->hasColumn('bill_item_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('type', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('recalculate_bill_item_id_id_idx', array(
             'fields' => 
             array(
              0 => 'bill_item_id',
              1 => 'type',
             ),
             ));
        $this->index('recalculate_bill_item_unique_idx', array(
             'fields' => 
             array(
              0 => 'bill_item_id',
              1 => 'type',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BillItem', array(
             'local' => 'bill_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}