<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BillItemLumpSumPercentage', 'main_conn');

/**
 * BaseBillItemLumpSumPercentage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bill_item_id
 * @property decimal $rate
 * @property decimal $percentage
 * @property decimal $amount
 * @property BillItem $BillItem
 * 
 * @method integer                   getId()           Returns the current record's "id" value
 * @method integer                   getBillItemId()   Returns the current record's "bill_item_id" value
 * @method decimal                   getRate()         Returns the current record's "rate" value
 * @method decimal                   getPercentage()   Returns the current record's "percentage" value
 * @method decimal                   getAmount()       Returns the current record's "amount" value
 * @method BillItem                  getBillItem()     Returns the current record's "BillItem" value
 * @method BillItemLumpSumPercentage setId()           Sets the current record's "id" value
 * @method BillItemLumpSumPercentage setBillItemId()   Sets the current record's "bill_item_id" value
 * @method BillItemLumpSumPercentage setRate()         Sets the current record's "rate" value
 * @method BillItemLumpSumPercentage setPercentage()   Sets the current record's "percentage" value
 * @method BillItemLumpSumPercentage setAmount()       Sets the current record's "amount" value
 * @method BillItemLumpSumPercentage setBillItem()     Sets the current record's "BillItem" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBillItemLumpSumPercentage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bill_item_lump_sum_percentages');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('bill_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rate', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('percentage', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('amount', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('bill_ilsp_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'bill_item_id',
              2 => 'amount',
              3 => 'deleted_at',
             ),
             ));
        $this->index('bill_ilsp_unique_idx', array(
             'fields' => 
             array(
              0 => 'bill_item_id',
              1 => 'deleted_at',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BillItem', array(
             'local' => 'bill_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($softdelete0);
    }
}