<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PurchaseOnBehalf', 'main_conn');

/**
 * BasePurchaseOnBehalf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_contract_claim_item_id
 * @property string $document_number
 * @property PostContractClaimItem $PostContractClaimItem
 * 
 * @method integer               getId()                          Returns the current record's "id" value
 * @method integer               getPostContractClaimItemId()     Returns the current record's "post_contract_claim_item_id" value
 * @method string                getDocumentNumber()              Returns the current record's "document_number" value
 * @method PostContractClaimItem getPostContractClaimItem()       Returns the current record's "PostContractClaimItem" value
 * @method PurchaseOnBehalf      setId()                          Sets the current record's "id" value
 * @method PurchaseOnBehalf      setPostContractClaimItemId()     Sets the current record's "post_contract_claim_item_id" value
 * @method PurchaseOnBehalf      setDocumentNumber()              Sets the current record's "document_number" value
 * @method PurchaseOnBehalf      setPostContractClaimItem()       Sets the current record's "PostContractClaimItem" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePurchaseOnBehalf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('purchase_on_behalf');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('post_contract_claim_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('document_number', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));


        $this->index('purchase_on_behalf_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->index('purchase_on_behalf_unique_idx', array(
             'fields' => 
             array(
              0 => 'post_contract_claim_item_id',
              1 => 'deleted_at',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PostContractClaimItem', array(
             'local' => 'post_contract_claim_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($softdelete0);
    }
}