<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubPackageUnitInformation', 'main_conn');

/**
 * BaseSubPackageUnitInformation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bill_column_setting_id
 * @property integer $counter
 * @property BillColumnSetting $BillColumnSetting
 * 
 * @method integer                   getId()                     Returns the current record's "id" value
 * @method integer                   getBillColumnSettingId()    Returns the current record's "bill_column_setting_id" value
 * @method integer                   getCounter()                Returns the current record's "counter" value
 * @method BillColumnSetting         getBillColumnSetting()      Returns the current record's "BillColumnSetting" value
 * @method SubPackageUnitInformation setId()                     Sets the current record's "id" value
 * @method SubPackageUnitInformation setBillColumnSettingId()    Sets the current record's "bill_column_setting_id" value
 * @method SubPackageUnitInformation setCounter()                Sets the current record's "counter" value
 * @method SubPackageUnitInformation setBillColumnSetting()      Sets the current record's "BillColumnSetting" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubPackageUnitInformation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_package_unit_information');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('bill_column_setting_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('counter', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('sub_package_unit_information_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->index('sub_package_unit_information_fk_idx', array(
             'fields' => 
             array(
              0 => 'bill_column_setting_id',
             ),
             ));
        $this->index('sub_package_unit_information_unique_idx', array(
             'fields' => 
             array(
              0 => 'bill_column_setting_id',
              1 => 'counter',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BillColumnSetting', array(
             'local' => 'bill_column_setting_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}