<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImportedMaterialOnSiteItem', 'main_conn');

/**
 * BaseImportedMaterialOnSiteItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $imported_material_on_site_id
 * @property string $tender_origin_id
 * @property string $description
 * @property integer $sequence
 * @property integer $type
 * @property varchar $uom_symbol
 * @property decimal $quantity
 * @property decimal $rate
 * @property decimal $final_amount
 * @property decimal $reduction_percentage
 * @property decimal $reduction_amount
 * @property ImportedMaterialOnSite $ImportedMaterialOnSite
 * 
 * @method integer                    getId()                           Returns the current record's "id" value
 * @method integer                    getImportedMaterialOnSiteId()     Returns the current record's "imported_material_on_site_id" value
 * @method string                     getTenderOriginId()               Returns the current record's "tender_origin_id" value
 * @method string                     getDescription()                  Returns the current record's "description" value
 * @method integer                    getSequence()                     Returns the current record's "sequence" value
 * @method integer                    getType()                         Returns the current record's "type" value
 * @method varchar                    getUomSymbol()                    Returns the current record's "uom_symbol" value
 * @method decimal                    getQuantity()                     Returns the current record's "quantity" value
 * @method decimal                    getRate()                         Returns the current record's "rate" value
 * @method decimal                    getFinalAmount()                  Returns the current record's "final_amount" value
 * @method decimal                    getReductionPercentage()          Returns the current record's "reduction_percentage" value
 * @method decimal                    getReductionAmount()              Returns the current record's "reduction_amount" value
 * @method ImportedMaterialOnSite     getImportedMaterialOnSite()       Returns the current record's "ImportedMaterialOnSite" value
 * @method ImportedMaterialOnSiteItem setId()                           Sets the current record's "id" value
 * @method ImportedMaterialOnSiteItem setImportedMaterialOnSiteId()     Sets the current record's "imported_material_on_site_id" value
 * @method ImportedMaterialOnSiteItem setTenderOriginId()               Sets the current record's "tender_origin_id" value
 * @method ImportedMaterialOnSiteItem setDescription()                  Sets the current record's "description" value
 * @method ImportedMaterialOnSiteItem setSequence()                     Sets the current record's "sequence" value
 * @method ImportedMaterialOnSiteItem setType()                         Sets the current record's "type" value
 * @method ImportedMaterialOnSiteItem setUomSymbol()                    Sets the current record's "uom_symbol" value
 * @method ImportedMaterialOnSiteItem setQuantity()                     Sets the current record's "quantity" value
 * @method ImportedMaterialOnSiteItem setRate()                         Sets the current record's "rate" value
 * @method ImportedMaterialOnSiteItem setFinalAmount()                  Sets the current record's "final_amount" value
 * @method ImportedMaterialOnSiteItem setReductionPercentage()          Sets the current record's "reduction_percentage" value
 * @method ImportedMaterialOnSiteItem setReductionAmount()              Sets the current record's "reduction_amount" value
 * @method ImportedMaterialOnSiteItem setImportedMaterialOnSite()       Sets the current record's "ImportedMaterialOnSite" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImportedMaterialOnSiteItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imported_material_on_site_items');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('imported_material_on_site_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tender_origin_id', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('sequence', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('type', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('uom_symbol', 'varchar', 10, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('quantity', 'decimal', null, array(
             'type' => 'decimal',
             'default' => 0,
             ));
        $this->hasColumn('rate', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'default' => 0,
             ));
        $this->hasColumn('final_amount', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'default' => 0,
             ));
        $this->hasColumn('reduction_percentage', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'default' => 0,
             ));
        $this->hasColumn('reduction_amount', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'default' => 0,
             ));


        $this->index('imported_mos_items_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'root_id',
              2 => 'lft',
              3 => 'rgt',
             ),
             ));
        $this->index('imported_mos_items_fk_idx', array(
             'fields' => 
             array(
              0 => 'imported_material_on_site_id',
              1 => 'root_id',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ImportedMaterialOnSite', array(
             'local' => 'imported_material_on_site_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'levelColumnName' => 'level',
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
    }
}