<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ResourceItemSelectedRate', 'main_conn');

/**
 * BaseResourceItemSelectedRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resource_item_id
 * @property integer $sorting_type
 * @property ResourceItem $ResourceItem
 * @property Doctrine_Collection $RFQItemRates
 * 
 * @method integer                  getResourceItemId()   Returns the current record's "resource_item_id" value
 * @method integer                  getSortingType()      Returns the current record's "sorting_type" value
 * @method ResourceItem             getResourceItem()     Returns the current record's "ResourceItem" value
 * @method Doctrine_Collection      getRFQItemRates()     Returns the current record's "RFQItemRates" collection
 * @method ResourceItemSelectedRate setResourceItemId()   Sets the current record's "resource_item_id" value
 * @method ResourceItemSelectedRate setSortingType()      Sets the current record's "sorting_type" value
 * @method ResourceItemSelectedRate setResourceItem()     Sets the current record's "ResourceItem" value
 * @method ResourceItemSelectedRate setRFQItemRates()     Sets the current record's "RFQItemRates" collection
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResourceItemSelectedRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource_item_selection_of_rates');
        $this->hasColumn('resource_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sorting_type', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('resource_item_uniq_idx', array(
             'fields' => 
             array(
              0 => 'resource_item_id',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ResourceItem', array(
             'local' => 'resource_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('RFQItemRate as RFQItemRates', array(
             'refClass' => 'ResourceSelectionOfRateRfqItemRate',
             'local' => 'resource_item_selection_of_rate_id',
             'foreign' => 'request_for_quotation_item_rate_id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}