<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Menu', 'main_conn');

/**
 * BaseMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $title
 * @property boolean $is_app
 * @property varchar $icon
 * @property varchar $sysname
 * @property integer $priority
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $sfGuardGroupMenu
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method varchar             getTitle()            Returns the current record's "title" value
 * @method boolean             getIsApp()            Returns the current record's "is_app" value
 * @method varchar             getIcon()             Returns the current record's "icon" value
 * @method varchar             getSysname()          Returns the current record's "sysname" value
 * @method integer             getPriority()         Returns the current record's "priority" value
 * @method Doctrine_Collection getGroups()           Returns the current record's "Groups" collection
 * @method Doctrine_Collection getSfGuardGroupMenu() Returns the current record's "sfGuardGroupMenu" collection
 * @method Menu                setId()               Sets the current record's "id" value
 * @method Menu                setTitle()            Sets the current record's "title" value
 * @method Menu                setIsApp()            Sets the current record's "is_app" value
 * @method Menu                setIcon()             Sets the current record's "icon" value
 * @method Menu                setSysname()          Sets the current record's "sysname" value
 * @method Menu                setPriority()         Sets the current record's "priority" value
 * @method Menu                setGroups()           Sets the current record's "Groups" collection
 * @method Menu                setSfGuardGroupMenu() Sets the current record's "sfGuardGroupMenu" collection
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menus');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'varchar', 40, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('is_app', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('icon', 'varchar', 20, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('sysname', 'varchar', 40, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 40,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('menu_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'is_app',
              2 => 'lft',
              3 => 'rgt',
             ),
             ));
        $this->index('menu_root_id_idx', array(
             'fields' => 
             array(
              0 => 'root_id',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardGroupMenu',
             'local' => 'menu_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroupMenu', array(
             'local' => 'id',
             'foreign' => 'menu_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'levelColumnName' => 'level',
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($nestedset0);
    }
}