<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BillMarkupSetting', 'main_conn');

/**
 * BaseBillMarkupSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_structure_id
 * @property boolean $bill_markup_enabled
 * @property decimal $bill_markup_percentage
 * @property decimal $bill_markup_amount
 * @property boolean $element_markup_enabled
 * @property boolean $item_markup_enabled
 * @property integer $rounding_type
 * @property ProjectStructure $ProjectStructure
 * 
 * @method integer           getId()                     Returns the current record's "id" value
 * @method integer           getProjectStructureId()     Returns the current record's "project_structure_id" value
 * @method boolean           getBillMarkupEnabled()      Returns the current record's "bill_markup_enabled" value
 * @method decimal           getBillMarkupPercentage()   Returns the current record's "bill_markup_percentage" value
 * @method decimal           getBillMarkupAmount()       Returns the current record's "bill_markup_amount" value
 * @method boolean           getElementMarkupEnabled()   Returns the current record's "element_markup_enabled" value
 * @method boolean           getItemMarkupEnabled()      Returns the current record's "item_markup_enabled" value
 * @method integer           getRoundingType()           Returns the current record's "rounding_type" value
 * @method ProjectStructure  getProjectStructure()       Returns the current record's "ProjectStructure" value
 * @method BillMarkupSetting setId()                     Sets the current record's "id" value
 * @method BillMarkupSetting setProjectStructureId()     Sets the current record's "project_structure_id" value
 * @method BillMarkupSetting setBillMarkupEnabled()      Sets the current record's "bill_markup_enabled" value
 * @method BillMarkupSetting setBillMarkupPercentage()   Sets the current record's "bill_markup_percentage" value
 * @method BillMarkupSetting setBillMarkupAmount()       Sets the current record's "bill_markup_amount" value
 * @method BillMarkupSetting setElementMarkupEnabled()   Sets the current record's "element_markup_enabled" value
 * @method BillMarkupSetting setItemMarkupEnabled()      Sets the current record's "item_markup_enabled" value
 * @method BillMarkupSetting setRoundingType()           Sets the current record's "rounding_type" value
 * @method BillMarkupSetting setProjectStructure()       Sets the current record's "ProjectStructure" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBillMarkupSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bill_markup_settings');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('project_structure_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bill_markup_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('bill_markup_percentage', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'default' => 0,
             ));
        $this->hasColumn('bill_markup_amount', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'default' => 0,
             ));
        $this->hasColumn('element_markup_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('item_markup_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('rounding_type', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('bill_markup_settings_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'project_structure_id',
              2 => 'rounding_type',
             ),
             ));
        $this->index('bill_markup_settings_unique_idx', array(
             'fields' => 
             array(
              0 => 'project_structure_id',
              1 => 'deleted_at',
             ),
             'type' => 'unique',
             ));
        $this->option('orderBy', 'id');
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProjectStructure', array(
             'local' => 'project_structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($softdelete0);
    }
}