<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PostContractStandardClaimTypeReference', 'main_conn');

/**
 * BasePostContractStandardClaimTypeReference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_contract_id
 * @property integer $bill_column_setting_id
 * @property integer $counter
 * @property string $new_name
 * @property PostContract $PostContract
 * @property BillColumnSetting $BillColumnSetting
 * @property Doctrine_Collection $PostContractStandardClaims
 * @property Doctrine_Collection $TaggedBillItemTypeReferences
 * @property Doctrine_Collection $SubPackagePostContractStandardClaims
 * @property Doctrine_Collection $VariationOrderItemReferences
 * @property Doctrine_Collection $SubPackageVariationOrderItemReferences
 * 
 * @method integer                                getId()                                     Returns the current record's "id" value
 * @method integer                                getPostContractId()                         Returns the current record's "post_contract_id" value
 * @method integer                                getBillColumnSettingId()                    Returns the current record's "bill_column_setting_id" value
 * @method integer                                getCounter()                                Returns the current record's "counter" value
 * @method string                                 getNewName()                                Returns the current record's "new_name" value
 * @method PostContract                           getPostContract()                           Returns the current record's "PostContract" value
 * @method BillColumnSetting                      getBillColumnSetting()                      Returns the current record's "BillColumnSetting" value
 * @method Doctrine_Collection                    getPostContractStandardClaims()             Returns the current record's "PostContractStandardClaims" collection
 * @method Doctrine_Collection                    getTaggedBillItemTypeReferences()           Returns the current record's "TaggedBillItemTypeReferences" collection
 * @method Doctrine_Collection                    getSubPackagePostContractStandardClaims()   Returns the current record's "SubPackagePostContractStandardClaims" collection
 * @method Doctrine_Collection                    getVariationOrderItemReferences()           Returns the current record's "VariationOrderItemReferences" collection
 * @method Doctrine_Collection                    getSubPackageVariationOrderItemReferences() Returns the current record's "SubPackageVariationOrderItemReferences" collection
 * @method PostContractStandardClaimTypeReference setId()                                     Sets the current record's "id" value
 * @method PostContractStandardClaimTypeReference setPostContractId()                         Sets the current record's "post_contract_id" value
 * @method PostContractStandardClaimTypeReference setBillColumnSettingId()                    Sets the current record's "bill_column_setting_id" value
 * @method PostContractStandardClaimTypeReference setCounter()                                Sets the current record's "counter" value
 * @method PostContractStandardClaimTypeReference setNewName()                                Sets the current record's "new_name" value
 * @method PostContractStandardClaimTypeReference setPostContract()                           Sets the current record's "PostContract" value
 * @method PostContractStandardClaimTypeReference setBillColumnSetting()                      Sets the current record's "BillColumnSetting" value
 * @method PostContractStandardClaimTypeReference setPostContractStandardClaims()             Sets the current record's "PostContractStandardClaims" collection
 * @method PostContractStandardClaimTypeReference setTaggedBillItemTypeReferences()           Sets the current record's "TaggedBillItemTypeReferences" collection
 * @method PostContractStandardClaimTypeReference setSubPackagePostContractStandardClaims()   Sets the current record's "SubPackagePostContractStandardClaims" collection
 * @method PostContractStandardClaimTypeReference setVariationOrderItemReferences()           Sets the current record's "VariationOrderItemReferences" collection
 * @method PostContractStandardClaimTypeReference setSubPackageVariationOrderItemReferences() Sets the current record's "SubPackageVariationOrderItemReferences" collection
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostContractStandardClaimTypeReference extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post_contract_standard_claim_type_reference');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('post_contract_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bill_column_setting_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('counter', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('new_name', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));


        $this->index('post_contract_standard_claim_type_reference_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->index('post_contract_standard_claim_type_reference_fk_idx', array(
             'fields' => 
             array(
              0 => 'post_contract_id',
              1 => 'bill_column_setting_id',
             ),
             ));
        $this->index('post_contract_standard_claim_type_reference_unique_idx', array(
             'fields' => 
             array(
              0 => 'post_contract_id',
              1 => 'bill_column_setting_id',
              2 => 'counter',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PostContract', array(
             'local' => 'post_contract_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('BillColumnSetting', array(
             'local' => 'bill_column_setting_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PostContractImportedStandardClaim as PostContractStandardClaims', array(
             'local' => 'id',
             'foreign' => 'claim_type_ref_id'));

        $this->hasMany('ScheduleTaggedBillItemTypeReference as TaggedBillItemTypeReferences', array(
             'local' => 'id',
             'foreign' => 'standard_type_reference_id'));

        $this->hasMany('SubPackagePostContractStandardClaim as SubPackagePostContractStandardClaims', array(
             'local' => 'id',
             'foreign' => 'claim_type_ref_id'));

        $this->hasMany('VariationOrderItemUnit as VariationOrderItemReferences', array(
             'local' => 'id',
             'foreign' => 'type_reference_id'));

        $this->hasMany('SubPackageVariationOrderItemUnit as SubPackageVariationOrderItemReferences', array(
             'local' => 'id',
             'foreign' => 'type_reference_id'));
    }
}