<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ScheduleOfRateBillElement', 'main_conn');

/**
 * BaseScheduleOfRateBillElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * @property string $note
 * @property integer $project_structure_id
 * @property string $tender_origin_id
 * @property integer $priority
 * @property ProjectStructure $ProjectStructure
 * @property Doctrine_Collection $Items
 * 
 * @method integer                   getId()                   Returns the current record's "id" value
 * @method string                    getDescription()          Returns the current record's "description" value
 * @method string                    getNote()                 Returns the current record's "note" value
 * @method integer                   getProjectStructureId()   Returns the current record's "project_structure_id" value
 * @method string                    getTenderOriginId()       Returns the current record's "tender_origin_id" value
 * @method integer                   getPriority()             Returns the current record's "priority" value
 * @method ProjectStructure          getProjectStructure()     Returns the current record's "ProjectStructure" value
 * @method Doctrine_Collection       getItems()                Returns the current record's "Items" collection
 * @method ScheduleOfRateBillElement setId()                   Sets the current record's "id" value
 * @method ScheduleOfRateBillElement setDescription()          Sets the current record's "description" value
 * @method ScheduleOfRateBillElement setNote()                 Sets the current record's "note" value
 * @method ScheduleOfRateBillElement setProjectStructureId()   Sets the current record's "project_structure_id" value
 * @method ScheduleOfRateBillElement setTenderOriginId()       Sets the current record's "tender_origin_id" value
 * @method ScheduleOfRateBillElement setPriority()             Sets the current record's "priority" value
 * @method ScheduleOfRateBillElement setProjectStructure()     Sets the current record's "ProjectStructure" value
 * @method ScheduleOfRateBillElement setItems()                Sets the current record's "Items" collection
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScheduleOfRateBillElement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('schedule_of_rate_bill_elements');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('note', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('project_structure_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tender_origin_id', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('schedule_of_rate_bill_elem_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'project_structure_id',
             ),
             ));
        $this->index('schedule_of_rate_bill_elem_priority_unique_idx', array(
             'fields' => 
             array(
              0 => 'priority',
              1 => 'project_structure_id',
              2 => 'deleted_at',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProjectStructure', array(
             'local' => 'project_structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ScheduleOfRateBillItem as Items', array(
             'local' => 'id',
             'foreign' => 'element_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($softdelete0);
    }
}