<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProjectSummaryBillStyle', 'main_conn');

/**
 * BaseProjectSummaryBillStyle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_structure_id
 * @property string $reference_char
 * @property boolean $is_bold
 * @property boolean $is_italic
 * @property boolean $is_underline
 * @property ProjectStructure $Bill
 * 
 * @method integer                 getId()                   Returns the current record's "id" value
 * @method integer                 getProjectStructureId()   Returns the current record's "project_structure_id" value
 * @method string                  getReferenceChar()        Returns the current record's "reference_char" value
 * @method boolean                 getIsBold()               Returns the current record's "is_bold" value
 * @method boolean                 getIsItalic()             Returns the current record's "is_italic" value
 * @method boolean                 getIsUnderline()          Returns the current record's "is_underline" value
 * @method ProjectStructure        getBill()                 Returns the current record's "Bill" value
 * @method ProjectSummaryBillStyle setId()                   Sets the current record's "id" value
 * @method ProjectSummaryBillStyle setProjectStructureId()   Sets the current record's "project_structure_id" value
 * @method ProjectSummaryBillStyle setReferenceChar()        Sets the current record's "reference_char" value
 * @method ProjectSummaryBillStyle setIsBold()               Sets the current record's "is_bold" value
 * @method ProjectSummaryBillStyle setIsItalic()             Sets the current record's "is_italic" value
 * @method ProjectSummaryBillStyle setIsUnderline()          Sets the current record's "is_underline" value
 * @method ProjectSummaryBillStyle setBill()                 Sets the current record's "Bill" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectSummaryBillStyle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_summary_bill_styles');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('project_structure_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('reference_char', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('is_bold', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_italic', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_underline', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));


        $this->index('project_sum_bill_sty_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'project_structure_id',
             ),
             ));
        $this->index('project_sum_bill_sty_unique_idx', array(
             'fields' => 
             array(
              0 => 'project_structure_id',
             ),
             'type' => 'unique',
             ));
        $this->option('orderBy', 'id');
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProjectStructure as Bill', array(
             'local' => 'project_structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}