<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BillItemPrimeCostRate', 'main_conn');

/**
 * BaseBillItemPrimeCostRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bill_item_id
 * @property decimal $supply_rate
 * @property decimal $wastage_percentage
 * @property decimal $wastage_amount
 * @property decimal $labour_for_installation
 * @property decimal $other_cost
 * @property decimal $profit_percentage
 * @property decimal $profit_amount
 * @property decimal $total
 * @property BillItem $BillItem
 * 
 * @method integer               getId()                      Returns the current record's "id" value
 * @method integer               getBillItemId()              Returns the current record's "bill_item_id" value
 * @method decimal               getSupplyRate()              Returns the current record's "supply_rate" value
 * @method decimal               getWastagePercentage()       Returns the current record's "wastage_percentage" value
 * @method decimal               getWastageAmount()           Returns the current record's "wastage_amount" value
 * @method decimal               getLabourForInstallation()   Returns the current record's "labour_for_installation" value
 * @method decimal               getOtherCost()               Returns the current record's "other_cost" value
 * @method decimal               getProfitPercentage()        Returns the current record's "profit_percentage" value
 * @method decimal               getProfitAmount()            Returns the current record's "profit_amount" value
 * @method decimal               getTotal()                   Returns the current record's "total" value
 * @method BillItem              getBillItem()                Returns the current record's "BillItem" value
 * @method BillItemPrimeCostRate setId()                      Sets the current record's "id" value
 * @method BillItemPrimeCostRate setBillItemId()              Sets the current record's "bill_item_id" value
 * @method BillItemPrimeCostRate setSupplyRate()              Sets the current record's "supply_rate" value
 * @method BillItemPrimeCostRate setWastagePercentage()       Sets the current record's "wastage_percentage" value
 * @method BillItemPrimeCostRate setWastageAmount()           Sets the current record's "wastage_amount" value
 * @method BillItemPrimeCostRate setLabourForInstallation()   Sets the current record's "labour_for_installation" value
 * @method BillItemPrimeCostRate setOtherCost()               Sets the current record's "other_cost" value
 * @method BillItemPrimeCostRate setProfitPercentage()        Sets the current record's "profit_percentage" value
 * @method BillItemPrimeCostRate setProfitAmount()            Sets the current record's "profit_amount" value
 * @method BillItemPrimeCostRate setTotal()                   Sets the current record's "total" value
 * @method BillItemPrimeCostRate setBillItem()                Sets the current record's "BillItem" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBillItemPrimeCostRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bill_item_prime_cost_rates');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('bill_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('supply_rate', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('wastage_percentage', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('wastage_amount', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('labour_for_installation', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('other_cost', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('profit_percentage', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('profit_amount', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('total', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 5,
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('bill_ipcr_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'bill_item_id',
              2 => 'total',
              3 => 'deleted_at',
             ),
             ));
        $this->index('bill_ipcr_unique_idx', array(
             'fields' => 
             array(
              0 => 'bill_item_id',
              1 => 'deleted_at',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BillItem', array(
             'local' => 'bill_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($softdelete0);
    }
}