<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Dimension', 'main_conn');

/**
 * BaseDimension
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $UnitOfMeasurements
 * @property Doctrine_Collection $UnitOfMeasurementDimensions
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method string              getName()                        Returns the current record's "name" value
 * @method Doctrine_Collection getUnitOfMeasurements()          Returns the current record's "UnitOfMeasurements" collection
 * @method Doctrine_Collection getUnitOfMeasurementDimensions() Returns the current record's "UnitOfMeasurementDimensions" collection
 * @method Dimension           setId()                          Sets the current record's "id" value
 * @method Dimension           setName()                        Sets the current record's "name" value
 * @method Dimension           setUnitOfMeasurements()          Sets the current record's "UnitOfMeasurements" collection
 * @method Dimension           setUnitOfMeasurementDimensions() Sets the current record's "UnitOfMeasurementDimensions" collection
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDimension extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dimensions');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));


        $this->index('dimension_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->index('dimension_name_unique_idx', array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'deleted_at',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UnitOfMeasurement as UnitOfMeasurements', array(
             'refClass' => 'UnitOfMeasurementDimensions',
             'local' => 'dimension_id',
             'foreign' => 'unit_of_measurement_id'));

        $this->hasMany('UnitOfMeasurementDimensions', array(
             'local' => 'id',
             'foreign' => 'dimension_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($softdelete0);
    }
}