<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubPackageBillItem', 'main_conn');

/**
 * BaseSubPackageBillItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sub_package_id
 * @property integer $bill_item_id
 * @property SubPackage $SubPackage
 * @property BillItem $BillItem
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method integer            getSubPackageId()   Returns the current record's "sub_package_id" value
 * @method integer            getBillItemId()     Returns the current record's "bill_item_id" value
 * @method SubPackage         getSubPackage()     Returns the current record's "SubPackage" value
 * @method BillItem           getBillItem()       Returns the current record's "BillItem" value
 * @method SubPackageBillItem setId()             Sets the current record's "id" value
 * @method SubPackageBillItem setSubPackageId()   Sets the current record's "sub_package_id" value
 * @method SubPackageBillItem setBillItemId()     Sets the current record's "bill_item_id" value
 * @method SubPackageBillItem setSubPackage()     Sets the current record's "SubPackage" value
 * @method SubPackageBillItem setBillItem()       Sets the current record's "BillItem" value
 * 
 * @package    buildspace
 * @subpackage model
 * @author     1337 developers
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubPackageBillItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_packages_bill_items');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sub_package_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bill_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('sub_package_bill_item_id_idx', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->index('sub_package_bill_item_fk_idx', array(
             'fields' => 
             array(
              0 => 'sub_package_id',
              1 => 'bill_item_id',
             ),
             ));
        $this->index('sub_package_bill_item_unique_idx', array(
             'fields' => 
             array(
              0 => 'sub_package_id',
              1 => 'bill_item_id',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SubPackage', array(
             'local' => 'sub_package_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('BillItem', array(
             'local' => 'bill_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}