define("buildspace/apps/PostContractSubPackageReport/Preliminaries/PreliminariesBillManager","dojo/_base/declare dojo/dom-style dojo/when dojo/currency dojo/store/Memory dijit/layout/ContentPane dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dojo/aspect dojo/request ./PreliminariesBillGrid ./buildUpQuantitySummary ./buildUpQuantityGrid ./TimeBasedFormDialog ./WorkBasedFormDialog ./lumpSumPercentDialog dojo/i18n!buildspace/nls/PostContractSubPackage".split(" "),function(m,E,u,F,n,v,
G,w,H,r,t,x,y,z,A,B,h){var D=m("buildspace.apps.PostContractSubPackageReport.PrelimBillElementContainer",dijit.layout.BorderContainer,{style:"padding:0px;border:0px;width:100%;height:100%;",gutters:!1,billId:null,rootProject:null,subPackage:null,bqVersion:0,columnData:null,currentBillType:null,currentSelectedClaimRevision:null,currentClaimRevision:null,previewElementStore:null,previewItemStore:null,constructor:function(a){this.previewElementStore=[];this.previewItemStore=[];this.inherited(arguments)},
postCreate:function(){this.inherited(arguments);var a=this;a.previewElementStore=new n({idProperty:"id"});a.previewItemStore=new n({idProperty:"id"});a.createElementGrid();dojo.subscribe("subPackageBillGrid"+a.billId+"-stackContainer-selectChild","",function(e){var c=dijit.byId("subPackageBillGrid"+a.billId+"-stackContainer");if(c){var b=c.getChildren();e=dojo.indexOf(b,dijit.byId(e.id));for(e+=1;b.length>e;){c.removeChild(b[e]);b[e].destroyRecursive(!0);e+=1;var d=dijit.byId("add_resource_category_"+
a.billId+"-btn");d&&d.destroy()}}})},createElementGrid:function(){var a=this,e=dijit.byId("subPackageBillGrid"+this.billId+"-stackContainer");e&&dijit.byId("subPackageBillGrid"+this.billId+"-stackContainer").destroyRecursive();var e=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:"subPackageBillGrid"+this.billId+"-stackContainer"}),c=this;dojo.xhrGet({url:"postContractSubPackage/getBillInfo",handleAs:"json",content:{id:this.billId,
sub_package_id:this.subPackage.id}}).then(function(b){try{c.currentBillType=b.bill_type.type;c.currentSelectedClaimRevision=b.current_selected_claim_project_revision_status;c.currentClaimRevision=b.claim_project_revision_status;var d=dojo.data.ItemFileWriteStore({url:"subPackagePostContractPreliminaries/getElementList/id/"+a.billId+"/sub_package_id/"+a.subPackage.id,clearOnClose:!0,urlPreventCache:!0}),f=new t({stackContainerTitle:"Element",billId:c.billId,rootProject:c.rootProject,subPackage:c.subPackage,
pageId:"sub_package_element-page-"+c.billId,id:"sub_package_element-page-container-"+c.billId,gridOpts:{gridContainer:a,store:d,typeColumns:b.column_settings,markupSettings:b.markup_settings,bqCSRFToken:b.bqCSRFToken,currentBillType:c.currentBillType,currentSelectedClaimRevision:c.currentSelectedClaimRevision,currentClaimRevision:c.currentClaimRevision,currentGridType:"element",onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id[0]&&null!==a.description[0]&&""!==a.description[0]&&c.createItemGrid(a,
b,f)}}}),g=new dijit.layout.StackController({region:"top",containerId:"subPackageBillGrid"+c.billId+"-stackContainer"}),h=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"subPackageBillGrid"+c.billId+"-controllerPane",content:g});c.addChild(e);c.addChild(h)}catch(l){console.debug(l)}})},createItemGrid:function(a,e,c){var b=this,d={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM_TEXT,
buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE_TEXT,
buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID_TEXT],values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM,
buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE,buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID]},f={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT],values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER]},g=dojo.xhrGet({url:"billManager/getUnits/billId/"+b.billId,handleAs:"json"}),k=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});k.show();g.then(function(a){return a});
var l=new dojo.data.ItemFileWriteStore({url:"subPackagePostContractPreliminaries/getItemList/id/"+a.id+"/bill_id/"+b.billId+"/sub_package_id/"+b.subPackage.id,clearOnClose:!0});return u(g,function(g){k.hide();try{new t({stackContainerTitle:a.description,billId:b.billId,rootProject:b.rootProject,subPackage:b.subPackage,id:"sub_package_item-page-container-"+b.billId,elementId:a.id,pageId:"sub_package_item-page-"+b.billId,type:"tree",gridOpts:{gridContainer:b,store:l,escapeHTMLInData:!1,typeColumns:e.column_settings,
markupSettings:e.markup_settings,elementGridStore:c,hierarchyTypes:d,hierarchyTypesForHead:f,unitOfMeasurements:g,currentBillType:b.currentBillType,currentSelectedClaimRevision:b.currentSelectedClaimRevision,currentClaimRevision:b.currentClaimRevision,currentGridType:"item",onRowDblClick:function(a){var e=a.cell.field,d=this.getItem(a.rowIndex),f=this.store;a=e.split("-");if(0<d.id[0]){if(d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&"rate"===e)return(new B({itemObj:d,
billGridStore:f,elementGridStore:c,disableEditingMode:!1})).show();if("qty-qty_per_unit"===e&&d["qty-has_build_up"][0]){var g=d["qty-column_id"][0],e=dojo.xhrPost({url:"billBuildUpQuantity/getDimensionColumnStructure",content:{uom_id:d.uom_id[0]},handleAs:"json"}),k=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});k.show();e.then(function(a){b.createBuildUpQuantityContainer(d,a,g,f);k.hide()})}d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||
d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID||a[0]!=buildspace.apps.PostContractSubPackageReport.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED&&a[0]!=buildspace.apps.PostContractSubPackageReport.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED||(a[0]==buildspace.apps.PostContractSubPackageReport.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED?b.timeBasedClaimDialog(d,b.currentClaimRevision,b.currentSelectedClaimRevision,f):a[0]==buildspace.apps.PostContractSubPackageReport.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED&&
b.workBasedClaimDialog(d,b.currentClaimRevision,b.currentSelectedClaimRevision,f))}}}})}catch(q){console.debug(q)}},function(a){})},createBuildUpQuantityContainer:function(a,e,c,b){var d=a.id,f=buildspace.constants.QUANTITY_PER_UNIT_ORIGINAL,g=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;outline:none;",gutters:!1}),k=new w,l=new dojo.data.ItemFileWriteStore({url:"billBuildUpQuantity/getBuildUpQuantityItemList/bill_item_id/"+d+"/bill_column_setting_id/"+c+
"/type/"+f,clearOnClose:!0}),m=[buildspace.constants.SIGN_POSITIVE_TEXT,buildspace.constants.SIGN_NEGATIVE_TEXT],q=[buildspace.constants.SIGN_POSITIVE,buildspace.constants.SIGN_NEGATIVE];b=new x({itemId:d,billColumnSettingId:c,type:f,container:g,billGridStore:b,buildUpGridStore:l,_csrf_token:a._csrf_token,moduleName:"billBuildUpQuantity",editable:!1});try{var p=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:k.rowCountCellFormatter},{name:h.description,field:"description",
width:"auto",editable:!1,cellType:"buildspace.widget.grid.cells.Textarea"},{name:h.factor,field:"factor-value",width:"100px",styles:"text-align:right;",editable:!1,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:k.formulaNumberCellFormatter}];dojo.forEach(e,function(a){p.push({name:a.title,field:a.field_name,width:"100px",styles:"text-align:right;",editable:!1,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:k.formulaNumberCellFormatter})});p.push({name:h.total,field:"total",
width:"100px",styles:"text-align:right;",formatter:k.numberCellFormatter});p.push({name:h.sign,field:"sign",width:"70px",styles:"text-align:center;",editable:!1,cellType:"dojox.grid.cells.Select",options:m,values:q,formatter:k.signCellFormatter});var n=new y({region:"center",billColumnSettingId:c,BillItem:a,type:f,editable:!1,gridOpts:{gridContainer:this,store:l,structure:p,buildUpSummaryWidget:b,currentBillLockedStatus:this.currentBillLockedStatus}});g.addChild(n)}catch(C){console.log(C)}g.addChild(b);
if(e=dijit.byId("subPackageBillGrid"+this.billId+"-stackContainer"))c=document.createElement("div"),a=new dojox.layout.ContentPane({title:buildspace.truncateString(a.description,60)+" ("+h.buildUpQuantity+" - "+a.uom_symbol+")",id:"buildUpQuantityPage-"+d,style:"padding:0px;border:0px;",executeScripts:!0},c),e.addChild(a),a.set("content",g),e.selectChild("buildUpQuantityPage-"+d)},timeBasedClaimDialog:function(a,e,c,b){var d,f;f=this;d=new buildspace.dialog.indeterminateProgressBar({title:""+h.processing+
"..."});d.show();r.get("subPackagePostContractPreliminaries/getTimeBasedInformation",{query:{id:a.sub_package_post_contract_bill_item_rate_id,sub_package_id:f.subPackage.id,bill_id:f.billId},handleAs:"json"}).then(function(c){(new z({itemId:a.sub_package_post_contract_bill_item_rate_id,bill_id:f.billId,subPackage:f.subPackage,formInfo:c.form,item:a,billGridStore:b,currentClaimRevision:e,gridEditable:!1})).show();return d.hide()},function(a){return d.hide()})},workBasedClaimDialog:function(a,e,c,b){var d,
f;f=this;d=new buildspace.dialog.indeterminateProgressBar({title:""+h.processing+"..."});d.show();r.get("subPackagePostContractPreliminaries/getWorkBasedInformation",{query:{id:a.sub_package_post_contract_bill_item_rate_id,sub_package_id:f.subPackage.id,bill_id:f.billId},handleAs:"json"}).then(function(c){(new A({itemId:a.sub_package_post_contract_bill_item_rate_id,bill_id:f.billId,subPackage:f.subPackage,formInfo:c.form,item:a,billGridStore:b,currentClaimRevision:e,gridEditable:!1})).show();return d.hide()},
function(a){return d.hide()})},reconstructBillContainer:function(){var a=dijit.byId("subPackageBillGrid"+this.billId+"-controllerPane"),e=dijit.byId("subPackageBillGrid"+this.billId+"-stackContainer");a.destroyRecursive();e.destroyRecursive();this.createElementGrid()},markedCheckBoxObject:function(a,e){var c=a.store;e.query().forEach(function(b){b.id!=buildspace.constants.GRID_LAST_ROW&&c.fetchItemByIdentity({identity:b.id,onItem:function(b){if(b)return a.rowSelectCell.toggleRow(b._0,!0)}})})}});
return m("buildspace.apps.PostContractSubPackageReport.PrelimBillManager",dijit.layout.TabContainer,{region:"center",rootProject:null,subPackage:null,style:"padding:0px;border:0px;margin:0px;width:100%;height:100%;",billId:null,billLayoutSettingId:null,postCreate:function(){this.inherited(arguments);var a=new D({id:"sub_package_bill_element_container_"+this.subPackage.id+"-bill-"+this.billId,rootProject:this.rootProject,subPackage:this.subPackage,billId:this.billId,bqVersion:0,type:this.type});this.addChild(new v({style:"padding:0px;border:0px;width:100%;height:100%;",
title:h.elementTradeList,content:a}))}})});
