define("buildspace/apps/ResourceLibrary/grid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojo/_base/connect dijit/TooltipDialog dijit/popup dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox ./fileImportDialog dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem ./importResourceItemDialog ./importSORItemDialog ./importBQItemDialog dojo/i18n!buildspace/nls/ResourceLibrary buildspace/widget/grid/Filter".split(" "),
function(w,t,L,M,p,A,q,N,O,B,C,D,E,r,F,P,Q,R,S,u,x,y,k,G,H,I,d,J){var K=w("buildspace.apps.ResourceLibrary.Grid",dojox.grid.EnhancedGrid,{type:null,libraryId:0,tradeId:0,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,checkBeforeDeleteUrl:null,deleteUrl:null,pasteUrl:null,indentUrl:null,outdentUrl:null,constructor:function(a){this.rearranger=B(this,{});this.formulatedColumn=C(this,{})},canSort:function(a){return!1},
canEdit:function(a,b){var c=this;if("tree"==this.type&&void 0!==a){var e=this.getItem(b),d=a.field;if("type"===d){var g=this.getItem(b+1);if(0<e.id[0]&&e.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&void 0!==g&&e.level[0]<g.level[0]){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}}if(0<e.id[0]&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM&&("rate-value"==d||"constant-value"==d||"wastage-value"==d||"uom_id"==d)){window.setTimeout(function(){c.edit.cancel();
c.focus.setFocusIndex(b,a.index)},10);return}}return this._canEdit},postCreate:function(){var a=this,b=null;this.inherited(arguments);this.on("RowContextMenu",function(b){a.selection.clear();var c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b);0<c.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Add","ImportFromLibrary"])},!0);this.on("RowClick",function(b){(b=a.getItem(b.rowIndex))&&0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Add","ImportFromLibrary"])});
"tree"===a.type&&(this._connects.push(p.connect(this,"onCellMouseOver",function(a){var c=a.cell.field,d=a.rowIndex,g=this.getItem(d),c=c.replace("-value","");"undefined"!==typeof g[c+"-has_formula"]&&g[c+"-has_formula"][0]&&(g=g[c+"-value"][0],g=this.formulatedColumn.convertItemIdToRowIndex(g,d),null===b&&(b=new A({content:g,onMouseLeave:function(){q.close(b)}}),q.open({popup:b,around:a.cellNode})))})),this._connects.push(p.connect(this,"onCellMouseOut",function(){null!==b&&(q.close(b),b=null)})),
this._connects.push(p.connect(this,"onStartEdit",function(){null!==b&&(q.close(b),b=null)})))},doApplyCellEdit:function(a,b,c){var e=this,f=e.getItem(b),g=e.store,h=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."}),v=c.replace("-value","");-1!==c.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,b));if(a!==f[c][0]){var z={id:f.id,attr_name:v,val:a,_csrf_token:f._csrf_token?f._csrf_token:null},n=this.updateUrl;f.id==buildspace.constants.GRID_LAST_ROW&&(n=0<
b?e.getItem(b-1):!1,t.mixin(z,{prev_item_id:n?n.id:0,relation_id:f.relation_id}),n=this.addUrl);var l=function(b,a){for(var c in b)f.hasOwnProperty(c)&&c!=a._getIdentifierAttribute()&&a.setValue(f,c,b[c]),dojo.forEach(b.affected_nodes,function(b){a.fetchItemByIdentity({identity:b.id,onItem:function(c){for(var e in b)f.hasOwnProperty(e)&&e!=a._getIdentifierAttribute()&&a.setValue(c,e,b[e])}})});a.save()},m={url:n,content:z,handleAs:"json",load:function(a){if(a.success){0<f.id?l(a.data,g):(g.deleteItem(f),
g.save(),dojo.forEach(a.items,function(b){g.newItem(b)}),g.save(),e.disableToolbarButtons(!0));var d=e.getCellByField(c);window.setTimeout(function(){e.focus.setFocusIndex(b,d.index)},10);h.hide()}},error:function(b){h.hide()}};void 0!=f[v+"-has_build_up"]&&f[v+"-has_build_up"][0]?(buildspace.dialog.confirm(d.confirmation,"<div>"+d.detachAllSelectLink+"</div>",60,280,function(){h.show();dojo.xhrPost(m)}),e.doCancelEdit(b)):(h.show(),dojo.xhrPost(m),e.inherited(arguments))}else e.inherited(arguments)},
dodblclick:function(a){this.onRowDblClick(a)},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==E.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},e=this.getItem(a.rowIndex);b&&e&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&F.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),D.stop(a))},contextMenuItems:function(a){var b=this,c=this.getItem(a.rowIndex);0<c.id&&(b.rowCtxMenu.addChild(new dijit.MenuItem({label:d.cut,
iconClass:"icon-16-container icon-16-cut",onClick:function(){b.pasteType="structure";b.cutItems()}})),b.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:d.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(b,"copyItems")})));b.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:d.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(b,"pasteItem",a.rowIndex),disabled:b.selectedItem?!1:!0}));0<c.id&&"tree"==b.type&&(b.rowCtxMenu.addChild(new dijit.MenuItem({label:d.indent,
iconClass:"icon-16-container icon-16-indent",onClick:dojo.hitch(b,"indentOutdent",a.rowIndex,"indent")})),b.rowCtxMenu.addChild(new dijit.MenuItem({label:d.outdent,iconClass:"icon-16-container icon-16-outdent",onClick:dojo.hitch(b,"indentOutdent",a.rowIndex,"outdent")})));b.rowCtxMenu.addChild(new dijit.MenuItem({label:d.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(b,"addRow",a.rowIndex,"lala")}));0<c.id&&b.rowCtxMenu.addChild(new dijit.MenuItem({label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",
onClick:dojo.hitch(b,"deleteRow",a.rowIndex)}))},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="copy"},pasteItem:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."}),e=b.store,f=b.selection.getFirstSelected(),g=f.id==buildspace.constants.GRID_LAST_ROW&&0<a?b.getItem(a-1).id:0;c.show();dojo.xhrPost({url:this.pasteUrl,content:{type:b.pasteOp,
target_id:f.id,prev_item_id:g,id:b.selectedItem.id,_csrf_token:b.selectedItem._csrf_token},handleAs:"json",load:function(d){var h=[];if(d.success){var g=d.c;switch(b.pasteOp){case "cut":e.fetchItemByIdentity({identity:d.data.id,onItem:function(c){c=b.getItemIndex(c);h.push(c);for(var d=0,f=g.length;d<f;++d)e.fetchItemByIdentity({identity:g[d].id,onItem:function(a){a=b.getItemIndex(a);h.push(a)}});0<h.length&&b.rearranger.moveRows(h,a);b.selectAfterPaste(c>a?a:a-1,!0)}});e.fetchItemByIdentity({identity:d.data.id,
onItem:function(b){for(var a in d.data)b.hasOwnProperty(a)&&a!=e._getIdentifierAttribute()&&e.setValue(b,a,d.data[a]);e.save();var c=0;for(b=g.length;c<b;++c)e.fetchItemByIdentity({identity:g[c].id,onItem:function(b){for(var a in g[c])b.hasOwnProperty(a)&&a!=e._getIdentifierAttribute()&&e.setValue(b,a,g[c][a]);e.save()}})}});break;case "copy":var f=e.newItem(d.data);e.save();f=b.getItemIndex(f);h.push(f);for(var f=0,l=g.length;f<l;++f){var m=e.newItem(g[f]);e.save();m=b.getItemIndex(m);h.push(m)}0<
h.length&&(b.rearranger.moveRows(h,a),b.selectAfterPaste(a,!1))}}b.disableToolbarButtons(!1);b.pasteOp=null;h.length=0;c.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;c.hide()}})},selectAfterPaste:function(a,b){this.selection.clear();this.selectedItem=null;this.selection.setSelected(a,!0);b&&this.scrollToRow(0<a-3?a-3:a)},addRow:function(a){r.curNode.blur();r.curNode=null;var b=this,c,e=buildspace.dialog.indeterminateProgressBar({title:d.addingRow+
". "+d.pleaseWait+"..."}),f=b.store;c=b.getItem(a);if(0<c.id)c={before_id:c.id,_csrf_token:c._csrf_token};else{var g=0<a?b.getItem(a-1).id:0;c={id:c.id,prev_item_id:g,relation_id:c.relation_id,_csrf_token:c._csrf_token}}e.show();dojo.xhrPost({url:this.addUrl,content:c,handleAs:"json",load:function(c){c.success&&dojo.forEach(c.items,function(c){0<c.id&&(c=f.newItem(c),f.save(),c=b.getItemIndex(c),b.rearranger.moveRows([c],a),b.selection.clear())});window.setTimeout(function(){b.selection.setSelected(a,
!0);b.focus.setFocusIndex(a,1)},30);e.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);e.hide()}})},deleteRow:function(a){var b=this,c=b.getItem(a),e=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});r.curNode.blur();r.curNode=null;var f={url:this.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(d){if(d.success){var f=d.items,g=b.store;if(void 0!=d.affected_nodes){d=d.affected_nodes;for(var h=0,l=d.length;h<
l;++h)dojo.forEach(d[h],function(a){g.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var d in a)c.hasOwnProperty(d)&&d!=g._getIdentifierAttribute()&&g.setValue(b,d,a[d])}})})}h=0;for(l=f.length;h<l;++h)g.fetchItemByIdentity({identity:f[h].id,onItem:function(a){g.deleteItem(a);g.save()}});f.length=0}e.hide();b.selection.clear();window.setTimeout(function(){b.focus.setFocusIndex(a,0)},10);b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null},error:function(a){b.selection.clear();
b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;e.hide()}},g={url:this.checkBeforeDeleteUrl,content:{id:c.id},handleAs:"json",load:function(a){a.success&&(a.sorLinkedItems||a.linkedItems?(new buildspace.dialog.alert(b.deleteLinkNotificationTitle,b.deleteLinkNotificationMsg,60,300),e.hide()):a.hasRowLinking?(new buildspace.dialog.alert(d.deleteRowLinkingNotificationTitle,d.deleteRowLinkingNotificationMsg,60,300),e.hide()):new buildspace.dialog.confirm(b.deleteLinkNormalTitle,b.deleteLinkNormalMsg,
80,320,function(){dojo.xhrPost(f)},function(){e.hide()}))},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;e.hide()}};e.show();dojo.xhrGet(g)},indentOutdent:function(a,b){var c=this,e=c.store;if(0<a){var f=c.getItem(a),g=buildspace.dialog.indeterminateProgressBar({title:d.recalculateRows+". "+d.pleaseWait+"..."});g.show();0<f.id&&dojo.xhrPost({url:this[b+"Url"],content:{id:f.id,_csrf_token:f._csrf_token},handleAs:"json",load:function(a){if(a.success){var b=
a.c,c;for(c in a.item)a.item.hasOwnProperty(c)&&c!=e._getIdentifierAttribute()&&e.setValue(f,c,a.item[c]);var d=0;for(a=b.length;d<a;++d)e.fetchItemByIdentity({identity:b[d].id,onItem:function(a){for(var c in b[d])a.hasOwnProperty(c)&&c!=e._getIdentifierAttribute()&&e.setValue(a,c,b[d][c])}});e.save()}g.hide()},error:function(a){c.selection.clear();c.disableToolbarButtons(!0);g.hide()}})}},disableToolbarButtons:function(a,b){var c=dijit.byId(this.libraryId+"_"+this.tradeId+"AddRow-button"),d=dijit.byId(this.libraryId+
"_"+this.tradeId+"DeleteRow-button"),f=dijit.byId(this.libraryId+"_"+this.tradeId+"Indent-button"),g=dijit.byId(this.libraryId+"_"+this.tradeId+"Outdent-button"),h=dijit.byId(this.libraryId+"_"+this.tradeId+"ImportFromLibraryRow-button");c._setDisabledAttr(a);d._setDisabledAttr(a);f&&f._setDisabledAttr(a);g&&g._setDisabledAttr(a);h&&h._setDisabledAttr(a);if(a&&b instanceof Array){var k=this;dojo.forEach(b,function(a){(a=dijit.byId(k.libraryId+"_"+k.tradeId+a+"Row-button"))&&a._setDisabledAttr(!1)})}},
doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,p.disconnect);delete this._connects}});return w("buildspace.apps.ResourceLibrary.grid",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;border:0px;width:100%;height:100%;",gutters:!1,stackContainerTitle:null,libraryId:0,tradeId:0,gridOpts:{},type:null,postCreate:function(){var a=this,b;this.inherited(arguments);
t.mixin(a.gridOpts,{libraryId:a.libraryId,tradeId:a.tradeId,type:a.type,region:"center",borderContainerWidget:a});var c=this.grid=new K(a.gridOpts),e=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});e.addChild(new dijit.form.Button({id:a.libraryId+"_"+a.tradeId+"AddRow-button",label:d.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<c.selection.selectedIndex?!1:!0,onClick:function(){-1<c.selection.selectedIndex&&c.addRow(c.selection.selectedIndex)}}));
"tree"==a.type&&(e.addChild(new dijit.ToolbarSeparator),e.addChild(new dijit.form.Button({id:a.libraryId+"_"+a.tradeId+"Indent-button",label:d.indent,iconClass:"icon-16-container icon-16-indent",disabled:-1<c.selection.selectedIndex?!1:!0,onClick:function(){-1<c.selection.selectedIndex&&c.indentOutdent(c.selection.selectedIndex,"indent")}})),e.addChild(new dijit.ToolbarSeparator),e.addChild(new dijit.form.Button({id:a.libraryId+"_"+a.tradeId+"Outdent-button",label:d.outdent,iconClass:"icon-16-container icon-16-outdent",
disabled:-1<c.selection.selectedIndex?!1:!0,onClick:function(){-1<c.selection.selectedIndex&&c.indentOutdent(c.selection.selectedIndex,"outdent")}})),b=[{description:d.description},{"constant-final_value":d.constant},{uom_symbol:d.unit},{"rate-final_value":d.rate},{"wastage-final_value":d.wastage+" (%)"}]);e.addChild(new dijit.ToolbarSeparator);e.addChild(new dijit.form.Button({id:a.libraryId+"_"+a.tradeId+"DeleteRow-button",label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<
c.selection.selectedIndex?!1:!0,onClick:function(){-1<c.selection.selectedIndex&&c.deleteRow(c.selection.selectedIndex)}}));if("tree"!=a.type)b=new y({style:"display: none;"}),b.addChild(new k({label:d.importFromBuildsoft,onClick:function(b){(new u({resourceId:a.libraryId,importType:buildspace.constants.FILE_IMPORT_TYPE_BUILDSOFT,uploadUrl:"resourceLibrary/importBuildsoftExcel",title:d.importFromBuildsoft,resourceGrid:c})).show()}})),b.addChild(new k({label:d.importFromExcel,onClick:function(b){(new u({resourceId:a.libraryId,
importType:buildspace.constants.FILE_IMPORT_TYPE_EXCEL,uploadUrl:"resourceLibrary/previewImportedFile",title:d.importFromExcel,resourceGrid:c})).show()}})),b.addChild(new k({label:d.importFromPricelist,onClick:function(b){(new u({resourceId:a.libraryId,importType:buildspace.constants.FILE_IMPORT_TYPE_PRICELIST,uploadUrl:"resourceLibrary/importPricelist",title:d.importFromPricelist,resourceGrid:c})).show()}})),e.addChild(new dijit.ToolbarSeparator),e.addChild(new x({label:d.importFromFiles,iconClass:"icon-16-container icon-16-import",
dropDown:b})),b=[{description:d.description}];else{var f=new y({style:"display: none;"});f.addChild(new k({label:d.importFromResource,onClick:function(b){-1<c.selection.selectedIndex&&(new G({title:d.importFromResource,libraryId:a.libraryId,tradeId:a.tradeId,selectedItem:c.selection.getFirstSelected(),resourceGrid:c})).show()}}));f.addChild(new k({label:d.importFromScheduleOfRate,onClick:function(b){-1<c.selection.selectedIndex&&(new H({title:d.importFromScheduleOfRate,libraryId:a.libraryId,tradeId:a.tradeId,
selectedItem:c.selection.getFirstSelected(),resourceGrid:c})).show()}}));f.addChild(new k({label:d.importFromBQLibrary,onClick:function(b){-1<c.selection.selectedIndex&&(new I({title:d.importFromBQLibrary,libraryId:a.libraryId,tradeId:a.tradeId,selectedItem:c.selection.getFirstSelected(),resourceGrid:c})).show()}}));e.addChild(new dijit.ToolbarSeparator);e.addChild(new x({id:a.libraryId+"_"+a.tradeId+"ImportFromLibraryRow-button",label:d.importLibrary,iconClass:"icon-16-container icon-16-import",
dropDown:f,disabled:-1<c.selection.selectedIndex?!1:!0}))}a.addChild(new J({grid:a.grid,region:"top",editableGrid:!0,filterFields:b}));a.addChild(e);a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:c,region:"center"}));if(e=dijit.byId("resourceLibraryGrid"+this.libraryId+"-stackContainer"))b=document.createElement("div"),b=new dojox.layout.ContentPane({title:buildspace.truncateString(a.stackContainerTitle,60),id:a.pageId,executeScripts:!0},b),e.addChild(b),b.set("content",a),t.mixin(b,
{grid:c}),e.selectChild(a.pageId)}})});
