(function(){define("buildspace/apps/PostContractSubPackageReport/BillManager/PrintPreviewElementByTypesDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json dojo/number dojo/currency ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(e,r,t,u,v,w,x,l,m,n,y,z,A,p,q,d){var h,k;h=e("buildspace.apps.PostContractSubPackageReport.StandardBillClaim.SelectedItemGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){this.inherited(arguments);dojo.style(a.node.children[0].children[0].rows[1],"display","none");return dojo.style(a.node.children[0].children[0].rows[2],"display","none")}});k=e("buildspace.apps.PostContractSubPackageReport.StandardBillClaim.SelectedItemGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,
subPackageId:-1,billId:-1,dialog:null,store:null,structure:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new h({store:b.store,structure:b.structure});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,
iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return n("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new p({title:a.dialog.title,printURL:"postContractSubPackageStandardBill/printElementByTypes",
exportURL:"postContractSubPackageStandardBillExportExcelReporting/exportExcelElementByTypes",subPackageId:a.subPackageId,billId:a.billId,_csrf_token:c._csrf_token});b.hide();return c.show()},function(){return b.hide()})}});return e("buildspace.apps.PostContractSubPackageReport.StandardBillClaim.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,data:null,subPackageId:-1,billId:-1,columnSettings:null,buildRendering:function(){var a;a=this.createContent();a.startup();
this.content=a;return this.inherited(arguments)},postCreate:function(){m.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===l.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(a){var b;null==a&&(a=this);b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});a=new k({dialog:a,structure:a.constructGridStructure(),
subPackageId:a.subPackageId,billId:a.billId,store:dojo.data.ItemFileWriteStore({data:a.data})});b.addChild(a);return b},constructGridStructure:function(a){var b,c,g,f,e;null==a&&(a=this);f=new q;g=0;e=[];c=[];b={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:f.rowCountCellFormatter,rowSpan:3},{name:d.description,field:"description",width:"500px",formatter:f.postContractPrintPreviewTreeCellFormatter,noresize:!0,rowSpan:3}]]};dojo.forEach(a.columnSettings,
function(a){g++;c.push({name:d.workDone,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+g,colSpan:2,noresize:!0});e.push({name:a.name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+g,colSpan:3,noresize:!0});b.cells[0].push({name:d.contractAmount,field:a.id+"-grand_total",styles:"text-align:right;color:blue;",width:"110px",formatter:f.unEditableNumberCellFormatter,noresize:!0,rowSpan:2});b.cells[0].push({name:d.percent,field:a.id+"-type_total_percentage",width:"75px",
styles:"text-align:right;",formatter:f.unEditablePercentageCellFormatter,noresize:!0});return b.cells[0].push({name:d.amount,field:a.id+"-type_total_up_to_date_amount",width:"100px",styles:"text-align:right;",formatter:f.unEditableCurrencyCellFormatter,noresize:!0})});b.cells.push(c);b.cells.push(e);return b}})})}).call(this);
