(function(){define("buildspace/apps/PostContractSubPackageReport/BillManager/PrintPreviewElementByTypesByUnitsWithClaimDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json dojo/number dojo/currency ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(e,y,z,A,B,C,D,t,u,v,E,F,G,w,x,d){var g,r;g=e("buildspace.apps.PostContractSubPackageReport.StandardBillClaim.SelectedItemGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){this.inherited(arguments);dojo.style(a.node.children[0].children[0].rows[1],"display","none");return dojo.style(a.node.children[0].children[0].rows[2],"display","none")}});r=e("buildspace.apps.PostContractSubPackageReport.StandardBillClaim.SelectedItemGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,
dialog:null,subPackageId:-1,billId:-1,printURL:null,exportURL:null,store:null,structure:null,selectedRows:[],postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new g({store:b.store,structure:b.structure});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,
iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return v.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new w({title:a.dialog.title,subPackageId:a.subPackageId,billId:a.billId,
printURL:a.printURL,exportURL:a.exportURL,selectedRows:a.selectedRows,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return e("buildspace.apps.PostContractSubPackageReport.StandardBillClaim.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,data:null,subPackageId:-1,billId:-1,printURL:null,exportURL:null,columnSettings:[],dynamicUnitStructure:[],selectedRows:[],buildRendering:function(){var a;a=this.createContent();a.startup();
this.content=a;return this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===t.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(a){var b;null==a&&(a=this);b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});a=new r({dialog:a,structure:a.constructGridStructure(),
store:dojo.data.ItemFileWriteStore({data:a.data}),selectedRows:a.selectedRows,subPackageId:a.subPackageId,billId:a.billId,printURL:a.printURL,exportURL:a.exportURL});b.addChild(a);return b},constructGridStructure:function(a){var b,c,m,h,k,l,f,e,n,g,p,q;null==a&&(a=this);f=new x;h=0;e=[];m=[];c={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:f.rowCountCellFormatter,rowSpan:3},{name:d.description,field:"description",width:0<Object.keys(a.columnSettings).length?
"500px":"auto",formatter:f.postContractPrintPreviewTreeCellFormatter,noresize:!0,rowSpan:3}]]};p=a.columnSettings;for(l in p){k=p[l];b=0;h++;m.push({name:d.workDone,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+h,colSpan:2,noresize:!0});c.cells[0].push({name:d.contractAmount,field:k.id+"-grand_total",styles:"text-align:right;color:blue;",width:"110px",formatter:f.unEditableNumberCellFormatter,noresize:!0,rowSpan:2});c.cells[0].push({name:d.percent,field:k.id+"-type_total_percentage",
width:"75px",styles:"text-align:right;",formatter:f.unEditablePercentageCellFormatter,noresize:!0});c.cells[0].push({name:d.amount,field:k.id+"-type_total_up_to_date_amount",width:"100px",styles:"text-align:right;",formatter:f.unEditableCurrencyCellFormatter,noresize:!0});if(a.dynamicUnitStructure[l])for(g in b=a.dynamicUnitStructure[l].length,q=a.dynamicUnitStructure[l],q)n=q[g],m.push({name:n.new_name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+h,noresize:!0}),c.cells[0].push({name:d.percent,
field:n.id+"-unit_total_percentage",width:"75px",styles:"text-align:right;",formatter:f.unEditablePercentageCellFormatter,noresize:!0});e.push({name:k.name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+h,colSpan:3+b,noresize:!0})}c.cells.push(m);c.cells.push(e);return c}})})}).call(this);
