var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){if(a==Array.prototype||a==Object.prototype)return a;a[d]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var c=a[d];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,d){var c=$jscomp.propertyToPolyfillSymbol[d];if(null==c)return a[d];c=a[c];return void 0!==c?c:a[d]};
$jscomp.polyfill=function(a,d,c,k){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,d,c,k):$jscomp.polyfillUnisolated(a,d,c,k))};$jscomp.polyfillUnisolated=function(a,d,c,k){c=$jscomp.global;a=a.split(".");for(k=0;k<a.length-1;k++){var l=a[k];if(!(l in c))return;c=c[l]}a=a[a.length-1];k=c[a];d=d(k);d!=k&&null!=d&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(a,d,c,k){var l=a.split(".");a=1===l.length;k=l[0];k=!a&&k in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var z=0;z<l.length-1;z++){var E=l[z];if(!(E in k))return;k=k[E]}l=l[l.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?k[l]:null;d=d(c);null!=d&&(a?$jscomp.defineProperty($jscomp.polyfills,l,{configurable:!0,writable:!0,value:d}):d!==c&&($jscomp.propertyToPolyfillSymbol[l]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(l):$jscomp.POLYFILL_PREFIX+l,l=
$jscomp.propertyToPolyfillSymbol[l],$jscomp.defineProperty(k,l,{configurable:!0,writable:!0,value:d})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var d=function(l,z){this.$jscomp$symbol$id_=l;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:z})};d.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,k=function(l){if(this instanceof k)throw new TypeError("Symbol is not a constructor");return new d("jscomp_symbol_"+(l||"")+"_"+c++,l)};return k},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var d="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<d.length;c++){var k=$jscomp.global[d[c]];"function"===typeof k&&"function"!=typeof k.prototype[a]&&$jscomp.defineProperty(k.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,d){a instanceof String&&(a+="");var c=0,k=!1,l={next:function(){if(!k&&c<a.length){var z=c++;return{value:d(z,a[z]),done:!1}}k=!0;return{done:!0,value:void 0}}};l[Symbol.iterator]=function(){return l};return l};
$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(d,c){return c})}},"es8","es3");
define("buildspace/apps/ProjectBuilder/BillManager","dojo/_base/declare dojo/dom-style dojo/when dojo/currency dijit/layout/AccordionContainer dijit/layout/ContentPane dojox/grid/EnhancedGrid ./BillManager/BillPropertiesForm ./BillPrintoutSetting/masterContainer ./BillManager/BillGrid ./BillManager/buildUpGrid ./BillManager/buildUpQuantityGrid ./BillManager/buildUpRateSummary ./BillManager/buildUpQuantitySummary ./BillManager/itemHtmlEditorDialog ./BillManager/primeCostRateDialog ./BillManager/lumpSumPercentDialog ./BillManager/AddResourceCategoryDialog ./BillManager/ScheduleOfQuantityGrid buildspace/widget/grid/cells/Formatter dojo/aspect dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(a,
d,c,k,l,z,E,I,J,F,K,L,M,N,O,P,Q,R,S,G,T,h){var U=a("buildspace.apps.ProjectBuilder.BillPropertiesContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;margin:0px;border:0px;height:100%;",gutters:!1,billId:null,billType:null,projectBreakdownGrid:null,billElementObj:null,postCreate:function(){this.inherited(arguments);if(this.billType==buildspace.constants.BILL_TYPE_PRELIMINARY||this.billType==buildspace.constants.BILL_TYPE_PRIMECOST)var b=!0;b=this.billPropertiesForm=I({billId:this.billId,
projectBreakdownGrid:this.projectBreakdownGrid,tenderAlternativeBillGridId:this.tenderAlternativeBillGridId,billElementObj:this.billElementObj,locked:b?b:!1});this.addChild(b)}}),V=a("buildspace.apps.ProjectBuilder.BillElementContainer",dijit.layout.BorderContainer,{style:"padding:0;margin:0px;border:none;width:100%;height:100%;",gutters:!1,billId:null,rootProject:null,bqVersion:0,columnData:null,projectBreakdownGrid:null,tenderAlternativeBillGridId:null,currentBQAddendumId:-1,currentBillLockedStatus:!1,
postCreate:function(){this.inherited(arguments);this.createElementGrid();var b=this.billId;dojo.subscribe("billGrid"+b+"-stackContainer-selectChild","",function(q){var e=dijit.byId("billGrid"+b+"-stackContainer");if(e){var f=e.getChildren(),n=dojo.indexOf(f,q);n+=1;if(f.length>n){for(;f.length>n;){e.removeChild(f[n]);f[n].destroyDescendants();f[n].destroyRecursive();n+=1;var t=dijit.byId("add_resource_category_"+b+"-btn");t&&t.destroy()}if(q.grid){var m=q.grid.selection.selectedIndex;q.grid.store.save();
q.grid.store.close();var p=T.after(q.grid,"_onFetchComplete",function(){p.remove();-1<m&&(this.scrollToRow(m),this.selection.setSelected(m,!0))});q.grid.sort()}}}})},createElementGrid:function(){var b=dijit.byId("billGrid"+this.billId+"-stackContainer");b&&dijit.byId("billGrid"+this.billId+"-stackContainer").destroyRecursive();b=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:"billGrid"+this.billId+"-stackContainer"});var q=dojo.data.ItemFileWriteStore({url:"billManager/getElementList/id/"+
this.billId,clearOnClose:!0,urlPreventCache:!0}),e=this;dojo.xhrGet({url:"billManager/getBillInfo",handleAs:"json",content:{id:this.billId}}).then(function(f){try{e.currentBQAddendumId=f.project_revision_status.id;parseInt(String(e.rootProject.status_id))!=buildspace.constants.STATUS_PRETENDER&&(e.currentBillLockedStatus=!0);var n=new F({stackContainerTitle:"Element",billId:e.billId,pageId:"element-page-"+e.billId,id:"element-page-container-"+e.billId,gridOpts:{store:q,typeColumns:f.column_settings,
markupSettings:f.markup_settings,bqCSRFToken:f.bqCSRFToken,addUrl:"billManager/elementAdd",updateUrl:"billManager/elementUpdate",rowUpdateUrl:"billManager/elementRowUpdate",deleteUrl:"billManager/elementDelete",pasteUrl:"billManager/elementPaste",currentBQAddendumId:e.currentBQAddendumId,currentBillLockedStatus:e.currentBillLockedStatus,currentGridType:"element",onRowDblClick:function(m){m=this.getItem(m.rowIndex);0<parseInt(String(m.id))&&null!==String(m.description)&&""!==String(m.description)&&
e.createItemGrid(m,f,n)}}}),t=new dijit.layout.StackController({region:"top",containerId:"billGrid"+e.billId+"-stackContainer"});e.addChild(b);e.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"billGrid"+e.billId+"-controllerPane",content:t}))}catch(m){console.debug(m)}})},createItemGrid:function(b,q,e){var f=this,n={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT,
buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT_TEXT,
buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID_TEXT],values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE,
buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE,buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID]},t={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT],
values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER]},m=new dojo.data.ItemFileWriteStore({url:"billManager/getItemList/id/"+b.id+"/bill_id/"+f.billId,clearOnClose:!0}),p=dojo.xhrGet({url:"billManager/getUnits/billId/"+f.billId,handleAs:"json"}),r=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});r.show();return c(p,function(D){r.hide();try{new F({stackContainerTitle:b.description,billId:f.billId,id:"item-page-container-"+
f.billId,elementId:b.id,pageId:"item-page-"+f.billId,type:"tree",gridOpts:{store:m,escapeHTMLInData:!1,typeColumns:q.column_settings,markupSettings:q.markup_settings,elementGridStore:e,hierarchyTypes:n,hierarchyTypesForHead:t,unitOfMeasurements:D,addUrl:"billManager/itemAdd",updateUrl:"billManager/itemUpdate",rowUpdateUrl:"billManager/itemRowUpdate",deleteUrl:"billManager/itemDelete",deleteRateUrl:"billManager/itemRateDelete",deleteQuantityUrl:"billManager/itemQuantityDelete",pasteUrl:"billManager/itemPaste",
indentUrl:"billManager/itemIndent",outdentUrl:"billManager/itemOutdent",currentBQAddendumId:f.currentBQAddendumId,currentBillLockedStatus:f.currentBillLockedStatus,currentGridType:"item",editableCellDblClick:function(y){var w=y.cell.field,g=this.getItem(y.rowIndex),u=this.store;if(g&&void 0!==g.project_revision_deleted_at&&g.project_revision_deleted_at[0])return!1;if("rate-value"==w&&0<parseInt(String(g.id)))parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM||parseInt(String(g.type))==
buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR||parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL||parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY||parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED||parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM||parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE?
f.createBuildUpRateContainer(g,u):parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE?(new P({itemObj:g,billGridStore:u,elementGridStore:e,currentBillLockedStatus:f.currentBillLockedStatus})).show():parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&(new Q({itemObj:g,billGridStore:u,elementGridStore:e,currentBillLockedStatus:f.currentBillLockedStatus})).show();else{var A=!1,v=y.cell.billColumnSettingId;w.match(/-quantity_per_unit-value/gi)?
A=buildspace.constants.QUANTITY_PER_UNIT_ORIGINAL:w.match(/-quantity_per_unit_remeasurement-value/gi)&&(A=buildspace.constants.QUANTITY_PER_UNIT_REMEASUREMENT);if(A&&0<parseInt(String(g.id))&&"true"==g[v+"-include"][0]&&parseInt(String(g.type))!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&parseInt(String(g.type))!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&parseInt(String(g.type))!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&parseInt(String(g.type))!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&
parseInt(String(g.type))!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&parseInt(String(g.type))!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY)if(0<parseInt(String(g.uom_id))){var B=dojo.xhrPost({url:"billBuildUpQuantity/getDimensionColumnStructure",content:{uom_id:parseInt(String(g.uom_id))},handleAs:"json"}),C=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});C.show().then(function(){B.then(function(x){f.createBuildUpQuantityContainer(g,
x,v,A);C.hide()})})}else buildspace.dialog.alert(h.buildUpQtyAlert,h.pleaseSetUOM,60,300);"description"==w&&0<parseInt(String(g.id))&&(parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR||parseInt(String(g.type))==buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID)&&(new O({itemObj:g,billId:f.billId,billGridStore:u,currentBillLockedStatus:f.currentBillLockedStatus})).show()}}}})}catch(y){console.debug(y)}},function(D){})},createBuildUpRateContainer:function(b,
q){var e=this,f=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation,n=new dijit.layout.BorderContainer({style:"padding:0px;margin:0px;width:100%;height:100%;border:0px;outline:none;",gutters:!1}),t=new dijit.layout.AccordionContainer({id:"accordian_"+e.billId+"_"+b.id+"-container",region:"center",style:"padding:0px;margin:0px;width:100%;height:100%;border:0px;outline:none;"}),m=dojo.xhrGet({url:"billBuildUpRate/resourceList/item_id/"+b.id,handleAs:"json"}),
p=new G,r=dojo.xhrGet({url:"billBuildUpRate/getUnits",handleAs:"json"}),D=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});D.show();r.then(function(y){c(m,function(w){if(0==w.length)t.addChild(new dijit.layout.ContentPane({title:h.emptyResourceCategoryTitle,style:"padding:0px;border:0px;",doLayout:!1,id:"accPane-empty_resource-"+b.id,content:'<div style="text-align:center;"><p><h1>'+h.emptyResourceCategory+"</h1></p></div> "}));else{var g=new M({id:"buildUpRateSummary-"+b.id,
itemId:b.id,container:n,billGridStore:q,_csrf_token:b._csrf_token,currentBillLockedStatus:e.currentBillLockedStatus});dojo.forEach(w,function(v){var B=new dojo.data.ItemFileWriteStore({url:"billBuildUpRate/getBuildUpRateItemList/bill_item_id/"+b.id+"/resource_id/"+v.id,clearOnClose:!0});try{var C=new K({resource:v,BQItem:b,gridOpts:{itemId:b.id,addUrl:"billBuildUpRate/buildUpRateItemAdd",updateUrl:"billBuildUpRate/buildUpRateItemUpdate",deleteUrl:"billBuildUpRate/buildUpRateItemDelete",pasteUrl:"billBuildUpRate/buildUpRateItemPaste",
store:B,buildUpSummaryWidget:g,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:p.rowCountCellFormatter},{name:h.description,field:"description",width:"auto",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:p.linkedCellFormatter},{name:h.number,field:"number-value",width:"100px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:p.formulaCurrencyCellFormatter},{name:h.constant,field:"constant-value",
width:"100px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:p.formulaCurrencyCellFormatter},{name:h.qty,field:"quantity-value",width:"70px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:p.formulaNumberCellFormatter},{name:h.unit,field:"uom_id",width:"70px",styles:"text-align:center;",editable:!0,cellType:"dojox.grid.cells.Select",options:y.options,values:y.values,formatter:p.linkedUnitIdCellFormatter},
{name:h.rate,field:"rate-value",width:"120px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:p.formulaCurrencyCellFormatter},{name:h.total,field:"total",width:"120px",styles:"text-align:right;",formatter:p.linkedCurrencyCellFormatter},{name:h.wastage+" (%)",field:"wastage-value",width:"70px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:p.formulaCurrencyCellFormatter},{name:h.lineTotal,
field:"line_total",width:"120px",styles:"text-align:right;",formatter:p.linkedCurrencyCellFormatter}],currentBillLockedStatus:e.currentBillLockedStatus}});t.addChild(new dijit.layout.ContentPane({title:v.name+'<span style="color:blue;float:right;">'+f+"&nbsp;"+k.format(v.total_build_up)+"</span>",style:"padding:0px;border:0px;",doLayout:!1,id:"accPane-"+v.id+"-"+b.id,content:C}))}catch(x){console.log(x)}});n.addChild(g)}n.addChild(t);if(w=dijit.byId("billGrid"+e.billId+"-stackContainer")){var u=dijit.byId("billGrid"+
e.billId+"-controllerPane"),A=new dijit.form.Button({id:"add_resource_category_"+e.billId+"-btn",label:h.addResourceCategory,style:"float:right;color:#333333!important;",iconClass:"icon-16-container icon-16-add",baseClass:"buildUpRateImportResourceCategory",disabled:e.currentBillLockedStatus?!0:!1,onClick:function(v){R({billId:e.billId,billItem:b,currencyAbbr:f,billGridStore:q,baseContainer:n}).show()}});u.addChild(A);u=document.createElement("div");u=new dojox.layout.ContentPane({title:buildspace.truncateString(b.description,
60)+" ("+h.buildUpRate+")",style:"padding:0px;border:0px;",id:"buildUpRatePage-"+b.id,content:n,executeScripts:!0},u);w.addChild(u);w.selectChild("buildUpRatePage-"+b.id)}D.hide()})})},createBuildUpQuantityContainer:function(b,q,e,f){var n=this,t,m=new dijit.layout.BorderContainer({style:"padding:0px;margin:0px;width:100%;height:100%;border:0px;outline:none;",gutters:!1}),p=new dijit.layout.TabContainer({nested:!0,style:"padding:0;border:none;margin:0;width:100%;height:100%;",region:"center"}),r=
new G,D=dojo.xhrGet({url:"billBuildUpQuantity/getLinkInfo/id/"+b.id+"/bcid/"+e+"/t/"+f,handleAs:"json"}),y=new dojo.data.ItemFileWriteStore({url:"billBuildUpQuantity/getBuildUpQuantityItemList/bill_item_id/"+b.id+"/bill_column_setting_id/"+e+"/type/"+f,clearOnClose:!0}),w=[buildspace.constants.SIGN_POSITIVE_TEXT,buildspace.constants.SIGN_NEGATIVE_TEXT],g=[buildspace.constants.SIGN_POSITIVE,buildspace.constants.SIGN_NEGATIVE],u=!1,A=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});
A.show();var v=this.currentBillLockedStatus;D.then(function(B){var C=[{name:"No.",field:"id",styles:"text-align:center;",width:"30px",formatter:r.rowCountCellFormatter},{name:h.description,field:"description",width:"auto",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea"},{name:h.factor,field:"factor-value",width:"100px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:r.formulaNumberCellFormatter}];dojo.forEach(q,function(H){C.push({name:H.title,
field:H.field_name,width:"100px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:r.formulaNumberCellFormatter})});C.push({name:h.total,field:"total",width:"100px",styles:"text-align:right;",formatter:r.numberCellFormatter});C.push({name:h.sign,field:"sign",width:"70px",styles:"text-align:center;",editable:!0,cellType:"dojox.grid.cells.Select",options:w,values:g,formatter:r.signCellFormatter});var x=new N({itemId:b.id,billColumnSettingId:e,type:f,
hasLinkedQty:B.has_linked_qty,container:m,_csrf_token:b._csrf_token,disableEditingMode:v});B.has_linked_qty&&(u=!0,t=S({title:h.scheduleOfQuantities,BillItem:b,billColumnSettingId:e,disableEditingMode:v,stackContainerId:"billGrid"+n.billId+"-stackContainer",gridOpts:{qtyType:f,buildUpSummaryWidget:x,store:new dojo.data.ItemFileWriteStore({url:"billBuildUpQuantity/getScheduleOfQuantities/id/"+b.id+"/bcid/"+e+"/type/"+f,clearOnClose:!0}),structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",
formatter:r.rowCountCellFormatter},{name:h.description,field:"description",width:"auto",formatter:r.treeCellFormatter},{name:h.type,field:"type",width:"70px",styles:"text-align:center;",formatter:r.typeCellFormatter},{name:h.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:r.unitIdCellFormatter},{name:h.qty,field:"quantity-value",width:"100px",styles:"text-align:right;",formatter:r.formulaNumberCellFormatter}]}}));p.addChild(new L({title:h.manualQtyItems,billColumnSettingId:e,
BillItem:b,type:f,disableEditingMode:v,gridOpts:{addUrl:"billBuildUpQuantity/buildUpQuantityItemAdd",updateUrl:"billBuildUpQuantity/buildUpQuantityItemUpdate",deleteUrl:"billBuildUpQuantity/buildUpQuantityItemDelete",pasteUrl:"billBuildUpQuantity/buildUpQuantityItemPaste",store:y,structure:C,buildUpSummaryWidget:x}}));u&&p.addChild(t);m.addChild(p);m.addChild(x);if(B=dijit.byId("billGrid"+n.billId+"-stackContainer"))x=document.createElement("div"),x=new dojox.layout.ContentPane({title:buildspace.truncateString(b.description,
60)+" ("+h.buildUpQuantity+" - "+b.uom_symbol+")",id:"buildUpQuantityPage-"+b.id,content:m,grid:u?t.grid:null,style:"padding:0px;border:0px;",executeScripts:!0},x),B.addChild(x),B.selectChild("buildUpQuantityPage-"+b.id);A.hide()})},reconstructBillContainer:function(){dijit.byId("billGrid"+this.billId+"-controllerPane").destroyRecursive();dijit.byId("billGrid"+this.billId+"-stackContainer").destroyRecursive();this.createElementGrid()}}),W=a("buildspace.apps.ProjectBuilder.BillPrintoutSettingContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;margin:0px;border:0px;height:100%;",gutters:!1,billLayoutSettingId:null,postCreate:function(){this.inherited(arguments);this.addChild(new J({projectId:parseInt(String(this.billLayoutSettingId))}))}});return a("buildspace.apps.ProjectBuilder.BillManager",dijit.layout.TabContainer,{region:"center",rootProject:null,nested:!0,style:"padding:0;border:none;margin:0;width:100%;height:100%;",billId:null,billType:null,billLayoutSettingId:null,projectBreakdownGrid:null,
tenderAlternativeBillGridId:null,postCreate:function(){this.inherited(arguments);var b=V({title:h.elementTradeList,id:"bill_element_container_"+this.rootProject.id+"-bill-"+this.billId,rootProject:this.rootProject,billId:this.billId,bqVersion:0,projectBreakdownGrid:this.projectBreakdownGrid,tenderAlternativeBillGridId:this.tenderAlternativeBillGridId});this.addChild(b);this.addChild(new U({title:h.billProperties,billId:this.billId,projectBreakdownGrid:this.projectBreakdownGrid,tenderAlternativeBillGridId:this.tenderAlternativeBillGridId,
billType:this.billType,billElementObj:b}));parseInt(String(this.rootProject.status_id))==buildspace.constants.STATUS_PRETENDER&&this.addChild(new W({title:h.billPrintoutSettingTabDesc,rootProject:this.rootProject,billLayoutSettingId:this.billLayoutSettingId}))}})});
