define("buildspace/apps/ProjectBuilder/BillForm","dojo/_base/declare dojo/html dojo/dom dojo/keys dojo/dom-style dijit/form/Form dijit/form/ValidationTextBox dijit/form/Textarea dijit/form/Select dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./templates/billForm.html dojo/i18n!buildspace/nls/ProjectBuilder dojo/on".split(" "),function(h,e,k,l,d,u,v,w,g,m,n,p,q,r,f,x){var t=h("buildspace.apps.ProjectBuilder.BillFormWidget",[m,n,p,q],{templateString:r,
baseClass:"buildspace-form",region:"center",dialogObj:null,billId:-1,parentId:null,projectBreakdownGrid:null,billType:null,nls:f,style:"padding:5px;overflow:auto;",constructor:function(a){var c=this.BillTypeConstantArray=[];this.BILL_TYPE_STANDARD=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_STANDARD;this.BILL_TYPE_STANDARD_TEXT=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_STANDARD_TEXT;this.BILL_TYPE_STANDARD_DESCRIPTION=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_STANDARD_DESCRIPTION;
this.BILL_TYPE_PRELIMINARY=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRELIMINARY;this.BILL_TYPE_PRELIMINARY_TEXT=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRELIMINARY_TEXT;this.BILL_TYPE_PRELIMINARY_DESCRIPTION=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRELIMINARY_DESCRIPTION;this.BILL_TYPE_PROVISIONAL=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PROVISIONAL;this.BILL_TYPE_PROVISIONAL_TEXT=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PROVISIONAL_TEXT;
this.BILL_TYPE_PROVISIONAL_DESCRIPTION=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PROVISIONAL_DESCRIPTION;this.BILL_TYPE_PRIMECOST=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRIMECOST;this.BILL_TYPE_PRIMECOST_TEXT=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRIMECOST_TEXT;this.BILL_TYPE_PRIMECOST_DESCRIPTION=buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRIMECOST_DESCRIPTION;this.RoundingTypeConstants=RoundingTypeConstants=
[{label:buildspace.constants.ROUNDING_TYPE_DISABLED_TEXT,value:buildspace.constants.ROUNDING_TYPE_DISABLED},{label:buildspace.constants.ROUNDING_TYPE_UPWARD_TEXT,value:buildspace.constants.ROUNDING_TYPE_UPWARD},{label:buildspace.constants.ROUNDING_TYPE_DOWNWARD_TEXT,value:buildspace.constants.ROUNDING_TYPE_DOWNWARD},{label:buildspace.constants.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER_TEXT,value:buildspace.constants.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER},{label:buildspace.constants.ROUNDING_TYPE_NEAREST_TENTH_TEXT,
value:buildspace.constants.ROUNDING_TYPE_NEAREST_TENTH}];this.BillTypeConstants=BillTypeConstants=[{label:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_STANDARD_TEXT,value:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_STANDARD,description:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_STANDARD_DESCRIPTION},{label:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRELIMINARY_TEXT,value:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRELIMINARY,
description:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRELIMINARY_DESCRIPTION},{label:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PROVISIONAL_TEXT,value:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PROVISIONAL,description:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PROVISIONAL_DESCRIPTION},{label:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRIMECOST_TEXT,value:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRIMECOST,
description:buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_TYPE_PRIMECOST_DESCRIPTION}];c[this.BILL_TYPE_STANDARD]={title:this.BILL_TYPE_STANDARD_TEXT,description:this.BILL_TYPE_STANDARD_DESCRIPTION};c[this.BILL_TYPE_PRELIMINARY]={title:this.BILL_TYPE_PRELIMINARY_TEXT,description:this.BILL_TYPE_PRELIMINARY_DESCRIPTION};c[this.BILL_TYPE_PROVISIONAL]={title:this.BILL_TYPE_PROVISIONAL_TEXT,description:this.BILL_TYPE_PROVISIONAL_DESCRIPTION};c[this.BILL_TYPE_PRIMECOST]={title:this.BILL_TYPE_PRIMECOST_TEXT,
description:this.BILL_TYPE_PRIMECOST_DESCRIPTION};this.inherited(arguments)},postCreate:function(){this.inherited(arguments);var a=new dojo.data.ItemFileReadStore({url:"projectBuilder/getUnitTypes"});this.billSelect=(new g({name:"bill_type[type]",style:"width:180px;padding:2px!important;",options:this.BillTypeConstants,searchAttr:"value",onChange:dojo.hitch(this,"doChangeBillType")})).placeAt(this.billTypeInputDivNode);this.buildUpQuantityRoundingSelect=(new g({name:"bill_setting[build_up_quantity_rounding_type]",
style:"width:180px;padding:2px!important;",options:this.RoundingTypeConstants,searchAttr:"name"})).placeAt(this.buildUpQuantityRoundingTypeInputDivNode);this.buildUpRateRoundingSelect=(new g({name:"bill_setting[build_up_rate_rounding_type]",style:"width:180px;padding:2px!important;",options:this.RoundingTypeConstants,searchAttr:"name"})).placeAt(this.buildUpRateRoundingTypeInputDivNode);this.unitTypeSelect=(new g({name:"bill_setting[unit_type]",style:"width:80px;padding:2px!important;",store:a,searchAttr:"name"})).placeAt(this.unitTypeInputDivNode)},
startup:function(){this.inherited(arguments);var a=this;0<this.billId?this.toggleEditableInputElements(!1):this.toggleEditableInputElements(!0);var c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});c.show().then(function(){dojo.xhrGet({url:"projectBuilder/billForm",handleAs:"json",content:{id:a.billId,parent_id:a.parentId},load:function(b){a.billForm.setFormValues(b);a.billType=a.BillTypeConstantArray[b["bill_type[type]"]];e.set(a.unitTypeViewDivNode,b.unitTypeText?b.unitTypeText:
"");e.set(a.billTypeViewDivNode,a.billType.title);e.set(a.billTypeDescriptionViewDivNode,a.billType.description);c.hide()},error:function(a){c.hide()}})})},toggleEditableInputElements:function(a){a?(d.set(this.unitTypeViewDivNode,"display","none"),d.set(this.billTypeViewDivNode,"display","none"),d.set(this.unitTypeInputDivNode,"display",""),d.set(this.billTypeInputDivNode,"display","")):(d.set(this.unitTypeViewDivNode,"display",""),d.set(this.billTypeViewDivNode,"display",""),d.set(this.unitTypeInputDivNode,
"display","none"),d.set(this.billTypeInputDivNode,"display","none"))},doChangeBillType:function(){var a=this.billSelect.get("value");this.billType=this.BillTypeConstantArray[a];e.set(this.billTypeViewDivNode,this.billType.title);e.set(this.billTypeDescriptionViewDivNode,this.billType.description)},save:function(){if(this.billForm.validate()){var a=buildspace.dialog.indeterminateProgressBar({title:f.savingData+"..."}),c=this,b=dojo.formToObject(c.billForm.id);a.show().then(function(){dojo.xhrPost({url:"projectBuilder/billUpdate",
content:b,handleAs:"json",load:function(b){dojo.query('[id^="error-bill_setting_"]').forEach(function(a){a.innerHTML=""});if(b.success)b=dijit.byId("bill_element_container_"+c.projectBreakdownGrid.rootProject.id+"-bill-"+b.item.id),c.projectBreakdownGrid.reload(),b&&b.reconstructBillContainer(),c.dialogObj&&c.dialogObj.hide();else for(var d in b.errors)e.set(k.byId("error-bill_setting_"+d),b.errors[d]);a.hide()},error:function(b){a.hide()}})})}},close:function(){},onCancel:function(){}});return h("buildspace.apps.ProjectBuilder.BillFormDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",billId:-1,parentId:null,projectBreakdownGrid:null,title:null,buildRendering:function(){var a=this.createForm();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){d.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==l.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createForm:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:540px;height:320px;",
gutters:!1}),c=new t({dialogObj:this,billId:this.billId,parentId:this.parentId,projectBreakdownGrid:this.projectBreakdownGrid}),b=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});b.addChild(new dijit.form.Button({label:f.save,iconClass:"icon-16-container icon-16-save",style:"outline:none!important;",onClick:dojo.hitch(c,"save")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({label:f.close,iconClass:"icon-16-container icon-16-close",
style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));a.addChild(b);a.addChild(c);return a}})});
