define("buildspace/apps/ProjectBuilder/Builder","dojo/_base/declare dojo/dom-style dojo/keys dojo/on dojo/_base/connect dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dijit/layout/ContentPane ./WorkArea buildspace/apps/AssignUser/assignGroupProjectGrid buildspace/apps/PageGenerator/GeneratorDialog buildspace/apps/TenderAlternative/TenderAlternativeListDialog ./EmptyGrandTotalQtyDialog ./HeadWithoutItemsDialog dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(r,u,F,G,q,v,w,
x,y,z,A,t,B,C,D,b){var E=r("buildspace.apps.ProjectBuilder.PublishToTenderDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:b.publishToTender,project:null,mainDialog:null,data:null,assignGroupProjectGridSavedState:!1,buildRendering:function(){var a=this.createForm();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==
dojo.keys.ESCAPE&&dojo.stopEvent(a)},onHide:function(){dojo.forEach(this._connects,q.disconnect);this.destroyRecursive()},createForm:function(){var a=this,e=new dijit.layout.BorderContainer({style:"padding:0;width:380px;height:120px;",gutters:!1}),d=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});d.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));
d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:b.assignUsersForTendering,iconClass:"icon-16-container icon-16-add",style:"outline:none!important;",onClick:dojo.hitch(this,"assignUserPermission")}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:b.publish,iconClass:"icon-16-container icon-16-indent",style:"outline:none!important;",onClick:function(){buildspace.dialog.confirm(b.confirmation,"<div>"+b.generateBillRef+"</div>",80,300,dojo.hitch(a.mainDialog,
"doPublishToTender"))}}));var c=new y({content:b.generateBillRef,region:"center",style:"padding:5px;text-align:center"});e.addChild(d);e.addChild(c);return e},assignUserPermission:function(){var a=this,e=new A({rootProject:this.project,sysName:"Tendering",projectStatus:buildspace.constants.USER_PERMISSION_STATUS_TENDERING});e.show();e.selectGroup();this._connects.push(q.connect(e,"save",function(){a.assignGroupProjectGridSavedState=!0}));this._connects.push(q.connect(e,"isAdminUpdate",function(){a.assignGroupProjectGridSavedState=
!0}))}});return r("buildspace.apps.ProjectBuilder.Builder",dijit.layout.BorderContainer,{style:"padding:0;margin:0;width:100%;height:100%;",gutters:!1,project:null,workarea:null,publishToTenderDialog:null,postCreate:function(){this.inherited(arguments);var a=this,e=dojo.xhrGet({url:"projectAnalyzer/getAnalysisStatus/",content:{pid:this.project.id},handleAs:"json"});dojo.xhrGet({url:"projectBuilder/validateEmptyGrandTotalQty/",content:{pid:this.project.id},handleAs:"json"}).then(function(d){d.has_error&&
a.displayEmptyGrandTotalQtyDialog(d)});e.then(function(d){var c=new dijit.Toolbar({region:"top",style:"padding:2px;width:100%;"}),g=a.workarea=z({rootProject:a.project});c.addChild(new dijit.form.Button({label:b.importRates,iconClass:"icon-16-container icon-16-import",onClick:function(){buildspace.app.launch({__children:[],icon:"project_import_rates",id:a.project.id+"-project_import_rates",is_app:!0,level:0,sysname:"ProjectImportRates",title:b.importRates},{type:buildspace.constants.STATUS_PRETENDER,
project:a.project})}}));c.addChild(new dijit.ToolbarSeparator);var n=new w({style:"display: none;"});dojo.forEach(["resourceAnalysis","scheduleOfRateAnalysis"],function(h){var k=!0;"resourceAnalysis"==h&&1==d.enable_resource_analysis?k=!1:"scheduleOfRateAnalysis"==h&&1==d.enable_schedule_of_rate_analysis&&(k=!1);n.addChild(new x({id:h+"-"+a.project.id+"-menuItem",label:b[h],disabled:k,onClick:function(){buildspace.app.launch({__children:[],icon:"project_analyzer",id:a.project.id+"-project_analyzer",
is_app:!0,level:0,sysname:"ProjectAnalyzer",title:b.projectAnalyzer},{type:buildspace.constants.STATUS_PRETENDER,opt:h,project:a.project})}}))});c.addChild(new v({id:"analyzer-"+a.project.id+"-dropDownButton",label:b.projectAnalyzer,iconClass:"icon-16-container icon-16-project_analyzer",style:"outline:none!important;",disabled:!d.enable_resource_analysis&&!d.enable_schedule_of_rate_analysis,dropDown:n}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:b.projectSummary,
iconClass:"icon-16-container icon-16-list",onClick:function(h){var k=dijit.byId("projectBuilder-projectBreakdownGrid"),m=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."}),p=dojo.xhrGet({url:"getTenderAlternatives/"+String(a.project.id)+"/1",handleAs:"json"});m.show().then(function(){p.then(function(f){m.hide();2<f.items.length?(a.project.has_tender_alternative=1,f=new B({project:a.project,workArea:a.workarea,type:"printPdf"})):(a.project.has_tender_alternative=0,f=new t({project:a.project,
onSuccess:dojo.hitch(a,"_openProjectSummary"),onClickErrorNode:function(l,H){switch(parseInt(String(l.type))){case buildspace.apps.ProjectBuilder.ProjectStructureConstants.TYPE_BILL:parseInt(String(l.bill_status))==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_OPEN&&a.workarea.initTab(l,{billId:parseInt(String(l.id)),billType:parseInt(String(l.bill_type)),billLayoutSettingId:l.billLayoutSettingId,projectBreakdownGrid:k,rootProject:a.project});break;case buildspace.apps.ProjectBuilder.ProjectStructureConstants.TYPE_SUPPLY_OF_MATERIAL_BILL:a.workarea.initTab(l,
{billId:parseInt(String(l.id)),somBillLayoutSettingId:l.somBillLayoutSettingId,projectBreakdownGrid:k,rootProject:a.project});break;case buildspace.apps.ProjectBuilder.ProjectStructureConstants.TYPE_SCHEDULE_OF_RATE_BILL:a.workarea.initTab(l,{billId:parseInt(String(l.id)),sorBillLayoutSettingId:l.sorBillLayoutSettingId,projectBreakdownGrid:k,rootProject:a.project})}}}));f.show()})})}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:a.project.id+"ViewSubPackageRow-button",
label:b.subPackages,iconClass:"icon-16-container icon-16-file",onClick:function(h){buildspace.app.launch({__children:[],icon:"project_sub_package",id:a.project.id+"-project_sub_package",is_app:!0,level:0,sysname:"SubPackage",title:b.subPackages},{type:buildspace.constants.STATUS_PRETENDER,project:a.project})}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"soq-"+a.project.id+"-mainButton",label:b.scheduleOfQuantities,iconClass:"icon-16-container icon-16-pyramid",disabled:1!=
d.enable_schedule_of_qty,onClick:function(h){buildspace.app.launch({__children:[],icon:"project_schedule_of_quantity",id:a.project.id+"-schedule_of_quantity",is_app:!0,level:0,sysname:"ScheduleOfQuantity",title:b.scheduleOfQuantities},{type:buildspace.constants.STATUS_PRETENDER,project:a.project,canEdit:a.project.status_id==buildspace.constants.STATUS_PRETENDER})}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"locationManagement-"+a.project.id+"-mainButton",label:b.locationManagement,
iconClass:"icon-16-container icon-16-shopping_basket",onClick:function(h){buildspace.app.launch({__children:[],icon:"project_location_management",id:a.project.id+"-location_management",is_app:!0,level:0,sysname:"ProjectLocationManagement",title:b.locationManagement},{type:buildspace.constants.STATUS_PRETENDER,project:a.project,canEdit:!0})}}));a.project.is_admin[0]&&(c.addChild(new dijit.ToolbarSeparator),c.addChild(new dijit.form.Button({id:a.project.id+"PublishToTenderRow-button",label:b.publishToTender,
iconClass:"icon-16-container icon-16-indent",onClick:function(h){var k=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});k.show().then(function(){dojo.xhrGet({url:"projectAnalyzer/getAnalysisStatus",content:{pid:a.project.id},handleAs:"json",load:function(m){k.hide();m.enable_resource_analysis&&m.enable_schedule_of_rate_analysis&&m.enable_schedule_of_qty?a.publishToTender():buildspace.dialog.alert(b.alert,b.cannotPushToTenderNoOpenBill,100,300)},error:function(m){k.hide()}})})}})));
g.startup();a.addChild(c);a.addChild(g)})},_openProjectSummary:function(){var a=this,e=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});e.show().then(function(){dojo.xhrGet({url:"projectSummary/projectSummaryData",content:{id:a.project.id},handleAs:"json"}).then(function(d){e.hide();buildspace.app.launch({__children:[],icon:"project_summary",id:a.project.id+"-project_summary",is_app:!0,level:0,sysname:"ProjectSummary",title:b.projectSummary},{project:a.project,projectSummaryData:d})})})},
publishToTender:function(){var a=this,e=dojo.xhrGet({url:"projectBuilder/validateEmptyGrandTotalQty/",content:{pid:this.project.id},handleAs:"json"}),d=dojo.xhrGet({url:"projectBuilder/validateZeroGrandTotalQty/",content:{pid:this.project.id},handleAs:"json"}),c=function(){e.then(function(g){g.has_error?a.displayEmptyGrandTotalQtyDialog(g):d.then(function(n){if(n.has_error)a.displayEmptyGrandTotalQtyDialog(n);else{var h=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."}),k=dojo.xhrGet({url:"getTenderAlternativeUntagProjectBills/"+
a.project.id,handleAs:"json"});h.show().then(function(){k.then(function(m){h.hide();if(m.success){var p=dijit.byId("projectBuilder-projectBreakdownGrid");(new t({project:a.project,onSuccess:dojo.hitch(a,"_openPublishToTenderDialog"),onClickErrorNode:function(f,l){switch(parseInt(String(f.type))){case buildspace.apps.ProjectBuilder.ProjectStructureConstants.TYPE_BILL:parseInt(String(f.bill_status))==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_OPEN&&a.workarea.initTab(f,{billId:parseInt(String(f.id)),
billType:parseInt(String(f.bill_type)),billLayoutSettingId:f.billLayoutSettingId,projectBreakdownGrid:p,rootProject:a.project});break;case buildspace.apps.ProjectBuilder.ProjectStructureConstants.TYPE_SUPPLY_OF_MATERIAL_BILL:a.workarea.initTab(f,{billId:parseInt(String(f.id)),somBillLayoutSettingId:f.somBillLayoutSettingId,projectBreakdownGrid:p,rootProject:a.project});break;case buildspace.apps.ProjectBuilder.ProjectStructureConstants.TYPE_SCHEDULE_OF_RATE_BILL:a.workarea.initTab(f,{billId:parseInt(String(f.id)),
sorBillLayoutSettingId:f.sorBillLayoutSettingId,projectBreakdownGrid:p,rootProject:a.project})}}})).show()}else buildspace.dialog.alert(b.alert,b.cannotPushToTenderTenderAlternativeUntagBills,100,300)})})}})})};dojo.xhrGet({url:"projectBuilder/validateHeadsWithoutItems/",content:{pid:this.project.id},handleAs:"json"}).then(function(g){g.has_error?a.displayHeadWithoutItemsDialog(g,c):c()})},_openPublishToTenderDialog:function(){(this.publishToTenderDialog=new E({id:"PublishToTenderDialog-"+this.project.id,
project:this.project,mainDialog:this})).show()},displayEmptyGrandTotalQtyDialog:function(a){(new C({id:"EmptyGrandTotalQtyDialog-"+this.project.id,project:this.project,data:a,mainDialog:this})).show()},displayHeadWithoutItemsDialog:function(a,e){(new D({id:"HeadWithoutItemsDialog-"+this.project.id,project:this.project,data:a,mainDialog:this,onYes:e})).show()},doPublishToTender:function(){var a=this,e=dijit.byId("projectBuilder-projectBreakdownGrid"),d=a.project,c=buildspace.dialog.indeterminateProgressBar({title:b.processing+
". "+b.pleaseWait+"..."});buildspace.dialog.confirm(b.confirmation,"<div>"+b.generateBillRefConfirmation+"</div>",100,300,function(){c.show().then(function(){e.workArea.removeBillTab();dojo.xhrPost({url:"projectBuilder/publishToTender",content:{id:d.id,usersAssignedManually:a.publishToTenderDialog.assignGroupProjectGridSavedState},handleAs:"json",load:function(g){a.project.status_id=[g.status_id];e.disableButtonsAfterPublish();(g=dijit.byId("projectProperties-"+a.project.id))&&g.projectMainInfoForm.disableForm();
(g=dijit.byId("PublishToTenderDialog-"+a.project.id))&&g.hide();c.hide()},error:function(g){c.hide()}})})})}})});
