define("buildspace/apps/ProjectBuilder/importBackupDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./templates/importBackupForm.html dojo/text!./templates/billInfoForm.html dojo/i18n!buildspace/nls/BackupImport dojox/form/Uploader".split(" "),
function(b,n,y,z,A,B,f,g,C,D,h,k,l,m,p,q,c,E){var r=function(a,c){return 0<a?a:""},t=b("buildspace.apps.ProjectBuilder.FileImportGrid",dojox.grid.EnhancedGrid,{type:null,selectedItem:null,dialogWidget:null,escapeHTMLInData:!1,gridData:null,style:"border-top:none;",constructor:function(a){this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments)},destroy:function(){this.inherited(arguments)}}),u=b("buildspace.apps.ProjectBuilder.billInfoForm",[h,k,l,m],
{templateString:q,baseClass:"buildspace-form",region:"top",nls:c,style:"padding:5px;overflow:auto;padding-bottom:10px;",title:null,postCreate:function(){this.inherited(arguments)},startup:function(){this.inherited(arguments)}}),v=b("buildspace.apps.ProjectBuilder.FileImportGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,region:"center",gridOpts:{},billInfo:null,postCreate:function(){this.inherited(arguments);n.mixin(this.gridOpts,
{region:"center"});var a=this.grid=new t(this.gridOpts);this.addChild(new u({title:this.billInfo.title[0]}));this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))}}),w=b("buildspace.apps.ProjectBuilder.FileImportGridDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",gridData:null,projectId:null,billInfo:null,parentId:null,billId:null,tempFileInfo:null,importUrl:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},
postCreate:function(){g.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==f.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},removeUploadedFile:function(){},createContent:function(){var a=this,e=new dijit.layout.BorderContainer({style:"padding:0px;width:650px;height:450px;",gutters:!1}),d=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});
d.addChild(new dijit.form.Button({label:c.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:function(){a.removeUploadedFile();a.hide()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:c["import"],iconClass:"icon-16-container icon-16-import",onClick:function(){a["import"]()}}));var b=dojo.data.ItemFileWriteStore({data:a.gridData}),b=v({stackContainerTitle:a.billInfo.title,billInfo:a.billInfo,gridOpts:{store:b,dialogWidget:a,
structure:[{name:c.number,field:"id",width:"30px",styles:"text-align:center;",formatter:r},{name:c.description,field:"description",width:"auto"}]}});e.addChild(d);e.addChild(b);return e},"import":function(){var a=this;this.hide();var b=buildspace.dialog.indeterminateProgressBar({title:c.savingData+". "+c.pleaseWait+"..."});b.show().then(function(){dojo.xhrPost({url:a.importUrl,content:{id:a.billId,parent_id:a.parentId,filename:a.tempFileInfo.filename,extension:a.tempFileInfo.extension,uploadPath:a.tempFileInfo.uploadPath},
handleAs:"json",load:function(d){b.hide();d.success?a.reloadProjectBreakdown():buildspace.dialog.alert(c.error,"<div>"+d.errorMsg+"</div>",80,280)},error:function(a){b.hide()}})})},reloadProjectBreakdown:function(){dijit.byId("main-project_breakdown").grid.reload()}}),x=b("buildspace.apps.ProjectBuilder.FileImportForm",[h,k,l,m],{templateString:p,baseClass:"buildspace-form",region:"center",dialogObj:null,billId:-1,parentId:-1,projectId:-1,projectBreakdownGrid:null,nls:c,uploadUrl:"projectBackup/uploadBill",
importUrl:"projectBackup/importBill",style:"padding:5px;overflow:auto;",postCreate:function(){this.inherited(arguments);var a=this.fileUploaderNode;a.on("Complete",dojo.hitch(this,"uploadComplete"));a.on("Begin",dojo.hitch(this,"uploadBegin"))},startup:function(){this.inherited(arguments)},doImportFile:function(){},uploadBegin:function(a){(this.pb=buildspace.dialog.indeterminateProgressBar({title:c.uploadingData+". "+c.pleaseWait+"..."})).show();this.dialogObj.hide()},uploadComplete:function(a){this.pb.hide();
a.success?(this.importGridDialog=new w({gridData:a.elements,projectId:this.projectId,parentId:this.parentId,billId:this.billId,billInfo:a.billInfo,tempFileInfo:a.tempFileInfo,importUrl:this.importUrl,title:this.title})).show():buildspace.dialog.alert(c.error,"<div>"+a.errorMsg+"</div>",80,280)},close:function(){},onCancel:function(){}});return b("buildspace.apps.ProjectBuilder.FileImportDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:c.importBackup,rootProject:null,projectBreakdownGrid:null,
item:null,buildRendering:function(){var a=this.createForm();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){g.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==f.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createForm:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:400px;height:80px;",gutters:!1}),b=new x({dialogObj:this,
title:this.title,projectBreakdownGrid:this.projectBreakdownGrid,projectId:this.rootProject.id,parentId:this.item.id}),d=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});d.addChild(new dijit.form.Button({label:c.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));a.addChild(d);a.addChild(b);return a}})});
