define("buildspace/apps/ProjectBuilder/RecalculateDialog","dojo/_base/declare dojo/_base/lang dojo/keys dojo/dom-style dojo/store/Memory dojo/data/ObjectStore buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(k,x,p,q,r,t,u,d){var w=k("buildspace.apps.ProjectBuilder.RecalculateDialogGrid",dojox.grid.EnhancedGrid,{rootProject:null,billId:0,region:"center",_csrf_token:null,dialog:null,projectBreakDownGrid:null,tenderAlternativeBillGrid:null,style:"border-top:none;",
canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);this.on("RowClick",function(g){var h=g.cell.field,b=this.getItem(g.rowIndex);if("recalculate"==h&&b.recalculate){var f=buildspace.dialog.indeterminateProgressBar({title:d.recalculating+". "+d.pleaseWait+"..."});f.show();dojo.xhrPost({url:"projectAnalyzer/recalculate",content:{bill_id:a.billId,level:b.id,_csrf_token:a._csrf_token},handleAs:"json",load:function(c){if(c.success){var e=a.store;a.projectBreakDownGrid.reload();
a.tenderAlternativeBillGrid&&a.tenderAlternativeBillGrid.reload();e.setValue(b,"recalculate",!1);e.setValue(b,"bill_status",c.bill_status);"item"!=b.id&&"element"!=b.id||e.fetchItemByIdentity({identity:"item"==b.id?"element":"bill",onItem:function(v){e.setValue(v,"recalculate",!0)}});e.save();if(a.dialog&&c.bill_status==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_OPEN){c=dijit.byId("analyzer-"+a.rootProject.id+"-dropDownButton");var l=dijit.byId("resourceAnalysis-"+a.rootProject.id+
"-menuItem"),m=dijit.byId("scheduleOfRateAnalysis-"+a.rootProject.id+"-menuItem"),n=dijit.byId("soq-"+a.rootProject.id+"-mainButton");c&&c.set("disabled",!1);l&&l.set("disabled",!1);m&&m.set("disabled",!1);n&&n.set("disabled",!1);a.dialog.hide()}}f.hide()},error:function(c){f.hide()}})}})},dodblclick:function(a){this.onRowDblClick(a)}});return k("buildspace.apps.ProjectBuilder.RecalculateDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",rootProject:null,bill:null,projectBreakDownGrid:null,tenderAlternativeBillGrid:null,
buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){q.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==p.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=this.bill,g=!1,h=!1,b=!1,f=new dijit.layout.BorderContainer({style:"padding:0px;width:500px;height:200px;",gutters:!1});
if(a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_RESOURCE_ANALYSIS_RECALCULATE_ITEM||a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_SCHEDULE_OF_RATE_ANALYSIS_RECALCULATE_ITEM||a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_SCHEDULE_OF_QUANTITY_RECALCULATE_ITEM)g=!0;if(a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_RESOURCE_ANALYSIS_RECALCULATE_ELEMENT||
a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_SCHEDULE_OF_RATE_ANALYSIS_RECALCULATE_ELEMENT||a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_SCHEDULE_OF_QUANTITY_RECALCULATE_ELEMENT)h=!0;if(a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_RESOURCE_ANALYSIS_RECALCULATE_BILL||a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_SCHEDULE_OF_RATE_ANALYSIS_RECALCULATE_BILL||
a.bill_status[0]==buildspace.apps.ProjectBuilder.ProjectStructureConstants.BILL_STATUS_SCHEDULE_OF_QUANTITY_RECALCULATE_BILL)b=!0;var c=new dijit.Toolbar({region:"top",style:"outline:none!important;border:none;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var e=new u;f.addChild(c);f.addChild(new w({rootProject:this.rootProject,billId:a.id,_csrf_token:a._csrf_token,
store:new t({objectStore:r({data:[{id:"item",level:d.levelBillItems,bill_status:a.bill_status[0],recalculate:g},{id:"element",level:d.levelBillElements,bill_status:a.bill_status[0],recalculate:h},{id:"bill",level:d.levelBills,bill_status:a.bill_status[0],recalculate:b}]})}),dialog:this,projectBreakDownGrid:this.projectBreakDownGrid,tenderAlternativeBillGrid:this.tenderAlternativeBillGrid,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:e.rowCountCellFormatter},
{name:d.level,field:"level",width:"auto"},{name:d.recalculate,field:"recalculate",width:"100px",styles:"text-align:center;",formatter:e.recalculateCellFormatter}]}));return f}})});
