define("buildspace/apps/PostContract/ImportedClaims/BaseContainer",["dojo/_base/declare","buildspace/apps/Attachment/UploadAttachmentContainer","dojox/grid/EnhancedGrid","buildspace/widget/grid/cells/Formatter","dojo/i18n!buildspace/nls/PostContract"],function(e,g,f,h,d){var k=e("buildspace.apps.PostContract/ImportedClaims/BreakdownGrid",f,{style:"border:none;",region:"center",keepSelection:!0,escapeHTMLInData:!1,canSort:function(){return!1},parentContainer:null,postCreate:function(){this.inherited(arguments);
var b=this;this.on("CellClick",function(a){var c=a.cell.field;a=this.getItem(a.rowIndex);0<a.id&&"attachment"==c&&b.parentContainer.addAttachmentContainer(a)})}}),l=e("buildspace.apps.PostContract/ImportedClaims/ItemGrid",f,{style:"border:none;",region:"center",keepSelection:!0,escapeHTMLInData:!1,canSort:function(){return!1},parentContainer:null,postCreate:function(){this.inherited(arguments);var b=this;this.on("CellClick",function(a){var c=a.cell.field;a=this.getItem(a.rowIndex);0<a.id&&"attachment"==
c&&b.parentContainer.addAttachmentContainer(a)})}});return e("buildspace.apps.PostContract.ImportedClaims.Base",dijit.layout.BorderContainer,{region:"center",title:"",style:"padding:0px;border:none;width:100%;height:40%;",gutters:!1,splitter:!0,grid:null,stackContainer:null,parentContainer:null,project:null,claimCertificate:null,postCreate:function(){this.inherited(arguments);this.formatter=new h;this.hierarchyTypes={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM_TEXT],
values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM]};this.addChild(this.createToolbar());var b=this.stackContainer=this.createStackContainer(),a=new dijit.layout.BorderContainer({title:this.title,style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,region:"center"});a.addChild(this.createBreakdownGrid());b.addChild(a)},createToolbar:function(){var b=new dijit.Toolbar({region:"top",style:"outline:none!important;border:none;padding:2px;width:100%;"});
b.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-container icon-16-close",style:"float:right;",onClick:dojo.hitch(this,"close")}));return b},getBreakdownGridStructure:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:this.formatter.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"},{name:d.amount,field:"total_amount",width:"90px",styles:"text-align: right;",formatter:this.formatter.unEditableCurrencyCellFormatter},
{name:d.upToDateClaim,field:"up_to_date_amount",width:"90px",styles:"text-align: right;",formatter:this.formatter.unEditableCurrencyCellFormatter}]},getItemGridStructure:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:this.formatter.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:this.formatter.treeCellFormatter,noresize:!0},{name:d.type,field:"type",width:"70px",styles:"text-align:center;",editable:!1,type:"dojox.grid.cells.Select",
options:this.hierarchyTypes.options,values:this.hierarchyTypes.values,formatter:this.formatter.typeCellFormatter},{name:d.amount,field:"total_amount",width:"90px",styles:"text-align: right;",formatter:this.formatter.unEditableCurrencyCellFormatter},{name:d.upToDateClaim,field:"up_to_date_amount",width:"90px",styles:"text-align: right;",formatter:this.formatter.unEditableCurrencyCellFormatter}]},createStackContainer:function(){var b=this.id+"-importedBreakdown-stackContainer",a=this.stackContainer=
new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:b});dojo.subscribe(b+"-selectChild","",function(a){var c=dijit.byId(b);if(c){var d=c.getChildren();a=dojo.indexOf(d,a);a+=1;if(d.length>a)for(;d.length>a;)c.removeChild(d[a]),d[a].destroyDescendants(),d[a].destroyRecursive(),a+=1}});var c=new dijit.layout.StackController({region:"top",containerId:b});c=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",
id:this.id+"-importedBreakdown-controllerPane",content:c});this.addChild(a);this.addChild(c);return a},createBreakdownGrid:function(){var b=this,a=this.getBreakdownGridUrl();a=b.breakdownGrid=k({structure:b.getBreakdownGridStructure(),parentContainer:b,store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:a}),onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id[0]&&b.createItemGrid(a)}});return new dijit.layout.ContentPane({style:"padding:0px;border:none;width:100%;height:100%;",region:"center",
content:a,grid:a})},createItemGrid:function(b){var a=new dijit.layout.BorderContainer({title:buildspace.truncateString(b.description,60),region:"center",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,item:b});b=this.getItemGridUrl(b);b=this.itemGrid=l({item:this.item,structure:this.getItemGridStructure(),parentContainer:this,store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:b})});a.addChild(b);this.stackContainer.addChild(a);this.stackContainer.selectChild(a)},getBreakdownGridUrl:function(){},
getItemGridUrl:function(b){},addAttachmentContainer:function(b){var a="project-"+this.project.id+"-importedAttachments",c=dijit.byId(a);c&&(this.removeChild(c),c.destroy());c=new g({id:a,region:"bottom",item:b,disableEditing:!0,style:"padding:0;margin:0;border:none;width:100%;height:40%;"});this.addChild(c)},close:function(){this.parentContainer.removeChild(this);return this.destroyRecursive()}})});
