define("buildspace/apps/TenderAlternative/TenderAlternativeListDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/keys dojo/dom-style dojo/on dijit/form/Form dojox/form/manager/_Mixin dojox/form/manager/_NodeMixin dojox/form/manager/_ValueMixin dojox/form/manager/_DisplayMixin dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/ValidationTextBox dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter buildspace/widget/grid/Filter buildspace/apps/PageGenerator/GeneratorDialog buildspace/apps/Tendering/PrintFinalBQDialog buildspace/apps/RationalizeRate/PrintBillDialog dojo/i18n!buildspace/nls/TenderAlternative".split(" "),
function(g,m,H,k,l,I,n,p,q,r,t,u,J,v,w,K,x,y,z,A,B,C,e){var D=g("buildspace.apps.TenderAlternative.ExportToExcelForm",[n,u,v,w,p,q,r,t],{templateString:'<form data-dojo-attach-point="containerNode"><table class="table-form"><tr><td class="label" style="width:80px;"><label style="display: inline;"></span>'+e.exportAs+' :</label></td><td><input type="text" name="filename" style="padding:2px;width:220px;" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="trim:true, propercase:true, maxlength:45, required: true"> .xlsx</td></tr></table></form>',
project:null,region:"center",url:"",defaultFilename:"",dialogWidget:null,style:"outline:none;padding:0px;margin:0px;border:none;",baseClass:"buildspace-form",startup:function(){this.inherited(arguments);this.setFormValues({filename:this.defaultFilename})},submit:function(){var a=dojo.formToObject(this.id);this.validate()&&(a=a.filename.replace(/ /g,"_"),window.open(this.url+"/"+a,"_self"),this.dialogWidget&&this.dialogWidget.hide())}}),E=g("buildspace.apps.TenderAlternative.ExportExcelDialog",dijit.Dialog,
{style:"padding:0px;margin:0px;",title:e.exportToExcel,project:null,url:"",defaultFilename:"",buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){l.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==k.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:400px;height:80px;",
gutters:!1}),b=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"}),c=D({project:this.project,url:this.url,defaultFilename:this.defaultFilename,dialogWidget:this});b.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({label:e.export,iconClass:"icon-16-container icon-16-export",style:"outline:none!important;",
onClick:dojo.hitch(c,"submit")}));a.addChild(b);a.addChild(c);return a}}),F=g("buildspace.apps.TenderAlternative.TenderAlternativeListGrid",x,{style:"border-top:none;",containerDialog:null,project:null,workArea:null,type:"printPdf",opt:null,region:"center",postCreate:function(){this.inherited(arguments);var a=this.project,b=this.opt,c=this;this.on("RowClick",function(d){if((d=this.getItem(d.rowIndex))&&0<parseInt(String(d.id)))switch(c.type){case "viewTenderer":c.openViewTenderer(d);break;case "exportExcel":c.openGeneratorDialog("_exportToExcel",
d);break;case "printPdf":switch(parseInt(String(a.status_id))){case buildspace.constants.STATUS_PRETENDER:c.openGeneratorDialog("_openProjectSummary",d);break;default:c.openGeneratorDialog("_printProjectSummaryPdf",d,b)}break;case "printFinalBQ":c.openPrintFinalBQ(d,b);break;case "printRationalizeRate":c.openPrintRationalizeRate(d,b)}},!0)},canSort:function(a){return!1},openViewTenderer:function(a){this.containerDialog.hide();buildspace.app.launch({__children:[],icon:"view_tenderer",id:String(this.project.id)+
"-view_tenderer",is_app:!0,level:0,sysname:"ViewTenderer",title:e.viewTenderers},{type:buildspace.constants.STATUS_TENDERING,project:this.project,tenderAlternative:a})},openGeneratorDialog:function(a,b,c){var d=this.project,h=this.workArea;dijit.byId("main-project_breakdown");(new A({project:d,onSuccess:m.hitch(this,a,b,c),onClickErrorNode:function(f,L){switch(parseInt(String(f.type))){case buildspace.constants.TYPE_BILL:f.bill_status==buildspace.constants.BILL_STATUS_OPEN&&h.initTab(f,{billId:f.id,
billType:f.bill_type,billLayoutSettingId:f.billLayoutSettingId,projectBreakdownGrid:projectBreakDownGrid,rootProject:d});break;case buildspace.constants.TYPE_SUPPLY_OF_MATERIAL_BILL:h.initTab(f,{billId:f.id,somBillLayoutSettingId:f.somBillLayoutSettingId,projectBreakdownGrid:projectBreakDownGrid,rootProject:d});break;case buildspace.constants.TYPE_SCHEDULE_OF_RATE_BILL:h.initTab(f,{billId:f.id,sorBillLayoutSettingId:f.sorBillLayoutSettingId,projectBreakdownGrid:projectBreakDownGrid,rootProject:d})}}})).show()},
_openProjectSummary:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});this.containerDialog.hide();c.show().then(function(){dojo.xhrGet({url:"tenderAlternativeProjectSummary/"+parseInt(String(a.id)),handleAs:"json"}).then(function(d){c.hide();buildspace.app.launch({__children:[],icon:"project_summary",id:parseInt(String(b.project.id))+"-project_summary",is_app:!0,level:0,sysname:"ProjectSummary",title:e.projectSummary},{project:b.project,tenderAlternative:a,
projectSummaryData:d})})})},_printProjectSummaryPdf:function(a,b){window.open("TenderAlternativeProjectSummaryPdf/"+parseInt(String(a.id))+"/"+String(this.project._csrf_token)+"/"+b,"_blank");return window.focus()},_exportToExcel:function(a){var b=new Date;E({project:this.project,url:"TenderAlternativeProjectSummaryXls/"+parseInt(String(a.id))+"/"+String(this.project._csrf_token),defaultFilename:"Project_Summary"+b.getDate()+(b.getMonth()+1)+b.getFullYear()}).show()},openPrintFinalBQ:function(a,b){b=
b.withPrice;(new B({title:e.printFinalBQ+" ("+(b?e.withPrice:e.withoutPrice)+") "+buildspace.truncateString(a.title,40),project:this.project,tenderAlternative:a,withPrice:b})).show()},openPrintRationalizeRate:function(a,b){var c=(b=b.printRationalizeRate)?e.printRationalizeBQ:e.printOriginalBQ;(new C({projectId:parseInt(String(this.project.id)),statusId:parseInt(String(this.project.status_id)),tenderAlternative:a,title:c+" ("+buildspace.truncateString(a.title,40)+")",printRationalizedRate:b,_csrf_token:String(this.project._csrf_token)})).show()}}),
G=g("buildspace.apps.TenderAlternative.TenderAlternativeListGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",containerDialog:null,project:null,workArea:null,type:"printPdf",opt:null,postCreate:function(){this.inherited(arguments);var a=new y;if("printRationalizeRate"==this.type){var b=this.opt.printRationalizeRate?1:0;b="getRationalizeRateTenderAlternatives/"+parseInt(String(this.project.id))+"/"+parseInt(b)}else b="getTenderAlternatives/"+parseInt(String(this.project.id))+
"/1";a=this.grid=new F({containerDialog:this.containerDialog,project:this.project,workArea:this.workArea,type:this.type,opt:this.opt,structure:[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:function(c,d){return 0<c?c:""}},{name:e.description,field:"title",width:"auto",formatter:function(c,d){d=this.grid.getItem(d);var h=16*parseInt(String(d.level));c=null==c?"&nbsp":c;parseInt(String(d.type))<buildspace.constants.TYPE_BILL&&(c="<b>"+c+"</b>");return'<div class="treeNode" style="padding-left:'+
h+'px;"><div class="treeContent">'+c+"&nbsp;</div></div>"}},{name:e.selected,field:"is_awarded",width:"80px",styles:"text-align:center;",formatter:a.awardedCellFormatter},{name:e.overallTotal,field:"overall_total_after_markup",width:"150px",styles:"text-align: right;",formatter:a.unEditableCurrencyCellFormatter}],store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:b})});this.addChild(a);this.addChild(new z({region:"top",editableGrid:!1,grid:a,filterFields:[{title:e.description}]}))},save:function(){this.grid.save()}});
return g("buildspace.apps.TenderAlternative.TenderAlternativeListDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,workArea:null,type:"printPdf",opt:null,title:e.tenderAlternatives,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){l.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==k.ESCAPE&&dojo.stopEvent(a)},
onHide:function(){this.destroyRecursive()},createContent:function(){parseInt(this.project.has_tender_alternative)||(this.project.has_tender_alternative=1);var a=new dijit.layout.BorderContainer({style:"padding:0px;width:820px;height:380px;",gutters:!1}),b=new G({region:"center",containerDialog:this,project:this.project,workArea:this.workArea,type:this.type,opt:this.opt}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:e.close,
iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));a.addChild(c);a.addChild(b);return a}})});
