(function(){define("buildspace/apps/PostContractSubPackage/MaterialOnSite/StockOutImportDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojox/layout/ContentPane buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!../../../nls/StockOut".split(" "),function(h,p,k,u,v,w,q,r,t,l,x,d){var g,m;m=h("buildspace.apps.MaterialOnSite.ImportStockOutItemGrid",dojox.grid.EnhancedGrid,{type:null,dialogWidget:null,
_csrf_token:null,resource:null,itemIds:[],style:"border-top:none;",materialOnSiteItem:null,itemListGrid:null,constructor:function(a){this.itemIds=[];this.connects=[];"tree"===a.type&&(this.urlGetDescendantIds="bqLibrary/getResourceDescendantsForImport",this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align: center;"}});return this.inherited(arguments)},canSort:function(){return!1},postCreate:function(){var a;a=this;a.inherited(arguments);this.on("RowClick",function(b){b=
a.getItem(b.rowIndex);if("tree"===a.type)return b&&0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)});if("tree"===this.type)return this._connects.push(k.connect(this,"onCellClick",function(b){return a.selectTree(b)})),this._connects.push(k.connect(this.rowSelectCell,"toggleAllSelection",function(b){return a.toggleAllSelection(b)}))},dodblclick:function(a){return this.onRowDblClick(a)},selectTree:function(a){var b,c,e,f,n;a=a.rowIndex;c=this.selection.selected[a];a=this.getItem(a);f=
this;n=this.store;if(a.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER)return e=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."}),e.show(),b=-1,a={url:this.urlGetDescendantIds,content:{id:a.id},handleAs:"json",load:function(a){dojo.forEach(a.items,function(a){return n.fetchItemByIdentity({identity:a.id,onItem:function(a){if(a)return b=a._0,f.pushItemIdIntoGridArray(a,c),f.selection[c?"addToSelection":"deselect"](b)}})});return e.hide()},error:function(){return e.hide()}},
dojo.xhrPost(a);if(null!=a.type&&a.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM)return this.pushItemIdIntoGridArray(a,c)},pushItemIdIntoGridArray:function(a,b){var c;c=dojo.indexOf(this.itemIds,a.id[0]);if(b){if(-1===c)return this.itemIds.push(a.id[0])}else if(-1!==c)return this.itemIds.splice(c,1)},toggleAllSelection:function(a){var b,c,e;b=this;e=this;c=b.selection;if(a)return c.selectRange(0,b.rowCount-1),b.itemIds=[],b.store.fetch({onComplete:function(a){return dojo.forEach(a,
function(a){if(0<a.id)return b.itemIds.push(a.id[0]),e.disableToolbarButtons(!1)})}});c.deselectAll();return b.itemIds=[]},disableToolbarButtons:function(a){return dijit.byId("ImportStockOutItemGrid-Import-button")._setDisabledAttr(a)},importFromStockOut:function(){var a,b,c;c=this;a=c.itemIds;if(0<a.length)return b=buildspace.dialog.indeterminateProgressBar({title:d.importingItems+". "+d.pleaseWait+"..."}),b.show(),a={url:"subPackageMaterialOnSite/importStockOutItems",content:{id:c.materialOnSiteItem.id[0],
sp_material_on_site_id:c.materialOnSiteItem.relation_id[0],ids:[a],_csrf_token:c._csrf_token},handleAs:"json",load:function(a){b.hide();a.success?(c.itemIds=[],c.itemListGrid.refreshGrid()):c.itemIds=[];return c.dialogWidget.hide()},error:function(){c.itemIds=[];b.hide();return c.dialogWidget.hide()}},dojo.xhrPost(a)},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,k.disconnect);return delete this._connects}});g=h("buildspace.apps.MaterialOnSite.ImportStockOutItemGridContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",gutters:!1,type:null,gridOpts:{},postCreate:function(){var a,b,c;this.inherited(arguments);p.mixin(this.gridOpts,{type:this.type,region:"center"});c=new m(this.gridOpts);"tree"===this.type&&(b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"}),b.addChild(new dijit.form.Button({id:"ImportStockOutItemGrid-Import-button",label:d["import"],iconClass:"icon-16-container icon-16-import",disabled:!0,
onClick:function(){return c.importFromStockOut()}})),this.addChild(b));this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:c,region:"center"}));if(b=dijit.byId("materialOnSiteQuantityFromStockOut-stackContainer"))return a=document.createElement("div"),a=new t({title:buildspace.truncateString(this.title,60),executeScripts:!0},a),b.addChild(a),a.set("content",this),b.selectChild(a)}});return h("buildspace.apps.MaterialOnSite.ImportResourceDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",
project:null,itemListGrid:null,buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){r.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===q.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,b,c,e,f;c=this;a=new dijit.layout.BorderContainer({style:"padding:0px;width:900px;height:400px;",
gutters:!1});f=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});f.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));b=new l;e=dojo.data.ItemFileWriteStore({url:"stockOut/getResourceWithStockInsByProject/projectId/"+c.subPackage.project_structure_id[0]});b=new g({gridOpts:{store:e,itemListGrid:c.itemListGrid,structure:[{name:"No",field:"id",width:"30px",
styles:"text-align: center;",formatter:b.rowCountCellFormatter,noresize:!0},{name:d.description,field:"name",width:"auto",formatter:b.treeCellFormatter,noresize:!0}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);if(0<a.id)return c.createResourceTradeGrid(a)}}});b=this.makeGridContainer(b);a.addChild(f);a.addChild(b);return a},createResourceTradeGrid:function(a){var b,c,e;c=this;b=new l;e=new dojo.data.ItemFileWriteStore({url:"stockOut/getResourceTradeWithStockInsByProject/projectId/"+c.subPackage.project_structure_id[0]+
"/resourceId/"+a.id[0]});return new g({title:a.name,gridOpts:{store:e,itemListGrid:c.itemListGrid,dialogWidget:c,structure:[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:b.rowCountCellFormatter,noresize:!0},{name:d.description,field:"description",width:"auto",formatter:b.treeCellFormatter,noresize:!0}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);if(0<a.id)return c.createItemGrid(a)}}})},createItemGrid:function(a){var b,c;b=new l;c=new dojo.data.ItemFileWriteStore({url:"stockOut/getItemListingsWithDeliveryOrder/projectId/"+
this.subPackage.project_structure_id[0]+"/resourceTradeId/"+a.id[0]});return new g({title:a.description[0],type:"tree",gridOpts:{escapeHTMLInData:!1,materialOnSiteItem:this.materialOnSiteItem,store:c,itemListGrid:this.itemListGrid,dialogWidget:this,_csrf_token:a._csrf_token,structure:[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:b.rowCountCellFormatter,noresize:!0},{name:d.description,field:"description",width:"auto",formatter:b.treeCellFormatter,noresize:!0},{name:d.unit,
field:"uom_id",styles:"text-align: center;",width:"70px",formatter:b.unitIdCellFormatter,noresize:!0},{name:d.doQuantity,field:"do_quantity",styles:"text-align:right;color:blue;",width:"120px",formatter:b.unEditableCurrencyCellFormatter,noresize:!0},{name:d.stockOutQuantity,field:"stock_out_quantity",styles:"text-align:right;color:blue;",width:"120px",formatter:b.unEditableCurrencyCellFormatter,noresize:!0},{name:d.balanceQuantity,field:"balance_quantity",styles:"text-align:right;",width:"120px",
formatter:b.unEditableCurrencyCellFormatter,noresize:!0}]}})},makeGridContainer:function(a){var b,c;(c=dijit.byId("materialOnSiteQuantityFromStockOut-stackContainer"))&&dijit.byId("materialOnSiteQuantityFromStockOut-stackContainer").destroyRecursive();c=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"materialOnSiteQuantityFromStockOut-stackContainer"});a=new dijit.layout.ContentPane({title:d.resource,content:a});c.addChild(a);a=new dijit.layout.StackController({region:"top",
containerId:"materialOnSiteQuantityFromStockOut-stackContainer"});b=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:a});a=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});a.addChild(c);a.addChild(b);dojo.subscribe("materialOnSiteQuantityFromStockOut-stackContainer-selectChild","",function(a){var b,c,d;if(c=dijit.byId("materialOnSiteQuantityFromStockOut-stackContainer")){b=
c.getChildren();a=dojo.indexOf(b,dijit.byId(a.id));a+=1;for(d=[];b.length>a;)c.removeChild(b[a]),b[a].destroyRecursive(!0),d.push(a+=1);return d}});return a}})})}).call(this);
