(function(){define("buildspace/apps/CompanyDirectories/Branches/CompanyBranchForm","dojo/_base/declare dojo/_base/lang dojo/parser dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/Toolbar dijit/form/Button dijit/layout/BorderContainer dijit/form/ValidationTextBox dijit/form/SimpleTextarea dijit/registry dojo/dom-style dojo/dom-form dojo/request dojox/validate/web dijit/form/Select dijit/form/FilteringSelect dojo/store/Memory dojox/form/Manager dojo/text!./templates/companyBranchForm.html dojo/i18n!../../../nls/CompanyDirectories".split(" "),
function(h,k,z,p,q,r,t,u,v,w,A,B,C,l,D,x,E,F,m,G,H,y,g){var n;n=h("buildspace.apps.CompanyDirectories.Branches.Branches.CompanyBranchForm",[p,q,r,t],{baseClass:"buildspace-form",companyId:-1,branchId:-1,newBranchId:-1,templateString:y,region:"center",style:"overflow: auto;",formInfo:null,companyBranchContainer:null,nls:g,editable:!0,postCreate:function(){this.inherited(arguments);return this.createDropdown()},startup:function(){this.inherited(arguments);this["branchForm-"+this.companyId+"-"+this.branchId].setFormValues(this.formInfo);
if(!this.editable)return this["branchForm-"+this.companyId+"-"+this.branchId].disable()},createDropdown:function(){var a,b,c;b=this;a=new dojo.data.ItemFileReadStore({url:"projectBuilder/getCountry"});this.stateSelectStore=c=new dojo.data.ItemFileReadStore({url:"projectBuilder/getStateByCountry/regionId/"+b.formInfo["company_branch[region_id]"]});this.countrySelect=(new m({name:"company_branch[region_id]",store:a,style:"width: 140px; padding:2px;",searchAttr:"name",value:b.formInfo["company_branch[region_id]"],
required:!0,onChange:function(a){a?b.stateSelect.set("readOnly",!1):b.stateSelect.set("readOnly",!0);return b.updateStateSelectStore(a)}})).placeAt(b.branchCountrySelectDivNode);return this.stateSelect=(new m({name:"company_branch[sub_region_id]",store:c,style:"width: 140px; padding:2px;",required:!0,searchAttr:"name",readOnly:0<b.formInfo["company_branch[sub_region_id]"]?!1:!0,value:b.formInfo["company_branch[sub_region_id]"]})).placeAt(b.branchStateSelectDivNode)},updateStateSelectStore:function(a){null==
a&&(a=0);a||(a=0);this.stateSelectStore=new dojo.data.ItemFileReadStore({url:"projectBuilder/getStateByCountry/regionId/"+a,clearOnClose:!0});this.stateSelect.store.close();this.stateSelect.set("store",this.stateSelectStore);return this.stateSelect.set("value","")},clearInputErrorMsgs:function(){var a,b,c,d;c={name:null,contact_person_name:null,contact_person_email:null,contact_person_direct_line:null,contact_person_mobile:null,phone_number:null,fax_number:null,address:null,postcode:null};d=[];for(b in c)a=
this["error-"+b],a.innerHTML=c[b],d.push(l.set(a,"display","none"));return d},save:function(){var a,b,c;c=this;this.clearInputErrorMsgs();if(!this["branchForm-"+this.companyId+"-"+this.branchId].validate())return!1;a=dojo.formToObject(this["branchForm-"+this.companyId+"-"+this.branchId].id);b=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."});0<c.newBranchId?k.mixin(a,{companyId:c.companyId,branchId:c.newBranchId}):k.mixin(a,{companyId:c.companyId,branchId:c.branchId});b.show();
return x.post("companyDirectories/updateBranchInformation",{data:a,handleAs:"json"}).then(function(a){var d,e,f;b.hide();if(a.success&&0<a.id)return c.newBranchId=a.id,c.companyBranchContainer.grid.refreshGrid();f=[];for(e in a.errorMsgs)"username"!==e?(d=c["error-"+e],d.innerHTML=a.errorMsgs[e],f.push(l.set(d,"display","block"))):f.push(void 0);return f},function(a){return b.hide()})}});return h("buildspace.apps.CompanyDirectories.Branches.CompanyBranchFormContainer",w,{companyId:-1,branchId:-1,
style:"width:100%;height:100%;padding:0;margin:0;",gutters:!1,formInfo:null,companyBranchContainer:null,region:"top",editable:!0,postCreate:function(){this.inherited(arguments);var a=new n({companyId:this.companyId,branchId:this.branchId,formInfo:this.formInfo,companyBranchContainer:this.companyBranchContainer,editable:this.editable});if(this.editable){var b=new u({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});b.addChild(new v({label:g.save,iconClass:"icon-16-container icon-16-save",
disabled:this.editable?!1:!0,onClick:function(){return a.save()}}));this.addChild(b)}return this.addChild(a)}})})}).call(this);
