define("buildspace/apps/PostContract/RequestForVariationClaim/RequestForVariationClaimGrid","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/html dojo/dom-style dojo/number dijit/focus dojo/_base/event dojo/keys dojo/has dojox/grid/EnhancedGrid buildspace/widget/grid/plugins/FormulatedColumn buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(n,p,q,y,z,A,B,C,D,r,t,u,E,g){var x=n("buildspace.apps.PostContract.RequestForVariationClaim.RequestForVariationClaimEnhancedGrid",
t,{type:null,style:"border-top:none;",rowSelector:"0px",selectedItem:null,region:"center",project:null,locked:!1,keepSelection:!0,constructor:function(a){this.connects=[];this.formulatedColumn=u(this,{})},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments);if(!this.locked&&"requestForVariationClaimItems"==this.type){var a=this;this.on("RowClick",function(b){if(b.cell){var d=this.getItem(b.rowIndex);b=b.cell.field;if(d&&!isNaN(parseInt(String(d.id)))&&!d.claim_cert_number[0]&&
"claim_cert_number"==b){var e=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."});e.show().then(function(){dojo.xhrGet({url:"requestForVariationClaim/getOpenClaimCertificate",content:{pid:a.project.id},handleAs:"json",load:function(c){var f=parseInt(String(c.id));e.hide();!isNaN(f)&&0<f?buildspace.dialog.confirm(g.confirmation,"<div>"+g.requestForVariationClaimAttachClaimCertConfirm+"<br /><br /><b>Claim Certificate No.</b> : "+c.version+"</div>",120,380,function(){a.attachClaimCertificate(f,
parseInt(String(d.id)))}):buildspace.dialog.alert(g.noInProgressClaimCertificate,g.noInProgressClaimCertificateMsg,100,300)},error:function(c){e.hide()}})})}}})}},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],d=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(d,function(e,c){c=dojo.attr(e,"rowSpan");(!c||2>c)&&dojo.attr(e,"rowSpan",2)})}},canEdit:function(a,
b){var d=this;if(void 0!=a){var e=this.getItem(b);if(this.locked||"requestForVariationClaimItems"==this.type&&e&&!isNaN(parseInt(String(e.id)))&&!e.can_claim[0])return window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(b,a.index)},10),!1}return this._canEdit},doApplyCellEdit:function(a,b,d){var e=this,c=this.getItem(b),f=this.store,h=d.replace("-value","");-1!==d.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,b));if(!this.locked&&c&&!isNaN(parseInt(String(c.id)))&&
c.can_claim[0]&&a!==c[d][0]){var k=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."}),v={id:c.id,attr_name:h,val:a,_csrf_token:c._csrf_token?c._csrf_token:null};k=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."});k.show().then(function(){dojo.xhrPost({url:"requestForVariationClaim/claimItemUpdate",content:v,handleAs:"json",load:function(l){if(l.success){for(var m in l.data)c.hasOwnProperty(m)&&m!=f._getIdentifierAttribute()&&f.setValue(c,m,l.data[m]);f.save();
var w=e.getCellByField(d);window.setTimeout(function(){e.focus.setFocusIndex(b,w.index)},10);k.hide()}},error:function(l){k.hide()}})})}this.inherited(arguments)},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},editableCellDblClick:function(a){var b=1<this._click.length&&r("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=this._click[1].rowIndex?this._click[0]:a;this.focus.setFocusCell(b.cell,b.rowIndex);this.onRowClick(b);
this.onRowDblClick(a)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);else this.onCellDblClick(a);else this.onRowDblClick(a)},attachClaimCertificate:function(a,b){var d=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."}),e=this.store;d.show().then(function(){dojo.xhrPost({url:"requestForVariationClaim/claimCertificateAttach",content:{cid:a,id:b},handleAs:"json",load:function(c){c.success&&(e.fetchItemByIdentity({identity:c.item.id,onItem:function(f){for(var h in c.item)f.hasOwnProperty(h)&&
h!=e._getIdentifierAttribute()&&e.setValue(f,h,c.item[h]);e.save()}}),d.hide())},error:function(c){d.hide()}})})},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,p.disconnect);delete this._connects}});return n("buildspace.apps.PostContract.RequestForVariationClaim.RequestForVariationClaimGrid",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0;margin:0;width:100%;height:100%;",gutters:!1,project:null,requestForVariationClaim:null,gridOpts:{},locked:!1,type:null,
pageId:0,postCreate:function(){this.inherited(arguments);q.mixin(this.gridOpts,{type:this.type,project:this.project,requestForVariationClaim:this.requestForVariationClaim,locked:this.locked});var a=this.grid=new x(this.gridOpts);this.addChild(a);var b=dijit.byId("requestForVariationClaim-"+this.project.id+"-stackContainer");b&&(b.addChild(new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),content:this,grid:a,id:this.pageId,executeScripts:!0})),b.selectChild(this.pageId))}})});
