(function(){define("buildspace/apps/PostContractSubPackageReport/PrintProjectClaimReportFormDialog","dojo/_base/declare dojo/_base/lang dojo/keys dojo/parser dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/Toolbar dijit/form/Button dijit/layout/BorderContainer dijit/form/ValidationTextBox dijit/form/RadioButton dijit/form/SimpleTextarea dijit/registry dojo/dom-style dojo/dom-form dojo/request dojo/json dojox/validate/web dojox/form/Manager dojo/text!./templates/printProjectClaimReportForm.html dojo/i18n!buildspace/nls/TenderingReport".split(" "),
function(f,v,k,w,l,m,n,p,q,g,r,x,y,z,A,t,B,C,D,E,F,u,e){var h;h=f("buildspace.apps.PostContractSubPackageReport.PrintProjectClaimReportForm",[l,m,n,p],{baseClass:"buildspace-form",templateString:u,region:"center",style:"overflow: auto;",default_title_input:null,printURL:null,exportURL:null,subPackageId:-1,_csrf_token:null,nls:e,dialogContainer:null,print:function(){var a,c,b;b=this.viewTendererReportingPrintForm;if(!b.validate())return!1;a=dojo.formToObject(b.id);(b=document.getElementById("printingPreviewForm"))&&
b.parentNode.removeChild(b);b=document.createElement("form");b.setAttribute("method","post");b.setAttribute("action",this.printURL);b.setAttribute("id","printingPreviewForm");b.setAttribute("target","formresult");c=document.createElement("input");c.setAttribute("name","printingPageTitle");c.setAttribute("value",a.fileName);c.setAttribute("type","hidden");b.appendChild(c);c=document.createElement("input");c.setAttribute("name","exportFileName");c.setAttribute("value",a.exportFileName);c.setAttribute("type",
"hidden");b.appendChild(c);c=document.createElement("input");c.setAttribute("name","pageNoPrefix");c.setAttribute("value",a.pageNoPrefix);c.setAttribute("type","hidden");b.appendChild(c);0<this.subPackageId&&(a=document.createElement("input"),a.setAttribute("name","subPackageId"),a.setAttribute("value",this.subPackageId),a.setAttribute("type","hidden"),b.appendChild(a));a=document.createElement("input");a.setAttribute("name","_csrf_token");a.setAttribute("value",this._csrf_token);a.setAttribute("type",
"hidden");b.appendChild(a);document.body.appendChild(b);window.open(null,"formresult");return b.submit()},"export":function(){var a,c,b;b=this.viewTendererReportingPrintForm;if(!b.validate())return!1;a=dojo.formToObject(b.id);(b=document.getElementById("printingPreviewForm"))&&b.parentNode.removeChild(b);b=document.createElement("form");b.setAttribute("method","post");b.setAttribute("action",this.exportURL);b.setAttribute("id","printingPreviewForm");b.setAttribute("target","formresult");c=document.createElement("input");
c.setAttribute("name","printingPageTitle");c.setAttribute("value",a.fileName);c.setAttribute("type","hidden");b.appendChild(c);c=document.createElement("input");c.setAttribute("name","exportFileName");c.setAttribute("value",a.exportFileName);c.setAttribute("type","hidden");b.appendChild(c);c=document.createElement("input");c.setAttribute("name","pageNoPrefix");c.setAttribute("value",a.pageNoPrefix);c.setAttribute("type","hidden");b.appendChild(c);0<this.subPackageId&&(a=document.createElement("input"),
a.setAttribute("name","subPackageId"),a.setAttribute("value",this.subPackageId),a.setAttribute("type","hidden"),b.appendChild(a));a=document.createElement("input");a.setAttribute("name","_csrf_token");a.setAttribute("value",this._csrf_token);a.setAttribute("type","hidden");b.appendChild(a);document.body.appendChild(b);this.dialogContainer&&this.dialogContainer.hide();return b.submit()}});return f("buildspace.apps.PostContractSubPackageReport.PrePrintFormDialog",dijit.Dialog,{style:"padding:0px;margin:0px;width:480px;height:240px;",
printURL:null,exportURL:null,subPackageId:-1,_csrf_token:null,projectTitle:null,buildRendering:function(){var a;this.content=a=this.createContent();a.startup();return this.inherited(arguments)},postCreate:function(){t.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},createContent:function(a){var c,b,d;null==a&&(a=this);c=new r({style:"width:480px;height:240px;padding:0;margin:0;",gutters:!1});b=new h({default_title_input:a.projectTitle,
dialogContainer:a,printURL:a.printURL,exportURL:a.exportURL,subPackageId:a.subPackageId,_csrf_token:a._csrf_token});d=new q({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});d.addChild(new g({label:e.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.print()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new g({label:e.exportToExcel,iconClass:"icon-16-container icon-16-spreadsheet",onClick:function(){return b["export"]()}}));d.addChild(new dijit.ToolbarSeparator);
d.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return a.hide()}}));c.addChild(d);c.addChild(b);return c},_onKey:function(a){if(a.keyCode===k.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()}})})}).call(this);
