define("buildspace/apps/CostData/PrimeCostSumBreakdown","dojo/_base/declare dojo/number dojo/currency dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/DateTextBox ./LinkBillItems/ProjectListingGrid ./RowInclusion/RowInclusionDialog dojo/i18n!buildspace/nls/CostData".split(" "),function(n,p,q,r,y,z,s,t,e){var v=n("buildspace.apps.CostData.PrimeCostSumBreakdown",r,{style:"border:none;",region:"center",keepSelection:!0,escapeHTMLInData:!1,costData:null,constructor:function(a){this.inherited(arguments)},
canSort:function(a){return!1},postCreate:function(){this.inherited(arguments)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(c,function(a,b){var c=dojo.attr(a,"rowSpan");(!c||2>c)&&dojo.attr(a,"rowSpan",2)})}},dodblclick:function(a){this.onRowDblClick(a)},doApplyCellEdit:function(a,b,c){var d=
this,f=d.getItem(b),u=d.store,h="primeCostSum/updatePrimeCostSumItem";c.includes("additional_column-")&&(h="primeCostSum/updatePrimeCostSumColumn");if(a!==f[c][0]){var g=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),l=function(a,b){for(var c in a)f.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(f,c,a[c]);b.save()},h={url:h,content:{id:f.id,attr_name:c,val:a,cost_data_id:d.costData.id,item_id:f.id,_csrf_token:f._csrf_token?f._csrf_token:null},
handleAs:"json",load:function(a){if(a.success){0<f.id&&l(a.data,u);var e=d.getCellByField(c);window.setTimeout(function(){d.focus.setFocusIndex(b,e.index)},10)}g.hide()},error:function(a){g.hide()}};g.show();dojo.xhrPost(h)}d.inherited(arguments)},canEdit:function(a,b){return void 0!=a?0<this.getItem(b).id[0]:this._canEdit},reload:function(){this.store.close();this._refresh()}}),w=function(a,b){return parseInt(b)+1},k=function(a,b,c){b=this.grid.getItem(b);var d=p.parse(a);a=isNaN(d)||0==d||null==
d?"&nbsp;":q.format(a);d=!1;"awarded_cost"==this.field&&b.awarded_cost_derived&&b.awarded_cost_derived[0]?d=!0:void 0!==b[this.field+"-derived"]&&b[this.field+"-derived"][0]&&(d=!0);d&&(a='<span style="color: #42b449;"><strong>'+a+"</strong></span>",c.customClasses.push("light-blue-cell"));return a},x=function(a,b,c){b=p.parse(a);c.customClasses.push("disable-cell");return a=isNaN(b)||0==b||null==b?"&nbsp;":q.format(a)};return n("buildspace.apps.CostData.PrimeCostSumContainer",dijit.layout.BorderContainer,
{region:"center",title:"",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,costData:null,grid:null,mainBreakdownGrid:null,columns:[],editable:!1,postCreate:function(){this.inherited(arguments);var a=this,b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});b.show();dojo.xhrPost({url:"primeCostSum/getColumns/costData/"+a.costData.id,handleAs:"json",load:function(b){a.columns=b.columns},error:function(a){}}).then(function(){var c=a.createBreakdownGrid(),c=new dijit.layout.ContentPane({style:"padding:0px;border:none;width:100%;height:100%;",
region:"center",content:c,grid:c});a.addChild(a.createToolbar());a.addChild(c);b.hide()})},createToolbar:function(){var a=this,b=new dijit.Toolbar({region:"top",style:"outline:none!important;border:none;padding:2px;width:100%;"});b.addChild(new dijit.form.Button({id:this.costData.id+"prime-cost-sum-refresh-button",label:e.refresh,iconClass:"icon-16-container icon-16-reload",style:"outline:none!important;",onClick:function(){a.mainBreakdownGrid.reloadPrimeCostSumGrid()}}));a.editable&&(b.addChild(new dijit.ToolbarSeparator),
b.addChild(new dijit.form.Button({id:this.costData.id+"-prime-cost-sum-row-inclusion-button",label:e.showHideRows,iconClass:"icon-16-container icon-16-dial",style:"outline:none!important;",onClick:function(){a.createRowVisibilityDialog()}})));return b},getGridStructure:function(){var a=this.columns,b="auto";2<=a.length&&(b="500px");var b=[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",rowSpan:2,formatter:w},{name:e.description,field:"description",rowSpan:2,width:b,cellType:"buildspace.widget.grid.cells.Textarea"},
{name:e.budget,field:"approved_cost",width:"140px",rowSpan:2,cellType:"buildspace.widget.grid.cells.Textarea",editable:this.editable,styles:"text-align:right;",formatter:k},{name:e.contractSum,field:"awarded_cost",width:"140px",rowSpan:2,cellType:"buildspace.widget.grid.cells.Textarea",editable:this.editable,styles:"text-align:right;",formatter:k}],c;for(c in a)b.push({name:a[c].column_name,field:"additional_column-"+a[c].id,width:"140px",cellType:"buildspace.widget.grid.cells.Textarea",editable:this.editable,
styles:"text-align:right;",formatter:k});b.push({name:e.totalAmount,field:"nominated_sub_contractor_total_amount",width:"140px",styles:"text-align:right;",formatter:x});b.push({name:e.awardedContractor,field:"awarded_nominated_sub_contractor",width:"140px",cellType:"buildspace.widget.grid.cells.Textarea",editable:this.editable,styles:"text-align:center;"});b.push({name:e.awardedDate,field:"awarded_date",width:"120px",cellType:"buildspace.widget.grid.cells.DateTextBox",editable:this.editable,styles:"text-align:center;"});
return{noscroll:!1,cells:[b,[{name:e.awardedNominatedSubContractor,styles:"text-align:center;",headerClasses:"staticHeader",colSpan:b.length-4}]]}},createBreakdownGrid:function(){var a=this;a.grid=v({costData:a.costData,structure:a.getGridStructure(),store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"primeCostSum/getPrimeCostSumBreakdown/costData/"+this.costData.id}),onRowDblClick:function(b){var c=this.getItem(b.rowIndex);if(0<c.id[0]&&a.editable){b=b.cell.field;var d=[],f=a.columns,e;
for(e in f)d.push("additional_column-"+f[e].id);"awarded_cost"==b&&a.createItemLinkBillItemsGrid(c);d.includes(b)&&a.createColumnLinkBillItemsGrid(c,b.replace("additional_column-",""))}}});return a.grid},createRowVisibilityDialog:function(){var a=this,b=[];dojo.forEach(a.grid.store._arrayOfAllItems,function(a,d){0<a.id[0]&&b.push(a.id[0])});(new t({title:e.showHideRows,gridUrl:"primeCostSum/getAllPrimeCostSumItemRecords/costData/"+a.costData.id,saveUrl:"primeCostSum/updateItemVisibility/costData/"+
a.costData.id+"/_csrf_token/"+a.costData._csrf_token,selectedItemIds:b,deselectedItemIds:[],onSave:function(){a.grid.reload()}})).show()},createItemLinkBillItemsStackContainer:function(a,b,c,d,e,k,h){var g=this,l="linkBillItems-"+g.costData.id+"-projectListingGrid",m=dijit.byId(l);m&&(g.removeChild(m),m.destroy());return new s({id:l,title:buildspace.truncateString(a.description,60),region:"bottom",parentContainer:g,costData:g.costData,linkItem:a,item:a,style:"padding:0px;margin:0px;width:100%;height:80%;",
selectedItemIds:b,conversionFactor:c,updateUrl:d,linkedProjectsUrl:e,linkedBillsUrl:k,linkedElementsUrl:h,onSave:function(){g.grid.reload()}})},createItemLinkBillItemsGrid:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});c.show().then(function(){dojo.xhrGet({url:"primeCostSum/getItemLinkedItems/cost_data_id/"+b.costData.id+"/id/"+a.id+"/id_type/bill_item_id",handleAs:"json",load:function(d){d.success&&b.addChild(b.createItemLinkBillItemsStackContainer(a,
d.ids,d.conversion_factor,"primeCostSum/linkItemToBillItems/id/"+a.id+"/_csrf_token/"+a._csrf_token,"primeCostSum/getItemLinkedItems/cost_data_id/"+b.costData.id+"/id/"+a.id+"/id_type/project_id","primeCostSum/getItemLinkedItems/cost_data_id/"+b.costData.id+"/id/"+a.id+"/id_type/bill_id","primeCostSum/getItemLinkedItems/cost_data_id/"+b.costData.id+"/id/"+a.id+"/id_type/element_id"));c.hide()},error:function(a){}})})},createColumnLinkBillItemsGrid:function(a,b){var c=this,d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+
"..."});d.show().then(function(){dojo.xhrGet({url:"primeCostSum/getColumnLinkedItems/id/"+a.id+"/column_id/"+b+"/id_type/bill_item_id",handleAs:"json",load:function(e){e.success&&c.addChild(c.createItemLinkBillItemsStackContainer(a,e.ids,e.conversion_factor,"primeCostSum/linkColumnToBillItems/id/"+a.id+"/column_id/"+b+"/_csrf_token/"+a._csrf_token,"primeCostSum/getColumnLinkedItems/id/"+a.id+"/column_id/"+b+"/id_type/project_id","primeCostSum/getColumnLinkedItems/id/"+a.id+"/column_id/"+b+"/id_type/bill_id",
"primeCostSum/getColumnLinkedItems/id/"+a.id+"/column_id/"+b+"/id_type/element_id"));d.hide()},error:function(a){}})})}})});
