define("buildspace/apps/CostData/ProjectInformation","dojo/_base/declare dojo/_base/lang dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter ./ProjectInformationComparisonReport/ComparisonReportDialog dojo/i18n!buildspace/nls/CostData".split(" "),function(l,u,n,v,p,g){var q=l("buildspace.apps.CostData.ProjectInformationGrid",n,{style:"border:none;",region:"center",keepSelection:!0,escapeHTMLInData:!1,costData:null,parentItem:null,constructor:function(a){this.inherited(arguments)},canSort:function(a){return!1},
postCreate:function(){this.inherited(arguments)},dodblclick:function(a){this.onRowDblClick(a)},focusCell:function(a,b){var d=this,c=d.getCellByField(b);window.setTimeout(function(){d.focus.setFocusIndex(a,c.index)},10)},updateRecord:function(a,b,d){var c=this,e=c.getItem(b),f=c.store,m=buildspace.dialog.indeterminateProgressBar({title:g.savingData+". "+g.pleaseWait+"..."});a={url:"projectInformation/updateItem",content:{id:e.id,val:a,cost_data_id:c.costData.id,item_id:e.id,_csrf_token:e._csrf_token?
e._csrf_token:null},handleAs:"json",load:function(h){if(h.success){if(0<e.id){h=h.data;for(var k in h)e.hasOwnProperty(k)&&k!=f._getIdentifierAttribute()&&f.setValue(e,k,h[k]);f.save()}c.focusCell(b,d)}m.hide()},error:function(h){m.hide()}};m.show();dojo.xhrPost(a)},doApplyCellEdit:function(a,b,d){var c=this.getItem(b);a!==c[d][0]&&this.updateRecord(a,b,d);this.inherited(arguments)},canEdit:function(a,b){return void 0!=a?0<this.getItem(b).id[0]:this._canEdit},reload:function(){this.store.close();
this._refresh()}}),r=function(a,b){return parseInt(b)+1},t=l("buildspace.apps.CostData.ProjectInformationContainer",dijit.layout.BorderContainer,{region:"center",title:"",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,costData:null,grid:null,stackContainer:null,level:null,parentItem:null,postCreate:function(){this.inherited(arguments);var a=this.createBreakdownGrid();a=new dijit.layout.ContentPane({style:"padding:0px;border:none;width:100%;height:100%;",region:"center",content:a,
grid:a});this.addChild(this.createToolbar());this.addChild(a)},createToolbar:function(){var a=this,b=new dijit.Toolbar({region:"top",style:"outline:none!important;border:none;padding:2px;width:100%;"});b.addChild(new dijit.form.Button({label:g.refresh,iconClass:"icon-16-container icon-16-reload",style:"outline:none!important;",onClick:function(){a.grid.reload()}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({label:g.comparisonReport,iconClass:"icon-16-container icon-16-print",
style:"outline:none!important;",onClick:function(){a.createComparisonReportDialog()}}));return b},createBreakdownGrid:function(){var a=this,b=[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:r},{name:g.item,field:"description",width:1==this.level?"auto":"280px"}];1<this.level&&b.push({name:g.description,field:"value",width:"auto",cellType:"buildspace.widget.grid.cells.Textarea",editable:!0});var d="projectInformation/getBreakdown/costData/"+this.costData.id;this.parentItem&&
(d+="/parent_id/"+this.parentItem.id);a.grid=q({costData:a.costData,parentItem:a.parentItem,structure:b,store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:d}),onRowDblClick:function(c){c=this.getItem(c.rowIndex);2>a.level&&0<c.id[0]&&a.stackContainer.addBreakdownContainer(c,a.level+1)}});return a.grid},createComparisonReportDialog:function(){var a="projectInformationComparisonReport/export/costData/"+this.costData.id;this.parentItem&&(a=a+"/parent_id/"+this.parentItem.id);(new p({gridUrl:"costData/getCostDataList/costData/"+
this.costData.id,title:g.comparisonReport,exportUrl:a,costData:this.costData,projectInfoItem:this.parentItem})).show()}});return l("buildspace.apps.CostData.ProjectInformationStackContainer",dijit.layout.BorderContainer,{region:"center",title:"",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,costData:null,grid:null,stackContainer:null,level:null,postCreate:function(){this.inherited(arguments);this.stackContainer=this.createStackContainer();this.addBreakdownContainer(null,1)},createStackContainer:function(){var a=
"costDataProjectInformation"+this.costData.id+"-stackContainer",b=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:a});dojo.subscribe(a+"-selectChild","",function(c){var e=dijit.byId(a);if(e){var f=e.getChildren();c=dojo.indexOf(f,c);c+=1;if(f.length>c)for(;f.length>c;)e.removeChild(f[c]),f[c].destroyDescendants(),f[c].destroyRecursive(),c+=1}});var d=new dijit.layout.StackController({region:"top",containerId:a});d=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",
baseClass:"breadCrumbTrail",region:"top",id:"costDataProjectInformation"+this.costData.id+"-controllerPane",content:d});this.addChild(b);this.addChild(d);return b},addBreakdownContainer:function(a,b){a=new t({title:buildspace.truncateString(a?a.description:g.projectInfo,60),costData:this.costData,level:b,stackContainer:this,parentItem:a});this.stackContainer.addChild(a);1<this.stackContainer.getChildren().length&&this.stackContainer.selectChild(a)}})});
