define("buildspace/apps/BQLibrary/buildUpGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojo/_base/connect dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/currency dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox dijit/popup dijit/TooltipDialog ./importResourceDialog dojo/i18n!buildspace/nls/BuildUpGrid".split(" "),
function(q,r,D,E,n,F,G,u,v,w,x,y,p,z,H,I,J,K,L,l,t,A,h){var C=q("buildspace.apps.BQLibrary.BuildUp.grid",dojox.grid.EnhancedGrid,{itemId:-1,resource:null,bqItemId:0,style:"border-top:none;",selectedItem:null,unitObj:null,keepSelection:!0,addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,buildUpSummaryWidget:null,constructor:function(b){this.rearranger=u(this,{});this.formulatedColumn=v(this,{})},canSort:function(b){return!1},postCreate:function(){var b=this,a=null;b.inherited(arguments);this.on("RowContextMenu",
function(a){b.selection.clear();var c=b.getItem(a.rowIndex);b.selection.setSelected(a.rowIndex,!0);b.contextMenu(a);0<c.id?b.disableToolbarButtons(!1):b.disableToolbarButtons(!0,["Add"])},!0);this.on("RowClick",function(a){(a=b.getItem(a.rowIndex))&&0<a.id?b.disableToolbarButtons(!1):b.disableToolbarButtons(!0,["Add"])});this._connects.push(n.connect(this,"onCellMouseOver",function(b){var c=b.cell.field,d=b.rowIndex,g=this.getItem(d),c=c.replace("-value","");"undefined"!==typeof g[c+"-has_formula"]&&
g[c+"-has_formula"][0]&&(g=g[c+"-value"][0],g=this.formulatedColumn.convertItemIdToRowIndex(g,d),null===a&&(a=new t({content:g,onMouseLeave:function(){l.close(a)}}),l.open({popup:a,around:b.cellNode})))}));this._connects.push(n.connect(this,"onCellMouseOut",function(){null!==a&&(l.close(a),a=null)}));this._connects.push(n.connect(this,"onStartEdit",function(){null!==a&&(l.close(a),a=null)}))},doApplyCellEdit:function(b,a,c){var e=this,d=e.getItem(a),g=e.store,k=c.replace("-value","");-1!==c.indexOf("-value")&&
(b=this.formulatedColumn.convertRowIndexToItemId(b,a));if(b!==d[c][0]){var k={id:d.id,attr_name:k,val:b,_csrf_token:d._csrf_token?d._csrf_token:null},f=this.updateUrl;d.id==buildspace.constants.GRID_LAST_ROW&&(f=0<a?e.getItem(a-1):!1,r.mixin(k,{prev_item_id:f?f.id:0,relation_id:d.relation_id,resource_id:e.resource.id}),f=this.addUrl);var B=function(a,b){for(var c in a)d.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(d,c,a[c]),dojo.forEach(a.affected_nodes,function(a){b.fetchItemByIdentity({identity:a.id,
onItem:function(c){for(var f in a)d.hasOwnProperty(f)&&f!=b._getIdentifierAttribute()&&b.setValue(c,f,a[f])}})});b.save()},m=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});m.show();dojo.xhrPost({url:f,content:k,handleAs:"json",load:function(b){if(b.success){0<d.id?B(b.data,g):(g.deleteItem(d),g.save(),dojo.forEach(b.items,function(a){g.newItem(a)}),g.save(),e.disableToolbarButtons(!0));e.updateTotalBuildUp(b.total_build_up);var f=e.getCellByField(c);window.setTimeout(function(){e.focus.setFocusIndex(a,
f.index)},10)}m.hide()},error:function(a){m.hide()}})}e.inherited(arguments)},dodblclick:function(b){},onCellFocus:function(b,a){var c=this,e=c.getItem(a);"description"!==b.field||0>e.id[0]||!e.linked[0]?c.closeToolTipDialogIfAvailable():dojo.xhrGet({url:"resourceLibrary/getBuildUpRatesToolTipInformation",content:{id:e.id,type:"bqLibrary"},handleAs:"json",load:function(d){if(d.success){c.closeToolTipDialogIfAvailable();var e=!1,k='<h1 style="font-size: 12px; text-shadow: 1px 1px 1px #000;background-color: rgba(35, 35, 35, .85); color: #fff; padding: 4px 10px;">'+
d.items[0].description+"</h1>";1<Object.keys(d.items).length&&(e=!0,k+='<table style="width: 100%; border-collapse: collapse;">');dojo.forEach(d.items,function(a,b){0!==b&&(k+='<tr><td style="border: 1px dotted #D5CDB5; font-weight: bold; font-size: 11px; padding-left:'+16*a.level+'px;">'+a.description+"</td></td>")});e&&(k+="</table>");c.myTooltipDialog=new t({id:"buildUpRatesTooltipDialog-"+c.itemId[0],style:"width: 300px;",content:k});l.open({popup:c.myTooltipDialog,around:b.view.rowNodes[a],orient:["below"]})}},
error:function(a){console.log(a)}})},onRowMouseOut:function(){this.closeToolTipDialogIfAvailable()},addRow:function(b){p.curNode.blur();p.curNode=null;var a=this,c=buildspace.dialog.indeterminateProgressBar({title:h.addingRow+". "+h.pleaseWait+"..."}),e=a.store,d=a.getItem(b);if(0<d.id)d={before_id:d.id,_csrf_token:d._csrf_token};else var g=0<b?a.getItem(b-1).id:0,d={id:d.id,prev_item_id:g,relation_id:d.relation_id,resource_id:a.resource.id,_csrf_token:d._csrf_token};c.show();dojo.xhrPost({url:this.addUrl,
content:d,handleAs:"json",load:function(d){d.success&&dojo.forEach(d.items,function(c){0<c.id&&(c=e.newItem(c),e.save(),c=a.getItemIndex(c),a.rearranger.moveRows([c],b),a.selection.clear())});window.setTimeout(function(){a.selection.setSelected(b,!0);a.focus.setFocusIndex(b,1)},30);c.hide()},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);c.hide()}})},deleteRow:function(b){var a=this,c=a.getItem(b),e=buildspace.dialog.indeterminateProgressBar({title:h.deleting+". "+h.pleaseWait+
"..."});p.curNode.blur();p.curNode=null;e.show();var d={url:this.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(d){if(d.success){var g=d.affected_nodes,f=a.store;f.deleteItem(c);f.save();for(var h=0,m=g.length;h<m;++h)f.fetchItemByIdentity({identity:g[h].id,onItem:function(a){for(var b in g[h])a.hasOwnProperty(b)&&b!=f._getIdentifierAttribute()&&f.setValue(a,b,g[h][b]);f.save()}});a.updateTotalBuildUp(d.total_build_up)}e.hide();a.selection.clear();window.setTimeout(function(){a.focus.setFocusIndex(b,
0)},10);a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;e.hide()}};new buildspace.dialog.confirm(h.deleteBuildUpRateItemTitle,h.deleteBuildUpRateItemMsg,80,320,function(){dojo.xhrPost(d)},function(){e.hide()})},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp=
"copy"},pasteItem:function(b){var a=this,c=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."}),e=a.store,d=a.selection.getFirstSelected(),g=d.id==buildspace.constants.GRID_LAST_ROW&&0<b?a.getItem(b-1).id:0;c.show();dojo.xhrPost({url:this.pasteUrl,content:{type:a.pasteOp,target_id:d.id,id:a.selectedItem.id,prev_item_id:g,_csrf_token:a.selectedItem._csrf_token},handleAs:"json",load:function(d){var f=[];if(d.success)switch(a.pasteOp){case "cut":e.fetchItemByIdentity({identity:d.data.id,
onItem:function(c){c=a.getItemIndex(c);f.push(c);0<f.length&&a.rearranger.moveRows(f,b);a.selectAfterPaste(c>b?b:b-1,!0)}});break;case "copy":var g=e.newItem(d.data);e.save();g=a.getItemIndex(g);f.push(g);0<f.length&&(a.rearranger.moveRows(f,b),a.selectAfterPaste(b,!1));a.updateTotalBuildUp(d.total_build_up)}a.disableToolbarButtons(!1);a.pasteOp=null;f.length=0;c.hide()},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;c.hide()}})},selectAfterPaste:function(b,
a){this.selection.clear();this.selectedItem=null;this.selection.setSelected(b,!0);a&&this.scrollToRow(0<b-3?b-3:b)},contextMenu:function(b){var a=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(b);var c={target:b.target,coords:b.keyCode!==x.F10&&"pageX"in b?{x:b.pageX,y:b.pageY}:null},e=this.getItem(b.rowIndex);a&&e&&(this.selection.isSelected(b.rowIndex)||b.rowNode&&z.hasClass(b.rowNode,"dojoxGridRowbar"))&&(a._openMyself(c),w.stop(b))},contextMenuItems:function(b){var a=this.getItem(b.rowIndex);
0<a.id&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:h.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItems")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:h.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(this,"copyItems")})));this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:h.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(this,"pasteItem",b.rowIndex),disabled:this.selectedItem?!1:!0}));this.rowCtxMenu.addChild(new dijit.MenuItem({label:h.addRow,
iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow",b.rowIndex,"lala")}));0<a.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:h.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow",b.rowIndex)}))},disableToolbarButtons:function(b,a){var c=dijit.byId("builUpGrid-"+this.resource.id+"_"+this.bqItemId+"AddRow-button"),e=dijit.byId("builUpGrid-"+this.resource.id+"_"+this.bqItemId+"DeleteRow-button");c._setDisabledAttr(b);e._setDisabledAttr(b);
if(b&&a instanceof Array){var d=this;dojo.forEach(a,function(a){dijit.byId("builUpGrid-"+d.resource.id+"_"+d.bqItemId+a+"Row-button")._setDisabledAttr(!1)})}},updateTotalBuildUp:function(b){dijit.byId("accPane-"+this.resource.id+"-"+this.bqItemId).set("title",this.resource.name+'<span style="color:blue;float:right;">'+buildspace.currencyAbbreviation+"&nbsp;"+y.format(b)+"</span>");this.buildUpSummaryWidget.refreshTotalCost()},closeToolTipDialogIfAvailable:function(){var b=dijit.byId("buildUpRatesTooltipDialog-"+
this.itemId[0]);void 0!==this.myTooltipDialog&&void 0!==b&&(l.close(),b.destroy())},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,n.disconnect);delete this._connects}});return q("buildspace.apps.BQLibrary.BuildUpGrid",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,resource:null,bqItemId:0,gridOpts:{},postCreate:function(){var b=this;b.inherited(arguments);r.mixin(b.gridOpts,{resource:b.resource,bqItemId:b.bqItemId,region:"center"});
var a=this.grid=new C(b.gridOpts),c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({id:"builUpGrid-"+b.resource.id+"_"+b.bqItemId+"AddRow-button",label:h.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.addRow(a.selection.selectedIndex)}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"builUpGrid-"+b.resource.id+
"_"+b.bqItemId+"DeleteRow-button",label:h.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.deleteRow(a.selection.selectedIndex)}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:h.importFromResourceLibrary,iconClass:"icon-16-container icon-16-import",onClick:function(){A({itemId:b.bqItemId,resource:b.resource,buildUpGridStore:a.store}).show()}}));b.addChild(c);b.addChild(new dijit.layout.ContentPane({style:"width:100%",
content:a,region:"center"}))}})});
