define("buildspace/apps/BQLibrary/buildUpSummary","dojo/_base/declare dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Button dijit/form/TextBox dijit/form/CheckBox dijit/form/Select dojo/text!./templates/buildUpSummary.html dojo/currency dojo/i18n!buildspace/nls/BQLibrary".split(" "),function(g,h,k,l,m,q,r,t,n,p,d,f){return g("buildspace.apps.BQLibrary.buildUpSummary",[h,k,l,m],{templateString:p,style:"outline:none;",itemId:-1,nls:f,region:"bottom",
_csrf_token:null,container:null,applyConversionFactor:!1,conversionFactorAmount:0,conversionFactorOperator:buildspace.constants.ARITHMETIC_OPERATOR_MULTIPLICATION,totalCost:0,totalCostAfterConversion:0,markup:0,finalCost:0,constructor:function(a){this.inherited(arguments)},postCreate:function(){this.inherited(arguments);var a=this;dojo.xhrGet({url:"bqLibrary/getBuildUpSummary",content:{id:this.itemId},handleAs:"json",load:function(c){a.applyConversionFactor=c.apply_conversion_factor;a.applyConversionFactorNode.set("checked",
a.applyConversionFactor);a.doApplyConversionFactor();a.conversionFactorAmount=c.conversion_factor_amount;a.conversionFactorAmountNode.set("value",a.conversionFactorAmount);a.conversionFactorOperator=c.conversion_factor_operator;a.conversionFactorOperatorNode.set("value",a.conversionFactorOperator);var b=a.totalCost=d.format(c.total_cost);dojo.attr(a.totalCostNode,"innerHTML",b);b=a.totalCostAfterConversion=d.format(c.total_cost_after_conversion);dojo.attr(a.totalCostAfterConversionNode,"innerHTML",
b);b=a.finalCost=d.format(c.final_cost);dojo.attr(a.finalCostNode,"innerHTML",b);c=a.markup=d.format(c.markup);a.markupNode.set("value",c)},error:function(a){console.log(a)}})},startup:function(){this.inherited(arguments);this.toggleConversionFactorRows(!1)},submitMarkup:function(){var a=this.markupNode.get("value");if(a!=this.markup){var c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});c.show();var b=this;dojo.xhrPost({url:"bqLibrary/buildUpSummaryMarkupUpdate",content:{id:this.itemId,
value:a,_csrf_token:this._csrf_token},handleAs:"json",load:function(a){var e=b.finalCost=d.format(a.final_cost);dojo.attr(b.finalCostNode,"innerHTML",e);a=b.markup=d.format(a.markup);b.markupNode.set("value",a);c.hide()},error:function(a){console.log(a);c.hide()}})}},doApplyConversionFactor:function(){var a=this.applyConversionFactorNode.get("checked");if(a!=this.applyConversionFactor){var c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});c.show();var b=this;dojo.xhrPost({url:"bqLibrary/buildUpSummaryApplyConversionFactorUpdate",
content:{id:this.itemId,value:a,_csrf_token:this._csrf_token},handleAs:"json",load:function(a){b.conversionFactorAmount=a.conversion_factor_amount;b.conversionFactorAmountNode.set("value",b.conversionFactorAmount);b.conversionFactorOperator=a.conversion_factor_operator;b.conversionFactorOperatorNode.set("value",b.conversionFactorOperator);var e=b.totalCostAfterConversion=d.format(a.total_cost_after_conversion);dojo.attr(b.totalCostAfterConversionNode,"innerHTML",e);a=b.finalCost=d.format(a.final_cost);
dojo.attr(b.finalCostNode,"innerHTML",a);c.hide()},error:function(a){console.log(a);c.hide()}})}this.applyConversionFactor=a;this.toggleConversionFactorRows(a)},toggleConversionFactorRows:function(a){if(a){var c=this;dojo.xhrPost({url:"bqLibrary/getConversionFactorUom",content:{id:this.itemId},handleAs:"json",load:function(a){new n({name:"bq_library_build_up_rate[conversion_factor_uom_id]",style:"width:100%;",options:a.uomOptions,onChange:function(){c.submitConversionFactorUOM(this.value)}},c.conversionFactorUOMNode);
dojo.query("."+c.itemId+"-conversion_factor-row").style({display:""});c.container.resize()},error:function(a){console.log(a)}})}else dojo.query("."+this.itemId+"-conversion_factor-row").style({display:"none"}),this.container.resize()},submitConversionFactorAmount:function(){var a=this.conversionFactorAmountNode.get("value");if(a!=this.conversionFactorAmount){var c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});c.show();var b=this;dojo.xhrPost({url:"bqLibrary/buildUpSummaryConversionFactorUpdate",
content:{id:this.itemId,val:a,type:"amount",_csrf_token:this._csrf_token},handleAs:"json",load:function(a){b.conversionFactorAmount=a.conversion_factor_amount;b.conversionFactorAmountNode.set("value",b.conversionFactorAmount);var e=b.totalCostAfterConversion=d.format(a.total_cost_after_conversion);dojo.attr(b.totalCostAfterConversionNode,"innerHTML",e);a=b.finalCost=d.format(a.final_cost);dojo.attr(b.finalCostNode,"innerHTML",a);c.hide()},error:function(a){console.log(a);c.hide()}})}},submitConversionFactorOperator:function(){var a=
this.conversionFactorOperatorNode.get("value");if(a!=this.conversionFactorOperator){var c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});c.show();var b=this;dojo.xhrPost({url:"bqLibrary/buildUpSummaryConversionFactorUpdate",content:{id:this.itemId,val:a,type:"operator",_csrf_token:this._csrf_token},handleAs:"json",load:function(a){b.conversionFactorOperator=a.conversion_factor_operator;b.conversionFactorOperatorNode.set("value",b.conversionFactorOperator);var e=b.totalCostAfterConversion=
d.format(a.total_cost_after_conversion);dojo.attr(b.totalCostAfterConversionNode,"innerHTML",e);a=b.finalCost=d.format(a.final_cost);dojo.attr(b.finalCostNode,"innerHTML",a);c.hide()},error:function(a){console.log(a);c.hide()}})}},submitConversionFactorUOM:function(a){var c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});c.show();dojo.xhrPost({url:"bqLibrary/buildUpSummaryConversionFactorUomUpdate",content:{id:this.itemId,uom_id:a,_csrf_token:this._csrf_token},handleAs:"json",
load:function(a){c.hide()},error:function(a){console.log(a);c.hide()}})},refreshTotalCost:function(){var a=this;dojo.xhrGet({url:"bqLibrary/getBuildUpSummary",content:{id:this.itemId},handleAs:"json",load:function(c){var b=a.totalCost=d.format(c.total_cost);dojo.attr(a.totalCostNode,"innerHTML",b);b=a.totalCostAfterConversion=d.format(c.total_cost_after_conversion);dojo.attr(a.totalCostAfterConversionNode,"innerHTML",b);c=a.finalCost=d.format(c.final_cost);dojo.attr(a.finalCostNode,"innerHTML",c)},
error:function(a){console.log(a)}})}})});
