define("buildspace/apps/BQLibrary/grid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojo/_base/connect dijit/TooltipDialog dijit/popup dojox/grid/enhanced/plugins/Menu dojo/number dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox ./fileImportDialog ./ImportBuildspaceZipFile ./BQLibraryExportBuildspaceZipFile dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dojo/i18n!buildspace/nls/BQLibrary buildspace/widget/grid/Filter".split(" "),
function(w,v,M,N,q,C,r,O,x,P,D,E,F,G,l,H,Q,R,S,T,t,I,J,y,z,m,e,K){var L=w("buildspace.apps.BQLibrary.Grid",dojox.grid.EnhancedGrid,{type:null,libraryId:0,elementId:0,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,indentUrl:null,outdentUrl:null,constructor:function(b){this.rearranger=D(this,{});this.formulatedColumn=E(this,{})},canSort:function(b){return!1},canEdit:function(b,a){var c=this;if("tree"==this.type&&
void 0!=b){var d=this.getItem(a),f=b.field;if("type"===f){var g=this.getItem(a+1);if(0<d.id[0]&&d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&void 0!==g&&d.level[0]<g.level[0]){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(a,b.index)},10);return}}if(0<d.id[0]&&d.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM&&("rate-value"==f||"uom_id"==f))return window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(a,b.index)},10),!1}return this._canEdit},
postCreate:function(){var b=this,a=null;this.inherited(arguments);this.on("RowContextMenu",function(a){b.selection.clear();var d=b.getItem(a.rowIndex);b.selection.setSelected(a.rowIndex,!0);b.contextMenu(a);0<d.id?b.disableToolbarButtons(!1):b.disableToolbarButtons(!0,["Add"])},!0);this.on("RowClick",function(a){(a=b.getItem(a.rowIndex))&&0<a.id?b.disableToolbarButtons(!1):b.disableToolbarButtons(!0,["Add"])});"tree"===b.type&&(this._connects.push(q.connect(this,"onCellMouseOver",function(b){var d=
b.cell.field,c=b.rowIndex,g=this.getItem(c),d=d.replace("-value","");"undefined"!==typeof g[d+"-has_formula"]&&g[d+"-has_formula"][0]&&(g=g[d+"-value"][0],g=this.formulatedColumn.convertItemIdToRowIndex(g,c),null===a&&(a=new C({content:g,onMouseLeave:function(){r.close(a)}}),r.open({popup:a,around:b.cellNode})))})),this._connects.push(q.connect(this,"onCellMouseOut",function(){null!==a&&(r.close(a),a=null)})),this._connects.push(q.connect(this,"onStartEdit",function(){null!==a&&(r.close(a),a=null)})))},
doApplyCellEdit:function(b,a,c){var d=this,f=d.getItem(a),g=d.store,h=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),k=c.replace("-value","");-1!==c.indexOf("-value")&&(b=this.formulatedColumn.convertRowIndexToItemId(b,a));if(b!==f[c][0]){var A={id:f.id,attr_name:k,val:b,_csrf_token:f._csrf_token?f._csrf_token:null},n=this.updateUrl;f.id==buildspace.constants.GRID_LAST_ROW&&(n=0<a?d.getItem(a-1):!1,v.mixin(A,{prev_item_id:n?n.id:0,relation_id:f.relation_id}),n=this.addUrl);
var u=d.getCellByField(c),p=function(a,b){for(var d in a)f.hasOwnProperty(d)&&d!=b._getIdentifierAttribute()&&b.setValue(f,d,a[d]),dojo.forEach(a.affected_nodes,function(a){b.fetchItemByIdentity({identity:a.id,onItem:function(d){for(var c in a)f.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(d,c,a[c])}})});b.save()},B={url:n,content:A,handleAs:"json",load:function(b){b.success&&(0<f.id?p(b.data,g):(g.deleteItem(f),g.save(),dojo.forEach(b.items,function(a){g.newItem(a)}),g.save(),d.disableToolbarButtons(!0)),
window.setTimeout(function(){d.focus.setFocusIndex(a,u.index)},10),h.hide())},error:function(a){h.hide()}};void 0!=f[k+"-has_build_up"]&&f[k+"-has_build_up"][0]?(buildspace.dialog.confirm(e.confirmation,"<div>"+e.detachAllBuildUpAndLink+"</div>",60,280,function(){dojo.xhrPost(B)},function(){h.hide();window.setTimeout(function(){d.focus.setFocusIndex(a,u.index)},10)}),d.doCancelEdit(a)):(h.show(),dojo.xhrPost(B),d.inherited(arguments))}else d.inherited(arguments)},doCancelEdit:function(b){this.inherited(arguments);
this.views.renormalizeRow(b);this.scroller.rowHeightChanged(b,!0)},dodblclick:function(b){this.onRowDblClick(b)},contextMenu:function(b){var a=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(b);var c={target:b.target,coords:b.keyCode!==G.F10&&"pageX"in b?{x:b.pageX,y:b.pageY}:null},d=this.getItem(b.rowIndex);a&&d&&(this.selection.isSelected(b.rowIndex)||b.rowNode&&H.hasClass(b.rowNode,"dojoxGridRowbar"))&&(a._openMyself(c),F.stop(b))},contextMenuItems:function(b){var a=this,c=this.getItem(b.rowIndex),
d=b.cell;if(0<c.id&&(a.rowCtxMenu.addChild(new dijit.MenuItem({label:e.cut,iconClass:"icon-16-container icon-16-cut",onClick:function(){a.pasteType="structure";a.cutItems()}})),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(a,"copyItems")})),"tree"==a.type&&"rate-value"==d.field)){var f=x.parse(c["rate-final_value"]);a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e.copyRate,iconClass:"icon-16-container icon-16-copy",
disabled:isNaN(f)||0==f||null==f?!0:!1,onClick:dojo.hitch(a,"copyCell","rate")}))}var f=!0,g="pasteItem";"tree"==a.type&&a.selectedItem?"rate"==a.copyCellType&&0<c.id&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID?(f=!1,g="pasteCell"):null==a.copyCellType&&(f=!1):f=a.selectedItem?!1:!0;a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(a,g,b.rowIndex),
disabled:f}));0<c.id&&"tree"==a.type&&(a.rowCtxMenu.addChild(new dijit.MenuItem({label:e.indent,iconClass:"icon-16-container icon-16-indent",onClick:dojo.hitch(a,"indentOutdent",b.rowIndex,"indent")})),a.rowCtxMenu.addChild(new dijit.MenuItem({label:e.outdent,iconClass:"icon-16-container icon-16-outdent",onClick:dojo.hitch(a,"indentOutdent",b.rowIndex,"outdent")})));a.rowCtxMenu.addChild(new dijit.MenuItem({label:e.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(a,"addRow",b.rowIndex)}));
0<c.id&&(a.rowCtxMenu.addChild(new dijit.MenuItem({label:e.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(a,"deleteRow",b.rowIndex)})),"tree"==a.type&&"rate-value"==d.field&&(f=x.parse(c["rate-final_value"]),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e.deleteRate,iconClass:"icon-16-container icon-16-delete",disabled:isNaN(f)||0==f||null==f?!0:!1,onClick:dojo.hitch(a,"deleteRate",b.rowIndex)}))))},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();
this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="copy"},copyCell:function(b,a){this.selectedItem=this.selection.getFirstSelected();this.copyCellType=b;this.pasteOp=null},pasteItem:function(b){var a=this,c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),d=a.store,f=a.selection.getFirstSelected(),g=f.id==buildspace.constants.GRID_LAST_ROW&&0<b?a.getItem(b-1).id:0;c.show();dojo.xhrPost({url:this.pasteUrl,content:{type:a.pasteOp,
target_id:f.id,prev_item_id:g,id:a.selectedItem.id,_csrf_token:a.selectedItem._csrf_token},handleAs:"json",load:function(f){var g=[];if(f.success){var e=f.c;switch(a.pasteOp){case "cut":d.fetchItemByIdentity({identity:f.data.id,onItem:function(c){c=a.getItemIndex(c);g.push(c);for(var f=0,h=e.length;f<h;++f)d.fetchItemByIdentity({identity:e[f].id,onItem:function(b){b=a.getItemIndex(b);g.push(b)}});0<g.length&&a.rearranger.moveRows(g,b);a.selectAfterPaste(c>b?b:b-1,!0)}});d.fetchItemByIdentity({identity:f.data.id,
onItem:function(a){for(var b in f.data)a.hasOwnProperty(b)&&b!=d._getIdentifierAttribute()&&d.setValue(a,b,f.data[b]);d.save();var c=0;for(a=e.length;c<a;++c)d.fetchItemByIdentity({identity:e[c].id,onItem:function(a){for(var b in e[c])a.hasOwnProperty(b)&&b!=d._getIdentifierAttribute()&&d.setValue(a,b,e[c][b]);d.save()}})}});break;case "copy":var h=d.newItem(f.data);d.save();h=a.getItemIndex(h);g.push(h);for(var h=0,u=e.length;h<u;++h){var p=d.newItem(e[h]);d.save();p=a.getItemIndex(p);g.push(p)}0<
g.length&&(a.rearranger.moveRows(g,b),a.selectAfterPaste(b,!1))}}a.disableToolbarButtons(!1);a.pasteOp=null;g.length=0;c.hide()},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;c.hide()}})},selectAfterPaste:function(b,a){this.selection.clear();this.selectedItem=null;this.selection.setSelected(b,!0);a&&this.scrollToRow(0<b-3?b-3:b)},pasteCell:function(b){var a=this,c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),d=a.store,
f=a.selection.getFirstSelected();f.id==buildspace.constants.GRID_LAST_ROW&&0<b&&a.getItem(b-1);c.show();"rate"!=a.copyCellType&&cell.field.split("-");dojo.xhrPost({url:this.pasteUrl,content:{type:a.copyCellType,target_id:f.id,id:a.selectedItem.id,_csrf_token:a.selectedItem._csrf_token},handleAs:"json",load:function(b){if(b.success){var f=b.c;d.fetchItemByIdentity({identity:b.data.id,onItem:function(a){for(var c in b.data)a.hasOwnProperty(c)&&c!=d._getIdentifierAttribute()&&d.setValue(a,c,b.data[c]);
d.save();var e=0;for(a=f.length;e<a;++e)d.fetchItemByIdentity({identity:f[e].id,onItem:function(a){for(var b in f[e])a.hasOwnProperty(b)&&b!=d._getIdentifierAttribute()&&d.setValue(a,b,f[e][b]);d.save()}})}})}a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.copyCellType=null;a.pasteOp=null;c.hide()},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.copyCellType=null;a.pasteOp=null;c.hide()}})},addRow:function(b){l.curNode.blur();l.curNode=
null;var a,c=this,d=buildspace.dialog.indeterminateProgressBar({title:e.addingRow+". "+e.pleaseWait+"..."}),f=this.store;a=this.getItem(b);if(0<a.id)a={before_id:a.id,_csrf_token:a._csrf_token};else{var g=0<b?c.getItem(b-1).id:0;a={id:a.id,prev_item_id:g,relation_id:a.relation_id,_csrf_token:a._csrf_token}}d.show();dojo.xhrPost({url:this.addUrl,content:a,handleAs:"json",load:function(a){a.success&&dojo.forEach(a.items,function(a){0<a.id&&(a=f.newItem(a),f.save(),a=c.getItemIndex(a),c.rearranger.moveRows([a],
b),c.selection.clear())});window.setTimeout(function(){c.selection.setSelected(b,!0);c.focus.setFocusIndex(b,1)},30);d.hide()},error:function(a){c.selection.clear();c.disableToolbarButtons(!0);d.hide()}})},deleteRow:function(b){var a=this,c=null,d=null,f=a.getItem(b),g=buildspace.dialog.indeterminateProgressBar({title:e.deleting+". "+e.pleaseWait+"..."});l.curNode.blur();l.curNode=null;g.show();var h={url:this.deleteUrl,content:{id:f.id,_csrf_token:f._csrf_token},handleAs:"json",load:function(c){if(c.success){var d=
c.items,e=a.store;if(void 0!=c.affected_nodes){c=c.affected_nodes;for(var h=0,k=c.length;h<k;++h)dojo.forEach(c[h],function(a){e.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var c in a)f.hasOwnProperty(c)&&c!=e._getIdentifierAttribute()&&e.setValue(b,c,a[c])}})})}h=0;for(k=d.length;h<k;++h)e.fetchItemByIdentity({identity:d[h].id,onItem:function(a){e.deleteItem(a);e.save()}});d.length=0}g.hide();a.selection.clear();window.setTimeout(function(){a.focus.setFocusIndex(b,0)},10);a.disableToolbarButtons(!0);
a.selectedItem=null;a.pasteOp=null},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;g.hide()}};"tree"!=this.type?(c=e.deleteElementDialogBoxTitle,d=e.deleteElementDialogBoxMsg):f.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||f.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N?(c=e.deleteHeadDialogBoxTitle,d=e.deleteHeadDialogBoxMsg):(c=e.deleteItemDialogBoxTitle,d=e.deleteItemDialogBoxMsg);new buildspace.dialog.confirm(c,
d,80,320,function(){dojo.xhrPost(h)},function(){g.hide()})},deleteRate:function(b){var a=this,c=a.getItem(b),d=buildspace.dialog.indeterminateProgressBar({title:e.deleting+". "+e.pleaseWait+"..."});l.curNode.blur();l.curNode=null;d.show();dojo.xhrPost({url:this.deleteRateUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(c){if(c.success){var f=a.store;dojo.forEach(c.items,function(a){f.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var c in a)b.hasOwnProperty(c)&&
c!=f._getIdentifierAttribute()&&(f.setValue(b,c,a[c]),f.save())}})})}d.hide();a.selection.clear();window.setTimeout(function(){a.focus.setFocusIndex(b,0)},10);a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;a.copyCellType=null},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;a.copyCellType=null;d.hide()}})},indentOutdent:function(b,a){var c=this,d=c.store;if(0<b){var f=c.getItem(b),g=buildspace.dialog.indeterminateProgressBar({title:e.recalculateRows+
". "+e.pleaseWait+"..."});g.show();0<f.id&&dojo.xhrPost({url:this[a+"Url"],content:{id:f.id,_csrf_token:f._csrf_token},handleAs:"json",load:function(a){if(a.success){var b=a.c,c;for(c in a.item)a.item.hasOwnProperty(c)&&c!=d._getIdentifierAttribute()&&d.setValue(f,c,a.item[c]);var e=0;for(a=b.length;e<a;++e)d.fetchItemByIdentity({identity:b[e].id,onItem:function(a){for(var c in b[e])a.hasOwnProperty(c)&&c!=d._getIdentifierAttribute()&&d.setValue(a,c,b[e][c])}});d.save()}g.hide()},error:function(a){c.selection.clear();
c.disableToolbarButtons(!0);g.hide()}})}},disableToolbarButtons:function(b,a){var c=dijit.byId(this.libraryId+"_"+this.elementId+"AddRow-button"),d=dijit.byId(this.libraryId+"_"+this.elementId+"DeleteRow-button"),f=dijit.byId(this.libraryId+"_"+this.elementId+"Indent-button"),e=dijit.byId(this.libraryId+"_"+this.elementId+"Outdent-button");c._setDisabledAttr(b);d._setDisabledAttr(b);f&&f._setDisabledAttr(b);e&&e._setDisabledAttr(b);if(b&&a instanceof Array){var h=this;dojo.forEach(a,function(a){dijit.byId(h.libraryId+
"_"+h.elementId+a+"Row-button")._setDisabledAttr(!1)})}},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,q.disconnect);delete this._connects}});return w("buildspace.apps.BQLibrary.grid",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;border:0px;width:100%;height:100%;",gutters:!1,stackContainerTitle:null,libraryId:0,elementId:0,rowSelector:null,gridOpts:{},type:null,postCreate:function(){var b=this,a;this.inherited(arguments);v.mixin(b.gridOpts,{libraryId:b.libraryId,
elementId:b.elementId,type:b.type,region:"center",borderContainerWidget:b});var c=this.grid=new L(b.gridOpts),d=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});d.addChild(new dijit.form.Button({id:b.libraryId+"_"+b.elementId+"AddRow-button",label:e.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<c.selection.selectedIndex?!1:!0,onClick:function(){-1<c.selection.selectedIndex&&c.addRow(c.selection.selectedIndex)}}));"tree"==b.type&&(d.addChild(new dijit.ToolbarSeparator),
d.addChild(new dijit.form.Button({id:b.libraryId+"_"+b.elementId+"Indent-button",label:e.indent,iconClass:"icon-16-container icon-16-indent",disabled:-1<c.selection.selectedIndex?!1:!0,onClick:function(){-1<c.selection.selectedIndex&&c.indentOutdent(c.selection.selectedIndex,"indent")}})),d.addChild(new dijit.ToolbarSeparator),d.addChild(new dijit.form.Button({id:b.libraryId+"_"+b.elementId+"Outdent-button",label:e.outdent,iconClass:"icon-16-container icon-16-outdent",disabled:-1<c.selection.selectedIndex?
!1:!0,onClick:function(){-1<c.selection.selectedIndex&&c.indentOutdent(c.selection.selectedIndex,"outdent")}})),a=[{description:e.description},{uom_symbol:e.unit},{"rate-final_value":e.rate}]);d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({id:b.libraryId+"_"+b.elementId+"DeleteRow-button",label:e.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<c.selection.selectedIndex?!1:!0,onClick:function(){-1<c.selection.selectedIndex&&c.deleteRow(c.selection.selectedIndex)}}));
if("tree"!=b.type){a=new z({style:"display: none;"});var f=new z({style:"display: none;"});a.addChild(new m({label:e.importFromBill,onClick:function(a){(new t({libraryId:b.libraryId,importType:buildspace.constants.FILE_IMPORT_TYPE_BUILDSPACE,uploadUrl:"bqLibrary/importBuildspaceExcel",title:e.importFromBill,libraryGrid:c})).show()}}));a.addChild(new m({label:e.importFromBuildspaceZipFile,onClick:function(a){(new I({libraryId:b.libraryId,title:e.importFromBuildspaceZipFile,libraryGrid:c})).show()}}));
a.addChild(new m({label:e.importFromBuildsoft,onClick:function(a){(new t({libraryId:b.libraryId,importType:buildspace.constants.FILE_IMPORT_TYPE_BUILDSOFT,uploadUrl:"bqLibrary/importBuildsoftExcel",title:e.importFromBuildsoft,libraryGrid:c})).show()}}));a.addChild(new m({label:e.importFromExcel,onClick:function(a){(new t({libraryId:b.libraryId,importType:buildspace.constants.FILE_IMPORT_TYPE_EXCEL,uploadUrl:"bqLibrary/previewImportedFile",title:e.importFromExcel,libraryGrid:c})).show()}}));a.addChild(new m({label:e.importFromPricelist,
onClick:function(a){(new t({libraryId:b.libraryId,importType:buildspace.constants.FILE_IMPORT_TYPE_PRICELIST,uploadUrl:"bqLibrary/importPricelist",title:e.importFromPricelist,libraryGrid:c})).show()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new y({label:e.importFromFiles,iconClass:"icon-16-container icon-16-import",dropDown:a}));f.addChild(new m({label:e.exportToBuildspaceZip,onClick:function(a){(new J({bqLibraryId:b.libraryId})).show()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new y({label:e.exportTo,
iconClass:"icon-16-container icon-16-export",dropDown:f}));a=[{description:e.description}]}b.addChild(new K({region:"top",grid:c,filterFields:a,editableGrid:!0}));b.addChild(d);b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:c,region:"center"}));if(d=dijit.byId("bqLibrary_"+b.libraryId+"-stackContainer"))a=document.createElement("div"),a=new dojox.layout.ContentPane({title:buildspace.truncateString(b.stackContainerTitle,60),id:b.pageId,executeScripts:!0},a),d.addChild(a),a.set("content",
b),v.mixin(a,{grid:c}),d.selectChild(b.pageId)}})});
