(function(){define("buildspace/apps/StockIn/InvoiceDeliveryOrderTab/DeliveryOrderListingGrid","dojo/_base/declare dojo/_base/lang dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/request dijit/focus dijit/Toolbar dijit/form/Button dijit/DropDownMenu dijit/form/DropDownButton dijit/MenuItem dijit/layout/BorderContainer buildspace/widget/grid/cells/Formatter buildspace/widget/grid/cells/FormulaTextBox buildspace/widget/grid/Filter ./DeliveryOrderFormDialog ./StockInItemRemarkDialog ./DeliveryOrderItemListGrid ./DeliveryOrderImportFileFormDialog dojo/i18n!../../../nls/StockIn".split(" "),
function(k,A,B,t,u,l,m,v,n,C,D,E,p,q,F,r,w,G,x,y,c){var z=k("buildspace.apps.StockIn.InvoiceInformation.DeliveryOrderListingGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",keepSelection:!0,rowSelector:"0px",region:"center",deliveryOrderContainer:null,invoice:null,constructor:function(){this.rearranger=t(this,{});return this.formulatedColumn=u(this,{})},canSort:function(){return!1},postCreate:function(){this.inherited(arguments);return this.on("RowClick",function(a){return(a=this.getItem(a.rowIndex))&&
0<a.id[0]?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0)})},deleteRow:function(a){var b,e,d,f;d=this;b=this.getItem(a);e=buildspace.dialog.indeterminateProgressBar({title:c.deleting+". "+c.pleaseWait+"..."});m.curNode.blur();m.curNode=null;e.show();f={url:"stockIn/deleteDeliveryOrder",content:{deliveryOrderId:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(b){if(b.success)return d.refreshGrid(),e.hide(),d.selection.clear(),window.setTimeout(function(){return d.focus.setFocusIndex(a,
0)},10)},error:function(a){d.selection.clear();return e.hide()}};return new buildspace.dialog.confirm(c.deleteItemDialogBoxTitle,c.deleteItemDialogBoxMsg,80,320,function(){return dojo.xhrPost(f)},function(){return e.hide()})},disableToolbarButtons:function(a){var b=dijit.byId("deleteDeliveryOrderFromStockInInvoice-"+this.invoice.id[0]);b&&b.set("disabled",a)},createUploadAttachmentForm:function(a){return(new y({deliveryOrderId:a.id[0],_csrf_token:a._csrf_token[0],deliveryOrderListGrid:this})).show()},
deleteUploadedAttachment:function(a,b){var e,d;null==b&&(b=this);e=a.remove_file_url[0];if(null===e)return!1;d=new buildspace.dialog.indeterminateProgressBar({title:c.processing+"..."});d.show();return l.post(e,{handleAs:"json",data:{_csrf_token:a._csrf_token[0]}}).then(function(a){d.hide();if(a.success)return b.refreshGrid()},function(a){return d.hide()})},refreshGrid:function(){this.store.save();this.store.close();return this.setStore(this.store)}});return k("buildspace.apps.StockIn.InvoiceInformation.DeliveryOrderContainer",
p,{invoice:null,style:"height:100%;width:100%;padding:0;margin:0;",gutters:!1,postCreate:function(){var a,b,e,d,f,g,h;this.inherited(arguments);d=this;g="stockInInvoiceDeliveryOrderList-"+this.invoice.id[0];(f=dijit.byId(g+"-stackContainer"))&&dijit.byId(g+"-stackContainer").destroyRecursive();f=d.stackContainer=new dijit.layout.StackContainer({style:"width:100%;height:100%;",region:"center",id:g+"-stackContainer"});a=new dojo.data.ItemFileWriteStore({url:"stockIn/getDeliveryOrderListings/invoiceId/"+
this.invoice.id[0],clearOnClose:!0,urlPreventCache:!0});b=new z({structure:d.getDeliveryOrderGridLayout(),store:a,invoice:this.invoice,invoiceId:this.invoice.id[0],escapeHTMLInData:!1,deliveryOrderContainer:d,onClick:function(a){var b;d=this;b=this.getItem(a.rowIndex);a=a.cell.field;if(0>b.id[0])return!1;"upload_file"===a?d.createUploadAttachmentForm(b):"remove_file"===a&&d.deleteUploadedAttachment(b);return!0},onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id[0]&&this.deliveryOrderContainer.createDeliveryOrderItemQuantityView(a)}});
h=new v({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border:none;"});h.addChild(new n({label:c.addNewDeliveryOrder,iconClass:"icon-16-container icon-16-add",onClick:function(){var a;a=new buildspace.dialog.indeterminateProgressBar({title:c.processing+"..."});a.show();return l.get("stockIn/getDeliveryOrderFormInformation",{query:{invoiceId:d.invoice.id[0]},handleAs:"json"}).then(function(c){(new w({invoice:d.invoice,deliveryOrderGrid:b,formInfo:c.formInformation})).show();
return a.hide()},function(b){return a.hide()})}}));h.addChild(new dijit.ToolbarSeparator);h.addChild(new n({label:c["delete"],id:"deleteDeliveryOrderFromStockInInvoice-"+d.invoice.id[0],iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:function(){return b.deleteRow(b.selection.selectedIndex)}}));a=new r({region:"top",grid:b,editableGrid:!1,filterFields:[{delivery_order_no:c.doNo}]});e=new p({region:"top",gutters:!1});e.addChild(a);e.addChild(h);e.addChild(b);a=new dijit.layout.ContentPane({title:c.deliveryOrder,
content:e});f.addChild(a);a=new dijit.layout.StackController({region:"top",containerId:g+"-stackContainer"});a=new dijit.layout.ContentPane({style:"padding: 0px; overflow: hidden;",baseClass:"breadCrumbTrail",region:"top",content:a});this.addChild(f);this.addChild(a);return dojo.subscribe(g+"-stackContainer-selectChild","",function(a){var b,c,d;if(c=dijit.byId(g+"-stackContainer")){b=c.getChildren();a=dojo.indexOf(b,dijit.byId(a.id))+1;for(d=[];b.length>a;)c.removeChild(b[a]),b[a].destroyRecursive(),
d.push(a+=1);return d}})},createDeliveryOrderItemQuantityView:function(a){var b,e;b=new dojo.data.ItemFileWriteStore({url:"stockIn/getDeliveryOrderItemQuantities/deliveryOrderId/"+a.id,clearOnClose:!0,urlPreventCache:!0});e=new x({invoice:this.invoice,invoiceId:this.invoice.id[0],deliveryOrder:a,store:b,structure:this.getDeliveryOrderItemQuantityViewGridLayout()});b=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",gutters:!1,region:"center"});b.addChild(new r({region:"top",
grid:e,editableGrid:!1,filterFields:[{description:c.description},{uom:c.unit},{invoiceQuantity:c.invoiceQuantity},{doQuantity:c.doQuantity},{remarks:c.remarks}]}));b.addChild(e);return this.makePane(a.delivery_order_no[0],b)},getDeliveryOrderGridLayout:function(){var a=new q;return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter,noresize:!0},{name:c.deliveryOrderNo,field:"delivery_order_no",width:"auto",formatter:a.treeCellFormatter,noresize:!0},{name:c.uploadFile,
field:"upload_file",width:"100px",styles:"text-align: center;",noresize:!0},{name:c.downloadFile,field:"download_file",width:"100px",styles:"text-align: center;",noresize:!0},{name:c.removeFile,field:"remove_file",styles:"text-align: center;",width:"100px",noresize:!0},{name:c.date_of_delivery_order,field:"delivery_order_date",width:"160px",styles:"text-align: center;",filterable:!1,noresize:!0}]},getDeliveryOrderItemQuantityViewGridLayout:function(){var a=new q;return[{name:"No",field:"id",width:"30px",
styles:"text-align: center;",formatter:a.rowCountCellFormatter},{name:c.description,field:"description",width:"auto",formatter:a.treeCellFormatter},{name:c.remarks,field:"remarks",width:"280px",formatter:a.rfqSupplierRemarkCellFormatter},{name:c.unit,field:"uom",width:"70px",styles:"text-align: center;",formatter:a.rfqUnitCellFormatter},{name:c.invoiceQuantity,field:"invoiceQuantity",width:"90px",styles:"text-align: right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.rfqQuantityCellFormatter},
{name:c.doQuantity,field:"doQuantity",width:"90px",styles:"text-align: right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",editable:!0,formatter:a.rfqQuantityCellFormatter}]},makePane:function(a,b){var c,d;d=dijit.byId("stockInInvoiceDeliveryOrderList-"+this.invoice.id[0]+"-stackContainer");c=new dijit.layout.ContentPane({title:a,content:b});d.addChild(c);return d.selectChild(c)}})})}).call(this);
