(function(){define("buildspace/apps/StockIn/InvoiceDeliveryOrderTab/StockInItemRemarkDialog","dojo/_base/declare dojo/_base/lang dojo/on dojo/keys dojo/parser dojo/_base/connect dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/Toolbar dijit/form/Button dijit/layout/BorderContainer dijit/layout/ContentPane dijit/form/ValidationTextBox dijit/form/SimpleTextarea dijit/registry dojo/dom-style dojo/dom-form dojo/request dojox/validate/web dojo/store/Memory dojox/form/Manager dojo/text!./templates/rfqItemRemarkForm.html buildspace/widget/grid/cells/Formatter dojo/i18n!../../../nls/StockIn buildspace/widget/grid/Filter".split(" "),
function(h,k,u,v,E,w,x,y,z,A,n,F,m,G,H,I,J,l,K,p,L,M,N,B,C,f,D){var q,r,t;t=h("buildspace.apps.PurchaseOrder.ItemList.POItemRemarkGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",keepSelection:!0,rowSelector:"0px",newStockInItemRemarkId:-1,rfqItemRemarkId:-1,stockInItemId:-1,poItem:null,resourceItemId:-1,stockInItemGridStore:null,dialogContainer:null,_csrf_token:null,postCreate:function(){var a;this.inherited(arguments);a=this;this.on("RowClick",function(a){return(a=this.getItem(a.rowIndex))&&
0<a.id[0]?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0)});return this._connects.push(w.connect(this,"onCellClick",function(c){var b;b=this.getItem(c.rowIndex);return"action"!==c.cell.field?!1:a.updatePOItemDescription(b)}))},canSort:function(a){return!1},updatePOItemDescription:function(a){var c,b;b=this;a={"rfq_item_remark[resource_item_id]":b.resourceItemId,"rfq_item_remark[description]":a.description,"rfq_item_remark[_csrf_token]":b._csrf_token};0<b.newStockInItemRemarkId?k.mixin(a,
{stockInItemRemarkId:b.newStockInItemRemarkId,stockInItemId:b.stockInItemId}):k.mixin(a,{stockInItemRemarkId:b.rfqItemRemarkId,stockInItemId:b.stockInItemId});c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});c.show();return p.post("stockIn/updateSelectedPreviousRFQItemRemark",{data:a,handleAs:"json"}).then(function(a){var d,e,f;c.hide();if(a.success&&0<a.id){b.newStockInItemRemarkId=a.id;b.refreshGrid();a=a.data;for(d in a)b.poItem.hasOwnProperty(d)&&d!==b.stockInItemGridStore._getIdentifierAttribute()&&
b.stockInItemGridStore.setValue(b.poItem,d,a[d]);return b.dialogContainer.hide()}f=[];for(e in a.errorMsgs)d=b["error-"+e],d.innerHTML=a.errorMsgs[e],f.push(l.set(d,"display","block"));return f},function(a){return c.hide()})},deleteRow:function(a){var c,b,e;b=this;a=this.getItem(a);c=buildspace.dialog.indeterminateProgressBar({title:f.deleting+". "+f.pleaseWait+"..."});c.show();e={url:"requestForQuotation/deleteRFQItemRemark",content:{rfqItemRemarkId:a.id,_csrf_token:a._csrf_token},handleAs:"json",
load:function(a){c.hide();return a.success?b.refreshGrid():console.log(a)},error:function(a){return c.hide()}};return new buildspace.dialog.confirm(f.deleteRFQItemRemarkTitle,f.deleteRFQItemRemarkMsg,80,320,function(){return dojo.xhrPost(e)},function(){return c.hide()})},refreshGrid:function(){this.store.save();this.store.close();return this.setStore(this.store)},disableToolbarButtons:function(a){var c=dijit.byId("deleteRemarkFromRequestForQuotationItem");c&&c.set("disabled",a)}});q=h("buildspace.apps.PurchaseOrder.ItemList.POItemRemarkForm",
[x,y,z,A],{baseClass:"buildspace-form",style:"overflow: auto;",item:null,stockInItemId:-1,resourceItemId:-1,rfqItemRemarkId:-1,newStockInItemRemarkId:-1,templateString:B,region:"center",style:"overflow: auto;",formInfo:null,nls:f,dialogContainer:null,stockInItemGridStore:null,_csrf_token:null,postCreate:function(){var a;this.inherited(arguments);a=this;return u(this.stockInItemRemarkFormSaveButton,"click",function(c){return a.save()})},startup:function(){this.inherited(arguments);return this.stockInItemRemarkForm.setFormValues(this.formInfo)},
clearInputErrorMsgs:function(){var a,c,b,e;b={description:null};e=[];for(c in b)a=this["error-"+c],a.innerHTML=b[c],e.push(l.set(a,"display","none"));return e},save:function(){var a,c,b;b=this;this.clearInputErrorMsgs();if(!this.stockInItemRemarkForm.validate())return!1;a=dojo.formToObject(this.stockInItemRemarkForm.id);c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});0<b.newStockInItemRemarkId?k.mixin(a,{rfqItemRemarkId:b.newStockInItemRemarkId,stockInItemId:b.stockInItemId,
resourceItemId:b.resourceItemId}):k.mixin(a,{rfqItemRemarkId:b.rfqItemRemarkId,stockInItemId:b.stockInItemId,resourceItemId:b.resourceItemId});c.show();return p.post("stockIn/updateRFQItemRemark",{data:a,handleAs:"json"}).then(function(a){var d,e,f;c.hide();if(a.success&&0<a.id)return b.newStockInItemRemarkId=a.id,b.stockInItemRemarkForm.reset(),b.grid.refreshGrid();f=[];for(e in a.errorMsgs)d=b["error-"+e],d.innerHTML=a.errorMsgs[e],f.push(l.set(d,"display","block"));return f},function(a){return c.hide()})}});
r=h("buildspace.apps.PurchaseOrder.ItemList.POItemRemarkFormContainer",m,{gutters:!1,style:"padding:0px;margin:0px;width:750px;height:400px;overflow:hidden;",item:null,dialogContainer:null,formInfo:null,stockInItemGridStore:null,_csrf_token:null,postCreate:function(){var a,c,b,e,d,g;this.inherited(arguments);d=this;c=d.item.stockInItemId[0];a=d.item.id[0];e=d.item.stockInItemRemarkId;g=new dojo.data.ItemFileWriteStore({url:"stockIn/getPreviousRFQItemRemarks/stockInItemId/"+c+"/resourceItemId/"+a,
clearOnClose:!0,urlPreventCache:!0});b=new t({stockInItemId:c,rfqItemRemarkId:e,structure:d.getRemarksGridLayout(),store:g,poItem:d.item,resourceItemId:a,stockInItemGridStore:d.stockInItemGridStore,dialogContainer:d.dialogContainer,_csrf_token:d._csrf_token,region:"center"});c=new q({item:d.item,stockInItemId:c,resourceItemId:a,rfqItemRemarkId:e,dialogContainer:d.dialogContainer,formInfo:d.formInfo,stockInItemGridStore:d.stockInItemGridStore,_csrf_token:d._csrf_token,grid:b});a=new n({region:"top",
style:"outline:none!important;padding:2px;overflow:hidden;"});a.addChild(new dijit.form.Button({label:f.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return d.dialogContainer.hide()}}));e=new n({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border-bottom:none;"});e.addChild(new dijit.form.Button({label:f["delete"],id:"deleteRemarkFromRequestForQuotationItem",iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:function(){return b.deleteRow(b.selection.selectedIndex)}}));
g=new m({gutters:!1,style:"width:100%;height:200px;margin:0;padding:0;overflow:hidden;",region:"top"});g.addChild(a);g.addChild(c);this.addChild(g);a=new m({gutters:!1,style:"width:100%;height:200px;margin:0;padding:0;overflow:hidden;",region:"center"});a.addChild(new D({region:"top",grid:b,editableGrid:!1,filterFields:[{description:f.description}]}));a.addChild(e);a.addChild(b);this.addChild(a)},getRemarksGridLayout:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",
formatter:(new C).rowCountCellFormatter},{name:f.description,field:"description",width:"auto"},{name:f.action,field:"action",width:"120px",styles:"text-align: center;",formatter:function(a,c){var b,e;b=this.grid.getItem(c);e=b.id;0<e?(b=b.selected[0]?f.selected:f.select,e='<a href="javascript:void(0);">'+b+"</a>"):e="&nbsp;";return e}}]}});return h("buildspace.apps.PurchaseOrder.ItemList.PurchaseOrderItemRemarkDialog",dijit.Dialog,{style:"padding:0px;margin:0px;width:750px;height:420px;",item:null,
data:null,stockInItemGridStore:null,buildRendering:function(){var a=this.createContent();this.content=a;a.startup();return this.inherited(arguments)},postCreate:function(){l.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},createContent:function(){return new r({item:this.item,dialogContainer:this,formInfo:this.data.rfqItemRemarkForm,_csrf_token:this.data.rfqItemRemarkForm._csrf_token,stockInItemGridStore:this.stockInItemGridStore})},
_onKey:function(a){if(a.keyCode===v.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()}})})}).call(this);
