Date.$VERSION=1.02;Date.LZ=function(a){return(0>a||9<a?"":"0")+a};Date.monthNames="January February March April May June July August September October November December".split(" ");Date.monthAbbreviations="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");Date.dayNames="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");Date.dayAbbreviations="Sun Mon Tue Wed Thu Fri Sat".split(" ");Date.preferAmericanFormat=!0;Date.firstDayOfWeek=0;Date.defaultFormat="dd/MM/yyyy";
Date.prototype.getFullYear||(Date.prototype.getFullYear=function(){var a=this.getYear();return 1900>a?a+1900:a});
Date.parseString=function(a,e){if("undefined"==typeof e||null==e||""==e){for(var f=["M/d/y","M-d-y","M.d.y","M/d","M-d"],h=["d/M/y","d-M-y","d.M.y","d/M","d-M"],h=[[Date.defaultFormat,"y-M-d","MMM d, y","MMM d,y","y-MMM-d","d-MMM-y","MMM d","MMM-d","d-MMM"],Date.preferAmericanFormat?f:h,Date.preferAmericanFormat?h:f],f=0;f<h.length;f++)for(var l=h[f],d=0;d<l.length;d++){var n=Date.parseString(a,l[d]);if(null!=n)return n}return null}this.isInteger=function(a){for(var b=0;b<a.length;b++)if(-1=="1234567890".indexOf(a.charAt(b)))return!1;
return!0};this.getInt=function(a,b,c,d){for(;d>=c;d--){var u=a.substring(b,b+d);if(u.length<c)break;if(this.isInteger(u))return u}return null};this.decodeShortcut=function(a){var b=a.trim().toUpperCase();a=new Date;a.clearTime();if(0<=["NOW","N"].indexOf(b))a=new Date;else if(!(0<=["TODAY","T"].indexOf(b)))if(0<=["YESTERDAY","Y"].indexOf(b))a.setDate(a.getDate()-1);else if(0<=["TOMORROW","TO"].indexOf(b))a.setDate(a.getDate()+1);else if(0<="W TW WEEK THISWEEK WEEKSTART THISWEEKSTART".split(" ").indexOf(b))a.setFirstDayOfThisWeek();
else if(0<=["LW","LASTWEEK","LASTWEEKSTART"].indexOf(b))a.setFirstDayOfThisWeek(),a.setDate(a.getDate()-7);else if(0<=["NW","NEXTWEEK","NEXTWEEKSTART"].indexOf(b))a.setFirstDayOfThisWeek(),a.setDate(a.getDate()+7);else if(0<="M TM MONTH THISMONTH MONTHSTART THISMONTHSTART".split(" ").indexOf(b))a.setDate(1);else if(0<=["LM","LASTMONTH","LASTMONTHSTART"].indexOf(b))a.setDate(1),a.setMonth(a.getMonth()-1);else if(0<=["NM","NEXTMONTH","NEXTMONTHSTART"].indexOf(b))a.setDate(1),a.setMonth(a.getMonth()+
1);else if(0<="Q TQ QUARTER THISQUARTER QUARTERSTART THISQUARTERSTART".split(" ").indexOf(b))a.setDate(1),a.setMonth(3*Math.floor(a.getMonth()/3));else if(0<=["LQ","LASTQUARTER","LASTQUARTERSTART"].indexOf(b))a.setDate(1),a.setMonth(3*Math.floor(a.getMonth()/3)-3);else if(0<=["NQ","NEXTQUARTER","NEXTQUARTERSTART"].indexOf(b))a.setDate(1),a.setMonth(3*Math.floor(a.getMonth()/3)+3);else if(/^-?[0-9]+[DWMY]$/.test(b)){var c=b.substr(b.length-1),b=parseInt(b.substr(0,b.length-1));"W"==c?a.setDate(a.getDate()+
7*b):"M"==c?a.setMonth(a.getMonth()+b):"Y"==c&&a.setYear(a.getYear()+b)}else a=void 0;return a};if(f=this.decodeShortcut(a))return f;a+="";e+="";for(var n=d=0,b=f="",m=(new Date).getFullYear(),k=1,c=1,g=0,q=0,r=0,t="";n<e.length;){f=e.charAt(n);for(b="";e.charAt(n)==f&&n<e.length;)b+=e.charAt(n++);if("yyyy"==b||"yy"==b||"y"==b){"yyyy"==b&&(l=h=4);"yy"==b&&(l=h=2);"y"==b&&(h=2,l=4);m=this.getInt(a,d,h,l);if(null==m)return null;d+=m.length;2==m.length&&(m=70<m?1900+(m-0):2E3+(m-0))}else if("MMM"==b||
"MMMM"==b){k=0;b="MMMM"==b?Date.monthNames.concat(Date.monthAbbreviations):Date.monthAbbreviations;for(f=0;f<b.length;f++){var p=b[f];if(a.substring(d,d+p.length).toLowerCase()==p.toLowerCase()){k=f%12+1;d+=p.length;break}}if(1>k||12<k)return null}else if("E"==b||"EE"==b||"EEE"==b||"EEEE"==b)for(b="EEEE"==b?Date.dayNames:Date.dayAbbreviations,f=0;f<b.length;f++){if(p=b[f],a.substring(d,d+p.length).toLowerCase()==p.toLowerCase()){d+=p.length;break}}else if("MM"==b||"M"==b){k=this.getInt(a,d,b.length,
2);if(null==k||1>k||12<k)return null;d+=k.length}else if("dd"==b||"d"==b){c=this.getInt(a,d,b.length,2);if(null==c||1>c||31<c)return null;d+=c.length}else if("hh"==b||"h"==b){g=this.getInt(a,d,b.length,2);if(null==g||1>g||12<g)return null;d+=g.length}else if("HH"==b||"H"==b){g=this.getInt(a,d,b.length,2);if(null==g||0>g||23<g)return null;d+=g.length}else if("KK"==b||"K"==b){g=this.getInt(a,d,b.length,2);if(null==g||0>g||11<g)return null;d+=g.length;g++}else if("kk"==b||"k"==b){g=this.getInt(a,d,b.length,
2);if(null==g||1>g||24<g)return null;d+=g.length;g--}else if("mm"==b||"m"==b){q=this.getInt(a,d,b.length,2);if(null==q||0>q||59<q)return null;d+=q.length}else if("ss"==b||"s"==b){r=this.getInt(a,d,b.length,2);if(null==r||0>r||59<r)return null;d+=r.length}else if("a"==b){if("am"==a.substring(d,d+2).toLowerCase())t="AM";else if("pm"==a.substring(d,d+2).toLowerCase())t="PM";else return null;d+=2}else{if(a.substring(d,d+b.length)!=b)return null;d+=b.length}}if(d!=a.length)return null;if(2==k)if(0==m%
4&&0!=m%100||0==m%400){if(29<c)return null}else if(28<c)return null;if((4==k||6==k||9==k||11==k)&&30<c)return null;12>g&&"PM"==t?g=g-0+12:11<g&&"AM"==t&&(g-=12);return new Date(m,k-1,c,g,q,r)};Date.isValid=function(a,e){return null!=Date.parseString(a,e)};Date.prototype.isBefore=function(a){return null==a?!1:this.getTime()<a.getTime()};Date.prototype.isAfter=function(a){return null==a?!1:this.getTime()>a.getTime()};Date.prototype.equals=function(a){return null==a?!1:this.getTime()==a.getTime()};
Date.prototype.equalsIgnoreTime=function(a){if(null==a)return!1;var e=(new Date(this.getTime())).clearTime();a=(new Date(a.getTime())).clearTime();return e.getTime()==a.getTime()};
Date.prototype.format=function(a){a||(a=Date.defaultFormat);a+="";var e="",f=0,h,l;h=this.getFullYear()+"";l=this.getMonth()+1;var d=this.getDate(),n=this.getDay(),b=this.getHours(),m=this.getMinutes(),k=this.getSeconds(),c={};4>h.length&&(h=""+(+h+1900));c.y=""+h;c.yyyy=h;c.yy=h.substring(2,4);c.M=l;c.MM=Date.LZ(l);c.MMM=Date.monthAbbreviations[l-1];c.MMMM=Date.monthNames[l-1];c.d=d;c.dd=Date.LZ(d);c.E=Date.dayAbbreviations[n];c.EE=Date.dayAbbreviations[n];c.EEE=Date.dayAbbreviations[n];c.EEEE=Date.dayNames[n];
c.H=b;c.HH=Date.LZ(b);c.h=0==b?12:12<b?b-12:b;c.hh=Date.LZ(c.h);c.K=c.h-1;c.k=c.H+1;c.KK=Date.LZ(c.K);c.kk=Date.LZ(c.k);c.a=11<b?"PM":"AM";c.m=m;c.mm=Date.LZ(m);c.s=k;for(c.ss=Date.LZ(k);f<a.length;){h=a.charAt(f);for(l="";a.charAt(f)==h&&f<a.length;)l+=a.charAt(f++);e="undefined"!=typeof c[l]?e+c[l]:e+l}return e};Date.prototype.getDayName=function(){return Date.dayNames[this.getDay()]};Date.prototype.getDayAbbreviation=function(){return Date.dayAbbreviations[this.getDay()]};
Date.prototype.getMonthName=function(){return Date.monthNames[this.getMonth()]};Date.prototype.getMonthAbbreviation=function(){return Date.monthAbbreviations[this.getMonth()]};Date.prototype.clearTime=function(){this.setHours(0);this.setMinutes(0);this.setSeconds(0);this.setMilliseconds(0);return this};
Date.prototype.add=function(a,e){if("undefined"==typeof a||null==a||"undefined"==typeof e||null==e)return this;e=+e;if("y"==a)this.setFullYear(this.getFullYear()+e);else if("M"==a)this.setMonth(this.getMonth()+e);else if("d"==a)this.setDate(this.getDate()+e);else if("w"==a)for(var f=0<e?1:-1;0!=e;){for(this.add("d",f);0==this.getDay()||6==this.getDay();)this.add("d",f);e-=f}else"h"==a?this.setHours(this.getHours()+e):"m"==a?this.setMinutes(this.getMinutes()+e):"s"==a&&this.setSeconds(this.getSeconds()+
e);return this};Date.prototype.toInt=function(){return 1E4*this.getFullYear()+100*(this.getMonth()+1)+this.getDate()};Date.fromInt=function(a){var e=parseInt(a/1E4),f=parseInt((a-1E4*e)/100);a=parseInt(a-1E4*e-100*f);return new Date(e,f-1,a,12,0,0)};Date.prototype.isToday=function(){return this.toInt()==(new Date).toInt()};Date.prototype.setFirstDayOfThisWeek=function(a){a||(a=Date.firstDayOfWeek);this.setDate(this.getDate()-this.getDay()+a-(0==this.getDay()&&0!=a?7:0))};
