function GridEditor(a){this.master=a;this.gridified=$.gridify($.JST.createFromTemplate({},"TASKSEDITHEAD"));this.element=this.gridified.find(".gdfTable").eq(1)}
GridEditor.prototype.fillEmptyLines=function(){for(var a=new TaskFactory,b=30-this.element.find(".taskEditRow").size(),d=0;d<b;d++){var c=$.JST.createFromTemplate({},"TASKEMPTYROW"),e=this.master;c.click(function(c){c=$(this);if(e.canWrite&&!(0<c.prevAll(".emptyRow").size())){e.beginTransaction();var b,d=(new Date).getTime(),h=0;e.tasks[0]&&(d=e.tasks[0].start,h=e.tasks[0].level+1);c.prevAll(".emptyRow").andSelf().each(function(){var c=e.computeStart(d),f=e.computeEndByDuration(c,1),c=a.build("tmp_fk"+
(new Date).getTime(),"","",h,c,f,1);e.addTask(c);b=c});e.endTransaction();b.rowElement.click();b.rowElement.find("[name=name]").focus().blur(function(){var c=$(this);""==c.val()&&(b.name="Task "+(b.getRow()+1),c.val(b.name))})}});this.element.append(c)}};
GridEditor.prototype.addTask=function(a,b,d){this.element.find("[taskId="+a.id+"]").remove();var c=$.JST.createFromTemplate(a,"TASKROW");a.rowElement=c;this.bindRowEvents(a,c);"number"!=typeof b?(b=this.element.find(".emptyRow:first"),0<b.size()?b.replaceWith(c):this.element.append(c)):(b=this.element.find("tr.taskEditRow").eq(b),0<b.size()?b.before(c):this.element.append(c));d&&(a.collapsed&&c.find(".exp-controller").removeClass("exp"),0<=this.master.getCollapsedDescendant().indexOf(a)&&c.hide());
return c};GridEditor.prototype.refreshExpandStatus=function(a){if(a){var b=a.getChildren();0<b.length&&0==a.rowElement.has(".expcoll").length?a.rowElement.find(".exp-controller").addClass("expcoll exp"):0==b.length&&0<a.rowElement.has(".expcoll").length&&a.rowElement.find(".exp-controller").removeClass("expcoll exp");(a=a.getParent())&&0==a.rowElement.has(".expcoll").length&&a.rowElement.find(".exp-controller").addClass("expcoll exp")}};
GridEditor.prototype.refreshTaskRow=function(a){var b=a.rowElement;b.find(".taskRowIndex").html(a.getRow()+1);b.find(".indentCell").css("padding-left",10*a.level+18);b.find("[name=name]").val(a.name);b.find("[name=code]").val(a.code);b.find("[status]").attr("status",a.status);b.find("[status]").attr("title",a.status);b.find("[name=duration]").val(a.duration);b.find("[name=start]").val((new Date(a.start)).format()).updateOldValue();b.find("[name=end]").val((new Date(a.end)).format()).updateOldValue();
b.find("[name=depends]").val(a.depends)};GridEditor.prototype.redraw=function(){for(var a=0;a<this.master.tasks.length;a++)this.refreshTaskRow(this.master.tasks[a])};GridEditor.prototype.reset=function(){this.element.find("[taskid]").remove()};
GridEditor.prototype.bindRowEvents=function(a,b){var d=this;this.master.canWrite&&a.canWrite?d.bindRowInputEvents(a,b):b.find("input").attr("readonly",!0);d.bindRowExpandEvents(a,b);b.find(".edit").click(function(){$.isFunction(d.master.customTaskEditorCallBack)&&d.master.customTaskEditorCallBack.call(d,d.master,a,b)})};
GridEditor.prototype.bindRowExpandEvents=function(a,b){var d=this;b.find(".exp-controller").click(function(){var c=$(this),a=c.closest("[taskid]").attr("taskid"),b=d.master.getTask(a),a=b.getDescendant();c.toggleClass("exp");b.collapsed=!c.is(".exp");b=d.master.getCollapsedDescendant();if(c.is(".exp"))for(c=0;c<a.length;c++){var f=a[c];0<=b.indexOf(f)||f.rowElement.show()}else for(c=0;c<a.length;c++)a[c].rowElement.hide();d.master.gantt.refreshGantt()})};
GridEditor.prototype.bindRowInputEvents=function(a,b){var d=this;b.find(".date").each(function(){var c=$(this);a.depends&&"start"==c.attr("name")?c.attr("readonly","true"):c.removeAttr("readonly");c.click(function(){$(this).dateField({inputField:c})});c.blur(function(c){var a=$(this);if(a.isValueChanged())if(Date.isValid(a.val())){c=Date.parseString(a.val());var b=a.closest("tr").attr("taskId"),b=d.master.getTask(b),e=b.start,g=b.end;"start"==a.attr("name")?(e=c.getTime(),e>=g&&(new Date(e)).add("d",
b.duration).getTime(),d.master.beginTransaction(),d.master.moveTask(b,e)):(g=c.getTime(),e>=g&&(g=e),g+=72E6,d.master.beginTransaction(),d.master.changeTaskDates(b,e,g));d.master.endTransaction();a.updateOldValue()}else buildspace.dialog.alert("Date Error",GanttMaster.messages.INVALID_DATE_FORMAT,80,200).show(),a.val(a.getOldValue())})});b.find("input:not(.date)").focus(function(){$(this).updateOldValue()}).blur(function(){var c=$(this);if(c.isValueChanged()){var a=c.closest("tr"),b=a.attr("taskId"),
b=d.master.getTask(b),f=c.attr("name");d.master.beginTransaction();if("depends"==f){if(b.depends=c.val(),b.depends?a.find("[name=start]").attr("readonly","true"):a.find("[name=start]").removeAttr("readonly"),d.master.updateLinks(b)){c=b.getSuperiors();for(a=0;a<c.length&&c[a].from.synchronizeStatus();a++);d.master.changeTaskDates(b,b.start,b.end)}}else"duration"==f?(a=parseInt(c.val())||1,c.val(a),c=d.master.computeEndByDuration(b.start,a),d.master.changeTaskDates(b,b.start,c)):"name"==f&&""==c.val()?
b.deleteTask():b[f]=c.val();d.master.endTransaction()}});b.find("input").keydown(function(c){var a=$(this).parent(),b=a.parent(),d=a.prevAll("td").size();switch(c.keyCode){case 37:0==this.selectionEnd&&a.prev().find("input").focus();break;case 39:this.selectionEnd==this.value.length&&a.next().find("input").focus();break;case 38:d=b.prev().find("td").eq(d);d=d.find("input");0<d.size()&&d.focus();break;case 40:c=b.next(),d=c.find("td").eq(d),d=d.find("input"),0<d.size()?d.focus():c.click()}return!0}).focus(function(){$(this).closest("tr").click()});
b.click(function(){var a=$(this);a.closest("table").find(".rowSelected").removeClass("rowSelected");a.addClass("rowSelected");d.master.currentTask=d.master.getTask(a.attr("taskId"));d.master.gantt.synchHighlight();var b=a.position().top;b>d.element.parent().height()?a.offsetParent().scrollTop(b-d.element.parent().height()+100):40>b&&a.offsetParent().scrollTop(a.offsetParent().scrollTop()-40+b)})};
