function GanttMaster(){this.tasks=[];this.deletedTaskIds=[];this.links=[];this.editor;this.gantt;this.splitter;this.element;this.customTaskEditorCallBack;this.minEditableDate=0;this.maxEditableDate=Infinity;this.canWrite=this.canWriteOnParent=!0;this.firstDayOfWeek=Date.firstDayOfWeek;this.currentTask;this.resourceUrl="res/";this.__currentTransaction;this.timeoutId;this.changesFromLoadProject=!1;this.projectScheduleStartDate=new Date;this.__undoStack=[];this.__redoStack=[];this.__inUndoRedo=!1;this.calendarSettings=
{satIsHoly:!0,sunIsHoly:!0,holidays:""}}
GanttMaster.prototype.init=function(a){this.element=a;var b=this;$("#gantEditorTemplates").loadTemplates().remove();this.editor=new GridEditor(this);a.append(this.editor.gridified);this.gantt=new Ganttalendar("m",this.projectScheduleStartDate.getTime()-1728E5,this.projectScheduleStartDate.getTime()+1296E6,this,.6*a.width());b.splitter=$.splittify.init(a,this.editor.gridified,this.gantt.element,60);b.splitter.firstBoxMinWidth=30;a.bind("refreshTasks.gantt",function(){b.redrawTasks()}).bind("refreshTask.gantt",function(a,
d){b.drawTask(d)}).bind("deleteCurrentTask.gantt",function(a){b.deleteCurrentTask()}).bind("addAboveCurrentTask.gantt",function(){b.addAboveCurrentTask()}).bind("addBelowCurrentTask.gantt",function(){b.addBelowCurrentTask()}).bind("indentCurrentTask.gantt",function(){b.indentCurrentTask()}).bind("outdentCurrentTask.gantt",function(){b.outdentCurrentTask()}).bind("moveUpCurrentTask.gantt",function(){b.moveUpCurrentTask()}).bind("moveDownCurrentTask.gantt",function(){b.moveDownCurrentTask()}).bind("zoomPlus.gantt",
function(){b.gantt.zoomGantt(!0)}).bind("zoomMinus.gantt",function(){b.gantt.zoomGantt(!1)}).bind("undo.gantt",function(){b.canWrite&&b.undo()}).bind("redo.gantt",function(){b.canWrite&&b.redo()}).bind("resize.gantt",function(){b.resize()});$("body").bind("keydown.body",function(a){if("body"==a.target.nodeName.toLowerCase()||"svg"==a.target.nodeName.toLowerCase()){var c=!0;switch(a.keyCode){case 46:case 8:var e=b.gantt.element.find(".focused.focused");e.is(".taskBox")?b.deleteCurrentTask():e.is(".linkGroup")&&
b.removeLink(e.data("from"),e.data("to"));break;case 38:b.currentTask&&(b.currentTask.ganttElement.is(".focused")?(b.moveUpCurrentTask(),b.gantt.element.oneTime(100,function(){b.currentTask.ganttElement.addClass("focused")})):b.currentTask.rowElement.prev().click());break;case 40:b.currentTask&&(b.currentTask.ganttElement.is(".focused")?(b.moveDownCurrentTask(),b.gantt.element.oneTime(100,function(){b.currentTask.ganttElement.addClass("focused")})):b.currentTask.rowElement.next().click());break;case 39:b.currentTask&&
b.currentTask.ganttElement.is(".focused")&&(b.indentCurrentTask(),b.gantt.element.oneTime(100,function(){b.currentTask.ganttElement.addClass("focused")}));break;case 37:b.currentTask&&b.currentTask.ganttElement.is(".focused")&&(b.outdentCurrentTask(),b.gantt.element.oneTime(100,function(){b.currentTask.ganttElement.addClass("focused")}));break;case 89:a.ctrlKey&&b.redo();break;case 90:a.ctrlKey&&b.undo();break;default:c=!1}c&&(a.preventDefault(),a.stopPropagation())}});this.__undoStack=[]};
GanttMaster.messages={CANNOT_WRITE:"CANNOT_WRITE",CHANGE_OUT_OF_SCOPE:"NO_RIGHTS_FOR_UPDATE_PARENTS_OUT_OF_EDITOR_SCOPE",START_IS_MILESTONE:"START_IS_MILESTONE",END_IS_MILESTONE:"END_IS_MILESTONE",TASK_HAS_CONSTRAINTS:"TASK_HAS_CONSTRAINTS",GANTT_ERROR_DEPENDS_ON_OPEN_TASK:"GANTT_ERROR_DEPENDS_ON_OPEN_TASK",GANTT_ERROR_DESCENDANT_OF_CLOSED_TASK:"GANTT_ERROR_DESCENDANT_OF_CLOSED_TASK",TASK_HAS_EXTERNAL_DEPS:"TASK_HAS_EXTERNAL_DEPS",GANTT_ERROR_LOADING_DATA_TASK_REMOVED:"GANTT_ERROR_LOADING_DATA_TASK_REMOVED",
CIRCULAR_REFERENCE:"CIRCULAR_REFERENCE",ERROR_SETTING_DATES:"ERROR_SETTING_DATES",CANNOT_DEPENDS_ON_ANCESTORS:"CANNOT_DEPENDS_ON_ANCESTORS",CANNOT_DEPENDS_ON_DESCENDANTS:"CANNOT_DEPENDS_ON_DESCENDANTS",INVALID_DATE_FORMAT:"INVALID_DATE_FORMAT",GANTT_QUARTER_SHORT:"QUARTER ",GANTT_SEMESTER_SHORT:"SEMESTER ",CANNOT_CLOSE_TASK_IF_OPEN_ISSUE:"CANNOT_CLOSE_TASK_IF_OPEN_ISSUE"};GanttMaster.prototype.hasUnsavedTasks=function(){return 0<this.__undoStack.length?!0:!1};
GanttMaster.prototype.isHoliday=function(a){var b=this.calendarSettings.satIsHoly,c=this.calendarSettings.sunIsHoly;pad=function(a){a="0"+a;return a.substr(a.length-2)};var d=this.calendarSettings.holidays,e="#"+a.getFullYear()+"_"+pad(a.getMonth()+1)+"_"+pad(a.getDate())+"#",f="#"+pad(a.getMonth()+1)+"_"+pad(a.getDate())+"#";a=a.getDay();return 6==a&&b||0==a&&c||-1<d.indexOf(e)||-1<d.indexOf(f)};GanttMaster.prototype.computeStart=function(a){return this.computeStartDate(a).getTime()};
GanttMaster.prototype.computeStartDate=function(a){a=new Date(a+432E5);for(a.setHours(0,0,0,0);this.isHoliday(a);)a.setDate(a.getDate()+1);a.setHours(0,0,0,0);return a};GanttMaster.prototype.computeEnd=function(a){return this.computeEndDate(a).getTime()};GanttMaster.prototype.computeEndDate=function(a){a=new Date(a-432E5);for(a.setHours(23,59,59,999);this.isHoliday(a);)a.setDate(a.getDate()+1);a.setHours(23,59,59,999);return a};
GanttMaster.prototype.computeEndByDuration=function(a,b){for(var c=new Date(a),d=b-1;0<d;)c.setDate(c.getDate()+1),this.isHoliday(c)||d--;c.setHours(23,59,59,999);return c.getTime()};GanttMaster.prototype.createTask=function(a,b,c,d,e,f){var l=new TaskFactory;e=this.computeStart(e);var g=this.computeEndByDuration(e,f);return l.build(a,b,c,d,e,g,f)};
GanttMaster.prototype.updateDependsStrings=function(){for(var a=0;a<this.tasks.length;a++)this.tasks[a].depends="";for(a=0;a<this.links.length;a++){var b=this.links[a];b.to.depends=b.to.depends+(""==b.to.depends?"":",")+(b.from.getRow()+1)+(b.lag?":"+b.lag:"")}};
GanttMaster.prototype.removeLink=function(a,b){if(this.canWrite&&(a.canWrite||b.canWrite)){this.beginTransaction();for(var c=!1,d=0;d<this.links.length;d++)if(this.links[d].from==a&&this.links[d].to==b){this.links.splice(d,1);c=!0;break}c&&(this.updateDependsStrings(),this.updateLinks(b)&&this.changeTaskDates(b,b.start,b.end));this.endTransaction()}};
GanttMaster.prototype.removeAllLinks=function(a,b){if(this.canWrite&&(a.canWrite||a.canWrite)){b&&this.beginTransaction();for(var c=!1,d=0;d<this.links.length;d++)if(this.links[d].from==a||this.links[d].to==a)this.links.splice(d,1),c=!0;c&&this.updateDependsStrings();b&&this.endTransaction()}};
GanttMaster.prototype.addTask=function(a,b){a.master=this;for(var c=-1,d=0;d<this.tasks.length;d++)if(a.id==this.tasks[d].id){c=d;break}0<=c&&(this.tasks.splice(c,1),b=parseInt(c));"number"!=typeof b?this.tasks.push(a):(this.tasks.splice(b,0,a),this.updateDependsStrings());c=!this.updateLinks(a);a.getParent()?a.status=a.getParent().status:a.status="STATUS_ACTIVE";d=a;c||!a.setPeriod(a.start,a.end)?(this.tasks.splice(a.getRow(),1),d=void 0):(this.editor.addTask(a,b),this.gantt.addTask(a));return d};
GanttMaster.prototype.loadProject=function(a){this.beginTransaction();this.canWrite=a.canWrite;this.canWriteOnParent=a.canWriteOnParent;this.cannotCloseTaskIfIssueOpen=a.cannotCloseTaskIfIssueOpen;this.minEditableDate=a.minEditableDate?this.computeStart(a.minEditableDate):-Infinity;this.maxEditableDate=a.maxEditableDate?this.computeEnd(a.maxEditableDate):Infinity;this.loadTasks(a.tasks,a.selectedRow);this.deletedTaskIds=[];a.splitterPosition&&this.splitter.resize(a.splitterPosition);a.zoom&&(this.gantt.zoom=
a.zoom);this.endTransaction(!0);var b=this;this.gantt.element.oneTime(200,function(){b.gantt.centerOnToday()})};
GanttMaster.prototype.loadTasks=function(a,b){var c=new TaskFactory;this.reset();for(var d=0;d<a.length;d++){var e=a[d];if(!(e instanceof Task)){var f=this.computeStart(e.start),l=this.computeEndByDuration(f,e.duration),f=c.build(e.id,e.name,e.code,e.level,f,l,e.duration,e.collapsed),g;for(g in e)"end"!=g&&"start"!=g&&(f[g]=e[g]);e=f}e.master=this;this.tasks.push(e)}for(d=0;d<this.tasks.length;d++){e=this.tasks[d];for(c=this.__currentTransaction&&this.__currentTransaction.errors?this.__currentTransaction.errors.length:
0;!this.updateLinks(e);){if(this.__currentTransaction&&c!=this.__currentTransaction.errors.length){for(g="";c<this.__currentTransaction.errors.length;)f=this.__currentTransaction.errors.pop(),g=g+f.msg+"\n\n";alert(g)}this.removeAllLinks(e,!1)}e.setPeriod(e.start,e.end)?(this.editor.addTask(e,null,!0),this.gantt.addTask(e)):(alert(GanttMaster.messages.GANNT_ERROR_LOADING_DATA_TASK_REMOVED+"\n"+e.name+"\n"+GanttMaster.messages.ERROR_SETTING_DATES),this.tasks.splice(e.getRow(),1))}this.editor.fillEmptyLines();
this.tasks&&0<this.tasks.length&&this.tasks[b?b:0].rowElement.click()};GanttMaster.prototype.getTask=function(a){for(var b,c=0;c<this.tasks.length;c++){var d=this.tasks[c];if(d.id==a){b=d;break}}return b};GanttMaster.prototype.changeTaskDates=function(a,b,c){return a.setPeriod(b,c)};GanttMaster.prototype.moveTask=function(a,b){return a.moveTo(b,!0)};
GanttMaster.prototype.taskIsChanged=function(a){var b=this;a||(b.timeoutId&&clearTimeout(b.timeoutId),b.timeoutId=setTimeout(b.saveToServer(),50));this.element.stopTime("gnnttaskIsChanged");this.element.oneTime(50,"gnnttaskIsChanged",function(){b.editor.redraw();b.gantt.refreshGantt()})};
GanttMaster.prototype.saveToServer=function(){var a=this,b=this.saveProject();b.hasOwnProperty("tasks")&&0<b.tasks.length&&$.ajax({type:"POST",async:!1,url:"projectManagement/taskItemUpdate",data:{id:a.projectSchedule.id[0],prj:JSON.stringify(b),_csrf_token:a.projectSchedule._csrf_token[0]},success:function(b){b.success&&a.updateTasksAfterAjax(b.data.tasks)},dataType:"json"})};
GanttMaster.prototype.updateTasksAfterAjax=function(a){for(var b=0;b<a.length;b++)this.tasks[b].idFromDB=a[b].id,this.tasks[b]._csrf_token=a[b]._csrf_token};GanttMaster.prototype.redraw=function(){this.editor.redraw();this.gantt.refreshGantt()};GanttMaster.prototype.reset=function(){this.tasks=[];this.links=[];this.deletedTaskIds=[];this.__inUndoRedo?this.__inUndoRedo=!1:(this.__undoStack=[],this.__redoStack=[]);delete this.currentTask;this.editor.reset();this.gantt.reset()};
GanttMaster.prototype.showTaskEditor=function(a){this.getTask(a).rowElement.find(".edit").click()};GanttMaster.prototype.saveProject=function(){return this.saveGantt(!1)};
GanttMaster.prototype.saveGantt=function(a){for(var b=[],c=0;c<this.tasks.length;c++){var d=this.tasks[c].clone();delete d.master;delete d.rowElement;delete d.ganttElement;b.push(d)}b={tasks:b};this.currentTask&&(b.selectedRow=this.currentTask.getRow());b.deletedTaskIds=this.deletedTaskIds;a||(b.canWrite=this.canWrite,b.canWriteOnParent=this.canWriteOnParent,b.splitterPosition=this.splitter.perc,b.zoom=this.gantt.zoom);return b};
GanttMaster.prototype.updateLinks=function(a){function b(a,c,d){if(c==a)return!0;for(var e=a.getSuperiors(),k=a.getParent();k;)e=e.concat(k.getSuperiors()),k=k.getParent();for(var m=a.getChildren(),k=0;k<m.length;k++)e=e.concat(m[k].getSuperiors());m=!1;for(k=0;k<e.length;k++){var q=e[k];if(q.from==c){m=!0;break}else if(0>=d.indexOf(q.from.id+"x"+c.id)&&(d.push(q.from.id+"x"+c.id),b(q.from,c,d))){m=!0;break}}(c=c.getParent())&&0>=d.indexOf(a.id+"x"+c.id)&&(d.push(a.id+"x"+c.id),b(a,c,d)&&(m=!0));
return m}this.links=this.links.filter(function(b){return b.to!=a});var c=!0;if(a.depends){for(var d=a.getParents(),e=a.getDescendant(),f=a.depends.split(","),l="",g=[],n=0;n<f.length;n++){var p=f[n],h=p.split(":"),k=0;1<h.length&&(k=parseInt(h[1]));if(h=this.tasks[parseInt(h[0]-1)])d&&0<=d.indexOf(h)?(this.setErrorOnTransaction(a.name+"\n"+GanttMaster.messages.CANNOT_DEPENDS_ON_ANCESTORS+"\n"+h.name),c=!1):e&&0<=e.indexOf(h)?(this.setErrorOnTransaction(a.name+"\n"+GanttMaster.messages.CANNOT_DEPENDS_ON_DESCENDANTS+
"\n"+h.name),c=!1):b(h,a,g)?(c=!1,this.setErrorOnTransaction(GanttMaster.messages.CIRCULAR_REFERENCE+"\n"+a.name+" -> "+h.name)):(this.links.push(new Link(h,a,k)),l=l+(0<l.length?",":"")+p)}a.depends=l}return c};GanttMaster.prototype.moveUpCurrentTask=function(){this.canWrite&&this.currentTask&&(this.beginTransaction(),this.currentTask.moveUp(),this.endTransaction())};
GanttMaster.prototype.moveDownCurrentTask=function(){this.canWrite&&this.currentTask&&(this.beginTransaction(),this.currentTask.moveDown(),this.endTransaction())};GanttMaster.prototype.outdentCurrentTask=function(){if(this.canWrite&&this.currentTask.canWrite&&this.currentTask){var a=this.currentTask.getParent();this.beginTransaction();this.currentTask.outdent();this.endTransaction();a&&this.editor.refreshExpandStatus(a)}};
GanttMaster.prototype.indentCurrentTask=function(){this.canWrite&&this.currentTask.canWrite&&this.currentTask&&(this.beginTransaction(),this.currentTask.indent(),this.endTransaction())};
GanttMaster.prototype.addBelowCurrentTask=function(){if(this.canWrite){var a=new TaskFactory;this.beginTransaction();var b=0;if(this.currentTask)var c=this.computeStart(this.currentTask.start),d=this.computeEndByDuration(c,1),b=0<this.currentTask.level?this.currentTask.level:this.currentTask.level+1,a=a.build("tmp_"+(new Date).getTime(),"","",b,c,d,1),b=this.currentTask.getRow()+1;else c=this.computeStart((new Date).getTime()),d=this.computeEndByDuration(c,1),a=a.build("tmp_"+(new Date).getTime(),
"","",0,c,d,1);if(a=this.addTask(a,b))a.rowElement.click(),a.rowElement.find("[name=name]").focus();this.endTransaction()}};
GanttMaster.prototype.addAboveCurrentTask=function(){if(this.canWrite){var a=new TaskFactory,b=0;if(this.currentTask){if(0>=this.currentTask.level)return;var c=this.computeStart(this.currentTask.start),d=this.computeEndByDuration(c,1),a=a.build("tmp_"+(new Date).getTime(),"","",this.currentTask.level,c,d,1),b=this.currentTask.getRow()}else c=this.computeStart((new Date).getTime()),d=this.computeEndByDuration(c,1),a=a.build("tmp_"+(new Date).getTime(),"","",0,c,d,1);this.beginTransaction();if(b=this.addTask(a,
b))b.rowElement.click(),b.rowElement.find("[name=name]").focus();this.endTransaction()}};
GanttMaster.prototype.deleteCurrentTask=function(){if(this.currentTask&&this.canWrite&&this.currentTask.canWrite){var a=this.currentTask.getRow();if(this.currentTask&&(0<a||this.currentTask.isNew())){var b=this.currentTask.getParent();this.beginTransaction();this.currentTask.deleteTask();this.currentTask=void 0;this.updateDependsStrings();this.redraw();b&&this.editor.refreshExpandStatus(b);a=a>this.tasks.length-1?this.tasks.length-1:a;0<=a&&(this.currentTask=this.tasks[a],this.currentTask.rowElement.click(),
this.currentTask.rowElement.find("[name=name]").focus());this.endTransaction()}}};GanttMaster.prototype.beginTransaction=function(){this.__currentTransaction?console.error("Cannot open twice a transaction"):this.__currentTransaction={snapshot:JSON.stringify(this.saveGantt(!0)),errors:[]};return this.__currentTransaction};
GanttMaster.prototype.endTransaction=function(a){this.changesFromLoadProject=a?!0:!1;if(!this.__currentTransaction)return console.error("Transaction never started."),!0;var b=!0;if(0>=this.__currentTransaction.errors.length){this.__undoStack.push(this.__currentTransaction.snapshot);this.__redoStack=[];this.gantt.originalStartMillis=Infinity;this.gantt.originalEndMillis=-Infinity;for(var c=0;c<this.tasks.length;c++){var d=this.tasks[c];this.gantt.originalStartMillis>d.start&&(this.gantt.originalStartMillis=
d.start);this.gantt.originalEndMillis<d.end&&(this.gantt.originalEndMillis=d.end)}this.taskIsChanged(a)}else{b=!1;c=JSON.parse(this.__currentTransaction.snapshot);this.deletedTaskIds=c.deletedTaskIds;this.loadTasks(c.tasks,c.selectedRow);this.redraw();a="";for(c=0;c<this.__currentTransaction.errors.length;c++)a=a+this.__currentTransaction.errors[c].msg+"\n\n";alert(a)}this.__currentTransaction=void 0;this.editor.refreshExpandStatus(this.currentTask);return b};
GanttMaster.prototype.setErrorOnTransaction=function(a,b){this.__currentTransaction?this.__currentTransaction.errors.push({msg:a,task:b}):console.error(a)};GanttMaster.prototype.checkpoint=function(){this.__undoStack=[];this.__redoStack=[]};
GanttMaster.prototype.undo=function(){if(0<this.__undoStack.length){var a=this.__undoStack.pop();this.__redoStack.push(JSON.stringify(this.saveGantt()));a=JSON.parse(a);this.deletedTaskIds=a.deletedTaskIds;this.__inUndoRedo=!0;this.loadTasks(a.tasks,a.selectedRow);this.redraw()}};
GanttMaster.prototype.redo=function(){if(0<this.__redoStack.length){var a=this.__redoStack.pop();this.__undoStack.push(JSON.stringify(this.saveGantt()));a=JSON.parse(a);this.deletedTaskIds=a.deletedTaskIds;this.__inUndoRedo=!0;this.loadTasks(a.tasks,a.selectedRow);this.redraw()}};GanttMaster.prototype.resize=function(){this.splitter.resize()};GanttMaster.prototype.getCollapsedDescendant=function(){for(var a=this.tasks,b=[],c=0;c<a.length;c++){var d=a[c];0<=b.indexOf(d)||d.collapsed&&(b=b.concat(d.getDescendant()))}return b};
GanttMaster.prototype.computeCriticalPath=function(){function a(a,b){for(var c=0;c<b.length;c++)if(0>a.indexOf(b[c]))return!1;return!0}function b(a){var c=a.earlyFinish;a=a.getInferiorTasks();for(var d=0;d<a.length;d++){var e=a[d];c>=e.earlyStart&&(e.earlyStart=c,e.earlyFinish=c+e.duration);b(e)}}if(!this.tasks)return!1;for(var c=this.tasks.filter(function(a){return 0<a.getRow()&&(!a.isParent()||a.isParent()&&!a.isDependent())}),d=0;d<c.length;d++){var e=c[d];e.earlyStart=-1;e.earlyFinish=-1;e.latestStart=
-1;e.latestFinish=-1;e.criticalCost=-1;e.isCritical=!1}for(var f=[],l=c.concat();0<l.length;){e=!1;for(d=0;d<l.length;d++){var g=l[d],n=g.getInferiorTasks();if(a(f,n)){for(var p=0,h=0;h<n.length;h++)e=n[h],e.criticalCost>p&&(p=e.criticalCost);g.criticalCost=p+g.duration;f.push(g);l.splice(d,1);e=!0}}if(!e)return console.error("Cyclic dependency, algorithm stopped!"),!1}(function(a){for(var b=-1,c=0;c<a.length;c++){var d=a[c];d.criticalCost>b&&(b=d.criticalCost)}for(c=0;c<a.length;c++)d=a[c],d.setLatest(b)})(c);
(function(a){for(var c=0;c<a.length;c++){var d=a[c];d.earlyStart=0;d.earlyFinish=d.duration;b(d)}})(function(a){for(var b=[],c=0;c<a.length;c++)a[c].depends&&""!=a[c].depends||b.push(a[c]);return b}(c));(function(a){for(var b=0;b<a.length;b++){var c=a[b];c.isCritical=c.earlyStart==c.latestStart}})(c);return c};
