function Ganttalendar(d,c,g,h,e){this.master=h;this.element;this.highlightBar;this.svg;this.tasksGroup;this.linksGroup;this.zoom=d;this.minGanttSize=e;this.showCriticalPath=this.includeToday=!1;this.zoomLevels="dwmqsy".split("");this.element=this.create(d,c,g);this.linkOnProgress=!1;this.rowHeight=30;this.taskHeight=20;this.taskVertOffset=(this.rowHeight-this.taskHeight)/2}
Ganttalendar.prototype.zoomGantt=function(d){var c=this.zoom,c=this.zoomLevels.indexOf(c+"");d=d?0>=c?0:c-1:c>=this.zoomLevels.length-1?this.zoomLevels.length-1:c+1;d!=c&&(this.zoom=c=this.zoomLevels[d],this.refreshGantt())};
Ganttalendar.prototype.create=function(d,c,g){function h(f,b,c,a){f=$("<th>").html(f).attr("colSpan",b);a&&f.width(a);c&&f.addClass(c);return f}function e(c,b,a){c=$("<td>").html("").attr("colSpan",c).addClass("ganttBodyCell");b&&c.addClass("end");a&&c.addClass(a);return c}var b=this,a=b.master.projectScheduleStartDate.getTime()+1296E6;c=b.master.projectScheduleStartDate.getTime()-1728E5;g=g<a?a:g;a=function(c,b,a){b=new Date(b);a=new Date(a);"d"==c?(b.setHours(0,0,0,0),a.setHours(23,59,59,999),b.setFirstDayOfThisWeek(),
a.setFirstDayOfThisWeek(),a.setDate(a.getDate()+6)):"w"==c?(b.setHours(0,0,0,0),a.setHours(23,59,59,999),b.setFirstDayOfThisWeek(),a.setFirstDayOfThisWeek(),a.setDate(a.getDate()+6)):"m"==c?(b.setHours(0,0,0,0),a.setHours(23,59,59,999),b.setDate(1),a.setDate(1),a.setMonth(a.getMonth()+1),a.setDate(a.getDate()-1)):"q"==c?(b.setHours(0,0,0,0),a.setHours(23,59,59,999),b.setDate(1),b.setMonth(3*Math.floor(b.getMonth()/3)),a.setDate(1),a.setMonth(3*Math.floor(a.getMonth()/3)+3),a.setDate(a.getDate()-1)):
"s"==c?(b.setHours(0,0,0,0),a.setHours(23,59,59,999),b.setDate(1),b.setMonth(6*Math.floor(b.getMonth()/6)),a.setDate(1),a.setMonth(6*Math.floor(a.getMonth()/6)+6),a.setDate(a.getDate()-1)):"y"==c&&(b.setHours(0,0,0,0),a.setHours(23,59,59,999),b.setDate(1),b.setMonth(0),a.setDate(1),a.setMonth(12),a.setDate(a.getDate()-1));return{start:b.getTime(),end:a.getTime()}}(d,c,g);b.startMillis=a.start;b.endMillis=a.end;b.originalStartMillis=c;b.originalEndMillis=g;return function(a,c,d){function f(a,b){for(var u=
new Date(c);u.getTime()<=d;)a(u);for(u=new Date(c);u.getTime()<=d;)b(u)}var k=$("<tr>").addClass("ganttHead1"),n=$("<tr>").addClass("ganttHead2"),q=$("<tr>").addClass("ganttBody"),m;"y"==a?(m=Math.floor((d-c)/15552E6*100),f(function(a){k.append(h(a.format("yyyy"),2));a.setFullYear(a.getFullYear()+1)},function(a){var b=Math.floor(a.getMonth()/6)+1;n.append(h(GanttMaster.messages.GANTT_SEMESTER_SHORT+b,1,null,100));q.append(e(1,2==b));a.setMonth(a.getMonth()+6)})):"s"==a?(m=Math.floor((d-c)/7776E6*
100),f(function(a){var b=new Date(a.getTime());b.setMonth(b.getMonth()+6);b.setDate(b.getDate()-1);k.append(h(a.format("MMM")+" - "+b.format("MMM yyyy"),2));a.setMonth(a.getMonth()+6)},function(a){var b=Math.floor(a.getMonth()/3)+1;n.append(h(GanttMaster.messages.GANTT_QUARTER_SHORT+b,1,null,100));q.append(e(1,0==b%2));a.setMonth(a.getMonth()+3)})):"q"==a?(m=Math.floor((d-c)/2592E6*300),f(function(a){var b=new Date(a.getTime());b.setMonth(b.getMonth()+3);b.setDate(b.getDate()-1);k.append(h(a.format("MMM")+
" - "+b.format("MMM yyyy"),3));a.setMonth(a.getMonth()+3)},function(a){var b=a.format("MMM");n.append(h(b,1,null,300));q.append(e(1,2==a.getMonth()%3));a.setMonth(a.getMonth()+1)})):"m"==a?(m=Math.floor((d-c)/864E5*25),f(function(a){var b=a.getTime();a.setMonth(a.getMonth()+1);a=Math.round((a.getTime()-b)/864E5);k.append(h((new Date(b)).format("MMMM yyyy"),a))},function(a){n.append(h(a.format("d"),1,b.master.isHoliday(a)?"holyH":null,25));var c=new Date(a.getTime());c.setDate(a.getDate()+1);q.append(e(1,
1==c.getDate(),b.master.isHoliday(a)?"holy":null));a.setDate(a.getDate()+1)})):"w"==a?(m=Math.floor((d-c)/864E5*40),f(function(a){var b=new Date(a.getTime());b.setDate(b.getDate()+6);k.append(h(a.format("MMM d")+" - "+b.format("MMM d'yy"),7));a.setDate(a.getDate()+7)},function(a){n.append(h(a.format("EEEE").substr(0,1),1,b.master.isHoliday(a)?"holyH":null,40));q.append(e(1,a.getDay()%7==(b.master.firstDayOfWeek+6)%7,b.master.isHoliday(a)?"holy":null));a.setDate(a.getDate()+1)})):"d"==a?(m=Math.floor((d-
c)/864E5*100),f(function(a){var b=new Date(a.getTime());b.setDate(b.getDate()+6);k.append(h(a.format("MMMM d")+" - "+b.format("MMMM d yyyy"),7));a.setDate(a.getDate()+7)},function(a){n.append(h(a.format("EEE d"),1,b.master.isHoliday(a)?"holyH":null,100));q.append(e(1,a.getDay()%7==(b.master.firstDayOfWeek+6)%7,b.master.isHoliday(a)?"holy":null));a.setDate(a.getDate()+1)})):console.error("Wrong level "+a);m=Math.max(m,b.minGanttSize);var g=$("<table cellspacing=0 cellpadding=0>");g.append(k).append(n).css({width:m});
var x=g.clone().addClass("fixHead");g.append(q).addClass("ganttTable");var w=b.master.editor.element.height();g.height(w);a=$("<div>");a.addClass("gantt unselectable").attr("unselectable","true").css({position:"relative",width:m});a.append(g);a.append(x);g=$("<div>").addClass("ganttHighLight");a.append(g);b.highlightBar=g;a.svg({settings:{"class":"ganttSVGBox"},onLoad:function(a){var f=a.defs("myDefs"),f=a.pattern(f,"extDep",0,0,10,10,0,0,10,10,{patternUnits:"userSpaceOnUse"});a.image(f,0,0,10,10,
b.master.resourceUrl+"hasExternalDeps.png",{opacity:.3});b.svg=a;$(a).addClass("ganttSVGBox");for(var f=a.group("gridGroup"),k=40;k<=w;k+=b.rowHeight)a.line(f,0,k,"100%",k,{"class":"ganttLinesSVG"});b.linksGroup=a.group("linksGroup");b.tasksGroup=a.group("tasksGroup");b.fx=m/(d-c);(new Date).getTime()>b.startMillis&&(new Date).getTime()<b.endMillis&&(k=Math.round(((new Date).getTime()-b.startMillis)*b.fx),a.line(f,k,0,k,"100%",{"class":"ganttTodaySVG"}))}});return a}(d,a.start,a.end)};
Ganttalendar.prototype.drawTask=function(d){var c=this;editorRow=d.rowElement;var g=editorRow.position().top+editorRow.offsetParent().scrollTop(),h=Math.round((d.start-c.startMillis)*c.fx);d.hasChild=d.isParent();var e=$(function(b,a){var f=c.svg,d=f.svg(c.tasksGroup,a.x,a.y,a.width,a.height,{"class":"taskBox taskBoxSVG taskStatusSVG",status:b.status,taskid:b.id});f.rect(d,0,0,"100%","100%",{"class":"taskLayout",rx:"2",ry:"2"});f.rect(d,0,0,"100%","100%",{fill:"rgba(255,255,255,.3)"});b.hasExternalDep&&
f.rect(d,0,0,"100%","100%",{fill:"url(#extDep)"});if(0<b.progress&&(f.rect(d,0,0,(100<b.progress?100:b.progress)+"%","100%",{rx:"2",ry:"2"}),50<a.width)){var e={fill:"#888","font-size":"10px","class":"textPerc",transform:"translate(5)"};100<b.progress&&(e["font-weight"]="bold");90<b.progress&&(e.transform="translate(-40)");f.text(d,(90<b.progress?100:b.progress)+"%",(c.rowHeight-5)/2,(100<b.progress?"!!! ":"")+b.progress+"%",e)}b.hasChild&&f.rect(d,0,0,"100%",3,{fill:"#000"});b.startIsMilestone&&
f.image(d,-9,a.height/2-9,18,18,c.master.resourceUrl+"milestone.png");b.endIsMilestone&&f.image(d,"100%",a.height/2-9,18,18,c.master.resourceUrl+"milestone.png",{transform:"translate(-9)"});f.text(d,"100%",18,b.name,{"class":"taskLabelSVG",transform:"translate(20,-5)"});0<b.level&&(f.circle(d,"0",a.height/2,a.height/3,{"class":"taskLinkStartSVG linkHandleSVG",transform:"translate("+(-a.height/3-1)+")"}),f.circle(d,"100%",a.height/2,a.height/3,{"class":"taskLinkEndSVG linkHandleSVG",transform:"translate("+
(a.height/3+1)+")"}));return d}(d,{x:h,y:g+c.taskVertOffset,width:Math.round((d.end-d.start)*c.fx),height:c.taskHeight}));d.ganttElement=e;c.showCriticalPath&&d.isCritical&&e.addClass("critical");this.master.canWrite&&d.canWrite&&(e.click(function(b){b.stopPropagation();c.element.find(".focused").removeClass("focused");$(".ganttSVGBox .focused").removeClass("focused");b=$(this);c.resDrop||b.addClass("focused");c.resDrop=!1;$("body").off("click.focused").one("click.focused",function(){$(".ganttSVGBox .focused").removeClass("focused")})}).dblclick(function(){c.master.showTaskEditor($(this).attr("taskid"))}).mouseenter(function(){var b=
$(this);c.linkOnProgress?b.addClass("linkOver"):b.find(".linkHandleSVG").show()}).mouseleave(function(){$(this).removeClass("linkOver").find(".linkHandleSVG").hide()}).mouseup(function(b){$(":focus").blur()}).mousedown(function(){c.master.getTask($(this).attr("taskId")).rowElement.click()}).dragExtedSVG($(c.svg.root()),{canResize:this.master.canWrite&&d.canWrite,canDrag:!d.depends&&this.master.canWrite&&d.canWrite,startDrag:function(b){$(".ganttSVGBox .focused").removeClass("focused")},drag:function(b){$("[from="+
d.id+"],[to="+d.id+"]").trigger("update")},drop:function(b){c.resDrop=!0;var a=$(this);b=c.master.getTask(a.attr("taskid"));a=Math.round(parseFloat(a.attr("x"))/c.fx+c.startMillis);c.master.beginTransaction();c.master.moveTask(b,new Date(a));c.master.endTransaction()},startResize:function(b){$(".ganttSVGBox .focused").removeClass("focused");b=$(this);b=$(c.svg.text(parseInt(b.attr("x"))+parseInt(b.attr("width")+8),parseInt(b.attr("y")),"",{"font-size":"10px",fill:"red"}));e.data("textDur",b)},resize:function(b){b=
$(this);var a=Math.round(parseFloat(b.attr("x"))/c.fx+c.startMillis),f=Math.round((parseFloat(b.attr("x"))+parseFloat(b.attr("width")))/c.fx+c.startMillis),a=c.master.computeStartDate(a).distanceInWorkingDays(c.master.computeEndDate(f));e.data("textDur").attr("x",parseInt(b.attr("x"))+parseInt(b.attr("width"))+8).html(a);$("[from="+d.id+"],[to="+d.id+"]").trigger("update")},stopResize:function(b){c.resDrop=!0;(b=e.data("textDur"))&&b.remove();var a=$(this);b=c.master.getTask(a.attr("taskid"));var d=
Math.round(parseFloat(a.attr("x"))/c.fx+c.startMillis),a=Math.round((parseFloat(a.attr("x"))+parseFloat(a.attr("width")))/c.fx+c.startMillis);c.master.beginTransaction();c.master.changeTaskDates(b,new Date(d),new Date(a));c.master.endTransaction()}}),e.find(".linkHandleSVG").mousedown(function(b){b.preventDefault();b.stopPropagation();var a=$(this).closest(".taskBoxSVG"),d=$(c.svg.root()),k=d.offset();c.linkOnProgress=!0;c.linkFromEnd=$(this).is(".taskLinkEndSVG");d.addClass("linkOnProgress");var e=
parseFloat(a.attr("x"))+(c.linkFromEnd?parseFloat(a.attr("width")):0),h=parseFloat(a.attr("y"))+parseFloat(a.attr("height"))/2,g=c.svg.line(e,h,b.pageX-k.left-5,b.pageY-k.top-5,{"class":"linkLineSVG"}),l=c.svg.circle(e,h,5,{"class":"linkLineSVG"});d.bind("mousemove.linkSVG",function(a){var b=d.offset(),f=a.pageX-b.left;a=a.pageY-b.top;b=Math.sqrt(Math.pow(f-e,2)+Math.pow(a-h,2));f-=10*(f-e)/b;a-=10*(a-h)/b;c.svg.change(g,{x2:f,y2:a});c.svg.change(l,{cx:f,cy:a})});$("body").one("mouseup.linkSVG",function(b){$(g).remove();
$(l).remove();c.linkOnProgress=!1;d.removeClass("linkOnProgress");$(c.svg.root()).unbind("mousemove.linkSVG");if((b=$(b.target).closest(".taskBoxSVG"))&&b.attr("taskid")!=a.attr("taskid")){var f;c.linkFromEnd?(f=c.master.getTask(b.attr("taskid")),b=c.master.getTask(a.attr("taskid"))):(b=c.master.getTask(b.attr("taskid")),f=c.master.getTask(a.attr("taskid")));f&&b&&(f=f.rowElement.find("[name=depends]"),f.val(f.val()+(0<(f.val()+"").length?",":"")+(b.getRow()+1)+""),f.blur())}})}));c.redrawLinks()};
Ganttalendar.prototype.addTask=function(d){this.originalEndMillis=this.originalEndMillis>d.end?this.originalEndMillis:d.end;this.originalStartMillis=this.originalStartMillis<d.start?this.originalStartMillis:d.start};
Ganttalendar.prototype.drawLink=function(d,c,g){function h(a){var b,c,d;a.hasOwnProperty("ganttElement")?(b=parseFloat(a.ganttElement.attr("x")),c=parseFloat(a.ganttElement.attr("y")),d=parseFloat(a.ganttElement.attr("width")),a=parseFloat(a.ganttElement.attr("height"))):a=d=c=b=0;return{left:b,top:c,width:d,height:a}}function e(b,c,d){var f=a.svg,e=f.group(a.linksGroup,""+b.id+"-"+c.id);f.title(e,b.name+" -> "+c.name);var g=f.createPath();f.image(e,0,0,5,10,a.master.resourceUrl+"linkArrow.png");
f.path(e,g,{"class":"taskLinkPathSVG"});e=$(e).data({from:b,to:c}).attr({from:b.id,to:c.id}).on("update",function(){var a=$(this),b=a.data("from"),c=a.data("to"),b=h(b),e=h(c),c=b.left+b.width,g=b.height/2+b.top,k=e.left,e=e.height/2+e.top,n=k<c+2*d,l=g>e,p=l?-1:1,r=c+2*d>k?-1:1,t=a.find("image"),v=f.createPath();n?(b=p*(b.height/2-10+2),v.move(c,g).line(d,0,!0).arc(5,5,90,!1,!l,5,5*p,!0).line(0,b,!0).arc(5,5,90,!1,!l,-5,5*p,!0).line(2*r*d+(k-c),0,!0).arc(5,5,90,!1,l,-5,5*p,!0).line(0,(Math.abs(e-
g)-20-Math.abs(b))*p-5,!0).arc(5,5,90,!1,l,5,5*p,!0).line(d,0,!0),t.attr({x:k-5,y:e-5-5})):(v.move(c,g).line((k-c)/2-5,0,!0).arc(5,5,90,!1,!l,5,5*p,!0).line(0,e-g-10*p+5,!0).arc(5,5,90,!1,l,5,5*p,!0).line((k-c)/2-5,0,!0),t.attr({x:k-5,y:e-5+5}));a.find("path").attr({d:v.path()})}).trigger("update");a.showCriticalPath&&b.isCritical&&c.isCritical&&e.addClass("critical");e.addClass("linkGroup");return e}function b(a,b){console.error("StartToStart not supported on SVG");h(a);h(b)}var a=this;g="start-to-start"==
g?b(d,c,10):e(d,c,10);this.master.canWrite&&(d.canWrite||c.canWrite)&&g.click(function(b){var c=$(this);b.stopPropagation();a.element.find(".focused").removeClass("focused");$(".ganttSVGBox .focused").removeClass("focused");c=$(this);a.resDrop||c.addClass("focused");a.resDrop=!1;$("body").off("click.focused").one("click.focused",function(){$(".ganttSVGBox .focused").removeClass("focused")})})};
Ganttalendar.prototype.redrawLinks=function(){var d=this;this.element.stopTime("ganttlnksredr");this.element.oneTime(60,"ganttlnksredr",function(){$("#linksSVG").empty();var c;c=d.master.getCollapsedDescendant();for(var g=0;g<d.master.links.length;g++){var h=d.master.links[g];0<=c.indexOf(h.from)||0<=c.indexOf(h.to)||d.drawLink(h.from,h.to)}})};Ganttalendar.prototype.reset=function(){this.element.find(".linkGroup").remove();this.element.find("[taskid]").remove()};
Ganttalendar.prototype.redrawTasks=function(){for(var d=this.master.getCollapsedDescendant(),c=0;c<this.master.tasks.length;c++){var g=this.master.tasks[c];0<=d.indexOf(g)||this.drawTask(g)}};
Ganttalendar.prototype.refreshGantt=function(){this.showCriticalPath&&this.master.computeCriticalPath();var d=this.element.parent(),c=d.scrollTop(),g=d.scrollLeft();this.element.remove();if(!this.zoom){var h=Math.round((this.originalEndMillis-this.originalStartMillis)/864E5);this.zoom=this.zoomLevels[2>h?0:15>h?1:60>h?2:150>h?3:4]}this.element=h=this.create(this.zoom,this.originalStartMillis,this.originalEndMillis);d.append(h);this.redrawTasks();d.scrollTop(c);d.scrollLeft(g);this.synchHighlight()};
Ganttalendar.prototype.fitGantt=function(){delete this.zoom;this.refreshGantt()};Ganttalendar.prototype.synchHighlight=function(){this.master.currentTask&&this.master.currentTask.ganttElement&&this.highlightBar.css("top",parseInt(this.master.currentTask.ganttElement.attr("y"))-this.taskVertOffset+"px")};Ganttalendar.prototype.centerOnToday=function(){var d=Math.round(((new Date).getTime()-this.startMillis)*this.fx)-30;this.element.parent().scrollLeft(d)};
$.fn.dragExtedSVG=function(d,c){function g(b){$(d).unbind("mousemove.deSVG").unbind("mouseup.deSVG").unbind("mouseleave.deSVG");e&&a.stopResize.call(e.get(0),b);e=void 0;$("body").clearUnselectable()}function h(b){$(d).unbind("mousemove.deSVG").unbind("mouseup.deSVG").unbind("mouseleave.deSVG");e&&e.attr("oldx")!=e.attr("x")&&a.drop.call(e.get(0),b);e=void 0;$("body").clearUnselectable()}var e,b,a={canDrag:!0,canResize:!0,resizeZoneWidth:15,minSize:10,startDrag:function(a){},drag:function(a){},drop:function(a){},
startResize:function(a){},resize:function(a){},stopResize:function(a){}};$.extend(a,c);this.each(function(){var c=$(this);d.parent().offset();a.canDrag&&c.addClass("deSVGdrag");(a.canResize||a.canDrag)&&c.bind("mousedown.deSVG",function(f){$(f.target).is("image")&&f.preventDefault();e=$(this);var k=parseFloat(c.offset().left),t=k+parseFloat(c.attr("width")),r=f.pageX;$("body").unselectable();r=t-r;if(a.canResize&&0<=r&&r<=a.resizeZoneWidth){b=t-f.pageX;e.attr("oldw",e.attr("width"));var l=!0;$(d).bind("mousemove.deSVG",
function(c){l&&(a.startResize.call(e.get(0),c),l=!1);var d=c.pageX-k+b;e.attr("width",d<a.minSize?a.minSize:d);a.resize.call(e.get(0),c)});$("body").one("mouseup.deSVG",g)}else a.canDrag&&(b=parseFloat(e.attr("x"))-f.pageX,e.attr("oldx",e.attr("x")),l=!0,$(d).bind("mousemove.deSVG",function(c){l&&(a.startDrag.call(e.get(0),c),l=!1);e.attr("x",b+c.pageX);a.drag.call(e.get(0),c)}).bind("mouseleave.deSVG",h),$("body").one("mouseup.deSVG",h))}).bind("mousemove.deSVG",function(b){var c=$(this);b=c.offset().left+
parseFloat(c.attr("width"))-b.pageX;a.canResize&&0<=b&&b<=a.resizeZoneWidth?c.addClass("deSVGhand"):c.removeClass("deSVGhand")}).addClass("deSVG")});return this};
