window.console||(window.console=new function(){this.log=function(a){};this.debug=function(a){};this.error=function(a){}});window.console.debug&&window.console.error&&window.console.log||(window.console=new function(){this.log=function(a){};this.debug=function(a){};this.error=function(a){}});
$.fn.bringToFront=function(a){var b=10;(a?$(a):$("*")).each(function(){"static"!=$(this).css("position")&&(b=parseInt($(this).css("zIndex"))>b?parseInt($(this).css("zIndex")):b)});return $(this).css("zIndex",b+=10)};
function nearBestPosition(a,b,d){var e=a,c=b;"object"!=typeof a&&(e=$("#"+a));"object"!=typeof b&&(c=$("#"+b));if(e){c.css("visibility","hidden");var f=!1;c.parents().each(function(){"static"!=$(this).css("position")&&(f=!0)});a=f?e.position().left:e.offset().left;b=f?e.position().top:e.offset().top;var h=e.outerHeight(),h=parseFloat(h);if(d){d=parseFloat(e.outerWidth());var g=parseFloat(c.outerWidth());a+=(d-g)/2}b+=parseFloat(h);d=a;h=b;a&&b&&(c.css("left",d),c.css("top",h));c.offset().left>=$(window).width()-
c.outerWidth()&&(d=$(window).width()-c.outerWidth()-0+"px",c.css("left",d));0>c.offset().left&&c.css("left","0px");c.offset().top+c.outerHeight()>=$(window).height()-35&&c.outerHeight()<$(window).height()&&c.css("margin-top",-(e.outerHeight()+c.outerHeight())+"px");c.css("visibility","visible")}}String.prototype.trim=function(){return this.replace(/^\s*(\S*(\s+\S+)*)\s*$/,"$1")};
String.prototype.startsWith=function(a,b){return b?a.toLowerCase()==this.substring(0,a.length).toLowerCase():a==this.substring(0,a.length)};String.prototype.endsWith=function(a,b){return b?a.toLowerCase()==this.substring(this.length-a.length).toLowerCase():a==this.substring(this.length-a.length)};String.prototype.asId=function(){return this.replace(/[^a-zA-Z0-9_]+/g,"")};String.prototype.replaceAll=function(a,b){return this.replace(new RegExp(RegExp.quote(a),"g"),b)};
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){if(null==this)throw new TypeError;var d=Object(this),e=d.length>>>0;if(0===e)return-1;var c=0;0<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=e)return-1;for(c=0<=c?c:Math.max(e-Math.abs(c),0);c<e;c++)if(c in d&&d[c]===a)return c;return-1});Object.size=function(a){var b=0,d;for(d in a)a.hasOwnProperty(d)&&b++;return b};
function transformToPrintable(a){for(var b in a){var d=a[b];"string"==typeof d&&(a[b]=(d+"").replace(/\n/g,"<br>"))}return a}function isValidURL(a){return/^(([\w]+:)?\/\/)?(([\d\w]|%[a-fA-f\d]{2,2})+(:([\d\w]|%[a-fA-f\d]{2,2})+)?@)?([\d\w][-\d\w]{0,253}[\d\w]\.)+[\w]{2,4}(:[\d]+)?(\/([-+_~.\d\w]|%[a-fA-f\d]{2,2})*)*(\?(&?([-+_~.\d\w]|%[a-fA-f\d]{2,2})=?)*)?(#([-+_~.\d\w]|%[a-fA-f\d]{2,2})*)?$/.test(a)}
function isValidEmail(a){return/^((([a-z]|[0-9]|!|#|$|%|&|'|\*|\+|\-|\/|=|\?|\^|_|`|\{|\||\}|~)+(\.([a-z]|[0-9]|!|#|$|%|&|'|\*|\+|\-|\/|=|\?|\^|_|`|\{|\||\}|~)+)*)@((((([a-z]|[0-9])([a-z]|[0-9]|\-){0,61}([a-z]|[0-9])\.))*([a-z]|[0-9])([a-z]|[0-9]|\-){0,61}([a-z]|[0-9])\.)[\w]{2,4}|(((([0-9]){1,3}\.){3}([0-9]){1,3}))|(\[((([0-9]){1,3}\.){3}([0-9]){1,3})\])))$/.test(a)}function isValidInteger(a){reg=/^[-+]{0,1}[0-9]*$/;return reg.test(a)}
function isValidDouble(a){reg=new RegExp("^[-+]{0,1}[0-9]*["+Number.decimalSeparator+"]{0,1}[0-9]*$");return reg.test(a)}function isValidTime(a){return!isNaN(millisFromHourMinute(a))}function isValidDurationDays(a){return!isNaN(daysFromString(a))}function isValidDurationMillis(a){return!isNaN(millisFromString(a))}function isValidDurationMillis(a){return!isNaN(millisFromString(a))}
function isValidCurrency(a){for(var b="",d=Number.currencyFormat+"",e=!1,c=!1,f="",h="[0-9\\"+Number.groupingSeparator+"]+[\\"+Number.decimalSeparator+"]?[0-9]*",g=0;g<d.length;g++){var n=d.charAt(g);"."==n||","==n||"0"==n?""!=f&&(b=b+"(?:"+RegExp.quote(f)+")?",f=""):"#"==n?(""!=f&&(b=b+"(?:"+RegExp.quote(f)+")?",f=""),c||(c=!0,b+=h)):"-"==n?(""!=f&&(b=b+"(?:"+RegExp.quote(f)+")?",f=""),e||(e=!0,b+="[-]?")):f+=n}e||(b="[-]?"+b);""!=f&&(b=b+"(?:"+RegExp.quote(f)+")?");return(new RegExp("^"+b+"$")).test(a)}
function getCurrencyValue(a){return isValidCurrency(a)?parseFloat(a.replaceAll(Number.groupingSeparator,"").replaceAll(Number.decimalSeparator,".").replace(/[^0123456789.]/,"")):NaN}function formatCurrency(a){return formatNumber(a,Number.currencyFormat)}
function formatNumber(a,b){b||(b="##0.00");for(var d=Number.decimalSeparator,e=Number.groupingSeparator,c=Number.minusSign,f="",h=!1,g=0;g<b.length;g++)if(-1=="0#-,.".indexOf(b.charAt(g)))f+=b.charAt(g);else if(0==g&&"-"==b.charAt(g))h=!0;else break;for(var n="",g=b.length-1;0<=g;g--)if(-1=="0#-,.".indexOf(b.charAt(g)))n=b.charAt(g)+n;else break;b=b.substring(f.length);b=b.substring(0,b.length-n.length);var p=new Number(a),r=!1;isNaN(p)&&(p=0,r=!0);"%"==n&&(p*=100);var q="";if(-1<b.indexOf(".")){for(var l=
d,k=b.substring(b.lastIndexOf(".")+1),p=new Number(p.toFixed(k.length)),m=new String((p%1).toFixed(k.length)),m=m.substring(m.lastIndexOf(".")+1),g=0;g<k.length;g++)if("#"==k.charAt(g)&&"0"!=m.charAt(g))l+=m.charAt(g);else if("#"==k.charAt(g)&&"0"==m.charAt(g))if(m.substring(g).match("[1-9]"))l+=m.charAt(g);else break;else"0"==k.charAt(g)&&(l+=m.charAt(g));q+=l}else p=Math.round(p);g=Math.floor(p);0>p&&(g=Math.ceil(p));l=-1==b.indexOf(".")?b:b.substring(0,b.indexOf("."));k="";if(0!=g||"#"!=l.substr(l.length-
1)||r){r=new String(Math.abs(g));m=9999;-1!=l.lastIndexOf(",")&&(m=l.length-l.lastIndexOf(",")-1);for(var t=0,g=r.length-1;-1<g;g--)k=r.charAt(g)+k,t++,t==m&&0!=g&&(k=e+k,t=0);if(l.length>k.length&&(g=l.indexOf("0"),-1!=g))for(g=l.length-g,r=l.length-k.length-1;k.length<g;)m=l.charAt(r),","==m&&(m=e),k=m+k,r--}k||-1===l.indexOf("0",l.length-1)||(k="0");q=k+q;0>p&&h&&0<f.length?f=c+f:0>p&&(q=c+q);q.lastIndexOf(d)==q.length-1&&(q=q.substring(0,q.length-1));return f+q+n}
RegExp.quote=function(a){return a.replace(/([.?*+^$[\]\\(){}-])/g,"\\$1")};function pad(a,b,d){return(a+"").length<b?Array(b-(""+a).length+1).join(d)+a:a}function getMillisInHours(a){return a?(0<(0<=a?1:-1)?"":"-")+pad(Math.floor(a/36E5),2,"0"):""}function getMillisInHoursMinutes(a){if("number"!=typeof a)return"";var b=0<=a?1:-1;a=Math.abs(a);var d=Math.floor(a%36E5/6E4);return(0<b?"":"-")+pad(Math.floor(a/36E5),1,"0")+":"+pad(d,2,"0")}
function getMillisInDaysHoursMinutes(a){if(!a)return"";var b=0<=a?1:-1;a=Math.abs(a);var d=Math.floor(a/millisInWorkingDay),e=Math.floor(a%millisInWorkingDay/36E5);a=Math.floor((a-d*millisInWorkingDay-36E5*e)/6E4);return(0<=b?"":"-")+(0<d?d+"  ":"")+pad(e,1,"0")+":"+pad(a,2,"0")}
function millisFromHourMinute(a){a.replace(",",".");var b=a.indexOf(":"),d=a.indexOf(".");if(0>b&&0>d&&5<a.length)return parseInt(a,10);if(-1<d)a=36E5*parseFloat(a);else{var e=0;-1==b?d=parseInt(a,10):(d=parseInt(a.substring(0,b),10),e=parseInt(a.substring(b+1),10));a=36E5*d+6E4*e}"number"!=typeof a&&(a=NaN);return a}
function millisFromString(a,b){if(!a)return 0;var d=RegExp("(\\d+[Yy])|(\\d+[M])|(\\d+[Ww])|(\\d+[Dd])|(\\d+[Hh])|(\\d+[m])|(\\d+[Ss])|(\\d+:\\d+)|(:\\d+)|(\\d*[\\.,]\\d+)|(\\d+)","g"),e=d.exec(a),c=0;if(!e)return NaN;for(;null!=e;){for(var f=1;f<e.length;f++){var h=e[f];if(h){var g=0;try{g=parseInt(h)}catch(n){}1==f?c+=g*(b?millisInWorkingDay*workingDaysPerWeek*52:31536E6):2==f?c+=g*(b?millisInWorkingDay*workingDaysPerWeek*4:2592E6):3==f?c+=g*(b?millisInWorkingDay*workingDaysPerWeek:6048E5):4==f?
c+=g*(b?millisInWorkingDay:864E5):5==f?c+=36E5*g:6==f?c+=6E4*g:7==f?c+=1E3*g:8==f?c+=millisFromHourMinute(h):9==f?c+=millisFromHourMinute(h):10==f?c+=millisFromHourMinute(h):11==f&&(c+=36E5*g)}}e=d.exec(a)}return c}
function daysFromString(a,b){if(a){var d=RegExp("(\\d+[Yy])|(\\d+[Mm])|(\\d+[Ww])|(\\d+[Dd])|(\\d*[\\.,]\\d+)|(\\d+)","g"),e=d.exec(a),c=0;if(!e)return NaN;for(;null!=e;){for(var f=1;f<e.length;f++){var h=e[f];if(h){var g=0;try{g=parseInt(h)}catch(n){}1==f?c+=g*(b?52*workingDaysPerWeek:365):2==f?c+=g*(b?4*workingDaysPerWeek:30):3==f?c+=g*(b?workingDaysPerWeek:7):4==f?c+=g:5==f?c+=g:6==f&&(c+=g)}}e=d.exec(a)}return c}}function stopBubble(a){a.stopPropagation();a.preventDefault();return!1}
function validateField(a){a=$(this);var b=!0;a.clearErrorAlert();var d=a.val();if(d){var e=a.attr("entryType").toUpperCase();"INTEGER"==e?b=isValidInteger(d):"DOUBLE"==e?b=isValidDouble(d):"PERCENTILE"==e?b=isValidDouble(d):"URL"==e?b=isValidURL(d):"EMAIL"==e?b=isValidEmail(d):"DURATIONMILLIS"==e?b=isValidDurationMillis(d):"DURATIONDAYS"==e?b=isValidDurationDays(d):"DATE"==e?b=Date.isValid(d,a.attr("format")):"TIME"==e?b=isValidTime(d):"CURRENCY"==e&&(b=isValidCurrency(d));b||a.createErrorAlert(i18n.ERROR_ON_FIELD,
i18n.INVALID_DATA)}return b}jQuery.fn.clearErrorAlert=function(){this.each(function(){var a=$(this);a.removeAttr("invalid").removeClass("formElementsError");$("#"+a.attr("id")+"error").remove()});return this};
jQuery.fn.createErrorAlert=function(a,b){this.each(function(){var d=$(this);d.attr("invalid","true").addClass("formElementsError");if(0>=$("#"+d.attr("id")+"error").size()){var e=(a?a:"")+": "+(b?b:""),c="<img width='17' heigh='17' id=\""+d.attr("id")+"error\" error='1'",c=$(c+" onclick=\"alert($(this).attr('title'))\" border='0' align='absmiddle'>");c.attr("title",e).attr("src","res/alert.gif");d.after(c)}});return this};
function jsonErrorHandling(a){if(!a.ok){a.message&&alert("ERROR:\n"+a.message);for(var b in a.clientEntryErrors){var d=a.clientEntryErrors[b];$(":input[name="+d.name+"]").createErrorAlert(d.error)}}}jQuery.fn.updateOldValue=function(){this.each(function(){var a=$(this);a.data("_oldvalue",a.val())});return this};jQuery.fn.isValueChanged=function(){var a=!1;this.each(function(){var b=$(this);if(b.val()+""!=b.data("_oldvalue")+"")return a=!0,!1});return a};jQuery.fn.getOldValue=function(){return $(this).data("_oldvalue")};
$.fn.unselectable=function(){this.each(function(){$(this).addClass("unselectable").attr("unselectable","on")});return $(this)};$.fn.clearUnselectable=function(){this.each(function(){$(this).removeClass("unselectable").removeAttr("unselectable")});return $(this)};var __profiler={};
function Profiler(a){this.startTime=(new Date).getTime();this.name=a;this.stop=function(){__profiler[this.name]||(__profiler[this.name]={millis:0,count:0});__profiler[this.name].millis+=(new Date).getTime()-this.startTime;__profiler[this.name].count++};this.display=function(){console.debug(__profiler[this.name])};this.reset=function(){delete __profiler[this.name]}}Profiler.reset=function(){__profiler={}};
Profiler.displayAll=function(){var a="",b;for(b in __profiler)var d=__profiler[b],e="                          ".substr(0,30-b.length),a=a+(b+e+"\t millis:"+d.millis+"\t count:"+d.count+"\n");console.debug(a)};$(document).ready(function(){$(":input[oldValue]").livequery(function(){$(this).updateOldValue()});$(".validated").livequery("blur",validateField)});
function openBlackPopup(a,b,d,e,c){c||(c="bwinPopup");b||(b="900px");d||(d="730px");$("#__blackpopup__").remove();var f=$("<div>").attr("id","__blackpopup__");f.css({position:"fixed",top:0,left:0,width:"100%",height:"100%",textAlign:"center"});window.name!=c&&f.css({backgroundImage:"url('"+contextPath+"/applications/teamwork/images/black_70.png')"});f.append("<iframe id='"+c+"' name='"+c+"' frameborder='0'></iframe>");f.bringToFront();f.bind("close",function(){f.slideUp(300,function(){f.remove();
"function"==typeof e&&e()})});f.bind("destroy",function(){f.remove()});f.find("iframe:first").attr("src",a).css({width:b,height:d,top:100,border:"8px solid #909090",backgroundColor:"#ffffff"});a=$("<div>").css({width:b,position:"relative",height:"5px",textAlign:"right",margin:"auto"});a.append("<img src=\"res/closeBig.png\" style='cursor:pointer;position:absolute;right:-40px;top:30px;'>");a.find("img:first").click(function(){f.trigger("close")});f.prepend(a);$("body").append(f)}
function createBlackPage(a,b,d){a||(a="900px");b||(b="730px");$("#__blackpopup__").remove();var e=$("<div>").attr("id","__blackpopup__");e.css({position:"fixed",top:"0px",paddingTop:"50px",left:0,width:"100%",height:"100%",backgroundImage:"url('res/img/black_70.png')"});e.append("<div id='bwinPopupd' name='bwinPopupd'></div>");e.bringToFront();var c=e.find("#bwinPopupd");c.css({width:a,height:b,top:10,"-moz-box-shadow":"1px 1px 6px #333333",overflow:"auto","-webkit-box-shadow":"1px 1px 6px #333333",
border:"8px solid #777",backgroundColor:"#fff",margin:"auto"});a=$("<div>").css({width:a,position:"relative",height:"0px",textAlign:"right",margin:"auto"});b=$("<img src='res/closeBig.png' style='cursor:pointer;position:absolute;right:-40px;top:5px;' title='close'>");a.append(b);b.click(function(){e.trigger("close")});e.prepend(a);$("body").append(e);e.bind("close",function(){e.slideUp(300,function(){e.remove();"function"==typeof d&&d()})});e.bind("destroy",function(){e.remove()});return c}
function getBlackPopup(){var a=$("#__blackpopup__");"undefined"!=typeof top&&(a=window.parent.$("#__blackpopup__"));return a}function closeBlackPopup(){getBlackPopup().trigger("close")}function openIssueEditorInBlack(a,b,d){b||(b="ED");b=contextPath+"/applications/teamwork/issue/issueEditor.jsp?CM="+b+"&OBJID="+a;d&&(b+=d);openBlackPopup(b,1020,$(window).height()-50,function(){$("#"+a).effect("highlight",{color:"yellow"},1500)})}
function openBoardInBlack(a,b,d,e){b||(b="ED");a=contextPath+"/applications/teamwork/board/boardEditor.jsp?CM="+b+"&OBJID="+a;d&&(a+=d);openBlackPopup(a,$(window).width()-100,$(window).height()-50,e)};
