define("buildspace/apps/Attachment/UploadAttachmentContainer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dijit/Menu dojo/number dijit/CheckedMenuItem dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dijit/focus dojo/html dojo/dom dojo/request/xhr dijit/PopupMenuItem dijit/MenuSeparator dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ViewTenderer dojo/on dojo/text!./templates/attachmentsForm.html".split(" "),
function(f,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,h,k,l,m,K,L,n,b,g,p){var q=f("buildspace.apps.Attachment.AttachmentsForm",[h,k,l,m],{baseClass:"buildspace-form",templateString:p,region:"center",style:"overflow: auto;",nls:b,uploaderUrl:null,startup:function(){this.inherited(arguments);return this.createUploader()},createUploader:function(){var a;a=this;this.uploader=new dojox.form.Uploader({label:b.upload,uploadOnSelect:!0,style:"height:24px;",url:this.uploaderUrl,name:"attachment"});g(this.uploader,
"Begin",function(c){a.pb=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});return a.pb.show()});g(this.uploader,"Complete",function(c){a.attachmentList.refreshGrid();return a.pb.hide()});this.buildspaceFormUploader.appendChild(this.uploader.domNode);return this.uploader.startup()}}),r=f("buildspace.apps.Attachment.AttachmentContainer",dijit.layout.BorderContainer,{style:"padding:0;margin:0;border:none;width:50%;",disableEditing:!1,uploaderUrl:null,attachmentListUrl:null,deleteAttachmentUrl:null,
postCreate:function(){var a=this,c=new n,c=a.attachmentList=new dojox.grid.EnhancedGrid({style:"padding:0px;margin:0px;border-top:none;width:"+(this.disableEditing?"100%":"75%"),region:"center",startup:function(){var c=this;this.on("RowClick",function(b){(b=c.getItem(b.rowIndex))&&!isNaN(parseInt(String(b.id)))?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)})},structure:[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:b.name,field:"name",
width:"auto",formatter:c.downloadCellFormatter},{name:b.uploadedBy,field:"updated_by",width:"180px",styles:"text-align:center;"},{name:b.uploadedAt,field:"updated_at",width:"128px",styles:"text-align:center;"}],store:new dojo.data.ItemFileWriteStore({url:this.attachmentListUrl,clearOnClose:!0}),refreshGrid:function(){this.store.close();this._refresh()}});a.addChild(c);if(!a.disableEditing){c=new dijit.Toolbar({region:"bottom",style:"padding:2px;width:100%;border-bottom:none;border-left:none;border-right:none;"});
c.addChild(a.deleteButton=new dijit.form.Button({label:b.delete,iconClass:"icon-16-container icon-16-container icon-16-delete",disabled:!0,onClick:dojo.hitch(a,"deleteAttachment")}));var d=new q({region:"right",attachmentList:a.attachmentList,style:"width:25%",uploaderUrl:this.uploaderUrl});a.addChild(d);a.addChild(c)}},deleteAttachment:function(){var a=this;if(-1<this.attachmentList.selection.selectedIndex){var c=this,d=c.attachmentList.getItem(this.attachmentList.selection.selectedIndex),e=buildspace.dialog.indeterminateProgressBar({title:b.deleting+
". "+b.pleaseWait+"..."});d&&!isNaN(parseInt(String(d.id)))&&buildspace.dialog.confirm(b.deleteConfirmation,"<div>"+b.firstLevelCategoryDialogMsg+"</div>",75,320,function(){e.show().then(function(){dojo.xhrPost({url:a.deleteAttachmentUrl,content:{id:d.id,"form[_csrf_token]":d._csrf_token},handleAs:"json",load:function(b){b.success&&c.attachmentList.refreshGrid();a.disableToolbarButtons(!0);e.hide()},error:function(a){e.hide()}})})})}},disableToolbarButtons:function(a){this.deleteButton&&this.deleteButton._setDisabledAttr(a)},
close:function(){return this.destroyRecursive()}});return f("buildspace.apps.Attachment.UploadAttachmentContainer",dijit.layout.BorderContainer,{style:"padding:0;margin:0;border:none;width:100%;height:100%;",gutters:!0,item:null,disableEditing:!1,splitter:!0,uploaderUrl:null,attachmentListUrl:null,deleteAttachmentUrl:null,canClose:!0,postCreate:function(){var a=this;this.inherited(arguments);this.uploaderUrl||(this.uploaderUrl="attachment/uploadAttachment/item_id/"+a.item.id+"/item_class/"+a.item.class);
this.attachmentListUrl||(this.attachmentListUrl="attachment/getAttachments/item_id/"+a.item.id+"/item_class/"+a.item.class);this.deleteAttachmentUrl||(this.deleteAttachmentUrl="attachment/deleteAttachment");if(this.canClose){var c=new dijit.Toolbar({region:"top",style:"padding:2px;width:100%;"});c.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-container icon-16-close",style:"float:right;",onClick:dojo.hitch(this,"close")}))}var d=this.attachmentContainer=new r({disableEditing:this.disableEditing,
region:"center",uploaderUrl:this.uploaderUrl,attachmentListUrl:this.attachmentListUrl,deleteAttachmentUrl:this.deleteAttachmentUrl}),e=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});e.show().then(function(){c&&a.addChild(c);a.addChild(d);e.hide()})},close:function(){this.getParent()&&this.canClose&&this.getParent().removeChild(this)},onHide:function(){this.getParent()&&this.canClose&&this.getParent().removeChild(this)}})});
