define("buildspace/apps/ProjectAnalyzerReport/ResourceGrid","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/request dijit/form/Button dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dojo/store/Memory dojo/aspect buildspace/widget/grid/plugins/FormulatedColumn dojox/grid/enhanced/plugins/IndirectSelection buildspace/apps/ProjectAnalyzerReport/plugins/TotalPane buildspace/apps/ProjectAnalyzerReport/MultiRateAnalyzerDialog ./ResourcePrintPreviewDialog/PrintSelectedResourceItemGridDialog ./ResourcePrintPreviewDialog/PrintSelectedTradeItemBillItemGridDialog dojo/i18n!buildspace/nls/ProjectAnalyzer".split(" "),
function(g,h,k,l,m,p,q,n,r,t,u,y,z,A,v,w,e){var x=g("buildspace.apps.ProjectAnalyzerReport.ResourceEnhancedGrid",dojox.grid.EnhancedGrid,{type:null,style:"border-top:none;",rowSelector:"0px",region:"center",updateUrl:null,project:null,unsorted:!1,trade:null,constructor:function(a){"resource"!==a.type&&(this.plugins={indirectSelection:{headerSelector:!0,width:"40px",styles:"text-align: center;"}});this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){this.formulatedColumn=
u(this,{});var a=this,b;a.inherited(arguments);"tradeItem"===a.type?b=a.gridContainer.tradeItemSelectBoxStore:"billItem"===a.type&&(b=a.gridContainer.tradeBillItemSelectBoxStore[a.trade.id[0]]);b&&t.after(a,"_onFetchComplete",function(){a.gridContainer.markedCheckBoxObject(a,b)})},startup:function(){this.inherited(arguments);var a=this;"resource"!==a.type&&(this._connects.push(h.connect(this,"onCellClick",function(b){""===b.cell.name&&a.singleCheckBoxSelection(b)})),this._connects.push(h.connect(this.rowSelectCell,
"toggleAllSelection",function(b){a.toggleAllSelection(b)})))},isInteger:function(a){return 0===a%1}});return g("buildspace.apps.ProjectAnalyzerReport.ResourceGrid",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,project:null,gridOpts:{},pageId:0,type:null,postCreate:function(){var a=this;this.inherited(arguments);k.mixin(a.gridOpts,{project:a.project});var b=new dijit.Toolbar({region:"top",style:"outline:none!important; border-bottom:none; padding:2px; width:100%;"}),
d=this.grid=new x(a.gridOpts);if("trade"===this.gridOpts.type)b.addChild(new m({label:e.print+" "+e.resourceItems,iconClass:"icon-16-container icon-16-print",onClick:function(){a.openSelectedSoRItemPrintPreviewDialog()}})),this.addChild(b);else if("tradeItem"===this.gridOpts.type){var c=new q({style:"display: none;"});c.addChild(new n({label:e.resourceItems,onClick:function(){a.openSelectedSoRItemPrintPreviewDialog()}}));c.addChild(new n({label:e.resourceWithBillItems,onClick:function(){a.openSelectedBillItemPrintPreviewDialog()}}));
b.addChild(new p({label:e.print,iconClass:"icon-16-container icon-16-print",dropDown:c}));this.addChild(b)}else"billItem"===this.gridOpts.type&&(b.addChild(new m({label:e.resourceWithBillItems,iconClass:"icon-16-container icon-16-print",onClick:function(){a.openSelectedBillItemPrintPreviewDialog()}})),this.addChild(b));this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:d,region:"center"}));if(b=dijit.byId("projectAnalyzerReport-resource_project_"+a.project.id+"-stackContainer"))c=
document.createElement("div"),c=new dojox.layout.ContentPane({title:buildspace.truncateString(a.stackContainerTitle,60),id:a.pageId,executeScripts:!0},c),b.addChild(c),c.set("content",a),k.mixin(c,{grid:d}),b.selectChild(a.pageId)},openSelectedSoRItemPrintPreviewDialog:function(){var a=this,b=[];a.gridOpts.gridContainer.tradeItemSelectBoxStore.query().forEach(function(a){b.push(a.id)});var d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});d.show();l.post("resourceProjectAnalyzerReport/getPrintingSelectedTradeItems",
{handleAs:"json",data:{pid:a.project.id,trade_item_ids:JSON.stringify(a.arrayUnique(b)),resourceId:a.resource.id,type:a.type}}).then(function(c){(new v({project:a.project,resourceId:a.resource.id,projectId:a.project.id,title:e.resourceItems,data:c,selectedItems:b,type:a.type})).show();d.hide()},function(a){console.log(a);d.hide()})},openSelectedBillItemPrintPreviewDialog:function(){this.gridOpts.gridContainer.tradeBillItemSelectBoxStore[this.gridOpts.trade.id[0]]||(this.gridOpts.gridContainer.tradeBillItemSelectBoxStore[this.gridOpts.trade.id[0]]=
new r({idProperty:"id"}));var a=this,b=a.gridOpts.gridContainer.tradeBillItemSelectBoxStore[a.gridOpts.trade.id[0]],d=[],c=[];a.gridOpts.gridContainer.tradeItemSelectBoxStore.query().forEach(function(a){d.push(a.id)});b.query().forEach(function(a){c.push(a.id)});var f=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});f.show();l.post("resourceProjectAnalyzerReport/getPrintingSelectedBillItems",{handleAs:"json",data:{pid:a.project.id,resource_id:a.resource.id,trade_id:a.gridOpts.trade.id,
tradeItemIds:JSON.stringify(a.arrayUnique(d)),bill_item_ids:JSON.stringify(a.arrayUnique(c))}}).then(function(b){(new w({project:a.project,title:e.resourceWithBillItems+" ("+a.gridOpts.trade.description+")",data:b,resourceId:a.resource.id,tradeId:a.gridOpts.trade.id,projectId:a.project.id,tradeItemIds:d,selectedItems:c,contractorList:a.contractorList})).show();f.hide()},function(a){console.log(a);f.hide()})},arrayUnique:function(a){return a.reverse().filter(function(a,d,c){return-1===c.indexOf(a,
d+1)}).reverse()}})});
