define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange dojo/_base/event dojo/keys dijit/focus buildspace/widget/grid/cells/Textarea buildspace/widget/grid/Filter buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PredefinedLocationCodeMaintenance dojo/html".split(" "),function(l,q,A,B,C,D,r,t,u,k,E,v,w,d,x){var z=l("buildspace.apps.PredefinedLocationCodeMaintenance.PredefinedLocationCodeGrid",
dojox.grid.EnhancedGrid,{region:"center",style:"border-top:none;",selectedItem:null,keepSelection:!0,rowSelector:"0px",constructor:function(a){this.rearranger=r(this,{})},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments);this.on("RowContextMenu",function(a){this.selection.clear();var b=this.getItem(a.rowIndex);this.selection.setSelected(a.rowIndex,!0);this.contextMenu(a);b&&!isNaN(parseInt(b.id[0]))?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0,["Add"])},
!0);this.on("RowClick",function(a){(a=this.getItem(a.rowIndex))&&!isNaN(parseInt(a.id[0]))?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0,["Add"])})},doApplyCellEdit:function(a,b,c){var f=this,e=this.getItem(b),g=this.store;if(a!==e[c][0]){var h=buildspace.dialog.indeterminateProgressBar({title:d.savingData+". "+d.pleaseWait+"..."}),m={id:e.id,attr_name:c,val:a,_csrf_token:e._csrf_token?e._csrf_token:null},n="systemMaintenance/predefinedLocationCodeUpdate";if(e&&isNaN(parseInt(e.id[0]))){var p=
0<b?this.getItem(b-1):!1;q.mixin(m,{prev_item_id:p?p.id:0});n="systemMaintenance/predefinedLocationCodeAdd"}var y=function(a,b){for(var c in a)e.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(e,c,a[c]);b.save()};h.show().then(function(){dojo.xhrPost({url:n,content:m,handleAs:"json",load:function(a){if(a.success){isNaN(parseInt(e.id[0]))?(g.deleteItem(e),g.save(),dojo.forEach(a.items,function(a){g.newItem(a)}),g.save(),f.disableToolbarButtons(!0)):y(a.data,g);var d=f.getCellByField(c);
window.setTimeout(function(){f.focus.setFocusIndex(b,d.index)},10);h.hide()}},error:function(a){h.hide()}})})}this.inherited(arguments)},canEdit:function(a,b){var c=this;if(void 0!=a){var f=this.getItem(b),e=a.field;if(f&&!isNaN(parseInt(f.id[0]))){if("name"!=e&&a.editable)return window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10),!1}else if("name"!==e)return!1}return this._canEdit},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,
!0)},dodblclick:function(a){this.onRowDblClick(a)},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==u.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},f=this.getItem(a.rowIndex);b&&f&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&x.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),t.stop(a))},contextMenuItems:function(a){(a=this.getItem(a.rowIndex))&&!isNaN(parseInt(a.id[0]))&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:d.addRow,
iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:d.indent,iconClass:"icon-16-container icon-16-indent",onClick:dojo.hitch(this,"indentOutdent","indent")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:d.outdent,iconClass:"icon-16-container icon-16-outdent",onClick:dojo.hitch(this,"indentOutdent","outdent")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",
onClick:dojo.hitch(this,"deleteRow")})))},addRow:function(){k.curNode.blur();k.curNode=null;if(-1<this.selection.selectedIndex){var a=this.selection.selectedIndex,b=this,c,f,e=buildspace.dialog.indeterminateProgressBar({title:d.savingData+". "+d.pleaseWait+"..."}),g=this.store,h=this.getItem(a);isNaN(parseInt(h.id[0]))?(c=0<a?this.getItem(a-1).id:0,f={id:h.id,prev_item_id:c,_csrf_token:h._csrf_token}):(c=0<a?this.getItem(a-1).id:0,f={prev_item_id:c,before_id:h.id,_csrf_token:h._csrf_token});e.show().then(function(){dojo.xhrPost({url:"systemMaintenance/predefinedLocationCodeAdd",
content:f,handleAs:"json",load:function(c){c.success&&dojo.forEach(c.items,function(c){0<c.id&&(c=g.newItem(c),g.save(),c=b.getItemIndex(c),b.rearranger.moveRows([c],a),b.selection.clear())});window.setTimeout(function(){b.selection.setSelected(a,!0);b.focus.setFocusIndex(a,1)},30);e.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);e.hide()}})})}},indentOutdent:function(a){var b=this.getItem(this.selection.selectedIndex);if(0<this.selection.selectedIndex&&b&&!isNaN(parseInt(b.id[0]))){var c=
this,f=c.store,e=buildspace.dialog.indeterminateProgressBar({title:d.recalculateRows+". "+d.pleaseWait+"..."});e.show().then(function(){dojo.xhrPost({url:"indent"==a?"systemMaintenance/predefinedLocationCodeIndent":"systemMaintenance/predefinedLocationCodeOutdent",content:{id:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(a){if(a.success){var c=a.c,d;for(d in a.item)a.item.hasOwnProperty(d)&&d!=f._getIdentifierAttribute()&&f.setValue(b,d,a.item[d]);var g=0;for(a=c.length;g<a;++g)f.fetchItemByIdentity({identity:c[g].id,
onItem:function(a){for(var b in c[g])a.hasOwnProperty(b)&&b!=f._getIdentifierAttribute()&&f.setValue(a,b,c[g][b])}});f.save()}e.hide()},error:function(a){c.selection.clear();c.disableToolbarButtons(!0);e.hide()}})})}},deleteRow:function(){var a=this.selection.selectedIndex,b=this.getItem(a);k.curNode.blur();k.curNode=null;if(-1<this.selection.selectedIndex&&b&&!isNaN(parseInt(b.id[0]))){var c=this,f=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});buildspace.dialog.confirm(d.deletePredefinedLocationCodeConfirmation,
"<div>"+d.doYouReallywantToDelete+" ?</div>",90,320,function(){f.show().then(function(){dojo.xhrPost({url:"systemMaintenance/predefinedLocationCodeDelete",content:{id:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(b){if(b.success){b=b.items;for(var e=c.store,h=0,k=b.length;h<k;++h)e.fetchItemByIdentity({identity:b[h].id,onItem:function(a){e.deleteItem(a);e.save()}});b.length=0;c.selection.clear();window.setTimeout(function(){c.focus.setFocusIndex(a,0)},10);c.disableToolbarButtons(!0)}else buildspace.dialog.alert(d.cannotDeleteTitle,
d.cannotDeleteMsg,90,320);f.hide();c.selectedItem=null;c.pasteOp=null},error:function(a){c.selection.clear();c.disableToolbarButtons(!0);c.selectedItem=null;c.pasteOp=null;f.hide()}})})})}},disableToolbarButtons:function(a,b){var c=dijit.byId("AddLocationCodeRow-button"),d=dijit.byId("DeleteLocationCodeRow-button"),e=dijit.byId("IndentLocationCodeRow-button"),g=dijit.byId("OutdentLocationCodeRow-button");c._setDisabledAttr(a);d._setDisabledAttr(a);e&&e._setDisabledAttr(a);g&&g._setDisabledAttr(a);
a&&b instanceof Array&&dojo.forEach(b,function(a){(a=dijit.byId(a+"LocationCodeRow-button"))&&a._setDisabledAttr(!1)})}});return l("buildspace.apps.PredefinedLocationCodeMaintenance.PredefinedLocationCodeMaintenanceFormContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,postCreate:function(){this.inherited(arguments);var a=new w,a=this.predefinedLocationCodeGrid=new z({store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"systemMaintenance/getPredefinedLocationCodes"}),
structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:d.name,field:"name",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"auto",formatter:{treeCellFormatter:function(a,b){var c=this.grid.getItem(b),d=16*c.level;a=null==a?"&nbsp":a;parseInt(c.level[0])<buildspace.constants.PREDEFINED_LOCATION_CODE_SUB_ELEMENT_LEVEL&&(a="<b>"+a+"</b>");return'<div class="treeNode" style="padding-left:'+d+'px;"><div class="treeContent">'+
a+"&nbsp;</div></div>"}}.treeCellFormatter},{name:d.type,field:"type_txt",styles:"text-align:center;",width:"140px"},{name:d.updatedAt,field:"updated_at",styles:"text-align:center;",width:"120px"}]}),b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({id:"AddLocationCodeRow-button",label:d.addRow,iconClass:"icon-16-container icon-16-add",disabled:!0,onClick:dojo.hitch(a,"addRow")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"IndentLocationCodeRow-button",
label:d.indent,iconClass:"icon-16-container icon-16-indent",style:"outline:none!important;",disabled:!0,onClick:dojo.hitch(a,"indentOutdent","indent")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"OutdentLocationCodeRow-button",label:d.outdent,iconClass:"icon-16-container icon-16-outdent",style:"outline:none!important;",disabled:!0,onClick:dojo.hitch(a,"indentOutdent","outdent")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"DeleteLocationCodeRow-button",
label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:dojo.hitch(a,"deleteRow")}));var c=new v({grid:a,region:"top",filterFields:[{name:d.name,type_txt:d.type}]});this.addChild(c);this.addChild(b);this.addChild(a)}})});
