define("buildspace/apps/Tendering/checkPublishRequirementDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/layout/ContentPane buildspace/widget/grid/cells/Formatter dijit/form/DropDownButton dijit/Menu dijit/DropDownMenu dijit/MenuItem dijit/PopupMenuItem buildspace/apps/AssignUser/assignGroupProjectGrid buildspace/apps/Tendering/newPostContractFormDialog dojo/i18n!buildspace/nls/CheckPublishRequirement".split(" "),
function(k,r,l,D,E,F,t,u,G,H,I,J,v,w,x,m,K,h,p,y,z,b){var A=function(a,d){return 0<a?a:""},B=k("buildspace.apps.Tendering.CheckPublishRequirementGrid",dojox.grid.EnhancedGrid,{type:null,selectedItem:null,dialogWidget:null,escapeHTMLInData:!1,gridData:null,style:"border-top:none;",constructor:function(a){this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments)},destroy:function(){this.inherited(arguments)}}),C=k("buildspace.apps.Tendering.CheckPublishRequirementGridContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",gutters:!1,region:"center",gridOpts:{},postCreate:function(){this.inherited(arguments);r.mixin(this.gridOpts,{region:"center"});var a=this.grid=new B(this.gridOpts);this.addChild(a)}});return k("buildspace.apps.Tendering.CheckPublishRequirementDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:b.checkPublishRequirement,rootProject:null,builderObj:null,tempPublishToPostContractOptions:{},assignGroupProjectGridSavedState:!1,
data:null,buildRendering:function(){var a=this.createForm();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==t.ESCAPE&&dojo.stopEvent(a)},onHide:function(){dojo.forEach(this._connects,l.disconnect);this.destroyRecursive()},createForm:function(){var a=this,d=new dijit.layout.BorderContainer({style:"padding:0px;width:680px;height:240px;",
gutters:!1}),e=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});e.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));e.addChild(new dijit.ToolbarSeparator);e.addChild(new dijit.form.Button({label:b.assignUsersForPostContract,iconClass:"icon-16-container icon-16-add",style:"outline:none!important;",onClick:dojo.hitch(this,"assignUserPermission")}));
var f=new m,c=new m;c.addChild(new h({label:b.withNotListedItem,onClick:function(){a.createPostContractForm(!1,!1)}}));c.addChild(new h({label:b.withoutNotListedItem,onClick:function(){a.createPostContractForm(!1,!0)}}));f.addChild(new p({label:parseInt(String(this.rootProject.tender_type_id))==buildspace.constants.TENDER_TYPE_TENDERED?b.useContractorRates:b.useRationalizedRate,disabled:a.data.requirementSuccess?!1:!0,popup:c}));c=new m;c.addChild(new h({label:b.withNotListedItem,onClick:function(){a.createPostContractForm(!0,
!1)}}));c.addChild(new h({label:b.withoutNotListedItem,onClick:function(){a.createPostContractForm(!0,!0)}}));f.addChild(new p({label:parseInt(String(this.rootProject.tender_type_id))==buildspace.constants.TENDER_TYPE_TENDERED?b.useEstimationRate:b.useOriginalRate,disabled:a.data.requirementSuccess?!1:!0,popup:c}));e.addChild(new dijit.ToolbarSeparator);e.addChild(new x({label:b.publish,iconClass:"icon-16-container icon-16-export",style:"outline:none!important;",dropDown:f}));f=new dijit.layout.BorderContainer({style:"padding:0px;width:400px;height:100px;",
gutters:!1,region:"top"});c=new v({content:b.checkRequirementMsg,region:"center",style:"padding:20px 30px 20px 30px; text-align:center"});var g=new w,n=dojo.data.ItemFileWriteStore({data:a.data.items});g=C({rootProject:a.rootProject,gridOpts:{store:n,dialogWidget:a,structure:[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:A},{name:b.description,field:"notice",width:"auto",styles:"padding:3px 3px 3px 3px;"},{name:b.status,field:"success",styles:"text-align:center;",width:"70px",
formatter:g.boolIconCellFormatter}]}});f.addChild(e);f.addChild(c);d.addChild(f);d.addChild(g);return d},assignUserPermission:function(){var a=this,d=new y({rootProject:this.rootProject,sysName:"PostContract",projectStatus:buildspace.constants.USER_PERMISSION_STATUS_POST_CONTRACT});d.show();d.selectGroup();this._connects.push(l.connect(d,"save",function(){a.assignGroupProjectGridSavedState=!0}));this._connects.push(l.connect(d,"isAdminUpdate",function(){a.assignGroupProjectGridSavedState=!0}))},createPostContractForm:function(a,
d){var e=this,f=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});f.show().then(function(){dojo.xhrGet({url:"tendering/checkIfCanSubmitNewPostContractForm/",content:{project_id:e.rootProject.id},handleAs:"json"}).then(function(c){c.canSubmit?(e.tempPublishToPostContractOptions={useOriginalRate:a,withoutNotListedItem:d,postContractType:buildspace.constants.POST_CONTRACT_TYPE_NEW},(new z({rootProject:e.rootProject,useOriginalRate:a,withoutNotListedItem:d,checkPublishRequirementDialog:e})).show()):
buildspace.dialog.alert(b.warning,c.errorMessage,80,320,function(){});f.hide()})})},sendNewPostContractFormForApproval:function(){var a=this,d=a.builderObj,e=dijit.byId("main-project_breakdown"),f=a.rootProject,c=buildspace.dialog.indeterminateProgressBar({title:b.publishing+". "+b.pleaseWait+"..."});a.hide();var g=a.tempPublishToPostContractOptions.useOriginalRate,n=a.tempPublishToPostContractOptions.withoutNotListedItem;c.show().then(function(){dojo.xhrPost({url:"tendering/sendNewPostContractFormForApproval",
content:{id:f.id,usersAssignedManually:a.assignGroupProjectGridSavedState,use_original_rate:g,withoutNotListedItem:n},handleAs:"json",load:function(q){e.grid.disableButtonsAfterPublish();e.rootProject.tendering_module_locked=[q.tendering_module_locked];d.disableButtonsAfterPublish();c.hide()},error:function(q){c.hide()}})})}})});
