define("buildspace/apps/Tendering/fileBrowserDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!buildspace/nls/FileBrowser dijit/form/ToggleButton dijit/form/RadioButton dojox/grid/enhanced/plugins/Pagination dojox/grid/enhanced/plugins/Filter".split(" "),function(e,f,h,q,r,t,k,l,m,u,d,v,w){var n=e("buildspace.apps.Tendering.FileBrowserGrid",
dojox.grid.EnhancedGrid,{type:null,selectedItem:null,projectId:0,dialogWidget:null,_csrf_token:null,billGrid:null,escapeHTMLInData:!1,style:"border-top:none;",plugins:{pagination:{pageSizes:["20","40","80","All"],description:!0,sizeSwitch:!0,pageStepper:!0,gotoButton:!0,defaultPageSize:20,maxPageStep:4,position:"bottom"},filter:{closeFilterbarButton:!1,ruleCount:5,itemsName:"files"}},constructor:function(b){this.itemIds=[];this.connects=[];this.inherited(arguments)},canSort:function(b){return!1},
postCreate:function(){var b=this;b.inherited(arguments);this.on("RowClick",function(a){(a=b.getItem(a.rowIndex))&&0<a.id?b.disableToolbarButtons(!1):b.disableToolbarButtons(!0)})},dodblclick:function(b){this.onRowDblClick(b)},disableToolbarButtons:function(b){var a=dijit.byId("FileBrowserGrid-"+this.projectId+"deleteFile-button");a&&a._setDisabledAttr(b)},deleteRow:function(b){var a=this,c=a.getItem(b),g=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});g.show();
dojo.xhrPost({url:"tenderingExportFile/deleteFile",content:{id:c.id},handleAs:"json",load:function(c){if(c.success){c=c.items;for(var d=a.store,e=0,f=c.length;e<f;++e)d.fetchItemByIdentity({identity:c[e].id,onItem:function(a){d.deleteItem(a);d.save()}});c.length=0}g.hide();a.selection.clear();window.setTimeout(function(){a.focus.setFocusIndex(b,0)},10);a.disableToolbarButtons(!0);a.selectedItem=null},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;g.hide()}})},
destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,h.disconnect);delete this._connects}}),p=e("buildspace.apps.Tendering.FileBrowserGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,projectId:0,gridOpts:{},postCreate:function(){this.inherited(arguments);f.mixin(this.gridOpts,{type:this.type,projectId:this.projectId,region:"center"});var b=this.grid=new n(this.gridOpts);if("tree"!=this.type){var a=new dijit.Toolbar({region:"top",
style:"padding:2px;border-bottom:none;width:100%;"});a.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(b.dialogWidget,"hide")}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({id:"FileBrowserGrid-"+this.projectId+"deleteFile-button",label:d["delete"],iconClass:"icon-16-container icon-16-trash",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&
b.deleteRow(b.selection.selectedIndex)}}));this.addChild(a)}this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}));if(a=dijit.byId("Tendering-file_browser_"+this.projectId+"_"+this.billElementId+"-stackContainer")){var c=document.createElement("div"),c=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),id:this.pageId,executeScripts:!0},c);a.addChild(c);c.set("content",this);a.selectChild(this.pageId)}}});return e("buildspace.apps.Tendering.FileBrowserDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",title:d.fileBrowser,selectedItem:null,projectId:0,billGrid:null,buildRendering:function(){var b=this.createContent();b.startup();this.content=b;this.inherited(arguments)},postCreate:function(){l.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(b){b.keyCode==k.ESCAPE&&dojo.stopEvent(b)},onHide:function(){this.destroyRecursive()},createContent:function(){var b=new dijit.layout.BorderContainer({style:"padding:0px;width:800px;height:400px;",
gutters:!1}),a=new m,c=dojo.data.ItemFileWriteStore({url:"tenderingExportFile/getFileByProject/id/"+this.projectId}),a=p({stackContainerTitle:d.files,pageId:"fileBrowser-page_library-"+this.projectId,projectId:this.projectId,gridOpts:{store:c,dialogWidget:this,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:d.filename,field:"filename",width:"auto"},{name:d.filetype,field:"file_type",styles:"text-align:center;",width:"80px"},{name:d.updated_at,
field:"updated_at",styles:"text-align:center;",width:"150px"},{name:d.download,field:"downloadPath",styles:"text-align:center;",width:"80px"}]}}),a=this.makeGridContainer(a,d.files);b.addChild(a);return b},makeGridContainer:function(b,a){var c=this.projectId,d=dijit.byId("Tendering-file_browser_"+c+"-stackContainer");d&&dijit.byId("Tendering-file_browser_"+c+"-stackContainer").destroyRecursive();d=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"Tendering-file_browser_"+
c+"-stackContainer"});c=new dijit.layout.ContentPane({title:a,content:b});d.addChild(c);c=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});c.addChild(d);return c}})});
