define("buildspace/apps/Tendering/LogDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/dom dojo/keys dojo/_base/array dojo/dom-style dojo/currency dojo/number dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/Tendering".split(" "),function(h,p,m,y,z,q,r,t,u,n,v,k,d){var w=function(a,c){var b=this.grid.getItem(c),e=16*b.level;a=null==a?"&nbsp":a;b.type<buildspace.apps.Tendering.ProjectStructureConstants.TYPE_BILL&&(a="<b>"+a+"</b>");
return'<div class="treeNode" style="padding-left:'+e+'px;"><div class="treeContent">'+a+"&nbsp;</div></div>"},f=function(a,c,b){c=this.grid.getItem(c);a=n.parse(a);if(isNaN(a)||0==a||null==a)a="&nbsp;";else{var e=b.field.replace("rev_",""),e=n.parse(c[e]),d=u.format(a);a=e==a?d:'<span style="color:#FF0000">'+d+"</span>"}void 0!=c.type&&1>c.type?b.customClasses.push("invalidTypeItemCell"):b.customClasses.push("disable-cell");return a},x=h("buildspace.apps.Tendering.LogGrid",v,{project:null,company:null,
style:"border:none;",region:"center",keepSelection:!0,rowSelector:"0px",currentRev:null,escapeHTMLInData:!1,canSort:function(a){return!1},postCreate:function(){this.inherited(arguments)},dodblclick:function(a){this.onRowDblClick(a)},reload:function(){this.store.close();this._refresh()}}),l=h("buildspace.apps.Tendering.LogGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,project:null,gridOpts:{},pageId:0,currentRev:null,postCreate:function(){this.inherited(arguments);
m.mixin(this.gridOpts,{project:this.project,currentRev:this.currentRev});var a=this.grid=new x(this.gridOpts);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));var c=dijit.byId("BillItemRateLog-"+this.project.id+"-stackContainer");if(c){var b=document.createElement("div"),b=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),id:this.pageId,executeScripts:!0,content:this},b);c.addChild(b);m.mixin(b,{grid:a});c.selectChild(this.pageId)}}});
return h("buildspace.apps.Tendering.LogDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:d.projectLog,project:null,logData:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){t.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==q.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=
this,c=this.borderContainer=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:986px;height:450px;",gutters:!1}),b=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border-right:0px;border-left:0px;border-top:0px;"});b.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));b.addChild(new dijit.ToolbarSeparator);r.forEach(this.logData,function(c,
d){0<c.id&&(b.addChild(new dijit.form.Button({label:c.revision,style:"outline:none!important;",onClick:dojo.hitch(a,"selectRevision",c)})),b.addChild(new dijit.ToolbarSeparator))});c.addChild(b);this.createProjectBreakdownGrid(this.logData[0]);return c},selectRevision:function(a){var c=this.project.id,b=dijit.byId("BillItemRateLog-"+c+"-controllerPane"),c=dijit.byId("BillItemRateLog-"+c+"-stackContainer");b.destroyRecursive();c.destroyRecursive();this.createProjectBreakdownGrid(a)},createProjectBreakdownGrid:function(a){var c=
this,b=new k,b=new l({id:"bill_item_rate_log_bill-"+this.project.id,stackContainerTitle:d.resources,pageId:"bill_item_rate_log_bill-"+this.project.id+"-page",project:this.project,company:this.company,currentRev:a,gridOpts:{store:dojo.data.ItemFileWriteStore({url:"tendering/getLogProjectBreakdown/pid/"+this.project.id+"/prid/"+a.id,clearOnClose:!0}),structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:d.description,field:"title",width:"auto",
formatter:w},{name:d.currentAmount,field:"overall_total_after_markup",width:"150px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:a.revision,field:"rev_overall_total_after_markup",width:"150px",styles:"text-align:right;",formatter:f}],onRowDblClick:function(b){b=this.getItem(b.rowIndex);b.type[0]==buildspace.constants.TYPE_BILL&&c.createElementGrid(b,a)}}}),b=this.makeGridContainer(b,d.bills);this.borderContainer.addChild(b)},createElementGrid:function(a,c){var b=this,
e=new k;new l({id:"bill_item_rate_log_element-"+this.project.id,stackContainerTitle:a.title,pageId:"bill_item_rate_log_element-"+this.project.id+"-page",project:this.project,currentRev:c,gridOpts:{store:dojo.data.ItemFileWriteStore({url:"tendering/getLogElementList/bid/"+a.id+"/prid/"+c.id,clearOnClose:!0}),structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:e.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"},{name:d.grandTotal,field:"overall_total_after_markup",
width:"150px",styles:"text-align:right;",formatter:e.unEditableCurrencyCellFormatter},{name:d.grandTotal+" "+c.revision,field:"rev_overall_total_after_markup",width:"150px",styles:"text-align:right;",formatter:f}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.description[0]&&b.createItemGrid(a,c)}}})},createItemGrid:function(a,c){var b=new k;new l({id:"bill_item_rate_log_item-"+this.project.id,stackContainerTitle:a.description,pageId:"bill_item_rate_log_item-"+this.project.id+
"-page",project:this.project,currentRev:c,gridOpts:{store:dojo.data.ItemFileWriteStore({url:"tendering/getLogItemList/eid/"+a.id+"/prid/"+c.id,clearOnClose:!0}),structure:[{name:d.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,formatter:b.billRefCellFormatter},{name:d.description,field:"description",width:"auto",formatter:b.treeCellFormatter},{name:d.unit,field:"uom_id",width:"50px",styles:"text-align:center;",formatter:b.unitIdCellFormatter,noresize:!0},
{name:d.rate,field:"rate_after_markup",width:"85px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:d.grandTotal,field:"grand_total_after_markup",width:"120px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:d.rate+" "+c.revision,field:"rev_rate_after_markup",width:"85px",styles:"text-align:right;",formatter:f},{name:d.grandTotal+" "+c.revision,field:"rev_grand_total_after_markup",width:"120px",styles:"text-align:right;",formatter:f}]}})},
makeGridContainer:function(a,c){var b=this.project.id,d=dijit.byId("BillItemRateLog-"+b+"-stackContainer");d&&dijit.byId("BillItemRateLog-"+b+"-stackContainer").destroyRecursive();var d=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"BillItemRateLog-"+b+"-stackContainer"}),g=new dijit.layout.ContentPane({title:c,content:a,grid:a.grid});d.addChild(g);var g=new dijit.layout.StackController({region:"top",containerId:"BillItemRateLog-"+b+"-stackContainer"}),
g=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",id:"BillItemRateLog-"+b+"-controllerPane",content:g}),f=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});f.addChild(d);f.addChild(g);dojo.subscribe("BillItemRateLog-"+b+"-stackContainer-selectChild","",function(a){var c=dijit.byId("BillItemRateLog-"+b+"-stackContainer");if(c){var d=c.getChildren(),e=dojo.indexOf(d,a);if(d.length>
e+1){a.grid.store.save();a.grid.store.close();var f=p.after(a.grid,"_onFetchComplete",function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,c.removeChild(d[e]),d[e].destroyRecursive(!0)}});return f}})});
