define("buildspace/apps/Tendering/ScheduleOfRateBillManager","dojo/_base/declare dojo/dom-style dojo/when dijit/layout/ContentPane dojox/grid/EnhancedGrid ./ScheduleOfRateBill/BillPropertiesForm ./ScheduleOfRateBill/BillGrid buildspace/widget/grid/cells/Formatter dojo/aspect dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(g,x,q,l,y,r,m,z,t,h){var u=g("buildspace.apps.Tendering.ScheduleOfRateBillPropertiesContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;margin:0px;border:0px;height:100%;",
gutters:!1,billId:null,billType:null,projectBreakdownGrid:null,billElementGrid:null,postCreate:function(){this.inherited(arguments);var b=this.billPropertiesForm=r({billId:this.billId,projectBreakdownGrid:this.projectBreakdownGrid,billElementGrid:this.billElementGrid});this.addChild(b)}}),w=g("buildspace.apps.Tendering.ScheduleOfRateBillElementContainer",dijit.layout.BorderContainer,{style:"padding:0;margin:0px;border:none;width:100%;height:100%;",gutters:!1,billId:null,rootProject:null,projectBreakdownGrid:null,
postCreate:function(){this.inherited(arguments);this.createElementGrid();var b=this.billId;dojo.subscribe("scheduleOfRateBillGrid"+b+"-stackContainer-selectChild","",function(d){var a=dijit.byId("scheduleOfRateBillGrid"+b+"-stackContainer");if(a){var f=a.getChildren(),e=dojo.indexOf(f,d);e+=1;if(f.length>e){for(;f.length>e;)a.removeChild(f[e]),f[e].destroyDescendants(),f[e].destroyRecursive(),e+=1;if(d.grid){var c=d.grid.selection.selectedIndex;d.grid.store.save();d.grid.store.close();var k=t.after(d.grid,
"_onFetchComplete",function(){k.remove();-1<c&&(this.scrollToRow(c),this.selection.setSelected(c,!0))});d.grid.sort()}}}})},createElementGrid:function(){var b=dijit.byId("scheduleOfRateBillGrid"+this.billId+"-stackContainer");b&&dijit.byId("scheduleOfRateBillGrid"+this.billId+"-stackContainer").destroyRecursive();b=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:"scheduleOfRateBillGrid"+this.billId+"-stackContainer"});var d=dojo.data.ItemFileWriteStore({url:"scheduleOfRateBill/getElementList/id/"+
this.billId,clearOnClose:!0,urlPreventCache:!0}),a=this;try{var f=new m({stackContainerTitle:"Element",billId:a.billId,pageId:"sorb_element-page-"+a.billId,id:"sorb_element-page-container-"+a.billId,editable:this.rootProject.tender_type_id[0]==buildspace.constants.TENDER_TYPE_PARTICIPATED,gridOpts:{store:d,addUrl:"scheduleOfRateBill/elementAdd",updateUrl:"scheduleOfRateBill/elementUpdate",rowUpdateUrl:"scheduleOfRateBill/elementRowUpdate",deleteUrl:"scheduleOfRateBill/elementDelete",pasteUrl:"scheduleOfRateBill/elementPaste",
currentGridType:"element",onRowDblClick:function(c){c=this.getItem(c.rowIndex);0<c.id[0]&&null!==c.description[0]&&""!==c.description[0]&&a.createItemGrid(c,f)}}}),e=new dijit.layout.StackController({region:"top",containerId:"scheduleOfRateBillGrid"+a.billId+"-stackContainer"});a.addChild(b);a.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"scheduleOfRateBillGrid"+a.billId+"-controllerPane",content:e}))}catch(c){console.debug(c)}},
createItemGrid:function(b,d){var a=this,f={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM_TEXT],values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM]},e={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT],
values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER]},c=new dojo.data.ItemFileWriteStore({url:"scheduleOfRateBill/getItemList/id/"+b.id,clearOnClose:!0}),k=dojo.xhrGet({url:"scheduleOfRateBill/getUnits/billId/"+this.billId,handleAs:"json"}),n=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});n.show().then(function(){q(k,function(p){n.hide();try{new m({stackContainerTitle:b.description,billId:a.billId,id:"sorb_item-page-container-"+
a.billId,elementId:b.id,pageId:"sorb_item-page-"+a.billId,type:"tree",editable:a.rootProject.tender_type_id[0]==buildspace.constants.TENDER_TYPE_PARTICIPATED,gridOpts:{store:c,elementGridStore:d,hierarchyTypes:f,hierarchyTypesForHead:e,unitOfMeasurements:p,addUrl:"scheduleOfRateBill/itemAdd",updateUrl:"scheduleOfRateBill/itemUpdate",rowUpdateUrl:"scheduleOfRateBill/itemRowUpdate",deleteUrl:"scheduleOfRateBill/itemDelete",pasteUrl:"scheduleOfRateBill/itemPaste",indentUrl:"scheduleOfRateBill/itemIndent",
outdentUrl:"scheduleOfRateBill/itemOutdent",currentGridType:"item"}})}catch(v){console.debug(v)}},function(p){})})},reconstructBillContainer:function(){dijit.byId("scheduleOfRateBillGrid"+this.billId+"-controllerPane").destroyRecursive();dijit.byId("scheduleOfRateBillGrid"+this.billId+"-stackContainer").destroyRecursive();this.createElementGrid()}});return g("buildspace.apps.Tendering.ScheduleOfRateBillManager",dijit.layout.TabContainer,{region:"center",rootProject:null,nested:!0,style:"padding:0;border:none;margin:0;width:100%;height:100%;",
billId:null,projectBreakdownGrid:null,postCreate:function(){this.inherited(arguments);var b=w({id:"sorb_element_container_"+this.rootProject.id+"-bill-"+this.billId,rootProject:this.rootProject,billId:this.billId,projectBreakdownGrid:this.projectBreakdownGrid});this.addChild(new l({style:"padding:0px;margin:0px;border:0px;width:100%;height:100%;",title:h.elementTradeList,content:b}));this.addChild(new l({style:"padding:0px;margin:0px;border:0px;width:100%;height:100%;",title:h.billProperties,content:new u({billId:this.billId,
projectBreakdownGrid:this.projectBreakdownGrid,billType:this.billType,billElementGrid:null})}))}})});
