define("buildspace/apps/Tendering/SupplyOfMaterialBillManager","dojo/_base/declare dojo/dom-style dojo/when dijit/layout/ContentPane dojox/grid/EnhancedGrid ./SupplyOfMaterial/BillPropertiesForm ./SupplyOfMaterial/BillGrid buildspace/widget/grid/cells/Formatter dojo/aspect dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(g,y,r,l,z,t,m,A,u,h){var v=g("buildspace.apps.Tendering.SupplyOfMaterialBillPropertiesContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;margin:0px;border:0px;height:100%;",
gutters:!1,billId:null,billType:null,projectBreakdownGrid:null,billElementGrid:null,postCreate:function(){this.inherited(arguments);var b=this.billPropertiesForm=t({billId:this.billId,projectBreakdownGrid:this.projectBreakdownGrid,billElementGrid:this.billElementGrid});this.addChild(b)}}),x=g("buildspace.apps.Tendering.SupplyOfMaterialBillElementContainer",dijit.layout.BorderContainer,{style:"padding:0;margin:0px;border:none;width:100%;height:100%;",gutters:!1,billId:null,rootProject:null,projectBreakdownGrid:null,
postCreate:function(){this.inherited(arguments);this.createElementGrid();var b=this.billId;dojo.subscribe("supplyOfMaterialGrid"+b+"-stackContainer-selectChild","",function(d){var a=dijit.byId("supplyOfMaterialGrid"+b+"-stackContainer");if(a){var f=a.getChildren(),e=dojo.indexOf(f,d);e+=1;if(f.length>e){for(;f.length>e;)a.removeChild(f[e]),f[e].destroyDescendants(),f[e].destroyRecursive(),e+=1;if(d.grid){var c=d.grid.selection.selectedIndex;d.grid.store.save();d.grid.store.close();var k=u.after(d.grid,
"_onFetchComplete",function(){k.remove();-1<c&&(this.scrollToRow(c),this.selection.setSelected(c,!0))});d.grid.sort()}}}})},createElementGrid:function(){var b=dijit.byId("supplyOfMaterialGrid"+this.billId+"-stackContainer");b&&dijit.byId("supplyOfMaterialGrid"+this.billId+"-stackContainer").destroyRecursive();b=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:"supplyOfMaterialGrid"+this.billId+"-stackContainer"});var d=dojo.data.ItemFileWriteStore({url:"supplyOfMaterial/getElementList/id/"+
this.billId,clearOnClose:!0,urlPreventCache:!0}),a=this;try{var f=new m({stackContainerTitle:"Element",billId:a.billId,pageId:"som_element-page-"+a.billId,id:"som_element-page-container-"+a.billId,editable:this.rootProject.tender_type_id[0]==buildspace.constants.TENDER_TYPE_PARTICIPATED,gridOpts:{store:d,addUrl:"supplyOfMaterial/elementAdd",updateUrl:"supplyOfMaterial/elementUpdate",rowUpdateUrl:"supplyOfMaterial/elementRowUpdate",deleteUrl:"supplyOfMaterial/elementDelete",pasteUrl:"supplyOfMaterial/elementPaste",
currentGridType:"element",onRowDblClick:function(c){c=this.getItem(c.rowIndex);0<c.id[0]&&null!==c.description[0]&&""!==c.description[0]&&a.createItemGrid(c,f)}}}),e=new dijit.layout.StackController({region:"top",containerId:"supplyOfMaterialGrid"+a.billId+"-stackContainer"});a.addChild(b);a.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"supplyOfMaterialGrid"+a.billId+"-controllerPane",content:e}))}catch(c){console.debug(c)}},
createItemGrid:function(b,d){var a=this,f={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM_TEXT],values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM]},e={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT],
values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER]},c=new dojo.data.ItemFileWriteStore({url:"supplyOfMaterial/getItemList/id/"+b.id+"/bill_id/"+this.billId,clearOnClose:!0}),k=dojo.xhrGet({url:"supplyOfMaterial/getUnits/billId/"+this.billId,handleAs:"json"}),n=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});n.show().then(function(){r(k,function(p){n.hide();try{var q=!1;parseInt(String(a.rootProject.tender_type_id))==
buildspace.constants.TENDER_TYPE_TENDERED&&parseInt(String(a.rootProject.status_id))==buildspace.constants.STATUS_TENDERING&&(q=!0);new m({stackContainerTitle:b.description,billId:a.billId,id:"som_item-page-container-"+a.billId,elementId:b.id,pageId:"som_item-page-"+a.billId,type:"tree",editable:parseInt(String(a.rootProject.tender_type_id))==buildspace.constants.TENDER_TYPE_PARTICIPATED,gridOpts:{store:c,editableDeveloperRate:q,elementGridStore:d,hierarchyTypes:f,hierarchyTypesForHead:e,unitOfMeasurements:p,
addUrl:"supplyOfMaterial/itemAdd",updateUrl:"supplyOfMaterial/itemUpdate",rowUpdateUrl:"supplyOfMaterial/itemRowUpdate",deleteUrl:"supplyOfMaterial/itemDelete",pasteUrl:"supplyOfMaterial/itemPaste",indentUrl:"supplyOfMaterial/itemIndent",outdentUrl:"supplyOfMaterial/itemOutdent",currentGridType:"item"}})}catch(w){console.debug(w)}},function(p){})})},reconstructBillContainer:function(){dijit.byId("supplyOfMaterialGrid"+this.billId+"-controllerPane").destroyRecursive();dijit.byId("supplyOfMaterialGrid"+
this.billId+"-stackContainer").destroyRecursive();this.createElementGrid()}});return g("buildspace.apps.Tendering.SupplyOfMaterialBillManager",dijit.layout.TabContainer,{region:"center",rootProject:null,nested:!0,style:"padding:0;border:none;margin:0;width:100%;height:100%;",billId:null,projectBreakdownGrid:null,postCreate:function(){this.inherited(arguments);var b=x({id:"som_element_container_"+this.rootProject.id+"-bill-"+this.billId,rootProject:this.rootProject,billId:this.billId,bqVersion:0,projectBreakdownGrid:this.projectBreakdownGrid});
this.addChild(new l({style:"padding:0px;margin:0px;border:0px;width:100%;height:100%;",title:h.elementTradeList,content:b}));this.addChild(new l({style:"padding:0px;margin:0px;border:0px;width:100%;height:100%;",title:h.billProperties,content:new v({billId:this.billId,projectBreakdownGrid:this.projectBreakdownGrid,billType:this.billType,billElementGrid:null})}))}})});
