(function(){define("buildspace/apps/RequestForQuotation/ItemList/ItemListContainer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/dom-style dijit/focus dojo/_base/html dojo/request/xhr dijit/Toolbar dijit/form/Button dijit/PopupMenuItem dojo/request dijit/layout/BorderContainer buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/Formatter buildspace/widget/grid/cells/FormulaTextBox ./ProjectResourceDialog ./ResourceLibraryDialog ./RFQItemRemarkDialog buildspace/widget/grid/Filter dojo/i18n!../../../nls/RequestForQuotation".split(" "),
function(m,C,D,E,F,G,r,t,H,I,J,n,K,L,u,k,M,v,w,N,x,O,y,z,A,B,b){var p;p=m("buildspace.apps.RequestForQuotation.ItemList.ItemListGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",rowSelector:"0px",region:"center",rfq:null,constructor:function(a){this.rearranger=r(this,{});return this.formulatedColumn=t(this,{})},canSort:function(a){return!1},noDataMessage:b.noRFQItemAvailableInGrid,postCreate:function(){this.inherited(arguments);return this.on("RowClick",function(a){return(a=this.getItem(a.rowIndex))&&
0<a.id[0]?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0)})},canEdit:function(a,e){var c,d;d=this;if(void 0!==a)if(c=this.getItem(e),0<c.id[0]){if(c.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||c.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N){window.setTimeout(function(){d.edit.cancel();return d.focus.setFocusIndex(e,a.index)},10);return}}else{window.setTimeout(function(){d.edit.cancel();return d.focus.setFocusIndex(e,a.index)},10);return}return this._canEdit},
onRowDblClick:function(a){var e,c,d,f,g;g=this;c=this.getItem(a.rowIndex);e=a.cell.field;f=this.store;return c&&c.rfqItemId&&0<c.rfqItemId[0]&&"remarks"===e?(d=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."}),d.show(),v.post("requestForQuotation/getRFQItemRemarkInformation",{query:{rfqItemId:c.rfqItemId[0],rfqItemRemarkId:c.rfqItemRemarkId[0]},handleAs:"json"}).then(function(a){(new A({title:""+b.itemRemarkDialogTitle,item:c,rfqId:g.rfqId,data:a,rfqItemGridStore:f})).show();
return d.hide()},function(a){return d.hide()})):this.inherited(arguments)},doApplyCellEdit:function(a,e,c){var d,f,g,h;h=this;d=this.getItem(e);return a!==d[c][0]?(f={rfqId:h.rfqId,rfqItemId:d.rfqItemId,val:a,_csrf_token:d._csrf_token?d._csrf_token:null},g=buildspace.dialog.indeterminateProgressBar({title:b.savingData+". "+b.pleaseWait+"..."}),g.show(),dojo.xhrPost({url:"requestForQuotation/updateRFQItemQuantity",content:f,handleAs:"json",load:function(a){var b,f,q,l;if(a.success)for(l=a.items,f=
0,q=l.length;f<q;f++)a=l[f],h.updateStore(d,a);b=h.getCellByField(c);window.setTimeout(function(){return h.focus.setFocusIndex(e,b.index)},10);return g.hide()},error:function(a){return g.hide()}})):h.inherited(arguments)},updateStore:function(a,e){var c,d,b;d=this.store;b=[];for(c in e)a.hasOwnProperty(c)&&c!==d._getIdentifierAttribute()?b.push(d.setValue(a,c,e[c])):b.push(void 0);return b},deleteRow:function(a){var e,c,d,f,g,h;d=this;e=this.getItem(a);f=d.store;c=buildspace.dialog.indeterminateProgressBar({title:b.deleting+
". "+b.pleaseWait+"..."});n.curNode.blur();n.curNode=null;c.show();h={url:"requestForQuotation/deleteRFQItems",content:{rfqId:d.rfqId,resourceItemId:e.id,_csrf_token:e._csrf_token},handleAs:"json",load:function(b){var e,g,h;if(b.success){f=d.store;if(void 0!==b.affected_nodes)for(e=b.affected_nodes,g=0,h=e.length;g<h;g++)b=e[g],f.fetchItemByIdentity({identity:b.id,onItem:function(a){if(a)return f.deleteItem(a),f.save()}});c.hide();d.selection.clear();return window.setTimeout(function(){return d.focus.setFocusIndex(a,
0)},10)}},error:function(a){d.selection.clear();return c.hide()}};e.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||e.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N?(g=b.deleteHeadDialogBoxTitle,e=b.deleteHeadDialogBoxMsg):(g=b.deleteItemDialogBoxTitle,e=b.deleteItemDialogBoxMsg);return new buildspace.dialog.confirm(g,e,80,320,function(){return dojo.xhrPost(h)},function(){return c.hide()})},disableToolbarButtons:function(a,b){var c=dijit.byId("deleteItemListFromRequestForQuotation");
c&&c.set("disabled",a)},refreshGrid:function(){this.store.save();this.store.close();return this.setStore(this.store)}});return m("buildspace.apps.RequestForQuotation.ItemList.ItemListContainer",w,{rfq:null,style:"height:100%;width:100%;padding:0;margin:0;",gutters:!1,postCreate:function(){var a,e,c,d;this.inherited(arguments);c=this;(a=dijit.byId("RequestForQuotationItemListMaintenance-stackContainer"))&&dijit.byId("RequestForQuotationItemListMaintenance-stackContainer").destroyRecursive();a=c.stackContainer=
new dijit.layout.StackContainer({style:"width:100%;height:100%;",region:"center",id:"RequestForQuotationItemListMaintenance-stackContainer"});a=new dojo.data.ItemFileWriteStore({url:"requestForQuotation/getRFQItemListing/rfqId/"+this.rfq.id,clearOnClose:!0,urlPreventCache:!0});e=new p({structure:c.getGridLayout(),store:a,rfqId:this.rfq.id,escapeHTMLInData:!1});d=new u({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border-bottom:none;"});this.rfq.type_id[0]===parseInt(buildspace.constants.RFQ_TYPE_PROJECT)&&
(d.addChild(new k({label:b.rfqCopyFromProjectResource,iconClass:"icon-16-container icon-16-import",onClick:function(){return(new y({title:b.rfqCopyFromProjectResource,projectId:c.rfq.project_id[0],rfqId:c.rfq.id[0],itemListGrid:e})).show()}})),d.addChild(new dijit.ToolbarSeparator));d.addChild(new k({label:b.rfqCopyFromResourceLibrary,iconClass:"icon-16-container icon-16-import",onClick:function(){return(new z({title:b.rfqCopyFromResourceLibrary,rfqId:c.rfq.id[0],itemListGrid:e})).show()}}));d.addChild(new dijit.ToolbarSeparator);
d.addChild(new k({label:b["delete"],id:"deleteItemListFromRequestForQuotation",iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:function(){return e.deleteRow(e.selection.selectedIndex)}}));a=new B({region:"top",grid:e,editableGrid:!1,filterFields:[{description:b.description},{quantity:b.quantity},{uom:b.unit},{remarks:b.remarks}]});this.addChild(a);this.addChild(d);return this.addChild(e)},getGridLayout:function(){var a=new x;return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",
formatter:a.rowCountCellFormatter},{name:b.description,field:"description",width:"auto",formatter:a.treeCellFormatter},{name:b.quantity,field:"quantity",width:"90px",styles:"text-align: right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",editable:!0,formatter:a.rfqQuantityCellFormatter},{name:b.unit,field:"uom",width:"70px",styles:"text-align: center;",formatter:a.rfqUnitCellFormatter},{name:b.remarks,field:"remarks",width:"280px",formatter:a.rfqRemarkCellFormatter}]}})})}).call(this);
