define("buildspace/apps/CostData/ComparisonReport/ComparisonReportDialog","dojo/_base/declare dojo/aspect dojo/_base/array dojo/_base/connect dojo/dom-style dojox/grid/EnhancedGrid dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/Filter ./ComparisonReportPreviewDialog dojo/i18n!buildspace/nls/CostData".split(" "),function(k,m,l,e,n,u,v,p,q,d){var r=k("buildspace.apps.CostData.ComparisonReport.Grid",dojox.grid.EnhancedGrid,{region:"center",style:"border-top:none;",selectedItemIds:[],
canSort:function(b){return!1},constructor:function(b){this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}};this.inherited(arguments)},postCreate:function(){this.inherited(arguments);var b=this;m.after(this,"_onFetchComplete",function(){b.markedCheckBoxObject(b.selectedItemIds,!0)});this._connects.push(e.connect(this,"onSelected",function(a){(a=b.getItem(a))&&0<a.id[0]&&b.pushItemIdIntoGridArray(a,!0)}));this._connects.push(e.connect(this,"onDeselected",function(a){(a=
b.getItem(a))&&0<a.id[0]&&b.pushItemIdIntoGridArray(a,!1)}));this._connects.push(e.connect(this.rowSelectCell,"toggleAllSelection",function(a){b.toggleAllSelection(a)}))},markedCheckBoxObject:function(b,a){var c=this,h=this.store;l.forEach(b,function(f){h.fetchItemByIdentity({identity:f,onItem:function(g){g&&(c.pushItemIdIntoGridArray(g,a),c.rowSelectCell.toggleRow(g._0,a))}})})},pushItemIdIntoGridArray:function(b,a){var c=dojo.indexOf(this.selectedItemIds,b.id[0]);a?-1===c&&this.selectedItemIds.push(b.id[0]):
-1!==c&&this.selectedItemIds.splice(c,1)},toggleAllSelection:function(b){var a=this;var c=a.selection;b?c.selectRange(0,a.rowCount-1):c.deselectAll();return a.store.fetch({onComplete:function(h){dojo.forEach(h,function(f,g){0<f.id&&a.pushItemIdIntoGridArray(f,b)})}})},refreshGrid:function(){this.selection.deselectAll();this.beginUpdate();this.store.close();this._refresh();this.endUpdate()},destroy:function(){this.inherited(arguments);l.forEach(this._connects,e.disconnect);return delete this._connects}}),
t=function(b,a){return parseInt(a)+1};return k("buildspace.apps.CostData.ComparisonReport.Dialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:d.comparisonReport,exportUrl:null,gridUrl:null,costData:null,selectedItemIds:[],level:null,type:null,parentItemId:null,buildRendering:function(){var b=this.createContent();b.startup();this.content=b;this.inherited(arguments)},postCreate:function(){n.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},
onHide:function(){this.destroyRecursive()},createToolbar:function(){var b=this,a=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;width:100%;"});a.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){b.hide()}}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:d.export,iconClass:"icon-16-container icon-16-print",onClick:function(){b.export()}}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:d.preview,
iconClass:"icon-16-container icon-16-print",onClick:function(){b.createPreviewDialog()}}));return a},getGridStructure:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:t},{name:d.name,field:"name",width:"350px"},{name:d.type,field:"type",width:"100px",styles:"text-align: center;"},{name:d.country,field:"country",width:"100px",styles:"text-align: center;"},{name:d.state,field:"state",width:"120px",styles:"text-align: center;"},{name:d.tender_year,field:"tender_year",
width:"120px",styles:"text-align: center;"},{name:d.award_year,field:"award_year",width:"120px",styles:"text-align: center;"}]},createContent:function(){var b=new dijit.layout.BorderContainer({style:"padding:0px;width:800px;height:350px;",gutters:!1}),a=this.grid=r({selectedItemIds:this.selectedItemIds,structure:this.getGridStructure(),store:dojo.data.ItemFileWriteStore({url:this.gridUrl,clearOnClose:!0})});b.addChild(new p({region:"top",grid:a,editableGrid:!1,filterFields:"name type country state tender_year award_year".split(" ")}));
b.addChild(this.createToolbar());b.addChild(a);return b},export:function(){form=document.createElement("form");form.setAttribute("method","post");form.setAttribute("action",this.exportUrl);form.setAttribute("target","_self");costDataId=document.createElement("select");costDataId.setAttribute("name","selected_ids[]");costDataId.setAttribute("multiple","");costDataId.setAttribute("type","hidden");form.appendChild(costDataId);var b;for(b in this.grid.selectedItemIds){var a=document.createElement("option");
a.setAttribute("value",this.grid.selectedItemIds[b]);a.setAttribute("selected","");costDataId.appendChild(a)}document.body.appendChild(form);return form.submit()},createPreviewDialog:function(){var b={};b[this.costData.id]={name:this.costData.name,awarded_date:this.costData.awarded_date,approved_date:this.costData.approved_date,adjusted_date:this.costData.adjusted_date};for(var a in this.grid.selectedItemIds)this.grid.store.fetchItemByIdentity({identity:this.grid.selectedItemIds[a],onItem:function(c){c&&
(b[c.id[0]]={name:c.name[0],awarded_date:c.awarded_date[0],approved_date:c.approved_date[0],adjusted_date:c.adjusted_date[0]})}});(new q({title:d.comparisonReport,costData:this.costData,selectedCostDataInfo:b,selectedItemIds:this.grid.selectedItemIds,parent:this,parentItemId:this.parentItemId,level:this.level,type:this.type})).show()}})});
