<?php namespace PCK\Tenders;

interface TenderStatuses {

	CONST TENDER_STATUS_NOT_YET_SUBMIT = 1;
	CONST TENDER_STATUS_NOT_YET_SUBMIT_TEXT = 'Not Yet Submit';

	CONST TENDER_STATUS_SUBMITTED = 4;
	CONST TENDER_STATUS_SUBMITTED_TEXT = 'Submitted';

	CONST OPEN_TENDER_STATUS_NOT_YET_OPEN = 1;
	CONST OPEN_TENDER_STATUS_NOT_YET_OPEN_TEXT = 'Not Yet Open';

	CONST OPEN_TENDER_STATUS_OPENED = 2;
	CONST OPEN_TENDER_STATUS_OPENED_TEXT = 'Opened';

	CONST TECHNICAL_EVALUATION_STATUS_NOT_STARTED = 1;
	CONST TECHNICAL_EVALUATION_STATUS_STARTED 	  = 2;
	CONST TECHNICAL_EVALUATION_STATUS_ENDED   	  = 4;
	CONST TECHNICAL_EVALUATION_STATUS_OPENED  	  = 8;

}