define("buildspace/apps/TenderingReport/ProjectBreakdown","dojo/_base/declare dojox/grid/EnhancedGrid dojo/request buildspace/widget/grid/cells/Formatter dijit/form/Button dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem ./PrintPreviewFormDialog dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!buildspace/nls/Tendering".split(" "),function(h,m,n,p,q,r,t,u,v,x,c){var w=h("buildspace.apps.TenderingReport.ProjectBreakdownGrid",m,{rootProject:null,explorer:null,style:"border:none;",region:"center",
keepSelection:!0,rowSelector:"0px",constructor:function(a){var b=new p;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;this.structure=[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:k.rowCountCellFormatter},{name:c.description,field:"title",width:"auto",formatter:k.treeCellFormatter},{name:c.originalAmount,field:"original_total",width:"150px",styles:"text-align: right;",formatter:b.unEditableCurrencyCellFormatter},
{name:c.total+" "+c.markup+" (%)",field:"original_total",width:"100px",styles:"text-align: right;",formatter:b.elementTotalMarkupPercentageCellFormatter},{name:c.total+" "+c.markup+" ("+this.currencySetting+")",field:"original_total",width:"120px",styles:"text-align: right;",formatter:b.elementTotalMarkupAmountCellFormatter},{name:c.overallTotal,field:"overall_total_after_markup",width:"150px",styles:"text-align: right;",formatter:b.unEditableCurrencyCellFormatter},{name:"% "+c.project,field:"overall_total_after_markup",
width:"80px",styles:"text-align: center;",formatter:b.projectBreakdownJobPercentageCellFormatter}];this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments);this.on("RowClick",function(a){(a=this.getItem(a.rowIndex))&&0<a.id&&a.type[0]==buildspace.apps.TenderingReport.ProjectStructureConstants.TYPE_BILL?this.disableToolbarButtons(!1,["ExportItemFromBill"],["ImportDropDown"]):this.disableToolbarButtons(!0)},!0)},dodblclick:function(a){this.onRowDblClick(a)},
disableButtonsAfterPublish:function(){},onRowDblClick:function(a){a=this.getItem(a.rowIndex);switch(parseInt(a.type)){case buildspace.apps.TenderingReport.ProjectStructureConstants.TYPE_BILL:a.bill_status[0]==buildspace.apps.TenderingReport.ProjectStructureConstants.BILL_STATUS_OPEN&&this.explorer.initTab(a,{billId:a.id,billLayoutSettingId:a.billLayoutSettingId,explorer:this.explorer,rootProject:this.rootProject})}},disableToolbarButtons:function(a,b){if(a&&b instanceof Array){var d=this;dojo.forEach(b,
function(e){(e=dijit.byId(d.rootProject.id+e+"Row-button"))&&e._setDisabledAttr(!1)})}},reload:function(){this.store.close();this._refresh()}}),k={rowCountCellFormatter:function(a,b){return 0<a?a:""},treeCellFormatter:function(a,b){b=this.grid.getItem(b);var d=16*b.level;a=null==a?"&nbsp":a;b.type<buildspace.apps.TenderingReport.ProjectStructureConstants.TYPE_BILL&&(a="<b>"+a+"</b>");return'<div class="treeNode" style="padding-left:'+d+'px;"><div class="treeContent">'+a+"&nbsp;</div></div>"}};return h("buildspace.apps.TenderingReport.ProjectBreakdown",
dijit.layout.BorderContainer,{region:"center",style:"padding:0px;width:100%;height:100%;",gutters:!1,rootProject:null,explorer:null,grid:null,analysisStatus:null,postCreate:function(){this.inherited(arguments);var a=this,b=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"tendering/getProjectBreakdown/id/"+this.rootProject.id});b=this.grid=new w({rootProject:this.rootProject,explorer:this.explorer,store:b});var d=new dijit.Toolbar({region:"top",style:"border:none;padding:2px;width:100%;"}),e=
new t({style:"display: none;"}),l=this.analysisStatus;dojo.forEach(["resourceAnalysis","scheduleOfRateAnalysis"],function(f){var g=!0;"resourceAnalysis"==f&&!0===l.enable_resource_analysis?g=!1:"scheduleOfRateAnalysis"==f&&1==l.enable_schedule_of_rate_analysis&&(g=!1);g=new u({id:f+"-"+a.rootProject.id+"-menuItem",label:c[f],disabled:g,onClick:function(){buildspace.app.launch({__children:[],icon:"project_analyzer",id:a.rootProject.id+"-project_analyzer",is_app:!0,level:0,sysname:"ProjectAnalyzerReport",
title:c.projectAnalyzer},{type:buildspace.constants.STATUS_TENDERING,opt:f,project:a.rootProject})}});e.addChild(g)});d.addChild(new r({label:c.projectAnalyzer,iconClass:"icon-16-container icon-16-project_analyzer",style:"outline:none!important;",dropDown:e}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new q({label:c.printSummary,iconClass:"icon-16-container icon-16-print",style:"outline:none!important;",onClick:function(){a.openSelectedBillsPrintingFormDialog()}}));switch(a.rootProject.tender_type_id[0]){case buildspace.constants.TENDER_TYPE_TENDERED:d.addChild(new dijit.ToolbarSeparator);
d.addChild(new dijit.form.Button({id:a.rootProject.id+"ViewTendererRow-button",disabled:!parseInt(String(a.rootProject.show_contractor_rates)),label:c.viewTenderers,iconClass:"icon-16-container icon-16-messenger",onClick:function(){buildspace.app.launch({__children:[],icon:"view_tenderer",id:a.rootProject.id+"-view_tenderer",is_app:!0,level:0,sysname:"ViewTendererReport",title:c.viewTenderers},{type:buildspace.constants.STATUS_TENDERING,project:a.rootProject})}}));break;case buildspace.constants.TENDER_TYPE_PARTICIPATED:d.addChild(new dijit.ToolbarSeparator),
d.addChild(new dijit.form.Button({id:a.rootProject.id+"RationalizeRatesRow-button",label:c.compareRationalizedRates,iconClass:"icon-16-container icon-16-list",onClick:function(){buildspace.app.launch({__children:[],icon:"rationalize_rate",id:a.rootProject.id+"-rationalize_rate",is_app:!0,level:0,sysname:"RationalizeRateReport",title:c.compareRationalizedRates},{type:buildspace.constants.STATUS_IMPORT,project:a.rootProject})}}))}d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({id:a.rootProject.id+
"ViewSubPackageRow-button",label:c.subPackages,iconClass:"icon-16-container icon-16-file",onClick:function(f){buildspace.app.launch({__children:[],icon:"project_sub_package",id:a.rootProject.id+"-project_sub_package",is_app:!0,level:0,sysname:"SubPackageReport",title:c.subPackages},{type:buildspace.constants.STATUS_TENDERING,project:a.rootProject})}}));this.addChild(d);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))},openSelectedBillsPrintingFormDialog:function(){var a=
this,b=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});b.show();return n.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(d){(new v({title:c.projectEstimateSummary,projectId:a.rootProject.id,printURL:"projectBuilderReport/printProjectEstimateSummary",exportURL:"projectBuilderReport/exportExcelProjectEstimateSummary",_csrf_token:d._csrf_token})).show();b.hide()},function(d){console.log(d);b.hide()})}})});
