define("buildspace/apps/ScheduleOfQuantity/BuildUpQuantityGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/currency dojo/number dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox dojo/i18n!buildspace/nls/BuildUpQuantityGrid".split(" "),
function(n,p,A,B,C,D,r,t,u,v,E,w,l,x,F,G,H,I,J,d){var z=n("buildspace.apps.scheduleOfQuantity.BuildUp.Grid",dojox.grid.EnhancedGrid,{type:null,scheduleOfQuantityItem:null,style:"border:none!important;",selectedItem:null,unitObj:null,keepSelection:!0,rowSelector:"0px",addUrl:null,editable:!0,updateUrl:null,deleteUrl:null,pasteUrl:null,constructor:function(a){this.rearranger=r(this,{});this.formulatedColumn=t(this,{})},canSort:function(a){return!1},canEdit:function(a,b){return"manual"==this.type?this._canEdit:
!1},postCreate:function(){var a=this;this.inherited(arguments);"manual"==this.type&&this.editable&&(this.on("RowContextMenu",function(b){a.selection.clear();var c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b);c&&0<c.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Add"])},!0),this.on("RowClick",function(b){(b=a.getItem(b.rowIndex))&&0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Add"])}))},doApplyCellEdit:function(a,b,c){var f=this,e=f.getItem(b),
h=f.store;if(a!==e[c][0]){var q=c.replace("-value","");-1!==c.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,b));var k={id:e.id,attr_name:q,val:a,_csrf_token:e._csrf_token?e._csrf_token:null},g=this.updateUrl;e.id==buildspace.constants.GRID_LAST_ROW&&(g=0<b?f.getItem(b-1):!1,p.mixin(k,{prev_item_id:g?g.id:0,relation_id:e.relation_id}),g=this.addUrl);var y=function(a,b){for(var c in a)e.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(e,c,a[c]),dojo.forEach(a.affected_nodes,
function(a){b.fetchItemByIdentity({identity:a.id,onItem:function(c){for(var f in a)e.hasOwnProperty(f)&&f!=b._getIdentifierAttribute()&&b.setValue(c,f,a[f])}})});b.save()},m=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});m.show();dojo.xhrPost({url:g,content:k,handleAs:"json",load:function(a){if(a.success){0<e.id?y(a.data,h):(h.deleteItem(e),h.save(),dojo.forEach(a.items,function(a){h.newItem(a)}),h.save(),f.disableToolbarButtons(!0));"description"!=q&&f.updateTotalBuildUp(a.total_build_up);
var k=f.getCellByField(c);window.setTimeout(function(){f.focus.setFocusIndex(b,k.index)},10)}m.hide()},error:function(a){m.hide()}})}this.inherited(arguments)},dodblclick:function(a){},addRow:function(a){l.curNode.blur();l.curNode=null;var b,c=this,f=buildspace.dialog.indeterminateProgressBar({title:d.addingRow+". "+d.pleaseWait+"..."}),e=this.store;b=this.getItem(a);if(0<b.id)b={before_id:b.id,_csrf_token:b._csrf_token};else{var h=0<a?c.getItem(a-1).id:0;b={id:b.id,prev_item_id:h,relation_id:b.relation_id,
_csrf_token:b._csrf_token}}f.show();dojo.xhrPost({url:this.addUrl,content:b,handleAs:"json",load:function(b){b.success&&dojo.forEach(b.items,function(b){0<b.id&&(b=e.newItem(b),e.save(),b=c.getItemIndex(b),c.rearranger.moveRows([b],a),c.selection.clear())});window.setTimeout(function(){c.selection.setSelected(a,!0);c.focus.setFocusIndex(a,1)},30);f.hide()},error:function(a){c.selection.clear();c.disableToolbarButtons(!0);f.hide()}})},deleteRow:function(a){var b=this,c=this.getItem(a),f=buildspace.dialog.indeterminateProgressBar({title:d.deleting+
". "+d.pleaseWait+"..."});l.curNode.blur();l.curNode=null;f.show();var e={url:this.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(e){if(e.success){var d=e.affected_nodes,k=b.store;k.deleteItem(c);k.save();for(var g=0,h=d.length;g<h;++g)k.fetchItemByIdentity({identity:d[g].id,onItem:function(a){for(var b in d[g])a.hasOwnProperty(b)&&b!=k._getIdentifierAttribute()&&k.setValue(a,b,d[g][b]);k.save()}});b.updateTotalBuildUp(e.total_build_up)}f.hide();b.selection.clear();
window.setTimeout(function(){b.focus.setFocusIndex(a,0)},10);b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;f.hide()}};new buildspace.dialog.confirm(d.deleteBuildUpQtyItemTitle,d.deleteBuildUpQtyItemMsg,80,320,function(){dojo.xhrPost(e)},function(){f.hide()})},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=
this.selection.getFirstSelected();this.pasteOp="copy"},pasteItem:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."}),f=this.store,e=this.selection.getFirstSelected(),h=e.id==buildspace.constants.GRID_LAST_ROW&&0<a?this.getItem(a-1).id:0;c.show();dojo.xhrPost({url:this.pasteUrl,content:{type:b.pasteOp,target_id:e.id,id:b.selectedItem.id,prev_item_id:h,_csrf_token:b.selectedItem._csrf_token},handleAs:"json",load:function(e){var d=[];if(e.success)switch(b.pasteOp){case "cut":f.fetchItemByIdentity({identity:e.data.id,
onItem:function(c){c=b.getItemIndex(c);d.push(c);0<d.length&&b.rearranger.moveRows(d,a);b.selectAfterPaste(c>a?a:a-1,!0)}});break;case "copy":var g=f.newItem(e.data);f.save();g=b.getItemIndex(g);d.push(g);0<d.length&&(b.rearranger.moveRows(d,a),b.selectAfterPaste(a,!1));b.updateTotalBuildUp(e.total_build_up)}b.disableToolbarButtons(!1);b.pasteOp=null;d.length=0;c.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;c.hide()}})},selectAfterPaste:function(a,
b){this.selection.clear();this.selectedItem=null;this.selection.setSelected(a,!0);b&&this.scrollToRow(0<a-3?a-3:a)},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==v.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},d=this.getItem(a.rowIndex);b&&d&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&x.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),u.stop(a))},contextMenuItems:function(a){var b=this.getItem(a.rowIndex);
0<b.id&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:d.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItems")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:d.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(this,"copyItems")})));this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:d.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(this,"pasteItem",a.rowIndex),disabled:this.selectedItem?!1:!0}));this.rowCtxMenu.addChild(new dijit.MenuItem({label:d.addRow,
iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow",a.rowIndex)}));0<b.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow",a.rowIndex)}))},disableToolbarButtons:function(a,b){var c=dijit.byId("builUpGrid-"+this.type+"_"+this.scheduleOfQuantityItem.id+"AddRow-button"),d=dijit.byId("builUpGrid-"+this.type+"_"+this.scheduleOfQuantityItem.id+"DeleteRow-button");c._setDisabledAttr(a);
d._setDisabledAttr(a);if(a&&b instanceof Array){var e=this;dojo.forEach(b,function(a){dijit.byId("builUpGrid-"+e.type+"_"+e.scheduleOfQuantityItem.id+a+"Row-button")._setDisabledAttr(!1)})}},updateTotalBuildUp:function(a){dijit.byId("accPane-"+this.type+"_"+this.scheduleOfQuantityItem.id).set("title",("manual"==this.type?d.manualItems:d.importedItems)+'<span style="color:blue;float:right;">'+w.format(a,{places:2})+"&nbsp;"+this.scheduleOfQuantityItem.uom_symbol+"</span>")}});return n("buildspace.apps.ScheduleOfQuantity.BuildUpQuantityGrid",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:none;",gutters:!1,type:null,scheduleOfQuantityItem:null,gridOpts:{},postCreate:function(){this.inherited(arguments);p.mixin(this.gridOpts,{type:this.type,scheduleOfQuantityItem:this.scheduleOfQuantityItem,region:"center"});var a=this.grid=new z(this.gridOpts);if("manual"==this.type&&this.gridOpts.editable){var b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({id:"builUpGrid-"+
this.type+"_"+this.scheduleOfQuantityItem.id+"AddRow-button",label:d.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.addRow(a.selection.selectedIndex)}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"builUpGrid-"+this.type+"_"+this.scheduleOfQuantityItem.id+"DeleteRow-button",label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<a.selection.selectedIndex?
!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.deleteRow(a.selection.selectedIndex)}}));this.addChild(b)}this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))}})});
