define("buildspace/apps/Gantt/GanttContainer","jquery jqueryui dojo/_base/declare dojo/dom-geometry dojo/dom dojo/json dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem ./TaskEditorDialog dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./templates/gantt.html dojo/text!./templates/readOnlyGantt.html dojo/i18n!buildspace/nls/ProjectManagement".split(" "),function(d,w,f,g,l,m,n,p,h,q,r,t,k,u,b){var v=f("buildspace.apps.Gantt.GanttTemplate",[r,t],{templateString:k,baseClass:"buildspace-form",
region:"center",style:"border:none;padding:0;overflow:hidden;",type:"planView",project:null,projectSchedule:null,nonWorkingDays:null,relativeUrl:relativeUrlRoot,workspaceId:"workSpaceGantt",nls:b,ganttMaster:null,constructor:function(a){this.templateString="planView"==a.type?k:u;this.inherited(arguments)},postCreate:function(){this.inherited(arguments);this.ganttMaster=new GanttMaster;this.ganttMaster.projectScheduleStartDate=new Date(""+this.projectSchedule.start_date[0]+"");this.ganttMaster.calendarSettings=
{satIsHoly:this.nonWorkingDays?this.nonWorkingDays.sat_is_holy:!0,sunIsHoly:this.nonWorkingDays?this.nonWorkingDays.sun_is_holy:!0,holidays:this.nonWorkingDays?this.nonWorkingDays.holidays:""};this.ganttMaster.customTaskEditorCallBack=this.openTaskEditor;this.ganttMaster.projectSchedule=this.projectSchedule;this.ganttMaster.resourceUrl=""+this.relativeUrl+"/css/gantt/res/"},startup:function(){this.inherited(arguments);var a=this,c=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});
c.show().then(function(){dojo.xhrGet({url:"planView"==a.type?"TaskItemList/"+a.projectSchedule.id:"ActualTaskItemList/"+a.projectSchedule.id,handleAs:"json",load:function(b){c.hide();a.initGantt(b)},error:function(a){c.hide()}})})},initGantt:function(a){var b=d("#"+this.workspaceId);this.ganttMaster.init(b);this.ganttMaster.loadProject(a);this.ganttMaster.checkpoint()},initToolbar:function(){var a=new dijit.Toolbar({region:"top",style:"outline:none!important;border:0px;padding:2px;overflow:hidden;"});
if("planView"==this.type){a.addChild(new dijit.form.Button({label:b.insertAbove,iconClass:"icon-16-container icon-16-directional_up",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttInsertAbove")}));a.addChild(new dijit.form.Button({label:b.insertBelow,iconClass:"icon-16-container icon-16-directional_down",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttInsertBelow")}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:b.indent,iconClass:"icon-16-container icon-16-indent",
style:"outline:none!important;",onClick:dojo.hitch(this,"ganttIndent")}));a.addChild(new dijit.form.Button({label:b.outdent,iconClass:"icon-16-container icon-16-outdent",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttOutdent")}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:b.moveUp,iconClass:"icon-16-container icon-16-arrow_up2",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttMoveUp")}));a.addChild(new dijit.form.Button({label:b.moveDown,
iconClass:"icon-16-container icon-16-arrow_down2",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttMoveDown")}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:b.zoomIn,iconClass:"icon-16-container icon-16-zoom_in",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttZoomIn")}));a.addChild(new dijit.form.Button({label:b.zoomOut,iconClass:"icon-16-container icon-16-zoom_out",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttZoomOut")}));
a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:b["delete"],iconClass:"icon-16-container icon-16-delete",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttDelete")}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:b.criticalPath,iconClass:"icon-16-container icon-16-random",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttCriticalPath")}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:b.print,
iconClass:"icon-16-container icon-16-print",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttPrint",buildspace.constants.PROJECT_SCHEDULE_PRINT_TYPE_PLAN)}));a.addChild(new dijit.ToolbarSeparator);var c=new p({style:"display: none;"});c.addChild(new h({label:b.costVsTime,onClick:dojo.hitch(this,"ganttChart")}));c.addChild(new h({label:b.accumulativeCost,onClick:dojo.hitch(this,"ganttAccumulativeChart")}));a.addChild(new n({label:b.charts,iconClass:"icon-16-container icon-16-stats_lines",
dropDown:c}))}else a.addChild(new dijit.form.Button({label:b.zoomIn,iconClass:"icon-16-container icon-16-zoom_in",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttZoomIn")})),a.addChild(new dijit.form.Button({label:b.zoomOut,iconClass:"icon-16-container icon-16-zoom_out",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttZoomOut")})),a.addChild(new dijit.ToolbarSeparator),a.addChild(new dijit.form.Button({label:b.criticalPath,iconClass:"icon-16-container icon-16-random",style:"outline:none!important;",
onClick:dojo.hitch(this,"ganttCriticalPath")})),a.addChild(new dijit.ToolbarSeparator),a.addChild(new dijit.form.Button({label:b.print,iconClass:"icon-16-container icon-16-print",style:"outline:none!important;",onClick:dojo.hitch(this,"ganttPrint",buildspace.constants.PROJECT_SCHEDULE_PRINT_TYPE_ACTUAL)}));return a},ganttInsertAbove:function(){d("#"+this.workspaceId).trigger("addAboveCurrentTask.gantt")},ganttInsertBelow:function(){d("#"+this.workspaceId).trigger("addBelowCurrentTask.gantt")},ganttIndent:function(){d("#"+
this.workspaceId).trigger("indentCurrentTask.gantt")},ganttOutdent:function(){d("#"+this.workspaceId).trigger("outdentCurrentTask.gantt")},ganttMoveUp:function(){d("#"+this.workspaceId).trigger("moveUpCurrentTask.gantt")},ganttMoveDown:function(){d("#"+this.workspaceId).trigger("moveDownCurrentTask.gantt")},ganttZoomIn:function(){d("#"+this.workspaceId).trigger("zoomPlus.gantt")},ganttZoomOut:function(){d("#"+this.workspaceId).trigger("zoomMinus.gantt")},ganttDelete:function(){d("#"+this.workspaceId).trigger("deleteCurrentTask.gantt")},
ganttPrint:function(a){window.open("Gantt/"+a+"/"+this.projectSchedule.id+"/"+this.projectSchedule._csrf_token,"_blank")},ganttChart:function(){window.open("Chart/"+this.projectSchedule.id+"/"+this.projectSchedule._csrf_token,"_blank")},ganttAccumulativeChart:function(){window.open("ChartAccumulativeCost/"+this.projectSchedule.id+"/"+this.projectSchedule._csrf_token,"_blank")},ganttCriticalPath:function(){this.ganttMaster.gantt.showCriticalPath=!this.ganttMaster.gantt.showCriticalPath;this.ganttMaster.redraw()},
ganttSave:function(){if(this.ganttMaster.canWrite){var a=this.ganttMaster.saveProject(),c=this,e=function(){var e=buildspace.dialog.indeterminateProgressBar({title:b.savingData+"..."});e.show().then(dojo.xhrPost({url:"projectManagement/taskItemUpdate",content:{id:c.projectSchedule.id,prj:m.stringify(a),_csrf_token:c.projectSchedule._csrf_token},handleAs:"json",load:function(a){a.data?(c.ganttMaster.loadProject(a.data),c.ganttMaster.checkpoint()):c.ganttMaster.reset();e.hide()},error:function(a){e.hide()}}))};
0<this.ganttMaster.deletedTaskIds.length?buildspace.dialog.confirm(b.deletedTasks,"<div>"+b.tasksThatWillBePermanentlyRemoved+" : "+this.ganttMaster.deletedTaskIds.length+"</div>",80,280,e).show():e()}},openTaskEditor:function(a,b,e){q({ganttMaster:a,task:b,taskRow:e,projectSchedule:a.projectSchedule}).show()},resize:function(){var a=g.getContentBox(this.domNode.parentNode),b=l.byId(this.workspaceId);g.setContentSize(b,{w:a.w-1,h:a.h-38});d("#"+this.workspaceId).trigger("resize.gantt")}});return f("buildspace.apps.Gantt.GanttContainer",
dijit.layout.BorderContainer,{region:"center",style:"padding:0;margin:0;border:none;outline:none;width:100%;height:100%;",gutters:!1,type:"planView",project:null,projectSchedule:null,nonWorkingDays:null,ganttMaster:null,postCreate:function(){var a=this;Date.prototype.isHoliday=function(){a.isHoliday(this)};Date.prototype.incrementDateByWorkingDays=function(a){for(var b=Math.abs(a);0<b;)this.setDate(this.getDate()+(0<a?1:-1)),this.isHoliday()||b--;return this};Date.prototype.distanceInWorkingDays=
function(b){var c=new Date(this.getTime());c.setHours(23,59,59,999);var d=0;b=new Date(b.getTime());b.setHours(23,59,59,999);for(b=b.getTime();c.getTime()<=b;)d+=a.isHoliday(c)?0:1,c.setDate(c.getDate()+1);return d};this.inherited(arguments);var b=new v({type:this.type,project:this.project,projectSchedule:this.projectSchedule,nonWorkingDays:this.nonWorkingDays});this.ganttMaster=b.ganttMaster;this.addChild(b.initToolbar());this.addChild(b)},isHoliday:function(a){var b=this.nonWorkingDays?this.nonWorkingDays.sat_is_holy:
!0,d=this.nonWorkingDays?this.nonWorkingDays.sun_is_holy:!0;pad=function(a){a="0"+a;return a.substr(a.length-2)};var f=this.nonWorkingDays?this.nonWorkingDays.holidays:"",g="#"+a.getFullYear()+"_"+pad(a.getMonth()+1)+"_"+pad(a.getDate())+"#",h="#"+pad(a.getMonth()+1)+"_"+pad(a.getDate())+"#";a=a.getDay();return 6==a&&b||0==a&&d||-1<f.indexOf(g)||-1<f.indexOf(h)}})});
