(function(){define("buildspace/apps/PostContractReport/VariationOrder/PrintSelectedVOItemsDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json dojo/number dojo/currency ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(g,u,v,w,x,y,z,n,p,q,A,e,h,r,t,f){var k,l,m;k=g("buildspace.apps.PostContractReport.VariationOrder.PreviewItemGridFormatter",
null,{additionQtyCellFormatter:function(b,a,c){var d;a=this.grid.getItem(a);d=e.parse(b);b="&nbsp;";a.type&&1>a.type[0]?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");isNaN(d)||0===d||null==d||(b=e.format(d,{places:2}));return a.has_addition_build_up_quantity&&a.has_addition_build_up_quantity[0]?'<span style="color:#0000FF;"><b>'+b+"</b></span>":0<=d?b:'<span style="color:#FF0000">'+b+"</span>"},additionTotalCellFormatter:function(b,a,c){var d;a=this.grid.getItem(a);
d=e.parse(b);b="&nbsp;";d=d*e.parse(a["rate-value"][0])*e.parse(a.total_unit[0]);isNaN(d)||0===d||(b=h.format(d));a.type&&1>a.type[0]?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");return 0<=d?b:'<span style="color:#FF0000">'+b+"</span>"},omissionQtyCellFormatter:function(b,a,c){var d;a=this.grid.getItem(a);d=e.parse(b);b="&nbsp;";a.type&&1>a.type[0]?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");isNaN(d)||0===d||null==d||(b=e.format(d,
{places:2}));return a.has_omission_build_up_quantity&&a.has_omission_build_up_quantity[0]?'<span style="color:#0000FF;"><b>'+b+"</b></span>":0<=d?b:'<span style="color:#FF0000">'+b+"</span>"},omissionTotalCellFormatter:function(b,a,c){var d;a=this.grid.getItem(a);d=e.parse(b);b="&nbsp;";d=d*e.parse(a["rate-value"][0])*e.parse(a.total_unit[0]);isNaN(d)||0===d||(b=h.format(d));a.type&&1>a.type[0]?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");return'<span style="color:#FF0000">'+
b+"</span>"},nettOmissionAdditionCellFormatter:function(b,a,c){a=this.grid.getItem(a);b=e.parse(a["omission_quantity-value"][0])*e.parse(a["rate-value"][0])*e.parse(a.total_unit[0]);a=e.parse(a["addition_quantity-value"][0])*e.parse(a["rate-value"][0])*e.parse(a.total_unit[0]);c.customClasses.push("disable-cell");c=a-b;return 0>c?'<span style="color:#FF0000">'+h.format(c)+"</span>":0===c?"&nbsp;":'<span style="color:#42b449;">'+h.format(c)+"</span>"}});l=g("buildspace.apps.PostContractReport.VariationOrder.SelectedItemGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(b){var a,c;this.inherited(arguments);if(b.node.children[0]&&2<=b.node.children[0].children[0].rows.length)return c=b.node.children[0].children[0].rows[1],a=b.node.children[0].children[0].rows[0].children,c.parentNode.removeChild(c),dojo.forEach(a,function(a,b){var c;c=dojo.attr(a,"rowSpan");if(!c||2>c)return dojo.attr(a,"rowSpan",2)})}});m=g("buildspace.apps.PostContractReport.VariationOrder.SelectedItemGridContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,billId:-1,projectId:-1,selectedItems:[],postCreate:function(){var b,a,c;a=this;a.inherited(arguments);b=this.grid=new l({store:a.store,structure:a.structure,selectedItems:a.selectedItems});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:f.print,iconClass:"icon-16-container icon-16-print",
onClick:function(){return a.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:f.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return a.dialog.hide()}}));a.addChild(c);return a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))},openPrintingDialog:function(b){var a;null==b&&(b=this);a=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});a.show();return q.get("viewTendererReporting/getPrintingInformation",
{handleAs:"json"}).then(function(c){c=new r({title:b.dialog.title,selectedRows:b.selectedItems,printURL:"printReport/printSelectedVOItemsDialog",exportURL:"exportExcelReport/exportSelectedVOItemsDialog",billId:b.billId,projectId:b.projectId,_csrf_token:c._csrf_token});a.hide();return c.show()},function(b){return a.hide()})}});return g("buildspace.apps.PostContractReport.VariationOrder.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,companyId:-1,billId:-1,projectId:-1,
companyName:null,data:null,selectedItems:[],buildRendering:function(){var b;b=this.createContent();b.startup();this.content=b;return this.inherited(arguments)},postCreate:function(){p.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(b){if(b.keyCode===n.ESCAPE)return dojo.stopEvent(b)},onHide:function(){return this.destroyRecursive()},createContent:function(b){var a;null==b&&(b=this);a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",
gutters:!1});b=new m({store:dojo.data.ItemFileWriteStore({data:b.data}),dialog:b,selectedItems:b.selectedItems,structure:b.constructGridStructure(),billId:b.billId,projectId:b.projectId});a.addChild(b);return a},constructGridStructure:function(b){var a,c;c=new t;a=new k;b=[];a={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:c.rowCountCellFormatter,rowSpan:2},{name:f.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",
noresize:!0,formatter:c.billRefCellFormatter,rowSpan:2},{name:f.description,field:"description",width:"500px",formatter:c.postContractPrintPreviewTreeCellFormatter,noresize:!0,rowSpan:2},{name:f.unit,field:"uom_symbol",width:"70px",styles:"text-align:center;",formatter:c.unitIdCellFormatter,noresize:!0,rowSpan:2},{name:f.rate,field:"rate",width:"75px",styles:"text-align:right;color:blue;",formatter:c.unEditableNumberCellFormatter,noresize:!0,rowSpan:2},{name:f.qty,field:"omission_quantity",width:"90px",
styles:"text-align:right;",formatter:a.omissionQtyCellFormatter},{name:f.amount,field:"omission_quantity",width:"120px",styles:"text-align:right;",formatter:a.omissionTotalCellFormatter},{name:f.qty,field:"addition_quantity",width:"90px",styles:"text-align:right;",formatter:a.additionQtyCellFormatter},{name:f.amount,field:"addition_quantity",width:"120px",styles:"text-align:right;",formatter:a.additionTotalCellFormatter}]]};b.push({name:f.omission,styles:"text-align:center;",headerClasses:"staticHeader typeHeader",
colSpan:2});b.push({name:f.addition,styles:"text-align:center;",headerClasses:"staticHeader typeHeader",colSpan:2});a.cells.push(b);return a}})})}).call(this);
