(function(){define("buildspace/apps/PostContractReport/VariationOrder/PrintAllVOItemsWithClaimDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json dojo/number dojo/currency ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(g,u,v,w,x,y,z,n,p,q,A,f,h,r,t,e){var k,l,m;k=g("buildspace.apps.PostContractReport.VariationOrder.PreviewItemGridFormatter",
null,{additionQtyCellFormatter:function(a,b,c){var d;b=this.grid.getItem(b);d=f.parse(a);a="&nbsp;";b.type&&1>b.type[0]?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");isNaN(d)||0===d||null==d||(a=f.format(d,{places:2}));return b.has_addition_build_up_quantity&&b.has_addition_build_up_quantity[0]?'<span style="color:#0000FF;"><b>'+a+"</b></span>":0<=d?a:'<span style="color:#FF0000">'+a+"</span>"},additionTotalCellFormatter:function(a,b,c){var d;b=this.grid.getItem(b);
d=f.parse(a);a="&nbsp;";d=d*f.parse(b["rate-value"][0])*f.parse(b.total_unit[0]);isNaN(d)||0===d||(a=h.format(d));b.type&&1>b.type[0]?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");return 0<=d?a:'<span style="color:#FF0000">'+a+"</span>"},omissionQtyCellFormatter:function(a,b,c){var d;b=this.grid.getItem(b);d=f.parse(a);a="&nbsp;";b.type&&1>b.type[0]?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");isNaN(d)||0===d||null==d||(a=f.format(d,
{places:2}));return b.has_omission_build_up_quantity&&b.has_omission_build_up_quantity[0]?'<span style="color:#0000FF;"><b>'+a+"</b></span>":0<=d?a:'<span style="color:#FF0000">'+a+"</span>"},omissionTotalCellFormatter:function(a,b,c){var d;b=this.grid.getItem(b);d=f.parse(a);a="&nbsp;";d=d*f.parse(b["rate-value"][0])*f.parse(b.total_unit[0]);isNaN(d)||0===d||(a=h.format(d));b.type&&1>b.type[0]?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");return'<span style="color:#FF0000">'+
a+"</span>"},nettOmissionAdditionCellFormatter:function(a,b,c){var d,e;b=this.grid.getItem(b);e=0;d=f.parse(b["omission_quantity-value"][0])*f.parse(b["rate-value"][0])*f.parse(b.total_unit[0]);a=f.parse(b["addition_quantity-value"][0])*f.parse(b["rate-value"][0])*f.parse(b.total_unit[0]);b.type&&1>b.type[0]?c.customClasses.push("invalidTypeItemCell"):(e=a-d,c.customClasses.push("disable-cell"));return 0>e?'<span style="color:#FF0000">'+h.format(e)+"</span>":isNaN(parseFloat(e))||0===e?"&nbsp;":'<span style="color:#42b449;">'+
h.format(e)+"</span>"}});l=g("buildspace.apps.PostContractReport.VariationOrder.SelectedItemGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){var b,c;this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length)return c=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children,c.parentNode.removeChild(c),dojo.forEach(b,function(a,b){var c;c=
dojo.attr(a,"rowSpan");if(!c||2>c)return dojo.attr(a,"rowSpan",2)})}});m=g("buildspace.apps.PostContractReport.VariationOrder.SelectedItemGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,billId:-1,projectId:-1,selectedItems:[],postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new l({store:b.store,structure:b.structure,selectedItems:b.selectedItems});c=new dijit.Toolbar({region:"top",
style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:e.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;
null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});b.show();return q.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new r({title:a.dialog.title,selectedRows:a.selectedItems,printURL:"printReport/printVOItemsWithClaims",exportURL:"exportExcelReport/exportVOItemsWithClaims",billId:a.billId,projectId:a.projectId,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return g("buildspace.apps.PostContractReport.VariationOrder.GroupProjectAssignmentDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,companyId:-1,billId:-1,projectId:-1,companyName:null,data:null,selectedItems:[],buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){p.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===n.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},
createContent:function(a){var b;null==a&&(a=this);b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});a=new m({store:dojo.data.ItemFileWriteStore({data:a.data}),dialog:a,selectedItems:a.selectedItems,structure:a.constructGridStructure(),billId:a.billId,projectId:a.projectId});b.addChild(a);return b},constructGridStructure:function(a){var b,c;c=new t;b=new k;a=[];b={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",
formatter:c.rowCountCellFormatter,rowSpan:2},{name:e.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,formatter:c.billRefCellFormatter,rowSpan:2},{name:e.description,field:"description",width:"500px",formatter:c.postContractPrintPreviewTreeCellFormatter,noresize:!0,rowSpan:2},{name:e.nettOmissionAddition,field:"id",styles:"text-align:right;",width:"120px",noresize:!0,formatter:b.nettOmissionAdditionCellFormatter,rowSpan:2},{name:"%",field:"previous_percentage-value",
styles:"text-align:right;",width:"60px",formatter:c.unEditablePercentageCellFormatter,noresize:!0},{name:e.amount,field:"previous_amount-value",styles:"text-align:right;",width:"120px",formatter:c.unEditableCurrencyCellFormatter,noresize:!0},{name:"%",field:"up_to_date_percentage-value",styles:"text-align:right;",width:"60px",formatter:c.unEditablePercentageCellFormatter,noresize:!0},{name:e.amount,field:"up_to_date_amount-value",styles:"text-align:right;",width:"120px",formatter:c.unEditableCurrencyCellFormatter,
noresize:!0},{name:"%",field:"current_percentage-value",styles:"text-align:right;",width:"60px",formatter:c.unEditablePercentageCellFormatter,noresize:!0},{name:e.amount,field:"current_amount-value",styles:"text-align:right;",width:"120px",formatter:c.unEditableCurrencyCellFormatter,noresize:!0}]]};a.push({name:e.previousPayment,styles:"text-align:center;",headerClasses:"staticHeader typeHeader",colSpan:2});a.push({name:e.workDone,styles:"text-align:center;",headerClasses:"staticHeader typeHeader",
colSpan:2});a.push({name:e.currentPayment,styles:"text-align:center;",headerClasses:"staticHeader typeHeader",colSpan:2});b.cells.push(a);return b}})})}).call(this);
