(function(){define("buildspace/apps/PostContractReport/VariationOrder/PrintAllSelectedVODialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json dojo/number dojo/currency ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(e,t,l,u,v,w,x,m,n,p,y,z,A,q,r,d){var h,k;h=e("buildspace.apps.PostContractReport.VariationOrder.SelectedItemGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){var b,c;this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length)return c=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children,c.parentNode.removeChild(c),dojo.forEach(b,function(a,b){var c;c=dojo.attr(a,"rowSpan");if(!c||2>c)return dojo.attr(a,"rowSpan",2)})}});k=e("buildspace.apps.PostContractReport.VariationOrder.SelectedItemGridContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,billId:-1,projectId:-1,selectedItems:[],postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new h({store:b.store,structure:b.structure,selectedItems:b.selectedItems});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",
onClick:function(){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return p.get("viewTendererReporting/getPrintingInformation",
{handleAs:"json"}).then(function(c){c=new q({title:a.dialog.title,selectedRows:a.selectedItems,printURL:"printReport/printSelectedVO",exportURL:"exportExcelReport/exportSelectedVO",projectId:a.projectId,billId:a.billId,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return e("buildspace.apps.PostContractReport.VariationOrder.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,companyId:-1,billId:-1,projectId:-1,companyName:null,
data:null,selectedItems:[],buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){n.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===m.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(a){var b;null==a&&(a=this);b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",
gutters:!1});a=new k({store:dojo.data.ItemFileWriteStore({data:a.data}),dialog:a,selectedItems:a.selectedItems,structure:a.constructGridStructure(),projectId:a.projectId,billId:a.billId});b.addChild(a);return b},constructGridStructure:function(a){var b,c,g,f,e;null==a&&(a=this);a=new r;e=this.dynamicGridHeaderStructure();g=0;f=[];c={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter,rowSpan:2},{name:d.description,field:"description",
width:"auto",formatter:a.postContractPrintPreviewTreeCellFormatter,noresize:!0,rowSpan:2}]]};b=[{name:d.omission,field_name:"omission",width:"150px",styles:"text-align:right;color:#FF0000;",formatter:a.unEditableCurrencyCellFormatter},{name:d.addition,field_name:"addition",width:"150px",styles:"text-align:right;",formatter:a.unEditableCurrencyCellFormatter}];dojo.forEach(e,function(a){var d,e;d=b.length;g++;f.push({name:a.name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+g,
colSpan:d});d=0;for(e=[];d<b.length;)a={field:b[d].field_name,columnType:"prelimClaimColumn"},l.mixin(a,b[d]),c.cells[0].push(a),e.push(d++);return e});c.cells.push(f);return c},dynamicGridHeaderStructure:function(){var a,b,c,e,f;f=[];e=[{name:d.amount}];b=e.length;for(a=0;a<b;)c={name:e[a].name},f.push(c),a++;return f}})})}).call(this);
