define("buildspace/apps/PostContractReport/VariationOrder/VariationOrderItemContainer","dojo/_base/declare dojo/_base/lang dojo/currency dojo/number dojo/when dojo/aspect dojo/request dijit/layout/TabContainer dijit/layout/ContentPane ./VariationOrderGrid ./buildUpQuantityGrid ./buildUpQuantitySummary ./VariationOrderClaim ./BillDialog buildspace/apps/ProjectBuilder/BillManager/ScheduleOfQuantityGrid buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(t,
x,p,f,y,O,z,A,B,C,D,E,F,G,H,u,c){var I=function(b,a,c){a=this.grid.getItem(a);a.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||a.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||a.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID||a.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY?(c.customClasses.push("disable-cell"),b="&nbsp;"):(0<a.bill_item_id[0]||!a.can_be_edited[0])&&c.customClasses.push("disable-cell");return b},J=function(b,a,c){a=
this.grid.getItem(a);b=f.parse(b);var d="&nbsp;";a.can_be_edited[0]||c.customClasses.push("disable-cell");isNaN(b)||0==b||null==b||(d=f.format(b,{places:2}));a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY||c.customClasses.push("disable-cell");return void 0!=a.has_addition_build_up_quantity&&
a.has_addition_build_up_quantity[0]?'<span style="color:#0000FF;"><b>'+d+"</b></span>":0<=b?d:'<span style="color:#FF0000">'+d+"</span>"},K=function(b,a,c){a=this.grid.getItem(a);var d=f.parse(b);b="&nbsp;";a=0<a.id?d*f.parse(a["rate-value"][0])*f.parse(a.total_unit[0]):0;isNaN(a)||0==a||(b=p.format(a));c.customClasses.push("disable-cell");return 0<=a?b:'<span style="color:#FF0000">'+b+"</span>"},L=function(b,a,c){a=this.grid.getItem(a);b=f.parse(b);var d="&nbsp;";c.customClasses.push("disable-cell");
isNaN(b)||0==b||null==b||(d=f.format(b,{places:2}));return void 0!=a.has_omission_build_up_quantity&&a.has_omission_build_up_quantity[0]?'<span style="color:#0000FF;"><b>'+d+"</b></span>":0<=b?d:'<span style="color:#FF0000">'+d+"</span>"},M=function(b,a,c){a=this.grid.getItem(a);var d=f.parse(b);b="&nbsp;";a=0<a.id?d*f.parse(a["rate-value"][0])*f.parse(a.total_unit[0]):0;isNaN(a)||0==a||(b=p.format(a));c.customClasses.push("disable-cell");return'<span style="color:#FF0000">'+b+"</span>"},N=function(b,
a,c){a=this.grid.getItem(a);b=0<a.id?f.parse(a["omission_quantity-value"][0])*f.parse(a["rate-value"][0])*f.parse(a.total_unit[0]):0;a=0<a.id?f.parse(a["addition_quantity-value"][0])*f.parse(a["rate-value"][0])*f.parse(a.total_unit[0]):0;c.customClasses.push("disable-cell");c=a-b;return 0>c?'<span style="color:#FF0000">'+p.format(c)+"</span>":0==c?"&nbsp;":'<span style="color:#42b449;">'+p.format(c)+"</span>"};return t("buildspace.apps.PostContractReport.VariationOrder.VariationOrderItemContainer",
A,{pageId:"page-00",style:"margin:0px;padding:0px;border:0px;width:100%;height:100%;",gutters:!1,stackContainerTitle:null,gridOpts:{},project:null,variationOrder:null,type:null,gridContainer:null,nested:!0,postCreate:function(){var b=this;b.inherited(arguments);x.mixin(b.gridOpts,{variationOrder:b.variationOrder,project:b.project,type:b.type,region:"center",tabContainerWidget:b});var a=dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}),d=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+
"..."}),l=dojo.xhrGet({url:"variationOrder/getClaimStatus",content:{id:this.variationOrder.id},handleAs:"json"});d.show();y(a,function(a){l.then(function(c){d.hide();b.createVariationOrderItemGrid(a,c,!0);b.createVariationOrderClaimGrid(c)})});if(a=dijit.byId("variationOrder-"+b.project.id+"-stackContainer")){var k=document.createElement("div"),k=new dojox.layout.ContentPane({title:buildspace.truncateString(b.stackContainerTitle,60),id:b.pageId,executeScripts:!0},k);a.addChild(k);k.set("content",
b);a.selectChild(b.pageId)}},createVariationOrderItemGrid:function(b,a,d){var l=dijit.byId("variationOrderItems_tab-"+this.project.id+"_"+this.variationOrder.id+"-StackPane");l||(l=new dijit.layout.StackContainer({id:"variationOrderItems_tab-"+this.project.id+"_"+this.variationOrder.id+"-StackPane",style:"margin:0px;padding:0px;border:0px;width:100%;height:100%;",title:c.variationOrderItems}));var k=dijit.byId("variationOrderReportingItems-"+this.project.id+"_"+this.variationOrder.id+"-borderContainer");
k&&(l.removeChild(k),k.destroyRecursive());var g=this,k=[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM_TEXT],f=[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM],h=new u,m=dojo.data.ItemFileWriteStore({url:"variationOrder/getVariationOrderItemList/id/"+g.variationOrder.id,clearOnClose:!0});b=new C({project:g.project,variationOrder:g.variationOrder,type:0<a.count?
"vo-claims":"vo-items",locked:"true"==g.variationOrder.is_approved[0]?!0:!1,gridOpts:{variationOrder:g.variationOrder,gridContainer:g.gridContainer,store:m,addUrl:"variationOrder/variationOrderItemAdd",updateUrl:0<a.count?"variationOrder/claimItemUpdate":"variationOrder/variationOrderItemUpdate",deleteUrl:"variationOrder/variationOrderItemDelete",indentUrl:"variationOrder/variationOrderItemIndent",outdentUrl:"variationOrder/variationOrderItemOutdent",pasteUrl:"variationOrder/variationOrderItemPaste",
structure:{cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:h.rowCountCellFormatter,noresize:!0,rowSpan:2},{name:c.billReference,field:"bill_ref",styles:"text-align:center; color:red;",width:"80px",formatter:h.unEditableCellFormatter,noresize:!0,rowSpan:2},{name:c.totalUnit,field:"total_unit",styles:"text-align:center;",width:"70px",formatter:I,noresize:!0,rowSpan:2},{name:c.description,field:"description",width:"500px",formatter:h.treeCellFormatter,noresize:!0,rowSpan:2},
{name:c.type,field:"type",width:"70px",styles:"text-align:center;",type:"dojox.grid.cells.Select",options:k,values:f,formatter:h.typeCellFormatter,noresize:!0,rowSpan:2},{name:c.unit,field:"uom_id",width:"70px",styles:"text-align:center;",type:"dojox.grid.cells.Select",options:b.options,values:b.values,formatter:h.unitIdCellFormatter,noresize:!0,rowSpan:2},{name:c.rate,field:"rate-value",styles:"text-align:right;",width:"120px",formatter:h.unEditableCurrencyCellFormatter,noresize:!0,rowSpan:2},{name:c.qty,
field:"omission_quantity-value",styles:"text-align:right;",width:"90px",formatter:L,noresize:!0},{name:c.total,field:"omission_quantity-value",styles:"text-align:right;",width:"120px",formatter:M,noresize:!0},{name:c.qty,field:"addition_quantity-value",styles:"text-align:right;",width:"90px",formatter:J,noresize:!0},{name:c.total,field:"addition_quantity-value",styles:"text-align:right;",width:"120px",formatter:K,noresize:!0},{name:c.nettOmissionAddition,field:"id",styles:"text-align:right;",width:"120px",
noresize:!0,formatter:N,rowSpan:2},{name:"%",field:"previous_percentage-value",styles:"text-align:right;",width:"60px",formatter:h.unEditablePercentageCellFormatter,noresize:!0},{name:c.amount,field:"previous_amount-value",styles:"text-align:right;",width:"120px",formatter:h.unEditableCurrencyCellFormatter,noresize:!0},{name:"%",field:"current_percentage-value",styles:"text-align:right;",width:"60px",formatter:h.unEditablePercentageCellFormatter,noresize:!0},{name:c.amount,field:"current_amount-value",
styles:"text-align:right;",width:"120px",formatter:h.unEditableCurrencyCellFormatter,noresize:!0},{name:"%",field:"up_to_date_percentage-value",styles:"text-align:right;",width:"60px",formatter:h.unEditablePercentageCellFormatter,noresize:!0},{name:c.amount,field:"up_to_date_amount-value",styles:"text-align:right;",width:"120px",formatter:h.unEditableCurrencyCellFormatter,noresize:!0}],[{name:c.omission,field:"id",styles:"text-align:center;",headerClasses:"staticHeader",noresize:!0,colSpan:2},{name:c.addition,
field:"id",styles:"text-align:center;",headerClasses:"staticHeader",noresize:!0,colSpan:2},{name:c.previousClaim,field:"id",styles:"text-align:center;",headerClasses:"staticHeader",noresize:!0,colSpan:2},{name:c.currentClaim,field:"id",styles:"text-align:center;",headerClasses:"staticHeader",noresize:!0,colSpan:2},{name:c.upToDateClaim,field:"id",styles:"text-align:center;",headerClasses:"staticHeader",noresize:!0,colSpan:2}]]},onRowDblClick:function(a){var b=a.cell.field,e=this.getItem(a.rowIndex);
if((this.locked||"omission_quantity-value"==b&&e.has_omission_build_up_quantity[0])&&("addition_quantity-value"==b&&e.has_addition_build_up_quantity[0]||"omission_quantity-value"==b&&e.has_omission_build_up_quantity[0])&&0<e.id&&(e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED))if(0<
e.uom_id[0]){var d=this;a=dojo.xhrGet({url:"billBuildUpQuantity/getDimensionColumnStructure",content:{uom_id:e.uom_id[0]},handleAs:"json"});var h=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."}),k="addition_quantity-value"==b?"addition":"omission";h.show();a.then(function(a){g.createBuildUpQuantityContainer(e,a,k,d.locked);h.hide()},function(a){h.hide()})}else buildspace.dialog.alert(c.buildUpQtyAlert,c.pleaseSetUOM,60,300);"total_unit"==b&&0<e.id&&(e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM||
e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE)&&
G({variationOrderItem:e,variationOrder:g.variationOrder,type:"update_total_unit",locked:"true"==g.variationOrder.is_approved[0]?!0:!1,variationOrderItemGrid:this}).show()},editableCellDblClick:function(a){var b=a.cell.field,e=this.getItem(a.rowIndex);if("addition_quantity-value"==b&&0<e.id&&(e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL||
e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED))if(0<e.uom_id[0]){a=dojo.xhrGet({url:"billBuildUpQuantity/getDimensionColumnStructure",content:{uom_id:e.uom_id[0]},handleAs:"json"});var d=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});d.show();a.then(function(a){g.createBuildUpQuantityContainer(e,a,"addition",!1);d.hide()},function(a){d.hide()})}else buildspace.dialog.alert(c.buildUpQtyAlert,c.pleaseSetUOM,60,300)},singleCheckBoxSelection:function(a){var b=
a.rowIndex;a=this.selection.selected[b];b=this.getItem(b);this.removedIds=[];if(a)return this.gridContainer.voItemSelectedStore.put({id:b.id[0]}),this.getAffectedVOByItems(b,"add");this.gridContainer.voItemSelectedStore.remove(b.id[0]);this.removedIds.push(b.id[0]);return this.getAffectedVOByItems(b,"remove")},toggleAllSelection:function(a){var b=this,c=this.selection;b.removedIds=[];if(a)return c.selectRange(0,b.rowCount-1),b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id&&
b.gridContainer.voItemSelectedStore.put({id:a.id[0]})})}}),b.getAffectedVOByItems(null,"add");c.deselectAll();b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id&&(b.gridContainer.voItemSelectedStore.remove(a.id[0]),b.removedIds.push(a.id[0]))})}});return b.getAffectedVOByItems(null,"remove")},getAffectedVOByItems:function(a,b){var e=this,d=[],h=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});h.show();if("add"===b)e.gridContainer.voItemSelectedStore.query().forEach(function(a){d.push(a.id)});
else for(var g in e.removedIds)d.push(e.removedIds[g]);z.post("variationOrderReporting/getAffectedVOS",{handleAs:"json",data:{pid:e.project.id,item_ids:JSON.stringify(e.gridContainer.arrayUnique(d))}}).then(function(a){var c=dijit.byId("variation_order-"+e.project.id);if("add"===b)for(var d in a){for(var g in a[d])e.gridContainer.voItemSelectedStore.put({id:a[d][g]});c.grid.store.fetchItemByIdentity({identity:d,onItem:function(a){if(a&&0<e.gridContainer.voItemSelectedStore.data.length)return e.gridContainer.voSelectedStore.put({id:d}),
c.grid.rowSelectCell.toggleRow(a._0,!0)}})}else for(d in a){for(g in a[d])e.gridContainer.voItemSelectedStore.remove(a[d][g]);c.grid.store.fetchItemByIdentity({identity:d,onItem:function(a){if(a&&0===e.gridContainer.voItemSelectedStore.data.length)return e.gridContainer.voSelectedStore.remove(d),c.grid.rowSelectCell.toggleRow(a._0,!1)}})}h.hide()},function(a){h.hide();console.log(a)})}}});l.addChild(this.makeItemGridContainer(b,c.variationOrderItems));d&&this.addChild(l)},createBuildUpQuantityContainer:function(b,
a,d,f){f=!0;var k=this,g,q=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;outline:none;",gutters:!1}),h=new dijit.layout.TabContainer({nested:!0,style:"padding:0;border:none;margin:0;width:100%;height:100%;",region:"center"}),m=new u,l=dojo.xhrGet({url:"variationOrder/getLinkInfo/id/"+b.id+"/t/"+d,handleAs:"json"}),p=new dojo.data.ItemFileWriteStore({url:"variationOrder/getBuildUpQuantityItemList/id/"+b.id+"/type/"+d,clearOnClose:!0}),e=[buildspace.constants.SIGN_POSITIVE_TEXT,
buildspace.constants.SIGN_NEGATIVE_TEXT],t=[buildspace.constants.SIGN_POSITIVE,buildspace.constants.SIGN_NEGATIVE],v=!1,w=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});w.show();l.then(function(l){var r=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:m.rowCountCellFormatter},{name:c.description,field:"description",width:"auto",cellType:"buildspace.widget.grid.cells.Textarea"},{name:c.factor,field:"factor-value",width:"100px",styles:"text-align:right;",
cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:m.formulaNumberCellFormatter}];dojo.forEach(a,function(a){r.push({name:a.title,field:a.field_name,width:"100px",styles:"text-align:right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:m.formulaNumberCellFormatter})});r.push({name:c.total,field:"total",width:"100px",styles:"text-align:right;",formatter:m.numberCellFormatter});r.push({name:c.sign,field:"sign",width:"70px",styles:"text-align:center;",cellType:"dojox.grid.cells.Select",
options:e,values:t,formatter:m.signCellFormatter});var n=new E({itemId:b.id,type:d,container:q,hasLinkedQty:l.has_linked_qty,_csrf_token:b._csrf_token,locked:f});l.has_linked_qty&&(v=!0,g=H({title:c.scheduleOfQuantities,BillItem:b,disableEditingMode:!0,stackContainerId:"variationOrderReportingItems-"+k.project.id+"_"+k.variationOrder.id+"-stackContainer",gridOpts:{qtyType:d,buildUpSummaryWidget:n,store:new dojo.data.ItemFileWriteStore({url:"variationOrder/getScheduleOfQuantities/id/"+b.id+"/t/"+d,
clearOnClose:!0}),structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:m.rowCountCellFormatter},{name:c.description,field:"description",width:"auto",formatter:m.treeCellFormatter},{name:c.type,field:"type",width:"70px",styles:"text-align:center;",formatter:m.typeCellFormatter},{name:c.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:m.unitIdCellFormatter},{name:c.qty,field:"quantity-value",width:"100px",styles:"text-align:right;",formatter:m.formulaNumberCellFormatter}]}}));
h.addChild(new D({title:c.manualQtyItems,region:"center",VariationOrderItem:b,type:d,locked:f,gridOpts:{store:p,structure:r,buildUpSummaryWidget:n}}));v&&h.addChild(g);q.addChild(h);q.addChild(n);if(l=dijit.byId("variationOrderReportingItems-"+k.project.id+"_"+k.variationOrder.id+"-stackContainer"))n=document.createElement("div"),n=new dojox.layout.ContentPane({title:buildspace.truncateString(b.description,60)+" ("+c.buildUpQuantity+" - "+b.uom_symbol+")",id:"variationOrderBuildUpQuantityPage-"+b.id,
style:"padding:0px;border:0px;",content:q,grid:g?g.grid:null,executeScripts:!0},n),l.addChild(n),l.selectChild("variationOrderBuildUpQuantityPage-"+b.id);w.hide()})},createVariationOrderClaimGrid:function(b){this.addChild(new B({style:"margin:0px;padding:0px;border:0px;width:100%;height:100%;",title:c.claimRevisions,content:new F({variationOrder:this.variationOrder,variationOrderItemContainer:this,claimStatus:b})}))},makeItemGridContainer:function(b,a){var c=this.project.id+"_"+this.variationOrder.id,
f=dijit.byId("variationOrderReportingItems-"+c+"-stackContainer");f&&f.destroyRecursive();f=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"variationOrderReportingItems-"+c+"-stackContainer"});f.addChild(new dijit.layout.ContentPane({title:a,content:b,grid:b.grid}));var k=new dijit.layout.StackController({region:"top",containerId:"variationOrderReportingItems-"+c+"-stackContainer"}),k=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",
"class":"breadCrumbTrail",region:"top",content:k}),g=dijit.byId("variationOrderReportingItems-"+c+"-borderContainer");g&&g.destroyRecursive(!0);g=new dijit.layout.BorderContainer({id:"variationOrderReportingItems-"+c+"-borderContainer",style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});g.addChild(f);g.addChild(k);dojo.subscribe("variationOrderReportingItems-"+c+"-stackContainer-selectChild","",function(a){var b=dijit.byId("variationOrderReportingItems-"+c+"-stackContainer");
if(b){var d=b.getChildren();a=dojo.indexOf(d,a);a+=1;if(d.length>a)for(;d.length>a;)b.removeChild(d[a]),d[a].destroyDescendants(),d[a].destroyRecursive(),a+=1}});return g}})});
