define("buildspace/apps/Tendering/SupplyOfMaterial/BillGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dijit/Menu dojo/number dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem dijit/MenuSeparator buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),
function(r,t,C,D,E,F,G,H,x,y,I,J,K,L,M,N,O,P,Q,R,z,f){var B=r("buildspace.apps.Tendering.SupplyOfMaterial.BillGrid",dojox.grid.EnhancedGrid,{type:null,billId:-1,elementId:0,itemId:-1,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,rowUpdateUrl:null,deleteUrl:null,deleteRateUrl:null,deleteQuantityUrl:null,pasteUrl:null,indentUrl:null,outdentUrl:null,headerMenu:null,parentGrid:null,elementGridStore:null,editable:!1,
currentGridType:"element",editableDeveloperRate:!1,constructor:function(a){this.type=a.type;this.hierarchyTypes=a.hierarchyTypes;this.hierarchyTypesForHead=a.hierarchyTypesForHead;this.unitOfMeasurements=a.unitOfMeasurements;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;this.editableDeveloperRate=a.editableDeveloperRate;this.editable=a.editable;this.currentGridType=a.currentGridType;this.formatter=new z;this.rearranger=
x(this,{});this.formulatedColumn=y(this,{});this.setColumnStructure()},canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);this.on("RowClick",function(e){a.disableToolbarButtons(!1)})},doApplyCellEdit:function(a,e,b){var c=this,d=c.getItem(e),l=c.store,m=b.replace("-value","");-1!==b.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,e));if(a!==d[b][0]){var p=buildspace.dialog.indeterminateProgressBar({title:f.savingData+". "+f.pleaseWait+"..."}),
u={id:d.id,attr_name:m,val:a,bill_id:c.billId,_csrf_token:d._csrf_token?d._csrf_token:null},v=this.updateUrl;d.id==buildspace.constants.GRID_LAST_ROW&&(m=0<e?c.getItem(e-1):!1,t.mixin(u,{prev_item_id:m?m.id:0,relation_id:d.relation_id}),v=this.addUrl);var A=function(g,h){for(var k in g)d.hasOwnProperty(k)&&k!=h._getIdentifierAttribute()&&h.setValue(d,k,g[k]);"tree"!=c.type&&dojo.forEach(g.other_elements,function(q){h.fetchItemByIdentity({identity:q.id,onItem:function(w){for(var n in q)w.hasOwnProperty(n)&&
n!=h._getIdentifierAttribute()&&h.setValue(w,n,q[n])}})});h.save()};p.show().then(function(){dojo.xhrPost({url:v,content:u,handleAs:"json",load:function(g){if(g.success){0<d.id?A(g.data,l):(l.deleteItem(d),l.save(),dojo.forEach(g.items,function(k){l.newItem(k)}),l.save(),c.disableToolbarButtons(!0));var h=c.getCellByField(b);window.setTimeout(function(){c.focus.setFocusIndex(e,h.index)},10);p.hide()}},error:function(g){p.hide()}})})}c.inherited(arguments)},canEdit:function(a,e){var b=this;if("tree"==
this.type&&void 0!=a){var c=this.getItem(e),d=a.field;if(!this.editable)return!1;if(0<parseInt(String(c.id))){if((c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N)&&"description"!=d&&"type"!=d&&a.editable){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(e,a.index)},10);return}if(c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&"description"!=d&&"type"!=d&&a.editable){window.setTimeout(function(){b.edit.cancel();
b.focus.setFocusIndex(e,a.index)},10);return}"tree"==b.type&&"type"===d&&(d=b.getItem(e+1),(c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N)&&a.editable&&void 0!==d&&parseInt(String(c.level))<parseInt(String(d.level))?(a.options=b.hierarchyTypesForHead.options,a.values=b.hierarchyTypesForHead.values):(a.options=b.hierarchyTypes.options,a.values=b.hierarchyTypes.values))}else if("description"!==d&&"type"!==d)return}return this._canEdit},
doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},setColumnStructure:function(){var a=this.formatter;this.structure="tree"==this.type?[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,rowSpan:2,noresize:!0},{name:f.description,field:"description",width:"auto",formatter:a.treeCellFormatter,rowSpan:2,noresize:!0},{name:f.type,field:"type",width:"70px",styles:"text-align:center;",formatter:a.typeCellFormatter,
rowSpan:2,noresize:!0},{name:f.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:a.unitIdCellFormatter,rowSpan:2,noresize:!0},{name:f.estimatedQty+"<br/>("+f.includeWastage+")<br />(A)",field:"estimated_qty",styles:"text-align:right;",width:"80px",editable:this.editable,cellType:"buildspace.widget.grid.cells.Textarea",formatter:this.editable?a.numberCellFormatter:a.unEditableNumberCellFormatter,rowSpan:2,noresize:!0},{name:"% "+f.ofWastageAllowed,field:"percentage_of_wastage",
styles:"text-align:right;",width:"65px",editable:this.editable,cellType:"buildspace.widget.grid.cells.Textarea",formatter:this.editable?a.numberCellFormatter:a.unEditableNumberCellFormatter,rowSpan:2,noresize:!0},{name:f.contractorRate+"<br />(X)",field:"contractor_supply_rate",styles:"text-align:right;",width:"120px",editable:this.editable,cellType:"buildspace.widget.grid.cells.Textarea",formatter:this.editable?a.currencyCellFormatter:a.unEditableCurrencyCellFormatter,noresize:!0},{name:f.developerRate+
"<br />(Y)",field:"supply_rate",styles:"text-align:right;",editable:this.editableDeveloperRate,width:"120px",cellType:"buildspace.widget.grid.cells.Textarea",formatter:this.editableDeveloperRate?a.currencyCellFormatter:a.unEditableCurrencyCellFormatter,noresize:!0},{name:f.difference+"<br />(B)=(Y)-(X)",field:"difference",styles:"text-align:right;",width:"120px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0},{name:f.amount+" ("+this.currencySetting+")<br />(C)=(A)x(B)",field:"amount",styles:"text-align:right;",
width:"120px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0}],[{name:f.supplyRate+" ("+this.currencySetting+")",field:"id",colSpan:3,styles:"text-align:center;",headerClasses:"staticHeader"}]]:[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0},{name:f.description,field:"description",width:"auto",editable:this.editable,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0},{name:f.total,field:"total",styles:"text-align:right;",
width:"120px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0}]},refreshGrid:function(){this.beginUpdate();this.set("structure",this.structure);this.store.close();this.pluginMgr=new this._pluginMgrClass(this);this.pluginMgr.preInit();this.pluginMgr.postInit();this.pluginMgr.startup();this._refresh();this.endUpdate()},editableCellDblClick:function(a){var e=1<this._click.length&&has("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=this._click[1].rowIndex?this._click[0]:a;
this.focus.setFocusCell(e.cell,e.rowIndex);this.onRowClick(e);this.onRowDblClick(a)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);else this.onCellDblClick(a);else this.onRowDblClick(a)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var e=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children;e.parentNode.removeChild(e);dojo.forEach(b,function(c,d){d=dojo.attr(c,
"rowSpan");(!d||2>d)&&dojo.attr(c,"rowSpan",2)})}},disableToolbarButtons:function(a,e){if(a&&e instanceof Array){var b=this;dojo.forEach(e,function(c){(c=dijit.byId(b.billId+b.elementId+c+"Row-button"))&&c._setDisabledAttr(!1)})}}});return r("buildspace.apps.Tendering.SupplyOfMaterial.BillGridBuilder",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;width:100%;height:100%;border:0px!important;",gutters:!1,stackContainerTitle:"",billId:-1,elementId:0,itemId:-1,rowSelector:null,gridOpts:{},
editable:!1,type:null,postCreate:function(){this.inherited(arguments);t.mixin(this.gridOpts,{editable:this.editable,billId:this.billId,elementId:this.elementId,type:this.type,region:"center",borderContainerWidget:this});var a=this.grid=new B(this.gridOpts);if("tree"!=this.type){var e=this.billId,b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({label:f.printBill,iconClass:"icon-16-container icon-16-print",onClick:function(d){window.open("supplyOfMaterialBill/printBill/id/"+
e,"_blank")}}));this.addChild(b)}this.addChild(a);if(b=dijit.byId("supplyOfMaterialGrid"+this.billId+"-stackContainer")){var c=document.createElement("div");b.addChild(new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),content:this,id:this.pageId,grid:a},c));b.selectChild(this.pageId)}}})});
