(function(){var p={}.hasOwnProperty;define("buildspace/apps/ProjectBuilderReport/BillManager/PrintPreviewDialog/PrintSelectedItemWithBuildUpQtyGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(e,v,w,x,y,z,A,q,r,t,B,u,l,d){var m,n;m=e("buildspace.apps.ProjectBuilderReport.SelectedElementGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){var b,c;this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length)return c=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children,c.parentNode.removeChild(c),dojo.forEach(b,function(a,b){var c;c=dojo.attr(a,"rowSpan");if(!c||2>c)return dojo.attr(a,"rowSpan",2)})}});n=e("buildspace.apps.ProjectBuilderReport.SelectedElementGridContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,billId:-1,selectedItems:[],dialog:null,store:null,structure:null,type:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new m({store:b.store,structure:b.structure});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",onClick:function(a){return b.openPrintingDialog()}}));
c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return t.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=
new u({title:a.dialog.title,billId:a.billId,selectedRows:a.selectedItems,type:a.type,printURL:"projectBuilderBuildUpItemsReports/printSelectedItemsWithBuildUpQty",exportURL:"projectBuilderBuildUpItemsReports/exportExcelSelectedItemsWithBuildUpQty",_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return e("buildspace.apps.ProjectBuilderReport.PrintPreviewReportDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",billId:-1,typeColumns:[],data:null,selectedItems:[],
buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){r.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===q.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(a){var b;null==a&&(a=this);b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",
gutters:!1});new l;a=new n({store:dojo.data.ItemFileWriteStore({data:a.data}),dialog:a,billId:a.billId,structure:a.constructGridStructure(),type:a.type,selectedItems:a.selectedItems});b.addChild(a);return b},constructGridStructure:function(a,b,c){var g,f,e,h,k;null==a&&(a=this.typeColumns);f=new l;k=[];b={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:f.rowCountCellFormatter,noresize:!0,rowSpan:2},{name:d.billReference,field:"bill_ref",styles:"text-align:center; color: red;",
width:"80px",formatter:f.billRefCellFormatter,noresize:!0,rowSpan:2},{name:d.description,field:"description",width:6<Object.keys(a).length?"500px":"auto",formatter:f.printPreviewTreeCellFormatter,noresize:!0,rowSpan:2},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:f.unitIdCellFormatter,noresize:!0,rowSpan:2}]]};for(h in a)p.call(a,h)&&(g=a[h],c=g.use_original_quantity?"quantity_per_unit":"quantity_per_unit_remeasurement",e=g.use_original_quantity?"":" (2)",b.cells[0].push({name:d.qty+
"/"+d.unit+e,field:g.id+"-"+c+"-value",width:"70px",styles:"text-align:right;",formatter:f.billQuantityCellFormatter,noresize:!0}),k.push({name:g.name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader0",noresize:!0}));b.cells.push(k);return b}})})}).call(this);
