define("buildspace/apps/ProjectBuilder/SupplyOfMaterial/BillGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dijit/Menu dojo/number dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem dijit/MenuSeparator buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),
function(x,y,H,I,J,K,L,M,z,A,B,C,w,D,N,O,E,P,Q,R,F,g){var G=x("buildspace.apps.ProjectBuilder.SupplyOfMaterial.BillGrid",dojox.grid.EnhancedGrid,{type:null,billId:-1,elementId:0,itemId:-1,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,rowUpdateUrl:null,deleteUrl:null,deleteRateUrl:null,deleteQuantityUrl:null,pasteUrl:null,indentUrl:null,outdentUrl:null,headerMenu:null,parentGrid:null,elementGridStore:null,currentBillLockedStatus:!1,
currentGridType:"element",constructor:function(a){this.type=a.type;this.hierarchyTypes=a.hierarchyTypes;this.hierarchyTypesForHead=a.hierarchyTypesForHead;this.unitOfMeasurements=a.unitOfMeasurements;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;this.currentBillLockedStatus=a.currentBillLockedStatus;this.currentGridType=a.currentGridType;this.formatter=new F;this.rearranger=z(this,{});this.formulatedColumn=A(this,{});this.setColumnStructure()},
canSort:function(a){return!1},postCreate:function(){var a=this;a.inherited(arguments);this.on("RowContextMenu",function(b){a.selection.clear();a.selection.setSelected(b.rowIndex,!0);a.setupContextMenuAndToolbarButtonRestriction(b);a.contextMenu(b)},!0);this.on("RowClick",function(b){a.setupContextMenuAndToolbarButtonRestriction(b)})},doApplyCellEdit:function(a,b,c){var d=this,e=d.getItem(b),n=d.store,f=c.replace("-value","");-1!==c.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,
b));if(a!==e[c][0]){var h=buildspace.dialog.indeterminateProgressBar({title:g.savingData+". "+g.pleaseWait+"..."}),l={id:e.id,attr_name:f,val:a,bill_id:d.billId,_csrf_token:e._csrf_token?e._csrf_token:null},k=this.updateUrl;e.id==buildspace.constants.GRID_LAST_ROW&&(f=0<b?d.getItem(b-1):!1,y.mixin(l,{prev_item_id:f?f.id:0,relation_id:e.relation_id}),k=this.addUrl);var r=function(p,m){for(var q in p)e.hasOwnProperty(q)&&q!=m._getIdentifierAttribute()&&m.setValue(e,q,p[q]);"tree"!=d.type&&dojo.forEach(p.other_elements,
function(t){m.fetchItemByIdentity({identity:t.id,onItem:function(u){for(var v in t)u.hasOwnProperty(v)&&v!=m._getIdentifierAttribute()&&m.setValue(u,v,t[v])}})});m.save()};h.show().then(function(){dojo.xhrPost({url:k,content:l,handleAs:"json",load:function(p){if(p.success){0<e.id?r(p.data,n):(n.deleteItem(e),n.save(),dojo.forEach(p.items,function(q){n.newItem(q)}),n.save(),d.disableToolbarButtons(!0));var m=d.getCellByField(c);window.setTimeout(function(){d.focus.setFocusIndex(b,m.index)},10);h.hide()}},
error:function(p){h.hide()}})})}d.inherited(arguments)},canEdit:function(a,b){var c=this;if("tree"==this.type&&void 0!=a){var d=this.getItem(b),e=a.field;if(this.currentBillLockedStatus)return!1;if(0<parseInt(String(d.id))){if((d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N)&&"description"!=e&&"type"!=e&&a.editable){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}if(d.type==
buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&"description"!=e&&"type"!=e&&a.editable){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}"tree"==c.type&&"type"===e&&(e=c.getItem(b+1),(d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N)&&a.editable&&void 0!==e&&parseInt(String(d.level))<parseInt(String(e.level))?(a.options=c.hierarchyTypesForHead.options,a.values=c.hierarchyTypesForHead.values):
(a.options=c.hierarchyTypes.options,a.values=c.hierarchyTypes.values))}else if("description"!==e&&"type"!==e)return}return this._canEdit},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},setColumnStructure:function(){var a=this.formatter,b=!0;this.currentBillLockedStatus&&(b=!1);if("tree"==this.type){var c=this.unitOfMeasurements,d=this.hierarchyTypes;this.structure=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",
formatter:a.rowCountCellFormatter,noresize:!0},{name:g.description,field:"description",width:"auto",editable:b,cellType:"buildspace.widget.grid.cells.Textarea",formatter:a.treeCellFormatter,noresize:!0},{name:g.type,field:"type",width:"70px",styles:"text-align:center;",editable:b,type:"dojox.grid.cells.Select",options:d.options,values:d.values,formatter:a.typeCellFormatter,noresize:!0},{name:g.unit,field:"uom_id",width:"70px",editable:b,styles:"text-align:center;",type:"dojox.grid.cells.Select",options:c.options,
values:c.values,formatter:a.unitIdCellFormatter,noresize:!0},{name:g.supplyRate+" ("+this.currencySetting+")",field:"supply_rate",styles:"text-align:right;",width:"120px",editable:b,cellType:"buildspace.widget.grid.cells.Textarea",formatter:a.currencyCellFormatter,noresize:!0}]}else this.structure=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0},{name:g.description,field:"description",width:"auto",editable:b,cellType:"buildspace.widget.grid.cells.Textarea",
noresize:!0},{name:g.total,field:"total",styles:"text-align:right;",width:"120px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0}]},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="copy"},pasteItem:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."}),d=this.store,e=this.selection.getFirstSelected(),n=e.id==buildspace.constants.GRID_LAST_ROW&&
0<a?this.getItem(a-1).id:0;c.show().then(function(){dojo.xhrPost({url:b.pasteUrl,content:{type:b.pasteOp,target_id:e.id,prev_item_id:n,id:b.selectedItem.id,_csrf_token:b.selectedItem._csrf_token},handleAs:"json",load:function(f){var h=[];if(f.success){var l=f.c;switch(b.pasteOp){case "cut":d.fetchItemByIdentity({identity:f.data.id,onItem:function(m){m=b.getItemIndex(m);h.push(m);for(var q=0,t=l.length;q<t;++q)d.fetchItemByIdentity({identity:l[q].id,onItem:function(u){u=b.getItemIndex(u);h.push(u)}});
0<h.length&&b.rearranger.moveRows(h,a);b.selectAfterPaste(m>a?a:a-1,!0)}});d.fetchItemByIdentity({identity:f.data.id,onItem:function(m){for(var q in f.data)m.hasOwnProperty(q)&&q!=d._getIdentifierAttribute()&&d.setValue(m,q,f.data[q]);d.save();var t=0;for(m=l.length;t<m;++t)d.fetchItemByIdentity({identity:l[t].id,onItem:function(u){for(var v in l[t])u.hasOwnProperty(v)&&v!=d._getIdentifierAttribute()&&d.setValue(u,v,l[t][v]);d.save()}})}});break;case "copy":var k=d.newItem(f.data);d.save();k=b.getItemIndex(k);
h.push(k);k=0;for(var r=l.length;k<r;++k){var p=d.newItem(l[k]);d.save();p=b.getItemIndex(p);h.push(p)}0<h.length&&(b.rearranger.moveRows(h,a),b.selectAfterPaste(a,!1))}}b.pasteOp=null;h.length=0;c.hide()},error:function(f){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;c.hide()}})})},selectAfterPaste:function(a,b){this.selection.clear();this.selectedItem=null;this.selection.setSelected(a,!0);b&&this.scrollToRow(0<a-3?a-3:a)},pasteCell:function(a,b){var c=this,
d=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."}),e=this.store,n=this.selection.getFirstSelected();d.show().then(function(){dojo.xhrPost({url:c.pasteUrl,content:{target_id:n.id,id:c.selectedItem.id,_csrf_token:c.selectedItem._csrf_token},handleAs:"json",load:function(f){if(f.success){var h=f.c;e.fetchItemByIdentity({identity:f.data.id,onItem:function(l){for(var k in f.data)l.hasOwnProperty(k)&&k!=e._getIdentifierAttribute()&&e.setValue(l,k,f.data[k]);e.save();var r=0;for(l=
h.length;r<l;++r)e.fetchItemByIdentity({identity:h[r].id,onItem:function(p){for(var m in h[r])p.hasOwnProperty(m)&&m!=e._getIdentifierAttribute()&&e.setValue(p,m,h[r][m]);e.save()}})}})}c.selection.clear();c.disableToolbarButtons(!0);c.selectedItem=null;d.hide()},error:function(f){c.selection.clear();c.disableToolbarButtons(!0);c.selectedItem=null;d.hide()}})})},addRow:function(a){w.curNode.blur();w.curNode=null;var b=this,c=buildspace.dialog.indeterminateProgressBar({title:g.addingRow+". "+g.pleaseWait+
"..."}),d=b.store,e=b.getItem(a),n=b.billId;if(0<e.id){var f=0<a?b.getItem(a-1).id:0;var h={prev_item_id:f,before_id:e.id,bill_id:n,_csrf_token:e._csrf_token}}else f=0<a?b.getItem(a-1).id:0,h={id:e.id,bill_id:n,prev_item_id:f,relation_id:e.relation_id,_csrf_token:e._csrf_token};c.show().then(function(){dojo.xhrPost({url:b.addUrl,content:h,handleAs:"json",load:function(l){l.success&&dojo.forEach(l.items,function(k){0<k.id&&(k=d.newItem(k),d.save(),k=b.getItemIndex(k),b.rearranger.moveRows([k],a),b.selection.clear())});
window.setTimeout(function(){var k="tree"==b.type?2:1;b.selection.setSelected(a,!0);b.focus.setFocusIndex(a,k)},30);c.hide()},error:function(l){b.selection.clear();b.disableToolbarButtons(!0);c.hide()}})})},deleteRow:function(a){var b=this,c=null,d=null;c=b.getItem(a);var e=buildspace.dialog.indeterminateProgressBar({title:g.deleting+". "+g.pleaseWait+"..."});w.curNode.blur();w.curNode=null;var n={url:this.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(f){if(f.success){f=
f.items;for(var h=b.store,l=0,k=f.length;l<k;++l)h.fetchItemByIdentity({identity:f[l].id,onItem:function(r){h.deleteItem(r);h.save()}});f.length=0}e.hide();b.selection.clear();window.setTimeout(function(){b.focus.setFocusIndex(a,0)},10);b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null},error:function(f){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;e.hide()}};"tree"!=this.type?(c=g.deleteElementDialogBoxTitle,d=g.deleteElementDialogBoxMsg):c.type==
buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N?(c=g.deleteHeadDialogBoxTitle,d=g.deleteHeadDialogBoxMsg):(c=g.deleteItemDialogBoxTitle,d=g.deleteItemMsg);new buildspace.dialog.confirm(c,d,80,320,function(){e.show().then(function(){dojo.xhrPost(n)})},function(){})},indentOutdent:function(a,b){var c=this,d=c.store;if(0<a){var e=c.getItem(a),n=buildspace.dialog.indeterminateProgressBar({title:g.recalculateRows+". "+g.pleaseWait+
"..."});0<parseInt(String(e.id))&&n.show().then(function(){dojo.xhrPost({url:c[b+"Url"],content:{id:e.id,_csrf_token:e._csrf_token},handleAs:"json",load:function(f){if(f.success){var h=f.c,l;for(l in f.item)f.item.hasOwnProperty(l)&&l!=d._getIdentifierAttribute()&&d.setValue(e,l,f.item[l]);var k=0;for(f=h.length;k<f;++k)d.fetchItemByIdentity({identity:h[k].id,onItem:function(r){for(var p in h[k])r.hasOwnProperty(p)&&p!=d._getIdentifierAttribute()&&d.setValue(r,p,h[k][p])}});d.save()}n.hide()},error:function(f){c.selection.clear();
c.disableToolbarButtons(!0);n.hide()}})})}},refreshGrid:function(){this.beginUpdate();this.set("structure",this.structure);this.store.close();this.pluginMgr=new this._pluginMgrClass(this);this.pluginMgr.preInit();this.pluginMgr.postInit();this.pluginMgr.startup();this._refresh();this.endUpdate()},editableCellDblClick:function(a){var b=1<this._click.length&&has("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=this._click[1].rowIndex?this._click[0]:a;this.focus.setFocusCell(b.cell,
b.rowIndex);this.onRowClick(b);this.onRowDblClick(a)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);else this.onCellDblClick(a);else this.onRowDblClick(a)},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==C.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},d=this.getItem(a.rowIndex);if(this.currentBillLockedStatus)return!1;b&&d&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&D.hasClass(a.rowNode,
"dojoxGridRowbar"))&&(b._openMyself(c),B.stop(a))},contextMenuItems:function(a){var b=this.getItem(a.rowIndex-1),c=this.getItem(a.rowIndex),d=a.cell,e=!1;"tree"==this.type&&(void 0===b&&(e=!0),b&&b.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&(e=!0));0<parseInt(String(c.id))&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItems"),disabled:!1})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:g.copy,
iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(this,"copyItems"),disabled:!1})));b=this.selectedItem?!1:!0;this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:g.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(this,"pasteItem",a.rowIndex,d),disabled:b}));0<parseInt(String(c.id))&&"tree"==this.type&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.indent,iconClass:"icon-16-container icon-16-indent",onClick:dojo.hitch(this,"indentOutdent",a.rowIndex,"indent"),
disabled:!1})),this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.outdent,iconClass:"icon-16-container icon-16-outdent",onClick:dojo.hitch(this,"indentOutdent",a.rowIndex,"outdent"),disabled:!1})));this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow",a.rowIndex),disabled:e}));0<parseInt(String(c.id))&&(this.rowCtxMenu.addChild(new E),this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.deleteRow,iconClass:"icon-16-container icon-16-delete",
onClick:dojo.hitch(this,"deleteRow",a.rowIndex),disabled:!1})))},disableToolbarButtons:function(a,b){var c=dijit.byId(this.billId+this.elementId+"AddRow-button"),d=dijit.byId(this.billId+this.elementId+"DeleteRow-button"),e=dijit.byId(this.billId+this.elementId+"IndentRow-button"),n=dijit.byId(this.billId+this.elementId+"OutdentRow-button");c._setDisabledAttr(a);d._setDisabledAttr(a);e&&e._setDisabledAttr(a);n&&n._setDisabledAttr(a);if(a&&b instanceof Array){var f=this;dojo.forEach(b,function(h){(h=
dijit.byId(f.billId+f.elementId+h+"Row-button"))&&h._setDisabledAttr(!1)})}},disableAllButtonWhenCurrentBillIsLocked:function(){this.currentBillLockedStatus||this.disableToolbarButtons(!0,["Add"])},setupContextMenuAndToolbarButtonRestriction:function(a){(a=this.getItem(a.rowIndex))&&0<a.id&&!this.currentBillLockedStatus?this.disableToolbarButtons(!1):this.disableAllButtonWhenCurrentBillIsLocked()}});return x("buildspace.apps.ProjectBuilder.SupplyOfMaterial.BillGridBuilder",dijit.layout.BorderContainer,
{pageId:"page-00",style:"padding:0px;width:100%;height:100%;border:0px!important;",gutters:!1,stackContainerTitle:"",billId:-1,elementId:0,itemId:-1,rowSelector:null,gridOpts:{},type:null,postCreate:function(){this.inherited(arguments);y.mixin(this.gridOpts,{billId:this.billId,elementId:this.elementId,type:this.type,region:"center",borderContainerWidget:this});var a=this.grid=new G(this.gridOpts),b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({id:this.billId+
this.elementId+"AddRow-button",label:g.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.addRow(a.selection.selectedIndex)}}));"tree"==this.type&&(b.addChild(new dijit.ToolbarSeparator),b.addChild(new dijit.form.Button({id:this.billId+this.elementId+"IndentRow-button",label:g.indent,iconClass:"icon-16-container icon-16-indent",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&
a.indentOutdent(a.selection.selectedIndex,"indent")}})),b.addChild(new dijit.ToolbarSeparator),b.addChild(new dijit.form.Button({id:this.billId+this.elementId+"OutdentRow-button",label:g.outdent,iconClass:"icon-16-container icon-16-outdent",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.indentOutdent(a.selection.selectedIndex,"outdent")}})));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:this.billId+this.elementId+"DeleteRow-button",
label:g.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.deleteRow(a.selection.selectedIndex)}}));if("tree"!=this.type){var c=this;b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({label:g.printBill,iconClass:"icon-16-container icon-16-print",onClick:function(e){window.open("supplyOfMaterialBill/printBill/id/"+c.billId,"_blank")}}))}this.addChild(b);this.addChild(a);if(b=dijit.byId("supplyOfMaterialGrid"+
this.billId+"-stackContainer")){var d=document.createElement("div");b.addChild(new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),content:this,id:this.pageId,grid:a},d));b.selectChild(this.pageId)}}})});
