var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};$jscomp.polyfill=function(a,c,b,d){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,d):$jscomp.polyfillUnisolated(a,c,b,d))};
$jscomp.polyfillUnisolated=function(a,c,b,d){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];if(!(f in b))return;b=b[f]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,d){var f=a.split(".");a=1===f.length;d=f[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<f.length-1;h++){var l=f[h];if(!(l in d))return;d=d[l]}f=f[f.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?d[f]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:c}):c!==b&&(void 0===$jscomp.propertyToPolyfillSymbol[f]&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):
$jscomp.POLYFILL_PREFIX+f),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[f],{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Object.is",function(a){return a?a:function(c,b){return c===b?0!==c||1/c===1/b:c!==c&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(c,b){var d=this;d instanceof String&&(d=String(d));var f=d.length;b=b||0;for(0>b&&(b=Math.max(b+f,0));b<f;b++){var h=d[b];if(h===c||Object.is(h,c))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(c,b){return-1!==$jscomp.checkStringArgs(this,c,"includes").indexOf(c,b||0)}},"es6","es3");
define("buildspace/apps/CostData/PrimeCostRateLinkBillItems/ElementListingGrid",["dojo/_base/declare","dojox/grid/EnhancedGrid","buildspace/widget/grid/cells/Formatter","./LinkBillItemsGrid","dojo/i18n!buildspace/nls/CostData"],function(a,c,b,d,f){var h=a("buildspace.apps.PrimeCostRateLinkBillItems.ElementListingGrid",c,{style:"border:none;",region:"center",keepSelection:!0,escapeHTMLInData:!1,costData:null,item:null,linkedIds:[],canSort:function(){return!1}}),l=function(e,g){return parseInt(g)+1},
m=function(e,g){g=this.grid.getItem(g);return this.grid.linkedIds.includes(g.id[0])?'<span style="color:#4c94e6">'+e+"</span>":e};return a("buildspace.apps.CostData.PrimeCostRateLinkBillItems.ElementListingContainer",dijit.layout.BorderContainer,{region:"center",title:"",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,costData:null,item:null,grid:null,moduleContainer:null,linkedIds:[],postCreate:function(){this.inherited(arguments);var e=this,g=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+
"..."});e.moduleContainer.linkedElementsUrl?g.show().then(function(){dojo.xhrGet({url:e.moduleContainer.linkedElementsUrl,handleAs:"json",load:function(k){k.success&&(e.linkedIds=k.ids,e.addChild(e.createBreakdownGrid()));g.hide()},error:function(k){}})}):e.addChild(e.createBreakdownGrid())},getGridStructure:function(){this.gridFormatter=new b;return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:l},{name:f.description,field:"description",width:"auto",formatter:m}]},createBreakdownGrid:function(){var e=
this,g=e.grid=h({costData:e.costData,item:e.item,linkedIds:e.linkedIds,structure:e.getGridStructure(),store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"costData/getLinkBillItemElementList/costData/"+e.costData.id+"/id/"+e.item.id}),onRowDblClick:function(k){k=this.getItem(k.rowIndex);0<k.id[0]&&e.createLinkBillItemGrid(k)}});return new dijit.layout.ContentPane({style:"padding:0px;border:none;width:100%;height:100%;",region:"center",content:g,grid:g})},createLinkBillItemGrid:function(e){e=
new d({title:buildspace.truncateString(e.description,60),moduleContainer:this.moduleContainer,costData:this.costData,item:e,style:"padding:0px;margin:0px;width:100%;height:40%;",gutters:!0});this.moduleContainer.stackContainer.addChild(e);this.moduleContainer.stackContainer.selectChild(e)}})});
