all:
  version: Development Trunk
  register:
    buildspace_id: buildspace
  default_user_password: 123456
  default_currency_abbreviation: RM
  rfq_project_ref_no_zero_fill_length: "%05d"
  rfq_resource_ref_no_zero_fill_length: "%06d"
  stock_out_ref_no_zero_fill_length: "%05d"
  maximum_users: 5
  wkhtmltopdf_bin_path: /usr/bin/wkhtmltopdf
  saml_sp_name: buildspace-sp
  can_online: true
  e_project_url: https://etender.buildspace.local
  guzzle_ssl_verification: true
  eproject_shared_folder: /usr/local/etc/buildspace/eproject/app/storage/buildspace
  post_contract_disabled_modules:
    water_deposit:                        false
    deposit:                              false
    out_of_contract_item:                 false
    purchase_on_behalf:                   false
    advanced_payment:                     false
    work_on_behalf:                       false
    work_on_behalf_back_charge:           false
    penalty:                              false
    permit:                               false
    post_contract_claim_material_on_site: false
    request_for_variation_claim:          false
    debit_credit_note:                    false
  sf_guard_plugin:
    signin_form: BsAuthSigninForm
#    algorithm_callable: sha256
    profile_class:               sfGuardUserProfile
    profile_field_name:          user_id
    allow_login_with_email:      true
    success_signin_url:          @homepage
    remember_key_expiration_age: 86400   # 30 days in seconds
    remember_cookie_name:        bsRememberMe
