define("buildspace/apps/CostData/LinkVariationOrderItems/LinkVariationOrderItemsGrid","dojo/_base/declare dojo/aspect dojo/number dojo/currency dojo/_base/array dojo/_base/connect dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dijit/form/TextBox dojo/i18n!buildspace/nls/CostData".split(" "),function(g,k,l,m,h,f,n,p,t,u,d){var q=g("buildspace.apps.CostData.LinkVariationOrderItems.LinkVariationOrderItemsGrid",n,{style:"border:none;",region:"center",
keepSelection:!0,rowSelector:"0px",escapeHTMLInData:!1,selectedItemIds:[],deselectedItemIds:[],constructor:function(a){this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}};this.inherited(arguments)},canSort:function(){return!1},postCreate:function(){var a;a=this;this.inherited(arguments);k.after(this,"_onFetchComplete",function(){a.markedCheckBoxObject(a.selectedItemIds,!0)});this._connects.push(f.connect(this,"onSelected",function(b){(b=a.getItem(b))&&0<b.id[0]&&
a.pushItemIdIntoGridArray(b,!0)}));this._connects.push(f.connect(this,"onDeselected",function(b){(b=a.getItem(b))&&0<b.id[0]&&a.pushItemIdIntoGridArray(b,!1)}));this._connects.push(f.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)}))},markedCheckBoxObject:function(a,b){var c=this,e=this.store;h.forEach(a,function(a){e.fetchItemByIdentity({identity:a,onItem:function(a){a&&(c.pushItemIdIntoGridArray(a,b),c.rowSelectCell.toggleRow(a._0,b))}})})},pushItemIdIntoGridArray:function(a,
b){var c=dojo.indexOf(this.selectedItemIds,a.id[0]),e=dojo.indexOf(this.deselectedItemIds,a.id[0]);b?(-1===c&&this.selectedItemIds.push(a.id[0]),-1!==e&&this.deselectedItemIds.splice(e,1)):(-1!==c&&this.selectedItemIds.splice(c,1),-1===e&&this.deselectedItemIds.push(a.id[0]))},toggleAllSelection:function(a){var b,c;b=this;c=b.selection;a?c.selectRange(0,b.rowCount-1):c.deselectAll();return b.store.fetch({onComplete:function(c){dojo.forEach(c,function(c,d){0<c.id&&b.pushItemIdIntoGridArray(c,a)})}})},
refreshGrid:function(){this.selection.deselectAll();this.beginUpdate();this.store.close();this._refresh();this.endUpdate()},destroy:function(){this.inherited(arguments);h.forEach(this._connects,f.disconnect);return delete this._connects}}),r=function(a,b){return parseInt(b)+1},s=function(a,b,c){b=l.parse(a);c.customClasses.push("disable-cell");return a=isNaN(b)||0==b||null==b?"&nbsp;":m.format(a)};return g("buildspace.apps.CostData.LinkVariationOrderItems.LinkVariationOrderItemsContainer",dijit.layout.BorderContainer,
{region:"center",title:"",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,costData:null,masterItem:null,item:null,grid:null,linkedIds:[],moduleContainer:null,postCreate:function(){var a=this;this.inherited(arguments);this.addToolbar();var b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show().then(function(){dojo.xhrGet({url:"variationOrder/getLinkedItems/cost_data_id/"+a.costData.id+"/id/"+a.masterItem.id+"/id_type/variation_order_item_id",handleAs:"json",
load:function(c){c.success&&(a.linkedIds=c.ids,a.addBreakdownGrid());b.hide()},error:function(a){}})})},getGridStructure:function(){this.gridFormatter=new p;return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:r},{name:d.description,field:"description",width:"auto"},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align: center;",formatter:this.gridFormatter.unitCellFormatter},{name:d.nettOmissionAddition,field:"nett_omission_addition",width:"140px",styles:"text-align: right;",
formatter:s}]},addToolbar:function(){var a=this,b=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;width:100%;"});b.addChild(new dijit.form.Button({label:d.save,iconClass:"icon-16-container icon-16-save",onClick:function(){a.save()}}));a.addChild(b)},addBreakdownGrid:function(){var a=this.grid=q({structure:this.getGridStructure(),selectedItemIds:this.linkedIds,store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"variationOrder/getVariationOrderItemList/costData/"+
this.costData.id+"/void/"+this.item.id})}),a=new dijit.layout.ContentPane({style:"padding:0px;border:none;width:100%;height:100%;",region:"center",content:a,grid:a});this.addChild(a)},save:function(){var a=this,b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show().then(function(){dojo.xhrPost({url:"variationOrder/linkItems/id/"+a.masterItem.id+"/_csrf_token/"+a.item._csrf_token,handleAs:"json",content:{cost_data_id:a.costData.id,selectedIds:a.grid.selectedItemIds.join(),
deselectedIds:a.grid.deselectedItemIds.join(),_csrf_token:a._csrf_token},load:function(c){a.grid.refreshGrid();a.grid.selectedItemIds=c.item_ids;a.grid.deselectedItemIds=[];a.grid.markedCheckBoxObject(a.grid.selectedItemIds,!0);if(a.moduleContainer.onSave)a.moduleContainer.onSave();b.hide()},error:function(a){b.hide()}})})}})});
