define("buildspace/apps/ScheduleOfRateLibrary/buildUpGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojo/_base/connect dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/currency dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox dijit/popup dijit/TooltipDialog ./importResourceDialog ./importScheduleOfRateDialog dojo/i18n!buildspace/nls/BuildUpGrid".split(" "),
function(q,r,E,F,n,G,H,u,v,w,x,y,p,z,I,J,K,L,M,l,t,A,B,h){var D=q("buildspace.apps.ScheduleOfRateLibrary.BuildUp.grid",dojox.grid.EnhancedGrid,{itemId:-1,resource:null,scheduleOfRateItemId:0,style:"border-top:none;",selectedItem:null,unitObj:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,buildUpSummaryWidget:null,constructor:function(a){this.rearranger=u(this,{});this.formulatedColumn=v(this,{})},canSort:function(a){return!1},postCreate:function(){var a=
this,b=null;a.inherited(arguments);this.on("RowContextMenu",function(b){a.selection.clear();var c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b);0<c.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Add"])},!0);this.on("RowClick",function(b){(b=a.getItem(b.rowIndex))&&0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Add"])});this._connects.push(n.connect(this,"onCellMouseOver",function(a){var c=a.cell.field,d=a.rowIndex,g=this.getItem(d),c=c.replace("-value",
"");"undefined"!==typeof g[c+"-has_formula"]&&g[c+"-has_formula"][0]&&(g=g[c+"-value"][0],g=this.formulatedColumn.convertItemIdToRowIndex(g,d),null===b&&(b=new t({content:g,onMouseLeave:function(){l.close(b)}}),l.open({popup:b,around:a.cellNode})))}));this._connects.push(n.connect(this,"onCellMouseOut",function(){null!==b&&(l.close(b),b=null)}));this._connects.push(n.connect(this,"onStartEdit",function(){null!==b&&(l.close(b),b=null)}))},doApplyCellEdit:function(a,b,c){var e=this,d=e.getItem(b),g=
e.store,k=c.replace("-value","");-1!==c.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,b));if(a!==d[c][0]){var k={id:d.id,attr_name:k,val:a,_csrf_token:d._csrf_token?d._csrf_token:null},f=this.updateUrl;d.id==buildspace.constants.GRID_LAST_ROW&&(f=0<b?e.getItem(b-1):!1,r.mixin(k,{prev_item_id:f?f.id:0,relation_id:d.relation_id,resource_id:e.resource.id}),f=this.addUrl);var C=function(b,a){for(var c in b)d.hasOwnProperty(c)&&c!=a._getIdentifierAttribute()&&a.setValue(d,c,b[c]),
dojo.forEach(b.affected_nodes,function(b){a.fetchItemByIdentity({identity:b.id,onItem:function(c){for(var f in b)d.hasOwnProperty(f)&&f!=a._getIdentifierAttribute()&&a.setValue(c,f,b[f])}})});a.save()},m=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});m.show();dojo.xhrPost({url:f,content:k,handleAs:"json",load:function(a){if(a.success){0<d.id?C(a.data,g):(g.deleteItem(d),g.save(),dojo.forEach(a.items,function(a){g.newItem(a)}),g.save(),e.disableToolbarButtons(!0));e.updateTotalBuildUp(a.total_build_up);
var f=e.getCellByField(c);window.setTimeout(function(){e.focus.setFocusIndex(b,f.index)},10)}m.hide()},error:function(a){console.log(a);m.hide()}})}e.inherited(arguments)},dodblclick:function(a){},onCellFocus:function(a,b){var c=this,e=c.getItem(b);"description"!==a.field||0>e.id[0]||!e.linked[0]?c.closeToolTipDialogIfAvailable():dojo.xhrGet({url:"resourceLibrary/getBuildUpRatesToolTipInformation",content:{id:e.id,type:"sor"},handleAs:"json",load:function(d){if(d.success){c.closeToolTipDialogIfAvailable();
var e=!1,k='<h1 style="font-size: 12px; text-shadow: 1px 1px 1px #000;background-color: rgba(35, 35, 35, .85); color: #fff; padding: 4px 10px;">'+d.items[0].description+"</h1>";1<Object.keys(d.items).length&&(e=!0,k+='<table style="width: 100%; border-collapse: collapse;">');dojo.forEach(d.items,function(a,b){0!==b&&(k+='<tr><td style="border: 1px dotted #D5CDB5; font-weight: bold; font-size: 11px; padding-left:'+16*a.level+'px;">'+a.description+"</td></td>")});e&&(k+="</table>");c.myTooltipDialog=
new t({id:"buildUpRatesTooltipDialog-"+c.itemId[0],style:"width: 300px;",content:k});l.open({popup:c.myTooltipDialog,around:a.view.rowNodes[b],orient:["below"]})}},error:function(a){console.log(a)}})},onRowMouseOut:function(){this.closeToolTipDialogIfAvailable()},addRow:function(a){p.curNode.blur();p.curNode=null;var b=this,c=buildspace.dialog.indeterminateProgressBar({title:h.addingRow+". "+h.pleaseWait+"..."}),e=b.store,d=b.getItem(a);if(0<d.id)d={before_id:d.id,_csrf_token:d._csrf_token};else var g=
0<a?b.getItem(a-1).id:0,d={id:d.id,prev_item_id:g,relation_id:d.relation_id,resource_id:b.resource.id,_csrf_token:d._csrf_token};c.show();dojo.xhrPost({url:this.addUrl,content:d,handleAs:"json",load:function(d){d.success&&dojo.forEach(d.items,function(c){0<c.id&&(c=e.newItem(c),e.save(),c=b.getItemIndex(c),b.rearranger.moveRows([c],a),b.selection.clear())});window.setTimeout(function(){b.selection.setSelected(a,!0);b.focus.setFocusIndex(a,1)},30);c.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);
c.hide()}})},deleteRow:function(a){var b=this,c=b.getItem(a),e=buildspace.dialog.indeterminateProgressBar({title:h.deleting+". "+h.pleaseWait+"..."});p.curNode.blur();p.curNode=null;e.show();var d={url:this.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(d){if(d.success){var g=d.affected_nodes,f=b.store;f.deleteItem(c);f.save();for(var h=0,m=g.length;h<m;++h)f.fetchItemByIdentity({identity:g[h].id,onItem:function(a){for(var b in g[h])a.hasOwnProperty(b)&&b!=f._getIdentifierAttribute()&&
f.setValue(a,b,g[h][b]);f.save()}});b.updateTotalBuildUp(d.total_build_up)}e.hide();b.selection.clear();window.setTimeout(function(){b.focus.setFocusIndex(a,0)},10);b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;e.hide()}};new buildspace.dialog.confirm(h.deleteBuildUpRateItemTitle,h.deleteBuildUpRateItemMsg,80,320,function(){dojo.xhrPost(d)},function(){e.hide()})},cutItems:function(){this.selectedItem=
this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="copy"},pasteItem:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."}),e=b.store,d=b.selection.getFirstSelected(),g=d.id==buildspace.constants.GRID_LAST_ROW&&0<a?b.getItem(a-1).id:0;c.show();dojo.xhrPost({url:this.pasteUrl,content:{type:b.pasteOp,target_id:d.id,id:b.selectedItem.id,prev_item_id:g,_csrf_token:b.selectedItem._csrf_token},
handleAs:"json",load:function(d){var f=[];if(d.success)switch(b.pasteOp){case "cut":e.fetchItemByIdentity({identity:d.data.id,onItem:function(c){c=b.getItemIndex(c);f.push(c);0<f.length&&b.rearranger.moveRows(f,a);b.selectAfterPaste(c>a?a:a-1,!0)}});break;case "copy":var g=e.newItem(d.data);e.save();g=b.getItemIndex(g);f.push(g);0<f.length&&(b.rearranger.moveRows(f,a),b.selectAfterPaste(a,!1));b.updateTotalBuildUp(d.total_build_up)}b.disableToolbarButtons(!1);b.pasteOp=null;f.length=0;c.hide()},error:function(a){b.selection.clear();
b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;c.hide()}})},selectAfterPaste:function(a,b){this.selection.clear();this.selectedItem=null;this.selection.setSelected(a,!0);b&&this.scrollToRow(0<a-3?a-3:a)},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==x.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},e=this.getItem(a.rowIndex);b&&e&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&z.hasClass(a.rowNode,"dojoxGridRowbar"))&&
(b._openMyself(c),w.stop(a))},contextMenuItems:function(a){var b=this.getItem(a.rowIndex);0<b.id&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:h.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItems")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:h.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(this,"copyItems")})));this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:h.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(this,
"pasteItem",a.rowIndex),disabled:this.selectedItem?!1:!0}));this.rowCtxMenu.addChild(new dijit.MenuItem({label:h.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow",a.rowIndex)}));0<b.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:h.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow",a.rowIndex)}))},disableToolbarButtons:function(a,b){var c=dijit.byId("builUpGrid-"+this.resource.id+"_"+this.scheduleOfRateItemId+"AddRow-button"),
e=dijit.byId("builUpGrid-"+this.resource.id+"_"+this.scheduleOfRateItemId+"DeleteRow-button");c._setDisabledAttr(a);e._setDisabledAttr(a);if(a&&b instanceof Array){var d=this;dojo.forEach(b,function(a){dijit.byId("builUpGrid-"+d.resource.id+"_"+d.scheduleOfRateItemId+a+"Row-button")._setDisabledAttr(!1)})}},updateTotalBuildUp:function(a){dijit.byId("accPane-"+this.resource.id+"-"+this.scheduleOfRateItemId).set("title",this.resource.name+'<span style="color:blue;float:right;">'+buildspace.currencyAbbreviation+
"&nbsp;"+y.format(a)+"</span>");this.buildUpSummaryWidget.refreshTotalCost()},closeToolTipDialogIfAvailable:function(){var a=dijit.byId("buildUpRatesTooltipDialog-"+this.itemId[0]);void 0!==this.myTooltipDialog&&void 0!==a&&(l.close(),a.destroy())},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,n.disconnect);delete this._connects}});return q("buildspace.apps.ScheduleOfRateLibrary.BuildUpGrid",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",
gutters:!1,resource:null,scheduleOfRateItemId:0,gridOpts:{},postCreate:function(){var a=this;a.inherited(arguments);r.mixin(a.gridOpts,{resource:a.resource,scheduleOfRateItemId:a.scheduleOfRateItemId,region:"center"});var b=this.grid=new D(a.gridOpts),c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({id:"builUpGrid-"+a.resource.id+"_"+a.scheduleOfRateItemId+"AddRow-button",label:h.addRow,iconClass:"icon-16-container icon-16-add",
disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.addRow(b.selection.selectedIndex)}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"builUpGrid-"+a.resource.id+"_"+a.scheduleOfRateItemId+"DeleteRow-button",label:h.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.deleteRow(b.selection.selectedIndex)}}));c.addChild(new dijit.ToolbarSeparator);
c.addChild(new dijit.form.Button({label:h.importFromResourceLibrary,iconClass:"icon-16-container icon-16-import",onClick:function(){A({itemId:a.scheduleOfRateItemId,resource:a.resource,buildUpGridStore:b.store}).show()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:h.importFromScheduleOfRate,iconClass:"icon-16-container icon-16-import",onClick:function(){(new B({itemId:a.scheduleOfRateItemId,resource:a.resource,buildUpGridStore:b.store,buildUpSummaryWidget:a.gridOpts.buildUpSummaryWidget})).show()}}));
a.addChild(c);a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))}})});
