define("buildspace/apps/ScheduleOfRateLibrary/importSORItemDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/aspect buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!buildspace/nls/ResourceLibrary buildspace/widget/grid/Filter".split(" "),function(g,n,h,x,y,z,t,u,p,k,A,d,v){var w=g("buildspace.apps.ScheduleOfRateLibrary.ImportSORItemGrid",dojox.grid.EnhancedGrid,{type:null,selectedItem:null,
libraryId:0,libraryTradeId:0,dialogWidget:null,_csrf_token:null,resourceGrid:null,style:"border-top:none;",constructor:function(b){this.itemIds=[];this.connects=[];"tree"==b.type&&(this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}});this.inherited(arguments)},canSort:function(){return!1},postCreate:function(){var b=this;this.inherited(arguments);this.on("RowClick",function(a){a=b.getItem(a.rowIndex);"tree"==b.type&&(a&&0<a.id?b.disableToolbarButtons(!1):
b.disableToolbarButtons(!0))});"tree"==this.type&&(this._connects.push(h.connect(this,"onCellClick",function(a){b.selectTree(a)})),this._connects.push(h.connect(this.rowSelectCell,"toggleAllSelection",function(a){b.toggleAllSelection(a)})))},dodblclick:function(b){this.onRowDblClick(b)},disableToolbarButtons:function(b){dijit.byId("ImportSORItemGrid-"+this.libraryTradeId+"_"+this.libraryId+"ImportWithRate-button")._setDisabledAttr(b);dijit.byId("ImportSORItemGrid-"+this.libraryTradeId+"_"+this.libraryId+
"ImportWithoutRate-button")._setDisabledAttr(b)},importItem:function(b){var a=this,c=a.resourceGrid,e=a.itemIds,f=-1,q=null;if(0<e.length){var r=c.getItemIndex(this.selectedItem);0<r&&(f=r-1);-1<f&&(q=c.getItem(f).id);var l=buildspace.dialog.indeterminateProgressBar({title:d.importingData+". "+d.pleaseWait+"..."});l.show();dojo.xhrPost({url:"scheduleOfRateImport/importSORItems",content:{id:q,trade_id:a.libraryTradeId,ids:[e],with_rate:b,_csrf_token:a._csrf_token},handleAs:"json",load:function(b){if(b.success){c.store.save();
c.store.close();var e=p.after(c,"_onFetchComplete",function(){this.selection.clear();e.remove();f=-1==f?0:f;this.scrollToRow(f);this.selection.setSelected(0==f?f:f+1,!0);this.disableToolbarButtons(!1)});c._refresh()}a.itemIds=[];l.hide();a.dialogWidget.hide()},error:function(b){a.itemIds=[];c.selection.clear();c.disableToolbarButtons(!0);l.hide();a.dialogWidget.hide()}})}},selectTree:function(b){var a=b.rowIndex;b=this.selection.selected[a];(a=this.getItem(a))&&this.pushItemIdIntoGridArray(a,b)},
pushItemIdIntoGridArray:function(b,a){var c=dojo.indexOf(this.itemIds,b.id[0]);a?-1==c&&this.itemIds.push(b.id[0]):-1!=c&&this.itemIds.splice(c,1)},toggleAllSelection:function(b){var a=this,c=a.selection;b?(c.selectRange(0,a.rowCount-1),a.itemIds=[],a.store.fetch({onComplete:function(b){dojo.forEach(b,function(b,c){0<b.id&&a.itemIds.push(b.id[0])})}})):(c.deselectAll(),a.itemIds=[])},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,h.disconnect);delete this._connects}}),m=
g("buildspace.apps.ScheduleOfRateLibrary.ImportSORItemGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,libraryId:0,libraryTradeId:0,gridOpts:{},postCreate:function(){this.inherited(arguments);n.mixin(this.gridOpts,{type:this.type,libraryId:this.libraryId,libraryTradeId:this.libraryTradeId,region:"center"});var b=this.grid=new w(this.gridOpts),a=new v({grid:b,region:"top",filterFields:this.filterFields});this.addChild(a);"tree"==
this.type&&(a=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"}),a.addChild(new dijit.form.Button({id:"ImportSORItemGrid-"+this.libraryTradeId+"_"+this.libraryId+"ImportWithRate-button",label:d.importWithRate,iconClass:"icon-16-container icon-16-import",onClick:function(){b.importItem(!0)}})),a.addChild(new dijit.ToolbarSeparator),a.addChild(new dijit.form.Button({id:"ImportSORItemGrid-"+this.libraryTradeId+"_"+this.libraryId+"ImportWithoutRate-button",label:d.importWithoutRate,
iconClass:"icon-16-container icon-16-import",onClick:function(){b.importItem(!1)}})),this.addChild(a));this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}));if(a=dijit.byId("resourceLibrary-item_import_"+this.libraryId+"_"+this.libraryTradeId+"-stackContainer")){var c=document.createElement("div"),c=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,45),content:this,id:this.pageId,executeScripts:!0},c);a.addChild(c);n.mixin(c,
{grid:b});a.selectChild(this.pageId)}}});return g("buildspace.apps.ScheduleOfRateLibrary.ImportItemDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",selectedItem:null,libraryId:0,tradeId:0,resourceGrid:null,buildRendering:function(){var b=this.createContent();b.startup();this.content=b;this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(b){b.keyCode==t.ESCAPE&&
dojo.stopEvent(b)},onHide:function(){this.destroyRecursive()},createContent:function(){var b=this,a=new dijit.layout.BorderContainer({style:"padding:0px;width:980px;height:500px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var e=new k,f=dojo.data.ItemFileWriteStore({clearOnClose:!0,
url:"scheduleOfRateImport/getScheduleOfRateList"}),e=new m({stackContainerTitle:d.scheduleOfRate,pageId:"import-page_library-"+this.libraryId+"_"+this.tradeId,libraryId:this.libraryId,filterFields:[{name:"Title"}],libraryTradeId:this.tradeId,gridOpts:{store:f,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:e.rowCountCellFormatter},{name:d.title,field:"name",width:"auto"}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.name[0]&&b.createTradeGrid(a)}}}),
e=this.makeGridContainer(e,d.scheduleOfRate);a.addChild(c);a.addChild(e);return a},createTradeGrid:function(b){var a=this,c=k(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"scheduleOfRate/getTradeList/id/"+b.id});new m({stackContainerTitle:b.name,pageId:"import-page_trade-"+this.libraryId+"_"+this.tradeId,libraryId:a.libraryId,libraryTradeId:a.tradeId,filterFields:[{description:"Description"}],gridOpts:{store:e,dialogWidget:a,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",
formatter:c.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"}],onRowDblClick:function(b){b=this.getItem(b.rowIndex);0<b.id&&null!==b.description[0]&&a.createItemGrid(b)}}})},createItemGrid:function(b){var a=k(),c=new dojo.data.ItemFileWriteStore({url:"scheduleOfRate/getItemList/id/"+b.id});new m({stackContainerTitle:b.description,pageId:"import-page_item-"+this.libraryId+"_"+this.tradeId,libraryId:this.libraryId,libraryTradeId:this.tradeId,filterFields:[{description:"Description"},
{uom_symbol:"Unit"},{"rate-final_value":"Rate"}],type:"tree",gridOpts:{escapeHTMLInData:!1,store:c,dialogWidget:this,selectedItem:this.selectedItem,resourceGrid:this.resourceGrid,_csrf_token:b._csrf_token,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:a.treeCellFormatter},{name:d.type,field:"type",width:"70px",styles:"text-align:center;",formatter:a.typeCellFormatter},{name:d.unit,
field:"uom_id",width:"70px",styles:"text-align:center;",formatter:a.unitIdCellFormatter},{name:d.rate,field:"rate-value",width:"80px",styles:"text-align:right;",formatter:a.formulaCurrencyCellFormatter}]}})},makeGridContainer:function(b,a){var c=this.libraryId+"_"+this.tradeId,e=dijit.byId("resourceLibrary-item_import_"+c+"-stackContainer");e&&dijit.byId("resourceLibrary-item_import_"+c+"-stackContainer").destroyRecursive();e=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",
region:"center",id:"resourceLibrary-item_import_"+c+"-stackContainer"});e.addChild(new dijit.layout.ContentPane({title:a,content:b,grid:b.grid}));var f=new dijit.layout.StackController({region:"top",containerId:"resourceLibrary-item_import_"+c+"-stackContainer"}),f=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:f}),d=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});
d.addChild(e);d.addChild(f);dojo.subscribe("resourceLibrary-item_import_"+c+"-stackContainer-selectChild","",function(a){var b=dijit.byId("resourceLibrary-item_import_"+c+"-stackContainer");if(b){var d=b.getChildren(),e=dojo.indexOf(d,a);if(d.length>e+1){a.grid.store.save();a.grid.store.close();var f=p.after(a.grid,"_onFetchComplete",function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,b.removeChild(d[e]),d[e].destroyRecursive(!0)}});return d}})});
