(function(){var k={}.hasOwnProperty;define("buildspace/apps/PurchaseOrder/SupplierList/SupplierSelectionGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/request dojo/html dojo/dom dojo/keys dojo/dom-style buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/Filter dojo/i18n!../../../nls/PurchaseOrder dojo/i18n!../../../nls/CompanyDirectories".split(" "),function(h,t,u,v,l,w,x,m,n,p,y,q,g,d){var r=h("buildspace.apps.PurchaseOrder.SupplierList.SupplierSelectionGrid",
dojox.grid.EnhancedGrid,{style:"padding:0;margin:0;border:none;",region:"center",poId:-1,poForm:null,selectionMode:"single",dialogContainer:null,companyIds:[],_csrf_token:null,plugins:{indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}},canSort:function(){return!1},postCreate:function(){var b;this.inherited(arguments);b=this;this.store.fetch({query:{},onComplete:function(a){return dojo.forEach(a,function(a){if(a.selected[0])return b.rowSelectCell.toggleRow(a._0,!0)})}});
this.connect(this.selection,"onDeselected",function(a){a=b.selection.getSelected();return b.gridAction(a)});return this.connect(this.selection,"onSelected",function(a){a=b.selection.getSelected();return b.gridAction(a)})},gridAction:function(b){var a,c,d,f;a=b.length;this.disableToolbarButtons(!0);this.companyIds=[];if(0<a){f=[];for(d in b)k.call(b,d)&&(a=b[d],c=a.id[0],0<c?(this.companyIds.push(a.id[0]),f.push(this.disableToolbarButtons(!1))):f.push(void 0));return f}},select:function(){var b,a;
a=this;b=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."});b.show();return l.post("purchaseOrder/saveCurrentSelectedSupplierInfo",{data:{poId:a.poId,"companyIds[]":a.companyIds,_csrf_token:a._csrf_token},handleAs:"json"}).then(function(c){c.success&&(a.poForm.currentAssignedSupplierNode.innerHTML=c.supplierName,a.poForm.supplierAddressNode_1.set("value",c.supplierAddress[0]),a.poForm.supplierAddressNode_2.set("value",c.supplierAddress[1]),a.poForm.supplierAddressNode_3.set("value",
c.supplierAddress[2]));b.hide();return a.dialogContainer.hide()},function(a){return b.hide()})},disableToolbarButtons:function(b,a){var c=dijit.byId("selectSupplierButtonForRFQ");c&&c.set("disabled",b)}});return h("buildspace.apps.PurchaseOrder.SupplierList.SupplierSelectionDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",poId:null,poForm:null,data:null,supplierListContainer:null,buildRendering:function(){var b=this.createContent();b.startup();this.content=b;return this.inherited(arguments)},
postCreate:function(){n.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(b){if(b.keyCode===m.ESCAPE)return dojo.stopEvent(b)},onHide:function(){return this.destroyRecursive()},createContent:function(){var b,a,c,e;c=this;a=this.grid=new r({poId:c.poId,poForm:c.poForm,store:dojo.data.ItemFileWriteStore({data:c.data.data}),_csrf_token:c.data._csrf_token,structure:c.getGridLayout(),dialogContainer:c});e=new dijit.Toolbar({region:"top",
style:"padding:2px;border:none;width:100%;"});e.addChild(new dijit.form.Button({id:"selectSupplierButtonForRFQ",disabled:!0,label:g.select,iconClass:"icon-16-container icon-16-checkmark2",onClick:function(){return a.select()}}));e.addChild(new dijit.ToolbarSeparator);e.addChild(new dijit.form.Button({label:g.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return c.hide()}}));b=new dijit.layout.BorderContainer({style:"padding:0px;width:850px;height:450px;",gutters:!1,region:"top"});
b.addChild(new q({region:"top",editableGrid:!1,grid:a,filterFields:[{company_name:d.companyName,registration_no:d.registrationNo,business_type:d.businessType,country:d.country,state:d.state}]}));b.addChild(e);b.addChild(a);return b},getGridLayout:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:(new p).rowCountCellFormatter},{name:d.companyName,field:"company_name",width:"auto"},{name:d.registrationNo,field:"registration_no",width:"120px",styles:"text-align: center;"},
{name:d.businessType,field:"business_type",width:"120px",styles:"text-align: center;"},{name:d.country,field:"country",width:"120px",styles:"text-align: center;"},{name:d.state,field:"state",width:"120px",styles:"text-align: center;"}]}})})}).call(this);
