(function(){define("buildspace/apps/PurchaseOrder/ItemList/ItemListContainer","dojo/_base/declare dojo/_base/lang dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/request dijit/focus dijit/Toolbar dijit/form/Button dijit/DropDownMenu dijit/form/DropDownButton dijit/MenuItem dijit/layout/BorderContainer buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/Formatter buildspace/widget/grid/cells/FormulaTextBox ./ProjectResourceDialog ./ResourceLibraryDialog ./RequestForQuotationDialog ./PurchaseOrderItemRemarkDialog buildspace/widget/grid/Filter dojo/i18n!../../../nls/PurchaseOrder".split(" "),
function(m,G,H,q,r,t,n,u,v,w,x,k,y,I,z,J,A,B,C,D,E,b){var F=m("buildspace.apps.PurchaseOrder.ItemList.ItemListGrid",dojox.grid.EnhancedGrid,{style:"border:none;",rowSelector:"0px",region:"center",purchaseOrder:null,constructor:function(a){this.rearranger=q(this,{});return this.formulatedColumn=r(this,{})},canSort:function(a){return!1},noDataMessage:b.noRFQItemAvailableInGrid,postCreate:function(){this.inherited(arguments);return this.on("RowClick",function(a){return(a=this.getItem(a.rowIndex))&&0<
a.id[0]?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0)})},canEdit:function(a,d){var c,e;e=this;if(void 0!==a)if(c=this.getItem(d),0<c.id[0]){if(c.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||c.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N){window.setTimeout(function(){e.edit.cancel();return e.focus.setFocusIndex(d,a.index)},10);return}}else{window.setTimeout(function(){e.edit.cancel();return e.focus.setFocusIndex(d,a.index)},10);return}return this._canEdit},
onRowDblClick:function(a){var d,c,e,f;c=this.getItem(a.rowIndex);d=a.cell.field;f=this.store;return c&&c.poItemId&&0<c.poItemId[0]&&"remarks"===d?(e=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."}),e.show(),t.post("requestForQuotation/getRFQItemRemarkInformation",{query:{rfqItemId:c.poItemId[0],rfqItemRemarkId:c.poItemRemarkId[0]},handleAs:"json"}).then(function(a){(new D({title:""+b.itemRemarkDialogTitle,item:c,data:a,poItemGridStore:f})).show();return e.hide()},function(a){return e.hide()})):
this.inherited(arguments)},doApplyCellEdit:function(a,d,c){var e,f,h,g;g=this;e=this.getItem(d);return a!==e[c][0]?(f={field_name:c,poId:g.poId,poItemId:e.poItemId,val:a,_csrf_token:e._csrf_token?e._csrf_token:null},h=buildspace.dialog.indeterminateProgressBar({title:b.savingData+". "+b.pleaseWait+"..."}),h.show(),dojo.xhrPost({url:"purchaseOrder/updateItemInformation",content:f,handleAs:"json",load:function(a){var b,f,p,l;if(a.success)for(l=a.items,f=0,p=l.length;f<p;f++)a=l[f],g.updateStore(e,a);
b=g.getCellByField(c);window.setTimeout(function(){return g.focus.setFocusIndex(d,b.index)},10);return h.hide()},error:function(a){return h.hide()}})):g.inherited(arguments)},updateStore:function(a,d){var c,e,b;e=this.store;b=[];for(c in d)a.hasOwnProperty(c)&&c!==e._getIdentifierAttribute()?b.push(e.setValue(a,c,d[c])):b.push(void 0);return b},deleteRow:function(a){var d,c,e,f,h,g;e=this;d=this.getItem(a);f=e.store;c=buildspace.dialog.indeterminateProgressBar({title:b.deleting+". "+b.pleaseWait+
"..."});n.curNode.blur();n.curNode=null;c.show();g={url:"purchaseOrder/deleteItems",content:{poId:e.poId,resourceItemId:d.id,_csrf_token:d._csrf_token},handleAs:"json",load:function(b){var d,g,h;if(b.success){f=e.store;if(void 0!==b.affected_nodes)for(d=b.affected_nodes,g=0,h=d.length;g<h;g++)b=d[g],f.fetchItemByIdentity({identity:b.id,onItem:function(a){if(a)return f.deleteItem(a),f.save()}});c.hide();e.selection.clear();return window.setTimeout(function(){return e.focus.setFocusIndex(a,0)},10)}},
error:function(a){e.selection.clear();return c.hide()}};d.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N?(h=b.deleteHeadDialogBoxTitle,d=b.deleteHeadDialogBoxMsg):(h=b.deleteItemDialogBoxTitle,d=b.deleteItemDialogBoxMsg);return new buildspace.dialog.confirm(h,d,80,320,function(){return dojo.xhrPost(g)},function(){return c.hide()})},disableToolbarButtons:function(a,b){var c=dijit.byId("deleteItemListFromPurchaseOrder");
c&&c.set("disabled",a)},refreshGrid:function(){this.store.save();this.store.close();return this.setStore(this.store)}});return m("buildspace.apps.PurchaseOrder.ItemList.ItemListContainer",y,{purchaseOrder:null,style:"height:100%;width:100%;padding:0;margin:0;",gutters:!1,postCreate:function(){var a,d,c,e;this.inherited(arguments);c=this;(d=dijit.byId("PurchaseOrderItemListMaintenance-stackContainer"))&&dijit.byId("PurchaseOrderItemListMaintenance-stackContainer").destroyRecursive();d=c.stackContainer=
new dijit.layout.StackContainer({style:"width:100%;height:100%;",region:"center",id:"PurchaseOrderItemListMaintenance-stackContainer"});d=new dojo.data.ItemFileWriteStore({url:"purchaseOrder/getItemListing/poId/"+this.purchaseOrder.id,clearOnClose:!0,urlPreventCache:!0});a=new F({structure:c.getGridLayout(),store:d,poId:this.purchaseOrder.id,escapeHTMLInData:!1});e=new u({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border:none;"});d=new w({style:"display: none;"});d.addChild(new k({label:b.copyFromProjectResource,
onClick:function(){return(new A({title:b.copyFromProjectResource,projectId:c.purchaseOrder.project_id[0],poId:c.purchaseOrder.id[0],itemListGrid:a})).show()}}));d.addChild(new k({label:b.copyFromResourceLibrary,onClick:function(){return(new B({title:b.copyFromResourceLibrary,poId:c.purchaseOrder.id[0],itemListGrid:a})).show()}}));d.addChild(new k({label:b.copyFromRequestForQuotation,onClick:function(){return(new C({title:b.copyFromRequestForQuotation,poId:c.purchaseOrder.id[0],itemListGrid:a,csrf_token:c.purchaseOrder._csrf_token[0]})).show()}}));
e.addChild(new x({label:b.copyFrom,iconClass:"icon-16-container icon-16-import",dropDown:d}));e.addChild(new dijit.ToolbarSeparator);e.addChild(new v({label:b["delete"],id:"deleteItemListFromPurchaseOrder",iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:function(){return a.deleteRow(a.selection.selectedIndex)}}));this.addChild(new E({region:"top",grid:a,editableGrid:!1,filterFields:[{description:b.description},{quantity:b.quantity},{uom:b.unit},{remarks:b.remarks}]}));this.addChild(e);
return this.addChild(a)},getGridLayout:function(){var a=new z;return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter,noresize:!0},{name:b.description,field:"description",width:"auto",formatter:a.treeCellFormatter,noresize:!0},{name:b.quantity,field:"quantity",width:"90px",styles:"text-align: right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",editable:!0,formatter:a.rfqQuantityCellFormatter,noresize:!0},{name:b.unit,field:"uom",width:"70px",
styles:"text-align: center;",formatter:a.rfqUnitCellFormatter,noresize:!0},{name:b.rate,field:"rates",styles:"text-align:right;",width:"75px",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.currencyCellFormatter,noresize:!0},{name:b.remarks,field:"remarks",width:"280px",formatter:a.rfqRemarkCellFormatter}]}})})}).call(this);
