(function(){define("buildspace/apps/PurchaseOrder/ItemList/ProjectResourceDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojox/layout/ContentPane buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!../../../nls/PurchaseOrder".split(" "),function(h,p,k,u,v,w,q,r,t,l,x,e){var g,m;m=h("buildspace.apps.PurchaseOrder.ImportProjectResourceGrid",dojox.grid.EnhancedGrid,{type:null,dialogWidget:null,
_csrf_token:null,resource:null,itemIds:[],style:"border-top:none;",poId:-1,projectId:-1,resourceId:-1,itemListGrid:null,constructor:function(a){this.itemIds=[];this.connects=[];"tree"===a.type&&(this.urlGetDescendantIds="bqLibrary/getResourceDescendantsForImport",this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align: center;"}});return this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){var a;a=this;a.inherited(arguments);this.on("RowClick",
function(b){b=a.getItem(b.rowIndex);if("tree"===a.type)return b&&0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)});if("tree"===this.type)return this._connects.push(k.connect(this,"onCellClick",function(b){return a.selectTree(b)})),this._connects.push(k.connect(this.rowSelectCell,"toggleAllSelection",function(b){return a.toggleAllSelection(b)}))},dodblclick:function(a){return this.onRowDblClick(a)},selectTree:function(a){var b,c,d,f,n;a=a.rowIndex;c=this.selection.selected[a];a=this.getItem(a);
f=this;n=this.store;if(a.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER)return d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),d.show(),b=-1,a={url:this.urlGetDescendantIds,content:{id:a.id},handleAs:"json",load:function(a){dojo.forEach(a.items,function(a){return n.fetchItemByIdentity({identity:a.id,onItem:function(a){if(a)return b=a._0,f.pushItemIdIntoGridArray(a,c),f.selection[c?"addToSelection":"deselect"](b)}})});return d.hide()},error:function(a){return d.hide()}},
dojo.xhrPost(a);if(a.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM)return this.pushItemIdIntoGridArray(a,c)},pushItemIdIntoGridArray:function(a,b){var c;c=dojo.indexOf(this.itemIds,a.id[0]);if(b){if(-1===c)return this.itemIds.push(a.id[0])}else if(-1!==c)return this.itemIds.splice(c,1)},toggleAllSelection:function(a){var b,c;b=this;c=b.selection;if(a)return c.selectRange(0,b.rowCount-1),b.itemIds=[],b.store.fetch({onComplete:function(a){return dojo.forEach(a,function(a,c){if(0<
a.id)return b.itemIds.push(a.id[0]),b.disableToolbarButtons(!1)})}});c.deselectAll();return b.itemIds=[]},disableToolbarButtons:function(a,b){return dijit.byId("ImportProjectResourceGrid-Import-button")._setDisabledAttr(a)},copy:function(){var a,b,c;c=this;a=c.itemIds;if(0<a.length)return b=buildspace.dialog.indeterminateProgressBar({title:e.importingItems+". "+e.pleaseWait+"..."}),b.show(),a={url:"purchaseOrder/copyProjectResourceItems",content:{poId:c.poId,projectId:c.projectId,resourceId:c.resourceId,
ids:[a],_csrf_token:c._csrf_token},handleAs:"json",load:function(a){b.hide();a.success?(c.itemIds=[],c.itemListGrid.refreshGrid()):c.itemIds=[];return c.dialogWidget.hide()},error:function(a){c.itemIds=[];b.hide();return c.dialogWidget.hide()}},dojo.xhrPost(a)},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,k.disconnect);return delete this._connects}});g=h("buildspace.apps.PurchaseOrder.ImportProjectResourceGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",
gutters:!1,poId:-1,projectId:-1,resourceId:-1,type:null,gridOpts:{},postCreate:function(){var a,b,c;this.inherited(arguments);p.mixin(this.gridOpts,{type:this.type,poId:this.poId,projectId:this.projectId,resourceId:this.resourceId,region:"center"});c=new m(this.gridOpts);"tree"===this.type&&(b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"}),b.addChild(new dijit.form.Button({id:"ImportProjectResourceGrid-Import-button",label:e.copyToPurchaseOrder,iconClass:"icon-16-container icon-16-import",
disabled:!0,onClick:function(){return c.copy()}})),this.addChild(b));this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:c,region:"center"}));if(b=dijit.byId("rfqCopyFromResourceLibrary-stackContainer"))return a=document.createElement("div"),a=new t({title:buildspace.truncateString(this.title,60),executeScripts:!0},a),b.addChild(a),a.set("content",this),b.selectChild(a)}});return h("buildspace.apps.PurchaseOrder.ImportProjectResourceDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",
projectId:-1,poId:-1,itemListGrid:null,buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){r.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===q.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,b,c,d,f;c=this;a=new dijit.layout.BorderContainer({style:"padding:0px;width:900px;height:400px;",
gutters:!1});f=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});f.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));b=new l;d=dojo.data.ItemFileWriteStore({url:"purchaseOrder/getProjectResources/pid/"+this.projectId});b=new g({poId:this.poId,gridOpts:{store:d,itemListGrid:c.itemListGrid,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",
formatter:b.rowCountCellFormatter},{name:e.description,field:"name",width:"auto"}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);if(0<a.id&&null!==a.name[0])return c.createTradeGrid(a)}}});b=this.makeGridContainer(b);a.addChild(f);a.addChild(b);return a},createTradeGrid:function(a){var b,c,d;c=this;b=new l;d=new dojo.data.ItemFileWriteStore({url:"purchaseOrder/getProjectResourceTrades/pid/"+c.projectId+"/id/"+a.id});return new g({title:a.name,poId:c.poId,gridOpts:{store:d,itemListGrid:c.itemListGrid,
dialogWidget:c,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:e.description,field:"description",width:"auto",formatter:b.treeCellFormatter}],onRowDblClick:function(b){b=this.getItem(b.rowIndex);if(0<b.id&&null!==b.description[0])return c.createItemGrid(a,b)}}})},createItemGrid:function(a,b){var c,d;c=new l;d=new dojo.data.ItemFileWriteStore({url:"purchaseOrder/getProjectResourceItems/poId/"+this.poId+"/pid/"+this.projectId+"/rid/"+
a.id+"/id/"+b.id});return new g({title:b.description,poId:this.poId,projectId:this.projectId,resourceId:a.id,type:"tree",gridOpts:{store:d,itemListGrid:this.itemListGrid,dialogWidget:this,_csrf_token:b._csrf_token,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:e.description,field:"description",width:"auto",formatter:c.treeCellFormatter},{name:e.type,field:"type",width:"80px",styles:"text-align:center;",formatter:c.typeCellFormatter},
{name:e.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:c.unitIdCellFormatter},{name:e.totalQty,field:"total_qty",width:"120px",styles:"text-align:right;",formatter:c.unEditableNumberCellFormatter}]}})},makeGridContainer:function(a){var b,c;(c=dijit.byId("rfqCopyFromResourceLibrary-stackContainer"))&&dijit.byId("rfqCopyFromResourceLibrary-stackContainer").destroyRecursive();c=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"rfqCopyFromResourceLibrary-stackContainer"});
a=new dijit.layout.ContentPane({title:e.resource,content:a});c.addChild(a);a=new dijit.layout.StackController({region:"top",containerId:"rfqCopyFromResourceLibrary-stackContainer"});b=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:a});a=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});a.addChild(c);a.addChild(b);dojo.subscribe("rfqCopyFromResourceLibrary-stackContainer-selectChild",
"",function(a){var b,c,d;if(c=dijit.byId("rfqCopyFromResourceLibrary-stackContainer")){b=c.getChildren();a=dojo.indexOf(b,dijit.byId(a.id));a+=1;for(d=[];b.length>a;)c.removeChild(b[a]),b[a].destroyRecursive(!0),d.push(a+=1);return d}});return a}})})}).call(this);
