define("buildspace/apps/Location/ProjectLocationManagement/AssignedLocationDialog","dojo/_base/declare dojo/_base/lang dojo/keys dojo/dom-style dijit/layout/ContentPane dojo/i18n!buildspace/nls/Location".split(" "),function(g,k,l,m,h,b){var n=g("buildspace.apps.ProjectLocationManagement.AssignedLocationDialog.LocationAssignmentContainer",dijit.layout.BorderContainer,{style:"padding:0;margin:0;width:100%;height:100%;",gutters:!1,locationAssignment:null,tabContainer:null,postCreate:function(){this.inherited(arguments);
var a=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});a.addChild(new dijit.form.Button({label:b.removeLocation,iconClass:"icon-16-container icon-16-delete",style:"outline:none!important;",onClick:k.hitch(this,"removeLocation")}));this.addChild(a);var c=[],d=[];this.locationAssignment.hasOwnProperty("predefined_location_code")&&dojo.forEach(this.locationAssignment.predefined_location_code,function(a){c.push(String(a.name))});this.locationAssignment.hasOwnProperty("project_structure_location_code")&&
dojo.forEach(this.locationAssignment.project_structure_location_code,function(a){d.push(String(a.name))});a=new h({content:'<div class="buildspace-form"><fieldset>\n<legend>'+b.predefinedLocationCodes+'</legend>\n<div style="height:2px;">&nbsp;</div>\n<p>'+c.join(" <span style='color:blue'> > </span>")+'</p></fieldset></div><div class="buildspace-form"><fieldset>\n<legend>'+b.projectStructureLocationCodes+'</legend>\n<div style="height:2px;">&nbsp;</div>\n<p>'+d.join(" <span style='color:blue'> > </span>")+
"</p></fieldset></div>",region:"top",style:"height:auto;"});this.addChild(a)},removeLocation:function(){var a=this,c=this.tabContainer,d=this.baseDialog.billItem,f=this.locationAssignment,e=buildspace.dialog.indeterminateProgressBar({title:b.deleting+". "+b.pleaseWait+"..."});new buildspace.dialog.confirm(b.removeLocation,b.removeLocationMsg,90,320,function(){e.show().then(function(){dojo.xhrPost({url:"location/removeAssignedLocation",content:{id:f.id,_csrf_token:d._csrf_token},handleAs:"json",load:function(b){e.hide();
b.success&&(c.removeChild(a),a.destroyRecursive(),(b=dijit.byId("location_assignment-project_item_grid-"+a.baseDialog.baseApp.project.id))&&b.reload(),a.baseDialog.baseApp.resetBQLocationTab(),0==c.getChildren().length&&a.baseDialog.hide())},error:function(a){e.hide()}})})})}}),p=g("buildspace.apps.ProjectLocationManagement.AssignedLocationDialog.MainContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",gutters:!1,baseDialog:null,postCreate:function(){this.inherited(arguments);
var a=new h({content:'<div class="buildspace-form"><fieldset>\n<legend>'+b.billItem+'</legend>\n<div style="height:2px;">&nbsp;</div>\n<p>'+String(this.baseDialog.billItem.description)+"</p></fieldset></div>",region:"top",style:"height:auto;"}),c=new dijit.layout.TabContainer({region:"center",style:"padding:0px;margin:0px;border:0px;width:100%;height:100%;"}),d=this.baseDialog.locationAssignments,f=1,e;for(e in d)d[e].id=parseInt(e),c.addChild(new n({title:b.location+" "+f,region:"center",baseDialog:this.baseDialog,
tabContainer:c,locationAssignment:d[e]})),f++;this.addChild(a);this.addChild(c)}});return g("buildspace.apps.ProjectLocationManagement.AssignedLocationDialog",dijit.Dialog,{title:b.listOfLocationsAssigned,style:"padding:0px;margin:0px;",billItem:null,locationAssignments:null,baseApp:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){m.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display=
"none";this.inherited(arguments)},_onKey:function(a){a.keyCode==l.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:780px;height:420px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,
"hide")}));a.addChild(c);a.addChild(new p({region:"center",baseDialog:this}));return a}})});
