(function(){define("buildspace/apps/CompanyDirectories/OtherInformation/CompanyOtherInformationContainer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange dojo/_base/event dojo/keys dojo/dom-style dijit/focus dojo/_base/html dojo/request/xhr dijit/Toolbar dijit/form/Button dijit/PopupMenuItem dojo/request dijit/layout/BorderContainer buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/Formatter ./CompanyOtherInformationForm dojo/i18n!../../../nls/CompanyDirectories".split(" "),
function(g,t,u,v,w,x,m,y,z,A,B,C,D,n,h,E,k,p,F,q,l,e){var r=g("buildspace.apps.CompanyDirectories.OtherInformation.CompanyOtherInformationGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",keepSelection:!0,rowSelector:"0px",region:"center",companyOtherInformationGridContainer:null,constructor:function(a){return this.rearranger=m(this,{})},canSort:function(a){return!1},noDataMessage:e.noOtherInformationAvailableInGrid,editable:!0,postCreate:function(){this.inherited(arguments);return this.on("RowClick",
function(a){return(a=this.getItem(a.rowIndex))&&0<a.id[0]&&this.editable?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0)})},onRowDblClick:function(a){if(0<this.getItem(a.rowIndex).id[0])return this.editExistingOtherInformation(this.getItem(a.rowIndex))},editExistingOtherInformation:function(a){var d,b;b=this;d=new buildspace.dialog.indeterminateProgressBar({title:e.processing+"..."});d.show();return k.get("companyDirectories/getOtherInformation",{query:{companyId:b.companyId,otherInformationId:a.id},
handleAs:"json"}).then(function(c){var f;f=new l({companyId:b.companyId,otherInformationId:a.id,formInfo:c.otherInformationForm,companyOtherInformationGrid:b,editable:b.editable});c=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",gutters:!1,region:"center"});c.addChild(f);b.makePane(e.editOtherInformation,c);return d.hide()},function(a){return d.hide()})},deleteRow:function(a){var d,b,c;b=this;a=this.getItem(a);d=buildspace.dialog.indeterminateProgressBar({title:e.deleting+
". "+e.pleaseWait+"..."});d.show();c={url:"companyDirectories/deleteOtherInformation",content:{otherInformationId:a.id,_csrf_token:a._csrf_token},handleAs:"json",load:function(a){d.hide();return a.success?b.refreshGrid():console.log(a)},error:function(a){return d.hide()}};return new buildspace.dialog.confirm(e.deleteOtherInformationTitle,e.deleteOtherInformationMsg,80,320,function(){return dojo.xhrPost(c)},function(){return d.hide()})},refreshGrid:function(){this.store.save();this.store.close();return this.setStore(this.store)},
makePane:function(a,d){var b,c;c=dijit.byId("companyDirectoriesOtherInformationMaintenance-stackContainer");b=new dijit.layout.ContentPane({title:a,content:d});c.addChild(b);return c.selectChild(b)},disableToolbarButtons:function(a,d){var b=dijit.byId("deleteOtherInformationFromCompanyDirectories");b&&b.set("disabled",a)}});return g("buildspace.apps.CompanyDirectories.OtherInformation.CompanyOtherInformationContainer",p,{companyId:-1,dialogContainer:null,style:"height:100%; width:100%; padding: 0; margin: 0;",
title:e.tabOtherInformationDesc,gutters:!1,editable:!0,postCreate:function(){var a,d,b,c,f;this.inherited(arguments);b=this;(c=dijit.byId("companyDirectoriesOtherInformationMaintenance-stackContainer"))&&dijit.byId("companyDirectoriesOtherInformationMaintenance-stackContainer").destroyRecursive();c=b.stackContainer=new dijit.layout.StackContainer({style:"width:100%;height:100%;",region:"center",id:"companyDirectoriesOtherInformationMaintenance-stackContainer"});a=new dojo.data.ItemFileWriteStore({url:"companyDirectories/getOtherInformationListing/companyId/"+
this.companyId,clearOnClose:!0,urlPreventCache:!0});d=new r({structure:this.getGridLayout(),store:a,companyId:this.companyId,escapeHTMLInData:!1,editable:this.editable});a=new dijit.layout.BorderContainer({region:"top",gutters:!1});this.editable&&(f=new n({region:"top",style:"outline:none!important;border:none;padding:2px;overflow:hidden;"}),f.addChild(new h({label:e.addNewOtherInformation,iconClass:"icon-16-container icon-16-add",disabled:this.editable?!1:!0,onClick:function(){var a;a=new buildspace.dialog.indeterminateProgressBar({title:e.processing+
"..."});a.show();return k.get("companyDirectories/getOtherInformation",{query:{companyId:b.companyId,otherInformationId:-1},handleAs:"json"}).then(function(c){var f;f=new l({companyId:b.companyId,otherInformationId:-1,formInfo:c.otherInformationForm,companyOtherInformationGrid:d,editable:b.editable});c=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",gutters:!1,region:"center"});c.addChild(f);d.makePane(e.addNewOtherInformation,c);return a.hide()},function(b){return a.hide()})}})),
f.addChild(new dijit.ToolbarSeparator),f.addChild(new h({label:e["delete"],id:"deleteOtherInformationFromCompanyDirectories",iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:function(){return d.deleteRow(d.selection.selectedIndex)}})),a.addChild(f));a.addChild(d);a=new dijit.layout.ContentPane({title:e.tabOtherInformationDesc,content:a});c.addChild(a);a=new dijit.layout.StackController({region:"top",containerId:"companyDirectoriesOtherInformationMaintenance-stackContainer"});a=new dijit.layout.ContentPane({style:"padding: 0px; overflow: hidden;",
baseClass:"breadCrumbTrail",region:"top",content:a});this.addChild(c);this.addChild(a);return dojo.subscribe("companyDirectoriesOtherInformationMaintenance-stackContainer-selectChild","",function(a){var b,c,d;if(c=dijit.byId("companyDirectoriesOtherInformationMaintenance-stackContainer")){b=c.getChildren();a=dojo.indexOf(b,dijit.byId(a.id));a+=1;for(d=[];b.length>a;)c.removeChild(b[a]),b[a].destroyRecursive(),d.push(a+=1);return d}})},getGridLayout:function(){return[{name:"No",field:"id",width:"30px",
styles:"text-align: center;",formatter:(new q).rowCountCellFormatter},{name:e.title,field:"title",width:"auto"},{name:e.lastUpdatedAt,field:"updated_at",width:"120px",styles:"text-align: center;"}]}})})}).call(this);
