(function(){define("buildspace/apps/CompanyDirectories/OtherInformation/CompanyOtherInformationForm","dojo/_base/declare dojo/on dojo/_base/lang dojo/parser dojo/_base/connect dojo/dom-attr dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/Toolbar dijit/form/Button dijit/layout/BorderContainer dijit/form/ValidationTextBox dijit/form/SimpleTextarea dijit/registry dojo/dom-style dojo/dom-form dojo/request dojox/validate/web dijit/form/Select dijit/form/FilteringSelect dojo/store/Memory dojox/form/Manager dojox/grid/enhanced/plugins/Rearrange dojo/text!./templates/companyOtherInformationForm.html buildspace/widget/grid/cells/Formatter dojo/i18n!../../../nls/CompanyDirectories".split(" "),
function(h,k,l,B,q,C,r,t,u,v,w,x,y,D,E,F,e,G,m,H,I,J,K,L,M,z,A,d){var n,p;p=h("buildspace.apps.CompanyDirectories.OtherInformation.UploadedFilesGrid",dojox.grid.EnhancedGrid,{style:"border:none;height:135px;",keepSelection:!0,rowSelector:"0px",companyOtherInformationForm:null,escapeHTMLInData:!1,noDataMessage:d.noUploadedFileAvailableInGrid,editable:!0,postCreate:function(){var a;this.inherited(arguments);a=this;return this._connects.push(q.connect(this,"onCellClick",function(b){var c;c=this.getItem(b.rowIndex);
return"delete"===b.cell.field&&a.editable?a.deleteUploadedFile(c):!1}))},canSort:function(a){return!1},deleteUploadedFile:function(a){var b,c;c=this;b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return m.post("companyDirectories/deleteUploadedFile",{data:{fileId:a.id,_csrf_token:a._csrf_token},handleAs:"json"}).then(function(a){b.hide();if(a.success)return c.refreshGrid()},function(a){return b.hide()})},refreshGrid:function(){this.store.save();this.store.close();
return this.setStore(this.store)}});n=h("buildspace.apps.CompanyDirectories.OtherInformation.CompanyOtherInformationForm",[r,t,u,v],{baseClass:"buildspace-form",companyId:-1,otherInformationId:-1,newOtherInformationId:-1,templateString:z,region:"center",style:"overflow: auto;",formInfo:null,companyOtherInformationGrid:null,grid:null,nls:d,editable:!0,constructor:function(a){if(0<a.otherInformationId)return a.newOtherInformationId=a.otherInformationId},startup:function(){this.inherited(arguments);
this["otherInformationForm-"+this.companyId+"-"+this.otherInformationId].setFormValues(this.formInfo);this.editable||this["otherInformationForm-"+this.companyId+"-"+this.otherInformationId].disable();return 0<this.otherInformationId?this.generateUploadedFilesGrid():this.hideUploaderFilesGrid()},clearInputErrorMsgs:function(){var a,b,c,d;c={description:null};d=[];for(b in c)a=this["error-"+b],a.innerHTML=c[b],d.push(e.set(a,"display","none"));return d},save:function(){var a,b,c;c=this;this.clearInputErrorMsgs();
if(!this["otherInformationForm-"+this.companyId+"-"+this.otherInformationId].validate())return!1;a=dojo.formToObject(this["otherInformationForm-"+this.companyId+"-"+this.otherInformationId].id);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});0<c.newOtherInformationId?l.mixin(a,{companyId:c.companyId,otherInformationId:c.newOtherInformationId}):l.mixin(a,{companyId:c.companyId,otherInformationId:c.otherInformationId});b.show();return m.post("companyDirectories/updateOtherInformation",
{data:a,handleAs:"json"}).then(function(a){var d,f,g;b.hide();if(a.success&&0<a.id){if(c.newOtherInformationId=a.id,c.companyOtherInformationGrid.refreshGrid(),a.isNew)return c.generateUploadedFilesGrid(a.id)()}else{g=[];for(f in a.errorMsgs)"username"!==f?(d=c["error-"+f],d.innerHTML=a.errorMsgs[f],g.push(e.set(d,"display","block"))):g.push(void 0);return g}},function(a){return b.hide()})},hideUploaderFilesGrid:function(){return e.set(this.uploadedFilesContainer,"display","none")},createUploader:function(){if(this.editable){var a=
this;this.uploader=new dojox.form.Uploader({label:d.fileUploadDesc,uploadOnSelect:!0,iconClass:"icon-16-container icon-16-upload",style:"height:24px;",url:"companyDirectories/uploadOtherInformationFile/otherInformationId/"+a.newOtherInformationId,name:"company_other_information[fileUpload]",disabled:this.editable?!1:!0});k(this.uploader,"Begin",function(b){a.pb=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b=a["error-fileUpload"];b.innerHTML=null;e.set(b,"display","none");
return a.pb.show()});k(this.uploader,"Complete",function(b){var c;a.pb.hide();c=a["error-fileUpload"];if(b.success)return c.innerHTML=null,e.set(c,"display","none"),a.grid.refreshGrid();c.innerHTML=b.errorMsgs.global_errors[0];return e.set(c,"display","block")});this.companyDirectoriesOtherInformationFileUploader.appendChild(this.uploader.domNode);this.uploader.startup()}},generateUploadedFilesGrid:function(a){null==a&&(a=this.otherInformationId);e.set(this.uploadedFilesContainer,"display","block");
this.createUploader();a=new dojo.data.ItemFileWriteStore({url:"companyDirectories/otherInformationFileListing/otherInformationId/"+a,clearOnClose:!0,urlPreventCache:!0});this.grid=new p({structure:this.getGridLayout(),store:a,companyOtherInformationForm:this,editable:this.editable});this.grid.placeAt(this.uploadedFilesGrid);return this.grid.startup()},getGridLayout:function(){var a,b;b=[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:(new A).rowCountCellFormatter},{name:d.fileName,
field:"file_name",width:"auto"},{name:d.uploadedAt,field:"created_at",width:"120px",styles:"text-align: center;"},{name:d.download,field:"download",width:"120px",styles:"text-align: center;"}];this.editable&&(a={name:d["delete"],field:"delete",width:"80px",styles:"text-align: center;",formatter:function(){return'<a href="javascript:void(0);">'+d.remove+"</a>"}},b.push(a));return b}});return h("buildspace.apps.CompanyDirectories.OtherInformation.CompanyOtherInformationFormContainer",y,{companyId:-1,
otherInformationId:-1,style:"width:100%;height:100%;padding:0;margin:0;",gutters:!1,formInfo:null,region:"top",companyOtherInformationGrid:null,editable:!0,postCreate:function(){this.inherited(arguments);var a=new n({companyId:this.companyId,otherInformationId:this.otherInformationId,formInfo:this.formInfo,companyOtherInformationGrid:this.companyOtherInformationGrid,editable:this.editable});if(this.editable){var b=new w({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});b.addChild(new x({label:d.save,
iconClass:"icon-16-container icon-16-save",disabled:this.editable?!1:!0,onClick:function(){return a.save()}}));this.addChild(b)}return this.addChild(a)}})})}).call(this);
