(function(){define("buildspace/apps/SubPackageReport/PrintPreviewDialog/PrintSelectedItemRateAndTotalGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/TenderingReport".split(" "),function(k,u,v,w,x,y,z,p,q,l,A,r,t,d){var m,n;m=k("buildspace.apps.SubPackageReport.SelectedItemRateAndTotalGrid",dojox.grid.EnhancedGrid,
{style:"border-top:none;",region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(c,function(a,c){var b=dojo.attr(a,"rowSpan");(!b||2>b)&&dojo.attr(a,"rowSpan",2)})}}});n=k("buildspace.apps.SubPackageReport.SelectedItemRateAndTotalGridContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,subPackageId:-1,billId:null,dialog:null,store:null,structure:null,selectedItems:[],type:null,printURL:null,exportURL:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new m({store:b.store,structure:b.structure,selectedItems:b.selectedItems});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,
iconClass:"icon-16-container icon-16-print",onClick:function(a){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+
"..."});b.show();return l.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new r({title:a.dialog.title,selectedRows:a.selectedItems,type:a.type,printURL:a.printURL,exportURL:a.exportURL,subPackageId:a.subPackageId,billId:a.billId,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return k("buildspace.apps.SubPackageReport.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,companyId:-1,
companyName:null,subPackage:null,bill:null,data:null,type:null,selectedItems:[],printURL:null,exportURL:null,buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){q.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===p.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,
b,c;b={};a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});this.type&&l.post("subPackageReporting/getSubContractors",{sync:!0,handleAs:"json",data:{sid:this.subPackage.id,type:this.type}}).then(function(a){return b=a},function(a){return console.log(a)});c=new n({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,subPackageId:this.subPackage.id,billId:this.bill?this.bill.id:null,selectedItems:this.selectedItems,structure:this.constructGridStructure(b),
type:this.type,printURL:this.printURL,exportURL:this.exportURL});a.addChild(c);return a},constructGridStructure:function(a,b,c){var g,f,e,h;null==a&&(a=[]);c=new t;b=[{name:"No",field:"id",width:"30px",rowSpan:2,styles:"text-align: center;",formatter:c.rowCountCellFormatter},{name:d.billReference,field:"bill_ref",width:"80px",rowSpan:2,styles:"text-align:center; color: red;",formatter:c.billRefCellFormatter,noresize:!0},{name:d.description,field:"description",width:2<a.length?"380px":"auto",rowSpan:2,
formatter:c.printPreviewTreeCellFormatter,noresize:!0},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:c.unitIdCellFormatter,noresize:!0,rowSpan:2},{name:d.quantity,field:"total_qty",width:"70px",rowSpan:2,styles:"text-align:right;color:blue;",formatter:c.unEditableNumberAndTextCellFormatter,noresize:!0},{name:d.rate,field:"rate-value",width:"100px",styles:"text-align:right;color:blue;",formatter:c.unEditableCurrencyCellFormatter,noresize:!0},{name:d.total,field:"total_est_amount",
width:"100px",styles:"text-align:right;color:blue;",formatter:c.unEditableCurrencyCellFormatter,noresize:!0}];h=[];h.push({name:d.estimate,styles:"text-align:center;",headerClasses:"staticHeader",colSpan:2});for(f in a)for(f in e=a[f].selected?"blue":"black",g=buildspace.truncateString(a[f].name,28),h.push({name:'<span style="color:'+e+'">'+g+"</span>",styles:"text-align:center;color:"+e+";",headerClasses:"staticHeader",colSpan:2}),e=[{name:'<span style="color:'+e+'">'+d.rate+"</span>",field:a[f].id+
"-rate-value",styles:"text-align:right;color:"+e+";",width:"100px",formatter:c.printPreviewTendererRateCellFormatter,noresize:!0},{name:'<span style="color:'+e+'">'+d.total+"</span>",field:a[f].id+"-grand_total",styles:"text-align:right;color:"+e+";",width:"100px",formatter:c.printPreviewTendererCurrencyCellFormatter,noresize:!0}],e)g=e[f],b.push(g);return[b,h]}})})}).call(this);
