define("dojo/_base/declare dojo/_base/lang dojo/dom-style dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dojo/_base/array dijit/_WidgetsInTemplateMixin dijit/form/Form dijit/form/Button dijit/form/ValidationTextBox dijit/Toolbar dijit/TitlePane dojox/calendar/Calendar dijit/Calendar dojo/i18n!buildspace/nls/GlobalCalendarMaintenance dojo/text!./templates/eventForm.html dojo/text!./templates/calendarSelectForm.html dojo/store/Observable dojo/store/Memory dojo/data/ObjectStore dojo/store/DataStore dojo/data/ItemFileWriteStore dijit/form/FilteringSelect dijit/form/Select dojo/html dojo/date".split(" "),
function(g,w,k,l,m,n,H,p,I,J,K,L,q,x,y,e,z,A,r,B,C,t,u,v,D,M,N){var E=g("buildspace.apps.GlobalCalendarMaintenance.GlobalCalendarMaintenanceForm",[l,m,n,p],{templateString:z,baseClass:"buildspace-form",region:"center",calendarObj:null,formContainerObj:null,nls:e,_csrf_token:null,style:"overflow:auto;",postCreate:function(){this.inherited(arguments);var a=this;this.isHolidayCheckBox.set("checked",!0);var b=this.stateSelectStore=new dojo.data.ItemFileReadStore({url:"projectBuilder/getStateByCountry/regionId/-1"});
this.stateSelect=(new v({name:"global_calendar[subregion_id]",store:b,style:"width: 100%;padding:2px 0;margin-top:3px;",searchAttr:"name",readOnly:!0,required:!1})).placeAt(this.stateSelectDivNode);dojo.xhrGet({url:"globalCalendarMaintenance/getEventTypeOptions",handleAs:"json",load:function(b){a.eventForm.setFormValues(b.formValues);a.eventTypeSelect=(new D({required:!0,name:"global_calendar[event_type]",style:"width:100%;padding:2px 0!important;margin-top:3px;",store:new C({objectStore:new B({data:b.eventTypeOptions})}),
onChange:function(b){a.formContainerObj.refreshStateSelect(b);a.toogleIsHolidayDiv(b)}})).placeAt(a.eventTypeSelectDivNode)}});this.evtStartDate.on("change",function(){a.evtEndDate.constraints.min=this.get("value")});this.evtEndDate.on("change",function(){a.evtStartDate.constraints.max=this.get("value")});this.evtStartDate.set("value",new Date);this.evtEndDate.set("value",new Date);this.saveItemButton.on("click",function(b){a.formContainerObj.save()});this.deleteItemButton.on("click",function(b){a.formContainerObj.deleteEvent()})},
toogleIsHolidayDiv:function(a){a==buildspace.constants.EVENT_TYPE_OTHER?k.set(this.isHolidayDiv,"display","block"):k.set(this.isHolidayDiv,"display","none")}}),F=g("buildspace.apps.GlobalCalendarMaintenance.CalendarSelectForm",[l,m,n,p],{templateString:A,baseClass:"buildspace-form",region:"center",calendarObj:null,mainFormObj:null,formContainerObj:null,defaultCountryId:null,nls:e,_csrf_token:null,style:"overflow:auto;",postCreate:function(){this.inherited(arguments);var a=this,b=new dojo.data.ItemFileReadStore({url:"projectBuilder/getCountry"});
this.countrySelect=(new v({name:"global_calendar[region_id]",store:b,value:this.defaultCountryId,style:"padding:2px 0;width: 100%;margin-top:3px;",searchAttr:"name",onChange:function(b){a.formContainerObj.refreshStateSelect();a.formContainerObj.refreshCalendar(b)}})).placeAt(this.countrySelectDivNode);this.saveItemButton.on("click",function(b){a.save()})},save:function(){var a=this,b=this.countrySelect.get("value"),c=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+
"..."});this.eventForm.validate()&&c.show().then(function(){dojo.xhrPost({url:"globalCalendarMaintenance/setDefaultCalendar",content:{countryId:b},handleAs:"json",load:function(b){a.formContainerObj.resetForm();c.hide()},error:function(a){c.hide()}})})}}),G=g("buildspace.apps.GlobalCalendarMaintenance.Calendar",x,{isItemEditable:function(a,b){return!1},isItemResizeEnabled:function(a,b){return this.isItemEditable(a,b)&&a.resizeEnabled},isItemMoveEnabled:function(a,b){return this.isItemEditable(a,b)&&
a.moveEnabled}});return g("buildspace.apps.GlobalCalendarMaintenance.GlobalCalendarMaintenanceFormContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,resource:null,postCreate:function(){this.inherited(arguments);var a=this;dojo.xhrGet({url:"globalCalendarMaintenance/getCalendarSetting",handleAs:"json"}).then(function(b){var c=b.data.default_region_id?b.data.default_region_id:-1;b=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:100%;height:100%;border:0;",
region:"center",gutters:!0});var d=a.calendar=new G({store:new r(new t({store:new u({clearOnClose:!0,url:"globalCalendarMaintenance/getEventsByCountryId/id/"+c})})),dateInterval:"month",cssClassFunc:function(a){return a.calendar},style:"position:absolute;left:10px;top:10px;bottom:30px;right:10px;"}),f=a.form=new E({formContainerObj:a}),c=a.csForm=new F({calendarObj:d,formContainerObj:a,mainFormObj:f,defaultCountryId:c}),d=new dijit.layout.ContentPane({content:d,region:"center",style:"border:0;"}),
h=new dijit.layout.ContentPane({splitter:!1,region:"leading",style:"border:0;padding:10px;margin:0;width:260px;"}),g=a.datePicker=new y({value:new Date,style:"width:250px;",minDate:null,maxDate:null,getClassForDate:function(a,b){if(this.minDate&&this.maxDate){var c=this.dateModule;if(0<=c.compare(a,this.minDate)&&0>=c.compare(a,this.maxDate))return"Highlighted"}return null}}),f=new q({title:e.eventProperties,content:f,region:"center",style:"padding:0;width:250px;margin-top: 10px;"}),c=new q({title:e.calendar,
content:c,region:"center",style:"padding:0;width:250px;margin-top: 10px;"});a.datePicker.on("change",function(b){b=a.datePicker.get("value");a.calendar.set("date",b)});h.addChild(g);h.addChild(c);h.addChild(f);b.addChild(d);b.addChild(h);a.addChild(b);a.configureCalendar()})},selectionChanged:function(a){var b=null==a,c=this;this.editedItem=b?null:w.mixin({},a);b?this.resetForm():(this.form.eventForm.setFormValues({"global_calendar[description]":a.summary,"global_calendar[start_date]":a.startTime,
"global_calendar[end_date]":a.endTime,id:a.id}),this.form.isHolidayCheckBox.set("checked",a.isHoliday),this.csForm.countrySelect.set("value",a.regionId),this.form.eventTypeSelect.set("value",a.eventType),setTimeout(function(){c.form.stateSelect.set("value",a.subRegionId)},320),this.form.deleteItemButton.set("disabled",!1))},resetForm:function(){this.form.eventForm.setFormValues({"global_calendar[description]":"","global_calendar[start_date]":new Date,"global_calendar[end_date]":new Date,id:-1});this.form.isHolidayCheckBox.set("checked",
!0);this.form.eventTypeSelect.set("value",buildspace.constants.EVENT_TYPE_PUBLIC);this.form.deleteItemButton.set("disabled",!0)},configureCalendar:function(){var a=this,b=this.calendar,c=this.datePicker.get("value");this.datePicker.set("value",b.get("date"));b.on("change",function(b){(b=b.newValue)?a.selectionChanged(b):a.resetForm()});b.on("timeIntervalChange",function(b){var c=b.startTime;b=b.endTime;a.datePicker.set("currentFocus",c,!1);a.datePicker.set("minDate",c);a.datePicker.set("maxDate",
b)});this.calendar.set("date",c)},makePane:function(a,b){var c=dijit.byId("GlobalCalendarMaintenance-stackContainer"),d=new dijit.layout.ContentPane({title:a,id:"GlobalCalendarForm",content:b});c.addChild(d);c.selectChild(d)},refreshCalendar:function(a){a=r(new t({store:new u({clearOnClose:!0,url:"globalCalendarMaintenance/getEventsByCountryId/id/"+(a?a:-1)})}));this.calendar.set("store",a)},refreshStateSelect:function(a,b,c){b=b?b:this.csForm.countrySelect.get("value");a=a?a:this.form.eventTypeSelect.get("value");
a==buildspace.constants.EVENT_TYPE_STATE?null!=b&&""!=b&&(this.form.stateSelect.set("readOnly",!1),this.form.stateSelect.set("required",!0)):(this.form.stateSelect.set("readOnly",!0),this.form.stateSelect.set("required",!1));null!=b&&""!=b?this.updateStateSelectStore(b,c):this.form.stateSelect.set("value","")},refreshStateSelectStore:function(a){a=void 0==a||""==a?"":a;this.form.stateSelect.store.close();this.form.stateSelect.set("store",this.form.stateSelectStore);this.form.stateSelect.set("value",
a)},updateStateSelectStore:function(a,b){this.form.stateSelectStore=new dojo.data.ItemFileReadStore({url:"projectBuilder/getStateByCountry/regionId/"+(a?a:0),clearOnClose:!0});this.refreshStateSelectStore(b)},deleteEvent:function(){var a=dojo.formToObject(this.form.eventForm.id),b=buildspace.dialog.indeterminateProgressBar({title:e.deletingData+". "+e.pleaseWait+"..."});if(a.id){var c=this.calendar.store;b.show().then(function(){dojo.xhrPost({url:"globalCalendarMaintenance/eventDelete",content:{id:a.id},
handleAs:"json",load:function(d){d.success&&(c.remove(a.id),b.hide())},error:function(a){b.hide()}})})}},save:function(){var a=this,b=dojo.formToObject(a.form.eventForm.id),c=dojo.formToObject(a.csForm.eventForm.id),d=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),f;for(f in c)b[f]=c[f];this.form.eventForm.validate()&&this.csForm.eventForm.validate()&&d.show().then(function(){dojo.xhrPost({url:"globalCalendarMaintenance/eventAdd",content:b,handleAs:"json",
load:function(b){if(b.success){var c=a.calendar.store;b=b.values;a.form.eventForm.setFormValues({id:b.id});c.put(b);d.hide()}},error:function(a){d.hide()}})})}})});
