define("buildspace/apps/Location/ProjectLocationManagement/LocationAssignment/LocationAssignmentContainer","dojo/_base/declare dojo/json dojo/dom-style dojo/_base/lang dojo/aspect dojo/keys dojo/query dojo/on dojo/dom dojo/number dojo/dom-construct dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./templates/locationSelectionForm.html dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/Filter buildspace/widget/grid/cells/Formatter buildspace/widget/forms/MultiSelectDropDown ../AssignedLocationDialog dojo/i18n!buildspace/nls/Location".split(" "),
function(n,L,M,r,A,N,u,O,P,v,p,B,C,D,E,F,Q,w,x,G,H,e){var I=n("buildspace.apps.ProjectLocationManagement.LocationAssignment.LocationSelectionForm",[B,C,D,E],{templateString:F,baseClass:"buildspace-form",region:"top",style:"border:none;padding:5px;overflow:auto;height:128px;",project:null,nls:e,formData:null,postCreate:function(){this.inherited(arguments)},startup:function(){this.inherited(arguments)},addProjectStructureLocationCodeRow:function(a,b,d){b=parseInt(b);var c,f,g,k,h,m;if(a==buildspace.constants.LOCATION_SEQUENCE_TYPE_TRADE)switch(k=
this.predefinedLocationCodeSelectionTitleTableRow,h=this.predefinedLocationCodeSelectionTableRow,f="predefinedLocationCodeHeadSelect",g="predefinedLocationCodeSelect",m="trade",b){case buildspace.constants.PREDEFINED_LOCATION_CODE_TRADE_LEVEL:c=e.trade;break;case buildspace.constants.PREDEFINED_LOCATION_CODE_ELEMENT_LEVEL:c=e.element;break;default:c=b>buildspace.constants.PREDEFINED_LOCATION_CODE_SUB_ELEMENT_LEVEL?e.subElement+" ("+(b-1)+")":e.subElement}else a==buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION&&
(k=this.projectStructureLocationCodeSelectionTitleTableRow,h=this.projectStructureLocationCodeSelectionTableRow,f="projectStructureLocationCodeHeadSelect",g="projectStructureLocationCodeSelect",c=e.location+" "+(b+1),m="location");var l=1;u("."+f,this.locationSelectionForm.id).forEach(function(a){l>b&&p.destroy(a);l++});l=1;u("."+g,this.locationSelectionForm.id).forEach(function(a){l>b&&p.destroy(a);l++});var y=this,z={t:a,s:b,pid:this.project.id};d&&0<d.length&&r.mixin(z,{"parent_id[]":d});dojo.xhrPost({url:"location/getLocationCodeByLevel",
content:z,handleAs:"json",load:function(e){if(0<e.items.length){var l=p.create("th",{style:"border:none!important;","class":f},k);p.create("label",{innerHTML:c+": "},l,"last");l=p.create("td",{style:"width:140px;","class":g},h);(new G({valueField:"id",textField:"name",name:m,style:"padding:2px;width:128px;",dropDownWidth:"240px",storeSort:[{attribute:"priority",descending:!1},{attribute:"lft",descending:!1},{attribute:"level",descending:!1}],dataStore:new dojo.data.ItemFileReadStore({data:e}),onClick:function(c){c=
this.getSelectedIds();0<c.length?y.addProjectStructureLocationCodeRow(a,b+1,c):y.addProjectStructureLocationCodeRow(a,b,d)}})).placeAt(l,"last")}},error:function(a){}})},getSelectedData:function(){var a=dojo.formToObject(this.locationSelectionForm.id),b,d;if(Array.isArray(a.trade))for(var c=a.trade.length;0<=c;c--){if("undefined"!==typeof a.trade[c]&&a.trade[c]&&0<a.trade[c].length){b=a.trade[c];break}}else b=a.trade;if(Array.isArray(a.location))for(c=a.location.length;0<=c;c--){if("undefined"!==
typeof a.location[c]&&a.location[c]&&0<a.location[c].length){d=a.location[c];break}}else d=a.location;return{trade:b,location:d}},onCancel:function(){}}),J=n("buildspace.apps.ProjectLocationManagement.LocationAssignment.BillGrid",dojox.grid.EnhancedGrid,{type:null,style:"border-top:none;",element:null,region:"center",baseApp:null,constructor:function(a){"tree"==a.type&&(this.escapeHTMLInData=!1,this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}});this.inherited(arguments)},
postCreate:function(){this.inherited(arguments);this.on("RowClick",function(a){if(a.cell){var b=a.cell.field,d=this.baseApp,c=this.getItem(a.rowIndex);if("tree"==this.type&&c&&!isNaN(parseInt(c.id[0]))&&c.has_location[0]&&"has_location"==b){var f=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});f.show().then(function(){dojo.xhrGet({url:"location/getBillItemLocations/",content:{id:c.id},handleAs:"json",load:function(a){f.hide();(new H({baseApp:d,billItem:c,locationAssignments:a})).show()},
error:function(a){f.hide()}})})}}})},canSort:function(a){return!1},onHeaderCellClick:function(a){dojo.hasClass(a.cell.id,"staticHeader")||(a.grid.setSortIndex(a.cell.index),a.grid.onHeaderClick(a))},onHeaderCellMouseOver:function(a){dojo.hasClass(a.cell.id,"staticHeader")||dojo.addClass(a.cellNode,this.cellOverClass)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],d=a.node.children[0].children[0].rows[0].children;
b.parentNode.removeChild(b);dojo.forEach(d,function(a,b){var d=dojo.attr(a,"rowSpan");(!d||2>d)&&dojo.attr(a,"rowSpan",2)})}},reload:function(){this.store.close();this._refresh()}}),t=n("buildspace.apps.ProjectLocationManagement.LocationAssignment.BillGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,project:null,gridOpts:{},postCreate:function(){this.inherited(arguments);r.mixin(this.gridOpts,{type:this.type,project:this.project,
region:"center"});var a=this.grid=new J(this.gridOpts);this.addChild(a);var b=dijit.byId("LocationManagement-location_assignment_"+this.project.id+"-stackContainer");if(b){var d=document.createElement("div"),d=new dijit.layout.BorderContainer({gutters:!1,title:buildspace.truncateString(this.stackContainerTitle,60),id:this.pageId},d);this.region="center";var c=[];this.pageId&&(/^location_assignment-page_project_element-/.test(this.pageId)&&(c=[{description:e.description}]),/^location_assignment-page_project_item-/.test(this.pageId)&&
(c=[{description:e.description},{uom_symbol:e.unit}]));d.addChild(new w({region:"top",editableGrid:!1,grid:a,filterFields:c}));d.addChild(this);b.addChild(d);r.mixin(d,{grid:a});b.selectChild(this.pageId)}}}),K=n("buildspace.apps.ProjectLocationManagement.LocationAssignment.BillContainer",dijit.layout.BorderContainer,{project:null,baseApp:null,region:"center",style:"padding:0px;margin:0px;width:100%;",gutters:!1,postCreate:function(){this.inherited(arguments);var a=this,b=dojo.data.ItemFileWriteStore({clearOnClose:!0,
url:"billManagerImportRate/getProjectBreakdown/id/"+this.project.id}),b=t({stackContainerTitle:e.scheduleOfRates,pageId:"import_rate-page_project-"+this.project.id,project:this.project,gridOpts:{baseApp:this.baseApp,store:b,structure:[{name:"No.",field:"count",width:"40px",styles:"text-align:center;",formatter:q.rowCountCellFormatter},{name:e.description,field:"title",width:"auto",formatter:q.treeCellFormatter},{name:e.billType,field:"bill_type",width:"180px",styles:"text-align:center;",formatter:q.billTypeCellFormatter}],
onRowDblClick:function(b){b=this.getItem(b.rowIndex);isNaN(parseInt(b.id[0]))||null===b.title[0]||b.type[0]!=buildspace.constants.TYPE_BILL||a.createElementGrid(b)}}}),b=this.makeGridContainer(b,buildspace.truncateString(this.project.title,100));this.addChild(b);b.startup()},createElementGrid:function(a){var b=this,d=x(),c=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportRate/getElementList/id/"+a.id});t({stackContainerTitle:a.title,pageId:"location_assignment-page_project_element-"+
this.project.id+"_"+a.id,project:this.project,gridOpts:{baseApp:this.baseApp,store:c,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:d.rowCountCellFormatter},{name:e.description,field:"description",width:"auto"}],onRowDblClick:function(d){var c=this.getItem(d.rowIndex);isNaN(parseInt(c.id[0]))||null===c.description[0]||dojo.xhrGet({url:"billManager/getBillInfo",handleAs:"json",content:{id:String(a.id)}}).then(function(a){b.createItemGrid(c,a)})}}})},createItemGrid:function(a,
b){var d=x(),c=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"location/getBillItemList/id/"+a.id}),f=[],g=0,k={noscroll:!1,width:57.8,cells:[[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:d.rowCountCellFormatter,noresize:!0,rowSpan:2},{name:e.description,field:"description",width:1<b.column_settings.length?"500px":"auto",formatter:d.treeCellFormatter,rowSpan:2},{name:e.type,field:"type",width:"100px",styles:"text-align:center;",formatter:d.typeCellFormatter,noresize:!0,
rowSpan:2},{name:e.location,field:"has_location",width:"100px",styles:"text-align:center;",formatter:q.hasLocationCellFormatter,noresize:!0,rowSpan:2},{name:e.unit,field:"uom_id",width:"100px",styles:"text-align:center;",formatter:d.unitIdCellFormatter,noresize:!0,rowSpan:2}]]},h=[{name:e.prorated+" %",field_name:"percentage",width:"80px",styles:"text-align:right;",formatter:q.percentageCellFormatter},{name:e.qty,field_name:"qty",width:"80px",styles:"text-align:right;",formatter:d.numberCellFormatter},
{name:e.prorated+" "+e.qty,field_name:"prorated_qty",width:"80px",styles:"text-align:right;",formatter:d.numberCellFormatter}];dojo.forEach(b.column_settings,function(a){g++;f.push({name:a.name+"<br>"+e.totalUnit+":"+a.quantity,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+g,colSpan:3});for(var b=0;b<h.length;b++){var c={field:String(a.id)+"-"+h[b].field_name,columnType:"typeColumn",headerClasses:"typeHeader"+g};r.mixin(c,h[b]);k.cells[0].push(c)}});k.cells.push(f);t({stackContainerTitle:a.description,
pageId:"location_assignment-page_project_item-"+this.project.id+"_"+a.id,project:this.project,type:"tree",gridOpts:{id:"location_assignment-project_item_grid-"+this.project.id,baseApp:this.baseApp,store:c,element:a,structure:k}})},makeGridContainer:function(a,b){var d=this.project.id,c=dijit.byId("LocationManagement-location_assignment_"+d+"-stackContainer");c&&dijit.byId("LocationManagement-location_assignment_"+d+"-stackContainer").destroyRecursive();var c=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",
region:"center",id:"LocationManagement-location_assignment_"+d+"-stackContainer"}),f=new dijit.layout.BorderContainer({gutters:!1});f.addChild(new w({grid:a.grid,region:"top",editableGrid:!1,filterFields:[{title:e.description}]}));a.region="center";f.addChild(a);c.addChild(new dijit.layout.ContentPane({title:b,content:f,grid:a.grid}));var f=new dijit.layout.StackController({region:"top",containerId:"LocationManagement-location_assignment_"+d+"-stackContainer"}),g=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",
gutters:!1,region:"center"});g.addChild(c);g.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:f}));dojo.subscribe("LocationManagement-location_assignment_"+d+"-stackContainer-selectChild","",function(a){var b=dijit.byId("LocationManagement-location_assignment_"+d+"-stackContainer");if(b){var c=b.getChildren(),e=dojo.indexOf(c,a);if(c.length>e+1){a.grid.store.save();a.grid.store.close();var f=A.after(a.grid,"_onFetchComplete",
function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;c.length>e+1;)e+=1,b.removeChild(c[e]),c[e].destroyRecursive(!0)}});return g}}),q={rowCountCellFormatter:function(a,b){return 0<a?a:""},treeCellFormatter:function(a,b){var d=this.grid.getItem(b),c=16*d.level;a=null==a?"&nbsp":a;d.type<buildspace.constants.TYPE_BILL&&(a="<b>"+a+"</b>");return'<div class="treeNode" style="padding-left:'+c+'px;"><div class="treeContent">'+a+"&nbsp;</div></div>"},billTypeCellFormatter:function(a,
b){return buildspace.getBillTypeText(a)},hasLocationCellFormatter:function(a,b,d){a||d.customClasses.push("disable-cell");return a?'<div style="cursor:pointer;color:blue;">'+e.assigned.toUpperCase()+"</div>":""},percentageCellFormatter:function(a,b,d){a=v.parse(a);isNaN(a)||0==a||null==a?a="&nbsp;":(b=v.format(a,{places:2})+"%",a=0<=a?'<span style="color:blue;">'+b+"</span>":'<span style="color:#FF0000">'+b+"</span>");return a}};return n("buildspace.apps.Location.ProjectLocationManagement.LocationAssignment.LocationAssignmentContainer",
dijit.layout.BorderContainer,{style:"padding:0;margin:0;width:100%;height:100%;",gutters:!1,project:null,baseApp:null,postCreate:function(){this.inherited(arguments);var a=new dijit.layout.BorderContainer({region:"center",style:"padding:0;width:100%;height:100%;",gutters:!1,liveSplitters:!0}),b=this.locationSelectionForm=new I({project:this.project});a.addChild(b);var d=new K({project:this.project,baseApp:this.baseApp});a.addChild(d);dojo.forEach([buildspace.constants.LOCATION_SEQUENCE_TYPE_TRADE,
buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION],function(a){b.addProjectStructureLocationCodeRow(a,0,null)});this.addChild(a)},save:function(){var a=dijit.byId("location_assignment-project_item_grid-"+this.project.id);if("undefined"==typeof a)buildspace.dialog.alert(e.noBillItemAlert,e.pleaseOpenBillItem+".",90,320);else{var b=this.locationSelectionForm.getSelectedData();if(0<a.selection.getSelected().length&&b.trade&&b.location&&0<b.trade.length&&0<b.location.length){var d=[];dojo.forEach(a.selection.getSelected(),
function(a){a&&!isNaN(parseInt(a.id[0]))&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&d.push(a.id[0])});if(0<d.length&&a.element){var c=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),f=this,g=b.trade.split(","),k=b.location.split(",");c.show().then(function(){dojo.xhrPost({url:"location/locationAssignmentUpdate",content:{"t[]":g,"l[]":k,"bid[]":d,pid:f.project.id,_csrf_token:f.project._csrf_token},
handleAs:"json",load:function(b){if(b.success){var d=a.store;dojo.forEach(b.items,function(a){d.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var c in a)b.hasOwnProperty(c)&&c!=d._getIdentifierAttribute()&&d.setValue(b,c,a[c])}})});d.save()}f.baseApp.resetBQLocationTab();c.hide();a.selection.clear()},error:function(b){c.hide();a.selection.clear()}})})}else a.selection.clear()}else{var h,m;0==a.selection.getSelected().length?(h=e.noItemSelectedAlert,m=e.pleaseSelectItem):b.trade&&0!=b.trade.length?
b.location&&0!=b.location.length||(h=e.noLocationSelectedAlert,m=e.pleaseSelectLocation):(h=e.noTradeSelectedAlert,m=e.pleaseSelectTrade);buildspace.dialog.alert(h,m+".",90,320)}}}})});
