define("dojo/_base/declare dojo/currency dojo/number dojo/keys dojo/dom-style dojo/_base/connect dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dojo/data/ItemFileWriteStore dojox/grid/EnhancedGrid dojox/grid/enhanced/plugins/IndirectSelection dijit/form/Form dojox/form/manager/_Mixin dojox/form/manager/_NodeMixin dojox/form/manager/_ValueMixin dojox/form/manager/_DisplayMixin dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/ValidationTextBox ./TableFooterForm ./FooterForm ./GeneralSettingForm buildspace/apps/ProjectBuilder/Builder dojo/i18n!buildspace/nls/ProjectSummary".split(" "),
function(r,w,x,y,z,t,A,B,C,D,E,X,F,G,H,I,J,K,Y,L,M,Z,N,O,P,Q,c){var R=function(a,b){return a&&0<a.length?"<b>"+a+"</b>":"&nbsp;"},S=function(a,b){b=this.grid.getItem(b);return'<div class="treeNode" style="padding-left:'+16*parseInt(parseInt(String(b.level))-1)+'px;"><div class="treeContent" style="'+(b.is_bold[0]?"font-weight:bold!important;":"")+(b.is_italic[0]?"font-style:italic!important;":"")+(b.is_underline[0]?"text-decoration:underline!important;":"")+'">'+(null==a?"&nbsp":a)+"&nbsp;</div></div>"},
T=function(a,b){b=x.parse(a);isNaN(b)||0==b||null==b?a="&nbsp;":(a=w.format(b),a=0<=b?a:'<span style="color:#FF0000">'+a+"</span>");return a},U=r("buildspace.apps.ProjectSummary.Grid",E,{project:null,style:"border-top:none;",constructor:function(a){this.itemIds=[];this.connects=[];a.project.status_id==buildspace.apps.ProjectSummary.ProjectStatus.STATUS_PRETENDER&&(this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align: center;"}});this.inherited(arguments)},canSort:function(a){return!1},
postCreate:function(){var a=this;this.inherited(arguments);this.project.status_id==buildspace.apps.ProjectSummary.ProjectStatus.STATUS_PRETENDER&&(this._connects.push(t.connect(this,"onCellClick",function(b){a.selectItem(b)})),this._connects.push(t.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)})))},doApplyCellEdit:function(a,b,d){var f=this,e=f.getItem(b),g=f.store,k=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});if(a!==e[d][0]){var h=
{id:e.id,attr_name:d,val:a,_csrf_token:e._csrf_token?e._csrf_token:null},l=f.getCellByField(d);k.show().then(function(){dojo.xhrPost({url:"projectSummary/billStyleReferenceCharUpdate",content:h,handleAs:"json",load:function(p){if(p.success){for(var m in p.data)e.hasOwnProperty(m)&&m!=g._getIdentifierAttribute()&&g.setValue(e,m,p.data[m]);g.save();window.setTimeout(function(){f.focus.setFocusIndex(b,l.index)},10);k.hide()}},error:function(p){k.hide()}})})}this.inherited(arguments)},doCancelEdit:function(a){this.inherited(arguments);
this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},updateStyle:function(a){var b=this,d=this.store,f=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});0<this.itemIds.length&&f.show().then(function(){var e=b.getItem(0);dojo.xhrPost({url:"projectSummary/billFontStyleUpdate",content:{pid:b.project.id,style:a,ids:[b.itemIds],_csrf_token:e._csrf_token},handleAs:"json",load:function(g){g.success&&(dojo.forEach(g.data,function(k){d.fetchItemByIdentity({identity:k.id,
onItem:function(h){d.setValue(h,"is_"+a,k.val)}})}),d.save(),b.selection.deselectAll(),b.itemIds=[],b.disableToolbarButtons(!0),f.hide())},error:function(g){b.selection.deselectAll();b.itemIds=[];b.disableToolbarButtons(!0);f.hide()}})})},selectItem:function(a){var b=a.rowIndex;a=this.selection.selected[b];(b=this.getItem(b))&&this.pushItemIdIntoGridArray(b,a)},pushItemIdIntoGridArray:function(a,b){var d=dojo.indexOf(this.itemIds,parseInt(String(a.id)));b&&0<parseInt(String(a.id))?-1==d&&this.itemIds.push(parseInt(String(a.id))):
-1!=d&&this.itemIds.splice(d,1);this.disableToolbarButtons(0<this.itemIds.length?!1:!0)},toggleAllSelection:function(a){var b=this,d=b.selection;a?(d.selectRange(0,b.rowCount-1),b.itemIds=[],b.store.fetch({onComplete:function(f){dojo.forEach(f,function(e,g){0<parseInt(String(e.id))&&b.itemIds.push(parseInt(String(e.id)))})}})):(d.deselectAll(),b.itemIds=[]);this.disableToolbarButtons(0<b.itemIds.length?!1:!0)},disableToolbarButtons:function(a){dijit.byId("ProjectSummary-"+this.project.id+"_StyleBold-button")._setDisabledAttr(a);
dijit.byId("ProjectSummary-"+this.project.id+"_StyleItalic-button")._setDisabledAttr(a);dijit.byId("ProjectSummary-"+this.project.id+"_StyleUnderline-button")._setDisabledAttr(a)},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,t.disconnect);delete this._connects}}),V=r("buildspace.apps.ProjectSummary.ExportToExcelForm",[F,K,L,M,G,H,I,J],{templateString:'<form data-dojo-attach-point="containerNode"><table class="table-form"><tr><td class="label" style="width:80px;"><label style="display: inline;"></span>'+
c.exportAs+' :</label></td><td><input type="text" name="filename" style="padding:2px;width:220px;" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="trim:true, propercase:true, maxlength:45, required: true"> .xlsx</td></tr></table></form>',project:null,tenderAlternative:null,region:"center",dialogWidget:null,style:"outline:none;padding:0px;margin:0px;border:none;",baseClass:"buildspace-form",startup:function(){this.inherited(arguments);var a=new Date;this.setFormValues({filename:"Project_Summary"+
a.getDate()+(a.getMonth()+1)+a.getFullYear()})},submit:function(){var a=dojo.formToObject(this.id);this.validate()&&(a=a.filename.replace(/ /g,"_"),a=this.tenderAlternative?"TenderAlternativeProjectSummaryXls/"+parseInt(String(this.tenderAlternative.id))+"/"+String(this.project._csrf_token)+"/"+a:"ProjectSummaryXls/"+parseInt(String(this.project.id))+"/"+String(this.project._csrf_token)+"/"+a,window.open(a,"_self"),this.dialogWidget&&this.dialogWidget.hide())}}),W=r("buildspace.apps.ProjectSummary.ExportExcelDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",title:c.exportToExcel,project:null,tenderAlternative:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){z.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==y.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:400px;height:80px;",
gutters:!1}),b=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"}),d=V({project:this.project,tenderAlternative:this.tenderAlternative,dialogWidget:this});b.addChild(new dijit.form.Button({label:c.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({label:c.export,iconClass:"icon-16-container icon-16-export",style:"outline:none!important;",
onClick:dojo.hitch(d,"submit")}));a.addChild(b);a.addChild(d);return a}});return r("buildspace.apps.ProjectSummary",buildspace.apps._App,{win:null,project:null,tenderAlternative:null,projectSummaryData:null,init:function(a){var b=this.project=a.project,d=this.tenderAlternative=a.tenderAlternative;a=this.projectSummaryData=a.projectSummaryData;var f=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:100%;height:100%;overflow:hidden;",gutters:!1,liveSplitters:!0}),e=new dijit.layout.BorderContainer({title:c.summaryView,
style:"padding:0;margin:0;width:100%;height:100%;overflow:hidden;",gutters:!1,liveSplitters:!0}),g=new dijit.layout.BorderContainer({title:c.generalSettings,style:"padding:0;margin:0;width:100%;height:100%;overflow:hidden;",gutters:!1,liveSplitters:!0}),k=new dijit.layout.BorderContainer({title:c.footerText,style:"padding:0;margin:0;width:100%;height:100%;overflow:hidden;",gutters:!1,liveSplitters:!0});if(d){var h=c.ProjectBuilder+" > "+c.projectSummary+" ("+buildspace.truncateString(d.title,60)+
") - "+buildspace.truncateString(b.title,100);var l="projectSummary/getTenderAlternativeBills/id/"+parseInt(String(d.id));var p="TenderAlternativeProjectSummaryPdf/"+parseInt(String(d.id))+"/"+String(b._csrf_token)}else h=c.ProjectBuilder+" > "+c.projectSummary+" - "+buildspace.truncateString(b.title,100),l="projectSummary/getBills/pid/"+parseInt(String(b.id)),p="ProjectSummaryPdf/"+parseInt(String(b.id))+"/"+String(b._csrf_token);h=this.win=new buildspace.widget.Window({title:h,onClose:dojo.hitch(this,
"kill")});var m=new dijit.layout.TabContainer({region:"center",style:"width:100%;height:100%;padding:0;margin:0;outline:none!important;"}),n=b.status_id==buildspace.apps.ProjectSummary.ProjectStatus.STATUS_PRETENDER?!0:!1;l=new U({region:"center",project:b,store:new D({url:l,clearOnClose:!0}),structure:[{name:c.item,field:"reference_char",width:"80px",styles:"text-align:center;",formatter:R,editable:n,cellType:"buildspace.widget.grid.cells.TextBox"},{name:c.description,field:"title",width:"auto",
formatter:S},{name:c.page,field:"page",width:"150px",styles:"text-align:center;"},{name:c.amount+" ("+a.currency_code+")",field:"amount",width:"200px",styles:"text-align:center;",formatter:T}]});n=new dijit.Toolbar({region:"top",style:"outline:none!important;border-top:0px;padding:2px;overflow:hidden;"});n.addChild(new dijit.form.Button({label:c.backToProjectBuilder,iconClass:"icon-16-container icon-16-directional_left",style:"outline:none!important;",onClick:dojo.hitch(this,"openBuilderWin",b)}));
n.addChild(new dijit.ToolbarSeparator);var u=new B({style:"display: none;"});dojo.forEach(["withPrice","withoutPrice"],function(v){u.addChild(new C({label:c[v],onClick:function(){window.open(p+"/"+v,"_blank");return window.focus()}}))});n.addChild(new A({label:c.printToPdf,iconClass:"icon-16-container icon-16-print",style:"outline:none!important;",dropDown:u}));n.addChild(new dijit.ToolbarSeparator);n.addChild(new dijit.form.Button({label:c.exportToExcel,iconClass:"icon-16-container icon-16-spreadsheet",
style:"outline:none!important;",onClick:function(){W({project:b,tenderAlternative:d}).show()}}));if(b.status_id==buildspace.apps.ProjectSummary.ProjectStatus.STATUS_PRETENDER){var q=new dijit.Toolbar({region:"top",style:"outline:none!important;border-top:0px;border-bottom:0px;padding:2px;overflow:hidden;"});q.addChild(new dijit.form.Button({id:"ProjectSummary-"+b.id+"_StyleBold-button",label:c.bold,iconClass:"icon-16-container icon-16-bold",style:"outline:none!important;",disabled:!0,onClick:dojo.hitch(l,
"updateStyle","bold")}));q.addChild(new dijit.ToolbarSeparator);q.addChild(new dijit.form.Button({id:"ProjectSummary-"+b.id+"_StyleItalic-button",label:c.italic,iconClass:"icon-16-container icon-16-italic",style:"outline:none!important;",disabled:!0,onClick:dojo.hitch(l,"updateStyle","italic")}));q.addChild(new dijit.ToolbarSeparator);q.addChild(new dijit.form.Button({id:"ProjectSummary-"+b.id+"_StyleUnderline-button",label:c.underlined,iconClass:"icon-16-container icon-16-underlined",style:"outline:none!important;",
disabled:!0,onClick:dojo.hitch(l,"updateStyle","underline")}));e.addChild(q)}e.addChild(l);e.addChild(new N({project:b,formValues:a.table_form,totalCost:a.total_cost}));k.addChild(new O({project:b,formValues:a.footer_form}));g.addChild(new P({project:b,formValues:a.general_setting_form}));m.addChild(e);m.addChild(k);m.addChild(g);f.addChild(n);f.addChild(m);f.startup();h.addChild(f);h.show();h.startup()},openBuilderWin:function(a){this.kill();this.project=a;this.win=new buildspace.widget.Window({title:c.ProjectBuilder+
" > "+buildspace.truncateString(a.title,100)+" ("+c.status+"::"+a.status[0].toUpperCase()+")",onClose:dojo.hitch(this,"kill")});this.win.addChild(Q({project:a}));this.win.show();this.win.startup()},kill:function(){"undefined"!=typeof this.win&&this.win.close()}})});
