(function(){define("buildspace/apps/StockInReport/InvoiceDeliveryOrderTab/ItemListingGrid","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/request dijit/focus dijit/Toolbar dijit/form/Button dijit/DropDownMenu dijit/form/DropDownButton dijit/MenuItem dijit/layout/BorderContainer buildspace/widget/grid/cells/Formatter buildspace/widget/grid/cells/FormulaTextBox dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/Filter dojo/store/Memory ./PrintPreviewDialog/PrintSelectedInvoiceItemGridDialog dojo/i18n!../../../nls/StockIn".split(" "),
function(f,g,y,z,k,l,m,A,n,B,p,q,r,t,u,C,D,v,w,x,b){var h;h=f("buildspace.apps.StockInReport.InvoiceInformation.ItemListGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",rowSelector:"0px",region:"center",invoice:null,container:null,constructor:function(a){this.rearranger=k(this,{});this.formulatedColumn=l(this,{});return this.plugins={indirectSelection:{headerSelector:!0,width:"40px",styles:"text-align: center;"}}},postCreate:function(){var a;this.inherited(arguments);a=this;this._connects.push(g.connect(this,
"onCellClick",function(c){if(""===c.cell.name)return a.singleCheckBoxSelection(c)}));return this._connects.push(g.connect(this.rowSelectCell,"toggleAllSelection",function(c){return a.toggleAllSelection(c)}))},canSort:function(a){return!1},refreshGrid:function(){this.store.save();this.store.close();return this.setStore(this.store)},singleCheckBoxSelection:function(a){var c,b;c=a.rowIndex;a=this.selection.selected[c];c=this.getItem(c).id[0];b=this.container.itemCheckedStore;return c==buildspace.constants.GRID_LAST_ROW?
!1:a?b.put({id:c}):b.remove(c)},toggleAllSelection:function(a){var c,b,e;e=this.store;b=this.selection;c=this.container.itemCheckedStore;b.selectRange(0,this.rowCount-1);e.fetch({onComplete:function(b){return dojo.forEach(b,function(b,e){var d;d=b.id[0];return d==buildspace.constants.GRID_LAST_ROW?!1:a?c.put({id:d}):c.remove(d)})}});if(!a)return b.deselectAll()}});return f("buildspace.apps.StockIn.InvoiceInformation.ItemListContainer",t,{invoice:null,style:"height:100%;width:100%;padding:0;margin:0;",
gutters:!1,itemCheckedStore:null,postCreate:function(){var a,c,d,e;this.inherited(arguments);this.itemCheckedStore=new w({idProperty:"id"});d=this;c=new dojo.data.ItemFileWriteStore({url:"stockIn/getInvoiceItemListings/invoiceId/"+this.invoice.id[0],clearOnClose:!0,urlPreventCache:!0});c=new h({structure:d.getGridLayout(),store:c,invoice:this.invoice,invoiceId:this.invoice.id[0],escapeHTMLInData:!1,container:d});e=new n({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border-bottom:none;"});
a=new p({style:"display: none;"});a.addChild(new r({label:b.printItemsByResourceTrade,iconClass:"icon-16-container icon-16-print",onClick:function(){return d.openBillPreviewDialogForSelectedItems()}}));e.addChild(new q({label:b.print,id:"stockInReport-invoiceItem-printButton-"+d.invoice.id[0],iconClass:"icon-16-container icon-16-print",dropDown:a}));a=new v({region:"top",grid:c,editableGrid:!1,filterFields:[{description:b.description},{quantity:b.quantity},{uom:b.unit}]});this.addChild(a);this.addChild(e);
return this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:c,region:"center"}))},openBillPreviewDialogForSelectedItems:function(){var a,c,d,e;e=this;d=e.itemCheckedStore;a=[];d.query().forEach(function(b){return a.push(b.id)});a=a.reverse().filter(function(a,b,c){return-1===c.indexOf(a,b+1)}).reverse();c=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});c.show();return m.post("stockInReporting/getPrintPreviewStockOutItems",{handleAs:"json",data:{invoiceId:e.invoice.id[0],
item_ids:JSON.stringify(a)}}).then(function(d){(new x({title:b.printItemsByResourceTrade,invoiceId:e.invoice.id[0],data:d,selectedItems:a})).show();return c.hide()},function(a){console.log(a);return c.hide()})},getGridLayout:function(){var a;a=new u;return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter,noresize:!0},{name:b.description,field:"description",width:"auto",formatter:a.treeCellFormatter,noresize:!0},{name:b.quantity,field:"quantity",width:"100px",
styles:"text-align: right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.rfqQuantityCellFormatter,noresize:!0},{name:b.unit,field:"uom",width:"70px",styles:"text-align: center;",formatter:a.rfqUnitCellFormatter,noresize:!0},{name:b.rate,field:"rates",styles:"text-align:right;",width:"120px",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.currencyCellFormatter,noresize:!0},{name:b.discount+" %",field:"discount_percentage",styles:"text-align:right;",width:"75px",
cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.currencyCellFormatter,noresize:!0},{name:b.tax+" %",field:"tax_percentage",styles:"text-align:right;",width:"75px",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.currencyCellFormatter,noresize:!0},{name:b.totalWithoutTax,field:"total_without_tax",styles:"text-align:right;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0},{name:b.totalWithTax,field:"total",styles:"text-align:right;",width:"100px",
formatter:a.unEditableCurrencyCellFormatter,noresize:!0},{name:b.doQuantity,field:"doQuantity",width:"90px",styles:"text-align: right;",formatter:a.unEditableNumberCellFormatter,noresize:!0},{name:b.balanceQuantity,field:"balanceQuantity",width:"90px",styles:"text-align: right;",formatter:a.unEditableNumberCellFormatter,noresize:!0}]}})})}).call(this);
