define("buildspace/apps/SystemMaintenance/RegionMaintenance/grid","dojo/_base/declare dojo/aspect dijit/layout/BorderContainer dijit/layout/ContentPane dojox/grid/EnhancedGrid dijit/form/Form dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Button dijit/ToolbarSeparator dijit/Toolbar dijit/Menu dijit/MenuItem dojo/keys dojo/_base/event dojo/text!./templates/regionUpdateForm.html buildspace/widget/grid/cells/Formatter dojo/i18n!../../../nls/SystemMaintenance dojo/html dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/Filter".split(" "),
function(g,h,k,l,m,t,u,v,w,f,n,p,x,q,y,z,A,B,d,r,C,D){var E=g("buildspace.apps.SystemMaintenance.RegionMaintenance.Grid",m,{rowSelector:!1,style:"border-top: none",keepSelection:!0,region:"center",store:null,regionMaintenanceGridContainer:null,canSort:function(){return!1},constructor:function(a){this.rearranger=C(this,{})},postCreate:function(){var a=this;this.inherited(arguments);this.on("RowContextMenu",function(b){a.selection.clear();var c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,
!0);a.contextMenu(b);c&&!isNaN(parseInt(c.id[0]))?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)},!0);this.on("RowClick",function(b){(b=a.getItem(b.rowIndex))&&!isNaN(parseInt(b.id[0]))?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)})},disableToolbarButtons:function(a){var b=dijit.byId("editRegionRow-button"),c=dijit.byId("deleteRegionRow-button");b._setDisabledAttr(a);c._setDisabledAttr(a)},dodblclick:function(a){this.onRowDblClick(a)},onRowDblClick:function(a){this.regionMaintenanceGridContainer.editRegion()},
contextMenu:function(a){var b=this.rowCtxMenu=new x;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==y.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},d=this.getItem(a.rowIndex);b&&d&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&r.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),z.stop(a))},contextMenuItems:function(a){if((a=this.getItem(a.rowIndex))&&!isNaN(parseInt(a.id[0]))){this.rowCtxMenu.addChild(new q({label:d.addRegion,iconClass:"icon-16-container icon-16-add",
onClick:dojo.hitch(this.regionMaintenanceGridContainer,"addRegion")}));a=["edit","delete"];for(var b in a){var c=a[b]+"Region";this.rowCtxMenu.addChild(new q({label:d[c],iconClass:"icon-16-container icon-16-"+a[b],onClick:dojo.hitch(this.regionMaintenanceGridContainer,c)}))}}}});m=g("buildspace.apps.RegionMaintenance.RegionMaintenanceFormContainer",k,{style:"padding: 0px; width: 100%; height: 100%",gutters:!1,title:null,rowSelector:null,refreshGrid:function(){this.grid.store.close();this.grid._refresh()},
postCreate:function(){var a=[{name:"No.",field:"id",width:"30px",editable:!1,styles:"text-align: center;",formatter:(new B).rowCountCellFormatter},{name:d.country,field:"country",width:"auto",editable:!1},{name:d.currency_code,field:"currency_code",width:"90px",editable:!1},{name:d.currency_name,field:"currency_name",width:"120px",editable:!1}],b=this.grid=new E({structure:a,store:new dojo.data.ItemFileWriteStore({url:"systemMaintenance/getRegions",clearOnClose:!0}),regionMaintenanceGridContainer:this});
a=new p({region:"top",style:"outline:none!important;padding:2px;overflow:hidden!important;border:none;"});a.addChild(new f({id:"addRegionRow-button",label:d.addRegion,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRegion")}));a.addChild(new n);a.addChild(new f({id:"editRegionRow-button",label:d.editRegion,iconClass:"icon-16-container icon-16-edit",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:dojo.hitch(this,"editRegion")}));a.addChild(new n);a.addChild(new f({id:"deleteRegionRow-button",
label:d.deleteRegion,iconClass:"icon-16-container icon-16-delete",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:dojo.hitch(this,"deleteRegion")}));var c=new k({style:"width: 100%; height: 100%",gutters:!1}),e=this.filterToolbar=new D({region:"top",grid:this.grid,editableGrid:!1,filterFields:[{country:d.country,currency_code:d.currency_code,currency_name:d.currency_name}]});c.addChild(e);c.addChild(a);c.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}));(a=
dijit.byId("regionMaintenance-stackContainer"))&&a.destroyRecursvie();a=this.stackContainer=new dijit.layout.StackContainer({region:"center",style:"width: 100%; height: 100%",id:"regionMaintenance-stackContainer"});b=new l({region:"center",title:d.regions,content:c,grid:b});a.addChild(b);b=new dijit.layout.StackController({region:"top",containerId:"regionMaintenance-stackContainer"});b=new l({style:"padding: 0px; overflow: hidden",baseClass:"breadCrumbTrail",region:"top",content:b});this.addChild(a);
this.addChild(b);dojo.subscribe("regionMaintenance-stackContainer-selectChild","",function(a){var b=dijit.byId("regionMaintenance-stackContainer");if(b){var c=b.getChildren(),d=dojo.indexOf(c,dijit.byId(a.id));for(d+=1;c.length>d;)b.removeChild(c[d]),c[d].destroyRecursive(!0),d+=1}if(a.hasOwnProperty("grid")){a.grid.store.close();var e=h.after(a.grid,"_onFetchComplete",function(){e.remove();this.selection.selectedIndex&&-1<this.selection.selectedIndex&&this.scrollToRow(this.selection.selectedIndex)});
a.grid._refresh()}})},addRegion:function(){var a=this,b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show().then(function(){dojo.xhrGet({url:"systemMaintenance/regionForm",handleAs:"json"}).then(function(c){b.hide();a.regionFormContainer(c,!0)})})},editRegion:function(){if(-1<this.grid.selection.selectedIndex){var a=this,b=this.grid.getItem(this.grid.selection.selectedIndex),c=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b&&!isNaN(parseInt(b.id[0]))&&
c.show().then(function(){dojo.xhrGet({url:"systemMaintenance/regionForm",handleAs:"json",content:{id:b.id}}).then(function(b){c.hide();a.regionFormContainer(b,!1)})})}},deleteRegion:function(){if(-1<this.grid.selection.selectedIndex){var a=this,b=this.grid.getItem(this.grid.selection.selectedIndex),c=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});b&&!isNaN(parseInt(b.id[0]))&&dojo.xhrGet({url:"systemMaintenance/regionPreDelete",content:{id:b.id},handleAs:"json"}).then(function(e){e.can_delete?
buildspace.dialog.confirm(d.confirmationRegion,"<div>"+d.regionDeleteDialogMsg+"<div>",75,320,function(){c.show().then(function(){dojo.xhrPost({url:"systemMaintenance/regionDelete",content:{id:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(d){if(d.success){var e=a.grid.selection.selectedIndex-1;0>e&&(e=0);a.grid.store.deleteItem(b);a.grid.store.save();a.refreshGrid();var f=h.after(a.grid,"_onFetchComplete",function(){f.remove();a.grid.selection.setSelected(e,!0);a.grid.scrollToRow(e)});
a.grid.disableToolbarButtons(!0)}c.hide()},error:function(){c.hide()}})})}):buildspace.dialog.alert(d.itemCannotBeDeleted,d.cannotDeleteUsedElsewhere,75,320)})}},makePane:function(a,b,c){var d=dijit.byId("regionMaintenance-stackContainer");a=new l({title:a,content:b,region:"center",id:c});d.addChild(a);d.selectChild(a)},regionFormContainer:function(a,b){a=this.regionUpdateForm=new F({region:"center",formValues:a,regionMaintenanceGrid:this.grid,regionMaintenanceGridContainer:this});var c=new p({region:"top",
style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new f({label:d.save,id:"regionMaintenance-submitButton",iconClass:"icon-16-container icon-16-save",style:"outline:none!important; width:auto",onClick:dojo.hitch(this.regionUpdateForm,"submit")}));var e=new k({style:"padding: 0px; width: 100%, height: 100%",baseClass:"form",gutters:!1});e.addChild(c);e.addChild(a);this.makePane(b?d.addRegion:d.editRegion,e,"regionUpdateFormContainer")}});var F=g("buildspace.apps.SystemMaintenance.RegionMaintenance.RegionUpdateForm",
[t,u,v,w,dojox.form.manager._Mixin,dojox.form.manager._NodeMixin,dojox.form.manager._ValueMixin,dojox.form.manager._DisplayMixin],{baseClass:"buildspace-form",nls:d,formValues:[],regionMaintenanceGrid:null,regionMaintenanceGridContainer:null,templateString:A,startup:function(){this.inherited(arguments);this.setFormValues(this.formValues);var a=this;dojo.query('[id^="region_input-"]').forEach(function(b){b.onkeypress=function(b){13==b.keyCode&&a.submit()}})},submit:function(){var a=this,b=dojo.formToObject(this.id),
c=buildspace.dialog.indeterminateProgressBar({title:d.savingData+". "+d.pleaseWait+"..."}),e;for(e in b)if("regions[iso]"==e||"regions[iso3]"==e||"regions[continent]"==e)b[e]=b[e].toUpperCase();var f={url:"systemMaintenance/regionUpdate",handleAs:"json",content:b,load:function(b){dojo.query('[id^="regions_error-"]').forEach(function(a){a.innerHTML=""});if(b.success&&a.regionMaintenanceGridContainer){var d=a.regionMaintenanceGrid.rowCount;a.removeForm();a.regionMaintenanceGrid.store.close();a.regionMaintenanceGridContainer.refreshGrid();
a.regionMaintenanceGrid.store.fetch({onComplete:function(){a.regionMaintenanceGrid.setStore(a.regionMaintenanceGrid.store);a.regionMaintenanceGridContainer.refreshGrid();var b=h.after(a.regionMaintenanceGrid,"_onFetchComplete",function(){b.remove();if(this.rowCount<=d){var a=this.selection.selectedIndex;this.scrollToRow(this.selection.selectedIndex);for(var c in this.selection.selected)this.selection.setSelected(c,!1);this.selection.setSelected(a,!0)}else{c=[];for(a in this.store._itemsByIdentity)c.push(a),
this.selection.setSelected(this.store._itemsByIdentity[a]._0,!1);this.scrollToRow(this.store._itemsByIdentity[Math.max.apply(Math,c)]._0);this.selection.setSelected(this.store._itemsByIdentity[Math.max.apply(Math,c)]._0,!0)}})}})}else{b=b.errors;for(var e in b)r.set(a["regions_error-"+e],b[e])}c.hide()},error:function(){c.hide()}};this.validate()&&c.show().then(function(){dojo.xhrPost(f)})},removeForm:function(){var a=dijit.byId("regionUpdateFormContainer");dijit.byId("regionMaintenance-stackContainer").removeChild(a);
a.destroyRecursive()}});return m});
