define("buildspace/apps/PostContractSubPackage/BillManager/StandardBillGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dijit/Menu dojo/number dijit/CheckedMenuItem dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem dijit/MenuSeparator buildspace/widget/grid/cells/Formatter ./ApplyToUnitDialog ./editBillNoteDialog dojo/i18n!buildspace/nls/PostContractSubPackage dojo/on dojox/grid/_Grid dojox/widget/PlaceholderMenuItem buildspace/widget/grid/cells/TextBox".split(" "),
function(h,l,v,w,x,g,y,z,A,B,C,n,p,D,q,E,F,G,r,t,k,b,H){var u=h("buildspace.apps.PostContractSubPackage.BillManager.StandardBillGrid",dojox.grid.EnhancedGrid,{type:null,billId:-1,elementId:0,subPackage:null,itemId:-1,disableEditing:!1,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",markupSettings:null,parentGrid:null,elementGridStore:null,selectedClaimRevision:null,claimRevision:null,updateUrl:null,typeItem:null,project:null,constructor:function(a){this.type=
a.type;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;this.formatter=new r;this.setColumnStructure();this.createHeaderCtxMenu();this.inherited(arguments)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);else this.onCellDblClick(a);else this.onRowDblClick(a)},editableCellDblClick:function(a){},setColumnStructure:function(){var a=this.formatter;this.structure="tree"==this.type?{noscroll:!1,
cells:[[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter,rowSpan:2},{name:b.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,showInCtxMenu:!0,formatter:a.billRefCellFormatter,rowSpan:2,hidden:!0},{name:b.description,field:"description",width:"500px",formatter:a.claimTreeCellFormatter,showInCtxMenu:!0,rowSpan:2},{name:b.type,field:"type",width:"70px",rowSpan:2,type:"dojox.grid.cells.Select",formatter:a.typeCellFormatter,
styles:"text-align:center;",showInCtxMenu:!0,hidden:!0},{name:b.qty,field:"qty_per_unit",width:"90px",styles:"text-align: right;",formatter:a.claimQtyPerUnitCellFormatter,showInCtxMenu:!0,noresize:!0,rowSpan:2},{name:b.unit,field:"uom_symbol",width:"70px",styles:"text-align: center;",formatter:a.unitIdCellFormatter,showInCtxMenu:!0,rowSpan:2},{name:b.rate,field:"rate",width:"70px",styles:"text-align: right;",formatter:a.claimRateLSCellFormatter,editable:!0,cellType:"buildspace.widget.grid.cells.TextBox",
showInCtxMenu:!0,rowSpan:2},{name:b.total,field:"total_per_unit",width:"90px",styles:"text-align: right;color:blue;",formatter:a.unEditableCurrencyCellFormatter,showInCtxMenu:!0,rowSpan:2},{name:b.percent,field:"prev_percentage",width:"70px",headerClasses:"typeHeader1",formatter:a.unEditablePercentageCellFormatter,styles:"text-align: right;"},{name:b.amount,field:"prev_amount",width:"110px",headerClasses:"typeHeader1",formatter:a.unEditableCurrencyCellFormatter,styles:"text-align: right;"},{name:b.percent,
field:"current_percentage",width:"70px",headerClasses:"typeHeader2",styles:"text-align: right;",formatter:a.editableClaimPercentageCellFormatter,editable:!0,cellType:"buildspace.widget.grid.cells.TextBox"},{name:b.amount,field:"current_amount",width:"110px",headerClasses:"typeHeader2",styles:"text-align: right;",formatter:a.claimAmountCellFormatter,editable:!0,cellType:"buildspace.widget.grid.cells.TextBox"},{name:b.percent,field:"up_to_date_percentage",width:"70px",headerClasses:"typeHeader1",styles:"text-align: right;",
formatter:a.editableClaimPercentageCellFormatter,editable:!0,cellType:"buildspace.widget.grid.cells.TextBox"},{name:b.qty,field:"up_to_date_qty",width:"90px",headerClasses:"typeHeader1",styles:"text-align: right;",formatter:a.claimAmountCellFormatter,editable:!0,cellType:"buildspace.widget.grid.cells.TextBox"},{name:b.amount,field:"up_to_date_amount",width:"110px",headerClasses:"typeHeader1",styles:"text-align: right;",formatter:a.claimAmountCellFormatter,editable:!0,cellType:"buildspace.widget.grid.cells.TextBox"}],
[{name:b.previousClaim,styles:"text-align:center;",headerClasses:"staticHeader typeHeader1",colSpan:2},{name:b.currentClaim,styles:"text-align:center;",headerClasses:"staticHeader typeHeader2",colSpan:2},{name:b.upToDateClaim,styles:"text-align:center;",headerClasses:"staticHeader typeHeader1",colSpan:3}]]}:{noscroll:!1,cells:[[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter,noresize:!0,rowSpan:2},{name:b.description,field:"description",width:"auto",
noresize:!0,formatter:a.claimTreeCellFormatter,rowSpan:2},{name:b.total,field:"total_per_unit",width:"90px",styles:"text-align: right;color:blue;",formatter:a.unEditableCurrencyCellFormatter,noresize:!0,rowSpan:2},{name:b.percent,field:"prev_percentage",width:"70px",headerClasses:"typeHeader1",formatter:a.unEditablePercentageCellFormatter,styles:"text-align: right;",noresize:!0},{name:b.amount,field:"prev_amount",width:"110px",headerClasses:"typeHeader1",formatter:a.unEditableCurrencyCellFormatter,
styles:"text-align: right;",noresize:!0},{name:b.percent,field:"current_percentage",width:"70px",headerClasses:"typeHeader2",styles:"text-align: right;",formatter:a.unEditablePercentageCellFormatter,noresize:!0,cellType:"buildspace.widget.grid.cells.TextBox"},{name:b.amount,field:"current_amount",width:"110px",headerClasses:"typeHeader2",styles:"text-align: right;",formatter:a.unEditableCurrencyCellFormatter,noresize:!0,cellType:"buildspace.widget.grid.cells.TextBox"},{name:b.percent,field:"up_to_date_percentage",
width:"70px",headerClasses:"typeHeader1",styles:"text-align: right;",formatter:a.elementClaimEditablePercentageCellFormatter,editable:!0,cellType:"buildspace.widget.grid.cells.TextBox"},{name:b.amount,field:"up_to_date_amount",width:"110px",headerClasses:"typeHeader1",styles:"text-align: right;",formatter:a.elementClaimAmountCellFormatter,editable:!0,cellType:"buildspace.widget.grid.cells.TextBox"}],[{name:b.previousClaim,styles:"text-align:center;",headerClasses:"staticHeader typeHeader1",colSpan:2,
noresize:!0},{name:b.currentClaim,styles:"text-align:center;",headerClasses:"staticHeader typeHeader2",colSpan:2,noresize:!0},{name:b.upToDateClaim,styles:"text-align:center;",headerClasses:"staticHeader typeHeader1",colSpan:2}]]}},canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);this.on("RowContextMenu",function(b){a.selection.clear();a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b)},!0)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&
2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(c,function(a,b){var c=dojo.attr(a,"rowSpan");(!c||2>c)&&dojo.attr(a,"rowSpan",2)})}},createHeaderCtxMenu:function(){if("undefined"!==typeof this.structure){var a=this.structure.cells[0],b=this,c={headerMenu:new dijit.Menu};dojo.forEach(a,function(a,e){a.showInCtxMenu&&c.headerMenu.addChild(new dijit.CheckedMenuItem({label:a.name,
checked:"undefined"===typeof a.hidden||!1===a.hidden?!0:!1,onChange:function(a){var c=!1;a&&(c=!0);b.showHideColumn(c,e)}}))});this.plugins={menus:c}}},showHideColumn:function(a,b){this.beginUpdate();this.layout.setColumnVisibility(b,a);this.endUpdate()},canEdit:function(a,b){var c=this;if(void 0!=a){var d=this.getItem(b),e=a.field;if("tree"!=c.type){if(void 0===d.total_per_unit){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}}else if(void 0===d.total_per_unit||
0>=d.total_per_unit){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}if(d.id==buildspace.constants.GRID_LAST_ROW||void 0!=d.include&&1!=d.include[0]||c.claimRevision.locked_status||c.claimRevision.id!=c.selectedClaimRevision.id){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}if("rate"==e&&(d.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE||g.parse(d.up_to_date_percentage)||g.parse(d.current_percentage)||
g.parse(d.prev_percentage))){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}}return this._canEdit},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==p.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},d=this.getItem(a.rowIndex);b&&d&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&q.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),n.stop(a))},contextMenuItems:function(a){a=
this.getItem(a.rowIndex);0<a.id&&"tree"==this.type?this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:b.editItemNote,iconClass:"icon-16-container icon-16-note",onClick:dojo.hitch(this,"doEditItemNote",a)})):0<a.id&&"tree"!=this.type&&this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:b.editTradeNote,iconClass:"icon-16-container icon-16-note",onClick:dojo.hitch(this,"doEditTradeNote",a)}))},doEditItemNote:function(a){(new k({item:a,billGrid:this,title:b.editItemNote,updateUrl:"billManager/itemNoteUpdate"})).show()},
doEditTradeNote:function(a){(new k({item:a,billGrid:this,title:b.editTradeNote,updateUrl:"billManager/elementNoteUpdate"})).show()},doApplyCellEdit:function(a,e,c){var d=this,f=d.getItem(e),g=d.store;if(void 0!=f[c][0]||a!==f[c][0]){var m=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."}),h={id:f.id,project_id:d.project.id,sub_package_id:d.subPackage.id,type_ref_id:d.typeItem.id,attr_name:c,val:a,_csrf_token:f._csrf_token?f._csrf_token:null},k=this.updateUrl,l=function(a,b){for(var c in a)f.hasOwnProperty(c)&&
c!=b._getIdentifierAttribute()&&b.setValue(f,c,a[c]);b.save()};m.show().then(function(){dojo.xhrPost({url:k,content:h,handleAs:"json",load:function(a){if(a.success){0<f.id&&l(a.item,g);var b=d.getCellByField(c);window.setTimeout(function(){d.focus.setFocusIndex(e,b.index)},10);m.hide()}},error:function(a){m.hide();console.log(a)}})})}d.inherited(arguments)}});return h("buildspace.apps.PostContractSubPackage.BillManager.StandardBillGridBuilder",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;width:100%;height:100%;",
gutters:!1,stackContainerTitle:"",rootProject:null,subPackage:null,billId:-1,elementId:0,disableEditing:!1,itemId:-1,rowSelector:null,typeItem:null,gridOpts:{},type:null,postCreate:function(){var a=this;this.inherited(arguments);l.mixin(this.gridOpts,{subPackage:this.subPackage,billId:this.billId,typeItem:this.typeItem,project:this.rootProject,elementId:this.elementId,type:this.type,region:"center",disableEditing:this.disableEditing,borderContainerWidget:this});var e=this.grid=new u(this.gridOpts);
this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:e,region:"center"}));"tree"!=this.type&&(e=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"}),e.addChild(new dijit.form.Button({id:this.billId+this.billId+"ApplyRow-button",label:b.applyToOtherUnit,iconClass:"icon-16-container icon-16-add",onClick:function(){(new t({rootProject:a.rootProject,subPackage:a.subPackage,typeItem:a.typeItem,billId:a.billId,elementId:a.elementId,url:"subPackagePostContractStandardBillClaim/applyToOtherUnit"})).show()}})),
this.addChild(e));if(e=dijit.byId("subPackagePostContractStandardBill"+this.billId+"-stackContainer")){var c=document.createElement("div"),c=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,45),id:this.pageId,content:this,grid:this.grid},c);e.addChild(c);e.selectChild(this.pageId)}}})});
