define("buildspace/apps/ProjectAnalyzer/buildUpRateSummary","dojo/_base/declare dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Button dijit/form/TextBox dijit/form/CheckBox dijit/form/Select dijit/InlineEditBox dojo/text!./templates/buildUpRateSummary.html dojo/currency dojo/i18n!buildspace/nls/BuildUpGrid".split(" "),function(g,h,k,l,m,q,r,t,n,u,p,d,f){return g("buildspace.apps.ProjectAnalyzer.buildUpRateSummary",[h,k,l,m],{templateString:p,
style:"outline:none;",itemId:-1,nls:f,region:"bottom",_csrf_token:null,container:null,applyConversionFactor:!1,conversionFactorAmount:0,conversionFactorOperator:buildspace.constants.ARITHMETIC_OPERATOR_MULTIPLICATION,totalCost:0,totalCostAfterConversion:0,markup:0,finalCost:0,roundingType:1,constructor:function(a){this.ROUNDING_TYPE_DISABLED=buildspace.constants.ROUNDING_TYPE_DISABLED;this.ROUNDING_TYPE_UPWARD=buildspace.constants.ROUNDING_TYPE_UPWARD;this.ROUNDING_TYPE_DOWNWARD=buildspace.constants.ROUNDING_TYPE_DOWNWARD;
this.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER=buildspace.constants.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER;this.ROUNDING_TYPE_NEAREST_TENTH=buildspace.constants.ROUNDING_TYPE_NEAREST_TENTH;this.ROUNDING_TYPE_DISABLED_TEXT=buildspace.constants.ROUNDING_TYPE_DISABLED_TEXT;this.ROUNDING_TYPE_UPWARD_TEXT=buildspace.constants.ROUNDING_TYPE_UPWARD_TEXT;this.ROUNDING_TYPE_DOWNWARD_TEXT=buildspace.constants.ROUNDING_TYPE_DOWNWARD_TEXT;this.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER_TEXT=buildspace.constants.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER_TEXT;
this.ROUNDING_TYPE_NEAREST_TENTH_TEXT=buildspace.constants.ROUNDING_TYPE_NEAREST_TENTH_TEXT;this.inherited(arguments)},postCreate:function(){this.inherited(arguments);var a=this;dojo.xhrGet({url:"billBuildUpRate/getBuildUpSummary",content:{id:this.itemId},handleAs:"json",load:function(b){a.applyConversionFactor=b.apply_conversion_factor;a.applyConversionFactorNode.set("checked",a.applyConversionFactor);a.doApplyConversionFactor();a.roundingType=b.rounding_type;a.roundingTypeNode.set("value",a.roundingType);
a.conversionFactorAmount=b.conversion_factor_amount;a.conversionFactorAmountNode.set("value",a.conversionFactorAmount);a.conversionFactorOperator=b.conversion_factor_operator;a.conversionFactorOperatorNode.set("value",a.conversionFactorOperator);var c=a.totalCost=d.format(b.total_cost);dojo.attr(a.totalCostNode,"innerHTML",c);c=a.totalCostAfterConversion=d.format(b.total_cost_after_conversion);dojo.attr(a.totalCostAfterConversionNode,"innerHTML",c);c=a.finalCost=d.format(b.final_cost);dojo.attr(a.finalCostNode,
"innerHTML",c);b=a.markup=d.format(b.markup);a.markupNode.set("value",b)},error:function(a){console.log(a)}})},startup:function(){this.inherited(arguments);this.toggleConversionFactorRows(!1)},submitMarkup:function(){var a=this.markupNode.get("value");if(a!=this.markup){var b=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});b.show();var c=this;dojo.xhrPost({url:"billBuildUpRate/buildUpSummaryMarkupUpdate",content:{id:this.itemId,value:a,_csrf_token:this._csrf_token},handleAs:"json",
load:function(a){var e=c.finalCost=d.format(a.final_cost);dojo.attr(c.finalCostNode,"innerHTML",e);a=c.markup=d.format(a.markup);c.markupNode.set("value",a);b.hide()},error:function(a){console.log(a);b.hide()}})}},doApplyConversionFactor:function(){var a=this.applyConversionFactorNode.get("checked");if(a!=this.applyConversionFactor){var b=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});b.show();var c=this;dojo.xhrPost({url:"billBuildUpRate/buildUpSummaryApplyConversionFactorUpdate",
content:{id:this.itemId,value:a,_csrf_token:this._csrf_token},handleAs:"json",load:function(a){c.conversionFactorAmount=a.conversion_factor_amount;c.conversionFactorAmountNode.set("value",c.conversionFactorAmount);c.conversionFactorOperator=a.conversion_factor_operator;c.conversionFactorOperatorNode.set("value",c.conversionFactorOperator);var e=c.totalCostAfterConversion=d.format(a.total_cost_after_conversion);dojo.attr(c.totalCostAfterConversionNode,"innerHTML",e);a=c.finalCost=d.format(a.final_cost);
dojo.attr(c.finalCostNode,"innerHTML",a);b.hide()},error:function(a){console.log(a);b.hide()}})}this.applyConversionFactor=a;this.toggleConversionFactorRows(a)},toggleConversionFactorRows:function(a){if(a){var b=this;dojo.xhrPost({url:"billBuildUpRate/getConversionFactorUom",content:{id:this.itemId},handleAs:"json",load:function(a){new n({name:"bill_item_build_up_rate[conversion_factor_uom_id]",style:"width:100%;",options:a.uomOptions,onChange:function(){b.submitConversionFactorUOM(this.value)}},
b.conversionFactorUOMNode);dojo.query("."+b.itemId+"-conversion_factor-row").style({display:""});b.container.resize()},error:function(a){console.log(a)}})}else dojo.query("."+this.itemId+"-conversion_factor-row").style({display:"none"}),this.container.resize()},submitConversionFactorAmount:function(){var a=this.conversionFactorAmountNode.get("value");if(a!=this.conversionFactorAmount){var b=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});b.show();var c=this;dojo.xhrPost({url:"billBuildUpRate/buildUpSummaryConversionFactorUpdate",
content:{id:this.itemId,val:a,type:"amount",_csrf_token:this._csrf_token},handleAs:"json",load:function(a){c.conversionFactorAmount=a.conversion_factor_amount;c.conversionFactorAmountNode.set("value",c.conversionFactorAmount);var e=c.totalCostAfterConversion=d.format(a.total_cost_after_conversion);dojo.attr(c.totalCostAfterConversionNode,"innerHTML",e);a=c.finalCost=d.format(a.final_cost);dojo.attr(c.finalCostNode,"innerHTML",a);b.hide()},error:function(a){console.log(a);b.hide()}})}},submitConversionFactorOperator:function(){var a=
this.conversionFactorOperatorNode.get("value");if(a!=this.conversionFactorOperator){var b=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});b.show();var c=this;dojo.xhrPost({url:"billBuildUpRate/buildUpSummaryConversionFactorUpdate",content:{id:this.itemId,val:a,type:"operator",_csrf_token:this._csrf_token},handleAs:"json",load:function(a){c.conversionFactorOperator=a.conversion_factor_operator;c.conversionFactorOperatorNode.set("value",c.conversionFactorOperator);var e=c.totalCostAfterConversion=
d.format(a.total_cost_after_conversion);dojo.attr(c.totalCostAfterConversionNode,"innerHTML",e);a=c.finalCost=d.format(a.final_cost);dojo.attr(c.finalCostNode,"innerHTML",a);b.hide()},error:function(a){console.log(a);b.hide()}})}},submitConversionFactorUOM:function(a){var b=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});b.show();dojo.xhrPost({url:"billBuildUpRate/buildUpSummaryConversionFactorUomUpdate",content:{id:this.itemId,uom_id:a,_csrf_token:this._csrf_token},handleAs:"json",
load:function(a){b.hide()},error:function(a){console.log(a);b.hide()}})},submitRoundingType:function(){var a=this.roundingTypeNode.get("value");if(a!=this.roundingType){var b=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});b.show();var c=this;dojo.xhrPost({url:"billBuildUpRate/buildUpSummaryRoundingUpdate",content:{rounding_type:a,_csrf_token:this._csrf_token,id:this.itemId},handleAs:"json",load:function(a){var e=c.finalCost=d.format(a.final_cost);dojo.attr(c.finalCostNode,
"innerHTML",e);c.roundingType=a.rounding_type;b.hide()},error:function(a){console.log(a);b.hide()}})}},refreshTotalCost:function(){var a=this;dojo.xhrGet({url:"billBuildUpRate/getBuildUpSummary",content:{id:this.itemId},handleAs:"json",load:function(b){var c=a.totalCost=d.format(b.total_cost);dojo.attr(a.totalCostNode,"innerHTML",c);c=a.totalCostAfterConversion=d.format(b.total_cost_after_conversion);dojo.attr(a.totalCostAfterConversionNode,"innerHTML",c);b=a.finalCost=d.format(b.final_cost);dojo.attr(a.finalCostNode,
"innerHTML",b)},error:function(a){console.log(a)}})}})});
