(function(){define("buildspace/apps/PostContractRemeasurementReport/PrintItemsDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json dojo/number dojo/currency ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(g,v,n,w,x,y,z,p,q,r,A,h,B,t,u,f){var k,l,m;k=g("buildspace.apps.PostContractRemeasurementReport.ResourceEnhancedGridFormatter",
null,{postContractRemeasurementQuantityCellFormatter:function(a,b,c){var e,d;d=this.grid.getItem(b);e=h.parse(a);b=this.field.replace("-qty_per_unit","");e=isNaN(e)||0===e||null===e?"&nbsp;":h.format(a,{places:2});d.has_note&&"true"===d.has_note&&c.customClasses.push("hasNoteTypeItemCell");d.version&&0<d.version&&c.customClasses.push("hasAddendumTypeItemCell");a=d[b+"-has_build_up"]&&d[b+"-has_build_up"][0]?'<span style="color:#0000FF;"><b>'+e+"</b></span>":0<=a?e:'<span style="color:#FF0000">'+e+
"</span>";d.type&&1>d.type[0]?c.customClasses.push("invalidTypeItemCell"):d.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||d.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID||d.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY?(c.customClasses.push("disable-cell"),a=d.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY?f.rateOnly:"&nbsp;"):b===buildspace.apps.PostContractReport.ProjectStructureConstants.OMISSION?
c.customClasses.push("disable-cell"):d&&0<d.id[0]&&!d.include[0]&&c.customClasses.push("disable-cell");return a}});l=g("buildspace.apps.PostContractRemeasurementReport.SelectedItemGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){var b,c;this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length)return c=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children,
c.parentNode.removeChild(c),dojo.forEach(b,function(a,b){var c;c=dojo.attr(a,"rowSpan");if(!c||2>c)return dojo.attr(a,"rowSpan",2)})}});m=g("buildspace.apps.PostContractRemeasurementReport.SelectedItemGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,billId:-1,bill_type_id:null,selectedItems:[],opt:null,printURL:null,exportURL:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=
this.grid=new l({store:b.store,structure:b.structure,selectedItems:b.selectedItems});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:f.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:f.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);
return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});b.show();return r.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new t({title:a.dialog.title,selectedRows:a.selectedItems,printURL:a.printURL,exportURL:a.exportURL,billId:a.billId,bill_type_id:a.bill_type_id,opt:a.opt,_csrf_token:c._csrf_token});
b.hide();return c.show()},function(){return b.hide()})}});return g("buildspace.apps.PostContractRemeasurementReport.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,companyId:-1,bill:null,bill_type_id:null,companyName:null,data:null,selectedItems:[],opt:null,printURL:null,exportURL:null,buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){q.set(this.containerNode,{padding:"0px",
margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===p.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(a){var b;null==a&&(a=this);b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});a=new m({store:dojo.data.ItemFileWriteStore({data:a.data}),dialog:a,selectedItems:a.selectedItems,structure:a.constructGridStructure(),billId:a.bill.id[0],
bill_type_id:a.bill_type_id,opt:a.opt,printURL:a.printURL,exportURL:a.exportURL});b.addChild(a);return b},constructGridStructure:function(){var a,b,c,e,d,g,h;e=new u;g=new k;h=this.dynamicGridHeaderStructure();c=0;d=[];b={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:e.rowCountCellFormatter,rowSpan:2},{name:f.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,formatter:e.billRefCellFormatter,rowSpan:2},
{name:f.description,field:"description",width:"auto",formatter:e.postContractPrintPreviewTreeCellFormatter,noresize:!0,rowSpan:2},{name:f.unit,field:"uom_symbol",width:"70px",styles:"text-align:center;",formatter:e.unitIdCellFormatter,noresize:!0,rowSpan:2},{name:f.rate,field:"rate",width:"120px",styles:"text-align:right;",formatter:e.unEditableNumberCellFormatter,noresize:!0,rowSpan:2}]]};a=[{name:f.qty,field_name:"qty_per_unit",width:"90px",styles:"text-align:right;",formatter:g.postContractRemeasurementQuantityCellFormatter},
{name:f.amount,field_name:"total_per_unit",width:"90px",styles:"text-align:right;",formatter:e.unEditableNumberCellFormatter}];dojo.forEach(h,function(e){var f,g,h;f=a.length;c++;d.push({name:e.name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+c,colSpan:f});g=0;for(h=[];g<a.length;)f={field:e.field_name+"-"+a[g].field_name,columnType:"prelimClaimColumn"},n.mixin(f,a[g]),b.cells[0].push(f),h.push(g++);return h});b.cells.push(d);return b},dynamicGridHeaderStructure:function(){var a,
b,c,e,d;d=[];e=[{name:f.omission,field_name:"omission"},{name:f.addition,field_name:"addition"}];b=e.length;for(a=0;a<b;)c={name:e[a].name,field_name:e[a].field_name},d.push(c),a++;return d}})})}).call(this);
