define("buildspace/apps/PostContractRemeasurementReport/RemeasurementContainer","dojo/_base/declare dojo/aspect dojo/request dojo/store/Memory ./RemeasurementGrid buildspace/widget/grid/cells/Formatter buildspace/apps/ProjectBuilder/BillManager/ScheduleOfQuantityGrid ./buildUpQuantitySummary ./buildUpQuantityGrid dojo/i18n!buildspace/nls/PostContractRemeasurement".split(" "),function(v,D,t,p,m,u,z,A,B,e){return v("buildspace.apps.PostContractRemeasurementReport.RemeasurementContainer",dijit.layout.BorderContainer,
{style:"padding:0px;width:100%;margin:0px;border:0px;height:100%;",gutters:!1,project:null,opt:null,selectedTypeStore:[],selectedElementStore:[],selectedItemStore:[],postCreate:function(){this.inherited(arguments);var d=this,g=new u,a=dojo.data.ItemFileWriteStore({url:"postContractRemeasurement/getAllBills/pid/"+d.project.id+"/opt/"+d.opt,clearOnClose:!0}),g=new m({id:"post-contract-remeasurement-report-grid-"+d.project.id,stackContainerTitle:e.bill,pageId:"post-contract-remeasurement-report-grid-"+
d.project.id,project:d.project,gridOpts:{type:"bill",store:a,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:g.rowCountCellFormatter},{name:e.bill,field:"title",width:"auto",formatter:g.analyzerDescriptionCellFormatter},{name:e.omission,field:"omission",width:"150px",styles:"text-align:right;color:red;",formatter:g.unEditableCurrencyCellFormatter},{name:e.addition,field:"addition",width:"150px",styles:"text-align:right;",formatter:g.unEditableCurrencyCellFormatter},
{name:e.nettAdditionOmission,field:"nettAdditionOmission",width:"150px",styles:"text-align:right;color:green;",formatter:g.unEditableCurrencyCellFormatter}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.title[0]&&d.createBillTypesGrid(a)}}}),g=this.makeGridContainer(g,e.bill);this.addChild(g)},createBillTypesGrid:function(d){var g=this,a=new u,h=dojo.data.ItemFileWriteStore({url:"postContractRemeasurement/getBillTypes/bid/"+d.id+"/opt/"+g.opt,clearOnClose:!0});this.selectedTypeStore=
new p({idProperty:"id"});this.selectedElementStore=[];this.selectedItemStore=[];new m({id:"post-contract-remeasurement-report-billtype"+g.project.id,stackContainerTitle:d.title,pageId:"post-contract-remeasurement-report-billtype"+g.project.id+"_"+d.id,project:g.project,gridOpts:{bill:d,gridContainer:g,type:"billTypes",store:h,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:e.description,field:"name",width:"auto",formatter:a.analyzerDescriptionCellFormatter},
{name:e.totalUnits,field:"quantity",width:"150px",styles:"text-align:right;",formatter:a.unEditableCurrencyCellFormatter},{name:e.omission,field:"omission",width:"150px",styles:"text-align:right;color:red;",formatter:a.unEditableCurrencyCellFormatter},{name:e.addition,field:"addition",width:"150px",styles:"text-align:right;",formatter:a.unEditableCurrencyCellFormatter},{name:e.nettAdditionOmission,field:"nettAdditionOmission",width:"150px",styles:"text-align:right;color:green;",formatter:a.unEditableCurrencyCellFormatter}],
onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.name[0]&&g.createElementGrid(a,d)},singleCheckBoxSelection:function(a){var f=a.rowIndex;a=this.selection.selected[f];f=this.getItem(f);this.removedIds=[];if(a)return this.gridContainer.selectedTypeStore.put({id:f.id[0]}),this.getAffectedElementsAndItemsByTypes(f,"add");this.gridContainer.selectedTypeStore.remove(f.id[0]);this.removedIds.push(f.id[0]);return this.getAffectedElementsAndItemsByTypes(f,"remove")},toggleAllSelection:function(a){var f=
this,b=this.selection;f.removedIds=[];if(a)return b.selectRange(0,f.rowCount-1),f.store.fetch({onComplete:function(b){dojo.forEach(b,function(b,c){0<b.id&&f.gridContainer.selectedTypeStore.put({id:b.id[0]})})}}),f.getAffectedElementsAndItemsByTypes(null,"add");b.deselectAll();f.store.fetch({onComplete:function(b){dojo.forEach(b,function(b,c){0<b.id&&(f.gridContainer.selectedTypeStore.remove(b.id[0]),f.removedIds.push(b.id[0]))})}});return f.getAffectedElementsAndItemsByTypes(null,"remove")},getAffectedElementsAndItemsByTypes:function(a,
f){var b=this,c=[],n=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});n.show();if("add"===f)b.gridContainer.selectedTypeStore.query().forEach(function(b){c.push(b.id)});else for(var q in b.removedIds)c.push(b.removedIds[q]);t.post("postContractRemeasurementReport/getElementsAndItemsByTypes",{handleAs:"json",data:{bill_id:d.id,type_ids:JSON.stringify(b.gridContainer.arrayUnique(c)),opt:b.gridContainer.opt}}).then(function(c){for(var a in c)b.gridContainer.selectedElementStore[a]||
(b.gridContainer.selectedElementStore[a]=new p({idProperty:"id"})),b.gridContainer.selectedItemStore[a]||(b.gridContainer.selectedItemStore[a]=new p({idProperty:"id"}));if("add"===f)for(a in c)for(var d in c[a]){b.gridContainer.selectedElementStore[a].put({id:d});for(var k in c[a][d])b.gridContainer.selectedItemStore[a].put({id:c[a][d][k]})}else for(a in c)for(d in c[a])for(k in b.gridContainer.selectedElementStore[a].remove(d),c[a][d])b.gridContainer.selectedItemStore[a].remove(c[a][d][k]);n.hide()},
function(b){n.hide();console.log(b)})}}})},createElementGrid:function(d,g){var a=this,h=new u,l=dojo.data.ItemFileWriteStore({url:"postContractRemeasurement/getElementList/btId/"+d.id+"/opt/"+a.opt,clearOnClose:!0});a.selectedElementStore[d.id]||(a.selectedElementStore[d.id]=new p({idProperty:"id"}));a.selectedItemStore[d.id]||(a.selectedItemStore[d.id]=new p({idProperty:"id"}));new m({id:"post-contract-remeasurement-report-element-"+a.project.id,stackContainerTitle:d.name,pageId:"post-contract-remeasurement-report-element-"+
a.project.id+"_"+d.id,project:a.project,gridOpts:{gridContainer:a,bill:g,billTypeId:d.id,type:"element",store:l,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:h.rowCountCellFormatter},{name:e.description,field:"description",width:"auto"},{name:e.omission,field:"omission",width:"150px",styles:"text-align:right;color:red;",formatter:h.unEditableCurrencyCellFormatter},{name:e.addition,field:"addition",width:"150px",styles:"text-align:right;",formatter:h.unEditableCurrencyCellFormatter},
{name:e.nettAdditionOmission,field:"nettAdditionOmission",width:"150px",styles:"text-align:right;color:green;",formatter:h.unEditableCurrencyCellFormatter}],onRowDblClick:function(f){f=this.getItem(f.rowIndex);0<f.id&&null!==f.description[0]&&a.createItemGrid(g,d,f)},singleCheckBoxSelection:function(a){var b=a.rowIndex;a=this.selection.selected[b];b=this.getItem(b);this.removedIds=[];if(a)return this.gridContainer.selectedElementStore[this.billTypeId].put({id:b.id[0]}),this.getAffectedTypesAndItemsByTypes(b,
"add");this.gridContainer.selectedElementStore[this.billTypeId].remove(b.id[0]);this.removedIds.push(b.id[0]);return this.getAffectedTypesAndItemsByTypes(b,"remove")},toggleAllSelection:function(a){var b=this,c=this.selection;b.removedIds=[];if(a)return c.selectRange(0,b.rowCount-1),b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id[0]&&b.gridContainer.selectedElementStore[b.billTypeId].put({id:a.id[0]})})}}),b.getAffectedTypesAndItemsByTypes(null,"add");c.deselectAll();b.store.fetch({onComplete:function(a){dojo.forEach(a,
function(a,c){0<a.id[0]&&(b.gridContainer.selectedElementStore[b.billTypeId].remove(a.id[0]),b.removedIds.push(a.id[0]))})}});return b.getAffectedTypesAndItemsByTypes(null,"remove")},getAffectedTypesAndItemsByTypes:function(a,b){var c=this,f=[],d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});d.show();if("add"===b)c.gridContainer.selectedElementStore[c.billTypeId].query().forEach(function(b){f.push(b.id)});else for(var g in c.removedIds)f.push(c.removedIds[g]);t.post("postContractRemeasurementReport/getTypesAndItemsByElement",
{handleAs:"json",data:{bill_type_id:c.billTypeId,element_ids:JSON.stringify(c.gridContainer.arrayUnique(f)),opt:c.gridContainer.opt}}).then(function(a){var f=dijit.byId("post-contract-remeasurement-report-billtype"+c.project.id);if("add"===b)for(var k in a){for(var e in a[k])for(var g in a[k][e])c.gridContainer.selectedItemStore[k].put({id:a[k][e][g]});f.grid.store.fetchItemByIdentity({identity:k,onItem:function(a){if(a&&0<c.gridContainer.selectedElementStore[k].data.length)return c.gridContainer.selectedTypeStore.put({id:k}),
f.grid.rowSelectCell.toggleRow(a._0,!0)}})}else for(k in a){for(e in a[k])for(g in c.gridContainer.selectedElementStore[k].remove(e),a[k][e])c.gridContainer.selectedItemStore[k].remove(a[k][e][g]);f.grid.store.fetchItemByIdentity({identity:k,onItem:function(a){if(a&&0==c.gridContainer.selectedElementStore[k].data.length)return c.gridContainer.selectedTypeStore.remove(k),f.grid.rowSelectCell.toggleRow(a._0,!1)}})}d.hide()},function(a){d.hide();console.log(a)})}}})},createItemGrid:function(d,g,a){var h=
this;u();var l=new dojo.data.ItemFileWriteStore({url:"postContractRemeasurement/getItemList/btId/"+g.id+"/elementId/"+a.id+"/opt/"+h.opt,clearOnClose:!0});new m({id:"post-contract-remeasurement-report-item-"+h.project.id,stackContainerTitle:a.description,pageId:"post-contract-remeasurement-report-item-"+h.project.id+"_"+a.id,project:h.project,gridOpts:{gridContainer:h,bill:d,billTypeId:g.id,store:l,type:"item",updateUrl:"postContractRemeasurement/remeasurementItemUpdate",onRowDblClick:function(a){var b=
a.cell.field,c=this.getItem(a.rowIndex),f=this.store,d=g.id;editable=!1;if(0<c.id&&("omission-qty_per_unit"===b||"addition-qty_per_unit"===b)&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&
("omission-qty_per_unit"!==b||void 0!=c["omission-has_build_up"]&&c["omission-has_build_up"][0]))if(0<c.uom_id[0]){if("addition-qty_per_unit"!==b||c.include[0]){a=dojo.xhrPost({url:"billBuildUpQuantity/getDimensionColumnStructure",content:{uom_id:c.uom_id[0]},handleAs:"json"});var l=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});l.show();a.then(function(a){h.createBuildUpQuantityContainer(b,editable,c,a,d,f);l.hide()})}}else buildspace.dialog.alert(e.buildUpQtyAlert,e.pleaseSetUOM,
60,300)},singleCheckBoxSelection:function(a){var b=a.rowIndex;a=this.selection.selected[b];b=this.getItem(b);this.removedIds=[];if(a)return this.gridContainer.selectedItemStore[this.billTypeId].put({id:b.id[0]}),this.getAffectedTypesAndElementsByItems(b,"add");this.gridContainer.selectedItemStore[this.billTypeId].remove(b.id[0]);this.removedIds.push(b.id[0]);return this.getAffectedTypesAndElementsByItems(b,"remove")},toggleAllSelection:function(a){var b=this,c=this.selection;b.removedIds=[];if(a)return c.selectRange(0,
b.rowCount-1),b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id[0]&&b.gridContainer.selectedItemStore[b.billTypeId].put({id:a.id[0]})})}}),b.getAffectedTypesAndElementsByItems(null,"add");c.deselectAll();b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id[0]&&(b.gridContainer.selectedItemStore[b.billTypeId].remove(a.id[0]),b.removedIds.push(a.id[0]))})}});return b.getAffectedTypesAndElementsByItems(null,"remove")},getAffectedTypesAndElementsByItems:function(a,
b){var c=this,d=[],f=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});f.show();if("add"===b)c.gridContainer.selectedItemStore[c.billTypeId].query().forEach(function(a){d.push(a.id)});else for(var g in c.removedIds)d.push(c.removedIds[g]);t.post("postContractRemeasurementReport/getTypesAndElementsByItem",{handleAs:"json",data:{bill_type_id:c.billTypeId,item_ids:JSON.stringify(c.gridContainer.arrayUnique(d)),opt:c.gridContainer.opt}}).then(function(d){var e=dijit.byId("post-contract-remeasurement-report-billtype"+
c.project.id),g=dijit.byId("post-contract-remeasurement-report-element-"+c.project.id);if("add"===b)for(var h in d){for(var l in d[h]){for(var n in d[h][l])c.gridContainer.selectedItemStore[h].put({id:d[h][l][n]});g.grid.store.fetchItemByIdentity({identity:l,onItem:function(a){if(a&&0<c.gridContainer.selectedItemStore[h].data.length)return c.gridContainer.selectedElementStore[h].put({id:l}),g.grid.rowSelectCell.toggleRow(a._0,!0)}})}e.grid.store.fetchItemByIdentity({identity:h,onItem:function(a){if(a&&
0<c.gridContainer.selectedElementStore[h].data.length)return c.gridContainer.selectedTypeStore.put({id:h}),e.grid.rowSelectCell.toggleRow(a._0,!0)}})}else for(h in a&&c.gridContainer.selectedItemStore[c.billTypeId].remove(a.id[0]),d){for(l in d[h])g.grid.store.fetchItemByIdentity({identity:l,onItem:function(a){if(a&&0==c.gridContainer.selectedItemStore[h].data.length)return c.gridContainer.selectedElementStore[h].remove(l),g.grid.rowSelectCell.toggleRow(a._0,!1)}});e.grid.store.fetchItemByIdentity({identity:h,
onItem:function(a){if(a&&0==c.gridContainer.selectedElementStore[h].data.length)return c.gridContainer.selectedTypeStore.remove(h),e.grid.rowSelectCell.toggleRow(a._0,!1)}})}f.hide()},function(a){f.hide();console.log(a)})}}})},createBuildUpQuantityContainer:function(d,g,a,h,l,f){var b,c;"addition-qty_per_unit"===d?(b="postContractRemeasurementBillBuildUpQuantity",c=a.post_contract_bill_item_rate_id):(b="billBuildUpQuantity",c=a.id);var n=this,q=buildspace.constants.QUANTITY_PER_UNIT_ORIGINAL,p,m=
new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;outline:none;",gutters:!1}),t=new dijit.layout.TabContainer({nested:!0,style:"padding:0;border:none;margin:0;width:100%;height:100%;",region:"center"}),k=new u;d=dojo.xhrGet({url:b+"/getLinkInfo/id/"+a.id+"/bcid/"+l+"/t/"+q,handleAs:"json"});var w=new dojo.data.ItemFileWriteStore({url:b+"/getBuildUpQuantityItemList/bill_item_id/"+c+"/bill_column_setting_id/"+l+"/type/"+q,clearOnClose:!0}),v=[buildspace.constants.SIGN_POSITIVE_TEXT,
buildspace.constants.SIGN_NEGATIVE_TEXT],C=[buildspace.constants.SIGN_POSITIVE,buildspace.constants.SIGN_NEGATIVE],x=!1,y=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});y.show();d.then(function(d){var g=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:k.rowCountCellFormatter},{name:e.description,field:"description",width:"auto",cellType:"buildspace.widget.grid.cells.Textarea"},{name:e.factor,field:"factor-value",width:"100px",styles:"text-align:right;",
cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:k.formulaNumberCellFormatter}];dojo.forEach(h,function(a){g.push({name:a.title,field:a.field_name,width:"100px",styles:"text-align:right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:k.formulaNumberCellFormatter})});g.push({name:e.total,field:"total",width:"100px",styles:"text-align:right;",formatter:k.numberCellFormatter});g.push({name:e.sign,field:"sign",width:"70px",styles:"text-align:center;",cellType:"dojox.grid.cells.Select",
options:v,values:C,formatter:k.signCellFormatter});var r=new A({itemId:c,billColumnSettingId:l,type:q,container:m,billGridStore:f,buildUpGridStore:w,hasLinkedQty:d.has_linked_qty,_csrf_token:a._csrf_token,moduleName:b,locked:!0});d.has_linked_qty&&(x=!0,p=new z({title:e.scheduleOfQuantities,BillItem:a,disableEditingMode:!0,stackContainerId:"postContractReportRemeasurement-grid_"+n.project.id+"-stackContainer",gridOpts:{qtyType:q,buildUpSummaryWidget:r,store:new dojo.data.ItemFileWriteStore({url:b+
"/getScheduleOfQuantities/id/"+a.id+"/bcid/"+l+"/type/"+q,clearOnClose:!0}),structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:k.rowCountCellFormatter},{name:e.description,field:"description",width:"auto",formatter:k.treeCellFormatter},{name:e.type,field:"type",width:"70px",styles:"text-align:center;",formatter:k.typeCellFormatter},{name:e.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:k.unitIdCellFormatter},{name:e.qty,field:"quantity-value",
width:"100px",styles:"text-align:right;",formatter:k.formulaNumberCellFormatter}]}}));t.addChild(new B({title:e.manualQtyItems,region:"center",billColumnSettingId:l,BillItem:a,type:q,locked:!0,gridOpts:{store:w,structure:g,buildUpSummaryWidget:r,currentBillLockedStatus:n.currentBillLockedStatus}}));x&&t.addChild(p);m.addChild(t);m.addChild(r);if(d=dijit.byId("postContractReportRemeasurement-grid_"+n.project.id+"-stackContainer"))r=document.createElement("div"),r=new dojox.layout.ContentPane({title:buildspace.truncateString(a.description,
60)+" ("+e.buildUpQuantity+" - "+a.uom_symbol+")",id:"buildUpQuantityPage-"+c,style:"padding:0px;border:0px;",executeScripts:!0},r),d.addChild(r),r.set("content",m),d.selectChild("buildUpQuantityPage-"+c);y.hide()})},makeGridContainer:function(d,g){var a=this.project.id,e=dijit.byId("postContractReportRemeasurement-grid_"+a+"-stackContainer");e&&dijit.byId("postContractReportRemeasurement-grid_"+a+"-stackContainer").destroyRecursive();var e=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",
region:"center",id:"postContractReportRemeasurement-grid_"+a+"-stackContainer"}),l=new dijit.layout.ContentPane({title:g,content:d,grid:d.grid});e.addChild(l);var l=new dijit.layout.StackController({region:"top",containerId:"postContractReportRemeasurement-grid_"+a+"-stackContainer"}),l=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:l}),f=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,
region:"center"});f.addChild(e);f.addChild(l);dojo.subscribe("postContractReportRemeasurement-grid_"+a+"-stackContainer-selectChild","",function(b){var c=dijit.byId("postContractReportRemeasurement-grid_"+a+"-stackContainer");if(c){var d=c.getChildren();b=dojo.indexOf(d,b);b+=1;if(d.length>b)for(;d.length>b;)c.removeChild(d[b]),d[b].destroyDescendants(),d[b].destroyRecursive(),b+=1}});return f},markedCheckBoxObject:function(d,e){var a=d.store;e.query().forEach(function(e){e.id!=buildspace.constants.GRID_LAST_ROW&&
a.fetchItemByIdentity({identity:e.id,onItem:function(a){if(a)return d.rowSelectCell.toggleRow(a._0,!0)}})})},arrayUnique:function(d){return d.reverse().filter(function(d,a,e){return-1===e.indexOf(d,a+1)}).reverse()}})});
