(function(){define("buildspace/apps/PostContractReport/Preliminaries/PrintAllItemWithCurrentClaimMoreThanZero","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json dojo/number dojo/currency ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(g,w,p,x,y,z,A,q,r,t,B,h,k,u,v,f){var l,m,n;l=g("buildspace.apps.PostContractReport.Preliminaries.PreviewItemGridFormatter",
null,{formulaPrelimCurrencyCellFormatter:function(a,b,c){var d;b=this.grid.getItem(b);d=h.parse(a);a=c.field.split("-");d=isNaN(d)||0===d||null==d?"&nbsp;":k.format(d);b.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||b.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||b.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID?(c.customClasses.push("disable-cell"),d="&nbsp;"):!a||a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_RECURRING&&
a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED&&a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED||c.customClasses.push("recurring-cell");return d},prelimPercentFormatter:function(a,b,c){var d,e;e=this.grid.getItem(b);b=c.fieldName;e&&e.grand_total&&0===e.grand_total[0]?a="&nbsp;":isNaN(a)||0===parseFloat(a)?a="&nbsp;":(d=h.format(a,{places:2})+"%",a=c.fieldName===buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED||
c.fieldName===buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED?0<a?'<span style="color:blue;">'+d+"</span>":'<span style="color:#FF0000">'+d+"</span>":0<a?"<span>"+d+"</span>":'<span style="color:#FF0000">'+d+"</span>");1>e.type[0]?c.customClasses.push("invalidTypeItemCell"):e.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||e.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||e.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID?
c.customClasses.push("disable-cell"):!b||b!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_RECURRING&&b!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED&&b!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED?!b||b!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_PREVIOUSCLAIM&&b!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_CURRENTCLAIM&&
b!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_UPTODATECLAIM||c.customClasses.push("disable-cell"):c.customClasses.push("recurring-cell");1>e.type[0]&&c.customClasses.push("invalidTypeItemCell");return a},prelimAmountFormatter:function(a,b,c){var d,e;b=this.grid.getItem(b);e=h.parse(a);a=c.fieldName;isNaN(e)||0===e||null==e?d="&nbsp;":(d=k.format(e),d=c.fieldName===buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED||c.fieldName===buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED?
0<e?'<span style="color:blue;">'+d+"</span>":'<span style="color:#FF0000">'+d+"</span>":0<e?"<span>"+d+"</span>":'<span style="color:#FF0000">'+d+"</span>");1>b.type[0]?c.customClasses.push("invalidTypeItemCell"):b.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||b.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||b.type===buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID?c.customClasses.push("disable-cell"):!a||a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_RECURRING&&
a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED&&a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED?!a||a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_PREVIOUSCLAIM&&a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_CURRENTCLAIM&&a!==buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_UPTODATECLAIM||c.customClasses.push("disable-cell"):
c.customClasses.push("recurring-cell");return d}});m=g("buildspace.apps.PostContractReport.Preliminaries.SelectedItemGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){var b,c;this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length)return c=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children,c.parentNode.removeChild(c),dojo.forEach(b,
function(a,b){var c;c=dojo.attr(a,"rowSpan");if(!c||2>c)return dojo.attr(a,"rowSpan",2)})}});n=g("buildspace.apps.PostContractReport.Preliminaries.SelectedItemGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,billId:-1,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new m({store:b.store,structure:b.structure});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});
c.addChild(new dijit.form.Button({label:f.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:f.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+
"..."});b.show();return t.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new u({title:a.dialog.title,printURL:"printReport/printPostContractPrelimAllItemWithClaimMoreThanZero",exportURL:"exportExcelReport/exportPostContractPrelimAllItemWithClaimMoreThanZero",billId:a.billId,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return g("buildspace.apps.PostContractReport.Preliminaries.GroupProjectAssignmentDialog",dijit.Dialog,
{style:"padding:0px;margin:0px;",project:null,companyId:-1,billId:-1,companyName:null,data:null,buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){r.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===q.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(a){var b;
null==a&&(a=this);b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});a=new n({store:dojo.data.ItemFileWriteStore({data:a.data}),dialog:a,structure:a.constructGridStructure(),billId:a.billId});b.addChild(a);return b},constructGridStructure:function(a){var b,c,d,e,g,h;null==a&&(a=this);a=new v;g=new l;h=this.recurringItemGridStructure();d=0;e=[];c={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter,
rowSpan:2},{name:f.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,formatter:a.billRefCellFormatter,rowSpan:2},{name:f.description,field:"description",width:"auto",formatter:a.postContractPrintPreviewTreeCellFormatter,noresize:!0,rowSpan:2},{name:""+f.contractAmount,field:"grand_total",styles:"text-align:right;color:blue;",width:"110px",formatter:a.unEditableNumberCellFormatter,noresize:!0,rowSpan:2},{name:""+f.initialPayment,field:"initial-amount",
styles:"text-align:right;color:blue;",width:"110px",formatter:a.unEditableNumberCellFormatter,noresize:!0,rowSpan:2},{name:""+f.recurringPayment,field:"recurring-amount",styles:"text-align:right;color:blue;",width:"110px",formatter:a.unEditableNumberCellFormatter,noresize:!0,rowSpan:2},{name:""+f.finalPayment,field:"final-amount",styles:"text-align:right;color:blue;",width:"110px",formatter:a.unEditableNumberCellFormatter,noresize:!0,rowSpan:2}]]};b=[{name:f.percent,field_name:"percentage",width:"60px",
styles:"text-align:right;",formatter:g.prelimPercentFormatter},{name:f.amount,field_name:"amount",width:"100px",styles:"text-align:right;",formatter:g.prelimAmountFormatter}];dojo.forEach(h,function(a){var f,g,h;g=b.length;d++;e.push({name:a.name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+d,colSpan:g});g=0;for(h=[];g<b.length;)f=a.field_name,f=f+"-"+b[g].field_name,f={field:f,columnType:"prelimClaimColumn",fieldName:a.field_name},p.mixin(f,b[g]),c.cells[0].push(f),h.push(g++);
return h});c.cells.push(e);return c},recurringItemGridStructure:function(){var a,b,c,d,e;e=[];d=[{name:f.totalPayment,field_name:buildspace.apps.PostContractReport.ProjectStructureConstants.PRELIM_COLUMN_CURRENTCLAIM}];b=d.length;for(a=0;a<b;)c={name:d[a].name,field_name:d[a].field_name},e.push(c),a++;return e}})})}).call(this);
