define("buildspace/apps/Location/ProjectStructureLocationCode/LocationCodeTabContainer","dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/dom-style dojo/_base/event dojo/keys dijit/focus dojox/grid/EnhancedGrid buildspace/widget/grid/Filter dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/Location".split(" "),function(m,q,r,B,t,u,l,v,w,x,y,e){var A=m("buildspace.apps.Location.ProjectStructureLocationCode.LocationCodeGrid",v,{rootProject:null,
style:"border:none;",region:"center",keepSelection:!0,rowSelector:"0px",selectedItem:null,pasteOp:null,constructor:function(a){this.rearranger=x(this,{})},canSort:function(){return!1},postCreate:function(){this.inherited(arguments);this.on("RowContextMenu",function(a){this.selection.clear();var b=this.getItem(a.rowIndex);this.selection.setSelected(a.rowIndex,!0);this.contextMenu(a);b&&!isNaN(parseInt(b.id[0]))?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0,["Add"])},!0);this.on("RowClick",
function(a){(a=this.getItem(a.rowIndex))&&!isNaN(parseInt(a.id[0]))?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0,["Add"])})},doApplyCellEdit:function(a,b,d){var f=this,c=this.getItem(b),g=this.store;if(a!==c[d][0]){var k=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),h={id:c.id,attr_name:d,val:a,pid:this.rootProject.id,_csrf_token:c._csrf_token?c._csrf_token:null},n="location/projectStructureLocationCodeUpdate";if(c&&isNaN(parseInt(c.id[0]))){var p=
0<b?this.getItem(b-1):!1;q.mixin(h,{prev_item_id:p?p.id:0});n="location/projectStructureLocationCodeAdd"}var z=function(a,b){for(var d in a)c.hasOwnProperty(d)&&d!=b._getIdentifierAttribute()&&b.setValue(c,d,a[d]);b.save()};k.show().then(function(){dojo.xhrPost({url:n,content:h,handleAs:"json",load:function(a){if(a.success){isNaN(parseInt(c.id[0]))?(g.deleteItem(c),g.save(),dojo.forEach(a.items,function(a){g.newItem(a)}),g.save(),f.disableToolbarButtons(!0)):z(a.data,g);var h=f.getCellByField(d);
window.setTimeout(function(){f.focus.setFocusIndex(b,h.index)},10);k.hide()}},error:function(a){k.hide()}})})}this.inherited(arguments)},canEdit:function(a,b){var d=this;if(void 0!=a){var f=this.getItem(b),c=a.field;if(f&&!isNaN(parseInt(f.id[0]))){if("description"!=c&&a.editable)return window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(b,a.index)},10),!1}else if("description"!==c)return!1}return this._canEdit},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);
this.scroller.rowHeightChanged(a,!0)},dodblclick:function(a){this.onRowDblClick(a)},onRowDblClick:function(a){this.inherited(arguments)},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var d={target:a.target,coords:a.keyCode!==u.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},f=this.getItem(a.rowIndex);b&&f&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&r.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(d),t.stop(a))},contextMenuItems:function(a){(a=this.getItem(a.rowIndex))&&
!isNaN(parseInt(a.id[0]))&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItem")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(this,"copyItem")})));this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e.paste,iconClass:"icon-16-container icon-16-paste",disabled:!this.selectedItem,onClick:dojo.hitch(this,"pasteItem")}));a&&!isNaN(parseInt(a.id[0]))&&
(this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.indent,iconClass:"icon-16-container icon-16-indent",onClick:dojo.hitch(this,"indentOutdent","indent")})),this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.outdent,iconClass:"icon-16-container icon-16-outdent",onClick:dojo.hitch(this,"indentOutdent","outdent")})));this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow")}));a&&!isNaN(parseInt(a.id[0]))&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.deleteRow,
iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow")}))},cutItem:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItem:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="copy"},pasteItem:function(){if(this.selectedItem&&this.pasteOp&&-1<this.selection.selectedIndex){var a=this,b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),d=this.store,f=this.selection.selectedIndex,c=this.selection.getFirstSelected(),
g=isNaN(parseInt(c.id[0]))&&0<f?this.getItem(f-1).id:0;b.show().then(function(){dojo.xhrPost({url:"location/ProjectStructureLocationCodePaste",content:{type:a.pasteOp,target_id:c.id,prev_item_id:g,id:a.selectedItem.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(c){var h=[];if(c.success){var g=c.c;switch(a.pasteOp){case "cut":d.fetchItemByIdentity({identity:c.data.id,onItem:function(b){b=a.getItemIndex(b);h.push(b);for(var c=0,e=g.length;c<e;++c)d.fetchItemByIdentity({identity:g[c].id,
onItem:function(b){b=a.getItemIndex(b);h.push(b)}});0<h.length&&a.rearranger.moveRows(h,f);a.selectAfterPaste(b>f?f:f-1,!0)}});d.fetchItemByIdentity({identity:c.data.id,onItem:function(a){for(var b in c.data)a.hasOwnProperty(b)&&b!=d._getIdentifierAttribute()&&d.setValue(a,b,c.data[b]);d.save();var f=0;for(a=g.length;f<a;++f)d.fetchItemByIdentity({identity:g[f].id,onItem:function(a){for(var b in g[f])a.hasOwnProperty(b)&&b!=d._getIdentifierAttribute()&&d.setValue(a,b,g[f][b]);d.save()}})}});break;
case "copy":var e=d.newItem(c.data);d.save();e=a.getItemIndex(e);h.push(e);e=0;for(var k=g.length;e<k;++e){var l=d.newItem(g[e]);d.save();l=a.getItemIndex(l);h.push(l)}0<h.length&&(a.rearranger.moveRows(h,f),a.selectAfterPaste(f,!1))}}a.disableToolbarButtons(!1);a.pasteOp=null;h.length=0;b.hide()},error:function(d){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;b.hide()}})})}},selectAfterPaste:function(a,b){this.selection.clear();this.selectedItem=null;this.selection.setSelected(a,
!0);b&&this.scrollToRow(0<a-3?a-3:a)},addRow:function(){l.curNode.blur();l.curNode=null;if(-1<this.selection.selectedIndex){var a=this.selection.selectedIndex,b=this,d=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),f=this.store,c=this.getItem(a);if(isNaN(parseInt(c.id[0]))){var g=0<a?this.getItem(a-1).id:0;var k={id:c.id,pid:this.rootProject.id,prev_item_id:g,_csrf_token:c._csrf_token}}else g=0<a?this.getItem(a-1).id:0,k={prev_item_id:g,before_id:c.id,pid:this.rootProject.id,
_csrf_token:c._csrf_token};d.show().then(function(){dojo.xhrPost({url:"location/projectStructureLocationCodeAdd",content:k,handleAs:"json",load:function(c){c.success&&dojo.forEach(c.items,function(c){0<c.id&&(c=f.newItem(c),f.save(),c=b.getItemIndex(c),b.rearranger.moveRows([c],a),b.selection.clear())});window.setTimeout(function(){b.selection.setSelected(a,!0);b.focus.setFocusIndex(a,1)},30);d.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);d.hide()}})})}},deleteRow:function(){var a=
this.selection.selectedIndex,b=this.getItem(a);l.curNode.blur();l.curNode=null;if(-1<this.selection.selectedIndex&&b&&!isNaN(parseInt(b.id[0]))){var d=this,f=null,c=null,g=buildspace.dialog.indeterminateProgressBar({title:e.deleting+". "+e.pleaseWait+"..."});1<parseInt(b.rgt[0])-parseInt(b.lft[0])?(f=e.deleteHeadDialogBoxTitle,c=e.deleteHeadDialogBoxMsg):(f=e.deleteItemDialogBoxTitle,c=e.deleteItemDialogBoxMsg);new buildspace.dialog.confirm(f,c,90,320,function(){g.show().then(function(){dojo.xhrPost({url:"location/projectStructureLocationCodeDelete",
content:{id:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(b){if(b.success){b=b.items;for(var c=d.store,f=0,k=b.length;f<k;++f)c.fetchItemByIdentity({identity:b[f].id,onItem:function(a){c.deleteItem(a);c.save()}});b.length=0;d.selection.clear();window.setTimeout(function(){d.focus.setFocusIndex(a,0)},10);d.disableToolbarButtons(!0)}else buildspace.dialog.alert(e.cannotDeleteProjectStructureLocationCodeTitle,e.cannotDeleteProjectStructureLocationCodeMsg,90,320);g.hide();d.selectedItem=
null;d.pasteOp=null},error:function(a){d.selection.clear();d.disableToolbarButtons(!0);d.selectedItem=null;d.pasteOp=null;g.hide()}})})})}},indentOutdent:function(a){var b=this.getItem(this.selection.selectedIndex);if(0<this.selection.selectedIndex&&b&&!isNaN(parseInt(b.id[0]))){var d=this,f=d.store,c=buildspace.dialog.indeterminateProgressBar({title:e.recalculateRows+". "+e.pleaseWait+"..."});c.show().then(function(){dojo.xhrPost({url:"indent"==a?"location/projectStructureLocationCodeIndent":"location/projectStructureLocationCodeOutdent",
content:{id:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(a){if(a.success){var d=a.c,e;for(e in a.item)a.item.hasOwnProperty(e)&&e!=f._getIdentifierAttribute()&&f.setValue(b,e,a.item[e]);var g=0;for(a=d.length;g<a;++g)f.fetchItemByIdentity({identity:d[g].id,onItem:function(a){for(var b in d[g])a.hasOwnProperty(b)&&b!=f._getIdentifierAttribute()&&f.setValue(a,b,d[g][b])}});f.save()}c.hide()},error:function(a){d.selection.clear();d.disableToolbarButtons(!0);c.hide()}})})}},disableToolbarButtons:function(a,
b){var d=dijit.byId(this.rootProject.id+"ProjectStructureLocationCodeAddRow-button"),f=dijit.byId(this.rootProject.id+"ProjectStructureLocationCodeDeleteRow-button"),c=dijit.byId(this.rootProject.id+"ProjectStructureLocationCodeIndentRow-button"),e=dijit.byId(this.rootProject.id+"ProjectStructureLocationCodeOutdentRow-button");d._setDisabledAttr(a);f._setDisabledAttr(a);c&&c._setDisabledAttr(a);e&&e._setDisabledAttr(a);if(a&&b instanceof Array){var k=this;dojo.forEach(b,function(a){(a=dijit.byId(k.rootProject.id+
"ProjectStructureLocationCode"+a+"Row-button"))&&a._setDisabledAttr(!1)})}}});return m("buildspace.apps.Location.ProjectStructureLocationCode.LocationCodeTabContainer",dijit.layout.BorderContainer,{region:"center",rootProject:null,style:"border:none;padding:0;margin:0;width:100%;height:100%;",gutters:!1,postCreate:function(){this.inherited(arguments);var a=new y;a=A({id:this.rootProject.id-NaN,rootProject:this.rootProject,structure:[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",
formatter:a.rowCountCellFormatter},{name:e.location,field:"description",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"auto",formatter:function(a,b){b=this.grid.getItem(b);var c=16*b.level;a=null==a?"&nbsp":a;1<parseInt(b.rgt[0])-parseInt(b.lft[0])&&(a="<b>"+a+"</b>");return'<div class="treeNode" style="padding-left:'+c+'px;"><div class="treeContent">'+a+"&nbsp;</div></div>"}},{name:e.updatedAt,field:"updated_at",styles:"text-align:center;",width:"120px"}],store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,
url:"location/getProjectStructureLocationCodes/pid/"+this.rootProject.id})});var b=new dijit.Toolbar({region:"top",style:"outline:none!important;border:none;padding:2px;width:100%;"});b.addChild(new dijit.form.Button({id:this.rootProject.id+"ProjectStructureLocationCodeAddRow-button",label:e.addRow,iconClass:"icon-16-container icon-16-add",style:"outline:none!important;",disabled:!0,onClick:dojo.hitch(a,"addRow")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:this.rootProject.id+
"ProjectStructureLocationCodeIndentRow-button",label:e.indent,iconClass:"icon-16-container icon-16-indent",style:"outline:none!important;",disabled:!0,onClick:dojo.hitch(a,"indentOutdent","indent")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:this.rootProject.id+"ProjectStructureLocationCodeOutdentRow-button",label:e.outdent,iconClass:"icon-16-container icon-16-outdent",style:"outline:none!important;",disabled:!0,onClick:dojo.hitch(a,"indentOutdent","outdent")}));
b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:this.rootProject.id+"ProjectStructureLocationCodeDeleteRow-button",label:e.deleteRow,iconClass:"icon-16-container icon-16-delete",style:"outline:none!important;",disabled:!0,onClick:dojo.hitch(a,"deleteRow")}));var d=new dijit.layout.BorderContainer({region:"center",rootProject:null,style:"border:none;padding:0;margin:0;width:100%;height:100%;",gutters:!1});d.addChild(b);d.addChild(a);this.addChild(new w({region:"top",grid:a,
editableGrid:!0,filterFields:["description"]}));this.addChild(d)}})});
