define("buildspace/apps/SubPackageReport/grid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/dom-attr dijit/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange dojo/_base/event dojo/keys dijit/focus dojo/aspect dojo/when dojo/request dijit/PopupMenuItem buildspace/widget/grid/cells/Textarea dijit/DropDownMenu dijit/form/DropDownButton dijit/MenuItem ./PrintPreviewDialog/PrintSelectedBillGridDialog ./PrintPreviewDialog/PrintSelectedItemRateAndTotalGridDialog dojo/i18n!buildspace/nls/SubPackages".split(" "),
function(k,l,x,m,y,n,z,s,A,B,C,p,D,g,q,E,t,u,h,r,v,e){var w=k("buildspace.apps.SubPackageReport.Grid",dojox.grid.EnhancedGrid,{type:null,subPackage:null,contId:0,rootProject:null,style:"border-top:none;",selectedItem:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,gridContainer:null,constructor:function(a){this.rearranger=new s(this,{});this.structure=a.structure;this.gridContainer=a.gridContainer;this.type=a.type;"sub_packages-list"!==a.type&&(this.plugins=
{indirectSelection:{headerSelector:!0,width:"40px",styles:"text-align: center;"}})},postCreate:function(){var a=this;a.inherited(arguments);"sub_packages-bill_element_list"===a.type?p.after(a,"_onFetchComplete",function(){a.gridContainer.markedCheckBoxObject(a,a.gridContainer.selectedElementStore)}):"sub_packages-bill_item_list"===a.type&&p.after(a,"_onFetchComplete",function(){a.gridContainer.markedCheckBoxObject(a,a.gridContainer.selectedItemStore)})},startup:function(){var a=this;a.inherited(arguments);
this._connects.push(m.connect(this,"onCellClick",function(b){""===b.cell.name&&a.singleCheckBoxSelection(b)}));this._connects.push(m.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)}))},canSort:function(a){return!1},dodblclick:function(a){this.onRowDblClick(a)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;
b.parentNode.removeChild(b);dojo.forEach(c,function(a,b){var c=dojo.attr(a,"rowSpan");(!c||2>c)&&dojo.attr(a,"rowSpan",2)})}}});return k("buildspace.apps.SubPackageReport.GridContainer",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;border:0px;width:100%;height:100%;",gutters:!1,stackContainerTitle:null,rootProject:null,subPackage:null,gridOpts:{},type:null,gridContainer:null,menu:null,postCreate:function(){this.inherited(arguments);l.mixin(this.gridOpts,{rootProject:this.rootProject,
contId:this.id,type:this.type,region:"center",gridContainer:this.gridContainer,subPackage:this.subPackage});var a=this.grid=new w(this.gridOpts);if("sub_packages-bill_list"===this.type||"sub_packages-bill_element_list"===this.type||"sub_packages-bill_item_list"===this.type){var b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"}),c=null;this.menu=new t({style:"display: none;"});var d=!1;0===this.gridOpts.subContractors.length&&(d=!0);0<this.gridOpts.subContractors.length&&
!1===this.gridOpts.subContractors[0].selected&&(d=!0);"sub_packages-bill_list"===this.type&&(c=e.summary,this.createSummaryPrintPreviewButtons(d));if("sub_packages-bill_element_list"===this.type||"sub_packages-bill_item_list"===this.type)c=e.itemRateAndTotal,this.createItemRatePrintPreviewButtons(d);b.addChild(new u({label:c,iconClass:"icon-16-container icon-16-print",dropDown:this.menu}));this.addChild(b)}this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));
if(b=dijit.byId("SubPackagesTenderingReport-"+this.rootProject.id+"-stackContainer"))c=document.createElement("div"),c=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,30),id:this.pageId,executeScripts:!0},c),b.addChild(c),c.set("content",this),l.mixin(c,{grid:a}),b.selectChild(this.pageId)},createSummaryPrintPreviewButtons:function(a){var b=this;a=new h({label:e.billSummarySelectedTendererPrintPreview,iconClass:"icon-16-container icon-16-print",disabled:a,onClick:function(){b.openBillSummarySelectedTendererPrintPreview()}});
b.menu.addChild(a);var c=new n;dojo.forEach(["printPreviewLowestToHighest","printPreviewHighestToLowest"],function(a){var f=new h({label:e[a],onClick:function(){b.openBillSummaryAllTendererPrintPreview(a)}});c.addChild(f)});a=new q({label:e.billSummaryAllTendererPrintPreview,iconClass:"icon-16-container icon-16-print",popup:c});b.menu.addChild(a)},createItemRatePrintPreviewButtons:function(a){var b=this,c=new n;dojo.forEach(["printPreviewLowestToHighest","printPreviewHighestToLowest"],function(a){var f=
new h({label:e[a],onClick:function(){b.openItemRateAndTotalAllTendererPrintPreview(a)}});c.addChild(f)});a=new q({label:e.itemRateAndTotalAllTendererPrintPreview,iconClass:"icon-16-container icon-16-print",popup:c});b.menu.addChild(a)},openBillSummarySelectedTendererPrintPreview:function(){var a=this,b=a.gridOpts.subContractors,c=[];a.gridContainer.selectedBillStore.query().forEach(function(a){c.push(a.id)});var d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});d.show();g.post("subPackageReporting/getPrintingSelectedBillsSummaryForSelectedTenderer",
{handleAs:"json",data:{sid:a.subPackage.id,bill_ids:JSON.stringify(a.gridContainer.arrayUnique(c))}}).then(function(f){var g,h;dojo.forEach(b,function(a){a.selected&&(g=a.id,h=buildspace.truncateString(a.name,28))});(new r({title:e.billSummarySelectedTendererPrintPreview,companyId:g,companyName:h,data:f,subPackage:a.subPackage,selectedBills:a.gridContainer.arrayUnique(c),printURL:"subPackageReporting/printBillSummarySelectedTenderer",exportURL:"subPackageExportExcelReporting/exportExcelBillSummarySelectedTenderer"})).show();
d.hide()},function(a){console.log(a);d.hide()})},openBillSummaryAllTendererPrintPreview:function(a){var b=this,c=[];b.gridContainer.selectedBillStore.query().forEach(function(a){c.push(a.id)});var d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});d.show();g.post("subPackageReporting/getPrintingSelectedBillsSummaryForAllTenderers",{handleAs:"json",data:{sid:b.subPackage.id,bill_ids:JSON.stringify(b.gridContainer.arrayUnique(c))}}).then(function(f){(new r({title:e.billSummaryAllTendererPrintPreview+
" ("+e[a]+")",data:f,subPackage:b.subPackage,selectedBills:b.gridContainer.arrayUnique(c),type:a,printURL:"subPackageReporting/printBillSummaryForAllTenderer",exportURL:"subPackageExportExcelReporting/exportExcelBillSummaryForAllTenderer"})).show();d.hide()},function(a){console.log(a);d.hide()})},openItemRateAndTotalAllTendererPrintPreview:function(a){var b=this,c=[];b.gridContainer.selectedItemStore.query().forEach(function(a){c.push(a.id)});var d=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+
"..."});d.show();g.post("subPackageReporting/getPrintingSelectedItemsRateSummaryForAllTenderer",{handleAs:"json",data:{sid:b.subPackage.id,bid:b.gridOpts.bill.id,item_ids:JSON.stringify(b.gridContainer.arrayUnique(c))}}).then(function(f){(new v({title:e.itemRateAndTotalAllTendererPrintPreview+" ("+e[a]+")",data:f,subPackage:b.subPackage,bill:b.gridOpts.bill,selectedItems:b.gridContainer.arrayUnique(c),type:a,printURL:"subPackageReporting/printItemRateAndTotalForAllTenderer",exportURL:"subPackageExportExcelReporting/exportExcelItemRateAndTotalForAllTenderer"})).show();
d.hide()},function(a){console.log(a);d.hide()})}})});
