define("buildspace/apps/SubPackageReport/SubPackageContainer","dojo/_base/declare dojo/_base/lang dojo/dom-style dojo/when dojo/currency dojo/aspect dojo/request dojo/store/Memory buildspace/widget/grid/cells/Formatter ./grid dojo/i18n!buildspace/nls/SubPackages".split(" "),function(v,w,z,x,A,y,t,m,r,s,l){return v("buildspace.apps.SubPackageReport.SubPackageContainer",dijit.layout.BorderContainer,{region:"center",rootProject:null,gutters:!1,style:"padding:0px;border:0px;margin:0px;width:100%;height:100%;",
selectedBillStore:[],selectedElementStore:[],selectedItemStore:[],elementStore:[],elementItemStore:[],postCreate:function(){this.inherited(arguments);var f=this;this.createSubPackageListGrid();dojo.subscribe("SubPackagesTenderingReport-"+f.rootProject.id+"-stackContainer-selectChild","",function(h){var k=dijit.byId("SubPackagesTenderingReport-"+f.rootProject.id+"-stackContainer");if(k){var c=k.getChildren(),a=dojo.indexOf(c,h),a=a+1;if(c.length>a){for(;c.length>a;)k.removeChild(c[a]),c[a].destroyRecursive(!0),
a+=1;var l=h.grid.selection.selectedIndex;h.grid.store.save();h.grid.store.close();var p=y.after(h.grid,"_onFetchComplete",function(){p.remove();-1<l&&(this.scrollToRow(l),this.selection.setSelected(l,!0))});h.grid.sort()}}})},createSubPackageListGrid:function(){var f=dijit.byId("SubPackagesTenderingReport-"+this.rootProject.id+"-stackContainer");f&&dijit.byId("SubPackages"+this.rootProject.id+"-stackContainer").destroyRecursive();var f=this.stackContainer=new dijit.layout.StackContainer({style:"padding:0px;border:0px;width:100%;height:100%;",
region:"center",id:"SubPackagesTenderingReport-"+this.rootProject.id+"-stackContainer"}),h=dojo.data.ItemFileWriteStore({url:"subPackage/getSubPackageList/id/"+this.rootProject.id,clearOnClose:!0,urlPreventCache:!0}),k=new r,c=this;try{new s({gridContainer:self,id:"sub_packages_list-page-container-"+c.rootProject.id,stackContainerTitle:l.subPackages,pageId:"sub_packages_grid_page-"+c.rootProject.id,rootProject:c.rootProject,type:"sub_packages-list",gridOpts:{store:h,structure:[{name:"No.",field:"id",
width:"30px",styles:"text-align:center;",formatter:k.rowCountCellFormatter},{name:l.name,field:"name",width:"auto",cellType:"buildspace.widget.grid.cells.Textarea"},{name:l.estAmount,field:"est_amount",width:"120px",styles:"text-align:right;",formatter:k.unEditableCurrencyCellFormatter},{name:l.selectedAmount,field:"selected_amount",width:"120px",styles:"text-align:right;",formatter:k.unEditableCurrencyCellFormatter}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.name[0]&&
c.createBillGrid(a)}}});var a=new dijit.layout.StackController({region:"top",containerId:"SubPackagesTenderingReport-"+c.rootProject.id+"-stackContainer"});c.addChild(f);c.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"SubPackagesTenderingReport-"+c.rootProject.id+"-controllerPane",content:a}))}catch(m){console.debug(m)}},createBillGrid:function(f){this.selectedBillStore=new m({idProperty:"id"});this.selectedElementStore=new m({idProperty:"id"});
this.selectedItemStore=new m({idProperty:"id"});this.elementStore=[];this.elementItemStore=[];var h=this,k=dojo.xhrGet({url:"subPackageReporting/getSubContractors/sid/"+f.id,handleAs:"json"}),c=buildspace.dialog.indeterminateProgressBar({title:l.pleaseWait+"..."});c.show();return x(k,function(a){c.hide();var k=r(),p=new dojo.data.ItemFileWriteStore({url:"subPackage/getBills/id/"+f.id,clearOnClose:!0,urlPreventCache:!0}),n=[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:k.rowCountCellFormatter},
{name:l.title,field:"title",width:5<a.length?"500px":"auto"},{name:l.estAmount,field:"est_amount",width:"120px",styles:"text-align:right;",formatter:k.unEditableCurrencyCellFormatter}];dojo.forEach(a,function(e){if(0<e.id){var g=null!=e.shortname&&0<e.shortname.length?e.shortname:buildspace.truncateString(e.name,20);n.push({name:e.selected?'<p style="color:#0000FF!important;">'+g+"</p>":g,field:"total_amount-"+e.id,width:"120px",styles:"text-align:right;",formatter:k.unEditableCurrencyCellFormatter})}});
new s({gridContainer:h,id:"sub_packages_bills-page-container-"+h.rootProject.id+"-"+f.id,stackContainerTitle:f.name,pageId:"sub_packages-bills_grid_page-"+h.rootProject.id+"-"+f.id,rootProject:h.rootProject,subPackage:f,type:"sub_packages-bill_list",gridOpts:{subContractors:a,store:p,structure:n,onRowDblClick:function(e){e=this.getItem(e.rowIndex);0<e.id&&null!==e.title[0]&&h.createBillElementGrid(e,f,a)},singleCheckBoxSelection:function(e){var g=e.rowIndex;e=this.selection.selected[g];g=this.getItem(g);
this.removedIds=[];if(e)return this.gridContainer.selectedBillStore.put({id:g.id[0]}),this.getAffectedElementsAndItemsByBill(g,"add");this.gridContainer.selectedBillStore.remove(g.id[0]);this.removedIds.push(g.id[0]);return this.getAffectedElementsAndItemsByBill(g,"remove")},toggleAllSelection:function(e){var g=this,b=this.selection;g.removedIds=[];if(e)return b.selectRange(0,g.rowCount-1),g.store.fetch({onComplete:function(b){dojo.forEach(b,function(b,e){0<b.id&&g.gridContainer.selectedBillStore.put({id:b.id[0]})})}}),
g.getAffectedElementsAndItemsByBill(null,"add");b.deselectAll();g.store.fetch({onComplete:function(b){dojo.forEach(b,function(b,e){0<b.id&&(g.gridContainer.selectedBillStore.remove(b.id[0]),g.removedIds.push(b.id[0]))})}});return g.getAffectedElementsAndItemsByBill(null,"remove")},getAffectedElementsAndItemsByBill:function(e,g){var b=this,a=[],q=buildspace.dialog.indeterminateProgressBar({title:l.pleaseWait+"..."});q.show();if("add"===g)e?a.push(e.id[0]):b.gridContainer.selectedBillStore.query().forEach(function(b){a.push(b.id)});
else for(var d in b.removedIds)a.push(b.removedIds[d]);t.post("subPackage/getSelectionAffectedElementsAndItems",{handleAs:"json",data:{sid:f.id,bill_ids:JSON.stringify(b.gridContainer.arrayUnique(a))}}).then(function(e){for(var a in e){b.gridContainer.elementStore[a]||(b.gridContainer.elementStore[a]=new m({idProperty:"id"}));for(var d in e[a])b.gridContainer.elementItemStore[d]||(b.gridContainer.elementItemStore[d]=new m({idProperty:"id"}))}if("add"===g)for(a in e)for(d in b.gridContainer.selectedBillStore.put({id:a}),
e[a]){b.gridContainer.elementStore[a].put({id:d});b.gridContainer.selectedElementStore.put({id:d});for(var c in e[a][d])b.gridContainer.elementItemStore[d].put({id:c}),b.gridContainer.selectedItemStore.put({id:c})}else for(a in e)for(d in b.gridContainer.selectedBillStore.remove(a),e[a])for(c in b.gridContainer.elementStore[a].remove(d),b.gridContainer.selectedElementStore.remove(d),e[a][d])b.gridContainer.elementItemStore[d].remove(c),b.gridContainer.selectedItemStore.remove(c);q.hide()},function(b){q.hide();
console.log(b)})}}})})},createBillElementGrid:function(f,h,k){var c=this,a=r(),u=new dojo.data.ItemFileWriteStore({url:"subPackage/getBillElements/id/"+f.id+"/sid/"+h.id,clearOnClose:!0,urlPreventCache:!0}),p=5<parseInt(k.length)?"500px":"auto",n=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0},{name:l.description,field:"description",width:p,noresize:!0},{name:l.estAmount,field:"est_amount_total",styles:"text-align:right;color:blue;",width:"120px",
formatter:a.unEditableCurrencyCellFormatter,noresize:!0}];dojo.forEach(k,function(e){if(0<e.id){var g=null!=e.shortname&&0<e.shortname.length?e.shortname:buildspace.truncateString(e.name,20);n.push({name:e.selected?'<p style="color:#0000FF!important;">'+g+"</p>":g,field:"est_amount-bill_column-"+e.id,width:"150px",styles:"text-align:right;",noresize:!0,formatter:a.unEditableCurrencyCellFormatter})}});new s({gridContainer:c,id:"sub_packages_tendering_report_bill_elements-page-container-"+c.rootProject.id+
"-"+h.id+"-"+f.id,stackContainerTitle:f.title,pageId:"sub_packages_tendering_report-bill_elements_grid_page-"+c.rootProject.id+"-"+h.id+"-"+f.id,rootProject:c.rootProject,subPackage:h,type:"sub_packages-bill_element_list",gridOpts:{subContractors:k,bill:f,store:u,structure:n,onRowDblClick:function(e){e=this.getItem(e.rowIndex);0<e.id&&null!==e.description[0]&&c.createBillItemGrid(f,e,h,k)},singleCheckBoxSelection:function(e){var a=e.rowIndex;e=this.selection.selected[a];a=this.getItem(a);this.removedIds=
[];if(e)return this.gridContainer.selectedElementStore.put({id:a.id[0]}),this.getAffectedBillAndItemsByElement(a,"add");this.gridContainer.selectedElementStore.remove(a.id[0]);this.removedIds.push(a.id[0]);return this.getAffectedBillAndItemsByElement(a,"remove")},toggleAllSelection:function(a){var g=this,b=this.selection;g.removedIds=[];if(a)return b.selectRange(0,g.rowCount-1),g.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,b){0<a.id&&g.gridContainer.selectedElementStore.put({id:a.id[0]})})}}),
g.getAffectedBillAndItemsByElement(null,"add");b.deselectAll();g.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,b){0<a.id&&(g.gridContainer.selectedElementStore.remove(a.id[0]),g.removedIds.push(a.id[0]))})}});return g.getAffectedBillAndItemsByElement(null,"remove")},getAffectedBillAndItemsByElement:function(a,g){var b=this,c=[],q=buildspace.dialog.indeterminateProgressBar({title:l.pleaseWait+"..."});q.show();if("add"===g)a?c.push(a.id[0]):b.gridContainer.selectedElementStore.query().forEach(function(a){c.push(a.id)});
else for(var d in b.removedIds)c.push(b.removedIds[d]);t.post("subPackage/getAffectedBillAndItemsByElements",{handleAs:"json",data:{sid:b.subPackage.id,element_ids:JSON.stringify(b.gridContainer.arrayUnique(c))}}).then(function(a){var e=dijit.byId("sub_packages_bills-page-container-"+b.rootProject.id+"-"+b.subPackage.id),d;for(d in a){b.gridContainer.elementStore[d]||(b.gridContainer.elementStore[d]=new m({idProperty:"id"}));for(var c in a[d])b.gridContainer.elementItemStore[c]||(b.gridContainer.elementItemStore[c]=
new m({idProperty:"id"}))}if("add"===g)for(d in a)for(c in b.gridContainer.selectedBillStore.put({id:d}),a[d]){b.gridContainer.elementStore[d].put({id:c});b.gridContainer.selectedElementStore.put({id:c});e.grid.store.fetchItemByIdentity({identity:d,onItem:function(a){if(a&&0<b.gridContainer.elementStore[d].data.length)return e.grid.rowSelectCell.toggleRow(a._0,!0)}});for(var f in a[d][c])b.gridContainer.elementItemStore[c].put({id:f}),b.gridContainer.selectedItemStore.put({id:f})}else for(d in a)for(c in a[d]){b.gridContainer.elementStore[d].remove(c);
b.gridContainer.selectedElementStore.remove(c);for(f in a[d][c])b.gridContainer.elementItemStore[c].remove(f),b.gridContainer.selectedItemStore.remove(f);e.grid.store.fetchItemByIdentity({identity:d,onItem:function(a){if(a&&0===b.gridContainer.elementStore[d].data.length)return b.gridContainer.selectedBillStore.remove(d),e.grid.rowSelectCell.toggleRow(a._0,!1)}})}q.hide()},function(a){q.hide();console.log(a)})}}})},createBillItemGrid:function(f,h,k,c){var a=r(),u=4<parseInt(c.length)?"500px":"auto",
p=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"subPackage/getBillItems/sid/"+k.id+"/eid/"+h.id}),n={noscroll:!1,cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0,rowSpan:2},{name:l.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,hidden:!0,rowSpan:2,showInCtxMenu:!0},{name:l.description,field:"description",width:u,formatter:a.treeCellFormatter,noresize:!0,rowSpan:2},{name:l.type,
field:"type",width:"70px",styles:"text-align:center;",formatter:a.typeCellFormatter,noresize:!0,hidden:!0,rowSpan:2,showInCtxMenu:!0},{name:l.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:a.unitIdCellFormatter,noresize:!0,rowSpan:2},{name:l.totalQty,field:"total_qty",styles:"text-align:right;color:blue;",width:"90px",formatter:a.unEditableNumberCellFormatter,noresize:!0,showInCtxMenu:!0,rowSpan:2},{name:l.estRate,field:"rate-value",styles:"text-align:right;color:blue;",width:"100px",
formatter:a.unEditableCurrencyCellFormatter,noresize:!0,showInCtxMenu:!0,rowSpan:2},{name:l.estAmount,field:"total_est_amount",styles:"text-align:right;color:blue;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0,showInCtxMenu:!0,rowSpan:2}]]},e=0,g=[],b=[{name:l.rate,field_name:"rate-value",width:"100px",cellType:"buildspace.widget.grid.cells.TextBox",styles:"text-align:right;",editable:!0,formatter:a.companyRateCurrencyCellFormatter},{name:l.totalAmount,field_name:"total_amount",
width:"100px",styles:"text-align:right;",editable:!1,formatter:a.unEditableCurrencyCellFormatter}];dojo.forEach(c,function(a){if(0<a.id){e++;var c=null!=a.shortname&&0<a.shortname.length?a.shortname:buildspace.truncateString(a.name,20);g.push({name:a.selected?'<p style="color:#0000FF!important;">'+c+"</p>":c,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+e,colSpan:b.length,headerId:a.id,hidden:!1});for(i=0;i<b.length;i++)field=b[i].field_name+"-"+a.id,c={field:field,columnType:"contractorColumn",
companyId:a.id,headerClasses:"typeHeader"+e},w.mixin(c,b[i]),n.cells[0].push(c)}});n.cells.push(g);new s({gridContainer:this,id:"sub_packages_tendering_report_bill_items-page-container-"+this.rootProject.id+"-"+k.id+"-"+h.id,stackContainerTitle:h.description,pageId:"sub_packages_tendering_report-bill_items_grid_page-"+this.rootProject.id+"-"+k.id+"-"+h.id,rootProject:this.rootProject,subPackage:k,type:"sub_packages-bill_item_list",gridOpts:{subContractors:c,store:p,escapeHTMLInData:!1,structure:n,
bill:f,singleCheckBoxSelection:function(a){var b=a.rowIndex;a=this.selection.selected[b];b=this.getItem(b);this.removedIds=[];if(a)return this.gridContainer.selectedItemStore.put({id:b.id[0]}),this.getAffectedBillAndElementsByItem(b,"add");this.gridContainer.selectedItemStore.remove(b.id[0]);this.removedIds.push(b.id[0]);return this.getAffectedBillAndElementsByItem(b,"remove")},toggleAllSelection:function(a){var b=this,d=this.selection;b.removedIds=[];if(a)return d.selectRange(0,b.rowCount-1),b.store.fetch({onComplete:function(a){dojo.forEach(a,
function(a,d){0<a.id&&b.gridContainer.selectedItemStore.put({id:a.id[0]})})}}),b.getAffectedBillAndElementsByItem(null,"add");d.deselectAll();b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,d){0<a.id&&(b.gridContainer.selectedItemStore.remove(a.id[0]),b.removedIds.push(a.id[0]))})}});return b.getAffectedBillAndElementsByItem(null,"remove")},getAffectedBillAndElementsByItem:function(a,b){var d=this,c=[],e=buildspace.dialog.indeterminateProgressBar({title:l.pleaseWait+"..."});e.show();
if("add"===b)a?c.push(a.id[0]):d.gridContainer.selectedItemStore.query().forEach(function(a){c.push(a.id)});else for(var g in d.removedIds)c.push(d.removedIds[g]);t.post("subPackage/getAffectedBillAndElementsByItem",{handleAs:"json",data:{sid:d.subPackage.id,bid:d.bill.id,item_ids:JSON.stringify(d.gridContainer.arrayUnique(c))}}).then(function(a){var c=dijit.byId("sub_packages_bills-page-container-"+d.rootProject.id+"-"+d.subPackage.id),g=dijit.byId("sub_packages_tendering_report_bill_elements-page-container-"+
d.rootProject.id+"-"+d.subPackage.id+"-"+d.bill.id),f;for(f in a){d.gridContainer.elementStore[f]||(d.gridContainer.elementStore[f]=new m({idProperty:"id"}));for(var h in a[f])d.gridContainer.elementItemStore[h]||(d.gridContainer.elementItemStore[h]=new m({idProperty:"id"}))}if("add"===b)for(f in a)for(h in d.gridContainer.selectedBillStore.put({id:f}),a[f]){d.gridContainer.elementStore[f].put({id:h});d.gridContainer.selectedElementStore.put({id:h});c.grid.store.fetchItemByIdentity({identity:f,onItem:function(a){if(a&&
0<d.gridContainer.elementStore[f].data.length)return c.grid.rowSelectCell.toggleRow(a._0,!0)}});for(var k in a[f][h])d.gridContainer.elementItemStore[h].put({id:k}),d.gridContainer.selectedItemStore.put({id:k}),g.grid.store.fetchItemByIdentity({identity:h,onItem:function(a){if(a&&0<d.gridContainer.elementItemStore[h].data.length)return g.grid.rowSelectCell.toggleRow(a._0,!0)}})}else for(f in a){for(h in a[f])for(k in a[f][h])d.gridContainer.elementItemStore[h].remove(k),d.gridContainer.selectedItemStore.remove(k),
g.grid.store.fetchItemByIdentity({identity:h,onItem:function(a){if(a&&0===d.gridContainer.elementItemStore[h].data.length)return d.gridContainer.elementStore[f].remove(h),d.gridContainer.selectedElementStore.remove(h),g.grid.rowSelectCell.toggleRow(a._0,!1)}});c.grid.store.fetchItemByIdentity({identity:f,onItem:function(a){if(a&&0===d.gridContainer.elementStore[f].data.length)return d.gridContainer.selectedBillStore.remove(f),c.grid.rowSelectCell.toggleRow(a._0,!1)}})}e.hide()},function(a){e.hide();
console.log(a)})}}})},markedCheckBoxObject:function(f,h){var k=f.store;h.query().forEach(function(c){c.id!=buildspace.constants.GRID_LAST_ROW&&k.fetchItemByIdentity({identity:c.id,onItem:function(a){if(a)return f.rowSelectCell.toggleRow(a._0,!0)}})})},arrayUnique:function(f){return f.reverse().filter(function(f,k,c){return-1===c.indexOf(f,k+1)}).reverse()}})});
