(function(){define("buildspace/apps/StockInReport/InvoiceDeliveryOrderTab/PrintPreviewDialog/PrintSelectedInvoiceItemGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json buildspace/widget/grid/cells/Formatter ./PrintPreviewFormDialog dojo/i18n!buildspace/nls/StockIn".split(" "),function(e,p,q,r,t,u,v,h,k,l,w,m,n,b){var f,g;f=e("buildspace.apps.StockInReport.SelectedItemRateGrid",dojox.grid.EnhancedGrid,
{style:"border-top:none;",region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1}});g=e("buildspace.apps.StockInReport.SelectedItemRateGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,invoiceId:-1,dialog:null,store:null,structure:null,selectedItems:[],postCreate:function(){var a,c,d;c=this;c.inherited(arguments);a=this.grid=new f({store:c.store,structure:c.structure,selectedItems:c.selectedItems});d=new dijit.Toolbar({region:"top",
style:"padding:2px;border-bottom:none;width:100%;"});d.addChild(new dijit.form.Button({label:b.print,iconClass:"icon-16-container icon-16-print",onClick:function(a){return c.openPrintingDialog()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return c.dialog.hide()}}));c.addChild(d);return c.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var c;
null==a&&(a=this);c=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});c.show();return l.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(b){b=new n({title:a.dialog.title,selectedRows:a.selectedItems,printURL:"stockInReporting/printPreviewStockOutItems",exportURL:"stockInReporting/exportExcelForSelectedItems",invoiceId:a.invoiceId,_csrf_token:b._csrf_token});c.hide();return b.show()},function(a){return c.hide()})}});return e("buildspace.apps.StockInReport.GroupProjectAssignmentDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,invoiceId:-1,data:null,selectedItems:[],buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){k.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===h.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,
b;a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});b=new g({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,invoiceId:this.invoiceId,selectedItems:this.selectedItems,structure:this.constructGridStructure()});a.addChild(b);return a},constructGridStructure:function(a){a=new m;return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter,noresize:!0},{name:b.description,field:"description",width:"auto",
formatter:a.treeCellFormatter,noresize:!0},{name:b.quantity,field:"quantity",width:"100px",styles:"text-align: right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.rfqQuantityCellFormatter,noresize:!0},{name:b.unit,field:"uom",width:"70px",styles:"text-align: center;",formatter:a.rfqUnitCellFormatter,noresize:!0},{name:b.rate,field:"rates",styles:"text-align:right;",width:"120px",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.currencyCellFormatter,noresize:!0},
{name:b.discount+" %",field:"discount_percentage",styles:"text-align:right;",width:"75px",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.currencyCellFormatter,noresize:!0},{name:b.tax+" %",field:"tax_percentage",styles:"text-align:right;",width:"75px",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.currencyCellFormatter,noresize:!0},{name:b.totalWithoutTax,field:"total_without_tax",styles:"text-align:right;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,
noresize:!0},{name:b.totalWithTax,field:"total",styles:"text-align:right;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0},{name:b.doQuantity,field:"doQuantity",width:"90px",styles:"text-align: right;",formatter:a.unEditableNumberCellFormatter,noresize:!0},{name:b.balanceQuantity,field:"balanceQuantity",width:"90px",styles:"text-align: right;",formatter:a.unEditableNumberCellFormatter,noresize:!0}]}})})}).call(this);
