(function(){define("buildspace/apps/StockInReport/InvoiceDeliveryOrderTab/PrintPreviewDialog/PrintPreviewFormDialog","dojo/_base/declare dojo/_base/lang dojo/keys dojo/parser dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/Toolbar dijit/form/Button dijit/layout/BorderContainer dijit/form/ValidationTextBox dijit/form/RadioButton dijit/form/SimpleTextarea dijit/registry dojo/dom-style dojo/dom-form dojo/request dojo/json dojox/validate/web dojox/form/Manager dojo/text!./templates/printPreviewForm.html dojo/i18n!buildspace/nls/StockIn".split(" "),
function(f,w,l,x,m,n,p,q,r,g,t,y,z,A,B,u,C,D,h,E,F,v,e){var k;k=f("buildspace.apps.StockInReport.InvoiceItem.PrintPreviewForm",[m,n,p,q],{baseClass:"buildspace-form",templateString:v,region:"center",style:"overflow: auto;",default_title_input:null,invoiceId:-1,deliveryOrderId:-1,printURL:null,exportURL:null,selectedRows:[],_csrf_token:null,nls:e,dialogContainer:null,print:function(){var c,a,b;b=this.stockInReportingPrintForm;if(!b.validate())return!1;c=dojo.formToObject(b.id);(b=document.getElementById("printingPreviewForm"))&&
b.parentNode.removeChild(b);b=document.createElement("form");b.setAttribute("method","post");b.setAttribute("action",this.printURL);b.setAttribute("id","printingPreviewForm");b.setAttribute("target","formresult");a=document.createElement("input");a.setAttribute("name","printingPageTitle");a.setAttribute("value",c.fileName);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","descriptionFormat");a.setAttribute("value",c.descriptionFormat);a.setAttribute("type",
"hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","selectedRows");a.setAttribute("value",h.stringify(this.selectedRows));a.setAttribute("type","hidden");b.appendChild(a);0<this.invoiceId&&(a=document.createElement("input"),a.setAttribute("name","invoiceId"),a.setAttribute("value",this.invoiceId),a.setAttribute("type","hidden"),b.appendChild(a));0<this.deliveryOrderId&&(a=document.createElement("input"),a.setAttribute("name","deliveryOrderId"),a.setAttribute("value",
this.deliveryOrderId),a.setAttribute("type","hidden"),b.appendChild(a));a=document.createElement("input");a.setAttribute("name","priceFormat");a.setAttribute("value",c.priceFormat);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","printNoCents");a.setAttribute("value",c.printNoCents);a.setAttribute("type","hidden");b.appendChild(a);c=document.createElement("input");c.setAttribute("name","_csrf_token");c.setAttribute("value",this._csrf_token);
c.setAttribute("type","hidden");b.appendChild(c);document.body.appendChild(b);window.open(null,"formresult");return b.submit()},"export":function(){var c,a,b;b=this.stockInReportingPrintForm;if(!b.validate())return!1;c=dojo.formToObject(b.id);(b=document.getElementById("printingPreviewForm"))&&b.parentNode.removeChild(b);b=document.createElement("form");b.setAttribute("method","post");b.setAttribute("action",this.exportURL);b.setAttribute("id","printingPreviewForm");b.setAttribute("target","_self");
a=document.createElement("input");a.setAttribute("name","printingPageTitle");a.setAttribute("value",c.fileName);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","descriptionFormat");a.setAttribute("value",c.descriptionFormat);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","selectedRows");a.setAttribute("value",h.stringify(this.selectedRows));a.setAttribute("type","hidden");b.appendChild(a);
0<this.invoiceId&&(a=document.createElement("input"),a.setAttribute("name","invoiceId"),a.setAttribute("value",this.invoiceId),a.setAttribute("type","hidden"),b.appendChild(a));0<this.deliveryOrderId&&(a=document.createElement("input"),a.setAttribute("name","deliveryOrderId"),a.setAttribute("value",this.deliveryOrderId),a.setAttribute("type","hidden"),b.appendChild(a));a=document.createElement("input");a.setAttribute("name","priceFormat");a.setAttribute("value",c.priceFormat);a.setAttribute("type",
"hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","printNoCents");a.setAttribute("value",c.printNoCents);a.setAttribute("type","hidden");b.appendChild(a);c=document.createElement("input");c.setAttribute("name","_csrf_token");c.setAttribute("value",this._csrf_token);c.setAttribute("type","hidden");b.appendChild(c);document.body.appendChild(b);this.dialogContainer&&this.dialogContainer.hide();return b.submit()}});return f("buildspace.apps.StockInReport.InvoiceItem.PrePrintFormDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;width:480px;height:210px;",printURL:null,exportURL:null,selectedRows:[],type:null,invoiceId:-1,deliveryOrderId:-1,_csrf_token:null,buildRendering:function(){var c;this.content=c=this.createContent();c.startup();return this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},createContent:function(c){var a,b,d;null==c&&(c=this);a=new t({style:"width:480px;height:210px;padding:0;margin:0;",
gutters:!1});b=new k({default_title_input:c.title,dialogContainer:c,printURL:c.printURL,exportURL:c.exportURL,selectedRows:c.selectedRows,_csrf_token:c._csrf_token,invoiceId:c.invoiceId,deliveryOrderId:c.deliveryOrderId});d=new r({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});d.addChild(new g({label:e.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.print()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new g({label:e.exportToExcel,
iconClass:"icon-16-container icon-16-spreadsheet",onClick:function(){return b["export"]()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return c.hide()}}));a.addChild(d);a.addChild(b);return a},_onKey:function(c){if(c.keyCode===l.ESCAPE)return dojo.stopEvent(c)},onHide:function(){return this.destroyRecursive()}})})}).call(this);
