define("buildspace/apps/PostContractSubPackage/MaterialOnSite","dojo/_base/declare dojo/aspect dojo/currency dojo/number dojo/when dijit/layout/ContentPane ./MaterialOnSite/MaterialOnSiteGrid buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContractSubPackage".split(" "),function(q,r,k,f,t,y,l,m,b){var u=function(a,e,d){if(this.grid.getItem(e).id==buildspace.constants.GRID_LAST_ROW)return d.customClasses.push("disable-cell"),"&nbsp;";if(a==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_CLAIMED)return d.customClasses.push("green-cell"),
b.claimed.toUpperCase();d.customClasses.push("yellow-cell");return b.thisClaim.toUpperCase()},n=function(a,e,d){if(this.grid.getItem(e).id==buildspace.constants.GRID_LAST_ROW)return d.customClasses.push("disable-cell"),"&nbsp;";d.customClasses.push("disable-cell");a=f.parse(a);return 0>a?'<span style="color:#FF0000">'+k.format(a)+"</span>":0==a?"&nbsp;":'<span style="color:#42b449;">'+k.format(a)+"</span>"},v=function(a,e,d){var c=f.parse(a);e=this.grid.getItem(e);isNaN(c)||0==c||null==c?a="&nbsp;":
(a=k.format(c),a=0<=c?a:'<span style="color:#FF0000">'+a+"</span>");e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY||d.customClasses.push("disable-cell");return a},p=function(a,e,d){e=this.grid.getItem(e);a=f.parse(a);var c="&nbsp;";isNaN(a)||0==a||null==a||(c=f.format(a,{places:2}));e.type!=
buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY||d.customClasses.push("disable-cell");return 0<=a?c:'<span style="color:#FF0000">'+c+"</span>"};return q("buildspace.apps.PostContractSubPackage.MaterialOnSite",dijit.layout.BorderContainer,{style:"padding:0;margin:0;border:none;width:100%;height:100%;",
region:"center",gutters:!1,subPackage:null,postCreate:function(){this.inherited(arguments);var a=[b.thisClaim,b.claimed],e=[buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_THIS_CLAIM,buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_CLAIMED],d=this,c=new m,h=dojo.data.ItemFileWriteStore({url:"subPackageMaterialOnSite/getMaterialOnSiteList/subPackageId/"+d.subPackage.id,clearOnClose:!0}),a=new l({id:"material_on_site-"+d.subPackage.id,
stackContainerTitle:b.scheduleOfRates,pageId:"material_on_site-"+d.subPackage.id,subPackage:d.subPackage,type:"vo",gridOpts:{store:h,addUrl:"subPackageMaterialOnSite/materialOnSiteAdd",updateUrl:"subPackageMaterialOnSite/materialOnSiteUpdate",deleteUrl:"subPackageMaterialOnSite/materialOnSiteDelete",structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:b.description,field:"description",width:"auto",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea"},
{name:b.reductionPercentage,cellType:"buildspace.widget.grid.cells.FormulaTextBox",field:"reduction_percentage",width:"150px",editable:!0,styles:"text-align:right;",formatter:c.editableClaimPercentageCellFormatter},{name:b.totalMos,field:"total",width:"150px",styles:"text-align:right;",formatter:n},{name:b.totalMosAfterReduction,field:"total_after_reduction",width:"150px",styles:"text-align:right;",formatter:n},{name:b.status,field:"status",width:"80px",styles:"text-align:center;",editable:!0,type:"dojox.grid.cells.Select",
options:a,values:e,formatter:u},{name:b.lastUpdated,field:"updated_at",width:"120px",styles:"text-align: center;"}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.description[0]&&0<a.description[0].length&&d.makeItemGrid(a)}}}),a=this.makeGridContainer(a,b.materialOnSite);this.addChild(a)},makeItemGrid:function(a){var e=this,d=dojo.xhrGet({url:"subPackageMaterialOnSite/getUnits",handleAs:"json"}),c=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});c.show();
t(d,function(d){c.hide();var h=[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM_TEXT],w=[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM],g=new m,x=dojo.data.ItemFileWriteStore({url:"subPackageMaterialOnSite/getMaterialOnSiteItemList/id/"+a.id,clearOnClose:!0});d=new l({subPackage:e.subPackage,materialOnSite:a,type:"vo-items",locked:a.status[0]==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_CLAIMED,
gridOpts:{store:x,escapeHTMLInData:!1,addUrl:"subPackageMaterialOnSite/materialOnSiteItemAdd",updateUrl:"subPackageMaterialOnSite/materialOnSiteItemUpdate",deleteUrl:"subPackageMaterialOnSite/materialOnSiteItemDelete",indentUrl:"subPackageMaterialOnSite/materialOnSiteItemIndent",outdentUrl:"subPackageMaterialOnSite/materialOnSiteItemOutdent",pasteUrl:"subPackageMaterialOnSite/materialOnSiteItemPaste",structure:[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:g.rowCountCellFormatter,
noresize:!0},{name:b.description,field:"description",width:"auto",editable:a.status[0]==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_THIS_CLAIM,cellType:"buildspace.widget.grid.cells.Textarea",formatter:g.treeCellFormatter,noresize:!0},{name:b.type,field:"type",width:"70px",styles:"text-align:center;",editable:a.status[0]==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_THIS_CLAIM,type:"dojox.grid.cells.Select",options:h,values:w,
formatter:g.typeCellFormatter,noresize:!0},{name:b.unit,field:"uom_id",width:"70px",editable:a.status[0]==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_THIS_CLAIM,styles:"text-align:center;",type:"dojox.grid.cells.Select",options:d.options,values:d.values,formatter:g.unitIdCellFormatter,noresize:!0},{name:b.deliveredQty,field:"delivered_qty",editable:a.status[0]==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_THIS_CLAIM,width:"90px",
cellType:"buildspace.widget.grid.cells.FormulaTextBox",styles:"text-align:right;",formatter:p,noresize:!0},{name:b.usedQty,field:"used_qty",editable:a.status[0]==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_THIS_CLAIM,width:"90px",cellType:"buildspace.widget.grid.cells.FormulaTextBox",styles:"text-align:right;",formatter:p,noresize:!0},{name:b.balanceQty,field:"balance_qty",width:"90px",styles:"text-align:right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",
formatter:g.unEditableCurrencyCellFormatter,noresize:!0},{name:b.rate,field:"rate-value",editable:a.status[0]==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_THIS_CLAIM,styles:"text-align:right;",width:"120px",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.status[0]==buildspace.apps.PostContractSubPackage.ProjectStructureConstants.MATERIAL_ON_SITE_THIS_CLAIM?v:g.unEditableCurrencyCellFormatter,noresize:!0},{name:b.amount,field:"amount",styles:"text-align:right;",
width:"120px",formatter:g.unEditableCurrencyCellFormatter,noresize:!0}]}});e.appendNewStack(d,"material_on_site_items-"+a.id+"-"+e.subPackage.id+"-page",a.description)})},makeGridContainer:function(a,e){var d=this.subPackage.id,c=dijit.byId("materialOnSite-"+d+"-stackContainer");c&&dijit.byId("materialOnSite-"+d+"-stackContainer").destroyRecursive();c=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:none;",region:"center",id:"materialOnSite-"+d+"-stackContainer"});c.addChild(new dijit.layout.ContentPane({title:e,
content:a,grid:a.grid}));var b=new dijit.layout.StackController({region:"top",containerId:"materialOnSite-"+d+"-stackContainer"}),b=new dijit.layout.ContentPane({style:"padding:0;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:b}),f=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:100%;height:100%;border:none;",gutters:!1,region:"center"});f.addChild(c);f.addChild(b);dojo.subscribe("materialOnSite-"+d+"-stackContainer-selectChild","",function(a){var e=dijit.byId("materialOnSite-"+
d+"-stackContainer");if(e){var b=e.getChildren(),c=dojo.indexOf(b,a),c=c+1;if(b.length>c){for(;b.length>c;)e.removeChild(b[c]),b[c].destroyDescendants(),b[c].destroyRecursive(),c+=1;var f=a.grid.selection.selectedIndex;a.grid.store.save();a.grid.store.close();var h=r.after(a.grid,"_onFetchComplete",function(){h.remove();-1<f&&(this.scrollToRow(f,!0),this.selection.setSelected(f,!0))});a.grid.sort()}}});return f},appendNewStack:function(a,b,d){var c=dijit.byId("materialOnSite-"+this.subPackage.id+
"-stackContainer");if(c){var e=document.createElement("div");a=new dojox.layout.ContentPane({title:buildspace.truncateString(d,45),id:b,content:a,executeScripts:!0},e);c.addChild(a);c.selectChild(b)}}})});
