// Generated by CoffeeScript 1.9.0
(function() {
  define("buildspace/apps/StockOutReport/PrintPreviewDialog/PrintSelectedItemGridDialog", ["dojo/_base/declare", "dojo/aspect", "dojo/_base/lang", "dojo/_base/connect", "dojo/when", "dojo/html", "dojo/dom", "dojo/keys", "dojo/dom-style", "dojo/request", "dojo/json", "buildspace/widget/grid/cells/Formatter", './PrintPreviewFormDialog', 'dojo/i18n!buildspace/nls/StockOut'], function(declare, aspect, lang, connect, when_, html, dom, keys, domStyle, request, JSON, Formatter, PrintPreviewFormDialog, nls) {
    var selectedItemGrid, selectedItemGridContainer;
    selectedItemGrid = declare("buildspace.apps.StockOutReport.SelectedItemRateGrid", dojox.grid.EnhancedGrid, {
      style: "border-top:none;",
      region: "center",
      selectedItems: [],
      escapeHTMLInData: false,
      canSort: function() {
        return false;
      }
    });
    selectedItemGridContainer = declare("buildspace.apps.StockOutReport.SelectedItemRateGridContainer", dijit.layout.BorderContainer, {
      style: "padding:0px;width:100%;height:100%;",
      region: "center",
      gutters: false,
      projectId: -1,
      resourceId: -1,
      dialog: null,
      store: null,
      structure: null,
      selectedItems: [],
      postCreate: function() {
        var grid, self, toolbar;
        self = this;
        self.inherited(arguments);
        grid = this.grid = new selectedItemGrid({
          store: self.store,
          structure: self.structure,
          selectedItems: self.selectedItems
        });
        toolbar = new dijit.Toolbar({
          region: "top",
          style: "padding:2px;border-bottom:none;width:100%;"
        });
        toolbar.addChild(new dijit.form.Button({
          label: nls.print,
          iconClass: "icon-16-container icon-16-print",
          onClick: function(e) {
            return self.openPrintingDialog();
          }
        }));
        toolbar.addChild(new dijit.ToolbarSeparator());
        toolbar.addChild(new dijit.form.Button({
          label: nls.close,
          iconClass: "icon-16-container icon-16-close",
          onClick: function() {
            return self.dialog.hide();
          }
        }));
        self.addChild(toolbar);
        return self.addChild(new dijit.layout.ContentPane({
          style: 'width:100%',
          content: grid,
          region: 'center'
        }));
      },
      openPrintingDialog: function(self) {
        var pb;
        if (self == null) {
          self = this;
        }
        pb = buildspace.dialog.indeterminateProgressBar({
          title: nls.pleaseWait + "..."
        });
        pb.show();
        return request.get("viewTendererReporting/getPrintingInformation", {
          handleAs: 'json'
        }).then(function(response) {
          var dialog;
          dialog = new PrintPreviewFormDialog({
            title: self.dialog.title,
            selectedRows: self.selectedItems,
            printURL: 'stockOutReporting/printSelectedItem',
            exportURL: 'stockOutReporting/exportExcelForSelectedItems',
            projectId: self.projectId,
            resourceId: self.resourceId,
            _csrf_token: response._csrf_token
          });
          pb.hide();
          return dialog.show();
        }, function(error) {
          return pb.hide();
        });
      }
    });
    return declare("buildspace.apps.StockOutReport.GroupProjectAssignmentDialog", dijit.Dialog, {
      style: "padding:0px;margin:0px;",
      project: null,
      projectId: -1,
      resourceId: -1,
      data: null,
      selectedItems: [],
      buildRendering: function() {
        var content;
        content = this.createContent();
        content.startup();
        this.content = content;
        return this.inherited(arguments);
      },
      postCreate: function() {
        domStyle.set(this.containerNode, {
          padding: "0px",
          margin: "0px"
        });
        this.closeButtonNode.style.display = "none";
        return this.inherited(arguments);
      },
      _onKey: function(e) {
        var key;
        key = e.keyCode;
        if (key === keys.ESCAPE) {
          return dojo.stopEvent(e);
        }
      },
      onHide: function() {
        return this.destroyRecursive();
      },
      createContent: function() {
        var borderContainer, companiesList, content, self;
        self = this;
        companiesList = {};
        borderContainer = new dijit.layout.BorderContainer({
          style: "padding:0px;width:1280px;height:600px;",
          gutters: false
        });
        content = new selectedItemGridContainer({
          store: dojo.data.ItemFileWriteStore({
            data: self.data
          }),
          dialog: self,
          projectId: self.projectId,
          resourceId: self.resourceId,
          selectedItems: self.selectedItems,
          structure: self.constructGridStructure()
        });
        borderContainer.addChild(content);
        return borderContainer;
      },
      constructGridStructure: function(self) {
        var formatter;
        if (self == null) {
          self = this;
        }
        formatter = new Formatter;
        return [
          {
            name: "No",
            field: "id",
            width: '30px',
            styles: 'text-align: center;',
            formatter: formatter.rowCountCellFormatter,
            noresize: true
          }, {
            name: nls.description,
            field: "description",
            width: 'auto',
            formatter: formatter.treeCellFormatter,
            noresize: true
          }, {
            name: nls.unit,
            field: "uom_id",
            styles: 'text-align: center;',
            width: '70px',
            formatter: formatter.unitIdCellFormatter,
            noresize: true
          }, {
            name: nls.totalCostWithoutTax,
            field: "total_cost_without_tax",
            styles: 'text-align:right;',
            width: '140px',
            formatter: formatter.unEditableCurrencyCellFormatter,
            noresize: true
          }, {
            name: nls.totalCostWithTax,
            field: "total_cost",
            styles: 'text-align:right;color:blue;',
            width: '140px',
            formatter: formatter.unEditableCurrencyCellFormatter,
            noresize: true
          }, {
            name: nls.doQuantity,
            field: 'do_quantity',
            styles: "text-align:right;color:blue;",
            width: '120px',
            formatter: formatter.unEditableCurrencyCellFormatter,
            noresize: true
          }, {
            name: nls.stockOutQuantity,
            field: 'stock_out_quantity',
            styles: "text-align:right;color:blue;",
            width: '120px',
            formatter: formatter.unEditableCurrencyCellFormatter,
            noresize: true
          }, {
            name: nls.balanceQuantity,
            field: 'balance_quantity',
            styles: "text-align:right;",
            width: '120px',
            formatter: formatter.unEditableCurrencyCellFormatter,
            noresize: true
          }
        ];
      }
    });
  });

}).call(this);
