define({
    root: {
        code: 'Account Code',
        name: 'Name',
        description: 'Description',
        type: 'Type',
        taxCode: 'Tax Code',
        updatedAt: 'Updated At',
        disable: 'Disable',
        enable: 'Enable',
        addRow: 'Add Row',
        deleteRow: 'Delete Row',
        savingData: 'Saving data',
        deleting: 'Deleting',
        pleaseWait: 'Please wait',
        deleteAccountGroupConfirmation: 'Delete Account Group Confirmation',
        doYouReallywantToDeleteAccountGroup: 'Do you really want to delete this account group',
        deleteAccountCodeConfirmation: 'Delete Account Group Confirmation',
        doYouReallywantToDeleteAccountCode: 'Do you really want to delete this account code',
        disableAccountGroupConfirmation: 'Disable Account Group Confirmation',
        enableAccountGroupConfirmation: 'Enable Account Group Confirmation',
        doYouReallywantToDisableAccountGroup: 'Do you really want to disable this account group',
        doYouReallywantToEnableAccountGroup: 'Do you really want to enable this account group',
        cannotDeleteTitle:'Account Group Cannot Be Deleted',
        cannotDeleteMsg: 'Error deleting Account Group',
        accountGroup: 'Account Group',
        accountCode: 'Account Code',
        cannotDeleteAccountGroupTitle:'Account Group Cannot Be Deleted',
        cannotDeleteAccountGroupMsg: 'Account Group cannot be deleted because it is being used.',
        cannotDeleteAccountCodeTitle:'Account Code Cannot Be Deleted',
        cannotDeleteAccountCodeMsg: 'Account code cannot be deleted because it is being used.',
    }
});