define({
    root: {
        appName: 'BQ Library Manager',
        error: 'Error',
        libraries: 'BQ Libraries',
        newLibrary: 'New Library',
        buildUpSummary: 'Build Up Summary',
        applyConversionFactor: 'Apply Conversion Factor',
        reload: 'Reload',
        toggleSidebar: 'Toggle Sidebar',
        addResourceCategory: 'Resource Category',
        edit: 'Edit',
        delete: 'Delete',
        importLibrary: 'Import Library',
        importFromResourceLibrary: 'Import From Resource Library',
        importToBuildUp: 'Import To Build-up',
        importFromExcel: 'Import From Excel',
        importFromBuildsoft: 'Import From Buildsoft',
        importFromBill: 'Import From Bill',
        importFromBuildspaceZipFile: 'Import From BuildSpace EBQ File',
        importFromPricelist: 'Import From Pricelist',
        importFromFiles: 'Import From Files',
        elements: 'Elements',
        addRows: 'Add Rows',
        description: 'Description',
        rate: 'Rate',
        trade: 'Trade',
        close: 'Close',
        lastUpdated: 'Last Updated',
        wastage: 'Wastage',
        unit: 'Unit',
        type: 'Type',
        cut: 'Cut',
        copy: 'Copy',
        copyRate: 'Copy Rate',
        paste: 'Paste',
        indent: 'Indent',
        outdent: 'Outdent',
        refresh: 'Refresh',
        save: 'Save',
        cancel: 'Cancel',
        addRow: 'Add Row',
        deleteRow: 'Delete Row',
        deleteRate: 'Delete Rate',
        pleaseWait: 'Please wait',
        addingRow: 'Adding row',
        deleting: 'Deleting in process',
        numberOfRows: 'Number of Rows',
        recalculateRows: 'Recalculating rows',
        savingData: 'Saving data',
        totalCost: 'Total Cost',
        conversionFactor: 'Conversion Factor',
        totalAfterConversion: 'Total After Conversion',
        conversionFactorUOM: 'Conversion Factor UOM',
        deleteLibraryAndAllData: 'This will delete library and all of its data. Are you sure you want to proceed?',
        markup: 'Mark Up',
        finalCost: 'Final Cost',
        number: 'Number',
        qty: 'Qty',
        total: 'Total',
        constant: 'Constant',
        buildUpRate: 'Build Up Rate',
        lineTotal: 'Line Total',
        confirmation: 'Confirmation',
        importingItems: 'Importing items',
        importRates: 'Import Rates',
        emptyResourceCategoryTitle: 'Empty Resource Category',
        emptyResourceCategory: 'There is no resource category in the build up. Click "+ Resource Category" button on the top right of the panel to add resource category.',
        detachAllBuildUpAndLink: 'Any update to this column will remove its build up or linked value. Are you sure you want to proceed?',
        deleteElementDialogBoxTitle: 'Delete Element',
        deleteElementDialogBoxMsg: 'Are you sure you want to delete this element?<br /><br />This action will delete all the items associated with this element.',
        deleteHeadDialogBoxTitle: 'Delete Head',
        deleteHeadDialogBoxMsg: 'Are you sure you want to delete this head?<br /><br />This action will delete all the child(s) head/item associated with this head.',
        deleteItemDialogBoxTitle: 'Delete Item',
        deleteItemDialogBoxMsg: 'Are you sure you want to delete this item?<br /><br />This action will delete build up quantity/rates associated with this item.',
        exportTo: 'Export To',
        exportToBuildspaceZip: 'BuildSpace EBQ File',
        exportBQLibraryBuildSpace: 'Export BuildSpace EBQ File',
        fileName: 'File Name',
        export: 'Export',
        importFile: 'Import File',
        printPreview: 'Print',
        selectedItems: 'Item(s) (Selected)',
        selectedItemsWithRate: 'Item(s) with Rate (Selected)',
        selectedItemsWithBuildUpRates: 'Item(s) with Build Up Rate (Selected)'
    }
});