define({
    root: {
        pleaseWait: 'Please wait',
        addingRow: 'Adding row',
        deleting: 'Deleting in process',
        save: 'Save',
        cancel: 'Cancel',
        addRow: 'Add Row',
        deleteRow: 'Delete Row',
        close: 'Close',
        trade: 'Trade',
        cut: 'Cut',
        copy: 'Copy',
        paste: 'Paste',
        totalScheduleOfQuantities: 'Total Schedule Of Quantities',
        manualItems: 'Manual Items',
        importedItems: 'Imported Items',
        buildUpSummary: 'Build Up Summary',
        applyConversionFactor: 'Apply Conversion Factor',
        totalQty: 'Total Quantity',
        conversionFactor: 'Conversion Factor',
        totalAfterConversion: 'Total After Conversion',
        finalQty: 'Final Quantity',
        description: 'Description',
        rate: 'Rate',
        wastage: 'Wastage',
        unit: 'Unit',
        type: 'Type',
        factor: 'Factor',
        total: 'Total',
        roundingOptions: 'Rounding Options',
        deleteBuildUpQtyItemTitle: 'Delete Build Up Quantity Item',
        deleteBuildUpQtyItemMsg: 'Are you sure you want to delete this build up quantity item?'
    }
});