define({
    root: {
        appName: 'Business Type Maintenance',
        businessType: 'Business Type',
        addUser: 'Add User',
        assign: 'Assign',
        reload: 'Reload',
        edit: 'Edit',
        delete: 'Delete',
        description: 'Description',
        lastUpdated: 'Last Updated',
        save: 'Save',
        cancel: 'Cancel',
        addRow: 'Add row',
        deleteRow: 'Delete row',
        pleaseWait: 'Please wait',
        addingRow: 'Adding row',
        deleting: 'Deleting in process',
        numberOfRows: 'Number of rows',
        recalculateRows: 'Recalculating rows',
        savingData: 'Saving data',
        groupList: 'Business Type List',
        editBusinessType: 'Edit Business Type',
        addBusinessType: 'Add Business Type',
        BusinessTypeList: 'Business Types',
        deleteBusinessType: 'Delete Business Type',
        refresh: "Refresh",
        name: 'Name',
        slug: 'Slug',
        dimensions: 'Dimensions',
        no: 'No',
        symbol: 'Symbol',
        itemCannotBeDeleted: 'Item cannot be deleted',
        cannotDeleteUsedElsewhere: 'This business type is still in use',
        priorityUsedDialogTitle: 'Priority has been used',
        priorityPrefix: 'Priority',
        priorityUsedMsg: 'has been used, please choose another one to update the priority !',
        confirmationBusinessType: 'Delete Business Type Confirmation',
        businessTypeDeleteDialogMsg: 'Do you really want to delete this business type?',
        confirmationDimension: 'Delete Dimension Confirmation',
        firstLevelDimensionDialogMsg: 'Do you really want to delete this dimension?',
        secondLevelDimensionDialogMsg: 'Do you really sure you want to delete this dimension?<br /><br />This action is totally cannot be undo.'
    }
});