define({
    root: {
        masterCostData: 'Master Cost Data',
        costData: 'Cost Data',
        standard: 'Standard',
        provisionalSum: 'Provisional Sum',
        primeCostSum: 'Prime Cost Sum',
        projectRatesAnalysis: 'Project Rates Analysis',
        overallProjectCosting: 'Overall Project Costing',
        description: 'Description',
        element: 'Element',
        type: 'Type',
        unit: 'Unit',
        qty: 'Qty',
        totalAcres: 'Total Acres',
        grossFloorArea: 'GFA',
        nettFloorArea: 'NFA',
        costPerUnit: 'Cost/Unit',
        costPerAcre: 'Cost/Acre',
        costPerGrossFloorArea: 'Cost/GFA',
        costPerNettFloorArea: 'Cost/NFA',
        unitRate: 'Unit Rate',
        brand: 'Brand',
        breakdown: 'Breakdown',
        projectParticulars: 'Project Particulars',
        confirmation: 'Confirmation',
        confirmationMessage: 'Are you sure you want to do this?',
        cannotBeUndone: 'This action cannot be undone',
        cannotBeDeleted: 'This item cannot be deleted',
        cannotBeEdited: 'This item cannot be edited',
        savingUnsuccessful: 'Saving Unsuccessful',
        willDeleteAllChildItems: 'All items under this item will also be deleted.',
        delete: 'Delete',
        deleteRow: 'Delete Row',
        deleting: 'Deleting',
        addRow: 'Add Row',
        pleaseWait: 'Please Wait',
        savingData: 'Saving Data',
        close: 'Close',
        save: 'Save',
        amount: 'Amount',
        percentageOfTotalCost: '% of Total Cost',
        percentage: '%',
        budget: 'Budget',
        contractSum: 'Contract Sum',
        remarks: 'Remarks',
        elementalCost: 'Elemental Cost',
        elementalCostPerSf: 'Elemental Cost/sf', // flexi.Todo - remove
        value: 'Value',
        totalAmount: 'Total Amount',
        awardedDate: 'Awarded Date',
        totalUnits: 'Total Units',
        rate: 'Rate',
        conversionFactor: 'Conversion Factor',
        nominatedSubContractorColumns: 'NSC Columns',
        columnName: 'Column Name',
        awardedNominatedSubContractor: 'Awarded NSC',
        awardedContractor: 'Awarded Contractor',
        refresh: 'Refresh',
        itemBreakdownWillBeLost: 'The breakdown of the item will be lost.',
        amountPerUnit: 'Amount/Unit',
        projects: 'Projects',
        project: 'Project',
        unitAndQuantity: 'Unit & Qty',
        showHideRows: 'Show/Hide Rows',
        showHideColumns: 'Show/Hide Columns',
        projectInfo: 'Project Info',
        item: 'Item',
        export: 'Export',
        comparisonReport: 'Comparison Report',
        variationOrderCost: 'Variation Order Cost',
        variationOrders: 'Variation Orders',
        nettOmissionAddition: 'Nett Omission/Addition',
        adjustedSum: 'Adjusted Sum',
        attachments: 'Attachments',
        preview: 'Preview',
        costDataInformation: 'Cost Data Information',
        submitting: 'Submitting',
        budgetDate: 'Budget Date',
        contractSumDate: 'Contract Sum Date',
        adjustedSumDate: 'Adjusted Sum Date',
        updatedBy: 'Updated By',
        updatedAt: 'Updated At',
        tenderComparisonReport: 'Tender Comparison Report',
        status: 'Status',
        displayInSummary: 'Display In Summary',
        displayInPrimeCostRateSummary: 'Display In Project Rates Analysis Summary',
        summaryDescription: 'Summary Desription',
        displayComparison: 'Display Comparison',
        components: 'Components',
        selectComponents: 'Select Components',
        select: 'Select',
        cost: 'Cost',
        name: 'Name',
        country: 'Country',
        state: 'State',
        tender_year: 'Tender Year',
        award_year: 'Award Year',
    }
});
