define({
    root: {
        close: 'Close',
        save: 'Save',
        submitting: 'Submitting',
        pleaseWait: 'Please Wait',
        type: 'Type',
        number: 'Number',
        contractSum: 'Contract Sum',
        projectInformation: 'Project Information',
        mainInformation: 'Main Information',
        contractInformation: 'Contract Information',
        postContract: 'Post Contract',
        contractInfo: 'Contract Info',
        projectOwner: 'Project Owner',
        company: 'Company',
        contractor: 'Contractor',
        project: 'Project',
        letterOfAwardNo: 'LA No.',
        workOrderNo: 'WO No.',
        contractInfoNo: 'CI No.',
        tenderAlternative: 'Tender Option',
        contractPeriodFrom: 'Contract Period From',
        contractPeriodTo: 'Contract Period To',
        subContractWorks: 'Sub Contract Works',
        trade: 'Trade',
        works: 'Works',
        works2: 'Works 2',
        creditorCode: 'Creditor Code',
        remarks: 'Remarks',
        retention: 'Retention',
        retentionSum: 'Retention Sum',
        byPassApproval: 'ByPassApproval',
        noSubConSelected: 'No Sub Con has been selected',
        submittedBy: 'Submitted By',
        submittedAt: 'Submitted At',
        labourRates: 'Labour Rates',
        normalWorkingHours: 'Normal Working Hours',
        normalRate: 'Normal Rate',
        normalRates: 'Normal Rates',
        otRate: 'OT Rate',
        otRates: 'OT Rates',
        skilled: 'Skilled',
        semiSkilled: 'Semi Skilled',
        labour: 'Labour',
        includeVO: 'Include VO',
        includeMaterialOnSite: 'Include Material On Site',
        maximumRetentionSum: 'Maximum Retention Sum',
        awardedDate: 'Awarded Date',
        includeVODescription: "VO will be included in Maximum Retention Sum calculation. Untick this if you don't want to include it.",
        reference: 'Reference',
        waiverOptions: 'Waiver Options',
        eTenderWaiver: 'e-Tender Waiver',
        eAuctionWaiver: 'e-Auction Waiver',
        reason: 'Reason',
        pleaseSpecify: 'Please specify',
        eTenderWaiverDescription: 'Check this option only if this project is not going through e-Tender process.',
        eAuctionWaiverDescription: 'Check this option only if this project is not going through e-Auction process.',
        other: 'Other',
        userSpecified: 'User Specified',
    }
});
