define({
    root: {
        appName: 'Schedule of Rates',
        error: 'Error',
        scheduleOfRates: 'Schedule of Rates',
        newScheduleOfRate: 'New Schedule of Rate',
        buildUpSummary: 'Build Up Summary',
        applyConversionFactor: 'Apply Conversion Factor',
        reload: 'Reload',
        toggleSidebar: 'Toggle Sidebar',
        addResourceCategory: 'Resource Category',
        edit: 'Edit',
        show: 'Show',
        hide: 'Hide',
        delete: 'Delete',
        deleteRate: 'Delete Rate',
        importLibrary: 'Import Library',
        importFromResourceLibrary: 'Import From Resource Library',
        importFromResource: 'Import From Resource',
        importFromScheduleOfRate: 'Import From Schedule Of Rate',
        importToBuildUp: 'Import To Build-up',
        importFromExcel: 'Import From Excel',
        importFromBuildsoft: 'Import From Buildsoft',
        importFromBill: 'Import From Bill',
        importFromPricelist: 'Import From Pricelist',
        importFromFiles: 'Import From Files',
        importFromBuildSpaceSOR: 'Import from BuildSpace SOR',
        elements: 'Elements',
        addRows: 'Add Rows',
        description: 'Description',
        name: 'Name',
        rate: 'Rate',
        trade: 'Trade',
        close: 'Close',
        lastUpdated: 'Last Updated',
        wastage: 'Wastage',
        unit: 'Unit',
        type: 'Type',
        cut: 'Cut',
        copy: 'Copy',
        copyRate: 'Copy Rate',
        paste: 'Paste',
        indent: 'Indent',
        outdent: 'Outdent',
        refresh: 'Refresh',
        save: 'Save',
        cancel: 'Cancel',
        addRow: 'Add Row',
        deleteRow: 'Delete Row',
        pleaseWait: 'Please wait',
        addingRow: 'Adding row',
        deleting: 'Deleting in process',
        numberOfRows: 'Number of Rows',
        recalculateRows: 'Recalculating rows',
        savingData: 'Saving data',
        totalCost: 'Total Cost',
        conversionFactor: 'Conversion Factor',
        totalAfterConversion: 'Total After Conversion',
        conversionFactorUOM: 'Conversion Factor UOM',
        markup: 'Mark Up',
        finalCost: 'Final Cost',
        number: 'Number',
        qty: 'Qty',
        buildUpRate: 'Build Up Rate',
        total: 'Total',
        constant: 'Constant',
        lineTotal: 'Line Total',
        confirmation: 'Confirmation',
        importingItems: 'Importing items',
        detachAllBuildUpAndLink: 'Any update to this column will remove its build up or linked value. Are you sure you want to proceed?',
        deleteScheduleOfRateAndAllData: 'This will delete schedule of rate and all of its data. Are you sure you want to proceed?',
        recalculateResourceStatus: 'Recalculate',
        recalculating: 'Recalculating',
        emptyResourceCategoryTitle: 'Empty Resource Category',
        emptyResourceCategory: 'There is no resource category in the build up. Click "+ Resource Category" button on the top right of the panel to add resource category.',
        deleteTradeDialogBoxTitle: 'Delete Trade',
        deleteTradeDialogBoxMsg: 'Are you sure you want to delete this trade?<br /><br />This action will delete all the items associated with this trade.',
        deleteHeadDialogBoxTitle: 'Delete Head',
        deleteHeadDialogBoxMsg: 'Are you sure you want to delete this head?<br /><br />This action will delete all the child(s) head/item associated with this head.',
        deleteItemDialogBoxTitle: 'Delete Item',
        deleteItemDialogBoxMsg: 'Are you sure you want to delete this item?<br /><br />This action will delete build up quantity/rates associated with this item.',
        printPreview: 'Print',
        selectedItems: 'Item(s) (Selected)',
        selectedItemsWithBuildUpRates: 'Item(s) with Build Up Rate (Selected)',
        resources: 'Resources',
        exportTo: 'Export To',
        exportToBuildSpaceSOR: 'BuildSpace SOR File',
        exportScheduleOfRateLibraryBuildSpace: 'Export Schedule of Rate Library',
        fileName: 'File Name',
        export: 'Export',
        importFile: 'Import File',
        importFromBuildSpaceSORFile: 'Import from BuildSpace SOR File'
    }
});