define({
    root: {
        appName: 'Stock In',
        createNewPO: 'Create New PO',
        edit: 'Edit',
        delete: 'Delete',
        poNo: 'PO No',
        project: 'Project Name',
        date_issued: 'Date Issued',
        status: 'Status',
        noRequestForQuotationAvailableInGrid: 'Sorry, currently there are no Request For Quotation available.',
        noRequestForQuotationProjectAvailableInGrid: 'Sorry, currently there are no Project available.',
        noSupplierAvailableInGrid: 'Sorry, currently there are no Supplier available.',
        noRFQItemAvailableInGrid: 'Sorry, currently there are no Item available.',
        rfqType: 'Type',
        country: 'Country',
        state: 'State',
        processing: 'Processing',
        poNoPrefix: 'PO No Prefix',
        save: 'Save',
        close: 'Close',
        error: 'Error',
        assignProject: 'Assign Project',
        assignSupplier: 'Assign Supplier',
        poProjectSelectionGrid: 'Request For Quotation Project Selection',
        title: 'Title',
        type: 'Type',
        createdAt: 'Created At',
        deleteInvoiceTitle: 'Delete Invoice',
        deleteInvoiceMsg: 'Do you really want to delete this?<br /><br />This action cannot be undo',
        invoiceList: 'Invoice List',
        poInformationTabDesc: 'PO Information',
        supplier: 'Supplier',
        updatedAt: 'Last Updated',
        pleaseWait: 'Please Wait',
        deleting: 'Deleting',
        description: 'Description',
        unit: 'Unit',
        quantity: 'Qty',
        remarks: 'Remarks',
        action: 'Action',
        copy: 'Copy',
        resource: 'Resource',
        savingData: 'Saving',
        totalQty: 'Total Qty',
        itemRemark: 'Item Remark',
        rate: 'Rate',
        deleteInvoiceDialogBoxTitle: 'Delete Invoice',
        deleteInvoiceDialogBoxMsg: 'Are you sure you want to delete this invoice?<br /><br />This action cannot be undone.',
        deleteDeliveryOrderDialogBoxTitle: 'Delete Delivery Order',
        deleteDeliveryOrderDialogBoxMsg: 'Are you sure you want to delete this delivery order?<br /><br />This action cannot be undone.',
        deleteHeadDialogBoxTitle: 'Delete Head',
        deleteHeadDialogBoxMsg: 'Are you sure you want to delete this head?<br /><br />This action will delete all the child(s) head/item associated with this head.',
        deleteItemDialogBoxTitle: 'Delete Item',
        deleteItemDialogBoxMsg: 'Are you sure you want to delete this item?',
        deleteRFQItemRemarkTitle: 'Delete Item Remark',
        deleteRFQItemRemarkMsg: 'Are you sure you want to delete this item?<br /><br />This action cannot be undone.',
        importingItems: 'Importing',
        pending: 'Pending',
        sent: 'Sent',
        closed: 'Closed',
        import: 'Import',
        created_by: 'Created By',
        created_at: 'Created At',
        invoiceNo: 'Invoice No',
        doNo: 'DO No',
        addNewInvoice: 'Add New Invoice',
        editInvoice: 'Edit Invoice',
        selectPO: 'Select PO',
        term: 'Term',
        date_of_invoice: 'Date of Invoice',
        date_of_delivery_order: 'Date of Delivery Order',
        invoiceItemList: 'Invoice Item List',
        deliveryOrder: 'Delivery Order',
        discount: 'Discount',
        tax: 'Tax',
        totalWithoutTax: 'Total without Tax',
        totalWithTax: 'Total with Tax',
        selected: 'Selected',
        select: 'Select',
        itemRemarkDialogTitle: 'Item Remark',
        copyFromResourceLibrary: 'Copy from Resource Library',
        copyToInvoice: 'Copy to Invoice',
        invoiceInformation: 'Invoice Information',
        addNewDeliveryOrder: 'Add New Delivery Order',
        deliveryOrderNo: 'Delivery Order No',
        invoiceQuantity: 'Invoice Qty',
        doQuantity: 'DO Qty',
        balanceQuantity: 'Balance Qty',
        refresh: 'Refresh',
        invoiceTotal: 'Invoice Total',
        selected_po: 'Selected PO',
        uploadFile: 'Upload File',
        downloadFile: 'Download File',
        removeFile: 'Remove File',
        deliveryOrderImportFile: 'Delivery Order Import File',
        print: 'Print',
        export: 'Export',
        exportToExcel: 'Export to Excel',
        printItemsByResourceTrade: 'Print Item(s) by Resource Trade (Selected)',
        printDOItemsByResourceTrade: 'Print DO Item(s) by Resource Trade (Selected)',
        printPageTitle: 'Page Title',
        descriptionType: 'Description Type',
        oneLineDescription: 'One Line Description',
        fullDescription: 'Full Line Description',
        priceDisplayFormat: 'Price Display Format',
        printWithoutCents: 'Print without Cents'
    }
});