define({
    root: {
        tenderingReport: 'Tendering Report',
        projectBreakdown: 'Project Breakdown',
        importProject: 'Import Project',
        fileBrowser: 'File Browser',
        newProject: 'New Project',
        project: 'Project',
        level: 'Level',
        billTotal: "Bill's Total",
        billMarkup: "Bill's Markup",
        recalculate: "Recalculate",
        recalculating: "Recalculating",
        editItemNote: "Edit Item Note",
        editTradeNote: 'Edit Trade Note',
        wastage: 'Wastage',
        tendererLog: 'Tenderer Log',
        currentAmount: 'Current Amount',
        amountRevision: 'Amount Rev',
        grandTotalRevision: 'Grand Total Rev',
        rateRevision: 'Rate Rev',
        type: 'Type',
        item: "Item",
        bill: 'Bill',
        bills: 'Bills',
        diff: 'Diff',
        use: 'Use',
        totalCost: 'Total Cost',
        options: 'Options',
        rounding: 'Rounding',
        roundingOptions: 'Rounding Options',
        element: "Element",
        yesCapital: 'YES',
        noCapital: 'NO',
        show: 'Show',
        unit: 'Unit',
        unitType: 'Unit Type',
        average: 'Average',
        rateAfterMarkup: 'Rate After Markup',
        overallTotalAfterMarkup: 'Overall Total After Markup',
        overallTotal: 'Overall Total',
        markupSummary: 'Markup Summary',
        title: 'Title',
        pleaseWait: 'Please wait',
        created_at: 'Created At',
        lastUpdated: 'Updated At',
        updating: 'Updating',
        addingRow: 'Adding row',
        delete: 'Delete',
        deleteQty: 'Delete Quantity',
        deleteRate: 'Delete Rate',
        deleting: 'Deleting',
        savingData: 'Saving data',
        exportingData: 'Exporting Data',
        export: 'Export',
        processing: 'Processing',
        addRow: 'Add Row',
        billType: 'Bill Type',
        provisional: 'Provisional',
        preliminary: 'Preliminary',
        editBill: 'Edit bill',
        deleteRow: 'Delete Row',
        addLevel: 'Add Level',
        editLevel: 'Edit Level',
        reload: 'Reload',
        save: 'Save',
        close: 'Close',
        cut: 'Cut',
        copy: 'Copy',
        copyQty: 'Copy Quantity',
        copyRate: 'Copy Rate',
        paste: 'Paste',
        mainInformation: 'Main Information',
        levelInformation: 'Level Information',
        billInformation: 'Bill Information',
        projectInformation: 'Project Information',
        description: 'Description',
        startDate: 'Start Date',
        client: 'Client',
        workCategory: 'Work Category',
        elementTradeList: 'Element/Trade List',
        columnSettings: "Column Settings",
        addColumn: 'Add Column',
        addType: 'Add Type',
        name: 'Name',
        shortName: 'Short Name',
        itemDescription: 'Item Description',
        unitQty: 'Unit/Qty',
        factor: 'Factor',
        sign: 'Sign',
        view: 'View',
        viewTenderers: 'View Tenderers',
        enable: 'Enable',
        action: 'Action',
        elements: 'Elements',
        qty: 'Qty',
        rate: 'Rate',
        total: 'Total',
        lineTotal: 'Line Total',
        include: 'Include',
        difference: 'Difference',
        importFromExcel: 'Import From Excel',
        totalUnit: 'Total Unit',
        updatingGridColumns: 'Updating grid columns',
        grandTotalQty: 'Grand Total Qty',
        grandTotal: 'Grand Total',
        originalGrandTotal: 'Original Grand Total',
        originalAmount: 'Original Amount',
        originalTotal: 'Original Total',
        adjustedTotal: 'Adjusted Total',
        amount: 'Amount',
        totalAfterMarkup: 'Total After Markup',
        ratePerNo: 'Rate Per No.',
        supplyRate: 'Supply Rate',
        primeCostRate: 'Prime Cost Rate',
        labourForInstallation: 'Labour For Installation',
        otherCost: 'Other Cost',
        profit: 'Profit',
        confirmation: 'Confirmation',
        lumpSumPercentage: 'Lump Sum Percentage',
        rateAndPercentage: 'Rate and Percentage',
        lumpSum: 'Lump Sum',
        percentage: 'Percentage',
        country: 'Country',
        state: 'State',
        siteAddress: 'Site Address',
        preTender: 'Pre Tender',
        tendering: 'Tendering',
        postContract: 'Post Contract',
        status: 'Status',
        currency: 'Currency',
        billReference: 'Bill Ref',
        tendererSetting: 'Tenderer Setting',
        address: 'Address',
        postcode: 'Postcode',
        phoneNo: 'Phone No.',
        contactPerson: 'Contact Person',
        addNewContractor: 'Add New Contractor',
        remove: 'Remove',
        removeContractorFromTender: 'Remove Contractor From Tender',
        areYouSureToRemove: 'Are you sure you want to remove',
        companyInfo: 'Company Info',
        contractor: 'Contractor',
        selectContractor: 'Select Contractor',
        importResourceItems: 'Import Resource Items',
        assignContractors: 'Assign Contractors',
        sort: 'Sort',
        nameAsc: 'Name Ascending',
        nameDesc: 'Name Descending',
        sorting: 'Sorting',
        selectedAmount: 'Selected Amount',
        highestToLowest: 'Highest To Lowest',
        lowestToHighest: 'Lowest To Highest',
        removeContractor: 'Remove Contractor',
        importContractorRates: "Import Contractor's Rate",
        exportContractorRates: "Export Contractor's Rate",
        backTo: 'Back To',
        withNotListedItem: 'With Not Listed Item',
        withoutNotListedItem: 'Without Not Listed Item',
        printSelectedContractorRates: "Print Selected Contractor's Rate",
        printContractorRates: "Print Contractor's Rate",
        printBQ: 'Print BQ',
        download: 'Download',
        downloadAs: 'Download As',
        printEstimationBQ: 'Print Estimation BQ',
        projectSummaryAllTenderers: 'Summary (All Tenderers)',
        projectSummaryRevisionsAllTenderers: 'Summary With Revisions (All Tenderers)',
        projectSummarySelectedTenderers: 'Summary (Selected Tenderer)',
        summaryAllTenderersLowToHighest: 'Lowest to Highest',
        summaryAllTenderersHighToLowest: 'Highest to Lowest',
        summary: 'Summary',
        refreshContractorRates: 'Refresh Contractor Rates',
        refresh: 'Refresh',
        upload: 'Upload',
        uploadedBy: 'Uploaded By',
        uploadedAt: 'Uploaded At',
        attachments: 'Attachments',
        remarks: 'Remarks',
        deleteConfirmation: 'Delete Confirmation',
        firstLevelCategoryDialogMsg: 'Do you really want to delete this record?',
        compareRemarks: 'Compare Remarks',
        compareAttachments: 'Compare Attachments'
    }
});