define("buildspace/apps/PostContract/DebitCreditNote/DebitCreditNoteContainer","dojo/_base/declare buildspace/widget/grid/Filter dijit/layout/ContentPane dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter ./DebitCreditNoteClaim ./DebitCreditNoteClaimItem dojo/i18n!buildspace/nls/DebitCreditNote".split(" "),function(l,m,g,n,p,q,r,e){var t=l("buildspace.apps.PostContract.DebitCreditNote.AccountGroupSelectionGrid",n,{rootProject:null,style:"border:none;",region:"center",keepSelection:!0,
rowSelector:"0px",constructor:function(){this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments)},dodblclick:function(a){this.onRowDblClick(a)},reloadGrid:function(){this.store.save();this.store.close();this._refresh()}});return l("buildspace.apps.PostContract.DebitCreditNote.DebitCreditNoteContainer",dijit.layout.BorderContainer,{style:"padding:0;margin:0px;border:none;width:100%;height:100%;",gutters:!1,rootProject:null,stackContainer:null,claimCertificate:null,
forVerification:null,locked:!1,debitCreditNoteClaimGrid:null,createAccountGroupSelectGridURL:function(){var a="debitCreditNote/getAccountGroups/projectStructureId/"+String(this.rootProject.id);this.claimCertificate&&(a+="/postContractClaimRevisionId/"+this.claimCertificate.post_contract_claim_revision_id);return a},postCreate:function(){this.inherited(arguments);this.createAccountGroupSelectGrid()},createAccountGroupSelectGrid:function(){var a=this,b=new p;(this.stackContainer=dijit.byId("debitCreditNote-"+
String(this.rootProject.id)+"-stackContainer"))&&dijit.byId("debitCreditNote-"+String(this.rootProject.id)+"-stackContainer").destroyRecursive();stackContainer=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:"debitCreditNote-"+String(a.rootProject.id)+"-stackContainer"});b=this.AccountGroupSelectionGrid=new t({store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:a.createAccountGroupSelectGridURL()}),structure:[{name:"No.",field:"id",
width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:e.accountGroup,field:"name",editable:!1,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"auto",formatter:b.disabledCellFormatter},{name:e.amount,field:"amount",editable:!1,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"160px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter}],onRowDblClick:dojo.hitch(this,"createDebitCreditNoteClaimWindow")});var c=new dijit.layout.StackController({region:"top",
containerId:"debitCreditNote-"+String(a.rootProject.id)+"-stackContainer"});c=new g({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"debitCreditNote-"+String(a.rootProject.id)+"-controllerPane",content:c});var u=new m({grid:b,region:"top",filterFields:[{name:e.accountGroup}]}),h=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",gutters:!1,region:"center"});h.addChild(u);h.addChild(b);b=new dijit.layout.ContentPane({title:e.accountGroup,
content:h});this.stackContainer.addChild(b);a.addChild(c);a.addChild(this.stackContainer);dojo.subscribe("debitCreditNote-"+String(a.rootProject.id)+"-stackContainer-selectChild","",function(d){var k=dijit.byId("debitCreditNote-"+String(a.rootProject.id)+"-stackContainer");if(k){var f=k.getChildren();d=dojo.indexOf(f,dijit.byId(d.id));for(d+=1;f.length>d;)k.removeChild(f[d]),f[d].destroyRecursive(!0),d+=1}})},createDebitCreditNoteClaimWindow:function(a){var b=this;a=this.AccountGroupSelectionGrid.getItem(a.rowIndex);
"No"!=a.disable||isNaN(String(a.id))||(a=new q({projectId:String(b.rootProject.id),accountGroupId:String(a.id),claimCertificate:b.claimCertificate,locked:b.locked,onRowDblClick:function(c){c=this.getItem(c.rowIndex);b.createDebitCreditNoteClaimItemWindow(c)}}),b.debitCreditNoteClaimGrid=a.DebitCreditClaimGrid,a=new g({title:e.debitCreditNoteClaims,content:a}),this.stackContainer.addChild(a),this.stackContainer.selectChild(a))},createDebitCreditNoteClaimItemWindow:function(a){isNaN(String(a.id))||
(a=new r({accountGroupId:String(a.account_group_id),accountGroupSelectionGrid:this.AccountGroupSelectionGrid,debitCreditNoteClaimGrid:this.debitCreditNoteClaimGrid,debitCreditNoteClaimId:String(a.id),locked:a.locked[0],lockedForVerify:this.lock}),a=new g({title:e.debitCreditNoteClaimItems,content:a}),this.stackContainer.addChild(a),this.stackContainer.selectChild(a))}})});
