define("buildspace/apps/PostContract/DebitCreditNote/DebitCreditNoteClaim","dojo/_base/declare dojo/_base/lang dojox/grid/enhanced/plugins/Rearrange dojo/_base/event dojo/keys dijit/focus buildspace/widget/grid/Filter dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter buildspace/apps/Attachment/UploadAttachmentContainer dojo/i18n!buildspace/nls/DebitCreditNote".split(" "),function(t,u,v,w,x,q,y,z,A,B,g){var D=t("buildspace.apps.PostContract.DebitCreditNote.DebitCreditClaimGrid",z,{style:"border:none;",
region:"center",keepSelection:!0,rowSelector:"0px",projectId:null,accountGroupId:null,container:null,locked:!1,constructor:function(){this.inherited(arguments);this.rearranger=v(this,{})},canSort:function(a){return!1},canEdit:function(a,b){return this.locked?!1:void 0!=a?(a=this.getItem(b),"LAST_ROW"===String(a.id)?!0:!a.locked[0]):this._canEdit},postCreate:function(){this.inherited(arguments);var a=this;a.locked||(this.on("RowContextMenu",function(b){this.selection.clear();var c=this.getItem(b.rowIndex);
c&&c.locked[0]||(this.selection.setSelected(b.rowIndex,!0),this.contextMenu(b),c&&!isNaN(parseInt(String(c.id)))?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0,["Add"]))},!0),this.on("RowClick",function(b){(b=this.getItem(b.rowIndex))&&b.locked[0]?this.disableToolbarButtons(!0):b&&!isNaN(parseInt(String(b.id)))?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0,["Add"])}));this.on("CellClick",function(b){if("attachment"===b.cell.field){var c=this.getItem(b.rowIndex);isNaN(String(c.id))||
a.container.addChild(a.addUploadAttachmentContainer(c))}if(!this.locked&&"claim_cert_number"===b.cell.field&&(c=this.getItem(b.rowIndex),!isNaN(String(c.id))&&!String(c.claim_cert_number))){var e=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."});e.show().then(function(){dojo.xhrPost({url:"debitCreditNote/getOpenClaimCertificate",content:{projectStructureId:a.projectId,accountGroupId:a.accountGroupId},handleAs:"json",load:function(d){var f=parseInt(String(d.id));e.hide();!isNaN(f)&&
0<f?buildspace.dialog.confirm(g.confirmation,"<div>"+g.attachClaimCertConfirm+"<br /><br /><b>Claim Certificate No.</b> : "+d.version+"</div>",120,380,function(){a.attachClaimCertificate(f,parseInt(String(c.id)))}):buildspace.dialog.alert(g.noInProgressClaimCertificate,g.noInProgressClaimCertificateMsg,100,300)},error:function(d){e.hide()}})})}})},startup:function(a){this.inherited(arguments)},dodblclick:function(a){this.onRowDblClick(a)},doApplyCellEdit:function(a,b,c){var e=this,d=this.getItem(b),
f=this.store;if(a!==d[c][0]){var h=buildspace.dialog.indeterminateProgressBar({title:g.savingData+". "+g.pleaseWait+"..."}),l={id:String(d.id),projectStructureId:e.projectId,accountGroupId:e.accountGroupId,attr_name:c,val:a,_csrf_token:d._csrf_token?d._csrf_token:null},k="debitCreditNote/debitCreditClaimUpdate";if(d&&isNaN(parseInt(String(d.id)))){var r=0<b?this.getItem(b-1):!1;u.mixin(l,{prev_item_id:r?r.id:0});k="debitCreditNote/debitCreditClaimAdd"}var C=function(m,p){for(var n in m)d.hasOwnProperty(n)&&
n!=p._getIdentifierAttribute()&&p.setValue(d,n,m[n]);p.save()};h.show().then(function(){dojo.xhrPost({url:k,content:l,handleAs:"json",load:function(m){if(m.success){isNaN(parseInt(String(d.id)))?(f.deleteItem(d),f.save(),dojo.forEach(m.items,function(n){f.newItem(n)}),f.save()):C(m.data,f);var p=e.getCellByField(c);window.setTimeout(function(){e.focus.setFocusIndex(b,p.index)},10);h.hide()}},error:function(m){h.hide()}})})}this.inherited(arguments)},addRow:function(){q.curNode.blur();q.curNode=null;
if(-1<this.selection.selectedIndex){var a=this.selection.selectedIndex,b=this,c=buildspace.dialog.indeterminateProgressBar({title:g.savingData+". "+g.pleaseWait+"..."}),e=this.store,d=this.getItem(a);if(isNaN(parseInt(String(d.id)))){var f=0<a?this.getItem(a-1).id:0;var h={id:d.id,prev_item_id:f,_csrf_token:d._csrf_token}}else f=0<a?this.getItem(a-1).id:0,h={prev_item_id:f,before_id:d.id,_csrf_token:d._csrf_token};u.mixin(h,{projectStructureId:b.projectId,accountGroupId:b.accountGroupId});c.show().then(function(){dojo.xhrPost({url:"debitCreditNote/debitCreditClaimAdd",
content:h,handleAs:"json",load:function(l){l.success&&dojo.forEach(l.items,function(k){0<k.id&&(k=e.newItem(k),e.save(),k=b.getItemIndex(k),b.rearranger.moveRows([k],a),b.selection.clear())});window.setTimeout(function(){b.selection.setSelected(a,!0);b.focus.setFocusIndex(a,1)},30);c.hide()},error:function(l){b.selection.clear();b.disableToolbarButtons(!0);c.hide()}})})}},deleteRow:function(){var a=this.selection.selectedIndex,b=this.getItem(a);q.curNode.blur();q.curNode=null;if(-1<this.selection.selectedIndex&&
b&&!isNaN(parseInt(String(b.id)))){var c=this,e=buildspace.dialog.indeterminateProgressBar({title:g.deleting+". "+g.pleaseWait+"..."}),d={id:b.id,_csrf_token:b._csrf_token,projectStructureId:c.projectId,accountGroupId:c.accountGroupId};buildspace.dialog.confirm(g.deleteClaimConfirmation,"<div>"+g.doYouReallywantToDeleteClaim+" ?</div>",90,320,function(){e.show().then(function(){dojo.xhrPost({url:"debitCreditNote/debitCreditClaimDelete",content:d,handleAs:"json",load:function(f){if(f.success){f=f.items;
for(var h=c.store,l=0,k=f.length;l<k;++l)h.fetchItemByIdentity({identity:f[l].id,onItem:function(r){h.deleteItem(r);h.save()}});f.length=0;c.selection.clear();window.setTimeout(function(){c.focus.setFocusIndex(a,0)},10);c.disableToolbarButtons(!0)}e.hide();c.selectedItem=null;c.pasteOp=null},error:function(f){c.selection.clear();c.disableToolbarButtons(!0);c.selectedItem=null;c.pasteOp=null;e.hide()}})})})}},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c=
{target:a.target,coords:a.keyCode!==x.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},e=this.getItem(a.rowIndex);b&&e&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&html.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),w.stop(a))},contextMenuItems:function(a){(a=this.getItem(a.rowIndex))&&!isNaN(parseInt(a.id[0]))&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow")})),this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.deleteRow,
iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow")})))},disableToolbarButtons:function(a,b){var c=dijit.byId("AddDebitCreditNoteClaimRow-button"),e=dijit.byId("DeleteDebitCreditNoteClaimRow-button");c._setDisabledAttr(a);e._setDisabledAttr(a);a&&b instanceof Array&&dojo.forEach(b,function(d){(d=dijit.byId(d+"DebitCreditNoteClaimRow-button"))&&d._setDisabledAttr(!1)})},addUploadAttachmentContainer:function(a){var b="project-"+this.projectId+"-uploadAttachment",c=dijit.byId(b);
c&&(this.container.removeChild(c),c.destroy());return c=new B({id:b,region:"bottom",item:a,disableEditing:a.locked[0]||this.locked,style:"padding:0;margin:0;border:none;width:100%;height:40%;"})},attachClaimCertificate:function(a,b){var c=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."}),e=this.store;c.show().then(function(){dojo.xhrPost({url:"debitCreditNote/claimCertificateAttach",content:{cid:a,debitCreditNoteClaimId:b},handleAs:"json",load:function(d){d.success&&(e.fetchItemByIdentity({identity:d.item.id,
onItem:function(f){for(var h in d.item)f.hasOwnProperty(h)&&h!=e._getIdentifierAttribute()&&e.setValue(f,h,d.item[h]);e.save()}}),c.hide())},error:function(d){c.hide()}})})},reloadGrid:function(){this.store.save();this.store.close();this._refresh()}});return t("buildspace.apps.PostContract.DebitCreditNote.DebitCreditNoteClaim",dijit.layout.BorderContainer,{style:"padding:0;margin:0px;border:none;width:100%;height:100%;",gutters:!1,projectId:null,accountGroupId:null,claimCertificate:null,stackContainer:null,
locked:!1,constructor:function(){this.inherited(arguments)},createGetDebitCreditClaimsURL:function(){var a="debitCreditNote/getDebitCreditClaims/projectStructureId/"+this.projectId+"/accountGroupId/"+this.accountGroupId;this.claimCertificate&&(a+="/postContractClaimRevisionId/"+this.claimCertificate.post_contract_claim_revision_id);return a},postCreate:function(){this.inherited(arguments);var a=new A;a=this.DebitCreditClaimGrid=new D({store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:this.createGetDebitCreditClaimsURL()}),
structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:g.description,field:"description",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"auto",styles:"text-align:left;"},{name:g.attachment,field:"attachment",editable:!1,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"82px",styles:"text-align:center;",formatter:function(e,d,f){return(e=this.grid.getItem(d))&&0<=parseInt(String(e.id))?'<span style="color:blue;">'+
e.attachment+"</span>":null}},{name:g.claimCertificateNo,field:"claim_cert_number",editable:!1,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"80px",styles:"text-align:center;"},{name:g.amount,field:"amount",editable:!1,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"160px",styles:"text-align:right;",formatter:a.unEditableCurrencyCellFormatter},{name:g.updatedAt,field:"updated_at",editable:!1,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"120px",
styles:"text-align:center;"}],projectId:this.projectId,accountGroupId:this.accountGroupId,claimCertificate:this.claimCertificate,onRowDblClick:this.onRowDblClick,container:this,locked:this.locked});if(!this.locked){var b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({id:"AddDebitCreditNoteClaimRow-button",label:g.addRow,iconClass:"icon-16-container icon-16-add",disabled:!0,onClick:dojo.hitch(a,"addRow")}));b.addChild(new dijit.ToolbarSeparator);
b.addChild(new dijit.form.Button({id:"DeleteDebitCreditNoteClaimRow-button",label:g.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:dojo.hitch(a,"deleteRow")}))}var c=new y({grid:a,region:"top",filterFields:[{name:g.description}]});this.addChild(c);this.locked||this.addChild(b);this.addChild(a)}})});
