(function(){var n={}.hasOwnProperty;define("buildspace/apps/PostContractReport/ClaimRevisionSettingsForm","dojo/_base/declare dojo/html dojo/dom dojo/dom-construct dojo/keys dojo/request dojo/dom-style dojo/dom-attr dojo/dom-geometry dojo/_base/lang dijit/form/Form dijit/form/RadioButton dijit/form/Select dijit/form/ValidationTextBox dijit/form/NumberTextBox dijit/form/CurrencyTextBox dojo/number dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/on dojo/text!./templates/claimRevisionSettingsForm.html dojo/text!./templates/claimRevisionSettingsRow.html dojo/i18n!buildspace/nls/PostContract".split(" "),
function(f,p,w,q,x,r,d,y,z,g,A,B,C,D,E,F,G,h,H,k,l,t,u,v,e){var m;m=f("buildspace.apps.PostContractReport.ClaimRevisionSettingRowForm",[h,k,l],{isNew:!1,projectId:-1,revisionId:-1,postContractId:-1,region:"center",nls:e,rootProject:null,revisionData:null,ClaimRevisionSettingsForm:null,_csrf_token:0,constructor:function(a){return a.templateString=v},postCreate:function(){var a;this.inherited(arguments);a=this;this.setSelectedCurrentSelectedRevision();this.exitEditMode();this.updateRevisionStatusDescription(this.revisionData.locked_status);
this.lockedStatusValue.set("value",this.revisionData.locked_status);return t(this.showRevisionSelectedLink,"click",function(b){return a.assignNewSelectedRevision()})},assignNewSelectedRevision:function(){var a,b;b=this;a=new buildspace.dialog.indeterminateProgressBar({title:"Processing..."});a.show();return r.post("postContract/assignNewSelectedRevision",{data:{post_contract_id:this.revisionData.post_contract_id,revisionId:this.revisionId,"post_contract_claim_revision[post_contract_id]":this.revisionData.post_contract_id,
"post_contract_claim_revision[current_selected_revision]":!0,"post_contract_claim_revision[_csrf_token]":this._csrf_token},handleAs:"json",preventCache:!0}).then(function(c){b.ClaimRevisionSettingsForm.revisionDatas=c;a.hide();return b.ClaimRevisionSettingsForm.clearOldRevisionAndAddNewRevision()},function(b){console.log(b);return a.hide()})},setSelectedCurrentSelectedRevision:function(){if(this.revisionData.selected)return d.set(this.showRevisionSelectedMarker,"display","block"),dijit.byId(this.rootProject.id[0]+
"-ProjectRevision").set("title",e.claimRevision+"::"+e.version+" "+this.revisionData.version),d.set(this.showRevisionSelectedLink,"display","none");d.set(this.showRevisionSelectedMarker,"display","none");return d.set(this.showRevisionSelectedLink,"display","block")},setupEditMode:function(){d.set(this.addendumStatusInput,"display","");d.set(this.addendumStatusView,"display","none")},exitEditMode:function(){d.set(this.addendumStatusInput,"display","none");d.set(this.addendumStatusView,"display","")},
updateRevisionStatusDescription:function(a){p.set(this.addendumStatusView,a?e.addendumLocked:e.addendumProgressing)}});return f("buildspace.apps.PostContractReport.ClaimRevisionSettingsForm",[h,k,l],{projectId:-1,baseClass:"buildspace-form",style:"padding:5px;overflow:auto;border:0px;",region:"center",rootProject:null,nls:e,workarea:null,revisionDatas:null,postContractId:null,_csrf_token:0,tableCount:1,rowArray:[],constructor:function(a){return a.templateString=u},postMixInProperties:function(){this.inherited(arguments);
return this.rowArray[this.projectId]=[]},postCreate:function(){this.inherited(arguments);return this.masterGenerateClaimRevisionTableRow()},masterGenerateClaimRevisionTableRow:function(){var a,b=this;a=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});a.show();return dojo.xhrGet({url:"postContract/getClaimRevisionLists",handleAs:"json",content:{id:this.projectId},load:function(c){b.revisionDatas=c;b.populateClaimRevisionTableRow();b.postContractId=c.postContractId;return a.hide()},
error:function(b){return a.hide()}})},clearOldRevisionAndAddNewRevision:function(){this.rowArray[this.projectId]=[];this.tableCount=1;dojo.empty(this.tableContainer);this.populateClaimRevisionTableRow();return g.hitch(this,"closeElementItemGrid")()},populateClaimRevisionTableRow:function(){var a,b,c;this._csrf_token=this.revisionDatas.form.csrf_token;c=this.revisionDatas.claimRevisions;for(b in c)n.call(c,b)&&(a=c[b],a=this.rowArray[this.projectId][b]=new m({count:this.tableCount,rootProject:this.rootProject,
projectId:this.projectId,revisionId:a.id,postContractId:a.post_contract_id,revisionData:a,ClaimRevisionSettingsForm:this,_csrf_token:this.revisionDatas.form.csrf_token}),this.addTableRow(a))},addTableRow:function(a){q.place(a.domNode,this.tableContainer);return this.tableCount++},closeElementItemGrid:function(){return g.hitch(this.workarea,"removeBillTab")()}})})}).call(this);
