define("buildspace/apps/RationalizeRate/Builder","../../../dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/event dojo/keys dojo/on ./WorkArea ./PrintBillDialog ./importRatesDialog dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dojo/when buildspace/apps/Tendering/Builder buildspace/apps/TenderAlternative/TenderAlternativeListDialog dojo/i18n!buildspace/nls/RationalizeRate".split(" "),function(g,v,w,x,y,z,l,m,n,p,q,h,A,r,t,f){var u=g("buildspace.apps.RationalizeRate.Explorer",
dijit.EditableTree,{splitter:!0,region:"left",container:null,openOnClick:!1,labelAttr:"name",rootProject:{},autoExpand:!0,billElementObj:null,style:"background-color:#e5e5e5;width:230px;height:100%;",constructor:function(a){this.inherited(arguments);var e=new dojo.data.ItemFileWriteStore({url:"tendering/getProjectStructure/id/"+a.rootProject.id}),c=new dijit.tree.ForestStoreModel({store:e,rootId:a.rootProject.id,rootLabel:buildspace.truncateString(a.rootProject.title,200),childrenAttrs:["__children"]});
this.getIconClass=dojo.hitch(e,function(b,d){return b.root||parseInt(String(b.type))==buildspace.apps.RationalizeRate.ProjectStructureConstants.TYPE_LEVEL?d?"icon-16-container icon-16-file":"icon-16-container icon-16-folder":parseInt(String(b.type))==buildspace.apps.RationalizeRate.ProjectStructureConstants.TYPE_BILL?"icon-16-container icon-16-list":parseInt(String(b.type))==buildspace.apps.RationalizeRate.ProjectStructureConstants.TYPE_SUPPLY_OF_MATERIAL_BILL?"icon-16-container icon-16-spreadsheet":
"icon-16-container icon-16-document"});this.model=c},createBill:function(a,e){var c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."}),b=this;c.show().then(function(){dojo.xhrPost({url:"tendering/createBill",content:{parent_id:a.id,type:e,_csrf_token:a._csrf_token},handleAs:"json",load:function(d){if(d.success){var k=b.model;a.root?k.newItem(d.item):k.newItem(d.item,a);dijit.byId("main-project_breakdown").content.grid.reload()}c.hide()},error:function(d){c.hide()}})})},removeBillTab:function(){this.container.workarea.removeBillTab()},
initTab:function(a,e){var c=!1,b=this.container.workarea.getChildren(),d;for(d in b)"object"==typeof b[d].pane_info&&b[d].pane_info.id==String(a.id)+"-form_"+String(a.type)&&(c=!0,this.container.workarea.selectChild(b[d]));c||this.container.workarea.makeTab(a,e,!0)}});return g("buildspace.apps.RationalizeRate.Builder",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",gutters:!1,project:null,type:null,workarea:null,postCreate:function(){this.inherited(arguments);var a=this.explorer=
u({rootProject:this.project,container:this}),e=this,c=this.project,b=new dijit.Toolbar({region:"top",style:"padding:2px;width:100%;"});b.addChild(new dijit.form.Button({label:f.backTo+" "+f.tendering,iconClass:"icon-16-container icon-16-directional_left",style:"outline:none!important;",onClick:dojo.hitch(this,"openBuilderWin",c)}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({label:f.importRationalizedRates,iconClass:"icon-16-container icon-16-import",disabled:parseInt(String(e.project.status_id))==
buildspace.constants.STATUS_IMPORT||parseInt(String(e.project.status_id))==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE?!1:!0,onClick:function(d){(new n({title:f.importRationalizedRates,project:e.project})).show()}}));c=new q({style:"display: none;"});c.addChild(new h({label:f.printOriginalBQ,onClick:function(d){e.printRates(0)}}));c.addChild(new h({label:f.printRationalizeBQ,onClick:function(d){e.printRates(1)}}));c=new p({label:f.printBQ,iconClass:"icon-16-container icon-16-print",dropDown:c});
b.addChild(new dijit.ToolbarSeparator);b.addChild(c);a=this.workarea=new l({rootProject:this.project,explorer:a,type:this.type});a.startup();this.addChild(b);this.addChild(a)},printRates:function(a){(parseInt(this.project.has_tender_alternative)?new t({project:this.project,workArea:this.workarea,type:"printRationalizeRate",opt:{printRationalizeRate:a}}):new m({projectId:parseInt(String(this.project.id)),statusId:parseInt(String(this.project.status_id)),title:a?f.printRationalizeBQ:f.printOriginalBQ,
printRationalizedRate:a,_csrf_token:String(this.project._csrf_token)})).show()},openBuilderWin:function(a){this.kill();this.project=a;this.win=new buildspace.widget.Window({title:buildspace.truncateString(a.title,100)+" ("+f.status+": "+String(a.status).toUpperCase()+")",onClose:dojo.hitch(this,"kill")});a=r({project:a});this.win.addChild(a);this.win.show();this.win.startup()},kill:function(){"undefined"!=typeof this.win&&this.win.close()}})});
