define("buildspace/apps/RationalizeRate/PrintBillDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/i18n!buildspace/nls/PrintBillDialog".split(" "),function(f,m,n,p,q,r,g,h,e){var k=f("buildspace.apps.RationalizeRate.PrintBillGrid",dojox.grid.EnhancedGrid,{projectId:0,statusId:null,tenderAlternative:null,region:"center",contractor:null,style:"border-top:none;",_csrf_token:null,printRationalizedRate:!1,currentModuleName:null,canSort:function(a){return!1},
postCreate:function(){this.inherited(arguments);var a=this,c=this.tenderAlternative?parseInt(String(this.tenderAlternative.id)):-1;this.on("RowClick",function(d){var b=a.getItem(d.rowIndex);d=d.cell.field;if(a.printRationalizedRate){if("printWithoutNotListedItem"==d&&b&&0<parseInt(String(b.id)))return parseInt(a.statusId)==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE||parseInt(a.statusId)==buildspace.constants.STATUS_POSTCONTRACT_SUB_PACKAGE?window.open("SubPackageRationalizedBQFinalPdf/"+a.projectId+
"/"+b.id+"/"+a._csrf_token+"/0","_blank"):window.open("RationalizedBQFinalPdf/"+a.projectId+"/"+b.id+"/"+a._csrf_token+"/0","_blank"),window.focus();if("printWithoutNotListedItem"==d&&b&&0==parseInt(String(b.id)))return parseInt(a.statusId)==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE||parseInt(a.statusId)==buildspace.constants.STATUS_POSTCONTRACT_SUB_PACKAGE?window.open("SubPackageRationalizedBQSummary/"+a.projectId+"/"+a._csrf_token+"/0","_blank"):window.open("RationalizedBQSummary/"+a.projectId+
"/"+c+"/"+a._csrf_token+"/0","_blank"),window.focus();if("printWithNotListedItem"==d&&b&&0<parseInt(String(b.id)))return parseInt(a.statusId)==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE||parseInt(a.statusId)==buildspace.constants.STATUS_POSTCONTRACT_SUB_PACKAGE?window.open("SubPackageRationalizedBQFinalPdf/"+a.projectId+"/"+b.id+"/"+a._csrf_token+"/1","_blank"):window.open("RationalizedBQFinalPdf/"+a.projectId+"/"+b.id+"/"+a._csrf_token+"/1","_blank"),window.focus();if("printWithNotListedItem"==
d&&b&&0==parseInt(String(b.id)))return parseInt(a.statusId)==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE||parseInt(a.statusId)==buildspace.constants.STATUS_POSTCONTRACT_SUB_PACKAGE?window.open("SubPackageRationalizedBQSummary/"+a.projectId+"/"+a._csrf_token+"/1","_blank"):window.open("RationalizedBQSummary/"+a.projectId+"/"+c+"/"+a._csrf_token+"/1","_blank"),window.focus()}else{if("printWithoutNotListedItem"==d&&b&&0<parseInt(String(b.id)))return parseInt(a.statusId)==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE||
parseInt(a.statusId)==buildspace.constants.STATUS_POSTCONTRACT_SUB_PACKAGE?window.open("SubPackageEstimationBQFinalPdf/"+a.projectId+"/"+b.id+"/"+a._csrf_token+"/0","_blank"):window.open("EstimationBQFinalPdf/"+a.projectId+"/"+b.id+"/"+a._csrf_token+"/0","_blank"),window.focus();if("printWithoutNotListedItem"==d&&b&&0==parseInt(String(b.id)))return parseInt(a.statusId)==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE||parseInt(a.statusId)==buildspace.constants.STATUS_POSTCONTRACT_SUB_PACKAGE?window.open("SubPackageEstimationBQSummary/"+
a.projectId+"/"+a._csrf_token+"/0","_blank"):window.open("EstimationBQSummary/"+a.projectId+"/"+c+"/"+a._csrf_token+"/0","_blank"),window.focus();if("printWithNotListedItem"==d&&b&&0<parseInt(String(b.id)))return parseInt(a.statusId)==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE||parseInt(a.statusId)==buildspace.constants.STATUS_POSTCONTRACT_SUB_PACKAGE?window.open("SubPackageEstimationBQFinalPdf/"+a.projectId+"/"+b.id+"/"+a._csrf_token+"/1","_blank"):window.open("EstimationBQFinalPdf/"+a.projectId+
"/"+b.id+"/"+a._csrf_token+"/1","_blank"),window.focus();if("printWithNotListedItem"==d&&b&&0==parseInt(String(b.id)))return parseInt(a.statusId)==buildspace.constants.STATUS_IMPORT_SUB_PACKAGE||parseInt(a.statusId)==buildspace.constants.STATUS_POSTCONTRACT_SUB_PACKAGE?window.open("SubPackageEstimationBQSummary/"+a.projectId+"/"+a._csrf_token+"/1","_blank"):window.open("EstimationBQSummary/"+a.projectId+"/"+c+"/"+a._csrf_token+"/1","_blank"),window.focus()}})},dodblclick:function(a){this.onRowDblClick(a)}}),
l=f("buildspace.apps.RationalizeRate.PrintBillGrid.CellFormatter",null,{rowCountCellFormatter:function(a,c,d){return parseInt(c)+1},descriptionCellFormatter:function(a,c){c=this.grid.getItem(c);return 0==parseInt(String(c.id))?e.summaryPage:a},printCellAddendumWithoutNotListedItemFormatter:function(a,c){return(a=this.grid.getItem(c))&&0<=parseInt(String(a.id))?'<a href="javascript:void(0);">'+e.print+"</a>":null},printCellAddendumWithNotListedItemFormatter:function(a,c){return(a=this.grid.getItem(c))&&
0<=parseInt(String(a.id))?'<a href="javascript:void(0);">'+e.print+"</a>":null}});return f("buildspace.apps.RationalizeRate.PrintBillGridDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:e.printBQ,contractor:!1,statusId:null,projectId:null,tenderAlternative:null,bqCSRFToken:null,printRationalizedRate:!1,_csrf_token:null,currentModuleName:"tendering",buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){h.set(this.containerNode,
{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==g.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:800px;height:350px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border:0px;"});c.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",
style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var d=this.tenderAlternative?"/tid/"+parseInt(String(this.tenderAlternative.id)):"",b=new l;d=dojo.data.ItemFileWriteStore({url:"printBQ/getProjectPrintList/id/"+this.projectId+d});b=k({projectId:parseInt(this.projectId),statusId:parseInt(this.statusId),tenderAlternative:this.tenderAlternative,contractor:this.contractor,_csrf_token:this._csrf_token,printRationalizedRate:this.printRationalizedRate,store:d,structure:[{name:"No.",field:"id",
width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:e.description,field:"title",width:"auto",formatter:b.descriptionCellFormatter},{name:e.numberOfItems,field:"item_count",width:"120px",styles:"text-align:center;"},{name:e.w_o+e.notListedItem,field:"printWithoutNotListedItem",width:"120px",styles:"text-align:center;",formatter:b.printCellAddendumWithoutNotListedItemFormatter},{name:e.w+e.notListedItem,field:"printWithNotListedItem",width:"120px",styles:"text-align:center;",
formatter:b.printCellAddendumWithNotListedItemFormatter}],currentModuleName:this.currentModuleName});a.addChild(c);a.addChild(b);return a}})});
