define("buildspace/apps/RationalizeRate/ProjectBreakdown","dojo/_base/declare dojo/_base/lang dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dojo/when ./BillGrid ./lumpSumPercentDialog ./primeCostRateDialog dojo/aspect dojo/i18n!buildspace/nls/RationalizeRate".split(" "),function(p,t,u,v,B,C,D,w,r,E,F,x,h){var q=p("buildspace.apps.RationalizeRate.ProjectBreakdownGrid",u,{rootProject:null,explorer:null,style:"border:none;",
region:"center",keepSelection:!0,tender_setting:null,tender_companies:null,rowSelector:"0px",constructor:function(a){this.formatter=new v;this.tender_setting=a.tender_setting;this.tender_companies=a.tender_companies;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;this.generateColumnStructure();this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments);this.on("RowClick",function(a){(a=
this.getItem(a.rowIndex))&&0<parseInt(String(a.id))&&parseInt(String(a.type))==buildspace.apps.RationalizeRate.ProjectStructureConstants.TYPE_BILL?this.disableToolbarButtons(!1,["ExportItemFromBill"],["ImportDropDown"]):this.disableToolbarButtons(!0)},!0)},generateColumnStructure:function(){var a=this.formatter;this.structure=this.fixedColumns={noscroll:!1,width:"50",cells:[[{name:h.description,field:"title",width:"auto",formatter:y.treeCellFormatter},{name:h.amount,field:"overall_total_after_markup",
width:"150px",styles:"color:blue;text-align: right;",formatter:a.unEditableCurrencyCellFormatter},{name:h.rationalizedTotal,field:"rationalized_overall_total_after_markup",width:"150px",styles:"color:blue;text-align: right;",formatter:a.unEditableCurrencyCellFormatter}]]}},dodblclick:function(a){this.onRowDblClick(a)},disableToolbarButtons:function(a,b){if(a&&b instanceof Array){var d=this;dojo.forEach(b,function(c){(c=dijit.byId(d.rootProject.id+c+"Row-button"))&&c._setDisabledAttr(!1)})}},reload:function(){this.store.close();
this._refresh()}}),z=p("buildspace.apps.RationalizeRate.GridContainer",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;width:100%;height:100%;",gutters:!1,stackContainerTitle:"",project:null,rowSelector:null,gridOpts:{},postCreate:function(){this.inherited(arguments);t.mixin(this.gridOpts,{rootProject:this.project,region:"center",borderContainerWidget:this});var a=this.grid=new q(this.gridOpts);this.addChild(a);if(a=dijit.byId("rationalizeRateBreakdown"+this.project.id+"-stackContainer")){var b=
new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),id:this.pageId});a.addChild(b);b.set("content",this);a.selectChild(this.pageId)}}}),y={rowCountCellFormatter:function(a,b){return 0<a?a:""},treeCellFormatter:function(a,b){b=this.grid.getItem(b);var d=16*parseInt(String(b.level));a=null==a?"&nbsp":a;b&&(-9999==parseInt(String(b.id))||parseInt(String(b.type))<buildspace.apps.RationalizeRate.ProjectStructureConstants.TYPE_BILL)&&(a="<b>"+a+"</b>");return'<div class="treeNode" style="padding-left:'+
d+'px;"><div class="treeContent">'+a+"&nbsp;</div></div>"}};return p("buildspace.apps.RationalizeRate.ProjectBreakdown",dijit.layout.BorderContainer,{region:"center",style:"padding:0px;width:100%;height:100%;",gutters:!1,rootProject:null,type:null,explorer:null,grid:null,postCreate:function(){this.inherited(arguments);this.reconstructBillContainer()},reconstructBillContainer:function(){var a=dijit.byId("rationalizeRateBreakdown"+this.rootProject.id+"-controllerPane"),b=dijit.byId("rationalizeRateBreakdown"+
this.rootProject.id+"-stackContainer");a&&b&&(a.destroyRecursive(),b.destroyRecursive());if(parseInt(this.rootProject.has_tender_alternative)){var d=h.tenderAlternatives;var c=this.createTenderAlternativeGrid()}else d=h.bills,c=this.createBreakdownGrid();b=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",region:"center",id:"rationalizeRateBreakdown"+this.rootProject.id+"-stackContainer"});a=new dijit.layout.StackController({region:"top",containerId:"rationalizeRateBreakdown"+
this.rootProject.id+"-stackContainer"});a=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"rationalizeRateBreakdown"+this.rootProject.id+"-controllerPane",content:a});this.addChild(b);this.addChild(a);c&&(c=new dojox.layout.ContentPane({title:d,content:c}),b.addChild(c));var l=this;dojo.subscribe("rationalizeRateBreakdown"+this.rootProject.id+"-stackContainer-selectChild","",function(f){var k=dijit.byId("rationalizeRateBreakdown"+l.rootProject.id+
"-stackContainer");if(k){var e=k.getChildren(),g=dojo.indexOf(e,f);g+=1;if(e.length>g){for(;e.length>g;)k.removeChild(e[g]),e[g].destroyDescendants(),e[g].destroyRecursive(),g+=1;if(f.grid){var m=f.grid.selection.selectedIndex;f.grid.store.save();f.grid.store.close();var n=x.after(f.grid,"_onFetchComplete",function(){n.remove();-1<m&&(this.scrollToRow(m),this.selection.setSelected(m,!0))});f.grid.sort()}}}})},createTenderAlternativeGrid:function(){var a=this,b=new dojo.data.ItemFileWriteStore({clearOnClose:!0,
url:"rationalizeRate/getTenderAlternatives/id/"+String(this.rootProject.id)});return this.grid=q({rootProject:this.rootProject,explorer:this.explorer,onRowDblClick:function(d){(d=this.getItem(d.rowIndex))&&0<parseInt(String(d.id))&&a.createTenderAlternativeBreakdownGrid(d)},store:b})},createTenderAlternativeBreakdownGrid:function(a){var b=this,d=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"rationalizeRate/getTenderAlternativeBills/id/"+String(a.id)});new z({stackContainerTitle:a.title,project:this.rootProject,
pageId:"tender_alternative_bill-page-"+a.id,id:"tender_alternative_bill-page-container-"+a.id,gridOpts:{store:d,onRowDblClick:function(c){(c=this.getItem(c.rowIndex))&&0<parseInt(String(c.id))&&parseInt(String(c.type))==buildspace.constants.TYPE_BILL&&b.createElementGrid(c)}}})},createBreakdownGrid:function(){var a=this,b=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"rationalizeRate/getProjectBreakdown/id/"+this.rootProject.id});return this.grid=q({rootProject:this.rootProject,explorer:this.explorer,
onRowDblClick:function(d){(d=this.getItem(d.rowIndex))&&0<parseInt(String(d.id))&&parseInt(String(d.type))==buildspace.constants.TYPE_BILL&&a.createElementGrid(d)},store:b})},createElementGrid:function(a){this.billId=a.id;var b=dojo.data.ItemFileWriteStore({url:"rationalizeRate/getElementList/id/"+a.id,clearOnClose:!0,urlPreventCache:!0}),d=dojo.xhrGet({url:"billManager/getBillInfo",handleAs:"json",content:{id:a.id}}),c=this,l=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});
l.show().then(function(){d.then(function(f){l.hide();try{var k=new r({stackContainerTitle:a.title,billId:parseInt(String(a.id)),rootProject:c.rootProject,pageId:"element-page-"+a.id,id:"element-page-container-"+a.id,gridOpts:{store:b,typeColumns:f.column_settings,currentGridType:"element",onRowDblClick:function(e){(e=this.getItem(e.rowIndex))&&0<parseInt(String(e.id))&&null!==String(e.description)&&""!==String(e.description)&&c.createItemGrid(e,f,k,a)}}})}catch(e){console.debug(e)}})})},createItemGrid:function(a,
b,d,c){this.billId=c.id;var l=this,f={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY_TEXT,
buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID_TEXT],values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM,
buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PROVISIONAL,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE,
buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID]},k={options:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N_TEXT,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_TEXT],values:[buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER]},e=new dojo.data.ItemFileWriteStore({url:"rationalizeRate/getItemList/id/"+a.id+"/bill_id/"+c.id,clearOnClose:!0}),g=dojo.xhrGet({url:"billManager/getUnits/billId/"+c.id,handleAs:"json"}),m=
buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});g.then(function(n){return n});m.show().then(function(){w(g,function(n){m.hide();try{new r({stackContainerTitle:a.description,billId:parseInt(String(c.id)),rootProject:l.rootProject,id:"item-page-container-"+c.id,elementId:a.id,pageId:"item-page-"+c.id,type:"tree",gridOpts:{store:e,escapeHTMLInData:!1,typeColumns:b.column_settings,markupSettings:b.markup_settings,elementGridStore:d,hierarchyTypes:f,hierarchyTypesForHead:k,updateUrl:"rationalizeRate/billItemRateUpdate",
unitOfMeasurements:n,currentGridType:"item"}})}catch(A){console.debug(A)}},function(n){})})}})});
