define("buildspace/apps/PostContractSubPackageReport/VariationOrder/VariationOrderGrid","dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/aspect dojo/request dojo/_base/connect dojo/number dojo/dom-style dijit/focus dojo/_base/event dojo/keys dijit/TooltipDialog dijit/popup dojox/grid/EnhancedGrid dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dijit/PopupMenuItem dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojox/grid/enhanced/plugins/IndirectSelection ./PrintAllSelectedVODialog ./PrintAllVOWithClaims ./PrintSelectedVOItemsDialog ./PrintAllVOItemsWithClaimDialog ./PrintSelectedVOItemsWithBuildUpQtyDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),
function(m,n,E,p,g,h,F,G,H,I,J,q,k,r,t,u,v,K,w,x,L,y,z,A,B,C,M,e){var D=m("buildspace.apps.PostContractSubPackageReport.VariationOrder.VariationOrderEnhancedGrid",r,{type:null,style:"border-top:none;",rowSelector:"0px",selectedItem:null,region:"center",subPackage:null,locked:!1,constructor:function(a){this.connects=[];this.rearranger=w(this,{});this.formulatedColumn=x(this,{});this.plugins={indirectSelection:{headerSelector:!0,width:"40px",styles:"text-align: center;"}}},postCreate:function(){var a=
this,b,c;a.inherited(arguments);b="vo"===a.type?a.gridContainer.voSelectedStore:a.gridContainer.voItemSelectedStore;p.after(a,"_onFetchComplete",function(){a.gridContainer.markedCheckBoxObject(a,b)});this._connects.push(h.connect(this,"onCellMouseOver",function(b){var d=a.getItem(b.rowIndex),e=b.rowIndex,l=b.cell.field.replace("-value","");"undefined"!==typeof d[l+"-has_formula"]&&d[l+"-has_formula"][0]&&(d=d[l+"-value"][0],d=this.formulatedColumn.convertItemIdToRowIndex(d,e),null===c&&(c=new q({content:d,
onMouseLeave:function(){k.close(c)}}),k.open({popup:c,around:b.cellNode})))}));this._connects.push(h.connect(this,"onCellMouseOut",function(a){void 0!==c&&k.close(c)}))},startup:function(){var a=this;a.inherited(arguments);this._connects.push(h.connect(this,"onCellClick",function(b){""===b.cell.name&&a.singleCheckBoxSelection(b)}));this._connects.push(h.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)}))},canSort:function(a){return!1},onStyleRow:function(a){this.inherited(arguments);
if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(c,function(a,b){var c=dojo.attr(a,"rowSpan");(!c||2>c)&&dojo.attr(a,"rowSpan",2)})}},editableCellDblClick:function(a){var b;b=1<this._click.length&&has("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=this._click[1].rowIndex?this._click[0]:a;this.focus.setFocusCell(b.cell,b.rowIndex);
this.onRowClick(b);this.onRowDblClick(a)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);else this.onCellDblClick(a);else this.onRowDblClick(a)},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,h.disconnect);delete this._connects}});return m("buildspace.apps.PostContractSubPackageReport.VariationOrder.VariationOrderGrid",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,subPackage:null,
variationOrder:null,gridOpts:{},locked:!1,type:null,pageId:0,postCreate:function(){var a=this,b;this.inherited(arguments);n.mixin(a.gridOpts,{type:a.type,subPackage:a.subPackage,variationOrder:a.variationOrder,locked:a.locked});var c=new u({style:"display: none;"}),d=this.grid=new D(a.gridOpts),f=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});switch(this.type){case "vo":b="SP_variationOrder-"+a.subPackage.id;break;case "vo-items":b="SP_variationOrderItems-"+a.subPackage.id+
"_"+a.variationOrder.id;break;case "vo-claims":break;default:throw Error("type must be set!");}dojo.forEach(["voSummary","voSummaryWithClaims","voSelectedItems","voItemsWithClaim","voItemsWithBuildUpQty"],function(b){var d;switch(b){case "voSummary":d="openPrintAllSelectedVODialog";break;case "voSummaryWithClaims":d="openPrintAllVOWithClaims";break;case "voSelectedItems":d="openPrintAllSelectedVOItems";break;case "voItemsWithClaim":d="openPrintAllVOItemsWithClaim";break;case "voItemsWithBuildUpQty":d=
"openPrintSelectedVOItemsWithBuildUpQty"}c.addChild(new v({label:e[b],onClick:function(){a[d](b)}}))});f.addChild(new t({label:e.printPreview,iconClass:"icon-16-container icon-16-print",dropDown:c}));this.addChild(f);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:d,region:"center"}));"vo-claims"!==this.type&&(b=dijit.byId(b+"-stackContainer"))&&(f=document.createElement("div"),f=new dojox.layout.ContentPane({title:buildspace.truncateString(a.stackContainerTitle,60),id:a.pageId,
executeScripts:!0},f),b.addChild(f),f.set("content",a),n.mixin(f,{grid:d}),b.selectChild(a.pageId))},openPrintAllSelectedVODialog:function(){var a=this,b=[];a.gridOpts.gridContainer.voSelectedStore.query().forEach(function(a){b.push(a.id)});var c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});c.show();g.post("postContractSubPackageVO/getPrintingSelectedVO",{handleAs:"json",data:{subPackageId:a.subPackage.id,vo_ids:JSON.stringify(a.gridOpts.gridContainer.arrayUnique(b))}}).then(function(d){(new y({subPackage:a.subPackage,
subPackageId:a.subPackage.id,title:e.voSummary,data:d,selectedItems:b})).show();c.hide()},function(a){console.log(a);c.hide()})},openPrintAllVOWithClaims:function(){var a=this,b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});b.show();g.post("postContractSubPackageVO/getPrintingVOWithClaims",{handleAs:"json",data:{subPackageId:a.subPackage.id}}).then(function(c){(new z({subPackage:a.subPackage,subPackageId:a.subPackage.id,title:e.voSummaryWithClaims,data:c})).show();b.hide()},
function(a){console.log(a);b.hide()})},openPrintAllSelectedVOItems:function(){var a=this,b=[];a.gridOpts.gridContainer.voItemSelectedStore.query().forEach(function(a){b.push(a.id)});var c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});c.show();g.post("postContractSubPackageVO/getPrintingSelectedVOItemsDialog",{handleAs:"json",data:{subPackageId:a.subPackage.id,item_ids:JSON.stringify(a.gridOpts.gridContainer.arrayUnique(b))}}).then(function(d){(new A({subPackage:a.subPackage,
subPackageId:a.subPackage.id,title:e.voSelectedItems,data:d,selectedItems:b})).show();c.hide()},function(a){console.log(a);c.hide()})},openPrintAllVOItemsWithClaim:function(){var a=this,b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});b.show();g.post("postContractSubPackageVO/getPrintingVOItemsWithClaim",{handleAs:"json",data:{subPackageId:a.subPackage.id}}).then(function(c){(new B({subPackage:a.subPackage,subPackageId:a.subPackage.id,title:e.voItemsWithClaim,data:c})).show();
b.hide()},function(a){console.log(a);b.hide()})},openPrintSelectedVOItemsWithBuildUpQty:function(){var a=this,b=[];a.gridOpts.gridContainer.voItemSelectedStore.query().forEach(function(a){b.push(a.id)});var c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});c.show();g.post("postContractSubPackageVO/getPrintingSelectedVOItemsWithBuildUpQty",{handleAs:"json",data:{subPackageId:a.subPackage.id,item_ids:JSON.stringify(a.gridOpts.gridContainer.arrayUnique(b))}}).then(function(d){(new C({subPackage:a.subPackage,
subPackageId:a.subPackage.id,title:e.voItemsWithBuildUpQty,data:d,selectedItems:b})).show();c.hide()},function(a){console.log(a);c.hide()})}})});
