define("buildspace/apps/StockOut/StockOutDialog/DeliveryOrderDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/keys dojo/dom-style dojox/layout/ContentPane buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!../../../nls/StockOut".split(" "),function(k,r,l,t,u,v,m,y,g){var x=k("buildspace.apps.StockOut.ImportResourceGrid",dojox.grid.EnhancedGrid,{type:null,dialogWidget:null,_csrf_token:null,resource:null,itemIds:[],style:"border-top:none;",
stockOutUsedQuantity:null,deliveryOrder:null,itemListGrid:null,constructor:function(a){this.itemIds=[];this.connects=[];"tree"===a.type&&(this.urlGetDescendantIds="bqLibrary/getResourceDescendantsForImport",this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align: center;"}});this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){var a=this;a.inherited(arguments);this.on("RowClick",function(b){b=a.getItem(b.rowIndex);"tree"===a.type&&(b&&0<parseInt(b.id)?
a.disableToolbarButtons(!1):a.disableToolbarButtons(!0))});"tree"===this.type&&(this._connects.push(l.connect(this,"onCellClick",function(b){a.selectTree(b)})),this._connects.push(l.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)})))},dodblclick:function(a){this.onRowDblClick(a)},selectTree:function(a){a=a.rowIndex;var b=this.selection.selected[a];var c=this.getItem(a);var d=this;var f=this.store;if(c.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER){var e=
buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."});var h=-1;e.show().then(function(){dojo.xhrPost({url:d.urlGetDescendantIds,content:{id:c.id},handleAs:"json",load:function(q){dojo.forEach(q.items,function(w){f.fetchItemByIdentity({identity:w.id,onItem:function(n){n&&(h=n._0,d.pushItemIdIntoGridArray(n,b),d.selection[b?"addToSelection":"deselect"](h))}})});e.hide()},error:function(q){e.hide()}})})}else null!=c.type&&c.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM&&
d.pushItemIdIntoGridArray(c,b)},pushItemIdIntoGridArray:function(a,b){var c=dojo.indexOf(this.itemIds,parseInt(a.id));b?-1===c&&this.itemIds.push(parseInt(a.id)):-1!==c&&this.itemIds.splice(c,1)},toggleAllSelection:function(a){var b=this;var c=this;var d=b.selection;if(a)return d.selectRange(0,b.rowCount-1),b.itemIds=[],b.store.fetch({onComplete:function(f){return dojo.forEach(f,function(e,h){0<parseInt(e.id)&&(b.itemIds.push(parseInt(e.id)),c.disableToolbarButtons(!1))})}});d.deselectAll();b.itemIds=
[]},disableToolbarButtons:function(a){var b=dijit.byId("ImportResourceGrid-Import-button");b&&b._setDisabledAttr(a)},copy:function(){var a=this;var b=a.itemIds;if(0<b.length){var c=buildspace.dialog.indeterminateProgressBar({title:g.importingItems+". "+g.pleaseWait+"..."});c.show().then(function(){dojo.xhrPost({url:"stockOut/copyDeliveryOrderItems",content:{stockOutUsedQuantityId:parseInt(a.stockOutUsedQuantity.id),deliveryOrderId:parseInt(a.deliveryOrder.id),ids:[b],_csrf_token:a._csrf_token},handleAs:"json",
load:function(d){c.hide();d.success?(a.itemIds=[],a.itemListGrid.refreshGrid()):a.itemIds=[];a.dialogWidget.hide()},error:function(d){a.itemIds=[];c.hide();a.dialogWidget.hide()}})})}},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,l.disconnect);delete this._connects}});var p=k("buildspace.apps.StockOut.ImportResourceGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",gutters:!1,stockOutUsedQuantity:null,type:null,gridOpts:{},postCreate:function(){this.inherited(arguments);
r.mixin(this.gridOpts,{type:this.type,stockOutUsedQuantity:this.stockOutUsedQuantity,region:"center"});var a=new x(this.gridOpts);if("tree"===this.type){var b=new dijit.Toolbar({region:"top",style:"padding:2px;border:none;width:100%;"});b.addChild(new dijit.form.Button({id:"ImportResourceGrid-Import-button",label:g.copy,iconClass:"icon-16-container icon-16-import",disabled:!0,onClick:function(){a.copy()}}));this.addChild(b)}this.addChild(a);if(b=dijit.byId("stockOutUsedQuantityFromResourceLibrary-stackContainer")){var c=
document.createElement("div");c=new v({title:buildspace.truncateString(this.title,60),executeScripts:!0},c);b.addChild(c);c.set("content",this);b.selectChild(c)}}});return k("buildspace.apps.StockOut.ImportResourceDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,stockOutUsedQuantity:null,itemListGrid:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",margin:"0px"});
this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode===t.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=this;var b=new dijit.layout.BorderContainer({style:"padding:0px;width:900px;height:400px;",gutters:!1});var c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:g.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",
onClick:dojo.hitch(this,"hide")}));var d=new m;var f=dojo.data.ItemFileWriteStore({url:"stockOut/getResourceWithStockInsByProject/projectId/"+parseInt(a.project.id)});d=new p({stockOutUsedQuantity:a.stockOutUsedQuantity,gridOpts:{store:f,itemListGrid:a.itemListGrid,structure:[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:d.rowCountCellFormatter,noresize:!0},{name:g.description,field:"name",width:"auto",formatter:d.treeCellFormatter,noresize:!0}],onRowDblClick:function(e){e=
this.getItem(e.rowIndex);0<parseInt(e.id)&&a.createResourceTradeGrid(e)}}});d=this.makeGridContainer(d);b.addChild(c);b.addChild(d);return b},createResourceTradeGrid:function(a){var b=this;var c=new m;var d=new dojo.data.ItemFileWriteStore({url:"stockOut/getResourceTradeWithStockInsByProject/projectId/"+parseInt(b.project.id)+"/resourceId/"+parseInt(a.id)});return new p({title:a.name,stockOutUsedQuantity:b.stockOutUsedQuantity,gridOpts:{store:d,itemListGrid:b.itemListGrid,dialogWidget:b,structure:[{name:"No",
field:"id",width:"30px",styles:"text-align: center;",formatter:c.rowCountCellFormatter,noresize:!0},{name:g.description,field:"description",width:"auto",formatter:c.treeCellFormatter,noresize:!0}],onRowDblClick:function(f){f=this.getItem(f.rowIndex);0<parseInt(f.id)&&b.createItemGrid(f)}}})},createItemGrid:function(a){var b=new m;var c=new dojo.data.ItemFileWriteStore({url:"stockOut/getCopyItemListingsWithDeliveryOrder/stockOutUsedQuantityId/"+parseInt(this.stockOutUsedQuantity.id)+"/resourceTradeId/"+
parseInt(a.id)});return new p({title:a.description[0],stockOutUsedQuantity:this.stockOutUsedQuantity,type:"tree",gridOpts:{deliveryOrder:a,store:c,itemListGrid:this.itemListGrid,dialogWidget:this,_csrf_token:a._csrf_token,structure:[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:b.rowCountCellFormatter,noresize:!0},{name:g.description,field:"description",width:"auto",formatter:b.treeCellFormatter,noresize:!0},{name:g.unit,field:"uom_id",styles:"text-align: center;",width:"70px",
formatter:b.unitIdCellFormatter,noresize:!0},{name:g.doQuantity,field:"do_quantity",styles:"text-align:right;color:blue;",width:"90px",formatter:b.unEditableCurrencyCellFormatter,noresize:!0},{name:g.stockOutQuantity,field:"stock_out_quantity",styles:"text-align:right;color:blue;",width:"90px",formatter:b.unEditableCurrencyCellFormatter,noresize:!0},{name:g.availableDOQuantity,field:"balance_quantity",styles:"text-align:right;color:blue;",width:"90px",formatter:b.unEditableCurrencyCellFormatter,noresize:!0}]}})},
makeGridContainer:function(a){var b;(b=dijit.byId("stockOutUsedQuantityFromResourceLibrary-stackContainer"))&&dijit.byId("stockOutUsedQuantityFromResourceLibrary-stackContainer").destroyRecursive();b=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"stockOutUsedQuantityFromResourceLibrary-stackContainer"});a=new dijit.layout.ContentPane({title:g.resource,content:a});b.addChild(a);a=new dijit.layout.StackController({region:"top",containerId:"stockOutUsedQuantityFromResourceLibrary-stackContainer"});
var c=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:a});a=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});a.addChild(b);a.addChild(c);dojo.subscribe("stockOutUsedQuantityFromResourceLibrary-stackContainer-selectChild","",function(d){var f,e;if(f=dijit.byId("stockOutUsedQuantityFromResourceLibrary-stackContainer")){var h=f.getChildren();d=dojo.indexOf(h,dijit.byId(d.id));
d+=1;for(e=[];h.length>d;)f.removeChild(h[d]),h[d].destroyRecursive(!0),e.push(d+=1);return e}});return a}})});
