(function(){define("buildspace/apps/RationalizeRateReport/PrintPreviewDialog/PrintSelectedItemRateGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/RationalizeRate".split(" "),function(e,p,q,r,t,u,v,h,k,l,w,m,n,d){var f,g;f=e("buildspace.apps.RationalizeRateReport.SelectedItemRateGrid",dojox.grid.EnhancedGrid,
{style:"border-top:none;",region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1}});g=e("buildspace.apps.RationalizeRateReport.SelectedItemRateGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,billId:-1,elementId:-1,selectedTenderers:[],selectedItems:[],type:null,postCreate:function(){var b,c,a;c=this;c.inherited(arguments);b=this.grid=new f({store:c.store,structure:c.structure,
selectedItems:c.selectedItems});a=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});a.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",onClick:function(a){return c.openPrintingDialog()}}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return c.dialog.hide()}}));c.addChild(a);return c.addChild(new dijit.layout.ContentPane({style:"width:100%",
content:b,region:"center"}))},openPrintingDialog:function(b){var c;null==b&&(b=this);c=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});c.show();return l.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(a){a=new m({title:b.dialog.title,selectedRows:b.selectedItems,printURL:"printReport/printSelectedItemRate",exportURL:"exportExcelReport/exportSelectedItemRate",billId:b.billId,elementId:b.elementId,_csrf_token:a._csrf_token});c.hide();return a.show()},
function(a){return c.hide()})}});return e("buildspace.apps.RationalizeRateReport.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,billId:-1,elementId:-1,data:null,type:null,selectedTenderers:[],selectedItems:[],buildRendering:function(){var b;b=this.createContent();b.startup();this.content=b;return this.inherited(arguments)},postCreate:function(){k.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},
_onKey:function(b){if(b.keyCode===h.ESCAPE)return dojo.stopEvent(b)},onHide:function(){return this.destroyRecursive()},createContent:function(){var b,c;b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});c=new g({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,selectedTenderers:this.selectedTenderers,selectedItems:this.selectedItems,structure:this.constructGridStructure(),billId:this.billId,elementId:this.elementId,type:this.type});b.addChild(c);
return b},constructGridStructure:function(b,c){var a,e,f,g;a=new n;e=[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter},{name:d.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,formatter:a.billRefCellFormatter},{name:d.description,field:"description",width:"auto",formatter:a.printPreviewTreeCellFormatter,noresize:!0},{name:d.quantity,field:"grand_total_quantity",width:"70px",styles:"text-align:right;color:blue;",
formatter:a.unEditableNumberCellFormatter,noresize:!0},{name:d.estimate,field:"rate_after_markup",styles:"text-align:right;color:blue;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0}];a=[{name:d.rationalizedRate,field:"rationalized_rate-value",styles:"text-align:right;color:blue;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0},{name:d.difference+" %",field:"rationalized-difference_percentage",styles:"text-align:right;color:blue;",width:"100px",formatter:a.unEditablePercentageCellFormatter,
noresize:!0},{name:d.difference+" "+buildspace.currencyAbbreviation,field:"rationalized-difference_amount",styles:"text-align:right;color:blue;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0}];for(f in a)g=a[f],e.push(g);return e}})})}).call(this);
