// Generated by CoffeeScript 1.9.0
(function() {
  define('buildspace/apps/StockInReport/InvoiceDeliveryOrderTab/ReadOnlyInvoiceInformationForm', ["dojo/_base/declare", 'dojo/_base/lang', "dojo/on", "dojo/keys", "dojo/parser", "dijit/_WidgetBase", "dijit/_OnDijitClickMixin", "dijit/_TemplatedMixin", "dijit/_WidgetsInTemplateMixin", 'dijit/Toolbar', 'dijit/form/Button', "dijit/layout/BorderContainer", "dijit/form/ValidationTextBox", "dijit/form/DateTextBox", "dojo/dom-construct", "dojo/dom-style", "dojo/dom-attr", "dojo/dom-form", "dojo/request", "dojox/validate/web", "dijit/form/FilteringSelect", "dojo/store/Memory", "dojox/form/Manager", "dojo/text!./templates/readOnlyInvoiceForm.html", 'dojo/i18n!../../../nls/StockIn'], function(declare, lang, on_, keys, parser, _WidgetBase, _OnDijitClickMixin, _TemplatedMixin, _WidgetsInTemplateMixin, Toolbar, Button, BorderContainer, ValidationTextBox, DateTextBox, domConstruct, domStyle, domAttr, domForm, request, web, FilteringSelect, Memory, Manager, template, nls) {
    var invoiceForm;
    invoiceForm = declare("buildspace.apps.StockInReport.InvoiceInformation.ReadOnlyInvoiceForm", [_WidgetBase, _OnDijitClickMixin, _TemplatedMixin, _WidgetsInTemplateMixin], {
      baseClass: "buildspace-form",
      templateString: template,
      region: 'center',
      style: "overflow: auto;",
      formInfo: null,
      nls: nls,
      invoiceId: -1,
      startup: function() {
        this.inherited(arguments);
        if (this.formInfo["attachmentDownloadLink"]) {
          return this.showDownloadLink(this.formInfo["attachmentDownloadFileName"], this.formInfo["attachmentDownloadLink"]);
        }
      },
      showDownloadLink: function(fileName, downloadLink) {
        var anchorLink, container;
        container = this["invoiceFileDownloadLink-" + this.invoiceId];
        domStyle.set(container, "display", "block");
        anchorLink = dojo.create("a", {
          href: downloadLink,
          innerHTML: "Download",
          download: fileName
        });
        domConstruct.empty(container);
        return domConstruct.place(anchorLink, container);
      }
    });
    return declare('buildspace.apps.StockInReport.InvoiceInformation.ReadOnlyInvoiceFormContainer', BorderContainer, {
      style: "padding:0;margin:0;",
      gutters: false,
      invoiceId: -1,
      formInfo: null,
      postCreate: function() {
        var form, self;
        this.inherited(arguments);
        self = this;
        form = new invoiceForm({
          invoiceId: self.invoiceId,
          formInfo: this.formInfo
        });
        return this.addChild(form);
      }
    });
  });

}).call(this);
