define("buildspace/apps/PostContractSubPackage/VariationOrder/BillDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/aspect dojo/html dojo/dom dojo/keys dojo/dom-style dojox/grid/EnhancedGrid dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(m,q,n,h,x,y,r,t,u,z,k,e){var w=m("buildspace.apps.PostContractSubPackage.VariationOrder.BillGrid",u,{type:null,style:"border-top:none;",rowSelector:"0px",
region:"center",locked:!1,variationOrder:null,variationOrderItem:null,variationOrderItemGrid:null,bill:null,dialogWidget:null,updateUrl:null,initialCheckboxSelection:!1,constructor:function(a){this.selectedItemIds=[];this.unSelectedItemIds=[];this.connects=[];a.locked||"update_total_unit-type_reference"!=a.type&&"omit_from_bill-bill_item"!=a.type||(this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}});this.inherited(arguments)},canSort:function(a){return!1},
dodblclick:function(a){this.onRowDblClick(a)},doclick:function(a){if(this.locked&&("update_total_unit-type_reference"==this.type||"omit_from_bill-bill_item"==this.type))return!1;this.inherited(arguments)},postCreate:function(){var a=this;a.inherited(arguments);"update_total_unit-type_reference"!=this.type&&"omit_from_bill-bill_item"!=this.type||h.after(this,"_onFetchComplete",function(){a.initialCheckboxSelection||(this.store.fetch({query:{selected:!0},queryOptions:{ignoreCase:!0},onComplete:this.markSelectedCheckBoxes,
scope:this}),a.initialCheckboxSelection=!0)});this.locked||(this._connects.push(n.connect(this,"onCellClick",function(c){a.selectItem(c)})),this._connects.push(n.connect(this.rowSelectCell,"toggleAllSelection",function(c){a.toggleAllSelection(c)})))},doApplyCellEdit:function(a,c,b){var d=this,f=d.getItem(c),g=d.store,p=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});a!==f[b][0]&&(p.show(),dojo.xhrPost({url:this.updateUrl,content:{id:f.id,attr_name:b,val:a,_csrf_token:f._csrf_token?
f._csrf_token:null},handleAs:"json",load:function(a){if(a.success){for(var e in a.data)f.hasOwnProperty(e)&&e!=g._getIdentifierAttribute()&&g.setValue(f,e,a.data[e]);g.save();var v=d.getCellByField(b);window.setTimeout(function(){d.focus.setFocusIndex(c,v.index)},10);p.hide()}},error:function(a){p.hide()}}));d.inherited(arguments)},markSelectedCheckBoxes:function(a,c){for(var b=0;b<a.length;b++){var d=a[b]._0;this.pushItemIdIntoGridArray(a[b],!0);this.selection.setSelected(d,!0)}},selectItem:function(a){var c=
a.rowIndex;a=this.selection.selected[c];((c=this.getItem(c))&&"update_total_unit-type_reference"==this.type&&0<c.level[0]||"omit_from_bill-bill_item"==this.type&&c.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&c.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&c.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE)&&this.pushItemIdIntoGridArray(c,a)},pushItemIdIntoGridArray:function(a,
c){var b=dojo.indexOf(this.selectedItemIds,a.id[0]),d=dojo.indexOf(this.unSelectedItemIds,a.id[0]);c?(-1==b&&this.selectedItemIds.push(a.id[0]),-1!=d&&this.unSelectedItemIds.splice(d,1)):(-1!=b&&this.selectedItemIds.splice(b,1),-1==d&&this.unSelectedItemIds.push(a.id[0]))},toggleAllSelection:function(a){var c=this,b=c.selection;a?(b.selectRange(0,c.rowCount-1),c.selectedItemIds=[],c.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,b){(a&&"update_total_unit-type_reference"==c.type&&0<
a.level[0]||"omit_from_bill-bill_item"==c.type&&a.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&a.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&a.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&a.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE)&&c.selectedItemIds.push(a.id[0])})}}),c.unSelectedItemIds=[]):(c.unSelectedItemIds=[],c.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,b){(a&&"update_total_unit-type_reference"==
c.type&&0<a.level[0]||"omit_from_bill-bill_item"==c.type&&a.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&a.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&a.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&a.type[0]!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE)&&c.unSelectedItemIds.push(a.id[0])})}}),b.deselectAll(),c.selectedItemIds=[])},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,n.disconnect);delete this._connects},
omitBillItems:function(a,c){var b=this,d=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),f={url:"variationOrder/spOmitBillItems",content:{vid:b.variationOrderItem.id,"void":b.variationOrder.id,last_item:c,uid:a.id,sid:[b.selectedItemIds],usid:[b.unSelectedItemIds],_csrf_token:b.variationOrderItem._csrf_token},handleAs:"json",load:function(a){if(a.success&&b.variationOrderItemGrid){b.variationOrderItemGrid.store.save();b.variationOrderItemGrid.store.close();
var c=h.after(b.variationOrderItemGrid,"_onFetchComplete",function(){c.remove();this.scrollToRow(this.selection.selectedIndex)});b.variationOrderItemGrid.sort()}b.selectedItemIds=[];b.unSelectedItemIds=[];d.hide();b.dialogWidget.hide()},error:function(a){b.selectedItemIds=[];b.unSelectedItemIds=[];d.hide();b.dialogWidget.hide()}};0==b.selectedItemIds.length?buildspace.dialog.confirm(e.confirmation,"<div>"+e.areYouSureToRemoveAllUnitAssignedToVariationOrderItem+"</div>",60,280,function(){d.show();
dojo.xhrPost(f)}):(d.show(),dojo.xhrPost(f))},saveTotalUnit:function(){var a=this,c=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),b={url:"variationOrder/spTotalUnitUpdate",content:{vid:a.variationOrderItem.id,bid:0<a.variationOrderItem.bill_item_id[0]?a.variationOrderItem.bill_item_id[0]:a.bill.id,ids:[a.selectedItemIds],_csrf_token:a.variationOrderItem._csrf_token},handleAs:"json",load:function(b){if(b.success&&a.variationOrderItemGrid){-1==b.id&&a.variationOrderItemGrid.disableToolbarButtons(!0);
a.variationOrderItemGrid.store.save();a.variationOrderItemGrid.store.close();var d=h.after(a.variationOrderItemGrid,"_onFetchComplete",function(){d.remove();this.scrollToRow(this.selection.selectedIndex)});a.variationOrderItemGrid._refresh()}a.selectedItemIds=[];a.unSelectedItemIds=[];c.hide();a.dialogWidget.hide()},error:function(b){a.selectedItemIds=[];a.unSelectedItemIds=[];c.hide();a.dialogWidget.hide()}};0==this.selectedItemIds.length?buildspace.dialog.confirm(e.confirmation,"<div>"+e.areYouSureToRemoveAllUnitAssignedToVariationOrderItem+
"</div>",60,280,function(){c.show();dojo.xhrPost(b)}):(c.show(),dojo.xhrPost(b))}}),l=m("buildspace.apps.PostContractSubPackage.VariationOrder.BillGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0;margin:0;width:100%;height:100%;",gutters:!1,variationOrder:null,variationOrderItem:null,variationOrderItemGrid:null,isLastItem:!1,bill:null,typeUnit:null,dialogWidget:null,gridOpts:{},locked:!1,type:null,pageId:0,postCreate:function(){var a=this;this.inherited(arguments);
q.mixin(this.gridOpts,{type:this.type,variationOrder:this.variationOrder,variationOrderItem:this.variationOrderItem,bill:this.bill,dialogWidget:this.dialogWidget,variationOrderItemGrid:this.variationOrderItemGrid,locked:this.locked});var c=this.grid=new w(this.gridOpts),b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",onClick:dojo.hitch(this.dialogWidget,"hide")}));this.locked||
"update_total_unit-type_reference"!=this.type&&"omit_from_bill-bill_item"!=this.type||(b.addChild(new dijit.ToolbarSeparator),b.addChild(new dijit.form.Button({label:"omit_from_bill-bill_item"==this.type?e["import"]:e.save,iconClass:"omit_from_bill-bill_item"==this.type?"icon-16-container icon-16-import":"icon-16-container icon-16-save",onClick:function(){"update_total_unit-type_reference"==a.type?c.saveTotalUnit():"omit_from_bill-bill_item"==a.type&&c.omitBillItems(a.typeUnit,a.isLastItem)}})));
this.addChild(b);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:c,region:"center"}));if(b=dijit.byId("SP_variationOrderBillGrid-"+this.variationOrderItem.id+"-stackContainer")){var d=document.createElement("div"),d=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,45),id:this.pageId,content:this,grid:c,executeScripts:!0},d);b.addChild(d);b.selectChild(this.pageId)}}});return m("buildspace.apps.PostContractSubPackage.VariationOrder.BillDialog",
dijit.Dialog,{style:"padding:0;margin:0;",title:e.updateTotalUnit,variationOrder:null,variationOrderItem:null,variationOrderItemGrid:null,isLastItem:!1,type:null,locked:!1,buildRendering:function(){this.title="update_total_unit"==this.type?e.updateTotalUnit:e.omitFromBills;var a=this,c,b,d,f;f=new k;var g=function(a){};"update_total_unit"==this.type&&0<this.variationOrderItem.bill_item_id[0]?(d=dojo.data.ItemFileWriteStore({url:"variationOrder/getSpVariationOrderItemUnitList/vid/"+this.variationOrderItem.id,
clearOnClose:!0}),b=this.type+"-type_reference",c="variationOrder/renameUnit",f=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:f.rowCountCellFormatter},{name:e.description,field:"description",width:"auto",formatter:f.typeListTreeCellFormatter},{name:e.renameDescription,field:"new_name",width:"150px",styles:"text-align:center;",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:f.typeListLevelFormatter}]):(d=dojo.data.ItemFileWriteStore({url:"variationOrder/getSpBillList/vid/"+
this.variationOrderItem.id+"/void/"+this.variationOrder.id,clearOnClose:!0}),b=this.type,f=[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:f.rowCountCellFormatter},{name:e.title,field:"title",width:"auto"}],g=function(b){b=this.getItem(b.rowIndex);0<b.id&&a.createTypeReferenceGrid(b)});c=new l({type:b,variationOrderItem:this.variationOrderItem,variationOrderItemGrid:this.variationOrderItemGrid,isLastItem:this.isLastItem,dialogWidget:this,locked:this.locked,gridOpts:{store:d,
structure:f,updateUrl:c,onRowDblClick:g}});c=this.makeGridContainer(c,e.bills);c.startup();this.content=c;this.inherited(arguments)},postCreate:function(){t.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==r.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createTypeReferenceGrid:function(a){var c=this,b=new k,d=dojo.data.ItemFileWriteStore({url:"variationOrder/getSpTypeReferenceList/void/"+
this.variationOrder.id+"/vid/"+this.variationOrderItem.id+"/bid/"+a.id,clearOnClose:!0});new l({stackContainerTitle:a.title,type:this.type+"-type_reference",variationOrderItem:this.variationOrderItem,variationOrderItemGrid:this.variationOrderItemGrid,isLastItem:this.isLastItem,bill:a,dialogWidget:this,locked:this.locked,pageId:"SP_variationOrderTypeReference-"+this.variationOrderItem+"_"+a.id,gridOpts:{store:d,updateUrl:"variationOrder/renameUnit",structure:[{name:"No",field:"id",styles:"text-align:center;",
width:"30px",formatter:b.rowCountCellFormatter},{name:e.description,field:"description",width:"auto",formatter:b.typeListTreeCellFormatter},{name:e.renameDescription,field:"new_name",width:"150px",styles:"text-align:center;",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:b.typeListLevelFormatter}],onRowDblClick:function(b){"omit_from_bill"==c.type&&(b=this.getItem(b.rowIndex),0<b.level&&c.createBillElementGrid(b,a))}}})},createBillElementGrid:function(a,c){var b=this,d=new k,
f=dojo.data.ItemFileWriteStore({url:"variationOrder/getSpBillElementList/bid/"+c.id+"/tid/"+a.id+"/void/"+this.variationOrder.id,clearOnClose:!0});new l({stackContainerTitle:a.description,type:this.type+"-bill_element",variationOrderItem:this.variationOrderItem,isLastItem:this.isLastItem,bill:c,dialogWidget:this,locked:this.locked,pageId:"SP_variationOrderBillElement-"+this.variationOrderItem+"_"+c.id,gridOpts:{store:f,structure:[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:d.rowCountCellFormatter},
{name:e.description,field:"description",width:"auto"}],onRowDblClick:function(d){d=this.getItem(d.rowIndex);0<d.id&&b.createBillItemGrid(c,d,a)}}})},createBillItemGrid:function(a,c,b){var d=new k,f=dojo.data.ItemFileWriteStore({url:"variationOrder/getSpBillItemList/eid/"+c.id+"/tid/"+b.id+"/void/"+this.variationOrder.id+"/vid/"+this.variationOrderItem.id,clearOnClose:!0});new l({stackContainerTitle:c.description,type:this.type+"-bill_item",variationOrder:this.variationOrder,variationOrderItem:this.variationOrderItem,
variationOrderItemGrid:this.variationOrderItemGrid,isLastItem:this.isLastItem,bill:a,typeUnit:b,dialogWidget:this,locked:this.locked,pageId:"SP_variationOrderBillItem-"+this.variationOrderItem+"_"+a.id,gridOpts:{store:f,updateUrl:"variationOrder/renameUnit",structure:[{name:e.billReference,field:"bill_ref",styles:"text-align:center;color:red;",width:"80px",formatter:d.unEditableCellFormatter},{name:e.description,field:"description",width:"auto",formatter:d.treeCellFormatter},{name:e.type,field:"type",
width:"70px",styles:"text-align:center;",formatter:d.typeCellFormatter},{name:e.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:d.unitIdCellFormatter},{name:e.qty,field:"qty_per_unit-value",width:"90px",styles:"text-align:right;",formatter:d.billQuantityCellFormatter},{name:e.rate,field:"rate",width:"120px",styles:"text-align:right;",formatter:d.unEditableCurrencyCellFormatter}]}})},makeGridContainer:function(a,c){var b=this.variationOrderItem.id,d=dijit.byId("SP_variationOrderBillGrid-"+
b+"-stackContainer");d&&dijit.byId("SP_variationOrderBillGrid-"+b+"-stackContainer").destroyRecursive();var d=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"SP_variationOrderBillGrid-"+b+"-stackContainer"}),e=new dijit.layout.ContentPane({title:c,content:a,grid:a.grid});d.addChild(e);var e=new dijit.layout.StackController({region:"top",containerId:"SP_variationOrderBillGrid-"+b+"-stackContainer"}),e=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",
"class":"breadCrumbTrail",region:"top",content:e}),g=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:"+("omit_from_bill"==this.type?"950px":"850px")+";height:450px;border:0px;",gutters:!1});g.addChild(d);g.addChild(e);dojo.subscribe("SP_variationOrderBillGrid-"+b+"-stackContainer-selectChild","",function(a){var c=dijit.byId("SP_variationOrderBillGrid-"+b+"-stackContainer");if(c){var d=c.getChildren(),e=dojo.indexOf(d,a);if(d.length>e+1){a.grid.store.save();a.grid.store.close();var f=
h.after(a.grid,"_onFetchComplete",function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,c.removeChild(d[e]),d[e].destroyRecursive()}});return g}})});
