define("buildspace/apps/PostContractSubPackage/VariationOrder/VariationOrderClaim","dojo/_base/declare dojo/_base/lang dojo/_base/html dijit/focus dojo/_base/event dojo/keys dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(l,v,w,g,x,y,m,n,d){var p=function(b,a,c){a=this.grid.getItem(a);c.customClasses.push("disable-cell");return 0<a.id?d.version+" "+d.no+" "+b:"&nbsp;"},q=function(b,a,c){if(0<this.grid.getItem(a).id)return b?
'<span class="icon-16-container icon-16-checkmark2" style="margin:0px auto; display:block;"></span>':'<a href="#" onclick="return false;">'+d.printThisRevision+"</a>";c.customClasses.push("disable-cell");return"&nbsp;"},r=function(b,a,c){a=this.grid.getItem(a);a.can_be_edited[0]||c.customClasses.push("disable-cell");return 0<a.id?1==parseInt(b)?d.addendumProgressing:d.addendumLocked:"&nbsp;"},u=l("buildspace.apps.PostContractSubPackage.VariationOrder.VariationOrderClaimEnhancedGrid",m,{style:"border-top:none;",
rowSelector:"0px",variationOrder:null,variationOrderItemContainer:null,region:"center",constructor:function(b){var a=new n,c=[d.addendumProgressing,d.addendumLocked];this.store=new dojo.data.ItemFileWriteStore({url:"variationOrder/getSpClaimList/id/"+b.variationOrder.id,clearOnClose:!0});this.structure=[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:d.claimVersion,field:"revision",width:"auto",formatter:p},{name:d.currentPrintingRevision,field:"is_viewing",
width:"140px",styles:"text-align: center;",formatter:q},{name:d.status,field:"status",width:"120px",styles:"text-align: center;",editable:!0,cellType:"dojox.grid.cells.Select",options:c,values:[1,2],formatter:r},{name:d.lastUpdated,field:"updated_at",width:"120px",styles:"text-align: center;"}]},canSort:function(b){return!1},postCreate:function(){var b=this;b.inherited(arguments);this.on("RowClick",function(a){(a=b.getItem(a.rowIndex))&&0<a.id&&a.can_be_deleted[0]?b.disableToolbarButtons(!1):b.disableToolbarButtons(!0)});
this.on("CellClick",function(a){var c=a.cell.field;a=b.getItem(a.rowIndex);"is_viewing"==c&&a&&0<a.id&&!a.is_viewing[0]&&b.changeCurrentViewingRevision(a)})},canEdit:function(b,a){var c=this;if(void 0==b||this.getItem(a).can_be_edited[0])return this._canEdit;window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(a,b.index)},10)},doApplyCellEdit:function(b,a,c){var e=this,f=e.getItem(a),h=e.store,k=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b!==f[c][0]&&0<f.id&&
(k.show(),dojo.xhrPost({url:"variationOrder/spClaimUpdate",content:{id:f.id,attr_name:c,val:b,_csrf_token:f._csrf_token?f._csrf_token:null},handleAs:"json",load:function(b){if(b.success){for(var d in b.data)f.hasOwnProperty(d)&&d!=h._getIdentifierAttribute()&&h.setValue(f,d,b.data[d]);h.save();2==f.status?dijit.byId("variationOrderClaim-"+e.variationOrder.id+"AddRow-button")._setDisabledAttr(!1):1==f.status&&dijit.byId("variationOrderClaim-"+e.variationOrder.id+"AddRow-button")._setDisabledAttr(!0);
var t=e.getCellByField(c);window.setTimeout(function(){e.focus.setFocusIndex(a,t.index)},10);dojo.xhrGet({url:"variationOrder/getSpClaimStatus",content:{id:e.variationOrder.id},handleAs:"json"}).then(function(a){dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}).then(function(b){e.variationOrderItemContainer.createVariationOrderItemGrid(b,a,!1)})})}k.hide()},error:function(a){k.hide()}}));e.inherited(arguments)},addNewClaim:function(b){g.curNode.blur();g.curNode=null;var a=this,c=buildspace.dialog.indeterminateProgressBar({title:d.addingRow+
". "+d.pleaseWait+"..."}),e=a.store;c.show();dojo.xhrGet({url:"variationOrder/getSpClaimStatus",content:{id:a.variationOrder.id},handleAs:"json"}).then(function(f){new buildspace.dialog.confirm(d.addNewClaim,0==f.count?d.confirmAddFirstNewClaimTitleMsg:d.confirmAddNewClaimTitleMsg,80,320,function(){dojo.xhrPost({url:"variationOrder/spClaimAdd",content:{id:a.variationOrder.id,_csrf_token:b},handleAs:"json",load:function(b){b.success&&(e.fetchItemByIdentity({identity:buildspace.constants.GRID_LAST_ROW,
onItem:function(a){a&&e.deleteItem(a)}}),dojo.forEach(b.prev_claims,function(a){e.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var c in a)b.hasOwnProperty(c)&&c!=e._getIdentifierAttribute()&&e.setValue(b,c,a[c])}})}),e.newItem(b.item),e.save(),dijit.byId("variationOrderClaim-"+a.variationOrder.id+"AddRow-button")._setDisabledAttr(!0),dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}).then(function(b){dojo.xhrGet({url:"variationOrder/getSpClaimStatus",content:{id:a.variationOrder.id},
handleAs:"json",load:function(c){a.variationOrderItemContainer.createVariationOrderItemGrid(b,c,!1)}})}));a.selection.clear();a.disableToolbarButtons(!0);c.hide()},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);c.hide()}})},function(){c.hide()})})},deleteRow:function(b){var a=this,c=a.getItem(b),e=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});g.curNode.blur();g.curNode=null;e.show();var f={url:"variationOrder/spClaimDelete",content:{id:c.id,
_csrf_token:c._csrf_token},handleAs:"json",load:function(b){if(b.success){var d=a.store;d.deleteItem(c);d.save();0<b.data.prev_item&&d.fetchItemByIdentity({identity:b.data.prev_item,onItem:function(a){a&&(d.setValue(a,"is_viewing",!0),d.setValue(a,"can_be_edited",!0),d.setValue(a,"can_be_deleted",!0),d.save())}});b.data.default_last_row&&(d.newItem(b.data.default_last_row),d.save());dijit.byId("variationOrderClaim-"+a.variationOrder.id+"AddRow-button")._setDisabledAttr(!1);dojo.xhrGet({url:"variationOrder/getSpClaimStatus",
content:{id:a.variationOrder.id},handleAs:"json"}).then(function(b){dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}).then(function(c){a.variationOrderItemContainer.createVariationOrderItemGrid(c,b,!1)})})}e.hide();a.selection.clear();a.disableToolbarButtons(!0)},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);e.hide()}};new buildspace.dialog.confirm(d.deleteVariationOrderClaimDialogBoxTitle,d.deleteVariationOrderClaimDialogBoxMsg,80,320,function(){dojo.xhrPost(f)},function(){e.hide()})},
changeCurrentViewingRevision:function(b){var a=this,c=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});g.curNode.blur();g.curNode=null;c.show();dojo.xhrPost({url:"variationOrder/viewSpClaimRevision",content:{id:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(b){if(b.success){var d=a.store;dojo.forEach(b.items,function(a){d.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var c in a)b.hasOwnProperty(c)&&c!=d._getIdentifierAttribute()&&d.setValue(b,c,a[c])}})});
d.save();dojo.xhrGet({url:"variationOrder/getSpClaimStatus",content:{id:a.variationOrder.id},handleAs:"json"}).then(function(b){dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}).then(function(c){a.variationOrderItemContainer.createVariationOrderItemGrid(c,b,!1)})})}c.hide();a.selection.clear();a.disableToolbarButtons(!0)},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);c.hide()}})},disableToolbarButtons:function(b){dijit.byId("variationOrderClaim-"+this.variationOrder.id+
"DeleteRow-button")._setDisabledAttr(b)}});return l("buildspace.apps.PostContractSubPackage.VariationOrder.VariationOrderClaim",dijit.layout.BorderContainer,{style:"padding:0;margin:0;width:100%;height:100%;",gutters:!1,variationOrder:null,variationOrderItemContainer:null,claimStatus:null,postCreate:function(){this.inherited(arguments);var b=this.claimStatus._csrf_token,a=new u({variationOrder:this.variationOrder,variationOrderItemContainer:this.variationOrderItemContainer}),c=new dijit.Toolbar({region:"top",
style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({id:"variationOrderClaim-"+this.variationOrder.id+"AddRow-button",label:d.addNewClaim,iconClass:"icon-16-container icon-16-add",disabled:"true"==this.variationOrder.is_approved[0]&&this.claimStatus.can_add_new_claim?!1:!0,onClick:function(){a.addNewClaim(b)}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"variationOrderClaim-"+this.variationOrder.id+"DeleteRow-button",label:d.deleteRow,
iconClass:"icon-16-container icon-16-delete",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.getItem(a.selection.selectedIndex).can_be_deleted[0]&&a.deleteRow(a.selection.selectedIndex)}}));this.addChild(c);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))}})});
