(function(){define("buildspace/apps/SystemAdministration/GroupMaintenance/assignUserGroupGrid","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojox/layout/TableContainer dijit/layout/ContentPane dijit/form/TextBox dijit/form/Button dijit/form/Select buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!../../../nls/SystemAdministration".split(" "),function(e,l,x,g,y,z,A,m,n,B,p,h,q,r,
t,C,c){var v=e("buildspace.apps.ProjectBuilder.BillManager.UserGroupAssignmentGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",groupMaintenanceGrid:null,groupId:-1,itemIds:[],selectedUsers:null,isSuperAdmin:!1,constructor:function(a){this.itemIds=[];this.plugins={indirectSelection:{headerSelector:!0,width:"20px",style:"text-align:center;"}};return this.inherited(arguments)},canSort:function(){return!1},postCreate:function(){var a=this;a.inherited(arguments);l.after(this,"_onFetchComplete",
function(a){return function(){return a.markedCheckBoxObject(a.selectedUsers,!0)}}(this));this._connects.push(g.connect(this,"onCellClick",function(b){return""!==b.cell.name?!1:a.selectTree(b)}));return this._connects.push(g.connect(this.rowSelectCell,"toggleAllSelection",function(b){return a.toggleAllSelection(b)}))},save:function(){var a=this;var b=this.getItem(0);var d={id:a.groupId,"sf_guard_group[users_list][]":this.itemIds,"sf_guard_group[_csrf_token]":b._csrf_token[0]};var f=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+
"..."});f.show().then(function(){dojo.xhrPost({url:"systemAdministration/updateGroupUserInfo",handleAs:"json",content:d,load:function(b){f.hide();b.success&&(b=a.groupMaintenanceGrid,b.store.save(),b.store.close(),b.setStore(b.store))},error:function(a){f.hide()}})})},selectTree:function(a){var b=a.rowIndex;a=this.selection.selected[b];if((b=this.getItem(b))&&0<b.id[0])return this.pushItemIdIntoGridArray(b,a)},markedCheckBoxObject:function(a,b){var c;var f=this;var u=this.store;var k=-1;var e=[];
for(c in a)e.push(u.fetchItemByIdentity({identity:c,onItem:function(a){a&&(k=a._0,f.pushItemIdIntoGridArray(a,b),f.selection.setSelected(k,b))}}));return e},pushItemIdIntoGridArray:function(a,b){var c=dojo.indexOf(this.itemIds,a.id[0]);if(b){if(-1===c)return this.itemIds.push(a.id[0])}else if(-1!==c)return this.itemIds.splice(c,1)},toggleAllSelection:function(a){var b=this;var c=b.selection;if(a)return c.selectRange(0,b.rowCount-1),b.itemIds=[],b.store.fetch({onComplete:function(a){return dojo.forEach(a,
function(a,c){if(0<a.id[0])return b.itemIds.push(a.id[0])})}});c.deselectAll();return b.itemIds=[]},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,g.disconnect);return delete this._connects}});var w=e("buildspace.apps.ProjectBuilder.BillManager.UserGroupAssignmentGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,groupMaintenanceGrid:null,groupId:-1,groupName:null,selectedUsers:null,
isSuperAdmin:!1,postCreate:function(){var a=this;this.inherited(arguments);var b=this.grid=new v({groupMaintenanceGrid:a.groupMaintenanceGrid,groupId:a.groupId,store:a.store,structure:a.structure,selectedUsers:a.selectedUsers[0],isSuperAdmin:a.isSuperAdmin});var d=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});d.addChild(new dijit.form.Button({label:c.save,iconClass:"icon-16-container icon-16-save",onClick:function(){return b.save()}}));d.addChild(new dijit.ToolbarSeparator);
d.addChild(new dijit.form.Button({label:c.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return a.dialog.hide()}}));var f=this.createFilter();a.addChild(f);a.addChild(d);return a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))},createFilter:function(){var a=new dojox.layout.TableContainer({showLabels:!0,orientation:"horiz",region:"top",cols:5,labelWidth:"auto",style:"padding:0;margin:0;width:100%;"});a.addChild(new h({id:"assignGroupUsernameFilterTxtBox",
title:c.name,style:"width:180px;padding:3px;",selectOnClick:!0,intermediateChanges:!0}));a.addChild(new h({id:"assignGroupCompanyFilterTxtBox",title:c.company,style:"width:180px;padding:3px;",selectOnClick:!0,intermediateChanges:!0}));var b=new r({id:"assignGroupCompanyRoleFilterTxtBox",title:c.companyRole,name:"company_role",style:"width:140px;padding:2px!important;",options:[{label:c.selectAll,value:-1},{label:c.architect,value:1},{label:c.contractor,value:2},{label:c.qs_consultant,value:4},{label:c.c_and_s_engineer,
value:8},{label:c.mep_engineer,value:16},{label:c.land_surveyor,value:32},{label:c.business_unit,value:64},{label:c.gcd,value:128}]});a.addChild(b);a.addChild(new p({content:new q({label:c.search,style:"float:right;",iconClass:"icon-16-container icon-16-zoom",onClick:dojo.hitch(this,"filterUserList")})}));return a},filterUserList:function(){var a=this,b=dijit.byId("assignGroupUsernameFilterTxtBox"),d=dijit.byId("assignGroupCompanyFilterTxtBox"),f=dijit.byId("assignGroupCompanyRoleFilterTxtBox"),e=
buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});e.show().then(function(){dojo.xhrPost({url:"systemAdministration/getGroupUserLists",handleAs:"json",content:{id:a.groupId,n:b.get("value"),c:d.get("value"),cr:f.get("value")},load:function(b){e.hide();a.grid.selection.deselectAll();a.grid.itemIds=[];b=new dojo.data.ItemFileReadStore({data:b.data,clearOnClose:!0});a.grid.setStore(b)},error:function(a){return e.hide()}})})}});return e("buildspace.apps.ProjectBuilder.BillManager.UserGroupAssignmentDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",title:c.addUserToGroup,groupMaintenanceGrid:null,groupId:-1,groupName:null,data:null,isSuperAdmin:!1,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.title=c.addUserToGroup+" ("+this.groupName+")";return this.inherited(arguments)},postCreate:function(){n.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===m.ESCAPE)return dojo.stopEvent(a)},
onHide:function(){return this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:950px;height:500px;",gutters:!1});var b=dojo.data.ItemFileWriteStore({data:this.data.data});var d=new t;d=new w({dialog:this,groupMaintenanceGrid:this.groupMaintenanceGrid,selectedUsers:this.data.users,groupId:this.groupId,groupName:this.groupName,isSuperAdmin:this.isSuperAdmin,store:b,structure:[{name:"No",field:"id",width:"30px",styles:"text-align: center;",
formatter:d.rowCountCellFormatter},{name:c.name,field:"name",width:"auto"},{name:c.email,field:"email",width:"200px"},{name:c.company,field:"company",width:"160px",styles:"text-align: center;"},{name:c.companyRole,field:"company_role",width:"120px",styles:"text-align: center;"}]});a.addChild(d);return a}})})}).call(this);
