(function(){define("buildspace/apps/SystemAdministration/GroupMaintenance/grid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem dojo/request ./GroupForm ./assignUserGroupGrid buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/Formatter dojo/i18n!../../../nls/SystemAdministration buildspace/widget/grid/Filter".split(" "),
function(f,r,t,u,v,w,k,l,x,y,m,z,A,B,g,n,C,p,e,q){var h;h=f("buildspace.apps.SystemAdministration.GroupMaintenance.Grid",dojox.grid.EnhancedGrid,{style:"border-top:none;",keepSelection:!0,rowSelector:"0px",region:"center",groupMaintenanceGridContainer:null,constructor:function(){return this.rearranger=k(this,{})},canSort:function(){return!1},postCreate:function(){var a;this.inherited(arguments);a=this;this.on("RowClick",function(b){var c;c=b.cell.field;b=this.getItem(b.rowIndex);this.disableToolbarButtons(!0);
if(b&&0<b.id&&(b.is_super_admin[0]?this.disableToolbarButtons(!0):this.disableToolbarButtons(!1),"viewUserList"===c))return a.generateAssignUserGroupDialog(b)});return this.on("RowContextMenu",function(b){var c;a=this;a.selection.clear();c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b);this.disableToolbarButtons(!0);if(c&&0<c.id)return c.is_super_admin[0]?this.disableToolbarButtons(!0):this.disableToolbarButtons(!1)})},onRowDblClick:function(a){return(a=this.getItem(a.rowIndex))&&
0<a.id?this.groupMaintenanceGridContainer.editExistingGroup(a):null},generateAssignUserGroupDialog:function(a){var b,c;c=this;b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});b.show().then(function(){dojo.xhrGet({url:"systemAdministration/getGroupUserLists",content:{id:a.id},handleAs:"json",load:function(d){b.hide();return(new n({groupMaintenanceGrid:c,groupId:a.id,isSuperAdmin:a.is_super_admin[0],groupName:a.name,data:d})).show()},error:function(){return b.hide()}})})},deleteRow:function(a){var b,
c,d;d=this;b=this.getItem(a);c=buildspace.dialog.indeterminateProgressBar({title:e.deleting+". "+e.pleaseWait+"..."});return new buildspace.dialog.confirm(e.deleteGroupTitle,e.deleteGroupMsg,80,320,function(){c.show().then(function(){dojo.xhrPost({url:"systemAdministration/deleteGroupInfo",content:{id:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(a){c.hide();return a.success?d.refreshGrid():console.log(a)},error:function(){return c.hide()}})})},function(){})},refreshGrid:function(){this.store.save();
this.store.close();return this.setStore(this.store)},contextMenu:function(a){var b,c,d;d=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);b={target:a.target};c=this.getItem(a.rowIndex);d&&c&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&m.hasClass(a.rowNode,"dojoxGridRowbar"))&&(d._openMyself(b),l.stop(a))},contextMenuItems:function(a){var b;b=this;if(0<this.getItem(a.rowIndex).id)return b.rowCtxMenu.addChild(new dijit.MenuItem({label:e.addNewGroup,iconClass:"icon-16-container icon-16-add",
onClick:function(){return b.groupMaintenanceGridContainer.addNewGroup()}})),b.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e["delete"],iconClass:"icon-16-container icon-16-delete",disabled:0<a.rowIndex?!1:!0,onClick:function(){return b.deleteRow(a.rowIndex)}}))},disableToolbarButtons:function(a){var b;if(b=dijit.byId("deleteGroupFromUserMaintenance"))return b.set("disabled",a)}});return f("buildspace.apps.SystemAdministration.GroupMaintenance.Container",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",
gutters:!1,postCreate:function(){var a,b,c,d;this.inherited(arguments);(c=dijit.byId("groupMaintenance-stackContainer"))&&c.destroyRecursive();c=this.stackContainer=new dijit.layout.StackContainer({style:"width:100%;height:100%;",region:"center",id:"groupMaintenance-stackContainer"});a=new dojo.data.ItemFileWriteStore({url:"systemAdministration/getGroupLists",clearOnClose:!0,urlPreventCache:!0});b=this.groupMaintenanceGrid=new h({structure:this.getGridLayout(),store:a,groupMaintenanceGridContainer:this});
d=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});d.addChild(new dijit.form.Button({id:"addGroupIntoUserMaintenance",label:e.addNewGroup,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addNewGroup")}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({id:"deleteGroupFromUserMaintenance",label:e["delete"],iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:function(){return b.deleteRow(b.selection.selectedIndex)}}));
a=new dijit.layout.BorderContainer({region:"top",gutters:!1});a.addChild(new q({grid:this.groupMaintenanceGrid,region:"top",editableGrid:!1,filterFields:[{name:"Name"},{usersCount:"User Count"}]}));a.addChild(d);a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}));a=new dijit.layout.ContentPane({title:e.groupList,content:a});c.addChild(a);a=new dijit.layout.StackController({region:"top",containerId:"groupMaintenance-stackContainer"});a=new dijit.layout.ContentPane({style:"padding: 0px; overflow: hidden;",
baseClass:"breadCrumbTrail",region:"top",content:a});this.addChild(c);this.addChild(a);return dojo.subscribe("groupMaintenance-stackContainer-selectChild","",function(a){var b,c,d;if(c=dijit.byId("groupMaintenance-stackContainer")){b=c.getChildren();a=dojo.indexOf(b,dijit.byId(a.id));a+=1;for(d=[];b.length>a;)c.removeChild(b[a]),b[a].destroyRecursive(),d.push(a+=1);return d}})},addNewGroup:function(){var a,b,c;b=this;c={id:-1};a=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});
a.show().then(function(){dojo.xhrGet({url:"systemAdministration/getGroupInfo",content:c,handleAs:"json",load:function(c){var d;a.hide();d=new g({region:"center",data:c,groupMaintenanceGrid:b.groupMaintenanceGrid});c=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",gutters:!1,region:"center"});c.addChild(d);return b.makePane(e.addNewGroup,c)},error:function(){return a.hide()}})})},editExistingGroup:function(a){var b,c,d;c=this;d={id:a.id};b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+
"..."});b.show().then(function(){dojo.xhrGet({url:"systemAdministration/getGroupInfo",content:d,handleAs:"json",load:function(d){var f;b.hide();f=new g({region:"center",data:d,groupMaintenanceGrid:c.groupMaintenanceGrid,isSuperAdmin:a.is_super_admin[0]});d=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",gutters:!1,region:"center"});d.addChild(f);return c.makePane(e.editExistingGroup,d)},error:function(){return b.hide()}})})},makePane:function(a,b){var c,
d;d=dijit.byId("groupMaintenance-stackContainer");c=new dijit.layout.ContentPane({title:a,content:b});d.addChild(c);return d.selectChild(c)},getGridLayout:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:(new p).rowCountCellFormatter},{name:e.name,field:"name",width:"auto"},{name:e.usersCount,field:"usersCount",width:"80px",styles:"text-align: center;"},{name:e.viewUserList,field:"viewUserList",width:"80px",styles:"text-align: center;",formatter:function(a,
b){return 0<this.grid.getItem(b).id?'<a href="#" onclick="return false;">'+e.view+"</a>":"&nbsp;"}},{name:e.lastUpdatedAt,field:"updated_at",width:"120px",styles:"text-align: center;"}]}})})}).call(this);
