define("buildspace/apps/Tendering/ScheduleOfRateBill/BillGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dijit/Menu dojo/number dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem dijit/MenuSeparator buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),
function(k,n,u,v,w,x,y,z,p,q,A,B,C,D,E,F,G,H,I,J,r,f){var t=k("buildspace.apps.Tendering.ScheduleOfRateBill.BillGrid",dojox.grid.EnhancedGrid,{type:null,billId:-1,elementId:0,itemId:-1,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,rowUpdateUrl:null,deleteUrl:null,pasteUrl:null,indentUrl:null,outdentUrl:null,headerMenu:null,parentGrid:null,elementGridStore:null,editable:!1,currentGridType:"element",constructor:function(a){this.type=
a.type;this.hierarchyTypes=a.hierarchyTypes;this.hierarchyTypesForHead=a.hierarchyTypesForHead;this.unitOfMeasurements=a.unitOfMeasurements;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;this.editable=a.editable;this.currentGridType=a.currentGridType;this.formatter=new r;this.rearranger=p(this,{});this.formulatedColumn=q(this,{});this.setColumnStructure()},canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);
this.on("RowClick",function(b){a.disableToolbarButtons(!1)})},doApplyCellEdit:function(a,b,c){var d=this,e=d.getItem(b),g=d.store,l=c.replace("-value","");-1!==c.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,b));if(a!==e[c][0]){var m=buildspace.dialog.indeterminateProgressBar({title:f.savingData+". "+f.pleaseWait+"..."}),l={id:e.id,attr_name:l,val:a,bill_id:d.billId,_csrf_token:e._csrf_token?e._csrf_token:null},h=this.updateUrl;e.id==buildspace.constants.GRID_LAST_ROW&&(h=
0<b?d.getItem(b-1):!1,n.mixin(l,{prev_item_id:h?h.id:0,relation_id:e.relation_id}),h=this.addUrl);var k=function(a,b){for(var c in a)e.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(e,c,a[c]);"tree"!=d.type&&dojo.forEach(a.other_elements,function(a){b.fetchItemByIdentity({identity:a.id,onItem:function(c){for(var d in a)c.hasOwnProperty(d)&&d!=b._getIdentifierAttribute()&&b.setValue(c,d,a[d])}})});b.save()};m.show();dojo.xhrPost({url:h,content:l,handleAs:"json",load:function(a){if(a.success){0<
e.id?k(a.data,g):(g.deleteItem(e),g.save(),dojo.forEach(a.items,function(a){g.newItem(a)}),g.save(),d.disableToolbarButtons(!0));var f=d.getCellByField(c);window.setTimeout(function(){d.focus.setFocusIndex(b,f.index)},10);m.hide()}},error:function(a){m.hide()}})}d.inherited(arguments)},canEdit:function(a,b){var c=this;if("tree"==this.type&&void 0!=a){var d=this.getItem(b),e=a.field;if(!this.editable)return!1;if(0<d.id[0]){if((d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type==
buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N)&&"description"!=e&&"type"!=e&&a.editable){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}if(d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&"description"!=e&&"type"!=e&&a.editable){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}"tree"==c.type&&"type"===e&&(e=c.getItem(b+1),(d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type==
buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N)&&a.editable&&void 0!==e&&d.level[0]<e.level[0]?(a.options=c.hierarchyTypesForHead.options,a.values=c.hierarchyTypesForHead.values):(a.options=c.hierarchyTypes.options,a.values=c.hierarchyTypes.values))}else if("description"!==e&&"type"!==e)return}return this._canEdit},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},setColumnStructure:function(){var a=this.formatter,b=this.editable?
f.contractorRate:f.estimationRate;this.structure="tree"==this.type?[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0},{name:f.description,field:"description",width:"auto",formatter:a.treeCellFormatter,noresize:!0},{name:f.type,field:"type",width:"70px",styles:"text-align:center;",formatter:a.typeCellFormatter,noresize:!0},{name:f.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:a.unitIdCellFormatter,noresize:!0},{name:b+
" ("+this.currencySetting+")",field:this.editable?"contractor_rate":"estimation_rate",styles:"text-align:right;",width:"128px",editable:this.editable,cellType:"buildspace.widget.grid.cells.Textarea",formatter:this.editable?a.currencyCellFormatter:a.unEditableCurrencyCellFormatter,noresize:!0}]:[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0},{name:f.description,field:"description",width:"auto",noresize:!0}]},refreshGrid:function(){this.beginUpdate();
this.set("structure",this.structure);this.store.close();this.pluginMgr=new this._pluginMgrClass(this);this.pluginMgr.preInit();this.pluginMgr.postInit();this.pluginMgr.startup();this._refresh();this.endUpdate()},editableCellDblClick:function(a){var b;b=1<this._click.length&&has("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=this._click[1].rowIndex?this._click[0]:a;this.focus.setFocusCell(b.cell,b.rowIndex);this.onRowClick(b);this.onRowDblClick(a)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);
else this.onCellDblClick(a);else this.onRowDblClick(a)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(c,function(a,c){var b=dojo.attr(a,"rowSpan");(!b||2>b)&&dojo.attr(a,"rowSpan",2)})}},disableToolbarButtons:function(a,b){if(a&&b instanceof Array){var c=this;dojo.forEach(b,function(a){(a=dijit.byId(c.billId+
c.elementId+a+"Row-button"))&&a._setDisabledAttr(!1)})}}});return k("buildspace.apps.Tendering.ScheduleOfRateBill.BillGridBuilder",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;width:100%;height:100%;border:0px!important;",gutters:!1,stackContainerTitle:"",billId:-1,elementId:0,itemId:-1,rowSelector:null,gridOpts:{},editable:!1,type:null,postCreate:function(){this.inherited(arguments);n.mixin(this.gridOpts,{editable:this.editable,billId:this.billId,elementId:this.elementId,type:this.type,
region:"center",borderContainerWidget:this});var a=this.grid=new t(this.gridOpts);if("tree"!=this.type){var b=this.billId,c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:f.printBill,iconClass:"icon-16-container icon-16-print",onClick:function(a){window.open("scheduleOfRateBill/printBill/id/"+b,"_blank")}}));this.addChild(c)}this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));if(c=
dijit.byId("scheduleOfRateBillGrid"+this.billId+"-stackContainer")){var d=document.createElement("div");c.addChild(new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),content:this,id:this.pageId,grid:a},d));c.selectChild(this.pageId)}}})});
