define("buildspace/apps/Tendering/BillManager/AddResourceCategoryDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/currency ./buildUpGrid ./buildUpRateSummary buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/AddResourceCategoryDialog".split(" "),function(c,x,y,z,A,B,m,p,q,r,t,u,b){var v=c("buildspace.apps.Tendering.BillManager.AddResourceCategoryGrid",dojox.grid.EnhancedGrid,{billId:0,billItem:null,currencyAbbr:null,
billGridStore:null,baseContainer:null,region:"center",style:"border-top:none;",canSort:function(a){return!1},postCreate:function(){var a=this;a.inherited(arguments);this.on("RowClick",function(g){var d=a.getItem(g.rowIndex),l=a.store;if("resource_library_exists"==g.cell.field&&0<d.id){var k=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."});if(d.resource_library_exists[0])c={url:"billBuildUpRate/resourceCategoryDelete",content:{bid:a.billItem.id,rid:d.id,_csrf_token:d._csrf_token},
handleAs:"json",load:function(f){if(f.success){l.setValue(d,"resource_library_exists",!1);l.save();var g=dijit.byId("accPane-"+f.rid+"-"+a.billItem.id),c=dijit.byId("accordian_"+a.billId+"_"+a.billItem.id+"-container"),e=dijit.byId("buildUpRateSummary-"+a.billItem.id);c&&g&&(c.removeChild(g),g.destroyRecursive());e&&(f.is_last_resource?(a.baseContainer.removeChild(e),e.destroyRecursive(),c.addChild(new dijit.layout.ContentPane({title:b.emptyResourceCategoryTitle,style:"padding:0px;border:0px;",doLayout:!1,
id:"accPane-empty_resource-"+a.billItem.id,content:'<div style="text-align:center;"><p><h1>'+b.emptyResourceCategory+"</h1></p></div> "})),dojo.xhrGet({url:"billBuildUpRate/getBuildUpSummary",content:{id:a.billItem.id},handleAs:"json",load:function(a){},error:function(a){}})):e.refreshTotalCost())}k.hide()},error:function(a){k.hide()}},buildspace.dialog.confirm(b.confirmation,"<div>"+b.areYouSureDeleteResourceCategory+"</div>",60,280,function(){k.show();dojo.xhrPost(c)});else{k.show();var c={url:"billBuildUpRate/resourceCategoryAdd",
content:{bid:a.billItem.id,rid:d.id,_csrf_token:d._csrf_token},handleAs:"json",load:function(f){if(f.success){l.setValue(d,"resource_library_exists",f.resource_library_exists);l.save();var g=dijit.byId("buildUpRateSummary-"+a.billItem.id);g||(g=new t({id:"buildUpRateSummary-"+a.billItem.id,itemId:a.billItem.id,container:a.baseContainer,billGridStore:a.billGridStore,_csrf_token:d._csrf_token,currentBillLockedStatus:f.bill_locked_status,currentBillVersion:f.bill_version,currentItemVersion:a.billItem.version[0]}),
a.baseContainer.addChild(g));var c=dijit.byId("accordian_"+a.billId+"_"+a.billItem.id+"-container"),e=f.resource,n=f.uom,h=new u,m=new dojo.data.ItemFileWriteStore({url:"billBuildUpRate/getBuildUpRateItemList/bill_item_id/"+a.billItem.id+"/resource_id/"+e.id,clearOnClose:!0});f=new r({resource:e,BQItem:a.billItem,gridOpts:{itemId:a.billItem.id,addUrl:"billBuildUpRate/buildUpRateItemAdd",updateUrl:"billBuildUpRate/buildUpRateItemUpdate",deleteUrl:"billBuildUpRate/buildUpRateItemDelete",pasteUrl:"billBuildUpRate/buildUpRateItemPaste",
store:m,buildUpSummaryWidget:g,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:h.rowCountCellFormatter},{name:b.description,field:"description",width:"auto",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:h.linkedCellFormatter},{name:b.number,field:"number-value",width:"100px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:h.formulaCurrencyCellFormatter},{name:b.constant,field:"constant-value",
width:"100px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:h.formulaCurrencyCellFormatter},{name:b.qty,field:"quantity-value",width:"70px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:h.formulaNumberCellFormatter},{name:b.unit,field:"uom_id",width:"70px",styles:"text-align:center;",editable:!0,cellType:"dojox.grid.cells.Select",options:n.options,values:n.values,formatter:h.linkedUnitIdCellFormatter},
{name:b.rate,field:"rate-value",width:"120px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:h.formulaCurrencyCellFormatter},{name:b.total,field:"total",width:"120px",styles:"text-align:right;",formatter:h.linkedCurrencyCellFormatter},{name:b.wastage+" (%)",field:"wastage-value",width:"70px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:h.formulaCurrencyCellFormatter},{name:b.lineTotal,
field:"line_total",width:"120px",styles:"text-align:right;",formatter:h.linkedCurrencyCellFormatter}],currentBillLockedStatus:f.bill_locked_status,currentBillVersion:f.bill_version,currentItemVersion:a.billItem.version[0]}});e=new dijit.layout.ContentPane({title:e.name+'<span style="color:blue;float:right;">'+a.currencyAbbr+"&nbsp;"+q.format(0)+"</span>",style:"padding:0px;border:0px;",doLayout:!1,id:"accPane-"+e.id+"-"+a.billItem.id,content:f});c.addChild(e);c.selectChild(e);if(e=dijit.byId("accPane-empty_resource-"+
a.billItem.id))c.removeChild(e),e.destroyRecursive()}k.hide()},error:function(a){k.hide()}};dojo.xhrPost(c)}}})},dodblclick:function(a){this.onRowDblClick(a)}}),w=c("buildspace.apps.Tendering.BillManager.AddResourceCategoryGrid.CellFormatter",null,{rowCountCellFormatter:function(a,b,d){return 0<this.grid.getItem(b).id?parseInt(b)+1:"&nbsp;"},actionCellFormatter:function(a,g){var d=a?b.remove:b.add,c=this.grid.getItem(g),k=Math.round((new Date).getTime()/1E3);return 0<c.id?'<a href="#'+k+'" onclick="return false;">'+
d+"</a>":null}});return c("buildspace.apps.Tendering.BillManager.AddResourceCategoryDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:b.addResourceCategory,billId:null,billItem:null,currencyAbbr:null,billGridStore:null,baseContainer:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){p.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},
_onKey:function(a){a.keyCode==m.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:500px;height:250px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border:0px;"});c.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var d=new w,
l=dojo.data.ItemFileWriteStore({url:"billBuildUpRate/getResourceList/item_id/"+this.billItem.id}),d=v({billId:this.billId,billItem:this.billItem,currencyAbbr:this.currencyAbbr,billGridStore:this.billGridStore,baseContainer:this.baseContainer,store:l,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:d.rowCountCellFormatter},{name:b.name,field:"name",width:"auto"},{name:b.action,field:"resource_library_exists",width:"80px",styles:"text-align:center;",formatter:d.actionCellFormatter}]});
a.addChild(c);a.addChild(d);return a}})});
