define("buildspace/apps/Tendering/BillManager/buildUpGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojo/_base/connect dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/currency dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox dijit/popup dijit/TooltipDialog ./importResourceDialog dojo/i18n!buildspace/nls/BuildUpGrid".split(" "),
function(q,r,D,E,n,F,G,u,v,w,x,y,p,z,H,I,J,K,L,h,t,A,g){var C=q("buildspace.apps.Tendering.BillManager.BuildUp.grid",dojox.grid.EnhancedGrid,{itemId:-1,resource:null,BQItem:null,style:"border-top:none;",selectedItem:null,unitObj:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,buildUpSummaryWidget:null,currentBillLockedStatus:!1,disableEditingMode:!1,constructor:function(a){this.rearranger=u(this,{});this.formulatedColumn=v(this,{});this.currencySetting=
buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation},canSort:function(a){return!1},canEdit:function(a,b){this.closeToolTipDialogIfAvailable();return this.disableEditingMode?!1:this._canEdit},postCreate:function(){var a=this,b=null;a.inherited(arguments);this.on("RowContextMenu",function(b){a.selection.clear();var c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b);c&&!a.disableEditingMode?0<c.id?a.disableToolbarButtons(!1):
a.disableToolbarButtons(!0,["Import"]):a.disableEditingMode&&a.disableToolbarButtons(!0)},!0);this.on("RowClick",function(b){(b=a.getItem(b.rowIndex))&&!a.disableEditingMode?0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Import"]):a.disableEditingMode&&a.disableToolbarButtons(!0)});this._connects.push(n.connect(this,"onCellMouseOver",function(a){var c=a.cell.field,d=a.rowIndex,f=this.getItem(d),c=c.replace("-value","");"undefined"!==typeof f[c+"-has_formula"]&&f[c+"-has_formula"][0]&&
(f=f[c+"-value"][0],f=this.formulatedColumn.convertItemIdToRowIndex(f,d),null===b&&(b=new t({content:f,onMouseLeave:function(){h.close(b)}}),h.open({popup:b,around:a.cellNode})))}));this._connects.push(n.connect(this,"onCellMouseOut",function(){null!==b&&(h.close(b),b=null)}));this._connects.push(n.connect(this,"onStartEdit",function(){null!==b&&(h.close(b),b=null)}))},doApplyCellEdit:function(a,b,c){var e=this,d=e.getItem(b),f=e.store;if(a!==d[c][0]){var l=c.replace("-value","");-1!==c.indexOf("-value")&&
(a=this.formulatedColumn.convertRowIndexToItemId(a,b));var k={id:d.id,attr_name:l,val:a,_csrf_token:d._csrf_token?d._csrf_token:null},m=this.updateUrl;d.id==buildspace.constants.GRID_LAST_ROW&&(m=0<b?e.getItem(b-1):!1,r.mixin(k,{prev_item_id:m?m.id:0,relation_id:d.relation_id,resource_id:e.resource.id}),m=this.addUrl);var B=function(a,b){for(var c in a)d.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(d,c,a[c]),dojo.forEach(a.affected_nodes,function(a){b.fetchItemByIdentity({identity:a.id,
onItem:function(c){for(var e in a)d.hasOwnProperty(e)&&e!=b._getIdentifierAttribute()&&b.setValue(c,e,a[e])}})});b.save()},h=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."});h.show();dojo.xhrPost({url:m,content:k,handleAs:"json",load:function(a){if(a.success){0<d.id?B(a.data,f):(f.deleteItem(d),f.save(),dojo.forEach(a.items,function(a){f.newItem(a)}),f.save(),e.disableToolbarButtons(!0));"description"!=l&&e.updateTotalBuildUp(a.total_build_up);var k=e.getCellByField(c);window.setTimeout(function(){e.focus.setFocusIndex(b,
k.index)},10)}h.hide()},error:function(a){console.log(a);h.hide()}})}e.inherited(arguments)},dodblclick:function(a){},onCellFocus:function(a,b){var c=this,e=c.getItem(b);"description"!==a.field||0>e.id[0]||!e.linked[0]?c.closeToolTipDialogIfAvailable():dojo.xhrGet({url:"resourceLibrary/getBuildUpRatesToolTipInformation",content:{id:e.id,type:"bill"},handleAs:"json",load:function(d){if(d.success){c.closeToolTipDialogIfAvailable();var e=!1,l='<h1 style="font-size: 12px; text-shadow: 1px 1px 1px #000;background-color: rgba(35, 35, 35, .85); color: #fff; padding: 4px 10px;">'+
d.items[0].description+"</h1>";1<Object.keys(d.items).length&&(e=!0,l+='<table style="width: 100%; border-collapse: collapse;">');dojo.forEach(d.items,function(a,b){0!==b&&(l+='<tr><td style="border: 1px dotted #D5CDB5; font-weight: bold; font-size: 11px; padding-left:'+16*a.level+'px;">'+a.description+"</td></td>")});e&&(l+="</table>");c.myTooltipDialog=new t({id:"buildUpRatesTooltipDialog-"+c.itemId[0],style:"width: 300px;",content:l});h.open({popup:c.myTooltipDialog,around:a.view.rowNodes[b],orient:["below"]})}},
error:function(a){console.log(a)}})},onRowMouseOut:function(){this.closeToolTipDialogIfAvailable()},addRow:function(a){p.curNode.blur();p.curNode=null;var b=this,c=buildspace.dialog.indeterminateProgressBar({title:g.addingRow+". "+g.pleaseWait+"..."}),e=b.store,d=b.getItem(a);if(0<d.id)d={before_id:d.id,_csrf_token:d._csrf_token};else var f=0<a?b.getItem(a-1).id:0,d={id:d.id,prev_item_id:f,relation_id:d.relation_id,resource_id:b.resource.id,_csrf_token:d._csrf_token};c.show();dojo.xhrPost({url:this.addUrl,
content:d,handleAs:"json",load:function(d){d.success&&dojo.forEach(d.items,function(c){0<c.id&&(c=e.newItem(c),e.save(),c=b.getItemIndex(c),b.rearranger.moveRows([c],a),b.selection.clear())});window.setTimeout(function(){b.selection.setSelected(a,!0);b.focus.setFocusIndex(a,1)},30);c.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);c.hide()}})},deleteRow:function(a){var b=this,c=b.getItem(a),e=buildspace.dialog.indeterminateProgressBar({title:g.deleting+". "+g.pleaseWait+
"..."});p.curNode.blur();p.curNode=null;e.show();var d={url:this.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(d){if(d.success){var f=d.affected_nodes,k=b.store;k.deleteItem(c);k.save();for(var g=0,h=f.length;g<h;++g)k.fetchItemByIdentity({identity:f[g].id,onItem:function(a){for(var b in f[g])a.hasOwnProperty(b)&&b!=k._getIdentifierAttribute()&&k.setValue(a,b,f[g][b]);k.save()}});b.updateTotalBuildUp(d.total_build_up)}e.hide();b.selection.clear();window.setTimeout(function(){b.focus.setFocusIndex(a,
0)},10);b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;e.hide()}};new buildspace.dialog.confirm(g.deleteBuildUpRateItemTitle,g.deleteBuildUpRateItemMsg,80,320,function(){dojo.xhrPost(d)},function(){e.hide()})},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp=
"copy"},pasteItem:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."}),e=b.store,d=b.selection.getFirstSelected(),f=d.id==buildspace.constants.GRID_LAST_ROW&&0<a?b.getItem(a-1).id:0;c.show();dojo.xhrPost({url:this.pasteUrl,content:{type:b.pasteOp,target_id:d.id,id:b.selectedItem.id,prev_item_id:f,_csrf_token:b.selectedItem._csrf_token},handleAs:"json",load:function(d){var f=[];if(d.success)switch(b.pasteOp){case "cut":e.fetchItemByIdentity({identity:d.data.id,
onItem:function(c){c=b.getItemIndex(c);f.push(c);0<f.length&&b.rearranger.moveRows(f,a);b.selectAfterPaste(c>a?a:a-1,!0)}});break;case "copy":var g=e.newItem(d.data);e.save();g=b.getItemIndex(g);f.push(g);0<f.length&&(b.rearranger.moveRows(f,a),b.selectAfterPaste(a,!1));b.updateTotalBuildUp(d.total_build_up)}b.disableToolbarButtons(!1);b.pasteOp=null;f.length=0;c.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;c.hide()}})},selectAfterPaste:function(a,
b){this.selection.clear();this.selectedItem=null;this.selection.setSelected(a,!0);b&&this.scrollToRow(0<a-3?a-3:a)},contextMenu:function(a){if(this.disableEditingMode)return!1;var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==x.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},e=this.getItem(a.rowIndex);b&&e&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&z.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),w.stop(a))},contextMenuItems:function(a){var b=
this.getItem(a.rowIndex);0<b.id&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItems")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:g.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(this,"copyItems")})));this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:g.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(this,"pasteItem",a.rowIndex),disabled:this.selectedItem?
!1:!0}));this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow",a.rowIndex,"lala")}));0<b.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow",a.rowIndex)}))},disableToolbarButtons:function(a,b){var c=dijit.byId("builUpGrid-"+this.resource.id+"_"+this.BQItem.id+"AddRow-button"),e=dijit.byId("builUpGrid-"+this.resource.id+"_"+
this.BQItem.id+"DeleteRow-button");c._setDisabledAttr(a);e._setDisabledAttr(a);if(a&&b instanceof Array){var d=this;dojo.forEach(b,function(a){dijit.byId("builUpGrid-"+d.resource.id+"_"+d.BQItem.id+a+"Row-button")._setDisabledAttr(!1)})}},updateTotalBuildUp:function(a){dijit.byId("accPane-"+this.resource.id+"-"+this.BQItem.id).set("title",this.resource.name+'<span style="color:blue;float:right;">'+this.currencySetting+"&nbsp;"+y.format(a)+"</span>");this.buildUpSummaryWidget.refreshTotalCost()},closeToolTipDialogIfAvailable:function(){var a=
dijit.byId("buildUpRatesTooltipDialog-"+this.itemId[0]);void 0!==this.myTooltipDialog&&void 0!==a&&(h.close(),a.destroy())},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,n.disconnect);delete this._connects}});return q("buildspace.apps.Tendering.BillManager.BuildUpGrid",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,resource:null,BQItem:null,gridOpts:{},postCreate:function(){var a=this;a.inherited(arguments);r.mixin(a.gridOpts,
{resource:a.resource,BQItem:a.BQItem,region:"center"});var b=this.grid=new C(a.gridOpts),c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({id:"builUpGrid-"+a.resource.id+"_"+a.BQItem.id+"AddRow-button",label:g.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.addRow(b.selection.selectedIndex)}}));c.addChild(new dijit.ToolbarSeparator);
c.addChild(new dijit.form.Button({id:"builUpGrid-"+a.resource.id+"_"+a.BQItem.id+"DeleteRow-button",label:g.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.deleteRow(b.selection.selectedIndex)}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"builUpGrid-"+a.resource.id+"_"+a.BQItem.id+"ImportRow-button",label:g.importFromResourceLibrary,iconClass:"icon-16-container icon-16-import",
disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(){A({BQItem:a.BQItem,resource:a.resource,buildUpGridStore:b.store}).show()}}));a.addChild(c);a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))}})});
