define("dojo/_base/declare dojo/_base/lang dojox/grid/enhanced/plugins/Rearrange dojo/_base/event dojo/keys dijit/focus buildspace/widget/grid/cells/Textarea buildspace/widget/grid/Filter buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ClaimCertificateTaxMaintenance".split(" "),function(r,u,v,w,x,q,C,y,z,e){var B=r("buildspace.apps.ClaimCertificateTaxMaintenance.ClaimCertificateTaxMaintenanceGrid",dojox.grid.EnhancedGrid,{region:"center",style:"border-top:none;",selectedItem:null,
keepSelection:!0,rowSelector:"0px",constructor:function(a){this.rearranger=v(this,{})},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments);this.on("RowContextMenu",function(a){this.selection.clear();var b=this.getItem(a.rowIndex);this.selection.setSelected(a.rowIndex,!0);this.contextMenu(a);b&&!isNaN(parseInt(b.id[0]))?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0,["Add"])},!0);this.on("RowClick",function(a){(a=this.getItem(a.rowIndex))&&!isNaN(parseInt(a.id[0]))?
this.disableToolbarButtons(!1):this.disableToolbarButtons(!0,["Add"])})},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},doApplyCellEdit:function(a,b,d){var f=this,c=this.getItem(b),g=this.store;if(a!==c[d][0]){var k=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),l={id:c.id,attr_name:d,val:a,_csrf_token:c._csrf_token?c._csrf_token:null},h="systemMaintenance/claimCertificateTaxUpdate";if(c&&
isNaN(parseInt(c.id[0]))){var t=0<b?this.getItem(b-1):!1;u.mixin(l,{prev_item_id:t?t.id:0});h="systemMaintenance/claimCertificateTaxAdd"}var A=function(m,p){for(var n in m)c.hasOwnProperty(n)&&n!=p._getIdentifierAttribute()&&p.setValue(c,n,m[n]);p.save()};k.show().then(function(){dojo.xhrPost({url:h,content:l,handleAs:"json",load:function(m){if(m.success){isNaN(parseInt(c.id[0]))?(g.deleteItem(c),g.save(),dojo.forEach(m.items,function(n){g.newItem(n)}),g.save()):A(m.data,g);var p=f.getCellByField(d);
window.setTimeout(function(){f.focus.setFocusIndex(b,p.index)},10);k.hide()}},error:function(m){k.hide()}})})}this.inherited(arguments)},dodblclick:function(a){this.onRowDblClick(a)},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var d={target:a.target,coords:a.keyCode!==x.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},f=this.getItem(a.rowIndex);b&&f&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&html.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(d),
w.stop(a))},contextMenuItems:function(a){(a=this.getItem(a.rowIndex))&&!isNaN(parseInt(a.id[0]))&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow")})),this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow")})))},addRow:function(){q.curNode.blur();q.curNode=null;if(-1<this.selection.selectedIndex){var a=this.selection.selectedIndex,
b=this,d=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."}),f=this.store,c=this.getItem(a);if(isNaN(parseInt(c.id[0]))){var g=0<a?this.getItem(a-1).id:0;var k={id:c.id,prev_item_id:g,_csrf_token:c._csrf_token}}else g=0<a?this.getItem(a-1).id:0,k={prev_item_id:g,before_id:c.id,_csrf_token:c._csrf_token};d.show().then(function(){dojo.xhrPost({url:"systemMaintenance/claimCertificateTaxAdd",content:k,handleAs:"json",load:function(l){l.success&&dojo.forEach(l.items,
function(h){0<h.id&&(h=f.newItem(h),f.save(),h=b.getItemIndex(h),b.rearranger.moveRows([h],a),b.selection.clear())});window.setTimeout(function(){b.selection.setSelected(a,!0);b.focus.setFocusIndex(a,1)},30);d.hide()},error:function(l){b.selection.clear();b.disableToolbarButtons(!0);d.hide()}})})}},deleteRow:function(){var a=this.selection.selectedIndex,b=this.getItem(a);q.curNode.blur();q.curNode=null;if(-1<this.selection.selectedIndex&&b&&!isNaN(parseInt(b.id[0]))){var d=this,f=buildspace.dialog.indeterminateProgressBar({title:e.deleting+
". "+e.pleaseWait+"..."});buildspace.dialog.confirm(e.deleteCertificateConfirmation,"<div>"+e.doYouReallywantToDeleteCertificate+" ?</div>",90,320,function(){f.show().then(function(){dojo.xhrPost({url:"systemMaintenance/claimCertificateTaxDelete",content:{id:b.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(c){if(c.success){c=c.items;for(var g=d.store,k=0,l=c.length;k<l;++k)g.fetchItemByIdentity({identity:c[k].id,onItem:function(h){g.deleteItem(h);g.save()}});c.length=0;d.selection.clear();
window.setTimeout(function(){d.focus.setFocusIndex(a,0)},10);d.disableToolbarButtons(!0)}else buildspace.dialog.alert(e.cannotDeleteCertificateTitle,e.cannotDeleteCertificateMsg,90,320);f.hide();d.selectedItem=null;d.pasteOp=null},error:function(c){d.selection.clear();d.disableToolbarButtons(!0);d.selectedItem=null;d.pasteOp=null;f.hide()}})})})}},disableToolbarButtons:function(a,b){var d=dijit.byId("AddClaimCertTaxRow-button"),f=dijit.byId("DeleteClaimCertTaxRow-button");d._setDisabledAttr(a);f._setDisabledAttr(a);
a&&b instanceof Array&&dojo.forEach(b,function(c){(c=dijit.byId(c+"ClaimCertTaxRow-button"))&&c._setDisabledAttr(!1)})}});return r("buildspace.apps.ClaimCertificateTaxMaintenance.ClaimCertificateTaxMaintenanceFormContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,postCreate:function(){this.inherited(arguments);var a=new z;a=this.ClaimCertificateMaintenanceGrid=new B({store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"systemMaintenance/getClaimCertificateTaxes"}),
structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:e.description,field:"description",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0,width:"auto"},{name:e.tax,field:"tax",width:"150px",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",noresize:!0},{name:e.updatedAt,field:"updated_at",styles:"text-align:center;",width:"120px"}]});var b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});
b.addChild(new dijit.form.Button({id:"AddClaimCertTaxRow-button",label:e.addRow,iconClass:"icon-16-container icon-16-add",disabled:!0,onClick:dojo.hitch(a,"addRow")}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"DeleteClaimCertTaxRow-button",label:e.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:!0,onClick:dojo.hitch(a,"deleteRow")}));var d=new y({grid:a,region:"top",filterFields:[{name:e.name}]});this.addChild(d);this.addChild(b);this.addChild(a)}})});
