define("buildspace/apps/PostContract/ClaimCertificateNoteContainer","dojo/_base/declare dojo/_base/lang dojo/aspect dojo/keys dojo/dom-style dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dijit/Editor dijit/_editor/plugins/LinkDialog dojox/editor/plugins/AutoUrlLink dojo/text!./templates/claimCertificateNoteForm.html dojo/i18n!buildspace/nls/PostContract".split(" "),function(e,y,z,h,k,l,
m,n,p,q,A,B,C,D,r,b){var v=e("buildspace.apps.PostContract.ClaimCertificateNoteEditorForm",[l,m,n,p],{templateString:r,style:"outline:none;",claimCertificate:null,claimCertificateContainer:null,nls:b,region:"center",postCreate:function(){this.inherited(arguments);this.htmlEditorNode.set("value",String(this.claimCertificate.note))},submit:function(a){var c=buildspace.dialog.indeterminateProgressBar({title:b.savingData+"..."}),d=this,g=this.claimCertificateContainer.grid,u={url:"claimCertificate/noteUpdate",
content:{note:this.htmlEditorNode.value,id:this.claimCertificate.id,_csrf_token:this.claimCertificate._csrf_token},handleAs:"json",load:function(f){f.success&&g.store.fetchItemByIdentity({identity:String(d.claimCertificate.id),onItem:function(t){g.store.setValue(t,"note",f.note);g.store.save();d.claimCertificate.note=f.note}});c.hide();a.hide()},error:function(f){c.hide();a.hide()}};c.show().then(function(){dojo.xhrPost(u)})}}),w=e("buildspace.apps.PostContract.ClaimCertificateNoteEditorDialog",dijit.Dialog,
{style:"padding:0px;margin:0px;",title:b.notes,claimCertificate:null,claimCertificateContainer:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){k.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==h.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:850px;height:350px;",
gutters:!1}),c=new v({claimCertificate:this.claimCertificate,claimCertificateContainer:this.claimCertificateContainer}),d=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});d.addChild(new dijit.form.Button({label:b.save,iconClass:"icon-16-container icon-16-save",style:"outline:none!important;",onClick:dojo.hitch(c,"submit",this)}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:b.close,iconClass:"icon-16-container icon-16-close",
style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));a.addChild(d);a.addChild(c);return a}}),x=e("buildspace.apps.PostContract.ClaimCertificateGrid",q,{style:"border:none;",region:"center",rowSelector:"0px",escapeHTMLInData:!1,selectable:!0,claimCertificate:null,claimCertificateNoteContainer:null,constructor:function(a){this.structure={noscroll:!1,cells:[[{name:b.claimNumber,field:"version",width:"80px",styles:"text-align:center;"},{name:b.status,field:"status_txt",width:"150px",styles:"text-align:center;"},
{name:b.notes,field:"note",width:"auto",styles:"text-align:left;"},{name:b.updatedBy,field:"creator",width:"200px",styles:"text-align:center;"}]]};this.inherited(arguments)},canSort:function(a){return!1},reload:function(){this.store.close();this._refresh()}});return e("buildspace.apps.PostContract.ClaimCertificateNoteContainer",dijit.layout.BorderContainer,{style:"padding:0;width:100%;margin:0;border:none;height:100%;",title:b.notes,gutters:!1,claimCertificate:!1,grid:null,postCreate:function(){this.inherited(arguments);
var a=this.claimCertificate;if(parseInt(String(a.status))==buildspace.constants.CLAIM_CERTIFICATE_STATUS_IN_PROGRESS){var c=new dijit.Toolbar({region:"top",style:"outline:none!important;border-bottom:none;padding:2px;width:100%;"});c.addChild(new dijit.form.Button({id:String(a.id)+"-ClaimCertificateNote-edit-btn",label:b.editNote,iconClass:"icon-16-container icon-16-edit",onClick:dojo.hitch(this,"editNote")}));this.addChild(c)}this.grid=new x({claimCertificateContainer:this,claimCertificate:a,store:new dojo.data.ItemFileWriteStore({url:"claimCertificate/getNotes/id/"+
String(a.id),handleAs:"json",clearOnClose:!0,urlPreventCache:!0})});this.addChild(this.grid)},editNote:function(){(new w({claimCertificate:this.claimCertificate,claimCertificateContainer:this})).show()}})});
