define("buildspace/apps/PostContract/StandardBillManager","dojo/_base/declare dojo/dom-style dojo/_base/connect dijit/TooltipDialog dijit/popup buildspace/widget/grid/plugins/FormulatedColumn dojo/when dojo/number dojo/currency dijit/layout/ContentPane dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter buildspace/apps/ProjectBuilder/BillManager/ScheduleOfQuantityGrid ./BillManager/buildUpQuantitySummary dojo/aspect dojo/i18n!buildspace/nls/PostContract ./BillManager/StandardBillGrid ./BillManager/lumpSumPercentDialog buildspace/widget/grid/cells/Textarea".split(" "),
function(x,N,t,D,u,E,O,y,P,Q,F,z,G,H,I,f,A,J,R){var L=x("buildspace.apps.PostContract.TypeGrid",F,{rootProject:null,style:"border:none;",region:"center",pageId:null,billId:null,updateUrl:null,keepSelection:!0,rowSelector:"0px",constructor:function(a){var b=new z;this.structure={noscroll:!1,cells:[[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:K.rowCountCellFormatter,rowSpan:2},{name:f.description,field:"description",width:"auto",formatter:b.typeListTreeCellFormatter,
rowSpan:2},{name:f.renameDescription,field:"new_name",width:"180px",editable:"true",cellType:"buildspace.widget.grid.cells.Textarea",rowSpan:2,styles:"text-align:center;",formatter:b.typeListLevelFormatter},{name:f.omittedItems,field:"vo_omitted_items",width:"45px",styles:"text-align: center;",editable:!1,noresize:!0,showInCtxMenu:!0,rowSpan:2,formatter:b.unEditableCellFormatter},{name:f.amount,field:"total_per_unit",width:"120px",styles:"text-align: right;color:blue;",formatter:b.unEditableCurrencyCellFormatter,
rowSpan:2},{name:f.percent,field:"up_to_date_percentage",width:"120px",headerClasses:"typeHeader1",formatter:b.unEditablePercentageCellFormatter,styles:"text-align: right;"},{name:f.amount,field:"up_to_date_amount",width:"120px",headerClasses:"typeHeader1",formatter:b.unEditableCurrencyCellFormatter,styles:"text-align: right;"},{name:f.percent,field:"imported_up_to_date_percentage",width:"120px",styles:"text-align: right;",formatter:b.unEditablePercentageCellFormatter,showInCtxMenu:!0,ctxMenuLabel:f.importedUpToDateClaim,
hideColumnGroup:[{field:"imported_up_to_date_amount"},{name:f.importedUpToDateClaim}]},{name:f.amount,field:"imported_up_to_date_amount",width:"120px",styles:"text-align: right;",formatter:b.unEditableCurrencyCellFormatter}],[{name:f.upToDateClaim,styles:"text-align:center;",headerClasses:"staticHeader typeHeader1",colSpan:2},{name:f.importedUpToDateClaim,styles:"text-align:center;",headerClasses:"staticHeader",colSpan:2}]]};buildspace.grid.headerCtxMenu.createMenu(this);this.inherited(arguments)},
canSort:function(a){return!1},dodblclick:function(a){this.onRowDblClick(a)},canEdit:function(a,b){var d=this;if(void 0!=a&&0===this.getItem(b).level[0])window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(b,a.index)},10);else return this._canEdit},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],d=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);
dojo.forEach(d,function(e,c){c=dojo.attr(e,"rowSpan");(!c||2>c)&&dojo.attr(e,"rowSpan",2)})}},doApplyCellEdit:function(a,b,d){var e=this,c=this.getItem(b),l=this.store;if(void 0!=c[d][0]||a!==c[d][0]){var g=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."}),h={id:c.id,project_id:e.rootProject.id,type_id:c.relation_id,counter:c.count,attr_name:d,val:a},n=this.updateUrl,m=function(k,q){for(var p in k)c.hasOwnProperty(p)&&p!=q._getIdentifierAttribute()&&q.setValue(c,p,k[p]);q.save()};
g.show().then(function(){dojo.xhrPost({url:n,content:h,handleAs:"json",load:function(k){if(k.success){m(k.item,l);var q=e.getCellByField(d);window.setTimeout(function(){e.focus.setFocusIndex(b,q.index)},10);g.hide()}},error:function(k){g.hide();console.log(k)}})})}this.inherited(arguments)},reload:function(){this.store.close();this._refresh()}}),K={rowCountCellFormatter:function(a,b,d){b=this.grid.getItem(b);void 0!=b.type&&1>b.type&&d.customClasses.push("invalidTypeItemCell");return 0<a?a:""}},M=
x("buildspace.apps.PostContract.BillManager.BuildUpQtyGrid",dojox.grid.EnhancedGrid,{title:f.manualQtyItems,region:"center",store:null,structure:null,postCreate:function(){var a=null;this.formulatedColumn=E(this,{});this.inherited(arguments);this._connects.push(t.connect(this,"onCellMouseOver",function(b){var d=b.cell.field,e=b.rowIndex,c=this.getItem(e);d=d.replace("-value","");"undefined"!==typeof c[d+"-has_formula"]&&c[d+"-has_formula"][0]&&(c=c[d+"-value"][0],c=this.formulatedColumn.convertItemIdToRowIndex(c,
e),null===a&&(a=new D({content:c,onMouseLeave:function(){u.close(a)}}),u.open({popup:a,around:b.cellNode})))}));this._connects.push(t.connect(this,"onCellMouseOut",function(){null!==a&&(u.close(a),a=null)}));this._connects.push(t.connect(this,"onStartEdit",function(){null!==a&&(u.close(a),a=null)}))},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,t.disconnect);delete this._connects}});return x("buildspace.apps.PostContract.StandardBillManager",dijit.layout.BorderContainer,
{style:"padding:0;margin:0px;border:none;width:100%;height:100%;",gutters:!1,billId:null,rootProject:null,locked:!1,postCreate:function(){this.inherited(arguments);var a=this;this.createTypeGrid();dojo.subscribe("postContractStandardBill"+a.billId+"-stackContainer-selectChild","",function(b){var d=dijit.byId("postContractStandardBill"+a.billId+"-stackContainer");if(d){var e=d.getChildren(),c=dojo.indexOf(e,dijit.byId(b));c+=1;if(e.length>c){for(;e.length>c;)d.removeChild(e[c]),e[c].destroyDescendants(),
e[c].destroyRecursive(),c+=1;if(b.grid){var l=b.grid.selection.selectedIndex;b.grid.store.save();b.grid.store.close();var g=I.after(b.grid,"_onFetchComplete",function(){g.remove();-1<l&&(this.scrollToRow(l),this.selection.setSelected(l,!0))});b.grid.sort()}}}})},createTypeGrid:function(){var a=this,b=dijit.byId("postContractStandardBill"+this.billId+"-stackContainer");b&&dijit.byId("postContractStandardBill"+this.billId+"-stackContainer").destroyRecursive();b=this.stackContainer=new dijit.layout.StackContainer({style:"border:0px;width:100%;height:100%;",
region:"center",id:"postContractStandardBill"+this.billId+"-stackContainer"});var d=this;dojo.xhrGet({url:"postContract/getBillInfo",handleAs:"json",content:{id:this.billId}}).then(function(e){var c=dojo.data.ItemFileWriteStore({url:"postContractStandardBillClaim/getTypeList/id/"+a.billId,clearOnClose:!0}),l=new L({billId:d.billId,rootProject:d.rootProject,pageId:"type-page-"+d.billId,id:"type-page-container-"+d.billId,updateUrl:"postContractStandardBillClaim/updateTypeList",store:c,onRowDblClick:function(g){g=
this.getItem(g.rowIndex);0<g.level[0]&&d.createElementGrid(g,e,l)}});c=new dijit.layout.StackController({region:"top",containerId:"postContractStandardBill"+d.billId+"-stackContainer"});b.addChild(new dijit.layout.ContentPane({title:f.type+" / "+f.unit,content:l,grid:l}));c=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;",baseClass:"breadCrumbTrail",region:"top",id:"billGrid"+d.billId+"-controllerPane",content:c});d.addChild(b);d.addChild(c)})},createElementGrid:function(a,b,d){var e=
this;dojo.xhrGet({url:"postContractStandardBillClaim/getTypeItem",handleAs:"json",content:{type_id:a.relation_id,project_id:e.rootProject.id,counter:a.count}}).then(function(c){var l=new A({stackContainerTitle:0<c.new_name.length?c.relation_name+" :: "+c.new_name:c.relation_name+" :: "+c.description,billId:e.billId,disableEditing:!b.editable,rootProject:e.rootProject,pageId:"element-page-"+e.billId,id:"element-page-container-"+e.billId,typeItem:c,locked:e.locked,gridOpts:{store:dojo.data.ItemFileWriteStore({url:"postContractStandardBillClaim/getBillElementList/id/"+
e.billId+"/project_id/"+e.rootProject.id+"/type_ref_id/"+c.id,clearOnClose:!0,urlPreventCache:!0}),updateUrl:"postContractStandardBillClaim/standardBillClaimElementUpdate",typeColumns:b.column_settings,bqCSRFToken:b.bqCSRFToken,claimRevision:b.claim_project_revision_status,selectedClaimRevision:b.current_selected_claim_project_revision_status,currentGridType:"element",onRowDblClick:function(g){g=this.getItem(g.rowIndex);0<g.id[0]&&null!==g.description[0]&&""!==g.description[0]&&e.createItemGrid(g,
c,b,l)}}})})},createItemGrid:function(a,b,d,e){var c=this.billId,l=this,g=new dojo.data.ItemFileWriteStore({url:"postContractStandardBillClaim/getItemList/id/"+a.id+"/bill_id/"+c+"/type_ref_id/"+a.claim_type_ref_id+"/project_id/"+l.rootProject.id,clearOnClose:!0});new A({stackContainerTitle:a.description,billId:c,disableEditing:!d.editable,rootProject:l.rootProject,id:"item-page-container-"+c,elementId:a.id,pageId:"item-page-"+c,type:"tree",typeItem:b,gridOpts:{store:g,escapeHTMLInData:!1,elementGridStore:e,
claimRevision:d.claim_project_revision_status,selectedClaimRevision:d.current_selected_claim_project_revision_status,updateUrl:"postContractStandardBillClaim/standardBillClaimUpdate",currentGridType:"item",onRowDblClick:function(h){var n=h.cell.field,m=this.getItem(h.rowIndex),k=this.store;if("qty_per_unit"==n&&m[n+"-has_build_up"][0]){var q=b.relation_id,p=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});p.show().then(function(){dojo.xhrPost({url:"billBuildUpQuantity/getDimensionColumnStructure",
content:{uom_id:m.uom_id[0]},handleAs:"json"}).then(function(v){l.createBuildUpQuantityContainer(m,v,q,k,e);p.hide()})})}},editableCellDblClick:function(h){var n=h.cell.field;h=this.getItem(h.rowIndex);var m=this.store;"rate"==n&&h&&!isNaN(parseInt(h.id[0]))&&h.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&(n=y.parse(h.up_to_date_percentage)||y.parse(h.current_percentage)||y.parse(h.prev_percentage)?!0:!1,(new J({itemObj:h,projectId:l.rootProject.id,billGridStore:m,
elementGridStore:e,disableEditingMode:this.disableEditing?!0:n})).show())}}})},createBuildUpQuantityContainer:function(a,b,d,e,c){var l=this,g,h=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:100%;height:100%;border:none;outline:none;",gutters:!1}),n=new dijit.layout.TabContainer({nested:!0,style:"padding:0;border:none;margin:0;width:100%;height:100%;",region:"center"}),m=buildspace.constants.QUANTITY_PER_UNIT_ORIGINAL,k=new z,q=new dojo.data.ItemFileWriteStore({url:"billBuildUpQuantity/getBuildUpQuantityItemList/bill_item_id/"+
a.id+"/bill_column_setting_id/"+d+"/type/"+m,clearOnClose:!0}),p=!1,v=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});v.show().then(function(){dojo.xhrGet({url:"billBuildUpQuantity/getLinkInfo/id/"+a.id+"/bcid/"+d+"/t/"+m,handleAs:"json"}).then(function(r){var w=[{name:"No.",field:"id",styles:"text-align:center;",width:"30px",formatter:k.rowCountCellFormatter},{name:f.description,field:"description",width:"auto"},{name:f.factor,field:"factor-value",width:"100px",styles:"text-align:right;",
formatter:k.formulaNumberCellFormatter}];dojo.forEach(b,function(B){w.push({name:B.title,field:B.field_name,width:"100px",styles:"text-align:right;",formatter:k.formulaNumberCellFormatter})});w.push({name:f.total,field:"total",width:"100px",styles:"text-align:right;",formatter:k.numberCellFormatter});w.push({name:f.sign,field:"sign",width:"70px",styles:"text-align:center;",formatter:k.signCellFormatter});var C=new H({itemId:a.id,billColumnSettingId:d,type:m,hasLinkedQty:r.has_linked_qty,container:h,
_csrf_token:a._csrf_token,disableEditingMode:!0});r.has_linked_qty&&(p=!0,g=G({title:f.scheduleOfQuantities,BillItem:a,billColumnSettingId:d,disableEditingMode:!0,stackContainerId:"postContractStandardBill"+l.billId+"-stackContainer",gridOpts:{qtyType:m,buildUpSummaryWidget:C,store:new dojo.data.ItemFileWriteStore({url:"billBuildUpQuantity/getScheduleOfQuantities/id/"+a.id+"/bcid/"+d+"/type/"+m,clearOnClose:!0}),structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:k.rowCountCellFormatter},
{name:f.description,field:"description",width:"auto",formatter:k.treeCellFormatter},{name:f.type,field:"type",width:"70px",styles:"text-align:center;",formatter:k.typeCellFormatter},{name:f.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:k.unitIdCellFormatter},{name:f.qty,field:"quantity-value",width:"100px",styles:"text-align:right;",formatter:k.formulaNumberCellFormatter}]}}));n.addChild(new M({store:q,structure:w}));p&&n.addChild(g);h.addChild(n);h.addChild(C);if(r=dijit.byId("postContractStandardBill"+
l.billId+"-stackContainer"))r.addChild(new dojox.layout.ContentPane({title:buildspace.truncateString(a.description,45)+" ("+f.buildUpQuantity+" - "+a.uom_symbol+")",id:"buildUpQuantityPage-"+a.id,style:"padding:0px;border:0px;",content:h,grid:p?g.grid:null,executeScripts:!0})),r.selectChild("buildUpQuantityPage-"+a.id);v.hide()})})}})});
