define("buildspace/apps/PostContract/VariationOrder","dojo/_base/declare dojo/_base/lang dojo/aspect dojo/currency dojo/number dijit/layout/ContentPane ./VariationOrder/VariationOrderGrid ./VariationOrder/VariationOrderItemContainer buildspace/apps/Attachment/UploadAttachmentContainer buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(l,v,m,k,n,w,p,q,r,x,s,c){var t=function(a,c,b){if(this.grid.getItem(c).id==buildspace.constants.GRID_LAST_ROW)return b.customClasses.push("disable-cell"),
"&nbsp;";switch(a){case buildspace.apps.PostContract.ProjectStructureConstants.STATUS_APPROVED:a=buildspace.apps.PostContract.ProjectStructureConstants.STATUS_APPROVED_TEXT;b.customClasses.push("green-cell");break;case buildspace.apps.PostContract.ProjectStructureConstants.STATUS_PENDING:a=buildspace.apps.PostContract.ProjectStructureConstants.STATUS_PENDING_TEXT;b.customClasses.push("yellow-cell");break;case buildspace.apps.PostContract.ProjectStructureConstants.STATUS_PREPARING:a=buildspace.apps.PostContract.ProjectStructureConstants.STATUS_PREPARING_TEXT;
break;default:a=""}return a.toUpperCase()},u=function(a,c,b){b.customClasses.push("disable-cell");a=n.parse(a);return 0>a?'<span style="color:#FF0000">'+k.format(a)+"</span>":0==a?"&nbsp;":'<span style="color:#42b449;">'+k.format(a)+"</span>"};return l("buildspace.apps.PostContract.VariationOrder",dijit.layout.BorderContainer,{style:"padding:0;margin:0;border:none;width:100%;height:100%;",region:"center",gutters:!1,rootProject:null,variationOrder:null,borderContainerWidget:null,locked:!1,claimCertificate:null,
postCreate:function(){this.inherited(arguments);var a=this,f=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});f.show().then(function(){dojo.xhrGet({url:"postContract/getClaimGridEditableStatus",handleAs:"json",content:{id:a.rootProject.id}}).then(function(b){a.locked||(a.locked=!b.editable);b=new s;var d=[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:c.rfvNumber,field:"rfv_number",width:"48px",styles:"text-align:center;"},
{name:c.description,field:"description",width:"auto",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea"},{name:c.attachment,field:"attachment",width:"82px",styles:"text-align:center;",formatter:{blueCellFormatter:function(a,b,c){a=this.grid.getItem(b);return 0<=a.id?'<span style="color:blue;">'+a.attachment+"</span>":null}}.blueCellFormatter,noresize:!0}];parseInt(String(a.rootProject.post_contract_type_id))==buildspace.constants.POST_CONTRACT_TYPE_NEW&&(d.push({name:c.type,field:"type",
styles:"text-align:center;",width:"92px",editable:!a.locked,type:"dojox.grid.cells.Select",options:[buildspace.constants.VARIATION_ORDER_TYPE_BUDGETARY_TEXT,buildspace.constants.VARIATION_ORDER_TYPE_CLAIMABLE_TEXT,buildspace.constants.VARIATION_ORDER_TYPE_NON_CLAIMABLE_TEXT],values:[buildspace.constants.VARIATION_ORDER_TYPE_BUDGETARY,buildspace.constants.VARIATION_ORDER_TYPE_CLAIMABLE,buildspace.constants.VARIATION_ORDER_TYPE_NON_CLAIMABLE],noresize:!0}),d.push({name:c.claimCertificateNumber,field:"claim_cert_number",
styles:"text-align:center;",width:"100px",noresize:!0}));dojo.forEach([{name:c.budget,field:"reference_amount",width:"100px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:c.omission,field:"omission",width:"100px",styles:"text-align:right;color:#FF0000;",formatter:b.unEditableCurrencyCellFormatter},{name:c.addition,field:"addition",width:"100px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:c.nettOmissionAddition,field:"nett_omission_addition",
width:"120px",styles:"text-align:right;",formatter:u},{name:c.upToDateClaim,field:"total_claim",width:"100px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:c.status,field:"status",width:"80px",styles:"text-align:center;",editable:!0,type:"dojox.grid.cells.Select",options:[buildspace.apps.PostContract.ProjectStructureConstants.STATUS_PENDING_TEXT,buildspace.apps.PostContract.ProjectStructureConstants.STATUS_PREPARING_TEXT],values:[buildspace.apps.PostContract.ProjectStructureConstants.STATUS_PENDING,
buildspace.apps.PostContract.ProjectStructureConstants.STATUS_PREPARING],formatter:t},{name:c.lastUpdated,field:"updated_at",width:"120px",styles:"text-align: center;"}],function(a){d.push(a)});b="variationOrder/getVariationOrderList/pid/"+a.rootProject.id;a.variationOrder&&(b+="/oid/"+a.variationOrder.id);a.claimCertificate&&(b+="/claimRevision/"+a.claimCertificate.post_contract_claim_revision_id);b=dojo.data.ItemFileWriteStore({url:b,clearOnClose:!0});b=new p({id:"variation_order-"+a.rootProject.id,
stackContainerTitle:c.scheduleOfRates,variationOrderFirstLevelContainer:a,pageId:"variation_order-"+a.rootProject.id,project:a.rootProject,type:"vo",locked:a.locked,claimCertificate:a.claimCertificate,gridOpts:{store:b,addUrl:"variationOrder/variationOrderAdd",updateUrl:"variationOrder/variationOrderUpdate",deleteUrl:"variationOrder/variationOrderDelete",structure:d,onRowDblClick:function(b){(b=this.getItem(b.rowIndex))&&(!isNaN(parseInt(String(b.id)))&&0<String(b.description).length)&&new q({stackContainerTitle:String(b.description),
project:this.project,variationOrder:b,locked:this.locked,claimCertificate:a.claimCertificate,id:"variation_order_items-"+b.id+"-"+this.project.id,pageId:"variation_order_items-"+b.id+"-"+this.project.id+"-page"})}}});b=a.makeGridContainer(b,c.variationOrders);a.borderContainerWidget=b;a.addChild(b);f.hide()})})},makeGridContainer:function(a,c){var b=this.rootProject.id,d=dijit.byId("variationOrder-"+b+"-stackContainer");d&&dijit.byId("variationOrder-"+b+"-stackContainer").destroyRecursive();d=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:none;",
region:"center",id:"variationOrder-"+b+"-stackContainer"});d.addChild(new dijit.layout.ContentPane({title:c,content:a,grid:a.grid}));var g=new dijit.layout.StackController({region:"top",containerId:"variationOrder-"+b+"-stackContainer"}),g=new dijit.layout.ContentPane({style:"padding:0;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:g}),h=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:100%;height:100%;border:none;",gutters:!1,region:"center"});h.addChild(d);h.addChild(g);
dojo.subscribe("variationOrder-"+b+"-stackContainer-selectChild","",function(a){var c=dijit.byId("variationOrder-"+b+"-stackContainer");if(c){var d=c.getChildren(),e=dojo.indexOf(d,a),e=e+1;if(d.length>e){for(;d.length>e;)c.removeChild(d[e]),d[e].destroyDescendants(),d[e].destroyRecursive(),e+=1;var f=a.grid.selection.selectedIndex;a.grid.store.save();a.grid.store.close();var g=m.after(a.grid,"_onFetchComplete",function(){g.remove();-1<f&&(this.scrollToRow(f,!0),this.selection.setSelected(f,!0))});
a.grid.sort()}}});return h},addUploadAttachmentContainer:function(a){var c="project-"+this.rootProject.id+"-uploadAttachment",b=dijit.byId(c);b&&(this.borderContainerWidget.removeChild(b),b.destroy());b=new r({id:c,region:"bottom",item:a,disableEditing:!a.can_be_edited[0],style:"padding:0;margin:0;border:none;width:100%;height:40%;"});this.borderContainerWidget.addChild(b);return b}})});
