define("buildspace/apps/ProjectBuilder/BillManager/AddResourceCategoryDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/currency ./buildUpGrid ./buildUpRateSummary buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/AddResourceCategoryDialog".split(" "),function(b,x,y,z,A,B,m,p,q,r,t,u,d){var v=b("buildspace.apps.ProjectBuilder.BillManager.AddResourceCategoryGrid",dojox.grid.EnhancedGrid,{billId:0,billItem:null,currencyAbbr:null,
billGridStore:null,baseContainer:null,region:"center",style:"border-top:none;",canSort:function(a){return!1},postCreate:function(){var a=this;a.inherited(arguments);this.on("RowClick",function(c){var g=a.getItem(c.rowIndex),h=a.store;if("resource_library_exists"==c.cell.field&&0<g.id){var k=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});if(g.resource_library_exists[0])b={url:"billBuildUpRate/resourceCategoryDelete",content:{bid:a.billItem.id,rid:g.id,_csrf_token:g._csrf_token},
handleAs:"json",load:function(l){if(l.success){h.setValue(g,"resource_library_exists",!1);h.save();var c=dijit.byId("accPane-"+l.rid+"-"+a.billItem.id),b=dijit.byId("accordian_"+a.billId+"_"+a.billItem.id+"-container"),e=dijit.byId("buildUpRateSummary-"+a.billItem.id);b&&c&&(b.removeChild(c),c.destroyRecursive());e&&(l.is_last_resource?(a.baseContainer.removeChild(e),e.destroyRecursive(),b.addChild(new dijit.layout.ContentPane({title:d.emptyResourceCategoryTitle,style:"padding:0px;border:0px;",doLayout:!1,
id:"accPane-empty_resource-"+a.billItem.id,content:'<div style="text-align:center;"><p><h1>'+d.emptyResourceCategory+"</h1></p></div> "})),dojo.xhrGet({url:"billBuildUpRate/getBuildUpSummary",content:{id:a.billItem.id},handleAs:"json",load:function(a){},error:function(a){}})):e.refreshTotalCost())}k.hide()},error:function(a){k.hide()}},buildspace.dialog.confirm(d.confirmation,"<div>"+d.areYouSureDeleteResourceCategory+"</div>",60,280,function(){k.show();dojo.xhrPost(b)});else{k.show();var b={url:"billBuildUpRate/resourceCategoryAdd",
content:{bid:a.billItem.id,rid:g.id,_csrf_token:g._csrf_token},handleAs:"json",load:function(c){if(c.success){h.setValue(g,"resource_library_exists",c.resource_library_exists);h.save();var b=dijit.byId("buildUpRateSummary-"+a.billItem.id);b||(b=new t({id:"buildUpRateSummary-"+a.billItem.id,itemId:a.billItem.id,container:a.baseContainer,billGridStore:a.billGridStore,_csrf_token:g._csrf_token,currentBillLockedStatus:c.bill_locked_status}),a.baseContainer.addChild(b));var l=dijit.byId("accordian_"+a.billId+
"_"+a.billItem.id+"-container"),e=c.resource,n=c.uom,f=new u,m=new dojo.data.ItemFileWriteStore({url:"billBuildUpRate/getBuildUpRateItemList/bill_item_id/"+a.billItem.id+"/resource_id/"+e.id,clearOnClose:!0});c=new r({resource:e,BQItem:a.billItem,gridOpts:{itemId:a.billItem.id,addUrl:"billBuildUpRate/buildUpRateItemAdd",updateUrl:"billBuildUpRate/buildUpRateItemUpdate",deleteUrl:"billBuildUpRate/buildUpRateItemDelete",pasteUrl:"billBuildUpRate/buildUpRateItemPaste",store:m,buildUpSummaryWidget:b,
structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:f.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:f.linkedCellFormatter},{name:d.number,field:"number-value",width:"100px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:f.formulaCurrencyCellFormatter},{name:d.constant,field:"constant-value",width:"100px",styles:"text-align:right;",
editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:f.formulaCurrencyCellFormatter},{name:d.qty,field:"quantity-value",width:"70px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:f.formulaNumberCellFormatter},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",editable:!0,cellType:"dojox.grid.cells.Select",options:n.options,values:n.values,formatter:f.linkedUnitIdCellFormatter},{name:d.rate,field:"rate-value",
width:"120px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:f.formulaCurrencyCellFormatter},{name:d.total,field:"total",width:"120px",styles:"text-align:right;",formatter:f.linkedCurrencyCellFormatter},{name:d.wastage+" (%)",field:"wastage-value",width:"70px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:f.formulaCurrencyCellFormatter},{name:d.lineTotal,field:"line_total",width:"120px",
styles:"text-align:right;",formatter:f.linkedCurrencyCellFormatter}],currentBillLockedStatus:c.bill_locked_status}});e=new dijit.layout.ContentPane({title:e.name+'<span style="color:blue;float:right;">'+a.currencyAbbr+"&nbsp;"+q.format(0)+"</span>",style:"padding:0px;border:0px;",doLayout:!1,id:"accPane-"+e.id+"-"+a.billItem.id,content:c});l.addChild(e);l.selectChild(e);if(e=dijit.byId("accPane-empty_resource-"+a.billItem.id))l.removeChild(e),e.destroyRecursive()}k.hide()},error:function(a){k.hide()}};
dojo.xhrPost(b)}}})},dodblclick:function(a){this.onRowDblClick(a)}}),w=b("buildspace.apps.ProjectBuilder.BillManager.AddResourceCategoryGrid.CellFormatter",null,{rowCountCellFormatter:function(a,c,d){return 0<this.grid.getItem(c).id?parseInt(c)+1:"&nbsp;"},actionCellFormatter:function(a,c){var b=a?d.remove:d.add,h=this.grid.getItem(c),k=Math.round((new Date).getTime()/1E3);return 0<h.id?'<a href="#'+k+'" onclick="return false;">'+b+"</a>":null}});return b("buildspace.apps.ProjectBuilder.BillManager.AddResourceCategoryDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",title:d.addResourceCategory,billId:null,billItem:null,currencyAbbr:null,billGridStore:null,baseContainer:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){p.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==m.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},
createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:500px;height:250px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border:0px;"});c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var b=new w,h=dojo.data.ItemFileWriteStore({url:"billBuildUpRate/getResourceList/item_id/"+this.billItem.id}),b=
v({billId:this.billId,billItem:this.billItem,currencyAbbr:this.currencyAbbr,billGridStore:this.billGridStore,baseContainer:this.baseContainer,store:h,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:d.name,field:"name",width:"auto"},{name:d.action,field:"resource_library_exists",width:"80px",styles:"text-align:center;",formatter:b.actionCellFormatter}]});a.addChild(c);a.addChild(b);return a}})});
