var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(h){var n=0;return function(){return n<h.length?{done:!1,value:h[n++]}:{done:!0}}};$jscomp.arrayIterator=function(h){return{next:$jscomp.arrayIteratorImpl(h)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(h,n,m){if(h==Array.prototype||h==Object.prototype)return h;h[n]=m.value;return h};$jscomp.getGlobal=function(h){h=["object"==typeof globalThis&&globalThis,h,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var n=0;n<h.length;++n){var m=h[n];if(m&&m.Math==Math)return m}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(h,n){var m=$jscomp.propertyToPolyfillSymbol[n];if(null==m)return h[n];m=h[m];return void 0!==m?m:h[n]};
$jscomp.polyfill=function(h,n,m,r){n&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(h,n,m,r):$jscomp.polyfillUnisolated(h,n,m,r))};$jscomp.polyfillUnisolated=function(h,n,m,r){m=$jscomp.global;h=h.split(".");for(r=0;r<h.length-1;r++){var v=h[r];if(!(v in m))return;m=m[v]}h=h[h.length-1];r=m[h];n=n(r);n!=r&&null!=n&&$jscomp.defineProperty(m,h,{configurable:!0,writable:!0,value:n})};
$jscomp.polyfillIsolated=function(h,n,m,r){var v=h.split(".");h=1===v.length;r=v[0];r=!h&&r in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var z=0;z<v.length-1;z++){var E=v[z];if(!(E in r))return;r=r[E]}v=v[v.length-1];m=$jscomp.IS_SYMBOL_NATIVE&&"es6"===m?r[v]:null;n=n(m);null!=n&&(h?$jscomp.defineProperty($jscomp.polyfills,v,{configurable:!0,writable:!0,value:n}):n!==m&&(void 0===$jscomp.propertyToPolyfillSymbol[v]&&(m=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[v]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(v):$jscomp.POLYFILL_PREFIX+m+"$"+v),$jscomp.defineProperty(r,$jscomp.propertyToPolyfillSymbol[v],{configurable:!0,writable:!0,value:n})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(h){if(h)return h;var n=function(z,E){this.$jscomp$symbol$id_=z;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:E})};n.prototype.toString=function(){return this.$jscomp$symbol$id_};var m="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",r=0,v=function(z){if(this instanceof v)throw new TypeError("Symbol is not a constructor");return new n(m+(z||"")+"_"+r++,z)};return v},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(h){if(h)return h;h=Symbol("Symbol.iterator");for(var n="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),m=0;m<n.length;m++){var r=$jscomp.global[n[m]];"function"===typeof r&&"function"!=typeof r.prototype[h]&&$jscomp.defineProperty(r.prototype,h,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return h},"es6",
"es3");$jscomp.iteratorPrototype=function(h){h={next:h};h[Symbol.iterator]=function(){return this};return h};$jscomp.iteratorFromArray=function(h,n){h instanceof String&&(h+="");var m=0,r=!1,v={next:function(){if(!r&&m<h.length){var z=m++;return{value:n(z,h[z]),done:!1}}r=!0;return{done:!0,value:void 0}}};v[Symbol.iterator]=function(){return v};return v};
$jscomp.polyfill("Array.prototype.values",function(h){return h?h:function(){return $jscomp.iteratorFromArray(this,function(n,m){return m})}},"es8","es3");$jscomp.polyfill("Object.is",function(h){return h?h:function(n,m){return n===m?0!==n||1/n===1/m:n!==n&&m!==m}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(h){return h?h:function(n,m){var r=this;r instanceof String&&(r=String(r));var v=r.length;m=m||0;for(0>m&&(m=Math.max(m+v,0));m<v;m++){var z=r[m];if(z===n||Object.is(z,n))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(h,n,m){if(null==h)throw new TypeError("The 'this' value for String.prototype."+m+" must not be null or undefined");if(n instanceof RegExp)throw new TypeError("First argument to String.prototype."+m+" must not be a regular expression");return h+""};$jscomp.polyfill("String.prototype.includes",function(h){return h?h:function(n,m){return-1!==$jscomp.checkStringArgs(this,n,"includes").indexOf(n,m||0)}},"es6","es3");
define("buildspace/apps/ProjectBuilder/BillManager/BillGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dijit/Menu dojo/number dijit/CheckedMenuItem dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn ./importItemDialog ./ImportQtyDialog ./importProjectItemDialog ./importElementDialog ./editBillNoteDialog ./PrintBillDialog dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem dijit/MenuSeparator buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectBuilder dojo/on dojox/grid/_Grid dojox/widget/PlaceholderMenuItem buildspace/widget/grid/cells/TextBox".split(" "),
function(h,n,m,r,v,z,E,T,U,G,H,I,J,K,L,F,M,N,O,D,P,V,W,Q,X,Y,Z,R,f,aa){var S=h("buildspace.apps.ProjectBuilder.BillManager.BillGrid",dojox.grid.EnhancedGrid,{type:null,billId:-1,elementId:0,itemId:-1,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,rowUpdateUrl:null,deleteUrl:null,deleteRateUrl:null,deleteQuantityUrl:null,pasteUrl:null,indentUrl:null,outdentUrl:null,headerMenu:null,typeColumns:null,markupSettings:null,
parentGrid:null,elementGridStore:null,currentBQAddendumId:-1,currentBillLockedStatus:!1,currentGridType:"element",ORIGINAL_BILL_VERSION:0,constructor:function(b){this.type=b.type;this.hierarchyTypes=b.hierarchyTypes;this.hierarchyTypesForHead=b.hierarchyTypesForHead;this.unitOfMeasurements=b.unitOfMeasurements;this.columnGroup=b.columnGroup;this.typeColumns=b.typeColumns;this.markupSettings=b.markupSettings;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:
buildspace.currencyAbbreviation;this.currentBQAddendumId=b.currentBQAddendumId;this.currentBillLockedStatus=b.currentBillLockedStatus;this.currentGridType=b.currentGridType;b=this.formatter=new R;this.typeColumnChildren="tree"!=this.type?[{name:"% "+f.job,field_name:"total",width:"60px",styles:"text-align:right;",editable:!1,formatter:b.elementTypeJobPercentageCellFormatter},{name:f.costPerMetreSquare,field_name:"total_cost",width:"100px",styles:"text-align:right;",editable:!1,formatter:b.unEditableCurrencyCellFormatter},
{name:f.total+"/"+f.unit,field_name:"total_per_unit",width:"100px",styles:"text-align:right;",editable:!1,formatter:b.elementTotalPerUnitCellFormatter},{name:f.estimated+" "+f.costPerMetreSquare,field_name:"estimated_cost_per_metre_square",width:"100px",styles:"text-align:right;",cellType:"buildspace.widget.grid.cells.TextBox",editable:!0,formatter:b.numberCellFormatter},{name:f.estimated+" "+f.totalCost,field_name:"estimated_cost",width:"100px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter}]:
[{name:f.include,field_name:"include",width:"60px",styles:"text-align:center;",editable:!0,cellType:"dojox.grid.cells.Select",options:[f.yesCapital,f.noCapital],values:["true","false"],formatter:b.yesNoCellFormatter},{name:f.qty+"/"+f.unit,field_name:"quantity_per_unit-value",width:"70px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:b.billQuantityCellFormatter},{name:f.qty+"/"+f.unit+" (2)",field_name:"quantity_per_unit_remeasurement-value",
width:"70px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:b.billQuantityCellFormatter},{name:f.difference+" (%)",field_name:"quantity_per_unit_difference",width:"85px",styles:"text-align:right;color:blue;",editable:!1,formatter:b.unEditablePercentageCellFormatter},{name:f.total+"/"+f.unit,field_name:"total_per_unit",width:"100px",styles:"text-align:right;",editable:!1,formatter:b.itemTotalPerUnitCellFormatter}];this.rearranger=G(this,{});
this.formulatedColumn=H(this,{});this.setColumnStructure();this.createHeaderCtxMenu()},canSort:function(b){return!1},postCreate:function(){var b=this;b.inherited(arguments);this.on("RowContextMenu",function(a){b.selection.clear();b.selection.setSelected(a.rowIndex,!0);b.setupContextMenuAndToolbarButtonRestriction(a);b.contextMenu(a)},!0);this.on("RowClick",function(a){b.setupContextMenuAndToolbarButtonRestriction(a)})},doApplyCellEdit:function(b,a,d){var c=this,e=c.getItem(a),l=c.store,g=d.replace("-value",
"");-1!==d.indexOf("-value")&&(b=this.formulatedColumn.convertRowIndexToItemId(b,a));if(b!==e[d][0]){var k=buildspace.dialog.indeterminateProgressBar({title:f.savingData+". "+f.pleaseWait+"..."}),p={id:e.id,attr_name:g,val:b,bill_id:c.billId,_csrf_token:e._csrf_token?e._csrf_token:null,currentBQAddendumId:this.currentBQAddendumId},q=this.updateUrl;e.id==buildspace.constants.GRID_LAST_ROW&&(q=0<a?c.getItem(a-1):!1,n.mixin(p,{prev_item_id:q?q.id:0,relation_id:e.relation_id}),q=this.addUrl);var t=function(u,
w){for(var C in u)e.hasOwnProperty(C)&&C!=w._getIdentifierAttribute()&&w.setValue(e,C,u[C]);u.affected_nodes.hasOwnProperty("affected_bill_items")&&dojo.forEach(u.affected_nodes.affected_bill_items,function(y){w.fetchItemByIdentity({identity:y.id,onItem:function(B){for(var x in y)B.hasOwnProperty(x)&&x!=w._getIdentifierAttribute()&&w.setValue(B,x,y[x])}})});u.affected_nodes.hasOwnProperty("affected_bill_item_type_references")&&dojo.forEach(u.affected_nodes.affected_bill_item_type_references,function(y){w.fetchItemByIdentity({identity:y.id,
onItem:function(B){for(var x in y)B.hasOwnProperty(x)&&x!=w._getIdentifierAttribute()&&w.setValue(B,x,y[x])}})});dojo.forEach(u.affected_nodes,function(y){w.fetchItemByIdentity({identity:y.id,onItem:function(B){for(var x in y)B.hasOwnProperty(x)&&x!=w._getIdentifierAttribute()&&w.setValue(B,x,y[x])}})});"tree"!=c.type&&dojo.forEach(u.other_elements,function(y){w.fetchItemByIdentity({identity:y.id,onItem:function(B){for(var x in y)B.hasOwnProperty(x)&&x!=w._getIdentifierAttribute()&&w.setValue(B,x,
y[x])}})});w.save()},A={url:q,content:p,handleAs:"json",load:function(u){if(u.success){0<e.id?t(u.data,l):(l.deleteItem(e),l.save(),dojo.forEach(u.items,function(C){l.newItem(C)}),l.save(),c.disableToolbarButtons(!0));"type"==d&&buildspace.apps.ProjectBuilder.NoMarkupItemTypes.includes(b)&&c.refreshGrid();var w=c.getCellByField(d);window.setTimeout(function(){c.focus.setFocusIndex(a,w.index)},10);k.hide()}},error:function(u){k.hide()}};void 0!=e[g+"-has_build_up"]&&e[g+"-has_build_up"][0]?(g="<div>"+
f.detachAllBuildUpAndLink+"</div>",buildspace.dialog.confirm(f.confirmation,g,60,280,function(){k.show().then(function(){dojo.xhrPost(A)})}),c.doCancelEdit(a)):"type"==d&&buildspace.apps.ProjectBuilder.NoMarkupItemTypes.includes(b)?(g="<div>"+f.changeItemTypeRemoveMarkup+"</div>",buildspace.dialog.confirm(f.confirmation,g,60,280,function(){k.show().then(function(){dojo.xhrPost(A)})}),c.doCancelEdit(a)):(k.show().then(function(){dojo.xhrPost(A)}),c.inherited(arguments))}else c.inherited(arguments)},
canEdit:function(b,a){var d=this;if(void 0!=b){var c=this.getItem(a),e=b.field;if("tree"==this.type){if(this.currentBillLockedStatus)return!1;if(0<c.id[0]){if(c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||"description"==e||"type"==e||!b.editable){if(c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&"description"!=e&&"type"!=e&&b.editable){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,
b.index)},10);return}if(c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_HTML_EDITOR&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID||"description"!=e){if(c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&"type"!=e&&"uom_id"!=e){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}if(c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&"description"!=e&&"type"!=e&&"rate-value"!=e&&"markup_percentage-value"!=
e&&"markup_amount-value"!=e&&"uom_id"!=e&&b.editable){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}if(c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE&&"rate-value"==e){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}if((c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM||c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE)&&"description"!=e&&"type"!=
e&&"rate-value"!=e&&"markup_percentage-value"!=e&&"markup_amount-value"!=e&&"uom_id"!=e&&b.editable){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}if(c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&"description"!=e&&"type"!=e&&"markup_percentage-value"!=e&&"markup_amount-value"!=e&&"uom_id"!=e&&b.editable){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}}else{window.setTimeout(function(){d.edit.cancel();
d.focus.setFocusIndex(a,b.index)},10);return}}else{window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}if(0<e.indexOf("-quantity_per_unit-value")){var l=e.split("-");if("false"==c[l[0]+"-include"][0]){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}}if(0<e.indexOf("-quantity_per_unit_remeasurement-value")&&(l=e.split("-"),"false"==c[l[0]+"-include"][0])){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,
b.index)},10);return}"type"===e&&(l=d.getItem(a+1),(c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||c.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N)&&b.editable&&void 0!==l&&c.level[0]<l.level[0]?(b.options=d.hierarchyTypesForHead.options,b.values=d.hierarchyTypesForHead.values):(b.options=d.hierarchyTypes.options,b.values=d.hierarchyTypes.values));if(("markup_percentage-value"==e||"markup_amount-value"==e)&&0<=[buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE,
buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT,buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_PC_RATE,buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER,buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N].indexOf(c.type[0])){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}}else if("description"!==e&&"type"!==e)return}else if(0<c.id[0]&&("markup_percentage-value"==e||
"markup_amount-value"==e)&&c.markup_disabled[0]){window.setTimeout(function(){d.edit.cancel();d.focus.setFocusIndex(a,b.index)},10);return}}return this._canEdit},doCancelEdit:function(b){this.inherited(arguments);this.views.renormalizeRow(b);this.scroller.rowHeightChanged(b,!0)},setColumnStructure:function(){var b=this.formatter,a=!0;this.currentBillLockedStatus&&(a=!1);var d="auto";if(1<this.typeColumns.length||this.markupSettings.bill_markup_enabled||this.markupSettings.element_markup_enabled||
this.markupSettings.item_markup_enabled)d="580px";var c=!0;if(this.markupSettings.bill_markup_enabled||this.markupSettings.element_markup_enabled||this.markupSettings.item_markup_enabled)c=!1;if("tree"==this.type){a=this.unitOfMeasurements;var e=this.hierarchyTypes;d=this.fixedColumns={noscroll:!1,width:57.8,cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:b.rowCountCellFormatter,noresize:!0,rowSpan:2,showInCtxMenu:!0},{name:f.billReference,field:"bill_ref",styles:"text-align:center; color: red;",
width:"80px",noresize:!0,hidden:!0,rowSpan:2,showInCtxMenu:!0},{name:f.description,field:"description",width:d,editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:b.treeCellFormatter,noresize:!0,rowSpan:2,showInCtxMenu:!0},{name:f.type,field:"type",width:"70px",styles:"text-align:center;",editable:!0,type:"dojox.grid.cells.Select",options:e.options,values:e.values,formatter:b.typeCellFormatter,noresize:!0,rowSpan:2,showInCtxMenu:!0},{name:f.unit,field:"uom_id",width:"70px",editable:!0,
styles:"text-align:center;",type:"dojox.grid.cells.Select",options:a.options,values:a.values,formatter:b.unitIdCellFormatter,noresize:!0,rowSpan:2,showInCtxMenu:!0},{name:f.grandTotalQty,field:"grand_total_quantity",styles:"text-align:right;color:blue;",width:"90px",formatter:b.unEditableNumberCellFormatter,noresize:!0,hidden:!0,rowSpan:2,showInCtxMenu:!0}]]};c=[{name:f.rate,field:"rate-value",styles:"text-align:right;",width:"75px",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",
formatter:b.formulaCurrencyCellFormatter,noresize:!0,rowSpan:2},{name:f.originalGrandTotal,field:"grand_total",styles:"text-align:right;color:blue;",width:"100px",formatter:b.unEditableCurrencyCellFormatter,noresize:!0,hidden:c,rowSpan:2,showInCtxMenu:!0}];var l=this.constructTypeColumnStructure(d)}else d=this.fixedColumns={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:b.rowCountCellFormatter,noresize:!0,rowSpan:2},{name:f.description,field:"description",
width:d,editable:a,cellType:"buildspace.widget.grid.cells.Textarea",formatter:b.treeCellFormatter,noresize:!0,rowSpan:2}]]},c=[{name:f.grandTotal,field:"grand_total",styles:"text-align:right;color:blue;",width:"100px",formatter:b.unEditableCurrencyCellFormatter,hidden:c,rowSpan:2,noresize:!0,showInCtxMenu:!0}],l=this.constructTypeColumnStructure(d);dojo.forEach(c,function(k){l.cells[0].push(k)});if("tree"==this.type&&this.markupSettings.item_markup_enabled||"tree"!=this.type&&this.markupSettings.element_markup_enabled)c=
[{name:f.markup+" (%)",field:"markup_percentage-value",width:"80px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:b.formulaPercentageCellFormatter,noresize:!0},{name:f.markup+" ("+this.currencySetting+")",field:"markup_amount-value",width:"100px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:b.formulaCurrencyCellFormatter,noresize:!0}],dojo.forEach(c,function(k){l.cells[0].push(k)}),
l.cells[1].push({name:"tree"==this.type?f.item+" "+f.markup:f.element+" "+f.markup,styles:"text-align:center;",headerClasses:"staticHeader",colSpan:c.length});if(this.markupSettings.bill_markup_enabled||this.markupSettings.element_markup_enabled||this.markupSettings.item_markup_enabled){var g=[];"tree"==this.type&&g.push({name:f.rateAfterMarkup,field:"rate_after_markup",width:"100px",styles:"text-align:right;",headerClasses:"typeHeader1",formatter:b.rateAfterMarkupCellFormatter,noresize:!0});dojo.forEach([{name:f.total+
" (%) "+f.markup,field:"tree"==this.type?"grand_total":"original_grand_total",formatter:"tree"==this.type?b.itemTotalMarkupPercentageCellFormatter:b.elementTotalMarkupPercentageCellFormatter},{name:f.total+" ("+this.currencySetting+") "+f.markup,field:"tree"==this.type?"grand_total":"original_grand_total",formatter:"tree"==this.type?b.itemTotalMarkupAmountCellFormatter:b.elementTotalMarkupAmountCellFormatter},{name:f.overallTotalAfterMarkup,field:"tree"==this.type?"grand_total_after_markup":"overall_total_after_markup",
formatter:"tree"==this.type?b.itemOverallTotalAfterMarkupCellFormatter:b.elementOverallTotalAfterMarkupCellFormatter}],function(k){g.push({name:k.name,field:k.field,width:"100px",styles:"text-align:right;",headerClasses:"typeHeader1",formatter:k.formatter,noresize:!0})});"tree"!=this.type&&g.push({name:"% "+f.job,field:"overall_total_after_markup",styles:"text-align:right;",headerClasses:"typeHeader1",width:"70px",formatter:b.elementJobPercentageCellFormatter,noresize:!0});dojo.forEach(g,function(k){l.cells[0].push(k)});
b=[];this.markupSettings.item_markup_enabled&&b.push(f.item);this.markupSettings.element_markup_enabled&&b.push(f.element);this.markupSettings.bill_markup_enabled&&b.push(f.bill);l.cells[1].push({name:'<div style="font-weight:normal;">('+b.toString()+")</div>"+f.markupSummary,styles:"text-align:center;",headerClasses:"staticHeader typeHeader1",colSpan:g.length})}this.structure=l},constructTypeColumnStructure:function(b){var a=this,d=this.typeColumnChildren,c=[],e=0;dojo.forEach(this.typeColumns,function(l){var g=
l.remeasurement_quantity_enabled||"tree"!=a.type?d.length:d.length-2;e++;if("tree"!=a.type){d[1].name=l.floor_area_display_metric?f.costPerMetreSquare:f.costPerSquareFeet;if(l.show_estimated_total_cost)var k=!1;else k=!0,g-=2;d[3].hidden=k;d[4].hidden=k}c.push({name:l.name+"<br>"+f.totalUnit+":"+l.quantity,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+e,colSpan:g,headerId:l.id,hidden:l.is_hidden});for(g=0;g<d.length;g++)if(k=l.id+"-"+d[g].field_name,l.remeasurement_quantity_enabled||
"tree"!=a.type||"quantity_per_unit_remeasurement-value"!=d[g].field_name&&"quantity_per_unit_difference"!=d[g].field_name)k={field:k,columnType:"typeColumn",billColumnSettingId:l.id,hidden:l.is_hidden,headerClasses:"typeHeader"+e},n.mixin(k,d[g]),b.cells[0].push(k)});b.cells.push(c);return b},createHeaderCtxMenu:function(){if("undefined"!==typeof this.fixedColumns){var b=this.fixedColumns.cells[0],a=this,d={headerMenu:new dijit.Menu};dojo.forEach(b,function(c,e){c.showInCtxMenu&&d.headerMenu.addChild(new dijit.CheckedMenuItem({label:c.name,
checked:"undefined"===typeof c.hidden||!1===c.hidden?!0:!1,onChange:function(l){var g=!1;l&&(g=!0);a.showHideMergedColumn(g,e)}}))});this.plugins={menus:d}}},showHideMergedColumn:function(b,a){this.beginUpdate();this.layout.setColumnVisibility(a,b);this.endUpdate()},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut";this.selectedBillColumnSettingId=this.copyCellType=null},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp=
"copy";this.selectedBillColumnSettingId=this.copyCellType=null},copyCell:function(b,a){this.selectedItem=this.selection.getFirstSelected();this.selectedBillColumnSettingId=a;this.copyCellType=b;this.pasteOp=null},importQty:function(b,a){(new J({billId:this.billId,billItem:this.selection.getFirstSelected(),billGrid:this,qtyType:b,targetBillColumnSettingId:a})).show()},pasteItem:function(b){var a=this,d=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."}),c=a.store,e=a.selection.getFirstSelected(),
l=e.id==buildspace.constants.GRID_LAST_ROW&&0<b?a.getItem(b-1).id:0,g={url:this.pasteUrl,content:{type:a.pasteOp,target_id:e.id,prev_item_id:l,id:a.selectedItem.id,currentBQAddendumId:a.currentBQAddendumId,_csrf_token:a.selectedItem._csrf_token},handleAs:"json",load:function(k){var p=[];if(k.success){var q=k.c;switch(a.pasteOp){case "cut":c.fetchItemByIdentity({identity:k.data.id,onItem:function(w){w=a.getItemIndex(w);p.push(w);for(var C=0,y=q.length;C<y;++C)c.fetchItemByIdentity({identity:q[C].id,
onItem:function(B){B=a.getItemIndex(B);p.push(B)}});0<p.length&&a.rearranger.moveRows(p,b);a.selectAfterPaste(w>b?b:b-1,!0)}});c.fetchItemByIdentity({identity:k.data.id,onItem:function(w){for(var C in k.data)w.hasOwnProperty(C)&&C!=c._getIdentifierAttribute()&&c.setValue(w,C,k.data[C]);c.save();var y=0;for(w=q.length;y<w;++y)c.fetchItemByIdentity({identity:q[y].id,onItem:function(B){for(var x in q[y])B.hasOwnProperty(x)&&x!=c._getIdentifierAttribute()&&c.setValue(B,x,q[y][x]);c.save()}})}});break;
case "copy":var t=c.newItem(k.data);c.save();t=a.getItemIndex(t);p.push(t);t=0;for(var A=q.length;t<A;++t){var u=c.newItem(q[t]);c.save();u=a.getItemIndex(u);p.push(u)}0<p.length&&(a.rearranger.moveRows(p,b),a.selectAfterPaste(b,!1))}}a.pasteOp=null;p.length=0;d.hide()},error:function(k){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;d.hide()}};d.show().then(function(){dojo.xhrPost(g)})},selectAfterPaste:function(b,a){this.selection.clear();this.selectedItem=null;
this.selection.setSelected(b,!0);a&&this.scrollToRow(0<b-3?b-3:b)},pasteCell:function(b,a){var d=this,c=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."}),e=d.store;b=d.selection.getFirstSelected();"rate"!=d.copyCellType?(a=a.field.split("-"),a={type:d.copyCellType,target_id:b.id,target_bill_column_setting_id:a[0],id:d.selectedItem.id,bill_column_setting_id:d.selectedBillColumnSettingId,currentBQAddendumId:d.currentBQAddendumId,_csrf_token:d.selectedItem._csrf_token}):a={type:d.copyCellType,
target_id:b.id,id:d.selectedItem.id,currentBQAddendumId:d.currentBQAddendumId,_csrf_token:d.selectedItem._csrf_token};var l={url:this.pasteUrl,content:a,handleAs:"json",load:function(g){if(g.success){var k=g.c;e.fetchItemByIdentity({identity:g.data.id,onItem:function(p){for(var q in g.data)p.hasOwnProperty(q)&&q!=e._getIdentifierAttribute()&&e.setValue(p,q,g.data[q]);e.save();var t=0;for(p=k.length;t<p;++t)e.fetchItemByIdentity({identity:k[t].id,onItem:function(A){for(var u in k[t])A.hasOwnProperty(u)&&
u!=e._getIdentifierAttribute()&&e.setValue(A,u,k[t][u]);e.save()}})}})}d.selection.clear();d.disableToolbarButtons(!0);d.selectedItem=null;d.copyCellType=null;d.selectedBillColumnSettingId=null;c.hide()},error:function(g){d.selection.clear();d.disableToolbarButtons(!0);d.selectedItem=null;d.copyCellType=null;d.selectedBillColumnSettingId=null;c.hide()}};c.show().then(function(){dojo.xhrPost(l)})},addRow:function(b){D.curNode.blur();D.curNode=null;var a=this,d=buildspace.dialog.indeterminateProgressBar({title:f.addingRow+
". "+f.pleaseWait+"..."}),c=a.store,e=a.getItem(b),l=a.billId;if(0<e.id){var g=0<b?a.getItem(b-1).id:0;var k={prev_item_id:g,before_id:e.id,bill_id:l,_csrf_token:e._csrf_token,currentBQAddendumId:this.currentBQAddendumId}}else g=0<b?a.getItem(b-1).id:0,k={id:e.id,bill_id:l,prev_item_id:g,relation_id:e.relation_id,_csrf_token:e._csrf_token,currentBQAddendumId:this.currentBQAddendumId};d.show().then(function(){dojo.xhrPost({url:a.addUrl,content:k,handleAs:"json",load:function(p){p.success&&dojo.forEach(p.items,
function(q){0<q.id&&(q=c.newItem(q),c.save(),q=a.getItemIndex(q),a.rearranger.moveRows([q],b),a.selection.clear())});window.setTimeout(function(){var q="tree"==a.type?2:1;a.selection.setSelected(b,!0);a.focus.setFocusIndex(b,q)},30);d.hide()},error:function(p){a.selection.clear();a.disableToolbarButtons(!0);d.hide()}})})},deleteRow:function(b){var a=this,d=null,c=null;d=a.getItem(b);var e=buildspace.dialog.indeterminateProgressBar({title:f.deleting+". "+f.pleaseWait+"..."});D.curNode.blur();D.curNode=
null;var l={url:this.deleteUrl,content:{id:d.id,method:"normal",addendum_id:a.currentBQAddendumId,_csrf_token:d._csrf_token},handleAs:"json",load:function(g){if(g.success){var k=g.items,p=a.store;if(void 0!=g.affected_nodes){g=g.affected_nodes;for(var q in g)dojo.forEach(g[q],function(t){p.fetchItemByIdentity({identity:t.id,onItem:function(A){for(var u in t)A.hasOwnProperty(u)&&u!=p._getIdentifierAttribute()&&(p.setValue(A,u,t[u]),p.save())}})})}q=0;for(g=k.length;q<g;++q)p.fetchItemByIdentity({identity:k[q].id,
onItem:function(t){p.deleteItem(t);p.save()}});k.length=0}e.hide();a.selection.clear();window.setTimeout(function(){a.focus.setFocusIndex(b,0)},10);a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;a.copyCellType=null},error:function(g){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;a.copyCellType=null;e.hide()}};"tree"!=this.type?(d=f.deleteElementDialogBoxTitle,c=f.deleteElementDialogBoxMsg):d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||
d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N?(d=f.deleteHeadDialogBoxTitle,c=f.deleteHeadDialogBoxMsg):(d=f.deleteItemDialogBoxTitle,c=f.deleteItemDialogBoxMsg);new buildspace.dialog.confirm(d,c,80,320,function(){e.show().then(function(){dojo.xhrPost(l)})},function(){})},deleteQuantity:function(b,a,d){var c=this,e=c.getItem(b),l=buildspace.dialog.indeterminateProgressBar({title:f.deleting+". "+f.pleaseWait+"..."});D.curNode.blur();D.curNode=null;a=a.field.split("-");var g={type:d,
bill_column_setting_id:a[0],id:e.id,_csrf_token:e._csrf_token};l.show().then(function(){dojo.xhrPost({url:c.deleteQuantityUrl,content:g,handleAs:"json",load:function(k){if(k.success){var p=c.store;dojo.forEach(k.items,function(q){p.fetchItemByIdentity({identity:q.id,onItem:function(t){for(var A in q)t.hasOwnProperty(A)&&A!=p._getIdentifierAttribute()&&(p.setValue(t,A,q[A]),p.save())}})})}l.hide();c.selection.clear();window.setTimeout(function(){c.focus.setFocusIndex(b,0)},10);c.disableToolbarButtons(!0);
c.selectedItem=null;c.pasteOp=null;c.copyCellType=null},error:function(k){c.selection.clear();c.disableToolbarButtons(!0);c.selectedItem=null;c.pasteOp=null;c.copyCellType=null;l.hide()}})})},deleteRate:function(b){var a=this,d=a.getItem(b),c=buildspace.dialog.indeterminateProgressBar({title:f.deleting+". "+f.pleaseWait+"..."});D.curNode.blur();D.curNode=null;c.show().then(function(){dojo.xhrPost({url:a.deleteRateUrl,content:{id:d.id,_csrf_token:d._csrf_token},handleAs:"json",load:function(e){if(e.success){var l=
a.store;dojo.forEach(e.items,function(g){l.fetchItemByIdentity({identity:g.id,onItem:function(k){for(var p in g)k.hasOwnProperty(p)&&p!=l._getIdentifierAttribute()&&(l.setValue(k,p,g[p]),l.save())}})})}c.hide();a.selection.clear();window.setTimeout(function(){a.focus.setFocusIndex(b,0)},10);a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;a.copyCellType=null},error:function(e){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;a.copyCellType=null;c.hide()}})})},
indentOutdent:function(b,a){var d=this,c=d.store;if(0<b){var e=d.getItem(b),l=buildspace.dialog.indeterminateProgressBar({title:f.recalculateRows+". "+f.pleaseWait+"..."});if(0<e.id){var g={url:this[a+"Url"],content:{id:e.id,_csrf_token:e._csrf_token},handleAs:"json",load:function(k){if(k.success){var p=k.c,q;for(q in k.item)k.item.hasOwnProperty(q)&&q!=c._getIdentifierAttribute()&&c.setValue(e,q,k.item[q]);var t=0;for(k=p.length;t<k;++t)c.fetchItemByIdentity({identity:p[t].id,onItem:function(A){for(var u in p[t])A.hasOwnProperty(u)&&
u!=c._getIdentifierAttribute()&&c.setValue(A,u,p[t][u])}});c.save()}l.hide()},error:function(k){d.selection.clear();d.disableToolbarButtons(!0);l.hide()}};l.show().then(function(){dojo.xhrPost(g)})}}},refreshGrid:function(){this.beginUpdate();this.set("structure",this.structure);this.set("headerMenu",this.createHeaderCtxMenu());this.store.close();this.pluginMgr=new this._pluginMgrClass(this);this.pluginMgr.preInit();this.pluginMgr.postInit();this.pluginMgr.startup();this._refresh();this.endUpdate()},
editableCellDblClick:function(b){var a=1<this._click.length&&has("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=this._click[1].rowIndex?this._click[0]:b;this.focus.setFocusCell(a.cell,a.rowIndex);this.onRowClick(a);this.onRowDblClick(b)},dodblclick:function(b){if(b.cellNode)if(b.cell.editable)this.editableCellDblClick(b);else this.onCellDblClick(b);else this.onRowDblClick(b)},contextMenu:function(b){var a=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(b);var d={target:b.target,
coords:b.keyCode!==O.F10&&"pageX"in b?{x:b.pageX,y:b.pageY}:null},c=this.getItem(b.rowIndex);if(this.currentBillLockedStatus)return!1;a&&c&&(this.selection.isSelected(b.rowIndex)||b.rowNode&&P.hasClass(b.rowNode,"dojoxGridRowbar"))&&(a._openMyself(d),N.stop(b))},contextMenuItems:function(b){var a=this;var d=this.getItem(b.rowIndex-1);var c=this.getItem(b.rowIndex),e=b.cell,l=!1;"tree"==this.type&&(void 0===d&&(l=!0),d&&d.type[0]===buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&(l=!0));if(0<
c.id&&(a.rowCtxMenu.addChild(new dijit.MenuItem({label:f.cut,iconClass:"icon-16-container icon-16-cut",onClick:function(){a.pasteType="structure";a.cutItems()},disabled:!1})),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(a,"copyItems"),disabled:!1})),"tree"==a.type))if(0<e.field.indexOf("-quantity_per_unit-value")){if(c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&
c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID){d=e.field.split("-");var g=z.parse(c[d[0]+"-quantity_per_unit-final_value"]);
a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.copyQty,iconClass:"icon-16-container icon-16-copy",disabled:isNaN(g)||0==g||null==g?!0:!1,onClick:dojo.hitch(a,"copyCell","qty",d[0])}));a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.importQtyFromProjects,iconClass:"icon-16-container icon-16-import",onClick:dojo.hitch(a,"importQty","qty",d[0])}))}}else 0<e.field.indexOf("-quantity_per_unit_remeasurement-value")?c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&
c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&(d=e.field.split("-"),g=z.parse(c[d[0]+"-quantity_per_unit_remeasurement-final_value"]),
a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.copyQty,iconClass:"icon-16-container icon-16-copy",disabled:isNaN(g)||0==g||null==g?!0:!1,onClick:dojo.hitch(a,"copyCell","qty_remeasurement",d[0])})),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.importQtyFromProjects,iconClass:"icon-16-container icon-16-import",onClick:dojo.hitch(a,"importQty","qty_remeasurement",d[0])}))):"rate-value"==e.field&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&
c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&(g=z.parse(c["rate-final_value"]),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.copyRate,iconClass:"icon-16-container icon-16-copy",disabled:isNaN(g)||0==g||null==g?!0:!1,onClick:dojo.hitch(a,"copyCell","rate")})));d=!0;g="pasteItem";"tree"==a.type&&a.selectedItem?"qty"==a.copyCellType&&0<c.id&&0<e.field.indexOf("-quantity_per_unit-value")&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&
c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID?(d=!1,g="pasteCell"):"qty_remeasurement"==a.copyCellType&&0<c.id&&0<e.field.indexOf("-quantity_per_unit_remeasurement-value")&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&
c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID?(d=!1,g="pasteCell"):"rate"==a.copyCellType&&0<c.id&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&
c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID?(d=!1,g="pasteCell"):null==a.copyCellType&&(d=!1):d=a.selectedItem?!1:!0;a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(a,g,b.rowIndex,e),disabled:d}));0<c.id&&"tree"==a.type?(a.rowCtxMenu.addChild(new dijit.MenuItem({label:f.indent,iconClass:"icon-16-container icon-16-indent",onClick:dojo.hitch(a,
"indentOutdent",b.rowIndex,"indent"),disabled:!1})),a.rowCtxMenu.addChild(new dijit.MenuItem({label:f.outdent,iconClass:"icon-16-container icon-16-outdent",onClick:dojo.hitch(a,"indentOutdent",b.rowIndex,"outdent"),disabled:!1})),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.editItemNote,iconClass:"icon-16-container icon-16-note",onClick:dojo.hitch(a,"doEditItemNote",c)}))):0<c.id&&"tree"!=a.type&&a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.editTradeNote,iconClass:"icon-16-container icon-16-note",
onClick:dojo.hitch(a,"doEditTradeNote",c)}));a.rowCtxMenu.addChild(new dijit.MenuItem({label:f.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(a,"addRow",b.rowIndex),disabled:l}));0<c.id&&(a.rowCtxMenu.addChild(new Q),a.rowCtxMenu.addChild(new dijit.MenuItem({label:f.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(a,"deleteRow",b.rowIndex),disabled:!1})),"tree"==a.type&&(0<e.field.indexOf("-quantity_per_unit-value")?c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&
c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&
(d=e.field.split("-"),g=z.parse(c[d[0]+"-quantity_per_unit-final_value"]),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.deleteQty,iconClass:"icon-16-container icon-16-delete",disabled:isNaN(g)||0==g||null==g?!0:!1,onClick:dojo.hitch(a,"deleteQuantity",b.rowIndex,e,"qty")}))):0<e.field.indexOf("-quantity_per_unit_remeasurement-value")?c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&
c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_NOT_LISTED&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_PERCENT&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&(d=e.field.split("-"),g=z.parse(c[d[0]+"-quantity_per_unit_remeasurement-final_value"]),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.deleteQty,
iconClass:"icon-16-container icon-16-delete",disabled:isNaN(g)||0==g||null==g?!0:!1,onClick:dojo.hitch(a,"deleteQuantity",b.rowIndex,e,"qty_remeasurement")}))):"rate-value"==e.field&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&(g=z.parse(c["rate-final_value"]),a.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.deleteRate,iconClass:"icon-16-container icon-16-delete",
disabled:isNaN(g)||0==g||null==g?!0:!1,onClick:dojo.hitch(a,"deleteRate",b.rowIndex)})))))},doEditItemNote:function(b){(new F({item:b,billGrid:this,title:f.editItemNote,updateUrl:"billManager/itemNoteUpdate"})).show()},doEditTradeNote:function(b){(new F({item:b,billGrid:this,title:f.editTradeNote,updateUrl:"billManager/elementNoteUpdate"})).show()},onHeaderCellClick:function(b){dojo.hasClass(b.cell.id,"staticHeader")||(b.grid.setSortIndex(b.cell.index),b.grid.onHeaderClick(b))},onHeaderCellMouseOver:function(b){dojo.hasClass(b.cell.id,
"staticHeader")||dojo.addClass(b.cellNode,this.cellOverClass)},onStyleRow:function(b){this.inherited(arguments);if(b.node.children[0]&&2<=b.node.children[0].children[0].rows.length){var a=b.node.children[0].children[0].rows[1],d=b.node.children[0].children[0].rows[0].children;a.parentNode.removeChild(a);dojo.forEach(d,function(c,e){e=dojo.attr(c,"rowSpan");(!e||2>e)&&dojo.attr(c,"rowSpan",2)})}},disableToolbarButtons:function(b,a){var d=dijit.byId(this.billId+this.elementId+"AddRow-button"),c=dijit.byId(this.billId+
this.elementId+"DeleteRow-button"),e=dijit.byId(this.billId+this.elementId+"IndentRow-button"),l=dijit.byId(this.billId+this.elementId+"OutdentRow-button"),g=dijit.byId(this.billId+this.elementId+"ImportElementFromLibraryRow-button"),k=dijit.byId(this.billId+this.elementId+"ImportItemFromLibraryRow-button"),p=dijit.byId(this.billId+this.elementId+"ImportItemFromProjectRow-button");d._setDisabledAttr(b);c._setDisabledAttr(b);g&&g._setDisabledAttr(b);k&&k._setDisabledAttr(b);p&&p._setDisabledAttr(b);
e&&e._setDisabledAttr(b);l&&l._setDisabledAttr(b);if(b&&a instanceof Array){var q=this;dojo.forEach(a,function(t){(t=dijit.byId(q.billId+q.elementId+t+"Row-button"))&&t._setDisabledAttr(!1)})}},disableAllButtonWhenCurrentBillIsLocked:function(){this.currentBillLockedStatus||("tree"==this.type?this.disableToolbarButtons(!0,["Add","ImportItemFromLibrary","ImportItemFromProject"]):this.disableToolbarButtons(!0,["Add","ImportElementFromLibrary"]))},setupContextMenuAndToolbarButtonRestriction:function(b){(b=
this.getItem(b.rowIndex))&&0<b.id&&!this.currentBillLockedStatus?this.disableToolbarButtons(!1):this.disableAllButtonWhenCurrentBillIsLocked()}});return h("buildspace.apps.ProjectBuilder.BillManager.BillGridBuilder",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;width:100%;height:100%;border:0px!important;",gutters:!1,stackContainerTitle:"",billId:-1,elementId:0,itemId:-1,rowSelector:null,gridOpts:{},type:null,postCreate:function(){var b=this;this.inherited(arguments);n.mixin(this.gridOpts,
{billId:this.billId,elementId:this.elementId,type:this.type,region:"center",borderContainerWidget:this});var a=this.grid=new S(this.gridOpts),d=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});d.addChild(new dijit.form.Button({id:this.billId+this.elementId+"AddRow-button",label:f.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.addRow(a.selection.selectedIndex)}}));"tree"==
this.type&&(d.addChild(new dijit.ToolbarSeparator),d.addChild(new dijit.form.Button({id:this.billId+this.elementId+"IndentRow-button",label:f.indent,iconClass:"icon-16-container icon-16-indent",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.indentOutdent(a.selection.selectedIndex,"indent")}})),d.addChild(new dijit.ToolbarSeparator),d.addChild(new dijit.form.Button({id:this.billId+this.elementId+"OutdentRow-button",label:f.outdent,iconClass:"icon-16-container icon-16-outdent",
disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.indentOutdent(a.selection.selectedIndex,"outdent")}})));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({id:this.billId+this.elementId+"DeleteRow-button",label:f.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.deleteRow(a.selection.selectedIndex)}}));"tree"==this.type?(d.addChild(new dijit.ToolbarSeparator),
d.addChild(new dijit.form.Button({id:this.billId+this.elementId+"ImportItemFromLibraryRow-button",label:f.importItemsFromLibrary,iconClass:"icon-16-container icon-16-import",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&(new I({billId:b.billId,selectedItem:a.selection.getFirstSelected(),elementId:b.elementId,billGrid:a,currentBQAddendumId:b.gridOpts.currentBQAddendumId})).show()}})),d.addChild(new dijit.ToolbarSeparator),d.addChild(new dijit.form.Button({id:this.billId+
this.elementId+"ImportItemFromProjectRow-button",label:f.importItemsFromProject,iconClass:"icon-16-container icon-16-import",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&(new K({billId:b.billId,selectedItem:a.selection.getFirstSelected(),elementId:b.elementId,billGrid:a,currentBQAddendumId:b.gridOpts.currentBQAddendumId})).show()}}))):(d.addChild(new dijit.ToolbarSeparator),d.addChild(new dijit.form.Button({id:this.billId+this.elementId+"ImportElementFromLibraryRow-button",
label:f.importElementsFromLibrary,iconClass:"icon-16-container icon-16-import",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&(new L({billId:b.billId,selectedItem:a.selection.getFirstSelected(),elementId:b.elementId,billGrid:a})).show()}})),d.addChild(new dijit.ToolbarSeparator),d.addChild(new dijit.form.Button({label:f.printBQ,iconClass:"icon-16-container icon-16-print",onClick:function(){(new M({billId:b.billId,bqCSRFToken:b.gridOpts.bqCSRFToken})).show()}})));
this.addChild(d);this.addChild(a);(d=dijit.byId("add_resource_category_"+this.billId+"-btn"))&&d.destroy();if(d=dijit.byId("billGrid"+this.billId+"-stackContainer")){var c=document.createElement("div");d.addChild(new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),content:this,id:this.pageId,grid:a},c));d.selectChild(this.pageId)}}})});
