define("buildspace/apps/ProjectBuilder/BillManager/buildUpGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/currency dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox dijit/popup dijit/TooltipDialog ./importResourceDialog dojo/i18n!buildspace/nls/BuildUpGrid".split(" "),
function(p,q,D,E,F,G,t,u,v,w,x,m,y,H,I,J,K,L,r,z,A,e){var C=p("buildspace.apps.ProjectBuilder.BillManager.BuildUp.grid",dojox.grid.EnhancedGrid,{itemId:-1,resource:null,BQItem:null,style:"border-top:none;",selectedItem:null,unitObj:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,buildUpSummaryWidget:null,currentBillLockedStatus:!1,disableEditingMode:!1,constructor:function(a){this.rearranger=t(this,{});this.formulatedColumn=u(this,{});this.currencySetting=
buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;a.currentBillLockedStatus&&(this.disableEditingMode=!0)},canSort:function(a){return!1},canEdit:function(a,b){this.closeToolTipDialogIfAvailable();return this.disableEditingMode?!1:this._canEdit},postCreate:function(){var a=this;this.inherited(arguments);this.on("RowContextMenu",function(b){a.selection.clear();var c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b);c&&
!a.disableEditingMode?0<c.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Import"]):a.disableEditingMode&&a.disableToolbarButtons(!0)},!0);this.on("RowClick",function(b){(b=a.getItem(b.rowIndex))&&!a.disableEditingMode?0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0,["Import"]):a.disableEditingMode&&a.disableToolbarButtons(!0)})},doApplyCellEdit:function(a,b,c){var d=this,f=d.getItem(b),h=d.store;if(a!==f[c][0]){var g=c.replace("-value","");-1!==c.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,
b));var k={id:f.id,attr_name:g,val:a,_csrf_token:f._csrf_token?f._csrf_token:null},l=this.updateUrl;f.id==buildspace.constants.GRID_LAST_ROW&&(l=0<b?d.getItem(b-1):!1,q.mixin(k,{prev_item_id:l?l.id:0,relation_id:f.relation_id,resource_id:d.resource.id}),l=this.addUrl);var B=function(a,b){for(var c in a)f.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(f,c,a[c]),dojo.forEach(a.affected_nodes,function(a){b.fetchItemByIdentity({identity:a.id,onItem:function(c){for(var d in a)f.hasOwnProperty(d)&&
d!=b._getIdentifierAttribute()&&b.setValue(c,d,a[d])}})});b.save()},n=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});n.show();dojo.xhrPost({url:l,content:k,handleAs:"json",load:function(a){if(a.success){0<f.id?B(a.data,h):(h.deleteItem(f),h.save(),dojo.forEach(a.items,function(a){h.newItem(a)}),h.save(),d.disableToolbarButtons(!0));"description"!=g&&d.updateTotalBuildUp(a.total_build_up);var k=d.getCellByField(c);window.setTimeout(function(){d.focus.setFocusIndex(b,k.index)},
10)}n.hide()},error:function(a){console.log(a);n.hide()}})}this.inherited(arguments)},dodblclick:function(a){},onCellFocus:function(a,b){var c=this,d=c.getItem(b);"description"!==a.field||0>d.id[0]||!d.linked[0]?c.closeToolTipDialogIfAvailable():dojo.xhrGet({url:"resourceLibrary/getBuildUpRatesToolTipInformation",content:{id:d.id,type:"bill"},handleAs:"json",load:function(d){if(d.success){c.closeToolTipDialogIfAvailable();var f=!1,g='<h1 style="font-size: 12px; text-shadow: 1px 1px 1px #000;background-color: rgba(35, 35, 35, .85); color: #fff; padding: 4px 10px;">'+
d.items[0].description+"</h1>";1<Object.keys(d.items).length&&(f=!0,g+='<table style="width: 100%; border-collapse: collapse;">');dojo.forEach(d.items,function(a,b){0!==b&&(g+='<tr><td style="border: 1px dotted #D5CDB5; font-weight: bold; font-size: 11px; padding-left:'+16*a.level+'px;">'+a.description+"</td></td>")});f&&(g+="</table>");c.myTooltipDialog=new z({id:"buildUpRatesTooltipDialog-"+c.itemId[0],style:"width: 300px;",content:g});r.open({popup:c.myTooltipDialog,around:a.view.rowNodes[b],orient:["below"]})}},
error:function(a){console.log(a)}})},onRowMouseOut:function(){this.closeToolTipDialogIfAvailable()},addRow:function(a){m.curNode.blur();m.curNode=null;var b,c=this,d=buildspace.dialog.indeterminateProgressBar({title:e.addingRow+". "+e.pleaseWait+"..."}),f=this.store;b=this.getItem(a);if(0<b.id)b={before_id:b.id,_csrf_token:b._csrf_token};else{var h=0<a?c.getItem(a-1).id:0;b={id:b.id,prev_item_id:h,relation_id:b.relation_id,resource_id:c.resource.id,_csrf_token:b._csrf_token}}d.show();dojo.xhrPost({url:this.addUrl,
content:b,handleAs:"json",load:function(b){b.success&&dojo.forEach(b.items,function(b){0<b.id&&(b=f.newItem(b),f.save(),b=c.getItemIndex(b),c.rearranger.moveRows([b],a),c.selection.clear())});window.setTimeout(function(){c.selection.setSelected(a,!0);c.focus.setFocusIndex(a,1)},30);d.hide()},error:function(a){c.selection.clear();c.disableToolbarButtons(!0);d.hide()}})},deleteRow:function(a){var b=this,c=b.getItem(a),d=buildspace.dialog.indeterminateProgressBar({title:e.deleting+". "+e.pleaseWait+
"..."});m.curNode.blur();m.curNode=null;d.show();var f={url:this.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(f){if(f.success){var g=f.affected_nodes,k=b.store;k.deleteItem(c);k.save();for(var e=0,h=g.length;e<h;++e)k.fetchItemByIdentity({identity:g[e].id,onItem:function(a){for(var b in g[e])a.hasOwnProperty(b)&&b!=k._getIdentifierAttribute()&&k.setValue(a,b,g[e][b]);k.save()}});b.updateTotalBuildUp(f.total_build_up)}d.hide();b.selection.clear();window.setTimeout(function(){b.focus.setFocusIndex(a,
0)},10);b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;d.hide()}};new buildspace.dialog.confirm(e.deleteBuildUpRateItemTitle,e.deleteBuildUpRateItemMsg,80,320,function(){dojo.xhrPost(f)},function(){d.hide()})},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp=
"copy"},pasteItem:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),d=this.store,f=this.selection.getFirstSelected(),h=f.id==buildspace.constants.GRID_LAST_ROW&&0<a?this.getItem(a-1).id:0;c.show();dojo.xhrPost({url:this.pasteUrl,content:{type:b.pasteOp,target_id:f.id,id:b.selectedItem.id,prev_item_id:h,_csrf_token:b.selectedItem._csrf_token},handleAs:"json",load:function(f){var e=[];if(f.success)switch(b.pasteOp){case "cut":d.fetchItemByIdentity({identity:f.data.id,
onItem:function(c){c=b.getItemIndex(c);e.push(c);0<e.length&&b.rearranger.moveRows(e,a);b.selectAfterPaste(c>a?a:a-1,!0)}});break;case "copy":var g=d.newItem(f.data);d.save();g=b.getItemIndex(g);e.push(g);0<e.length&&(b.rearranger.moveRows(e,a),b.selectAfterPaste(a,!1));b.updateTotalBuildUp(f.total_build_up)}b.disableToolbarButtons(!1);b.pasteOp=null;e.length=0;c.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;c.hide()}})},selectAfterPaste:function(a,
b){this.selection.clear();this.selectedItem=null;this.selection.setSelected(a,!0);b&&this.scrollToRow(0<a-3?a-3:a)},contextMenu:function(a){if(this.disableEditingMode)return!1;var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==w.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},d=this.getItem(a.rowIndex);b&&d&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&y.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),v.stop(a))},contextMenuItems:function(a){var b=
this.getItem(a.rowIndex);0<b.id&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItems")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(this,"copyItems")})));this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:e.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(this,"pasteItem",a.rowIndex),disabled:this.selectedItem?
!1:!0}));this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow",a.rowIndex)}));0<b.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:e.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow",a.rowIndex)}))},disableToolbarButtons:function(a,b){var c=dijit.byId("builUpGrid-"+this.resource.id+"_"+this.BQItem.id+"AddRow-button"),d=dijit.byId("builUpGrid-"+this.resource.id+"_"+this.BQItem.id+
"DeleteRow-button"),f=dijit.byId("builUpGrid-"+this.resource.id+"_"+this.BQItem.id+"ImportRow-button");c._setDisabledAttr(a);d._setDisabledAttr(a);f._setDisabledAttr(a);if(a&&b instanceof Array){var e=this;dojo.forEach(b,function(a){dijit.byId("builUpGrid-"+e.resource.id+"_"+e.BQItem.id+a+"Row-button")._setDisabledAttr(!1)})}},updateTotalBuildUp:function(a){dijit.byId("accPane-"+this.resource.id+"-"+this.BQItem.id).set("title",this.resource.name+'<span style="color:blue;float:right;">'+this.currencySetting+
"&nbsp;"+x.format(a)+"</span>");this.buildUpSummaryWidget.refreshTotalCost()},closeToolTipDialogIfAvailable:function(){var a=dijit.byId("buildUpRatesTooltipDialog-"+this.itemId[0]);void 0!==this.myTooltipDialog&&void 0!==a&&(r.close(),a.destroy())}});return p("buildspace.apps.ProjectBuilder.BillManager.BuildUpGrid",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,resource:null,BQItem:null,gridOpts:{},postCreate:function(){this.inherited(arguments);q.mixin(this.gridOpts,
{resource:this.resource,BQItem:this.BQItem,region:"center"});var a=this.grid=new C(this.gridOpts),b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({id:"builUpGrid-"+this.resource.id+"_"+this.BQItem.id+"AddRow-button",label:e.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.addRow(a.selection.selectedIndex)}}));b.addChild(new dijit.ToolbarSeparator);
b.addChild(new dijit.form.Button({id:"builUpGrid-"+this.resource.id+"_"+this.BQItem.id+"DeleteRow-button",label:e.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.deleteRow(a.selection.selectedIndex)}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"builUpGrid-"+this.resource.id+"_"+this.BQItem.id+"ImportRow-button",label:e.importFromResourceLibrary,iconClass:"icon-16-container icon-16-import",
disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){A({BQItem:a.BQItem,resource:a.resource,buildUpGridStore:a.store}).show()}}));this.addChild(b);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))}})});
