define("buildspace/apps/ProjectBuilder/BillManager/buildUpQuantityGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/currency dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox dojo/i18n!buildspace/nls/BuildUpQuantityGrid".split(" "),
function(n,p,y,z,A,B,q,r,t,u,C,l,v,D,E,F,G,H,g){var x=n("buildspace.apps.ProjectBuilder.BillManager.BuildUpQuantity.grid",dojox.grid.EnhancedGrid,{billColumnSettingId:null,BillItem:null,style:"border:none!important;",selectedItem:null,keepSelection:!0,addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,buildUpSummaryWidget:null,type:null,disableEditingMode:!1,constructor:function(b){this.rearranger=q(this,{});this.formulatedColumn=r(this,{})},canSort:function(b){return!1},canEdit:function(b,a){return this.disableEditingMode?
!1:this._canEdit},postCreate:function(){var b=this;this.inherited(arguments);this.disableEditingMode||(this.on("RowContextMenu",function(a){b.selection.clear();var c=b.getItem(a.rowIndex);b.selection.setSelected(a.rowIndex,!0);b.contextMenu(a);c&&0<c.id?b.disableToolbarButtons(!1):b.disableToolbarButtons(!0,["Add"])},!0),this.on("RowClick",function(a){(a=b.getItem(a.rowIndex))&&0<a.id?b.disableToolbarButtons(!1):b.disableToolbarButtons(!0,["Add"])}))},doApplyCellEdit:function(b,a,c){var f=this,d=
f.getItem(a),h=f.store;if(b!==d[c][0]){var k=c.replace("-value","");-1!==c.indexOf("-value")&&(b=this.formulatedColumn.convertRowIndexToItemId(b,a));var k={id:d.id,attr_name:k,val:b,type:f.type,_csrf_token:d._csrf_token?d._csrf_token:null},e=this.updateUrl;d.id==buildspace.constants.GRID_LAST_ROW&&(e=0<a?f.getItem(a-1):!1,p.mixin(k,{prev_item_id:e?e.id:0,relation_id:d.relation_id,bill_column_setting_id:f.billColumnSettingId}),e=this.addUrl);var w=function(a,b){for(var c in a)d.hasOwnProperty(c)&&
c!=b._getIdentifierAttribute()&&b.setValue(d,c,a[c]),dojo.forEach(a.affected_nodes,function(a){b.fetchItemByIdentity({identity:a.id,onItem:function(c){for(var e in a)d.hasOwnProperty(e)&&e!=b._getIdentifierAttribute()&&b.setValue(c,e,a[e])}})});b.save()},m=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."});m.show();dojo.xhrPost({url:e,content:k,handleAs:"json",load:function(b){if(b.success){d&&0<d.id?w(b.data,h):(h.deleteItem(d),h.save(),dojo.forEach(b.items,function(a){h.newItem(a)}),
h.save(),f.disableToolbarButtons(!0));f.updateTotalBuildUp(b.total_build_up);var e=f.getCellByField(c);window.setTimeout(function(){f.focus.setFocusIndex(a,e.index)},10)}m.hide()},error:function(a){m.hide()}})}this.inherited(arguments)},dodblclick:function(b){},addRow:function(b){l.curNode.blur();l.curNode=null;var a,c=this,f=buildspace.dialog.indeterminateProgressBar({title:g.addingRow+". "+g.pleaseWait+"..."}),d=this.store;a=this.getItem(b);if(0<a.id)a={before_id:a.id,type:c.type,_csrf_token:a._csrf_token,
bill_column_setting_id:c.billColumnSettingId,relation_id:a.relation_id};else{var h=0<b?c.getItem(b-1).id:0;a={id:a.id,type:c.type,prev_item_id:h,relation_id:a.relation_id,bill_column_setting_id:c.billColumnSettingId,_csrf_token:a._csrf_token}}f.show();dojo.xhrPost({url:this.addUrl,content:a,handleAs:"json",load:function(a){a.success&&dojo.forEach(a.items,function(a){0<a.id&&(a=d.newItem(a),d.save(),a=c.getItemIndex(a),c.rearranger.moveRows([a],b),c.selection.clear())});window.setTimeout(function(){c.selection.setSelected(b,
!0);c.focus.setFocusIndex(b,1)},30);f.hide()},error:function(a){c.selection.clear();c.disableToolbarButtons(!0);f.hide()}})},deleteRow:function(b){var a=this,c=a.getItem(b),f=buildspace.dialog.indeterminateProgressBar({title:g.deleting+". "+g.pleaseWait+"..."});l.curNode.blur();l.curNode=null;f.show();var d={url:this.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(d){if(d.success){var k=d.affected_nodes,e=a.store;e.deleteItem(c);e.save();var g=0;for(d=k.length;g<
d;++g)e.fetchItemByIdentity({identity:k[g].id,onItem:function(a){for(var b in k[g])a.hasOwnProperty(b)&&b!=e._getIdentifierAttribute()&&e.setValue(a,b,k[g][b]);e.save()}});a.updateTotalBuildUp()}f.hide();a.selection.clear();window.setTimeout(function(){a.focus.setFocusIndex(b,0)},10);a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;f.hide()}};new buildspace.dialog.confirm(g.deleteBuildUpQtyItemTitle,
g.deleteBuildUpQtyItemMsg,80,320,function(){dojo.xhrPost(d)},function(){f.hide()})},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="copy"},pasteItem:function(b){var a=this,c=buildspace.dialog.indeterminateProgressBar({title:g.pleaseWait+"..."}),f=a.store,d=a.selection.getFirstSelected(),h=d.id==buildspace.constants.GRID_LAST_ROW&&0<b?a.getItem(b-1).id:0;c.show();dojo.xhrPost({url:this.pasteUrl,
content:{type:a.pasteOp,target_id:d.id,id:a.selectedItem.id,prev_item_id:h,_csrf_token:a.selectedItem._csrf_token},handleAs:"json",load:function(d){var e=[];if(d.success)switch(a.pasteOp){case "cut":f.fetchItemByIdentity({identity:d.data.id,onItem:function(c){c=a.getItemIndex(c);e.push(c);0<e.length&&a.rearranger.moveRows(e,b);a.selectAfterPaste(c>b?b:b-1,!0)}});break;case "copy":d=f.newItem(d.data),f.save(),d=a.getItemIndex(d),e.push(d),0<e.length&&(a.rearranger.moveRows(e,b),a.selectAfterPaste(b,
!1)),a.updateTotalBuildUp()}a.disableToolbarButtons(!1);a.pasteOp=null;e.length=0;c.hide()},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;c.hide()}})},selectAfterPaste:function(b,a){this.selection.clear();this.selectedItem=null;this.selection.setSelected(b,!0);a&&this.scrollToRow(0<b-3?b-3:b)},contextMenu:function(b){if(this.disableEditingMode)return!1;var a=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(b);var c={target:b.target,coords:b.keyCode!==
u.F10&&"pageX"in b?{x:b.pageX,y:b.pageY}:null},f=this.getItem(b.rowIndex);a&&f&&(this.selection.isSelected(b.rowIndex)||b.rowNode&&v.hasClass(b.rowNode,"dojoxGridRowbar"))&&(a._openMyself(c),t.stop(b))},contextMenuItems:function(b){var a=this.getItem(b.rowIndex);a&&0<a.id&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItems")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:g.copy,iconClass:"icon-16-container icon-16-copy",
onClick:dojo.hitch(this,"copyItems")})));this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:g.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(this,"pasteItem",b.rowIndex),disabled:this.selectedItem?!1:!0}));this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow",b.rowIndex)}));a&&0<a.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:g.deleteRow,iconClass:"icon-16-container icon-16-delete",
onClick:dojo.hitch(this,"deleteRow",b.rowIndex)}))},disableToolbarButtons:function(b,a){var c=dijit.byId("builUpGrid-"+this.billColumnSettingId+"_"+this.BillItem.id+"AddRow-button"),f=dijit.byId("builUpGrid-"+this.billColumnSettingId+"_"+this.BillItem.id+"DeleteRow-button");c._setDisabledAttr(b);f._setDisabledAttr(b);if(b&&a instanceof Array){var d=this;dojo.forEach(a,function(a){dijit.byId("builUpGrid-"+d.billColumnSettingId+"_"+d.BillItem.id+a+"Row-button")._setDisabledAttr(!1)})}},updateTotalBuildUp:function(){this.buildUpSummaryWidget.refreshTotalQuantity()}});
return n("buildspace.apps.ProjectBuilder.BillManager.BuildUpQuantityGrid",dijit.layout.BorderContainer,{style:"padding:0;margin:0;width:100%;height:100%;border:none!important;",gutters:!1,billColumnSettingId:null,type:null,BillItem:null,disableEditingMode:!1,gridOpts:{},postCreate:function(){this.inherited(arguments);p.mixin(this.gridOpts,{disableEditingMode:this.disableEditingMode,billColumnSettingId:this.billColumnSettingId,BillItem:this.BillItem,region:"center",type:this.type});var b=this.grid=
new x(this.gridOpts);if(!this.disableEditingMode){var a=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});a.addChild(new dijit.form.Button({id:"builUpGrid-"+this.billColumnSettingId+"_"+this.BillItem.id+"AddRow-button",label:g.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.addRow(b.selection.selectedIndex)}}));a.addChild(new dijit.ToolbarSeparator);a.addChild(new dijit.form.Button({id:"builUpGrid-"+
this.billColumnSettingId+"_"+this.BillItem.id+"DeleteRow-button",label:g.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.deleteRow(b.selection.selectedIndex)}}));this.addChild(a)}this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))}})});
