define("buildspace/apps/ProjectBuilder/BillManager/importProjectItemDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/aspect buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/Filter dojo/i18n!buildspace/nls/BillManagerImport".split(" "),function(l,p,m,x,y,z,t,u,q,h,A,v,d){var w=l("buildspace.apps.ProjectBuilder.BillManager.ImportProjectItemGrid",dojox.grid.EnhancedGrid,
{type:null,selectedItem:null,billId:0,billElementId:0,dialogWidget:null,_csrf_token:null,billGrid:null,style:"border-top:none;",currentBQAddendumId:-1,constructor:function(a){this.itemIds=[];this.connects=[];"tree"==a.type&&(this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}});this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);this.on("RowClick",function(b){b=a.getItem(b.rowIndex);"tree"==a.type&&
(b&&0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0))});"tree"==this.type&&(this._connects.push(m.connect(this,"onCellClick",function(b){a.selectTree(b)})),this._connects.push(m.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)})))},dodblclick:function(a){this.onRowDblClick(a)},disableToolbarButtons:function(a){dijit.byId("ImportProjectItemGrid-"+this.billElementId+"_"+this.billId+"ImportWithRate-button")._setDisabledAttr(a);dijit.byId("ImportProjectItemGrid-"+
this.billElementId+"_"+this.billId+"ImportWithoutRate-button")._setDisabledAttr(a)},"import":function(a){var b=this,c=b.billGrid,e=b.itemIds,f=-1,g=null;if(0<e.length){var r=c.getItemIndex(this.selectedItem);0<r&&(f=r-1);-1<f&&(g=c.getItem(f).id);var n=buildspace.dialog.indeterminateProgressBar({title:d.importingData+". "+d.pleaseWait+"..."});n.show();dojo.xhrPost({url:"billManagerImport/importBillProjectItems",content:{id:g,element_id:b.billElementId,ids:[e],with_rate:a,currentBQAddendumId:b.currentBQAddendumId,
_csrf_token:b._csrf_token},handleAs:"json",load:function(a){if(a.success){c.store.save();c.store.close();var d=q.after(c,"_onFetchComplete",function(){d.remove();-1<c.selection.selectedIndex&&this.scrollToRow(c.selection.selectedIndex);this.disableToolbarButtons(!1)});c.sort()}b.itemIds=[];n.hide();b.dialogWidget.hide()},error:function(a){b.itemIds=[];c.selection.clear();c.disableToolbarButtons(!0);n.hide();b.dialogWidget.hide()}})}},selectTree:function(a){var b=a.rowIndex;a=this.selection.selected[b];
(b=this.getItem(b))&&this.pushItemIdIntoGridArray(b,a)},pushItemIdIntoGridArray:function(a,b){var c=dojo.indexOf(this.itemIds,a.id[0]);b?-1==c&&this.itemIds.push(a.id[0]):-1!=c&&this.itemIds.splice(c,1)},toggleAllSelection:function(a){var b=this,c=b.selection;a?(c.selectRange(0,b.rowCount-1),b.itemIds=[],b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id&&b.itemIds.push(a.id[0])})}})):(c.deselectAll(),b.itemIds=[])},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,
m.disconnect);delete this._connects}}),k=l("buildspace.apps.ProjectBuilder.BillManager.ImportProjectItemGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,billId:0,billElementId:0,gridOpts:{},postCreate:function(){this.inherited(arguments);p.mixin(this.gridOpts,{type:this.type,billId:this.billId,billElementId:this.billElementId,region:"center"});var a=this.grid=new w(this.gridOpts);this.addChild(new v({region:"top",editableGrid:!1,
grid:a,filterFields:this.filterFields}));if("tree"==this.type){var b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({id:"ImportProjectItemGrid-"+this.billElementId+"_"+this.billId+"ImportWithRate-button",label:d.importWithRate,iconClass:"icon-16-container icon-16-import",onClick:function(){a["import"](!0)}}));b.addChild(new dijit.ToolbarSeparator);b.addChild(new dijit.form.Button({id:"ImportProjectItemGrid-"+this.billElementId+
"_"+this.billId+"ImportWithoutRate-button",label:d.importWithoutRate,iconClass:"icon-16-container icon-16-import",onClick:function(){a["import"](!1)}}));this.addChild(b)}this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));if(b=dijit.byId("billManager-item_import_"+this.billId+"_"+this.billElementId+"-stackContainer")){var c=document.createElement("div"),c=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),id:this.pageId,
executeScripts:!0},c);b.addChild(c);c.set("content",this);p.mixin(c,{grid:a});b.selectChild(this.pageId)}}});return l("buildspace.apps.ProjectBuilder.BillManager.ImportProjectItemDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:d.importFromItemProject,selectedItem:null,billId:0,elementId:0,billGrid:null,currentBQAddendumId:-1,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",
margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==t.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=this,b=new dijit.layout.BorderContainer({style:"padding:0px;width:980px;height:500px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",
style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var e=new h,f=dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImport/getProjectList"}),e=new k({stackContainerTitle:d.projects,pageId:"import-page_project-"+this.billId+"_"+this.elementId,billId:this.billId,billElementId:this.elementId,filterFields:[{title:d.title},{country:d.country},{state:d.state}],gridOpts:{store:f,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",filterable:!1,formatter:e.rowCountCellFormatter},
{name:d.title,field:"title",width:"auto"},{name:d.country,field:"country",width:"120px",styles:"text-align: center;"},{name:d.state,field:"state",width:"120px",styles:"text-align: center;"},{name:d.created_at,field:"created_at",width:"120px",styles:"text-align: center;",filterable:!1}],onRowDblClick:function(b){b=this.getItem(b.rowIndex);0<b.id&&null!==b.title[0]&&a.createBillGrid(b)},currentBQAddendumId:a.currentBQAddendumId}}),e=this.makeGridContainer(e,d.projects);b.addChild(c);b.addChild(e);return b},
createBillGrid:function(a){var b=this,c=h(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImport/getBillList/id/"+a.id});new k({stackContainerTitle:a.title,pageId:"import-page_bill-"+this.billId+"_"+this.elementId,billId:b.billId,billElementId:b.elementId,filterFields:[{title:d.title}],gridOpts:{store:e,dialogWidget:b,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.title,field:"title",width:"auto"}],onRowDblClick:function(a){a=
this.getItem(a.rowIndex);0<a.id&&null!==a.title[0]&&b.createElementGrid(a)},currentBQAddendumId:b.currentBQAddendumId}})},createElementGrid:function(a){var b=this,c=h(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImport/getBillElementList/id/"+a.id});new k({stackContainerTitle:a.title,pageId:"import-page_element-"+this.billId+"_"+this.elementId,billId:b.billId,billElementId:b.elementId,filterFields:[{description:d.description}],gridOpts:{store:e,dialogWidget:b,structure:[{name:"No.",
field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.description[0]&&b.createItemGrid(a)},currentBQAddendumId:b.currentBQAddendumId}})},createItemGrid:function(a){var b=h(),c=new dojo.data.ItemFileWriteStore({url:"billManagerImport/getBillItemList/id/"+a.id});new k({stackContainerTitle:a.description,pageId:"import-page_item-"+this.billId+"_"+
this.elementId,billId:this.billId,billElementId:this.elementId,type:"tree",filterFields:[{description:d.description},{uom_symbol:d.unit},{"rate-final_value":d.rate}],gridOpts:{store:c,escapeHTMLInData:!1,dialogWidget:this,selectedItem:this.selectedItem,billGrid:this.billGrid,_csrf_token:a._csrf_token,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:b.treeCellFormatter},{name:d.type,
field:"type",width:"70px",styles:"text-align:center;",formatter:b.typeCellFormatter},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:b.unitIdCellFormatter},{name:d.rate,field:"rate-value",width:"80px",styles:"text-align:right;",formatter:b.formulaCurrencyCellFormatter}],currentBQAddendumId:this.currentBQAddendumId}})},makeGridContainer:function(a,b){var c=this.billId+"_"+this.elementId,d=dijit.byId("billManager-item_import_"+c+"-stackContainer");d&&dijit.byId("billManager-item_import_"+
c+"-stackContainer").destroyRecursive();d=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"billManager-item_import_"+c+"-stackContainer"});d.addChild(new dijit.layout.ContentPane({title:b,content:a,grid:a.grid}));var f=new dijit.layout.StackController({region:"top",containerId:"billManager-item_import_"+c+"-stackContainer"}),f=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:f}),g=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",
gutters:!1,region:"center"});g.addChild(d);g.addChild(f);dojo.subscribe("billManager-item_import_"+c+"-stackContainer-selectChild","",function(a){var b=dijit.byId("billManager-item_import_"+c+"-stackContainer");if(b){var d=b.getChildren(),e=dojo.indexOf(d,a);if(d.length>e+1){a.grid.store.save();a.grid.store.close();var f=q.after(a.grid,"_onFetchComplete",function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,b.removeChild(d[e]),d[e].destroyRecursive(!0)}});
return g}})});
