define("buildspace/apps/ProjectBuilder/BillManager/importItemDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/aspect buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!buildspace/nls/BillManagerImport buildspace/widget/grid/Filter".split(" "),function(h,p,k,x,y,z,t,u,q,l,A,d,v){var w=h("buildspace.apps.ProjectBuilder.BillManager.ImportItemGrid",dojox.grid.EnhancedGrid,{type:null,selectedItem:null,
billId:0,billElementId:0,dialogWidget:null,_csrf_token:null,billGrid:null,style:"border-top:none;",currentBQAddendumId:-1,constructor:function(b){this.itemIds=[];this.connects=[];"tree"==b.type&&(this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}});this.inherited(arguments)},canSort:function(b){return!1},postCreate:function(){var b=this;this.inherited(arguments);this.on("RowClick",function(a){a=b.getItem(a.rowIndex);"tree"==b.type&&(a&&0<a.id?b.disableToolbarButtons(!1):
b.disableToolbarButtons(!0))});"tree"==this.type&&(this._connects.push(k.connect(this,"onCellClick",function(a){b.selectTree(a)})),this._connects.push(k.connect(this.rowSelectCell,"toggleAllSelection",function(a){b.toggleAllSelection(a)})))},dodblclick:function(b){this.onRowDblClick(b)},disableToolbarButtons:function(b){dijit.byId("ImportItemGrid-"+this.billElementId+"_"+this.billId+"ImportWithRate-button")._setDisabledAttr(b);dijit.byId("ImportItemGrid-"+this.billElementId+"_"+this.billId+"ImportWithoutRate-button")._setDisabledAttr(b)},
importItem:function(b){var a=this,c=a.billGrid,e=a.itemIds,f=-1,g=null;if(0<e.length){var r=c.getItemIndex(this.selectedItem);0<r&&(f=r-1);-1<f&&(g=c.getItem(f).id);var m=buildspace.dialog.indeterminateProgressBar({title:d.importingData+". "+d.pleaseWait+"..."});m.show();dojo.xhrPost({url:"billManagerImport/importBillItems",content:{id:g,element_id:a.billElementId,ids:[e],with_rate:b,currentBQAddendumId:a.currentBQAddendumId,_csrf_token:a._csrf_token},handleAs:"json",load:function(b){if(b.success){c.store.save();
c.store.close();var f=q.after(c,"_onFetchComplete",function(){f.remove();-1<c.selection.selectedIndex&&this.scrollToRow(c.selection.selectedIndex);this.disableToolbarButtons(!1)});c.sort()}a.itemIds=[];m.hide();a.dialogWidget.hide()},error:function(b){a.itemIds=[];c.selection.clear();c.disableToolbarButtons(!0);m.hide();a.dialogWidget.hide()}})}},selectTree:function(b){var a=b.rowIndex;b=this.selection.selected[a];(a=this.getItem(a))&&this.pushItemIdIntoGridArray(a,b)},pushItemIdIntoGridArray:function(b,
a){var c=dojo.indexOf(this.itemIds,b.id[0]);a?-1==c&&this.itemIds.push(b.id[0]):-1!=c&&this.itemIds.splice(c,1)},toggleAllSelection:function(b){var a=this,c=a.selection;b?(c.selectRange(0,a.rowCount-1),a.itemIds=[],a.store.fetch({onComplete:function(b){dojo.forEach(b,function(b,c){0<b.id&&a.itemIds.push(b.id[0])})}})):(c.deselectAll(),a.itemIds=[])},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,k.disconnect);delete this._connects}}),n=h("buildspace.apps.ProjectBuilder.BillManager.ImportItemGridContainer",
dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,billId:0,billElementId:0,gridOpts:{},postCreate:function(){this.inherited(arguments);p.mixin(this.gridOpts,{type:this.type,billId:this.billId,billElementId:this.billElementId,region:"center"});var b=this.grid=new w(this.gridOpts),a=new v({grid:b,region:"top",filterFields:this.filterFields});this.addChild(a);"tree"==this.type&&(a=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"}),
a.addChild(new dijit.form.Button({id:"ImportItemGrid-"+this.billElementId+"_"+this.billId+"ImportWithRate-button",label:d.importWithRate,iconClass:"icon-16-container icon-16-import",onClick:function(){b.importItem(!0)}})),a.addChild(new dijit.ToolbarSeparator),a.addChild(new dijit.form.Button({id:"ImportItemGrid-"+this.billElementId+"_"+this.billId+"ImportWithoutRate-button",label:d.importWithoutRate,iconClass:"icon-16-container icon-16-import",onClick:function(){b.importItem(!1)}})),this.addChild(a));
this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}));if(a=dijit.byId("billManager-item_import_"+this.billId+"_"+this.billElementId+"-stackContainer")){var c=document.createElement("div"),c=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,45),content:this,id:this.pageId,executeScripts:!0},c);a.addChild(c);p.mixin(c,{grid:b});a.selectChild(this.pageId)}}});return h("buildspace.apps.ProjectBuilder.BillManager.ImportItemDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",title:d.importFromItemLibrary,selectedItem:null,billId:0,elementId:0,billGrid:null,currentBQAddendumId:-1,buildRendering:function(){var b=this.createContent();b.startup();this.content=b;this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(b){b.keyCode==t.ESCAPE&&dojo.stopEvent(b)},onHide:function(){this.destroyRecursive()},
createContent:function(){var b=this,a=new dijit.layout.BorderContainer({style:"padding:0px;width:950px;height:500px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var e=new l,f=dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImport/getLibraryList"}),e=new n({stackContainerTitle:d.libraries,
pageId:"import-page_library-"+this.billId+"_"+this.elementId,billId:this.billId,filterFields:[{name:"Title"}],billElementId:this.elementId,gridOpts:{store:f,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:e.rowCountCellFormatter},{name:d.title,field:"name",width:"auto"}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.name[0]&&b.createElementGrid(a)},currentBQAddendumId:b.currentBQAddendumId}}),e=this.makeGridContainer(e,d.libraries);a.addChild(c);
a.addChild(e);return a},createElementGrid:function(b){var a=this,c=l(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImport/getElementList/id/"+b.id});new n({stackContainerTitle:b.name,pageId:"import-page_element-"+this.billId+"_"+this.elementId,billId:a.billId,billElementId:a.elementId,filterFields:[{description:"Description"}],gridOpts:{store:e,dialogWidget:a,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.description,
field:"description",width:"auto"}],onRowDblClick:function(b){b=this.getItem(b.rowIndex);0<b.id&&null!==b.description[0]&&a.createItemGrid(b)},currentBQAddendumId:a.currentBQAddendumId}})},createItemGrid:function(b){var a=l(),c=new dojo.data.ItemFileWriteStore({url:"billManagerImport/getItemList/id/"+b.id});new n({stackContainerTitle:b.description,pageId:"import-page_item-"+this.billId+"_"+this.elementId,billId:this.billId,billElementId:this.elementId,filterFields:[{description:"Description"},{uom_symbol:"Unit"},
{"rate-final_value":"Rate"}],type:"tree",gridOpts:{escapeHTMLInData:!1,store:c,dialogWidget:this,selectedItem:this.selectedItem,billGrid:this.billGrid,_csrf_token:b._csrf_token,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:a.treeCellFormatter},{name:d.type,field:"type",width:"70px",styles:"text-align:center;",formatter:a.typeCellFormatter},{name:d.unit,field:"uom_id",width:"70px",
styles:"text-align:center;",formatter:a.unitIdCellFormatter},{name:d.rate,field:"rate-value",width:"80px",styles:"text-align:right;",formatter:a.formulaCurrencyCellFormatter}],currentBQAddendumId:this.currentBQAddendumId}})},makeGridContainer:function(b,a){var c=this.billId+"_"+this.elementId,e=dijit.byId("billManager-item_import_"+c+"-stackContainer");e&&dijit.byId("billManager-item_import_"+c+"-stackContainer").destroyRecursive();e=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",
region:"center",id:"billManager-item_import_"+c+"-stackContainer"});e.addChild(new dijit.layout.ContentPane({title:a,content:b,grid:b.grid}));var d=new dijit.layout.StackController({region:"top",containerId:"billManager-item_import_"+c+"-stackContainer"}),d=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:d}),g=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});g.addChild(e);
g.addChild(d);dojo.subscribe("billManager-item_import_"+c+"-stackContainer-selectChild","",function(a){var b=dijit.byId("billManager-item_import_"+c+"-stackContainer");if(b){var d=b.getChildren(),e=dojo.indexOf(d,a);if(d.length>e+1){a.grid.store.save();a.grid.store.close();var f=q.after(a.grid,"_onFetchComplete",function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,b.removeChild(d[e]),d[e].destroyRecursive(!0)}});return g}})});
