define("buildspace/apps/ProjectBuilder/BillManager/ImportQtyDialog","dojo/_base/declare dojo/_base/lang dojo/dom dojo/keys dojo/dom-style dojo/aspect dojo/number buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/BillManagerImport buildspace/widget/grid/Filter".split(" "),function(h,k,z,p,q,l,m,f,d,r){var u=h("buildspace.apps.ProjectBuilder.BillManager.ImportQtyGrid",dojox.grid.EnhancedGrid,{type:null,billId:0,billItem:null,qtyType:"qty",targetBillColumnSettingId:0,dialogWidget:null,
billGrid:null,style:"border-top:none;",constructor:function(a){this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){var a=this;this.inherited(arguments);if("tree"==this.type)this.on("RowClick",function(b){var c=b.cell.field;b=this.getItem(b.rowIndex);("quantity_import"==c||"quantity_remeasurement_import"==c)&&0<b.id&&null!==b.description[0]&&b.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&b.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&b.type!=
buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&a.importQty(b,c)},!0)},dodblclick:function(a){this.onRowDblClick(a)},importQty:function(a,b){var c=this,e=buildspace.dialog.indeterminateProgressBar({title:d.savingData+". "+d.pleaseWait+"..."});e.show();dojo.xhrPost({url:"billManagerImportQty/import",content:{tid:c.billItem.id,type:c.qtyType,tcid:c.targetBillColumnSettingId,sid:a.id,rid:a[b],_csrf_token:a._csrf_token},handleAs:"json",load:function(a){if(a.success){a=c.billGrid.store;a.save();
a.close();var b=l.after(c.billGrid,"_onFetchComplete",function(){b.remove();this.scrollToRow(this.selection.selectedIndex)});c.billGrid.sort()}e.hide();c.dialogWidget&&c.dialogWidget.hide()},error:function(a){e.hide();c.dialogWidget&&c.dialogWidget.hide()}})}}),g=h("buildspace.apps.ProjectBuilder.BillManager.ImportQtyGridContainer",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0px;width:100%;height:100%;",gutters:!1,billId:0,billItem:null,billGrid:null,qtyType:"qty",targetBillColumnSettingId:0,
gridOpts:{},postCreate:function(){this.inherited(arguments);k.mixin(this.gridOpts,{type:this.type,qtyType:this.qtyType,billId:this.billId,billItem:this.billItem,billGrid:this.billGrid,targetBillColumnSettingId:this.targetBillColumnSettingId,region:"center"});var a=this.grid=new u(this.gridOpts);this.addChild(new r({grid:this.grid,region:"top",filterFields:this.filterFields}));this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));var b=dijit.byId("billManager-qty_import_"+
this.billId+"_"+this.billItem.id+"-stackContainer");if(b){var c=document.createElement("div"),c=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,25),id:this.pageId,executeScripts:!0},c);b.addChild(c);c.set("content",this);k.mixin(c,{grid:a});b.selectChild(this.pageId)}}}),v=function(a,b){return 0<a?a:""},w=function(a,b){var c=this.grid.getItem(b),d=16*c.level;a=null==a?"&nbsp":a;c.type<buildspace.constants.TYPE_BILL&&(a="<b>"+a+"</b>");return'<div class="treeNode" style="padding-left:'+
d+'px;"><div class="treeContent">'+a+"&nbsp;</div></div>"},x=function(a,b){return buildspace.getBillTypeText(a)},n=function(a,b,c){a=this.grid.getItem(b);b=m.parse(a["quantity_per_unit-final_value"]);if(0<a.id&&0!=b&&!isNaN(b)&&null!=b&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID)return'<a href="#" onclick="return false;">'+d["import"]+"</a>";c.customClasses.push("disable-cell");
return"&nbsp;"},y=function(a,b,c){a=this.grid.getItem(b);b=m.parse(a["quantity_per_unit_remeasurement-final_value"]);if(0<a.id&&0!=b&&!isNaN(b)&&null!=b&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&a.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID)return'<a href="#" onclick="return false;">'+d["import"]+"</a>";c.customClasses.push("disable-cell");return"&nbsp;"};return h("buildspace.apps.ProjectBuilder.BillManager.ImportQtyDialog",
dijit.Dialog,{style:"padding:0px;margin:0px;",title:d.importQtyFromProjects,billItem:null,billId:0,billGrid:null,qtyType:"qty",targetBillColumnSettingId:0,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){q.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==p.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},
createContent:function(){var a=this,b=new dijit.layout.BorderContainer({style:"padding:0px;width:950px;height:500px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var e=new f,t=dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportQty/getProjects"}),e=new g({stackContainerTitle:d.projects,
pageId:"importQty-page_project-"+this.billId+"_"+this.billItem.id,billId:this.billId,billItem:this.billItem,filterFields:[{title:"Title",state:"State",country:"Country"}],gridOpts:{store:t,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:e.rowCountCellFormatter},{name:d.title,field:"title",width:"auto"},{name:d.country,field:"country",width:"120px",styles:"text-align:center;"},{name:d.state,field:"state",width:"120px",styles:"text-align:center;"}],onRowDblClick:function(b){b=
this.getItem(b.rowIndex);0<b.id&&null!==b.title[0]&&a.createBillGrid(b)}}}),e=this.makeGridContainer(e,d.projects);b.addChild(c);b.addChild(e);return b},createBillGrid:function(a){var b=this,c=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportQty/getBillList/pid/"+a.id});new g({stackContainerTitle:a.title,pageId:"importQty-page_bill-"+this.billId+"_"+this.billItem.id,billId:b.billId,billItem:b.billItem,filterFields:[{title:"Title"}],gridOpts:{store:c,dialogWidget:b,structure:[{name:"No.",
field:"count",width:"40px",styles:"text-align:center;",formatter:v},{name:d.title,field:"title",width:"auto",formatter:w},{name:d.billType,field:"bill_type",width:"180px",styles:"text-align:center;",formatter:x}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.title[0]&&b.createBillColumnSettingGrid(a)}}})},createBillColumnSettingGrid:function(a){var b=this,c=f(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportQty/getBillColumnSettingList/bid/"+a.id});
new g({stackContainerTitle:a.title,pageId:"importQty-page_bill_column_setting-"+this.billId+"_"+this.billItem.id,billId:b.billId,billItem:b.billItem,filterFields:[{name:"Name"}],gridOpts:{store:e,dialogWidget:b,structure:[{name:"No.",field:"count",width:"40px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.name,field:"name",width:"auto"}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.name[0]&&b.createElementGrid(a)}}})},createElementGrid:function(a){var b=
this,c=f(),e=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"billManagerImportQty/getElementList/cid/"+a.id});new g({stackContainerTitle:a.name,pageId:"import-page_element-"+this.billId+"_"+this.billItem.id,billId:b.billId,billItem:b.billItem,filterFields:[{description:"Description"}],gridOpts:{store:e,dialogWidget:b,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"}],onRowDblClick:function(c){c=
this.getItem(c.rowIndex);0<c.id&&null!==c.description[0]&&b.createItemGrid(c,a)}}})},createItemGrid:function(a,b){var c=f(),e=new dojo.data.ItemFileWriteStore({url:"billManagerImportQty/getItemList/eid/"+a.id+"/cid/"+b.id});new g({stackContainerTitle:a.description,pageId:"import-page_item-"+this.billId+"_"+this.billItem.id,billId:this.billId,billItem:this.billItem,billGrid:this.billGrid,qtyType:this.qtyType,targetBillColumnSettingId:this.targetBillColumnSettingId,filterFields:[{description:"Description"},
{uom_symbol:"Unit"}],type:"tree",gridOpts:{store:e,escapeHTMLInData:!1,dialogWidget:this,billGrid:this.billGrid,structure:b.remeasurement_quantity_enabled[0]?[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:c.treeCellFormatter},{name:d.type,field:"type",width:"70px",styles:"text-align:center;",formatter:c.typeCellFormatter},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",
formatter:c.unitIdCellFormatter},{name:d.qty+"/"+d.unit,field:"quantity_per_unit-value",width:"80px",styles:"text-align:right;",formatter:c.formulaCurrencyCellFormatter},{name:d["import"]+" "+d.qty,field:"quantity_import",width:"80px",styles:"text-align:center;",formatter:n},{name:d.qty+"/"+d.unit+" (2)",field:"quantity_per_unit_remeasurement-value",width:"80px",styles:"text-align:right;",formatter:c.formulaCurrencyCellFormatter},{name:d["import"]+" "+d.qty+" 2",field:"quantity_remeasurement_import",
width:"80px",styles:"text-align:center;",formatter:y}]:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:d.description,field:"description",width:"auto",formatter:c.treeCellFormatter},{name:d.type,field:"type",width:"70px",styles:"text-align:center;",formatter:c.typeCellFormatter},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:c.unitIdCellFormatter},{name:d.qty+"/"+d.unit,field:"quantity_per_unit-value",width:"80px",
styles:"text-align:right;",formatter:c.formulaCurrencyCellFormatter},{name:d["import"]+" "+d.qty,field:"quantity_import",width:"80px",styles:"text-align:center;",formatter:n}]}})},makeGridContainer:function(a,b){var c=this.billId+"_"+this.billItem.id,d=dijit.byId("billManager-qty_import_"+c+"-stackContainer");d&&dijit.byId("billManager-qty_import_"+c+"-stackContainer").destroyRecursive();d=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"billManager-qty_import_"+
c+"-stackContainer"});d.addChild(new dijit.layout.ContentPane({title:b,content:a,grid:a.grid}));var g=new dijit.layout.StackController({region:"top",containerId:"billManager-qty_import_"+c+"-stackContainer"}),f=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});f.addChild(d);f.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:g}));dojo.subscribe("billManager-qty_import_"+
c+"-stackContainer-selectChild","",function(a){var b=dijit.byId("billManager-qty_import_"+c+"-stackContainer");if(b){var d=b.getChildren(),e=dojo.indexOf(d,a);if(d.length>e+1){a.grid.store.save();a.grid.store.close();var f=l.after(a.grid,"_onFetchComplete",function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,b.removeChild(d[e]),d[e].destroyRecursive(!0)}});return f}})});
