define("buildspace/apps/ProjectBuilder/BillManager/ScheduleOfQuantityGrid","dojo/_base/declare dojo/_base/lang dojo/when dojo/_base/connect dojo/_base/event dojo/number dojo/keys dojo/aspect dojo/_base/html dijit/focus dojo/dom-style dijit/TooltipDialog dijit/popup dojox/grid/EnhancedGrid buildspace/apps/ScheduleOfQuantity/BuildUpQuantityGrid buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(l,v,w,m,x,p,y,z,A,q,B,r,f,C,t,u,d){var D=l("buildspace.apps.ProjectBuilder.BillManager.ScheduleOfQuantityTooltipDialog",
r,{itemId:-1,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){B.set(this.containerNode,{padding:"0px",margin:"0px"});this.inherited(arguments)},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0;width:580px;height:120px;",gutters:!1}),b=u();a.addChild(new dijit.layout.ContentPane({content:dojox.grid.DataGrid({escapeHTMLInData:!1,store:new dojo.data.ItemFileReadStore({url:"billBuildUpQuantity/getScheduleOfQuantityInfo/id/"+
this.itemId}),structure:[{name:d.title,field:"title",width:"auto",formatter:b.treeCellFormatter}],rowSelector:"0px",style:"border:none!important;"}),style:"padding:0px;margin:0px;width:100%;height:100%;border:0px;",region:"center"}));return a}}),F=l("buildspace.apps.ProjectBuilder.BillManager.ScheduleOfQuantityGrid",C,{type:null,style:"border:none!important;",rowSelector:"0px",region:"center",billColumnSettingId:null,BillItem:null,keepSelection:!0,qtyType:null,stackContainerId:null,buildUpSummaryWidget:null,
disableEditingMode:!1,constructor:function(a){this.connects=[]},canSort:function(a){return!1},canEdit:function(a,b){return!1},postCreate:function(){var a=this;this.inherited(arguments);var b;this.disableEditingMode||(this.on("RowContextMenu",function(b){a.selection.clear();var c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b);c&&0<c.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)},!0),this.on("RowClick",function(b){(b=a.getItem(b.rowIndex))&&0<b.id?a.disableToolbarButtons(!1):
a.disableToolbarButtons(!0)}));this._connects.push(m.connect(this,"onCellMouseOver",function(e){var c=a.getItem(e.rowIndex);if("description"==e.cell.field&&0<c.id&&0==c.level[0])b=new D({itemId:c.id[0],onMouseLeave:function(){f.close(b)}}),f.open({popup:b,around:e.cellNode});else{var d=e.rowIndex,n=e.cell.field.replace("-value","");"undefined"!==typeof c[n+"-has_formula"]&&c[n+"-has_formula"][0]&&(c=c[n+"-value"][0],c=this.formulatedColumn.convertItemIdToRowIndex(c,d),null===b&&(b=new r({content:c,
onMouseLeave:function(){f.close(b)}}),f.open({popup:b,around:e.cellNode})))}}));this._connects.push(m.connect(this,"onCellMouseOut",function(a){void 0!==b&&f.close(b)}))},deleteRow:function(a){var b=this,e=b.getItem(a),c=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."});q.curNode.blur();q.curNode=null;c.show();var g={url:"billBuildUpQuantity/scheduleOfQuantityDelete",content:{id:e.id,bid:this.BillItem.id,bcid:this.billColumnSettingId,type:this.qtyType,_csrf_token:e._csrf_token},
handleAs:"json",load:function(d){if(d.success){b.store.save();b.store.close();b.sort();var e=z.after(b,"_onFetchComplete",function(){e.remove();a=a>b.store._arrayOfAllItems.length?0:a;this.scrollToRow(a)});b.updateTotalBuildUp()}c.hide();b.selection.clear();b.disableToolbarButtons(!0)},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);c.hide()}};new buildspace.dialog.confirm(d.unlinkScheduleOfQuantityTitle,d.unlinkScheduleOfQuantityMsg,80,320,function(){dojo.xhrPost(g)},function(){c.hide()})},
contextMenu:function(a){if(this.disableEditingMode)return!1;var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var d={target:a.target,coords:a.keyCode!==y.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:null},c=this.getItem(a.rowIndex);b&&c&&0<c.id&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&A.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(d),x.stop(a))},onRowDblClick:function(a){this.inherited(arguments);var b=this,e=a.cell.field,c=this.getItem(a.rowIndex);if("quantity-value"==
e&&0<c.id&&c.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&c["quantity-has_build_up"][0]&&0!=c["quantity-final_value"][0]){var e=dojo.xhrGet({url:"billBuildUpQuantity/getDimensionColumnStructure",content:{uom_id:c.uom_id[0]},handleAs:"json"}),g=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});g.show();e.then(function(a){b.createBuildUpQuantityContainer(c,a);g.hide()})}},createBuildUpQuantityContainer:function(a,b){var e=this,c=new dijit.layout.BorderContainer({style:"padding:0;margin:0;width:100%;height:100%;border:none!important;outline:none;",
gutters:!1}),g=new dijit.layout.AccordionContainer({id:"acc_"+this.BillItem.id+"_"+a.id+"-container",region:"center",style:"padding:0;margin:0;width:100%;height:100%;border:none;outline:none;"}),f=dojo.xhrGet({url:"scheduleOfQuantity/hasImportedItems/id/"+a.id,handleAs:"json"}),h=new u;try{var k=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:h.rowCountCellFormatter},{name:d.description,field:"description",width:"auto"},{name:d.factor,field:"factor-value",width:"100px",styles:"text-align:right;",
formatter:h.formulaNumberCellFormatter}];dojo.forEach(b,function(a){k.push({name:a.title,field:a.field_name,width:"100px",styles:"text-align:right;",formatter:h.formulaNumberCellFormatter})});k.push({name:d.total,field:"total",width:"100px",styles:"text-align:right;",formatter:h.numberCellFormatter});k.push({name:d.sign,field:"sign",width:"70px",styles:"text-align:center;",formatter:h.signCellFormatter});w(f,function(b){g.addChild(new dijit.layout.ContentPane({title:d.manualItems+'<span style="color:blue;float:right;">'+
p.format(a.editable_total,{places:2})+"&nbsp;"+a.uom_symbol+"</span>",style:"padding:0;border:none!important;",doLayout:!1,id:"accPane-SOQManual_"+a.id,content:new t({type:"manual",scheduleOfQuantityItem:a,gridOpts:{editable:!1,structure:k,store:new dojo.data.ItemFileWriteStore({url:"scheduleOfQuantity/getBuildUpItemList/id/"+a.id+"/t/m",clearOnClose:!0})}})}));b&&(b=new dijit.layout.ContentPane({title:d.importedItems+'<span style="color:blue;float:right;">'+p.format(a.non_editable_total,{places:2})+
"&nbsp;"+a.uom_symbol+"</span>",style:"padding:0;border:none!important;",doLayout:!1,id:"accPane-SOQImported_"+a.id,content:new t({type:"imported",scheduleOfQuantityItem:a,gridOpts:{editable:!1,structure:k,store:new dojo.data.ItemFileWriteStore({url:"scheduleOfQuantity/getBuildUpItemList/id/"+a.id+"/t/i",clearOnClose:!0})}})}),g.addChild(b),g.startup(),g.selectChild(b));c.addChild(g);if(b=dijit.byId(e.stackContainerId)){var f=document.createElement("div"),f=new dojox.layout.ContentPane({title:buildspace.truncateString(a.description,
28)+" ("+d.scheduleOfQuantity+" - "+a.uom_symbol+")",id:"SOQBuildUpQuantityPage-"+a.id,style:"padding:0;border:none!important;",content:c,executeScripts:!0},f);b.addChild(f);b.selectChild("SOQBuildUpQuantityPage-"+a.id)}})}catch(E){console.log(E)}},contextMenuItems:function(a){var b=this.getItem(a.rowIndex);b&&0<b.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,"deleteRow",a.rowIndex)}))},disableToolbarButtons:function(a){dijit.byId("SOQGrid-"+
this.billColumnSettingId+"_"+this.BillItem.id+"DeleteRow-button")._setDisabledAttr(a)},updateTotalBuildUp:function(){this.buildUpSummaryWidget.refreshTotalQuantity()},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,m.disconnect);delete this._connects}});return l("buildspace.apps.ProjectBuilder.BillManager.ScheduleOfQuantityGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,billColumnSettingId:null,type:null,BillItem:null,
disableEditingMode:!1,stackContainerId:null,gridOpts:{},postCreate:function(){this.inherited(arguments);v.mixin(this.gridOpts,{disableEditingMode:this.disableEditingMode,billColumnSettingId:this.billColumnSettingId,BillItem:this.BillItem,stackContainerId:this.stackContainerId,region:"center"});var a=this.grid=new F(this.gridOpts);if(!this.disableEditingMode){var b=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});b.addChild(new dijit.form.Button({id:"SOQGrid-"+this.billColumnSettingId+
"_"+this.BillItem.id+"DeleteRow-button",label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:function(){-1<a.selection.selectedIndex&&a.deleteRow(a.selection.selectedIndex)}}));this.addChild(b)}this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))}})});
