define("dojo/_base/declare dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/_base/lang dijit/form/Form dijit/form/Button dijit/form/ValidationTextBox dijit/form/TextBox dijit/form/DateTextBox dijit/Toolbar dijit/form/FilteringSelect dijit/form/Select ./grid dojo/text!./templates/businessTypeMaintenanceForm.html dojo/i18n!buildspace/nls/BusinessTypeMaintenance dojo/html dojo/dom dojo/on buildspace/widget/grid/cells/Formatter dojo/dom-construct dojo/dom-style dojo/domReady! dojox/layout/TableContainer dojox/form/Manager dijit/InlineEditBox buildspace/widget/forms/InlineEditBox".split(" "),
function(g,h,w,k,l,x,m,n,y,z,A,p,B,C,q,r,e,t,D,E,u,F,G){var v=g("buildspace.apps.BusinessTypeMaintenance.BusinessTypeUpdateForm",[m,h,k,l,dojox.form.manager._Mixin,dojox.form.manager._NodeMixin,dojox.form.manager._ValueMixin,dojox.form.manager._DisplayMixin],{baseClass:"buildspace-form",formValues:[],nls:e,isNew:!0,templateString:r,businessTypeMaintenanceGrid:null,postCreate:function(){this.inherited(arguments)},startup:function(){this.inherited(arguments);this.setFormValues(this.formValues)},submit:function(){var b=
this;this.businessTypeMaintenanceGrid.grid.store.save();var a=dojo.formToObject(this.id),c=buildspace.dialog.indeterminateProgressBar({title:e.savingData+". "+e.pleaseWait+"..."});this.validate()&&c.show().then(function(){dojo.xhrPost({url:"systemAdministration/businessTypeUpdate",content:a,handleAs:"json",load:function(d){dojo.query('[id^="company_business_type_error-"]').forEach(function(c){c.innerHTML=""});if(1==d.success&&b.businessTypeMaintenanceGrid){b.setFormValues(d.values);var a=dijit.byId("BusinessTypeMaintenance-stackContainer");
d=dijit.byId("BusinessTypeForm");a.removeChild(d);d.destroyRecursive();b.businessTypeMaintenanceGrid.refreshGrid()}else for(a in d=d.errors,d)b["company_business_type_error-"+a]&&t.set(b["company_business_type_error-"+a],d[a]);c.hide()},error:function(a){c.hide()}})})}});return g("buildspace.apps.BusinessTypeMaintenance.BusinessTypeMaintenanceFormContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,postCreate:function(){this.inherited(arguments);
var b=new u,a=dijit.byId("BusinessTypeMaintenance-stackContainer");a&&dijit.byId("BusinessTypeMaintenance-stackContainer").destroyRecursive();a=this.stackContainer=new dijit.layout.StackContainer({style:"width:100%;height:100%;",region:"center",id:"BusinessTypeMaintenance-stackContainer"});b=this.businessTypeMaintenanceGrid=new q({gridOpts:{store:new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"systemAdministration/getBusinessTypes"}),formContainer:this,structure:[{name:"No.",field:"id",width:"30px",
styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:e.name,field:"name",width:"auto"},{name:e.lastUpdated,field:"updated_at",width:"120px",styles:"text-align:center;"}],onRowDblClick:dojo.hitch(this,"editBusinessType")}});b=new dijit.layout.ContentPane({title:e.BusinessTypeList,content:b});a.addChild(b);b=new dijit.layout.StackController({region:"top",containerId:"BusinessTypeMaintenance-stackContainer"});b=new dijit.layout.ContentPane({style:"padding: 0px; overflow: hidden;",baseClass:"breadCrumbTrail",
region:"top",content:b});this.addChild(a);this.addChild(b);dojo.subscribe("BusinessTypeMaintenance-stackContainer-selectChild","",function(c){var a=dijit.byId("BusinessTypeMaintenance-stackContainer");if(a){var b=a.getChildren();c=dojo.indexOf(b,dijit.byId(c.id));for(c+=1;b.length>c;)a.removeChild(b[c]),b[c].destroyRecursive(!0),c+=1}})},makePane:function(b,a){var c=dijit.byId("BusinessTypeMaintenance-stackContainer"),d=new dijit.layout.ContentPane({title:b,id:"BusinessTypeForm",content:a});c.addChild(d);
c.selectChild(d)},FormContainer:function(b,a){var c=this.businessTypeUpdateForm=new v({region:"center",formValues:b,businessTypeMaintenanceGrid:this.businessTypeMaintenanceGrid}),d=new p({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});d.addChild(new n({label:e.save,iconClass:"icon-16-container icon-16-save",style:"outline:none!important;",onClick:dojo.hitch(c,"submit")}));var f=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",
gutters:!1,region:"center"});f.addChild(d);f.addChild(c);this.makePane(a?e.addBusinessType:e.editBusinessType,f)},addBusinessType:function(){var b=this,a=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});a.show().then(function(){dojo.xhrGet({url:"systemAdministration/getBusinessType",handleAs:"json"}).then(function(c){a.hide();b.FormContainer(c,!0)})})},editBusinessType:function(){if(-1<this.businessTypeMaintenanceGrid.grid.selection.selectedIndex){var b=this,a=this.businessTypeMaintenanceGrid.grid.getItem(this.businessTypeMaintenanceGrid.grid.selection.selectedIndex),
c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});a&&!isNaN(parseInt(a.id[0]))&&c.show().then(function(){dojo.xhrGet({url:"systemAdministration/getBusinessType/id/"+a.id,handleAs:"json"}).then(function(a){c.hide();b.FormContainer(a,!1)})})}},deleteBusinessType:function(b){if(-1<this.businessTypeMaintenanceGrid.grid.selection.selectedIndex){var a=this,c=a.businessTypeMaintenanceGrid.grid.getItem(this.businessTypeMaintenanceGrid.grid.selection.selectedIndex),d=buildspace.dialog.indeterminateProgressBar({title:e.deleting+
". "+e.pleaseWait+"..."});c&&!isNaN(parseInt(c.id[0]))&&dojo.xhrGet({url:"systemAdministration/businessTypePreDelete",content:{id:c.id},handleAs:"json"}).then(function(b){b.can_delete?buildspace.dialog.confirm(e.confirmationBusinessType,"<div>"+e.businessTypeDeleteDialogMsg+"<div>",75,320,function(){d.show().then(function(){dojo.xhrPost({url:"systemAdministration/deleteBusinessType",content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(b){b.success&&(a.businessTypeMaintenanceGrid.refreshGrid(),
a.businessTypeMaintenanceGrid.grid.disableToolbarButtons(!0));d.hide()},error:function(){d.hide()}})})}):buildspace.dialog.alert(e.itemCannotBeDeleted,e.cannotDeleteUsedElsewhere,75,320)})}}})});
