(function(){define("buildspace/apps/PurchaseOrder/AssignProjectGrid","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/on dojo/request dojo/html dojo/dom dojo/keys dojo/dom-style dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange dijit/layout/TabContainer dijit/layout/ContentPane dijit/layout/BorderContainer dijit/Toolbar dijit/form/Button buildspace/widget/grid/cells/Formatter dojo/i18n!../../nls/PurchaseOrder dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/Filter".split(" "),
function(f,v,w,x,l,y,z,m,n,g,A,B,p,C,D,q,r,h,t,d,E,u){var k;k=f("buildspace.apps.PurchaseOrder.PurchaseOrderProjectGrid",dojox.grid.EnhancedGrid,{style:"border:none;padding:0px;margin:0px;width:100%;height:100%;",selectionMode:"single",keepSelection:!0,rowSelector:"0px",region:"center",poForm:null,dialogContainer:null,plugins:{indirectSelection:{headerSelector:!1,width:"20px",styles:"text-align:center;"}},constructor:function(a){return this.rearranger=p(this,{})},canSort:function(a){return!1},noDataMessage:d.noPurchaseOrderProjectAvailableInGrid,
postCreate:function(){var a;this.inherited(arguments);a=this;this.connect(this.selection,"onDeselected",function(c){return a.disableToolbarButtons(!0)});return this.connect(this.selection,"onSelected",function(c){return(c=a.getItem(c))&&0<c.id[0]?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)})},select:function(){var a,c,b;b=this;a=this.getItem(this.selection.selectedIndex);c=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});c.show();return l.get("purchaseOrder/getCurrentProjectPurchaseOrderNoAndSupplierInfo",
{query:{projectStructureId:a.id},handleAs:"json"}).then(function(e){c.hide();dijit.byId("PO-form-button-save").set("disabled",!1);b.poForm.assignProjectTitle.innerHTML=a.title[0];b.poForm.projectSiteAddress.innerHTML=a.site_address[0];b.poForm.currentPurchaseOrderNo=e.poCount;b.poForm.countrySelect.set("value",a.region_id[0]);b.poForm.stateValue=a.subregion_id[0];b.poForm.poPrefix.set("value",e.poPrefix);e.poPrefix?b.poForm.poPrefix.set("readOnly",!0):b.poForm.poPrefix.set("readOnly",!1);g.set(b.poForm.projectStructureIdInput,
"value",a.id[0]);g.set(b.poForm.poCountInput,"value",e.poCount);b.poForm.updateFormView();0<e.poUsedSuppliers.length?b.poForm.showSupplierSelectContainer():b.poForm.hideSupplierSelectContainer();b.poForm.updateSupplierSelectStore(e.poUsedSuppliers);return b.dialogContainer.hide()},function(a){return c.hide()})},disableToolbarButtons:function(a,c){var b=dijit.byId("requestForQuotationProjectSelectButton");b&&b.set("disabled",a)}});return f("buildspace.apps.PurchaseOrder.PurchaseOrderProjectGridDialog",
dijit.Dialog,{title:d.poProjectSelectionGrid,style:"padding:0px;margin:0px;width:750px;height:450px;",poForm:null,buildRendering:function(){var a=this.createContent();this.content=a;a.startup();return this.inherited(arguments)},postCreate:function(){n.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},createContent:function(){var a,c,b,e;b=this;a=new dojo.data.ItemFileWriteStore({url:"purchaseOrder/getProjectListings",clearOnClose:!0,
urlPreventCache:!0});c=new k({structure:b.getGridLayout(),store:a,poForm:b.poForm,dialogContainer:b});e=new r({region:"top",style:"outline:none!important;padding:2px;border:none;width:100%;"});e.addChild(new h({id:"requestForQuotationProjectSelectButton",label:d.select,iconClass:"icon-16-container icon-16-checkmark2",disabled:!0,onClick:function(){return c.select()}}));e.addChild(new dijit.ToolbarSeparator);e.addChild(new h({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.hide()}}));
a=new q({style:"padding:0px;margin:0px;width:750px;height:420px;",gutters:!1});a.addChild(new u({region:"top",editableGrid:!1,grid:c,filterFields:[{title:d.title,country:d.country,state:d.state}]}));a.addChild(e);a.addChild(c);return a},getGridLayout:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:(new t).rowCountCellFormatter},{name:d.title,field:"title",width:"auto"},{name:d.country,field:"country",width:"100px",styles:"text-align: center;"},{name:d.state,
field:"state",width:"100px",styles:"text-align: center;"},{name:d.createdAt,field:"created_at",width:"80px",styles:"text-align: center;"}]},_onKey:function(a){if(a.keyCode===m.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()}})})}).call(this);
