(function(){define("buildspace/apps/PurchaseOrder/PurchaseOrderDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/on dojo/request dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/html dojo/dom dojo/dom-attr dojo/keys dojo/dom-style dijit/layout/TabContainer dijit/layout/ContentPane dijit/layout/BorderContainer dijit/Toolbar dijit/form/FilteringSelect dijit/form/Select dijit/form/Button dojo/store/Memory dojox/form/Manager dojo/text!./templates/purchaseOrderForm.html ./AssignProjectGrid dojo/i18n!../../nls/PurchaseOrder".split(" "),
function(h,k,B,l,p,q,r,t,u,C,D,v,w,f,E,F,x,y,g,G,m,H,I,z,A,d){var n;n=h("buildspace.apps.PurchaseOrder.PurchaseOrderForm",[q,r,t,u],{baseClass:"buildspace-form",poId:-1,newPoId:-1,templateString:z,region:"center",style:"overflow: auto;",formInfo:null,dialogContainer:null,purchaseOrderGrid:null,rfqStatusSelections:null,currentPurchaseOrderNo:null,nls:d,postCreate:function(){var a;this.inherited(arguments);a=this;l(this.assignProjectGridAction,"click",function(b){return(new A({poId:a.newPoId,poForm:a})).show()});
l(this.poPrefix,"change",function(b){return a.updateFormView()});this.createDropdown();this.hideSupplierSelectContainer();return this.setRequiredFields()},startup:function(){this.inherited(arguments);this["poForm-"+this.poId].setFormValues(this.formInfo);return this.toggleProjectInformationContainer()},createDropdown:function(){var a,b,c;b=this;this.supplierSelectStore=new dojo.data.ItemFileReadStore({data:{identifier:"id",items:[]}});a=new dojo.data.ItemFileReadStore({url:"projectBuilder/getCountry"});
this.stateSelectStore=c=new dojo.data.ItemFileReadStore({url:"projectBuilder/getStateByCountry/regionId/"+b.formInfo["purchase_order[region_id]"]});this.supplierSelect=(new g({name:"company_id",store:this.supplierSelectStore,style:"width: 180px;padding:2px!important;",searchAttr:"name",required:!1})).placeAt(b.supplierSelectDivNode);this.countrySelect=(new g({name:"purchase_order[region_id]",store:a,style:"width: 180px;padding:2px!important;",searchAttr:"name",value:b.formInfo["purchase_order[region_id]"],
required:!0,onChange:function(a){return b.updateStateSelectStore(a)}})).placeAt(b.countrySelectDivNode);return this.stateSelect=(new g({name:"purchase_order[sub_region_id]",store:c,style:"width: 180px;padding:2px!important;",searchAttr:"name",readOnly:0<b.formInfo["purchase_order[sub_region_id]"]?!1:!0,value:b.formInfo["purchase_order[sub_region_id]"],required:!0})).placeAt(b.stateSelectDivNode)},updateStateSelectStore:function(a){null==a&&(a=0);a||(a=0);this.stateSelectStore=new dojo.data.ItemFileReadStore({url:"projectBuilder/getStateByCountry/regionId/"+
a,clearOnClose:!0});this.stateSelect.store.close();this.stateSelect.set("store",this.stateSelectStore);if(this.stateValue)return this.stateSelect.set("value",this.stateValue)},save:function(){var a,b,c;c=this;if(!this["poForm-"+this.poId].validate())return!1;a=dojo.formToObject(this["poForm-"+this.poId].id);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});0<c.newPoId?k.mixin(a,{poId:c.newPoId}):k.mixin(a,{poId:c.poId});b.show();return p.post("purchaseOrder/savePurchaseOrderInformation",
{data:a,handleAs:"json"}).then(function(a){var e,d;if(a.success&&0<a.id)c.newPoId=a.id,c.purchaseOrderGrid.refreshGrid(),c.dialogContainer.hide();else for(d in a.errorMsgs)"username"!==d&&(e=c["error-"+d],e.innerHTML=a.errorMsgs[d],f.set(e,"display","block"));return b.hide()},function(a){return b.hide()})},toggleProjectInformationContainer:function(){f.set(this.projectNameContainer,"display","table-row");return f.set(this.projectSiteAddressContainer,"display","table-row")},setRequiredFields:function(){var a,
b,c;b=this.poPrefix;a=this.countrySelect;c=this.stateSelect;b.set("required",!0);a.set("required",!1);c.set("required",!1);a.set("readOnly",!0);return c.set("readOnly",!0)},updateFormView:function(){var a;a=v.get(this.poPrefix,"value");return this.poNoContainer.innerHTML=null!==this.currentPurchaseOrderNo?a?""+a+this.currentPurchaseOrderNo:this.currentPurchaseOrderNo:null},hideSupplierSelectContainer:function(){return f.set(this.supplierSelectContainer,"display","none")},showSupplierSelectContainer:function(){return f.set(this.supplierSelectContainer,
"display","table-row")},updateSupplierSelectStore:function(a){this.supplierSelectStore=new dojo.data.ItemFileReadStore({clearOnClose:!0,data:{identifier:"id",items:a}});this.supplierSelect.store.close();this.supplierSelect.set("store",this.supplierSelectStore);this.supplierSelect.set("value",-1);return this.supplierSelect.set("item",null)}});return h("buildspace.apps.PurchaseOrder.PurchaseOrderDialog",dijit.Dialog,{poId:-1,style:"padding:0px;margin:0px;width:540px;height:280px;",billId:null,data:null,
purchaseOrderGrid:null,buildRendering:function(){var a;this.content=a=this.createContent();a.startup();return this.inherited(arguments)},postCreate:function(){f.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},createContent:function(){var a,b,c,e;c=this;b=new n({poId:c.poId,dialogContainer:c,formInfo:c.data.purchaseOrderForm,purchaseOrderGrid:c.purchaseOrderGrid});e=new y({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});
e.addChild(new m({label:d.save,iconClass:"icon-16-container icon-16-save",onClick:function(){return b.save()},id:"PO-form-button-save",disabled:!0}));e.addChild(new dijit.ToolbarSeparator);e.addChild(new m({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return c.hide()}}));a=new x({style:"width:540px;height:280px;padding:0;margin:0;",gutters:!1});a.addChild(e);a.addChild(b);return a},_onKey:function(a){if(a.keyCode===w.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()}})})}).call(this);
