define("buildspace/apps/PostContractSubPackage/Preliminaries/buildUpQuantityGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/currency dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox dojo/i18n!buildspace/nls/BuildUpQuantityGrid".split(" "),
function(n,p,y,z,A,B,r,t,u,v,C,l,w,D,E,F,G,H,f){var x=n("buildspace.apps.PostContractSubPackage.BuildUpQuantity.grid",dojox.grid.EnhancedGrid,{billColumnSettingId:null,BillItem:null,style:"border-top:none;",selectedItem:null,keepSelection:!0,addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,buildUpSummaryWidget:null,type:null,editable:!1,disableEditingMode:!1,constructor:function(b){this.rearranger=r(this,{});this.formulatedColumn=t(this,{});b.editable||(this.disableEditingMode=!0)},canSort:function(b){return!1},
canEdit:function(b,a){return this.disableEditingMode?!1:this._canEdit},postCreate:function(){var b=this;b.inherited(arguments);this.on("RowContextMenu",function(a){b.selection.clear();var d=b.getItem(a.rowIndex);b.selection.setSelected(a.rowIndex,!0);b.contextMenu(a);d&&0<d.id&&!b.disableEditingMode?b.disableToolbarButtons(!1):b.disableEditingMode||b.disableToolbarButtons(!0,["Add"])},!0);this.on("RowClick",function(a){(a=b.getItem(a.rowIndex))&&0<a.id&&!b.disableEditingMode?b.disableToolbarButtons(!1):
b.disableEditingMode||b.disableToolbarButtons(!0,["Add"])})},doApplyCellEdit:function(b,a,d){var e=this,c=e.getItem(a),k=e.store;if(b!==c[d][0]){var g=d.replace("-value","");-1!==d.indexOf("-value")&&(b=this.formulatedColumn.convertRowIndexToItemId(b,a));var h={id:c.id,attr_name:g,val:b,type:e.type,_csrf_token:c._csrf_token?c._csrf_token:null},q=this.updateUrl;c.id==buildspace.constants.GRID_LAST_ROW&&(g=0<a?e.getItem(a-1):!1,p.mixin(h,{prev_item_id:g?g.id:0,relation_id:c.relation_id,bill_column_setting_id:e.billColumnSettingId}),
q=this.addUrl);var l=function(a,b){for(var d in a)c.hasOwnProperty(d)&&d!=b._getIdentifierAttribute()&&b.setValue(c,d,a[d]),dojo.forEach(a.affected_nodes,function(a){b.fetchItemByIdentity({identity:a.id,onItem:function(d){for(var e in a)c.hasOwnProperty(e)&&e!=b._getIdentifierAttribute()&&b.setValue(d,e,a[e])}})});b.save()},m=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});m.show().then(function(){dojo.xhrPost({url:q,content:h,handleAs:"json",load:function(b){if(b.success){c&&
0<c.id?l(b.data,k):(k.deleteItem(c),k.save(),dojo.forEach(b.items,function(a){k.newItem(a)}),k.save(),e.disableToolbarButtons(!0));e.updateTotalBuildUp(b.total_build_up);var h=e.getCellByField(d);window.setTimeout(function(){e.focus.setFocusIndex(a,h.index)},10)}m.hide()},error:function(a){console.log(a);m.hide()}})})}e.inherited(arguments)},dodblclick:function(b){},addRow:function(b){l.curNode.blur();l.curNode=null;var a=this,d=buildspace.dialog.indeterminateProgressBar({title:f.addingRow+". "+f.pleaseWait+
"..."}),e=a.store,c=a.getItem(b);if(0<c.id)var k={before_id:c.id,type:a.type,_csrf_token:c._csrf_token,bill_column_setting_id:a.billColumnSettingId,relation_id:c.relation_id};else var g=0<b?a.getItem(b-1).id:0,k={id:c.id,type:a.type,prev_item_id:g,relation_id:c.relation_id,bill_column_setting_id:a.billColumnSettingId,_csrf_token:c._csrf_token};d.show().then(function(){dojo.xhrPost({url:this.addUrl,content:k,handleAs:"json",load:function(c){c.success&&dojo.forEach(c.items,function(d){0<d.id&&(d=e.newItem(d),
e.save(),d=a.getItemIndex(d),a.rearranger.moveRows([d],b))});window.setTimeout(function(){a.focus.setFocusIndex(b,1)},30);d.hide()},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);d.hide()}})})},deleteRow:function(b){var a=this,d=a.getItem(b),e=buildspace.dialog.indeterminateProgressBar({title:f.deleting+". "+f.pleaseWait+"..."});l.curNode.blur();l.curNode=null;e.show();var c={url:this.deleteUrl,content:{id:d.id,_csrf_token:d._csrf_token},handleAs:"json",load:function(c){if(c.success){var g=
c.affected_nodes,h=a.store;h.deleteItem(d);h.save();var f=0;for(c=g.length;f<c;++f)h.fetchItemByIdentity({identity:g[f].id,onItem:function(a){for(var b in g[f])a.hasOwnProperty(b)&&b!=h._getIdentifierAttribute()&&h.setValue(a,b,g[f][b]);h.save()}});a.updateTotalBuildUp()}e.hide();a.selection.clear();window.setTimeout(function(){a.focus.setFocusIndex(b,0)},10);a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=
null;a.pasteOp=null;e.hide()}};new buildspace.dialog.confirm(f.deleteBuildUpQtyItemTitle,f.deleteBuildUpQtyItemMsg,80,320,function(){dojo.xhrPost(c)},function(){e.hide()})},cutItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="cut"},copyItems:function(){this.selectedItem=this.selection.getFirstSelected();this.pasteOp="copy"},pasteItem:function(b){var a=this,d=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."}),e=a.store,c=a.selection.getFirstSelected(),
k=c.id==buildspace.constants.GRID_LAST_ROW&&0<b?a.getItem(b-1).id:0;d.show();dojo.xhrPost({url:this.pasteUrl,content:{type:a.pasteOp,target_id:c.id,id:a.selectedItem.id,prev_item_id:k,_csrf_token:a.selectedItem._csrf_token},handleAs:"json",load:function(c){var f=[];if(c.success)switch(a.pasteOp){case "cut":e.fetchItemByIdentity({identity:c.data.id,onItem:function(c){c=a.getItemIndex(c);f.push(c);0<f.length&&(a.rearranger.moveRows(f,b),a.scrollToRow(b))}});break;case "copy":c=e.newItem(c.data),e.save(),
c=a.getItemIndex(c),f.push(c),0<f.length&&a.rearranger.moveRows(f,b),a.updateTotalBuildUp()}a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;f.length=0;d.hide()},error:function(b){a.selection.clear();a.disableToolbarButtons(!0);a.selectedItem=null;a.pasteOp=null;d.hide()}})},contextMenu:function(b){if(this.disableEditingMode)return!1;var a=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(b);var d={target:b.target,coords:b.keyCode!==v.F10&&"pageX"in b?{x:b.pageX,
y:b.pageY}:null},e=this.getItem(b.rowIndex);a&&e&&(this.selection.isSelected(b.rowIndex)||b.rowNode&&w.hasClass(b.rowNode,"dojoxGridRowbar"))&&(a._openMyself(d),u.stop(b))},contextMenuItems:function(b){var a=this.getItem(b.rowIndex);a&&0<a.id&&(this.rowCtxMenu.addChild(new dijit.MenuItem({label:f.cut,iconClass:"icon-16-container icon-16-cut",onClick:dojo.hitch(this,"cutItems")})),this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.copy,iconClass:"icon-16-container icon-16-copy",onClick:dojo.hitch(this,
"copyItems")})));this.rowCtxMenu.addChild(new dijit.PopupMenuItem({label:f.paste,iconClass:"icon-16-container icon-16-paste",onClick:dojo.hitch(this,"pasteItem",b.rowIndex),disabled:this.selectedItem?!1:!0}));this.rowCtxMenu.addChild(new dijit.MenuItem({label:f.addRow,iconClass:"icon-16-container icon-16-add",onClick:dojo.hitch(this,"addRow",b.rowIndex)}));a&&0<a.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:f.deleteRow,iconClass:"icon-16-container icon-16-delete",onClick:dojo.hitch(this,
"deleteRow",b.rowIndex)}))},disableToolbarButtons:function(b,a){var d=dijit.byId("builUpGrid-"+this.billColumnSettingId+"_"+this.BillItem.id+"AddRow-button"),e=dijit.byId("builUpGrid-"+this.billColumnSettingId+"_"+this.BillItem.id+"DeleteRow-button");d._setDisabledAttr(b);e._setDisabledAttr(b);if(b&&a instanceof Array){var c=this;dojo.forEach(a,function(a){dijit.byId("builUpGrid-"+c.billColumnSettingId+"_"+c.BillItem.id+a+"Row-button")._setDisabledAttr(!1)})}},updateTotalBuildUp:function(){this.buildUpSummaryWidget.refreshTotalQuantity()}});
return n("buildspace.apps.PostContractSubPackage.BuildUpQuantityGrid",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,billColumnSettingId:null,type:null,BillItem:null,gridOpts:{},editable:!1,postCreate:function(){this.inherited(arguments);p.mixin(this.gridOpts,{billColumnSettingId:this.billColumnSettingId,BillItem:this.BillItem,region:"center",type:this.type,editable:this.editable});var b=this.grid=new x(this.gridOpts),a=new dijit.Toolbar({region:"top",
style:"padding:2px;border-bottom:none;width:100%;"}),d=this.gridOpts.editable?!1:!0;this.editable&&(a.addChild(new dijit.form.Button({id:"builUpGrid-"+this.billColumnSettingId+"_"+this.BillItem.id+"AddRow-button",label:f.addRow,iconClass:"icon-16-container icon-16-add",disabled:d?d:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.addRow(b.selection.selectedIndex)}})),a.addChild(new dijit.ToolbarSeparator),a.addChild(new dijit.form.Button({id:"builUpGrid-"+this.billColumnSettingId+
"_"+this.BillItem.id+"DeleteRow-button",label:f.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:d?d:-1<b.selection.selectedIndex?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.deleteRow(b.selection.selectedIndex)}})),this.addChild(a));this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))}})});
