define("buildspace/apps/PostContractSubPackage/Preliminaries/buildUpQuantitySummary","dojo/_base/declare dojo/dom-style dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Button dijit/form/TextBox dijit/form/CheckBox dijit/form/Select dojo/text!./templates/buildUpQuantitySummary.html dojo/number dojo/i18n!buildspace/nls/BuildUpQuantityGrid".split(" "),function(f,g,h,k,l,m,p,q,r,t,n,d,e){return f("buildspace.apps.PostContractSubPackage.buildUpQuantitySummary",
[h,k,l,m],{templateString:n,style:"outline:none;",itemId:-1,billColumnSettingId:-1,nls:e,region:"bottom",_csrf_token:null,container:null,applyConversionFactor:!1,conversionFactorAmount:0,conversionFactorOperator:buildspace.constants.ARITHMETIC_OPERATOR_ADDITION,hasLinkedQty:!1,linkedTotalQuantity:0,totalQuantity:0,totalQuantityAfterConversion:0,roundingType:1,finalQuantity:0,editable:!1,moduleName:null,constructor:function(a){this.ROUNDING_TYPE_DISABLED=buildspace.constants.ROUNDING_TYPE_DISABLED;
this.ROUNDING_TYPE_UPWARD=buildspace.constants.ROUNDING_TYPE_UPWARD;this.ROUNDING_TYPE_DOWNWARD=buildspace.constants.ROUNDING_TYPE_DOWNWARD;this.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER=buildspace.constants.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER;this.ROUNDING_TYPE_NEAREST_TENTH=buildspace.constants.ROUNDING_TYPE_NEAREST_TENTH;this.ROUNDING_TYPE_DISABLED_TEXT=buildspace.constants.ROUNDING_TYPE_DISABLED_TEXT;this.ROUNDING_TYPE_UPWARD_TEXT=buildspace.constants.ROUNDING_TYPE_UPWARD_TEXT;this.ROUNDING_TYPE_DOWNWARD_TEXT=
buildspace.constants.ROUNDING_TYPE_DOWNWARD_TEXT;this.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER_TEXT=buildspace.constants.ROUNDING_TYPE_NEAREST_WHOLE_NUMBER_TEXT;this.ROUNDING_TYPE_NEAREST_TENTH_TEXT=buildspace.constants.ROUNDING_TYPE_NEAREST_TENTH_TEXT;this.inherited(arguments)},postCreate:function(){this.inherited(arguments);var a=this;this.hasLinkedQty&&g.set(this.linkedTotalQuantityRow,"display","");dojo.xhrGet({url:a.moduleName+"/getBuildUpSummary",content:{id:this.itemId,bill_column_setting_id:this.billColumnSettingId,
type:this.type},handleAs:"json",load:function(b){a.applyConversionFactor=b.apply_conversion_factor;a.applyConversionFactorNode.set("checked",a.applyConversionFactor);a.doApplyConversionFactor();a.roundingType=b.rounding_type;a.roundingTypeNode.set("value",a.roundingType);a.conversionFactorAmount=b.conversion_factor_amount;a.conversionFactorAmountNode.set("value",a.conversionFactorAmount);a.conversionFactorOperator=b.conversion_factor_operator;a.conversionFactorOperatorNode.set("value",a.conversionFactorOperator);
var c=a.linkedTotalQuantity=d.format(b.linked_total_quantity,{places:2});dojo.attr(a.linkedTotalQuantityNode,"innerHTML",c);c=a.totalQuantity=d.format(b.total_quantity,{places:2});dojo.attr(a.totalQuantityNode,"innerHTML",c);b=a.finalQuantity=d.format(b.final_quantity,{places:2});dojo.attr(a.finalQuantityNode,"innerHTML",b);b=!a.editable;a.applyConversionFactorNode.set("disabled",b);a.roundingTypeNode.set("disabled",b);a.conversionFactorAmountNode.set("disabled",b);a.conversionFactorOperatorNode.set("disabled",
b)},error:function(a){console.log(a)}})},startup:function(){this.inherited(arguments);this.toggleConversionFactorRows(!1)},doApplyConversionFactor:function(){var a=this.applyConversionFactorNode.get("checked");if(a!=this.applyConversionFactor){var b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),c=this;b.show().then(function(){dojo.xhrPost({url:c.moduleName+"/buildUpSummaryApplyConversionFactorUpdate",content:{id:this.itemId,value:a,_csrf_token:this._csrf_token,bill_column_setting_id:this.billColumnSettingId,
type:this.type},handleAs:"json",load:function(a){c.conversionFactorAmount=a.conversion_factor_amount;c.conversionFactorAmountNode.set("value",c.conversionFactorAmount);c.conversionFactorOperator=a.conversion_factor_operator;c.conversionFactorOperatorNode.set("value",c.conversionFactorOperator);a=c.finalQuantity=d.format(a.final_quantity,{places:2});dojo.attr(c.finalQuantityNode,"innerHTML",a);b.hide()},error:function(a){console.log(a);b.hide()}})})}this.applyConversionFactor=a;this.toggleConversionFactorRows(a)},
toggleConversionFactorRows:function(a){a?dojo.query("."+this.itemId+"-conversion_factor-row").style({display:""}):dojo.query("."+this.itemId+"-conversion_factor-row").style({display:"none"});this.container.resize()},submitConversionFactorAmount:function(){var a=this.conversionFactorAmountNode.get("value");if(a!=this.conversionFactorAmount){var b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),c=this;b.show().then(function(){dojo.xhrPost({url:c.moduleName+"/buildUpSummaryConversionFactorUpdate",
content:{id:this.itemId,val:a,token:"amount",_csrf_token:this._csrf_token,bill_column_setting_id:this.billColumnSettingId,type:this.type},handleAs:"json",load:function(a){c.conversionFactorAmount=a.conversion_factor_amount;c.conversionFactorAmountNode.set("value",c.conversionFactorAmount);a=c.finalQuantity=d.format(a.final_quantity,{places:2});dojo.attr(c.finalQuantityNode,"innerHTML",a);b.hide()},error:function(a){console.log(a);b.hide()}})})}},submitConversionFactorOperator:function(){var a=this.conversionFactorOperatorNode.get("value");
if(a!=this.conversionFactorOperator){var b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),c=this;b.show().then(function(){dojo.xhrPost({url:c.moduleName+"/buildUpSummaryConversionFactorUpdate",content:{id:this.itemId,val:a,token:"operator",_csrf_token:this._csrf_token,bill_column_setting_id:this.billColumnSettingId,type:this.type},handleAs:"json",load:function(a){c.conversionFactorOperator=a.conversion_factor_operator;c.conversionFactorOperatorNode.set("value",c.conversionFactorOperator);
a=c.finalQuantity=d.format(a.final_quantity,{places:2});dojo.attr(c.finalQuantityNode,"innerHTML",a);b.hide()},error:function(a){console.log(a);b.hide()}})})}},refreshTotalQuantity:function(){var a=this;dojo.xhrGet({url:a.moduleName+"/getBuildUpSummary",content:{id:this.itemId,bill_column_setting_id:this.billColumnSettingId,type:this.type},handleAs:"json",load:function(b){var c=a.linkedTotalQuantity=d.format(b.linked_total_quantity,{places:2});dojo.attr(a.linkedTotalQuantityNode,"innerHTML",c);c=
a.totalQuantity=d.format(b.total_quantity,{places:2});dojo.attr(a.totalQuantityNode,"innerHTML",c);b=a.finalQuantity=d.format(b.final_quantity,{places:2});dojo.attr(a.finalQuantityNode,"innerHTML",b)},error:function(a){console.log(a)}})},submitRoundingType:function(){var a=this.roundingTypeNode.get("value");if(a!=this.roundingType){var b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."}),c=this;b.show().then(function(){dojo.xhrPost({url:c.moduleName+"/buildUpSummaryRoundingUpdate",
content:{id:this.itemId,rounding_type:a,_csrf_token:this._csrf_token,bill_column_setting_id:this.billColumnSettingId,type:this.type},handleAs:"json",load:function(a){var e=c.finalQuantity=d.format(a.final_quantity,{places:2});dojo.attr(c.finalQuantityNode,"innerHTML",e);c.roundingType=a.rounding_type;b.hide()},error:function(a){console.log(a);b.hide()}})})}}})});
