(function(){define("buildspace/apps/StockOutReport/WorkArea","dojo/_base/declare dojo/_base/connect dojo/request dijit/layout/ContentPane dijit/layout/BorderContainer dijit/layout/TabContainer buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojox/grid/enhanced/plugins/IndirectSelection dojo/store/Memory dijit/Menu dijit/DropDownMenu dijit/MenuItem dijit/form/Button dijit/form/DropDownButton buildspace/widget/grid/Filter ./StockOutItemGridContainer ./PrintPreviewDialog/PrintSelectedItemGridDialog dojo/i18n!../../nls/StockOut".split(" "),
function(p,q,m,E,v,w,r,x,y,F,n,G,z,A,H,B,t,C,D,f){var u=p("buildspace.apps.StockOutReport.ResourceGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",keepSelection:!0,rowSelector:"0px",region:"center",stockOutWorkAreaContainer:null,project:null,type:null,constructor:function(a){this.rearranger=x(this,{});this.formulatedColumn=y(this,{});if((this.type=a.type)&&"trade"===this.type)return this.plugins={indirectSelection:{headerSelector:!0,width:"40px",styles:"text-align: center;"}}},postCreate:function(){this.inherited(arguments);
if(this.type&&"trade"===this.type){var a=this;this._connects.push(q.connect(this,"onCellClick",function(c){if(""===c.cell.name)return a.singleCheckBoxSelection(c)}));return this._connects.push(q.connect(this.rowSelectCell,"toggleAllSelection",function(c){return a.toggleAllSelection(c)}))}},canSort:function(){return!1},refreshGrid:function(){this.store.save();this.store.close();return this.setStore(this.store)},arrayUnique:function(a){return a.reverse().filter(function(a,b,d){return-1===d.indexOf(a,
b+1)}).reverse()}});return p("buildspace.apps.StockOutReport.WorkArea",w,{region:"center",style:"padding:0px;margin:0px;border:0px;width:100%;height:100%;",project:null,gutters:!1,resourceTradePreviewStore:[],resourceAllTradeItemStore:[],resourceTradeItemStore:[],postCreate:function(){this.inherited(arguments);var a=this;var c=new buildspace.dialog.indeterminateProgressBar({title:f.processing+"..."});c.show();return m.get("stockOut/getResourceWithStockInsByProject/projectId/"+this.project.id[0],{handleAs:"json"}).then(function(b){a.createContentPaneTab("main-stockOutResourceList",
f.resource,a.createResourceContainer(b),!1);b=dijit.byId("main-stockOutResourceList");a.selectChild(b);return c.hide()},function(a){return c.hide()})},createResourceContainer:function(a,c){null==c&&(c=this);a=new dojo.data.ItemFileWriteStore({url:"stockOut/getResourceWithStockInsByProject/projectId/"+this.project.id[0],clearOnClose:!0,urlPreventCache:!0});var b=new u({type:"resource",structure:c.getResourceGridLayout(),store:a,project:this.project,projectId:this.project.id[0],stockOutWorkAreaContainer:c,
onRowDblClick:function(a){var b;a=this.getItem(a.rowIndex);if(0<a.id[0]){var d="main-stockOutResourceList-"+a.id[0];return(b=dijit.byId(d))?c.selectChild(b):c.createContentPaneTab(d,a.name[0],c.createResourceTradeGridView(a),!0)}}});a=new t({region:"top",grid:b,editableGrid:!1,filterFields:[{name:f.description}]});var d=new v({region:"top",gutters:!1});d.addChild(a);d.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}));return d},createResourceTradeGridView:function(a){var c;
var b=this;var d=this;var e="stockOutReportContainerPane-"+a.id[0];(c=dijit.byId(e+"-stackContainer"))&&dijit.byId(e+"-stackContainer").destroyRecursive();c=b.stackContainer=new dijit.layout.StackContainer({id:e+"-stackContainer",style:"width:100%;height:100%;",region:"center"});var k=new dojo.data.ItemFileWriteStore({url:"stockOut/getResourceTradeWithStockInsByProject/projectId/"+b.project.id[0]+"/resourceId/"+a.id[0],clearOnClose:!0,urlPreventCache:!0});this.resourceTradePreviewStore[a.id[0]]=new n({idProperty:"id"});
this.resourceAllTradeItemStore[a.id[0]]=new n({idProperty:"id"});this.resourceTradeItemStore[a.id[0]]=[];var g=new u({id:"stockOutReport-resourceTrade-container-"+b.project.id[0]+"-"+a.id[0],type:"trade",structure:b.getResourceTradeGridLayout(),project:b.project,projectId:b.project.id[0],stockOutWorkAreaContainer:b,resource:a,store:k,onRowDblClick:function(b){b=this.getItem(b.rowIndex);if(0<b.id[0])return this.stockOutWorkAreaContainer.createResourceItemGridView(a,b)},singleCheckBoxSelection:function(a){var b=
a.rowIndex;a=this.selection.selected[b];b=this.getItem(b);return a?this.getAffectedItemByResourceTrade(b,"add"):this.getAffectedItemByResourceTrade(b,"remove")},toggleAllSelection:function(a){b=this;var c=this.selection;var d=this.stockOutWorkAreaContainer.resourceTradePreviewStore[b.resource.id[0]];if(a)return c.selectRange(0,b.rowCount-1),k.fetch({onComplete:function(a){return dojo.forEach(a,function(a,b){if(0<a.id[0])return d.put({id:a.id[0]})})}}),b.getAffectedItemByResourceTrade(null,"add");
c.deselectAll();return b.getAffectedItemByResourceTrade(null,"remove")},getAffectedItemByResourceTrade:function(a,c){b=this;var d=this.stockOutWorkAreaContainer.resourceTradePreviewStore[b.resource.id[0]];var e=[];var k=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});k.show();if(a){if(0>a.id[0])return k.hide(),!1;d.put({id:a.id[0]});e.push(a.id[0])}else d.query().forEach(function(a){return e.push(a.id)});return m.post("stockOutReporting/getAffectedItemsByResourceTrade",{handleAs:"json",
data:{projectId:b.projectId,resourceId:b.resource.id[0],resource_trade_ids:JSON.stringify(b.arrayUnique(e))}}).then(function(a){var d,e;for(d in a){void 0===b.stockOutWorkAreaContainer.resourceTradeItemStore[b.resource.id[0]][d]&&(b.stockOutWorkAreaContainer.resourceTradeItemStore[b.resource.id[0]][d]=new n({idProperty:"id"}));var f=a[d];var g=0;for(e=f.length;g<e;g++){var h=f[g];"add"===c?(b.stockOutWorkAreaContainer.resourceTradeItemStore[b.resource.id[0]][d].put({id:h}),b.stockOutWorkAreaContainer.resourceAllTradeItemStore[b.resource.id[0]].put({id:h})):
(b.stockOutWorkAreaContainer.resourceTradeItemStore[b.resource.id[0]][d].remove(h),b.stockOutWorkAreaContainer.resourceAllTradeItemStore[b.resource.id[0]].remove(h))}}return k.hide()},function(a){console.log(a);return k.hide()})}});var h=new z({style:"display: none;"});h.addChild(new A({label:f.printItemsByResourceTrade,iconClass:"icon-16-container icon-16-print",onClick:function(){return d.openBillPreviewDialogForSelectedItems(a)}}));var l=new dijit.Toolbar({style:"outline:none!important; border-bottom:none; padding:2px; width:100%;",
region:"top"});l.addChild(new B({label:f.print,id:"stockOutReport-resourceTrade-printButton-"+b.project.id[0]+"-"+a.id[0],iconClass:"icon-16-container icon-16-print",dropDown:h}));h=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",gutters:!1,region:"center"});h.addChild(new t({region:"top",grid:g,editableGrid:!1,filterFields:[{description:f.description}]}));h.addChild(l);h.addChild(new dijit.layout.ContentPane({style:"width:100%",content:g,region:"center"}));
g=new dijit.layout.ContentPane({title:a.name,content:h});c.addChild(g);g=new dijit.layout.StackController({region:"top",containerId:e+"-stackContainer"});g=new dijit.layout.ContentPane({style:"padding: 0px; overflow: hidden;",baseClass:"breadCrumbTrail",region:"top",content:g});l=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;",baseClass:"form",gutters:!1,region:"center"});l.addChild(c);l.addChild(g);dojo.subscribe(e+"-stackContainer-selectChild","",function(a){var b,
c;if(b=dijit.byId(e+"-stackContainer")){var d=b.getChildren();a=dojo.indexOf(d,dijit.byId(a.id))+1;for(c=[];d.length>a;)b.removeChild(d[a]),d[a].destroyRecursive(),c.push(a+=1);return c}});l.startup();return l},openBillPreviewDialogForSelectedItems:function(a){var c=this;var b=c.resourceAllTradeItemStore[a.id[0]];var d=[];b.query().forEach(function(a){return d.push(a.id)});d=d.reverse().filter(function(a,b,c){return-1===c.indexOf(a,b+1)}).reverse();var e=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+
"..."});e.show();return m.post("stockOutReporting/getPrintPreviewStockOutItems",{handleAs:"json",data:{projectId:c.project.id[0],resourceId:a.id[0],item_ids:JSON.stringify(d)}}).then(function(b){(new D({title:f.printItemsByResourceTrade,projectId:c.project.id[0],resourceId:a.id[0],data:b,selectedItems:d})).show();return e.hide()},function(a){console.log(a);return e.hide()})},createResourceItemGridView:function(a,c,b){null==b&&(b=this);var d=new C({project:this.project,resource:a,resourceTrade:c,stockOutWorkAreaContainer:b});
return b.makePane(a,c.description[0],d)},getResourceGridLayout:function(){var a=new r;return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter,noresize:!0},{name:f.description,field:"name",width:"auto",formatter:a.treeCellFormatter,noresize:!0},{name:f.totalCost,field:"total_cost",width:"140px",styles:"text-align: right;",formatter:a.unEditableCurrencyCellFormatter,noresize:!0}]},getResourceTradeGridLayout:function(){var a=new r;return[{name:"No",field:"id",
width:"30px",styles:"text-align: center;",formatter:a.rowCountCellFormatter,noresize:!0},{name:f.description,field:"description",width:"auto",formatter:a.treeCellFormatter,noresize:!0},{name:f.totalCost,field:"total_cost",width:"140px",styles:"text-align: right;",formatter:a.unEditableCurrencyCellFormatter,noresize:!0}]},createContentPaneTab:function(a,c,b,d){a=new dijit.layout.ContentPane({closable:d,id:a,style:"padding:0px;border:0px;margin:0px;overflow:hidden;",title:buildspace.truncateString(c,
60),content:b});this.addChild(a);return this.selectChild(a)},makePane:function(a,c,b){a=dijit.byId("stockOutReportContainerPane-"+a.id[0]+"-stackContainer");c=new dijit.layout.ContentPane({title:buildspace.truncateString(c,35),content:b});a.addChild(c);return a.selectChild(c)}})})}).call(this);
