(function(){var l={}.hasOwnProperty;define("buildspace/apps/TenderingReport/BillManager/PrintPreviewDialog/PrintSelectedItemAmountIncludingQty2GridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(f,t,u,v,w,x,y,m,n,p,z,q,r,d){var h,k;h=f("buildspace.apps.TenderingReport.SelectedElementGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){var b,c;this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length)return c=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children,c.parentNode.removeChild(c),dojo.forEach(b,function(a,b){var c;c=dojo.attr(a,"rowSpan");if(!c||2>c)return dojo.attr(a,"rowSpan",2)})}});k=f("buildspace.apps.TenderingReport.SelectedElementGridContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,billId:-1,selectedItems:[],dialog:null,store:null,structure:null,type:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new h({store:b.store,structure:b.structure});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.openPrintingDialog()}}));
c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return p.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=
new q({title:a.dialog.title,billId:a.billId,selectedRows:a.selectedItems,type:a.type,printURL:"tenderingReport/printSelectedItemsAmountIncludingQty2",exportURL:"tenderingReport/exportExcelSelectedItemsAmountIncludingQty2",_csrf_token:c._csrf_token});b.hide();return c.show()},function(){return b.hide()})}});return f("buildspace.apps.TenderingReport.PrintPreviewReportDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",billId:-1,typeColumns:[],data:null,selectedItems:[],buildRendering:function(){var a;
a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){n.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===m.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(a){var b;null==a&&(a=this);b=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});
a=new k({store:dojo.data.ItemFileWriteStore({data:a.data}),dialog:a,billId:a.billId,structure:a.constructGridStructure(),type:a.type,selectedItems:a.selectedItems});b.addChild(a);return b},constructGridStructure:function(a){var b,c,e,f,g;null==a&&(a=this.typeColumns);e=new r;g=[];b={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:e.rowCountCellFormatter,noresize:!0,rowSpan:2},{name:d.billReference,field:"bill_ref",styles:"text-align:center; color: red;",
width:"80px",formatter:e.billRefCellFormatter,noresize:!0,rowSpan:2},{name:d.description,field:"description",width:"500px",formatter:e.treeCellFormatter,noresize:!0,rowSpan:2},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:e.unitIdCellFormatter,noresize:!0,rowSpan:2}]]};for(f in a)l.call(a,f)&&(c=a[f],b.cells[0].push({name:d.amount+"/"+d.unit,field:c.id+"-total_per_unit",width:"100px",styles:"text-align:right;",formatter:e.itemTotalPerUnitCellFormatter,noresize:!0}),
b.cells[0].push({name:d.amount+"/"+d.unit+" (2)",field:c.id+"-remeasure_total_per_unit",width:"100px",styles:"text-align:right;",formatter:e.itemTotalPerUnitCellFormatter,noresize:!0}),b.cells[0].push({name:d.difference+" (%)",field:c.id+"-total_per_unit_difference",width:"85px",styles:"text-align:right;color:blue;",formatter:e.unEditablePercentageCellFormatter,noresize:!0}),g.push({name:c.name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader0",colSpan:3,noresize:!0}));b.cells.push(g);
return b}})})}).call(this);
