define("buildspace/apps/ViewTenderer/ScheduleOfRateBillGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dijit/Menu dojo/number dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem dijit/MenuSeparator buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/Tendering dojo/on dojox/grid/_Grid dojox/widget/PlaceholderMenuItem buildspace/widget/grid/cells/TextBox".split(" "),function(h,k,q,r,t,
u,v,w,x,y,z,A,B,C,n,f,D){var p=h("buildspace.apps.ViewTenderer.ScheduleOfRateBillGrid",dojox.grid.EnhancedGrid,{type:null,billId:-1,elementId:0,itemId:-1,disableEditing:!1,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",parentGrid:null,elementGridStore:null,updateUrl:null,project:null,constructor:function(a){this.type=a.type;this.tender_setting=a.tender_setting;this.tender_companies=a.tender_companies;this.currencySetting=buildspace.billCurrencyAbbreviation?
buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;var b=this.formatter=new n;this.companyColumnChildren=[{name:f.rate,field_name:"contractor_rate",width:"100px",cellType:"buildspace.widget.grid.cells.TextBox",styles:"text-align:right;",editable:!0,formatter:b.currencyCellFormatter},{name:f.difference,field_name:"difference",width:"100px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter}];this.setColumnStructure();this.inherited(arguments)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);
else this.onCellDblClick(a);else this.onRowDblClick(a)},editableCellDblClick:function(a){var b;b=1<this._click.length&&has("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=this._click[1].rowIndex?this._click[0]:a;this.focus.setFocusCell(b.cell,b.rowIndex);this.onRowClick(b);this.onRowDblClick(a)},setColumnStructure:function(){var a=this.formatter,b="auto",c;"tree"==this.type?(0<this.tender_companies.length&&(b="580px"),a=this.fixedColumns={noscroll:!1,width:57.8,cells:[[{name:"No",
field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0,showInCtxMenu:!0,rowSpan:2},{name:f.description,field:"description",width:b,formatter:a.treeCellFormatter,noresize:!0,rowSpan:2},{name:f.type,field:"type",width:"70px",styles:"text-align:center;",formatter:a.typeCellFormatter,noresize:!0,rowSpan:2},{name:f.unit,field:"uom_id",width:"50px",editable:!1,styles:"text-align:center;",formatter:a.unitIdCellFormatter,noresize:!0,rowSpan:2},{name:f.estimationRate,
field:"estimation_rate",styles:"text-align:right;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0,rowSpan:2}]]},b=[],c=this.generateContractorRateColumn(a)):(5<this.tender_companies.length&&(b="480px"),a=this.fixedColumns={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0},{name:f.description,field:"description",width:b,formatter:a.treeCellFormatter,noresize:!0}]]},b=this.generateContractorGrandTotalColumn(),
c=a);dojo.forEach(b,function(a){c.cells[0].push(a)});this.structure=c},generateContractorRateColumn:function(a){var b=this.companyColumnChildren,c=[],d=0;dojo.forEach(this.tender_companies,function(e){var g=b.length;d++;var f;f=e.awarded?'<span style="color:blue;">'+buildspace.truncateString(e.name,28)+"</span>":buildspace.truncateString(e.name,28);c.push({name:f,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+d,colSpan:g,headerId:e.id,hidden:!1});for(i=0;i<b.length;i++)g=e.id+
"-"+b[i].field_name,g={field:g,columnType:"contractorColumn",companyId:e.id,headerClasses:"typeHeader"+d},k.mixin(g,b[i]),a.cells[0].push(g)});a.cells.push(c);return a},generateContractorGrandTotalColumn:function(){var a=[],b=this.formatter,c=0;dojo.forEach(this.tender_companies,function(d){c++;var e;e=d.awarded?'<span style="color:blue;">'+buildspace.truncateString(d.name,28)+"</span>":buildspace.truncateString(d.name,28);a.push({name:e,field:d.id+"-total",styles:"text-align:right;",width:"120px",
formatter:b.unEditableCurrencyCellFormatter,headerClasses:"typeHeader"+c,noresize:!0})});return a},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments)},doApplyCellEdit:function(a,b,c){var d=this,e=this.getItem(b),g=d.store,l=c.replace("-value","");if(void 0!=e[c][0]||a!==e[c][0]){var m=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."}),l={id:e.id,pid:this.project.id,unsorted:this.unsorted,attr_name:l,val:a,_csrf_token:e._csrf_token?e._csrf_token:null},
h=this.updateUrl,k=function(a,b){for(var c in a)e.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(e,c,a[c]),dojo.forEach(a.affected_nodes,function(a){b.fetchItemByIdentity({identity:a.id,onItem:function(c){for(var d in a)e.hasOwnProperty(d)&&d!=b._getIdentifierAttribute()&&b.setValue(c,d,a[d])}})});b.save()};m.show();dojo.xhrPost({url:h,content:l,handleAs:"json",load:function(a){if(a.success){0<e.id&&k(a.data,g);var f=d.getCellByField(c);window.setTimeout(function(){d.focus.setFocusIndex(b,
f.index)},10);m.hide()}},error:function(a){m.hide()}})}this.inherited(arguments)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(c,function(a,b){var c=dojo.attr(a,"rowSpan");(!c||2>c)&&dojo.attr(a,"rowSpan",2)})}},canEdit:function(a,b){var c=this,d;return void 0!=a&&(d=this.getItem(b),0>d.id[0]||
this.disableEditing||"tree"==this.type&&0<d.id[0]&&(d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N)&&a.editable)?(window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10),!1):this._canEdit}});return h("buildspace.apps.ViewTenderer.ScheduleOfRateBillGridBuilder",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,stackContainerTitle:"",
rootProject:null,billId:-1,elementId:0,disableEditing:!1,itemId:-1,rowSelector:null,gridOpts:{},type:null,postCreate:function(){this.inherited(arguments);k.mixin(this.gridOpts,{billId:this.billId,project:this.rootProject,elementId:this.elementId,type:this.type,region:"center",disableEditing:this.disableEditing,borderContainerWidget:this});var a=this.grid=new p(this.gridOpts);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));var b=dijit.byId("viewTenderBreakdown"+
this.rootProject.id+"-stackContainer");if(b){var c=document.createElement("div");b.addChild(new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),id:this.pageId,content:this,grid:a},c));b.selectChild(this.pageId)}}})});
