define("buildspace/widget/grid/plugins/LocationFilter","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/on dojo/aspect dojo/dom-attr dojo/query dijit/registry dijit/form/TextBox buildspace/widget/forms/MultiSelectDropDown dojox/grid/enhanced/_Plugin dojox/grid/EnhancedGrid dojo/i18n!buildspace/nls/Common".split(" "),function(h,p,v,q,w,t,u,x,y,z,A,B,C,r){h=h("buildspace.widget.grid.plugins.LocationFilter",B,{name:"buildspaceLocationFilter",constructor:function(a,d){this.grid=
a;this.nls=r;this._connects=[];d=p.isObject(d)?d:{};this.columns=d.columns;this.gridStoreUrl=d.gridStoreUrl;this.dropDownFilterUrl=d.dropDownFilterUrl;this.manualFilter=d.manualFilter;a.manualFilter=p.hitch(this,"doManualFilter");this._connects.push(q.connect(this.grid.views,"render",this,"_addWidgetsToHeaders"));this._connects.push(q.connect(this.grid,"_onFetchComplete",this,"_addWidgetsToHeaders"))},_addWidgetsToHeaders:function(){var a=x(".dojoxGridHeader table th",this.grid.viewsHeaderNode);if(this.columns){var d=
this.columns,e=this.grid,b=this.dropdownStoreData,k=this;this.filterWidgets=[];dojo.forEach(a,function(a){dojo.forEach(d,function(c){if(parseInt(u.get(a,"idx"))==parseInt(c.idx)){var d;d=a.firstChild&&3!=a.firstChild.nodeType?a.firstChild:a;var f=e.layout.cells[c.idx],l,m,n;if(c.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION||c.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_TRADE)l=e.id+"-"+c.level+"-"+c.type+"-location_filter",n={data:{identifier:"id",label:"name",items:c.data},clearOnClose:!0},
m=[{attribute:"priority",descending:!1},{attribute:"lft",descending:!1},{attribute:"level",descending:!1}];else if(c.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_TYPE||c.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_UNIT)l=e.id+"-"+c.type+"-column_filter",n={data:{identifier:"id",label:"name",items:c.data},clearOnClose:!0},m=[];else if(l=e.id+"-"+f.index+"-"+f.field+"-filter",b){m=[];for(var g=0;g<b.length;g++)if(b[g].idx==c.idx){n={data:{identifier:"id",label:"name",items:b[g].data},
clearOnClose:!0};break}}g=dijit.byId(l);if(!g)switch(c.widgetName){case "dropdown":g=new A({id:l,cell:f,column:c,name:f.index+"-"+f.field+"-filter",valueField:"id",textField:"name",style:"font-weight:normal!important;padding:2px;width:auto;display:block;",dropDownWidth:"240px",storeSort:m,dataStore:new dojo.data.ItemFileReadStore(n)});w(g,"click",p.hitch(k,"doDropDownFilter",g));break;case "textbox":g=new z({id:l,cell:f,column:c,name:f.index+"-"+f.field+"-filter",style:"font-weight:normal!important;padding:2px;width:98%;display:block;",
onKeyUp:dojo.hitch(k,"doTextBoxFilter",f.index)})}g&&(k.filterWidgets.push(g),g.placeAt(d,"before"))}})})}},doDropDownFilter:function(a){if(a.dropDown.grid.store._arrayOfAllItems.length){var d=this,e=t.after(this.grid,"_refresh",function(){e.remove();d.resetSelectRow(a.cell.index)}),b={};dojo.forEach(this.filterWidgets,function(c){if(c.column.hasOwnProperty("type")&&0<c.getSelectedIds().length){var a;if(c.column.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION||c.column.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_TRADE){switch(c.column.type){case buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION:a=
"l-";break;default:a="t-"}b[a+c.column.level]=c._hidden.value}if(c.column.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_UNIT||c.column.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_TYPE){switch(c.column.type){case buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_TYPE:a="column_type";break;default:a="column_unit"}b[a]=c._hidden.value}}});var k=this.grid,h=buildspace.dialog.indeterminateProgressBar({title:r.pleaseWait+"..."});d.dropDownFilterUrl&&h.show().then(function(){dojo.xhrPost({url:d.dropDownFilterUrl,
handleAs:"json",preventCache:!0,content:b,load:function(c){var b,f;switch(a.column.type){case buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_TYPE:b="column_types";break;case buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION:b="project_structure_location_codes";break;default:b="predefined_location_codes"}if(c.hasOwnProperty(b))if("project_structure_location_codes"==b||"predefined_location_codes"==b){for(var e in c[b])(f=dijit.byId(k.id+"-"+e+"-"+a.column.type+"-location_filter"))&&d._updateDependentDropDownStore(f,
c[b][e]);0==c[b].length&&(e=a.column.level);c=dojo.query('span[widgetid$="-'+a.column.type+'-location_filter"]');c.length>parseInt(e)&&dojo.forEach(c,function(a){var b=u.get(a,"widgetid").split("-");parseInt(b[1])>parseInt(e)&&y.getEnclosingWidget(a).resetDataStore(new dojo.data.ItemFileReadStore({data:{identifier:"id",label:"name",items:[]},clearOnClose:!0}))})}else"column_types"==b&&(f=dijit.byId(k.id+"-"+buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_UNIT+"-column_filter"))&&d._updateDependentDropDownStore(f,
c.column_units);h.hide();d.manualFilter||d.doFilter()},error:function(a){h.hide()}})})}},_updateDependentDropDownStore:function(a,d){a.column.type!=buildspace.constants.LOCATION_SEQUENCE_TYPE_TRADE&&a.column.type!=buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION&&a.column.type!=buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_UNIT||a.resetDataStore(new dojo.data.ItemFileReadStore({data:{identifier:"id",label:"name",items:d},clearOnClose:!0}))},doTextBoxFilter:function(a){var d=this,e=t.after(this.grid,
"_refresh",function(){e.remove();d.resetSelectRow(a)});this.manualFilter||this.doFilter()},doManualFilter:function(){this.doFilter()},doFilter:function(){var a={};dojo.forEach(this.filterWidgets,function(b){if(b.column.hasOwnProperty("type")&&"dropdown"==b.column.widgetName.toLowerCase()&&0<b.getSelectedIds().length){var d;if(b.column.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION||b.column.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_TRADE){switch(b.column.type){case buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION:d=
"l-";break;default:d="t-"}a[d+b.column.level]=b._hidden.value}else if(b.column.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_UNIT||b.column.type==buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_TYPE){switch(b.column.type){case buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_TYPE:d="column_type";break;default:d="column_unit"}a[d]=b._hidden.value}}else"textbox"==b.column.widgetName.toLowerCase()&&(a[b.cell.field]=b.get("value"))});var d=buildspace.dialog.indeterminateProgressBar({title:r.pleaseWait+
"..."}),e=this;e.grid.filterParams=a;d.show().then(function(){dojo.xhrPost({url:e.gridStoreUrl,content:a,handleAs:"json",preventCache:!0,load:function(a){e.grid.setStore(new dojo.data.ItemFileWriteStore({data:a,clearOnClose:!0}));d.hide()},error:function(a){d.hide()}})})},resetSelectRow:function(a){this.deselectAll();this.focusCell(a)},deselectAll:function(){this.hasIndirectSelection||this.grid.selection.deselectAll()},focusCell:function(a){this.grid.focus.setFocusIndex(0,a)},destroy:function(){v.forEach(this._connects,
q.disconnect);delete this._connects;dojo.forEach(this.filterWidgets,function(a){a.destroyRecursive()});delete this.filterWidgets}});C.registerPlugin(h);return h});
