(function(){define("buildspace/apps/ProjectAnalyzerReport/ScheduleOfRatePrintPreviewDialog/PrintSelectedTradeItemBillItemGridDialog","dojo/_base/declare dojo/aspect dojo/number dojo/currency dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectAnalyzer".split(" "),function(f,u,l,m,v,w,x,y,z,n,p,q,A,r,t,d){var g,h,k;g=f("buildspace.apps.RationalizeRateReport.Formatter",
null,{unEditableCurrencyCellFormatter:function(a,b,c){var e;b=this.grid.getItem(b);e=l.parse(a);isNaN(e)||0===e||null===e?a="&nbsp;":(a=m.format(e),a=0<=e?a:'<span style="color:#FF0000">'+a+"</span>");null!=b.type&&"tradeItem"===b.type[0]&&(a='<span style="color: blue;">'+a+"</span>");void 0!==b.type&&1>b.type?c.customClasses.push("invalidTypeItemCell"):c.customClasses.push("disable-cell");return a}});h=f("buildspace.apps.RationalizeRateReport.SelectedItemRateGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",
region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1}});k=f("buildspace.apps.RationalizeRateReport.SelectedItemRateGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,billId:-1,projectId:-1,scheduleOfRateId:-1,tradeId:-1,elementId:-1,tradeItemIds:[],selectedItems:[],printURL:null,exportURL:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new h({store:b.store,
structure:b.structure,tradeItemIds:b.tradeItemIds,selectedItems:b.selectedItems});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",onClick:function(a){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);
return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return q.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new r({title:a.dialog.title,tradeItemIds:a.tradeItemIds,selectedRows:a.selectedItems,printURL:a.printURL,exportURL:a.exportURL,billId:a.billId,elementId:a.elementId,projectId:a.projectId,
scheduleOfRateId:a.scheduleOfRateId,tradeId:a.tradeId,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return f("buildspace.apps.RationalizeRateReport.PrintPreviewDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,billId:-1,elementId:-1,projectId:-1,scheduleOfRateId:-1,tradeId:-1,data:null,tradeItemIds:[],selectedItems:[],contractorList:[],printURL:null,exportURL:null,buildRendering:function(){var a;a=this.createContent();a.startup();this.content=
a;return this.inherited(arguments)},postCreate:function(){p.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===n.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,b;a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});b=new k({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,
tradeItemIds:this.tradeItemIds,selectedItems:this.selectedItems,structure:this.constructGridStructure(),billId:this.billId,elementId:this.elementId,projectId:this.projectId,scheduleOfRateId:this.scheduleOfRateId,tradeId:this.tradeId,printURL:this.printURL,exportURL:this.exportURL});a.addChild(b);return a},constructGridStructure:function(a){var b,c;null==a&&(a=this);c=new t;a=new g;b=[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:c.rowCountCellFormatter},{name:d.description,
field:"description",width:this.contractorList&&this.contractorList.hasOwnProperty("items")&&0<this.contractorList.items.length?"500px":"auto",formatter:c.printPreviewTreeCellFormatter,noresize:!0},{name:d.totalQty,field:"grand_total_quantity",width:"120px",styles:"text-align:right;",formatter:c.unEditableNumberCellFormatter,noresize:!0},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:c.unitIdCellFormatter,noresize:!0},{name:d.rate,field:"rate-value",width:"120px",styles:"text-align:right;",
formatter:c.unEditableAnalyzerRateCellFormatter,noresize:!0},{name:d.total,field:"grand_total",width:"120px",styles:"text-align:right;",formatter:a.unEditableCurrencyCellFormatter,noresize:!0},{name:d.itemMarkup+" (%)",field:"markup_percentage-value",width:"100px",styles:"text-align:right;",formatter:c.analyzerItemMarkupCellFormatter,noresize:!0}];this.contractorList&&this.contractorList.hasOwnProperty("items")&&dojo.forEach(this.contractorList.items,function(a){var d;d=a.awarded?'<p style="color:#0000FF!important;">'+
buildspace.truncateString(a.name,45)+"</p>":buildspace.truncateString(a.name,45);return b.push({name:d,field:"contractor_rate-"+a.id+"-value",width:"120px",styles:"text-align:right;",formatter:c.formulaCurrencyCellFormatter})});return b}})})}).call(this);
