define("buildspace/apps/PostContractSubPackageReport/MaterialOnSiteReport/MaterialOnSiteGrid","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/html dojo/dom-style dojo/number dojo/request dojo/aspect dijit/focus dojo/_base/event dojo/keys dijit/TooltipDialog dijit/popup dojox/grid/EnhancedGrid dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection ./PrintSelectedMOSItemsDialog ./PrintSelectedMOSItemsByAmountOnlyDialog dojo/i18n!buildspace/nls/PostContract".split(" "),
function(h,g,k,y,z,A,l,m,B,C,D,E,F,n,p,q,r,t,u,G,H,v,w,e){var x=h("buildspace.apps.PostContractSubPackageReport.MaterialOnSiteReport.MaterialOnSiteReportEnhancedGrid",n,{type:null,style:"border-top:none;",rowSelector:"0px",selectedItem:null,region:"center",subPackage:null,locked:!1,keepSelection:!0,gridContainer:null,constructor:function(){this.connects=[];this.rearranger=t(this,{});this.formulatedColumn=u(this,{});this.plugins={indirectSelection:{headerSelector:!0,width:"40px",styles:"text-align: center;"}}},
postCreate:function(){var b=this,a;b.inherited(arguments);a="vo"===b.type?b.gridContainer.mosSelectedStore:b.gridContainer.mosItemSelectedStore;m.after(b,"_onFetchComplete",function(){b.gridContainer.markedCheckBoxObject(b,a)})},startup:function(){var b=this;b.inherited(arguments);this._connects.push(g.connect(this,"onCellClick",function(a){""===a.cell.name&&b.singleCheckBoxSelection(a)}));this._connects.push(g.connect(this.rowSelectCell,"toggleAllSelection",function(a){b.toggleAllSelection(a)}))},
canSort:function(){return!1},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,g.disconnect);delete this._connects}});return h("buildspace.apps.PostContractSubPackageReport.MaterialOnSiteReport.MaterialOnSiteReportGrid",dijit.layout.BorderContainer,{stackContainerTitle:"",style:"padding:0;margin:0;width:100%;height:100%;",gutters:!1,subPackage:null,materialOnSite:null,gridOpts:{},type:null,pageId:0,postCreate:function(){var b=this,a;this.inherited(arguments);k.mixin(this.gridOpts,
{type:this.type,subPackage:this.subPackage,materialOnSite:this.materialOnSite,locked:!0});var c=this.grid=new x(this.gridOpts);switch(this.type){case "vo":a="materialOnSiteReport-"+this.subPackage.id;break;case "vo-items":a="materialOnSiteItemsReport-"+this.subPackage.id+"_"+this.materialOnSite.id;break;default:throw Error("type must be set!");}var f=new q({style:"display: none;"}),d=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});dojo.forEach(["selectedMOSItems",
"selectedMOSItemsByAmount"],function(a){var c;switch(a){case "selectedMOSItems":c="openPrintSelectedMOSItems";break;case "selectedMOSItemsByAmount":c="openPrintSelectedMOSItemsByAmounts"}f.addChild(new r({label:e[a],onClick:function(){b[c](a)}}))});d.addChild(new p({label:e.printPreview,iconClass:"icon-16-container icon-16-print",dropDown:f}));this.addChild(d);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:c,region:"center"}));if(a=dijit.byId(a+"-stackContainer"))d=document.createElement("div"),
d=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),content:this,id:this.pageId,executeScripts:!0},d),a.addChild(d),k.mixin(d,{grid:c}),a.selectChild(this.pageId)},openPrintSelectedMOSItems:function(){var b=this,a=[];b.gridOpts.gridContainer.mosItemSelectedStore.query().forEach(function(b){a.push(b.id)});var c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});c.show();l.post("subPackageMaterialOnSiteReporting/getPrintPreviewSelectedItems",
{handleAs:"json",data:{subPackageId:b.subPackage.id[0],item_ids:JSON.stringify(b.gridOpts.gridContainer.arrayUnique(a))}}).then(function(f){(new v({subPackageId:b.subPackage.id,title:e.selectedMOSItems,data:f,selectedItems:a})).show();c.hide()},function(a){console.log(a);c.hide()})},openPrintSelectedMOSItemsByAmounts:function(){var b=this,a=[];b.gridOpts.gridContainer.mosItemSelectedStore.query().forEach(function(b){a.push(b.id)});var c=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+
"..."});c.show();l.post("subPackageMaterialOnSiteReporting/getPrintPreviewSelectedItems",{handleAs:"json",data:{subPackageId:b.subPackage.id[0],item_ids:JSON.stringify(b.gridOpts.gridContainer.arrayUnique(a))}}).then(function(f){(new w({subPackageId:b.subPackage.id,title:e.selectedMOSItemsByAmount,data:f,selectedItems:a})).show();c.hide()},function(a){console.log(a);c.hide()})}})});
