require({cache:{"url:buildspace/widget/forms/templates/DropdownDialog.html":'<div role="presentation" data-dojo-attach-point="containerNode" tabIndex="-1">\n\t</div>\n'}});
define("buildspace/widget/forms/MultiSelectDropDown","dojo/_base/declare dojo/on dojo/_base/html dojo/_base/array dojo/_base/lang dojo/_base/connect dojo/aspect dojo/dom-class dojo/_base/event dojo/keys dijit/popup dijit/focus dijit/form/DropDownButton dijit/layout/ContentPane dijit/_DialogMixin dijit/form/_FormMixin dijit/_TemplatedMixin dojo/text!./templates/DropdownDialog.html dojox/grid/enhanced/plugins/filter/FilterLayer dojox/grid/enhanced/plugins/filter/FilterBuilder dojox/grid/enhanced/_Plugin dojox/grid/enhanced/plugins/IndirectSelection dijit/form/TextBox dojo/i18n!buildspace/nls/Common".split(" "),function(k,
E,g,l,e,f,n,p,q,F,G,r,t,u,v,w,x,y,m,z,A,H,B,h){var C=k("buildspace.widget.forms.DropDownDialog.grid.plugins.Filter",A,{name:"buildspaceDropDownFilter",constructor:function(a,c){this.grid=a;this.nls=h;this._connects=[];this.args=e.isObject(c)?c:{};this.builder=new z;var b=new m.ClientSideFilterLayer({getter:this._clientFilterGetter});m.wrap(a,"_storeLayerFetch",b);this.textBox||(this.textBox=new B({id:this.grid.id+"_dropDownFilterTextBox",style:"font-weight:normal!important;padding:2px;height:auto;width:auto;display:block;",
intermediateChanges:!0,onKeyUp:dojo.hitch(this,"doTextBoxFilter")}));this._connects.push(f.connect(this.grid,"_onDelete",e.hitch(b,"invalidate")));this.fetchCompleted=!1;this._connects.push(f.connect(this.grid.views,"render",this,"_addWidgetsToHeaders"));this._connects.push(f.connect(this.grid,"_onFetchComplete",this,"_onItemsLoaded"))},_clientFilterGetter:function(a,c,b){return c.get(b,a)},_addWidgetsToHeaders:function(){var a=dojo.query(".dojoxGridHeader table th",this.grid.viewsHeaderNode);g.empty(a[1].firstChild);
this.fetchCompleted&&this.textBox&&(this.textBox.placeAt(a[1].firstChild,"replace"),this.textBox.focus())},_onItemsLoaded:function(a){this.fetchCompleted=!0;this.grid.focus._colHeadFocusIdx=null;this.grid.focus._colHeadNode=null},doTextBoxFilter:function(){var a={datatype:"string",args:null,isColumn:!0},c=[e.mixin({data:this.grid.layout.cells[1]},a)];a.isColumn=!1;c.push(e.mixin({data:this.textBox.get("value")},a));this.grid.layer("filter").filterDef(this.builder.buildExpression({op:"logicall",data:[{op:"contains",
data:c}]}));var b=this;this.textBox.get("value");var d=n.after(this.grid,"_refresh",function(){d.remove();b.textBox.focus();var a=b.grid.layer("filter")._items.length?b.grid.layer("filter")._items:this._arrayOfAllItems;b.resetSelectFunc(a)});setTimeout(e.hitch(this.grid,"_refresh"),10)},resetSelectFunc:function(a){var c=!0,b;for(b in a){var d=this.grid.dropDownDialog.getSelectedIds().indexOf(String(a[b].id));this.grid.rowSelectCell.toggleRow(this.grid.getItemIndex(a[b]),-1!=d);-1==d&&(c=!1)}this.grid.rowCount=
this.grid.store._arrayOfAllItems.length;!c&&(a=dojo.byId(this.grid.id+"_rowSelector_-1"))&&(g.toggleClass(a,"dijitCheckBoxChecked",!1),a.setAttribute("aria-checked",!1))},destroy:function(){this.grid.unwrap("filter");l.forEach(this._connects,f.disconnect);delete this._connects}}),D=k("buildspace.widget.forms.DropDownDialog",[u,x,w,v],{title:"",doLayout:!1,autofocus:!1,baseClass:"multiSelectDropDown",_firstFocusItem:null,_lastFocusItem:null,templateString:y,isResetDataStore:!1,constructor:function(a){this.dropDownButton=
a.dropDownButton;this.store=this.dropDownButton.dataStore;this.sortOrder=this.dropDownButton.storeSort;dojox.grid.EnhancedGrid.registerPlugin(C);this.grid=new dojox.grid.EnhancedGrid({sortInitialOrder:this.sortOrder,store:this.store,structure:[{name:"",field:"name",width:"auto"}],style:"border:none;padding:0;margin:0;",canSort:function(){return!1},dropDownDialog:this,plugins:{indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"},buildspaceDropDownFilter:{}}})},postCreate:function(){this.inherited(arguments);
var a=this;this._connects=[];this._selectedIds=[];this.addChild(this.grid);this._connects.push(f.connect(this.grid,"onCellClick",function(c){a._onCheckboxClicked(c.rowIndex)}));this._connects.push(f.connect(this.grid.rowSelectCell,"toggleAllSelection",function(c){a.toggleSelectAll(this.getValue(-1),!1)}));this._lastFocusItem=this._firstFocusItem=dojo.byId(this.grid.id+"_dropDownFilterTextBox")},getSelectedIds:function(){return this._selectedIds},_onCheckboxClicked:function(a){var c=this.grid,b=c.getItem(a),
d=!0;if(b){var e=this._selectedIds.indexOf(String(b.id));-1<e?(d=!1,this._selectedIds.splice(e,1)):this._selectedIds.push(String(b.id))}c.rowSelectCell.toggleRow(a,d);this._updateContent(!1)},toggleSelectAll:function(a,c){if(a){var b=this.grid.layer("filter")._items.length?this.grid.layer("filter")._items:this.grid.store._arrayOfAllItems;if(b.length){var d=this;this._selectedIds=Array(b.length);dojo.forEach(b,function(a,b){d._selectedIds[b]=String(a.id)})}}else if(this._selectedIds=[],this.grid.selection.deselectAll(),
b=dojo.byId(this.grid.id+"_rowSelector_-1"))g.toggleClass(b,"dijitCheckBoxChecked",!1),b.setAttribute("aria-checked",!1);this._updateContent(c)},_updateContent:function(a){this.dropDownButton._hidden.value=this._selectedIds.join(",");this.dropDownButton.set("label",e.replace(h.multiSelectLabelText,{num:this._selectedIds.length}));a||this.dropDownButton.defer("onClick");setTimeout(e.hitch(this,"focus"),10)},orient:function(a,c,b){a={"MR-ML":"dijitTooltipRight","ML-MR":"dijitTooltipLeft","TM-BM":"dijitTooltipAbove",
"BM-TM":"dijitTooltipBelow","BL-TL":"dijitTooltipBelow dijitTooltipABLeft","TL-BL":"dijitTooltipAbove dijitTooltipABLeft","BR-TR":"dijitTooltipBelow dijitTooltipABRight","TR-BR":"dijitTooltipAbove dijitTooltipABRight","BR-BL":"dijitTooltipRight","BL-BR":"dijitTooltipLeft"}[c+"-"+b];p.replace(this.domNode,a,this._currentOrientClass||"");this._currentOrientClass=a},focus:function(){this._getFocusItems();r.focus(this._firstFocusItem)},onOpen:function(a){this.orient(this.domNode,a.aroundCorner,a.corner);
if(this.grid&&this.isResetDataStore){this.grid.selection.deselectAll();this.grid.layer("filter").filterDef(null);(a=dijit.byId(this.grid.id+"_dropDownFilterTextBox"))&&a.set("value",null);this.grid.store.close();this.grid.set("store",this.dropDownButton.dataStore);this.grid._refresh();a=this.grid.layer("filter")._items.length?this.grid.layer("filter")._items:this.grid.store._arrayOfAllItems;if(a.length&&this._selectedIds.length)for(var c=0;c<this._selectedIds.length;c++)for(var b=0;b<a.length;b++)String(a[b].id)==
String(this._selectedIds[c])&&this.grid.rowSelectCell.toggleRow(this.grid.getItemIndex(a[b]),!0);this._updateContent(!0);this.isResetDataStore=!1}this._onShow()},_getFocusItems:function(){this._lastFocusItem=this._firstFocusItem=dojo.byId(this.grid.id+"_dropDownFilterTextBox")},onClose:function(){this.onHide()},close:function(){this.defer("onCancel")},destroy:function(){this.dropDownButton=this.grid=null;l.forEach(this._connects,f.disconnect);delete this._connects}});return dojo.declare("buildspace.widget.forms.MultiSelectDropDown",
[t],{dataStore:null,storeSort:null,dataCarrierId:"",dropDownWidth:null,_hidden:null,baseClass:"multiSelectDropDown",postMixInProperties:function(){this.inherited(arguments);this.label=e.replace(h.multiSelectLabelText,{num:0});if(!this.dataStore)throw"Data store must be provided";this.storeSort||(this.storeSort=[{attribute:this.textField}]);this.dropDown=new D({dropDownButton:this,className:"multiSelectDropDown",style:"border:none;"+(this.dropDownWidth?"width:"+this.dropDownWidth+";":"")})},postCreate:function(){this.inherited(arguments);
if(this.dataCarrierId)this._hidden=dojo.byId(this.dataCarrierId);else{var a=this._hidden=document.createElement("input");a.type="hidden";a.name=this.name;a.value="";dojo.place(a,this.domNode)}},resetDataStore:function(a){this.dataStore=a;this.dropDown.store=this.dataStore;this.dropDown.isResetDataStore=!0;a=a.hasOwnProperty("_jsonData")?a._jsonData.items:[];var c=[];if(a.length)for(var b=this.getSelectedIds(),d=0;d<a.length;d++)-1!==b.indexOf(String(a[d].id))&&c.push(String(a[d].id));this.dropDown._selectedIds=
c;this.dropDown._updateContent(!0)},focus:function(){},getSelectedIds:function(){return this.dropDown.getSelectedIds()},_onClick:function(a){q.stop(a)},onClick:function(a){}})});
