define("buildspace/apps/PostContract/BillManager/ApplyToUnitDialog","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/layout/ContentPane dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!buildspace/nls/PostContract".split(" "),function(e,p,f,q,r,t,g,h,u,v,w,x,k,l,m,y,d){var n=
e("buildspace.apps.PostContract.BillManager.ApplyGrid",l,{rootProject:null,style:"border:none;",region:"center",pageId:null,billId:null,dialogObj:null,columnSettingId:null,url:null,typeItem:null,keepSelection:!0,rowSelector:"0px",constructor:function(a){this.structure={noscroll:!1,cells:[[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:(new m).rowCountCellFormatter},{name:d.description,field:"description",width:"auto"}]]};this.counterIds=[];this.connects=[];this.plugins=
{indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"}};this.inherited(arguments)},postCreate:function(){var a=this;a.inherited(arguments);this._connects.push(f.connect(this,"onCellClick",function(b){a.selectTree(b)}));this._connects.push(f.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)}))},selectTree:function(a){var b=a.rowIndex;a=this.selection.selected[b];if(b=this.getItem(b))this.pushItemIdIntoGridArray(b,a),0<this.counterIds.length?
this.dialogObj.saveBtn.set("disabled",!1):this.dialogObj.saveBtn.set("disabled",!0)},pushItemIdIntoGridArray:function(a,b){var c=dojo.indexOf(this.counterIds,a.count[0]);b?-1==c&&-1!=a.count[0]&&this.counterIds.push(a.count[0]):-1!=c&&this.counterIds.splice(c,1)},toggleAllSelection:function(a){var b=this,c=b.selection;a?(c.selectRange(0,b.rowCount-1),b.counterIds=[],b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.count&&b.counterIds.push(a.count[0])})}})):(c.deselectAll(),b.counterIds=
[]);0<b.counterIds.length?b.dialogObj.saveBtn.set("disabled",!1):b.dialogObj.saveBtn.set("disabled",!0)},canSort:function(a){return!1},save:function(){var a=this,b=a.counterIds;if(0<b.length){a.dialogObj.hide();var c=buildspace.dialog.indeterminateProgressBar({title:d.processing+". "+d.pleaseWait+"..."});c.show();dojo.xhrPost({url:a.url,content:{counters:[b],bill_column_setting_id:a.columnSettingId,id:a.rootProject.id,type_ref_id:a.typeItem.id},handleAs:"json",load:function(b){a.counterIds=[];c.hide()},
error:function(b){a.counterIds=[];c.hide()}})}},reload:function(){this.store.close();this._refresh()}});return e("buildspace.apps.PostContract.BillManager.ApplyDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:d.applyToOtherUnit,rootProject:null,typeItem:null,billId:null,elementId:null,url:null,buildRendering:function(){var a=this.createForm();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){h.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display=
"none";this.inherited(arguments)},_onKey:function(a){a.keyCode==g.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createForm:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:580px;height:380px;",gutters:!1}),b=new dijit.layout.BorderContainer({style:"padding:0px;height:90px;",gutters:!1,region:"top"}),c=dojo.data.ItemFileWriteStore({url:"postContractStandardBillClaim/getUnitList/id/"+this.typeItem.relation_id+"/exc_count/"+this.typeItem.count,clearOnClose:!0}),
e=new n({dialogObj:this,title:this.title,rootProject:this.rootProject,store:c,columnSettingId:this.typeItem.relation_id,typeItem:this.typeItem,url:this.url}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));c.addChild(new dijit.ToolbarSeparator);c.addChild(this.saveBtn=new dijit.form.Button({label:d.save,
id:this.billId+this.elementId+"saveRow-button",iconClass:"icon-16-container icon-16-save",disabled:!0,onClick:function(){e.save()}}));b.addChild(c);b.addChild(new k({content:d.applyNote,region:"center",style:"padding:20px 30px 20px 30px; text-align:center"}));a.addChild(b);a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:e,region:"center"}));return a}})});
