// Generated by CoffeeScript 1.9.0
(function() {
  define(['dojo/_base/declare', 'dojo/parser', 'dijit/_WidgetBase', 'dijit/_OnDijitClickMixin', 'dijit/_TemplatedMixin', 'dijit/_WidgetsInTemplateMixin', 'dojox/validate/web', 'dojox/form/Manager', 'dijit/form/ValidationTextBox', 'dojo/dom-form', 'dojo/text!./templates/standardPhrasesForm.html'], function(declare, parser, _WidgetBase, _OnDijitClickMixin, _TemplatedMixin, _WidgetsInTemplateMixin, web, Manager, ValidationTextBox, domForm, template) {
    var form;
    form = declare('buildspace.apps.ProjectBuilder.SupplyOfMaterialBillPrintoutSetting.StandardPhrasesForm', [_WidgetBase, _OnDijitClickMixin, _TemplatedMixin, _WidgetsInTemplateMixin], {
      baseClass: "buildspace-form",
      templateString: template,
      somBillLayoutSettingId: 1,
      data: null,
      startup: function() {
        this.inherited(arguments);
        return this["somBillPrintingForms-" + this.somBillLayoutSettingId].setFormValues(this.data);
      },
      validateForm: function() {
        var formID, formValues, postContent;
        this.inherited(arguments);
        if (!this["somBillPrintingForms-" + this.somBillLayoutSettingId].validate()) {
          return false;
        }
        formID = this["somBillPrintingForms-" + this.somBillLayoutSettingId].id;
        formValues = domForm.toJson(formID);
        return postContent = {
          somBillLayoutSettingId: this.somBillLayoutSettingId,
          content: formValues,
          type: 'summaryPhrases'
        };
      }
    });
    return form;
  });

}).call(this);
