define("buildspace/apps/PostContract/PostContractClaim/PostContractClaimClaimGrid","dojo/_base/declare dojo/_base/lang dojo/_base/html dijit/focus dojo/_base/event dojo/keys dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(m,n,w,g,x,y,p,q,d){var r=function(a,b,c){b=this.grid.getItem(b);c.customClasses.push("disable-cell");return b&&!isNaN(parseInt(String(b.id)))?d.version+" "+d.no+" "+a:"&nbsp;"},t=function(a,b,c){if((b=this.grid.getItem(b))&&
!isNaN(parseInt(String(b.id))))return a?'<span class="icon-16-container icon-16-checkmark2" style="margin:0px auto; display:block;"></span>':'<a href="#" onclick="return false;">'+d.printThisRevision+"</a>";c.customClasses.push("disable-cell");return"&nbsp;"},u=function(a,b,c){b=this.grid.getItem(b);b.can_be_edited[0]||c.customClasses.push("disable-cell");return b&&!isNaN(parseInt(String(b.id)))?1==parseInt(a)?d.addendumProgressing:d.addendumLocked:"&nbsp;"},v=m("buildspace.apps.PostContract.PostContractClaim.PostContractClaimClaimEnhancedGrid",
p,{style:"border-top:none;",rowSelector:"0px",project:null,postContractClaim:null,postContractClaimItemContainer:null,region:"center",constructor:function(a){a=new q;var b=[d.addendumProgressing,d.addendumLocked],c=[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:d.claimVersion,field:"revision",width:"auto",formatter:r}];c.push({name:d.claimCertificateNumber,field:"claim_cert_number",styles:"text-align:center;",width:"100px",noresize:!0});dojo.forEach([{name:d.currentPrintingRevision,
field:"is_viewing",width:"140px",styles:"text-align: center;",formatter:t},{name:d.status,field:"status",width:"120px",styles:"text-align: center;",editable:!0,cellType:"dojox.grid.cells.Select",options:b,values:[1,2],formatter:u},{name:d.lastUpdated,field:"updated_at",width:"120px",styles:"text-align: center;"}],function(b){c.push(b)});this.structure=c},canSort:function(a){return!1},postCreate:function(){this.inherited(arguments);this.on("RowClick",function(a){(a=this.getItem(a.rowIndex))&&!isNaN(parseInt(String(a.id)))&&
a.can_be_deleted[0]?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0)});this.on("CellClick",function(a){var b=a.cell.field;a=this.getItem(a.rowIndex);"is_viewing"!=b||!a||isNaN(parseInt(String(a.id)))||a.is_viewing[0]||this.changeCurrentViewingRevision(a)})},canEdit:function(a,b){var c=this;if(void 0==a||this.getItem(b).can_be_edited[0])return this._canEdit;window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10)},doApplyCellEdit:function(a,b,c){var f=this,e=
this.getItem(b),h=this.store,k=function(){var l=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});l.show().then(function(){dojo.xhrPost({url:"postContractClaim/claimUpdate",content:{id:e.id,attr_name:c,val:a,_csrf_token:e._csrf_token?e._csrf_token:null},handleAs:"json",load:function(a){if(a.success){for(var d in a.data)e.hasOwnProperty(d)&&d!=h._getIdentifierAttribute()&&h.setValue(e,d,a.data[d]);h.save();2==e.status?dijit.byId("postContractClaimClaim-"+f.postContractClaim.id+
"AddRow-button")._setDisabledAttr(!1):1==e.status&&dijit.byId("postContractClaimClaim-"+f.postContractClaim.id+"AddRow-button")._setDisabledAttr(!0);var k=f.getCellByField(c);window.setTimeout(function(){f.focus.setFocusIndex(b,k.index)},10);dojo.xhrGet({url:"postContractClaim/getClaimStatus",content:{id:f.postContractClaim.id},handleAs:"json"}).then(function(b){dojo.xhrGet({url:"postContractClaim/getUnits",handleAs:"json"}).then(function(a){f.postContractClaimItemContainer.createPostContractClaimItemGrid(a,
b,!1)})})}l.hide()},error:function(b){l.hide()}})})};a===e[c][0]||isNaN(parseInt(String(e.id)))||("status"==c&&2==a?buildspace.dialog.confirm(d.confirmSubmit,d.cannotBeUndone,60,200,function(){k()},function(){h.setValue(e,"status",1)}):k());this.inherited(arguments)},addNewClaim:function(a){g.curNode.blur();g.curNode=null;var b=this,c=buildspace.dialog.indeterminateProgressBar({title:d.addingRow+". "+d.pleaseWait+"..."}),f=this.store;dojo.xhrGet({url:"postContractClaim/getClaimStatus",content:{id:b.postContractClaim.id},
handleAs:"json"}).then(function(e){new buildspace.dialog.confirm(d.addNewClaim,0==e.count?d.confirmAddFirstPostContractNewClaimTitleMsg:d.confirmAddPostContractNewClaimTitleMsg,90,380,function(){c.show().then(function(){dojo.xhrPost({url:"postContractClaim/claimAdd",content:{id:b.postContractClaim.id,_csrf_token:a},handleAs:"json",load:function(a){a.success&&(f.close(),b._refresh(),dijit.byId("postContractClaimClaim-"+b.postContractClaim.id+"AddRow-button")._setDisabledAttr(!0),dojo.xhrGet({url:"postContractClaim/getUnits",
handleAs:"json"}).then(function(a){dojo.xhrGet({url:"postContractClaim/getClaimStatus",content:{id:b.postContractClaim.id},handleAs:"json",load:function(c){b.postContractClaimItemContainer.createPostContractClaimItemGrid(a,c,!1)}})}));b.selection.clear();b.disableToolbarButtons(!0);c.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);c.hide()}})})},function(){})})},deleteRow:function(){var a=this.getItem(this.selection.selectedIndex);g.curNode.blur();g.curNode=null;if(-1<this.selection.selectedIndex&&
a&&!isNaN(parseInt(a.id[0]))&&a.can_be_deleted[0]){var b=this,c=this.store,f=buildspace.dialog.indeterminateProgressBar({title:d.deleting+". "+d.pleaseWait+"..."}),e={url:"postContractClaim/claimDelete",content:{id:a.id,_csrf_token:a._csrf_token},handleAs:"json",load:function(a){a.success&&(c.close(),b._refresh(),dijit.byId("postContractClaimClaim-"+b.postContractClaim.id+"AddRow-button")._setDisabledAttr(!1),dojo.xhrGet({url:"postContractClaim/getClaimStatus",content:{id:b.postContractClaim.id},
handleAs:"json"}).then(function(a){dojo.xhrGet({url:"postContractClaim/getUnits",handleAs:"json"}).then(function(c){b.postContractClaimItemContainer.createPostContractClaimItemGrid(c,a,!1)})}));f.hide();b.selection.clear();b.disableToolbarButtons(!0)},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);f.hide()}};new buildspace.dialog.confirm(d.deletePostContractClaimClaimDialogBoxTitle,d.deletePostContractClaimClaimDialogBoxMsg,90,380,function(){f.show().then(function(){dojo.xhrPost(e)})},
function(){})}},changeCurrentViewingRevision:function(a){var b=this,c=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});g.curNode.blur();g.curNode=null;c.show().then(function(){dojo.xhrPost({url:"postContractClaim/viewClaimRevision",content:{id:a.id,_csrf_token:a._csrf_token},handleAs:"json",load:function(a){if(a.success){var d=b.store;dojo.forEach(a.items,function(a){d.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var c in a)b.hasOwnProperty(c)&&c!=d._getIdentifierAttribute()&&
d.setValue(b,c,a[c])}})});d.save();dojo.xhrGet({url:"postContractClaim/getClaimStatus",content:{id:b.postContractClaim.id},handleAs:"json"}).then(function(a){dojo.xhrGet({url:"postContractClaim/getUnits",handleAs:"json"}).then(function(c){b.postContractClaimItemContainer.createPostContractClaimItemGrid(c,a,!1)})})}c.hide();b.selection.clear();b.disableToolbarButtons(!0)},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);c.hide()}})})},disableToolbarButtons:function(a){var b=dijit.byId("postContractClaimClaim-"+
this.postContractClaim.id+"DeleteRow-button");b&&b._setDisabledAttr(a)}});return m("buildspace.apps.PostContract.PostContractClaim.PostContractClaimClaim",dijit.layout.BorderContainer,{style:"padding:0;margin:0;border:0px;width:100%;height:100%;",gutters:!1,project:null,postContractClaim:null,postContractClaimItemContainer:null,claimStatus:null,claimCertificate:null,locked:!1,postCreate:function(){this.inherited(arguments);var a="postContractClaim/getClaimList/id/"+this.postContractClaim.id;this.claimCertificate&&
(a+="/claimRevision/"+this.claimCertificate.post_contract_claim_revision_id);var b=new dojo.data.ItemFileWriteStore({url:a,clearOnClose:!0}),a=this.claimStatus._csrf_token,b=new v({project:this.project,postContractClaim:this.postContractClaim,postContractClaimItemContainer:this.postContractClaimItemContainer,claimCertificate:this.claimCertificate,store:b});if(!this.locked){var c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({id:"postContractClaimClaim-"+
this.postContractClaim.id+"AddRow-button",label:d.addNewClaim,iconClass:"icon-16-container icon-16-add",disabled:this.postContractClaim.status[0]==buildspace.apps.PostContract.ProjectStructureConstants.STATUS_APPROVED&&this.claimStatus.can_add_new_claim?!1:!0,onClick:n.hitch(b,"addNewClaim",a)}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"postContractClaimClaim-"+this.postContractClaim.id+"DeleteRow-button",label:d.deleteRow,iconClass:"icon-16-container icon-16-delete",
onClick:n.hitch(b,"deleteRow")}))}c&&this.addChild(c);this.addChild(b)}})});
