define("buildspace/apps/PostContract/Preliminaries/PreliminariesBillGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dijit/Menu dojo/number dijit/CheckedMenuItem dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dijit/PopupMenuItem dijit/MenuSeparator buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract dojo/on dojox/grid/_Grid dojox/widget/PlaceholderMenuItem buildspace/widget/grid/cells/TextBox".split(" "),
function(l,m,u,v,w,x,y,z,A,n,p,B,C,D,E,F,G,H,I,J,K,L,M,N,q,d,O){var t=l("buildspace.apps.PostContract.Preliminaries.PreliminariesBillGrid",dojox.grid.EnhancedGrid,{type:null,billId:-1,elementId:0,itemId:-1,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",headerMenu:null,typeColumns:null,markupSettings:null,parentGrid:null,elementGridStore:null,currentGridType:"element",typeColumsToQtyUsed:[],currentSelectedClaimRevision:null,currentClaimRevision:null,
constructor:function(a){this.type=a.type;this.hierarchyTypes=a.hierarchyTypes;this.hierarchyTypesForHead=a.hierarchyTypesForHead;this.unitOfMeasurements=a.unitOfMeasurements;this.columnGroup=a.columnGroup;this.typeColumns=a.typeColumns;this.markupSettings=a.markupSettings;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;this.currentGridType=a.currentGridType;this.gridEditable=a.editable;a=this.formatter=new q;this.typeColumns=
"tree"!=this.type?this.recurringElementGridStructure():this.recurringItemGridStructure();this.typeColumnChildren=[{name:d.percent,field_name:"percentage",width:"60px",styles:"text-align:right;",formatter:a.prelimPercentFormatter,cellType:"buildspace.widget.grid.cells.FormulaTextBox"},{name:d.amount,field_name:"amount",width:"100px",styles:"text-align:right;",formatter:a.prelimAmountFormatter,cellType:"buildspace.widget.grid.cells.FormulaTextBox"}];this.rearranger=n(this,{});this.formulatedColumn=
p(this,{});this.setColumnStructure();this.createHeaderCtxMenu()},canSort:function(a){return!1},doApplyCellEdit:function(a,c,b){var e=this,f=e.getItem(c),r=e.store;if(f[b]&&a!==f[b][0]){var g=buildspace.dialog.indeterminateProgressBar({title:d.savingData+". "+d.pleaseWait+"..."});a||(a=0);var h={id:f.post_contract_bill_item_rate_id,attr_name:b,val:a,bill_id:e.billId,revision_id:e.currentClaimRevision.id,_csrf_token:f._csrf_token?f._csrf_token:null},k=function(a,b){for(var c in a)f.hasOwnProperty(c)&&
c!=b._getIdentifierAttribute()&&b.setValue(f,c,a[c]);b.save()};g.show();dojo.xhrPost({url:"postContractPreliminaries/updateItemClaim",content:h,handleAs:"json",load:function(a){if(a.success){0<f.id&&k(a.item,r);var d=e.getCellByField(b);window.setTimeout(function(){e.focus.setFocusIndex(c,d.index)},10);g.hide()}},error:function(a){g.hide()}})}else e.inherited(arguments)},canEdit:function(a,c){var b=this,e=this.getItem(c);if(!b.gridEditable)return!1;if("tree"==this.type){if(void 0!=e&&0<e.id[0]&&void 0!=
a){var d=a.field.split("-");if(1<d.length){if(!(e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID||"percentage"===d[1]&&"amount"===d[1])){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);return}if(d[0]==buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_INITIAL){if("true"==e.include_initial[0]){window.setTimeout(function(){b.edit.cancel();
b.focus.setFocusIndex(c,a.index)},10);return}if(0!=e["previousClaim-amount"][0]){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);return}}else if(d[0]==buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_FINAL){if("true"==e.include_final[0]){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);return}if(0!=e["previousClaim-amount"][0]){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);
return}}}else{if(e.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||e.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||e.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);return}if("rate"===d[0]){if(e.type!=buildspace.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);return}if(0!=e["previousClaim-amount"][0]){window.setTimeout(function(){b.edit.cancel();
b.focus.setFocusIndex(c,a.index)},10);return}}else{if("include_initial"===d[0]&&e.initial_include_at_revision_id[0]!=b.currentClaimRevision.id){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);return}if("include_final"===d[0]&&e.final_include_at_revision_id[0]!=b.currentClaimRevision.id){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);return}}}return this._canEdit}}else window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c)},
10)},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},setColumnStructure:function(){var a=this.formatter,c="auto";if(1<this.typeColumns.length||this.markupSettings.bill_markup_enabled||this.markupSettings.element_markup_enabled||this.markupSettings.item_markup_enabled)c="500px";if("tree"==this.type){var b=this.unitOfMeasurements;c=this.fixedColumns={noscroll:!1,width:57.8,cells:[[{name:"No",field:"id",styles:"text-align:center;",
width:"30px",formatter:a.rowCountCellFormatter,noresize:!0,rowSpan:2,showInCtxMenu:!0},{name:d.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,hidden:!0,rowSpan:2,showInCtxMenu:!0,formatter:a.billRefCellFormatter},{name:d.description,field:"description",width:c,editable:!1,cellType:"buildspace.widget.grid.cells.Textarea",formatter:a.treeCellFormatter,noresize:!0,rowSpan:2,showInCtxMenu:!0},{name:d.voOmittedAt,field:"omitted_at_vo",width:"90px",styles:"text-align: center;",
showInCtxMenu:!0,noresize:!0,rowSpan:2,editable:!1,formatter:a.unEditableCellFormatter},{name:d.quantity,field:"qty-qty_per_unit",styles:"text-align:right;",width:"90px",formatter:a.postContractPreliminariesQuantityCellFormatter,noresize:!0,hidden:!0,rowSpan:2,showInCtxMenu:!0},{name:d.unit,field:"uom_id",width:"70px",editable:!1,styles:"text-align:center;",type:"dojox.grid.cells.Select",options:b.options,values:b.values,formatter:a.unitIdCellFormatter,noresize:!0,rowSpan:2,hidden:!0,showInCtxMenu:!0},
{name:d.rate,field:"rate",styles:"text-align:right;",width:"75px",editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.formulaPrelimCurrencyCellFormatter,noresize:!0,rowSpan:2,hidden:!0,showInCtxMenu:!0},{name:d.itemTotal,field:"item_total",styles:"text-align:right;color:blue;",width:"75px",editable:!1,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.unEditableNumberCellFormatter,noresize:!0,rowSpan:2}]]};b=[d.includeCapital,d.excludeCapital];var e=["true",
"false"];b=[{name:d.includeInitial,field:"include_initial",width:"100px",styles:"text-align:center;",type:"dojox.grid.cells.Select",options:b,values:e,rowSpan:2,formatter:a.yesNoCellFormatter,editable:!0},{name:d.includeFinal,field:"include_final",width:"100px",styles:"text-align:center;",type:"dojox.grid.cells.Select",options:b,values:e,rowSpan:2,formatter:a.yesNoCellFormatter,editable:!0}];var f=this.constructTypeColumnStructure(c)}else{c="auto";if(1<this.typeColumns.length||this.markupSettings.bill_markup_enabled||
this.markupSettings.element_markup_enabled||this.markupSettings.item_markup_enabled)c="500px";c=this.fixedColumns={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0,rowSpan:2},{name:d.description,field:"description",width:c,editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:a.treeCellFormatter,noresize:!0,rowSpan:2},{name:d.omittedItems,field:"vo_omitted_items",width:"45px",styles:"text-align: center;",
editable:!1,noresize:!0,showInCtxMenu:!0,rowSpan:2,formatter:a.unEditableCellFormatter},{name:d.grandTotal,field:"grand_total",styles:"text-align:right;color:blue;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,rowSpan:2,noresize:!0,showInCtxMenu:!0}]]};b=[];f=this.constructTypeColumnStructure(c)}b.unshift({name:d.importedUpToDateClaim,field:"imported_up_to_date_amount",width:"90px",styles:"text-align: right;",formatter:a.unEditableCurrencyCellFormatter,showInCtxMenu:!0,rowSpan:2});dojo.forEach(b,
function(a){f.cells[0].push(a)});this.structure=f},constructTypeColumnStructure:function(a){var c=this,b=this.typeColumnChildren,d=[],f=0;dojo.forEach(this.typeColumns,function(e){c.typeColumsToQtyUsed[e.id]=e.use_original_quantity;var g=b.length;f++;d.push({name:e.name,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+f,colSpan:g});for(i=0;i<b.length;i++){var h=e.field_name,k=!0;g=h+"-"+b[i].field_name;if("tree"==c.type){if(h==buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_RECURRING||
h==buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED||h==buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED||h==buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_PREVIOUSCLAIM||h==buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_CURRENTCLAIM||h==buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_UPTODATECLAIM)k=!1}else k=!1;g={field:g,columnType:"prelimClaimColumn",editable:k,fieldName:e.field_name};
m.mixin(g,b[i]);a.cells[0].push(g)}});a.cells.push(d);return a},createHeaderCtxMenu:function(){if("undefined"!==typeof this.fixedColumns){var a=this.fixedColumns.cells[0],c=this,b={headerMenu:new dijit.Menu};dojo.forEach(a,function(a,d){a.showInCtxMenu&&b.headerMenu.addChild(new dijit.CheckedMenuItem({label:a.name,checked:"undefined"===typeof a.hidden||!1===a.hidden?!0:!1,onChange:function(a){var b=!1;a&&(b=!0);c.showHideMergedColumn(b,d)}}))});this.plugins={menus:b}}},showHideMergedColumn:function(a,
c){this.beginUpdate();this.layout.setColumnVisibility(c,a);this.endUpdate()},refreshGrid:function(){this.beginUpdate();this.set("structure",this.structure);this.store.close();this.pluginMgr=new this._pluginMgrClass(this);this.pluginMgr.preInit();this.pluginMgr.postInit();this.pluginMgr.startup();this._refresh();this.endUpdate()},editableCellDblClick:function(a){var c=1<this._click.length&&has("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=this._click[1].rowIndex?this._click[0]:
a;this.focus.setFocusCell(c.cell,c.rowIndex);this.onRowClick(c);this.onRowDblClick(a)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);else this.onCellDblClick(a);else this.onRowDblClick(a)},doEditItemNote:function(a){},doEditTradeNote:function(a){},onHeaderCellClick:function(a){dojo.hasClass(a.cell.id,"staticHeader")||(a.grid.setSortIndex(a.cell.index),a.grid.onHeaderClick(a))},onHeaderCellMouseOver:function(a){dojo.hasClass(a.cell.id,"staticHeader")||dojo.addClass(a.cellNode,
this.cellOverClass)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var c=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children;c.parentNode.removeChild(c);dojo.forEach(b,function(a,b){b=dojo.attr(a,"rowSpan");(!b||2>b)&&dojo.attr(a,"rowSpan",2)})}},recurringElementGridStructure:function(){typeColumns=[];for(var a=[{name:d.previousClaim,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_PREVIOUSCLAIM},
{name:d.currentClaim,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_CURRENTCLAIM},{name:d.upToDateClaim,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_UPTODATECLAIM}],c=a.length,b=0;b<c;b++)typeColumns.push({name:a[b].name,field_name:a[b].field_name});return typeColumns},recurringItemGridStructure:function(){typeColumns=[];for(var a=[{name:d.initial,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_INITIAL},
{name:d.recurring,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_RECURRING},{name:d.timeBased,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_TIMEBASED},{name:d.workBased,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_WORKBASED},{name:d.final,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_FINAL},{name:d.previousClaim,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_PREVIOUSCLAIM},
{name:d.currentClaim,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_CURRENTCLAIM},{name:d.upToDateClaim,field_name:buildspace.apps.PostContract.ProjectStructureConstants.PRELIM_COLUMN_UPTODATECLAIM}],c=a.length,b=0;b<c;b++)typeColumns.push({name:a[b].name,field_name:a[b].field_name});return typeColumns}});return l("buildspace.apps.PostContract.BillManager.PreliminariesBillGridBuilder",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;width:100%;height:100%;",
gutters:!1,stackContainerTitle:"",rootProject:null,billId:-1,elementId:0,itemId:-1,rowSelector:null,gridOpts:{},type:null,postCreate:function(){this.inherited(arguments);m.mixin(this.gridOpts,{billId:this.billId,elementId:this.elementId,type:this.type,region:"center",borderContainerWidget:this});var a=this.grid=new t(this.gridOpts);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));var c=dijit.byId("billGrid"+this.billId+"-stackContainer");if(c){var b=document.createElement("div");
a=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,45),id:this.pageId,content:this,grid:a},b);c.addChild(a);c.selectChild(this.pageId)}}})});
