(function(){define("buildspace/apps/SubPackage/ExportSubPackageByContractorDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json dojo/number dojo/currency ./ImportSubPackageByContractorDialog ./ExportExcelSubPackageByContractorDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(f,r,t,u,v,w,x,l,m,g,y,z,A,n,p,q,d){var h,k;h=f("buildspace.apps.SubPackage.SelectedItemGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",escapeHTMLInData:!1,subPackage:null,company:null,subPackageGrid:null,subContractorGridContainer:null,postCreate:function(){var b;b=this;b.inherited(arguments);return this.on("CellClick",function(a){var c;c=a.cell.field;a=b.getItem(a.rowIndex);"import_link"===c&&0<a.id[0]&&b.createImportSubPackageByContractorDialog(a);if("export_link"===c&&0<a.id[0])return b.createExportSubPackageByContractorDialog(a)})},canSort:function(){return!1},
createImportSubPackageByContractorDialog:function(b,a){var c;null==a&&(a=this);c=new buildspace.dialog.indeterminateProgressBar({title:d.processing+"..."});c.show();return g.get("subPackage/getImportExportPermission",{query:{id:a.subPackage.id,company_id:a.company.id},handleAs:"json"}).then(function(e){c.hide();return(new n({title:d.importContractorRates+" ("+b.title[0]+")",subPackage:a.subPackage,company:a.company,bill:b,formInfo:e,subPackageGrid:a.subPackageGrid,subContractorGridContainer:a.subContractorGridContainer})).show()},
function(a){return c.hide()})},createExportSubPackageByContractorDialog:function(b,a){var c;null==a&&(a=this);c=new buildspace.dialog.indeterminateProgressBar({title:d.processing+"..."});c.show();return g.get("subPackage/getImportExportPermission",{query:{id:a.subPackage.id,company_id:a.company.id},handleAs:"json"}).then(function(e){c.hide();return(new p({title:d.exportSubPackageExcel+" ("+b.title[0]+")",subPackage:a.subPackage,company:a.company,bill:b,formInfo:e})).show()},function(a){return c.hide()})}});
k=f("buildspace.apps.SubPackage.SelectedItemGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,subPackage:null,company:null,dialog:null,store:null,structure:null,subPackageGrid:null,subContractorGridContainer:null,postCreate:function(){var b,a,c;a=this;a.inherited(arguments);b=this.grid=new h({store:a.store,structure:a.structure,subPackage:a.subPackage,company:a.company,subPackageGrid:a.subPackageGrid,subContractorGridContainer:a.subContractorGridContainer});
c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return a.dialog.hide()}}));a.addChild(c);return a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))}});return f("buildspace.apps.SubPackage.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,data:null,subPackage:null,company:null,
columnSettings:null,subPackageGrid:null,subContractorGridContainer:null,buildRendering:function(){var b;b=this.createContent();b.startup();this.content=b;return this.inherited(arguments)},postCreate:function(){m.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(b){if(b.keyCode===l.ESCAPE)return dojo.stopEvent(b)},onHide:function(){return this.destroyRecursive()},createContent:function(b){var a;null==b&&
(b=this);a=new dijit.layout.BorderContainer({style:"padding:0px;width:780px;height:380px;",gutters:!1});b=new k({dialog:b,structure:b.constructGridStructure(),subPackage:b.subPackage,company:b.company,store:dojo.data.ItemFileWriteStore({data:b.data}),subPackageGrid:b.subPackageGrid,subContractorGridContainer:b.subContractorGridContainer});a.addChild(b);return a},constructGridStructure:function(b){null==b&&(b=this);return{noscroll:!1,width:"50",cells:[[{name:"No",field:"id",width:"30px",styles:"text-align: center;",
formatter:(new q).rowCountCellFormatter},{name:d.description,field:"title",width:"auto",noresize:!0},{name:d["import"],field:"import_link",width:"120px",styles:"text-align: center;",noresize:!0,formatter:function(a,b,e){return 0<this.grid.getItem(b).id[0]?'<a href="#" onclick="return false;">'+d["import"]+"</a>":null}},{name:d["export"],field:"export_link",width:"120px",styles:"text-align: center;",noresize:!0,formatter:function(a,b,e){return 0<this.grid.getItem(b).id[0]?'<a href="#" onclick="return false;">'+
d["export"]+"</a>":null}}]]}}})})}).call(this);
