define("buildspace/apps/SubPackage/grid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange dojo/_base/event dojo/keys dijit/focus dojo/when dojo/request/xhr dijit/PopupMenuItem buildspace/widget/grid/cells/Textarea ./ImportResourceItemDialog ./ImportScheduleOfRateItemDialog ./ImportBillItemDialog ./AssignContractorDialog ./BillPrintoutSetting/printSettingDialog ./BillPrintoutSetting/PrintBillDialog ./ResourceFilterDialog ./PushToPostContractDialog dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dojo/i18n!buildspace/nls/SubPackages".split(" "),
function(q,l,J,K,L,M,u,v,w,m,r,N,O,P,x,y,z,A,B,C,D,E,F,G,n,f){var I=q("buildspace.apps.SubPackage.Grid",dojox.grid.EnhancedGrid,{type:null,subPackage:null,contId:0,rootProject:null,style:"border-top:none;",selectedItem:null,keepSelection:!0,rowSelector:"0px",addUrl:null,updateUrl:null,deleteUrl:null,pasteUrl:null,region:"center",constructor:function(a){this.rearranger=new u(this,{});this.structure=a.structure;"sub_packages-bill_item_list"===a.type&&this.createHeaderCtxMenu()},canSort:function(a){return!1},
postCreate:function(){var a=this;a.inherited(arguments);"sub_packages-list"==this.type&&(this.on("RowContextMenu",function(b){a.selection.clear();var c=a.getItem(b.rowIndex);a.selection.setSelected(b.rowIndex,!0);a.contextMenu(b);0<c.id?a.disableToolbarButtons(!1):a.disableEditing?a.disableToolbarButtons(!0):a.disableToolbarButtons(!0,["Add"])},!0),this.on("RowClick",function(b){var c=a.getItem(b.rowIndex);c&&0<parseInt(String(c.id))?(a.disableToolbarButtons(!1),"sub_packages-list"==a.type&&(c.locked[0]?
a.disableToolbarButtons(!0,["Add"]):null==c.selected_company_id[0]&&a.disableToolbarButtons(!0,"Add Delete ImportResourceItem ImportScheduleOfRateItem ImportBillItem ImportDropDown AssignSubContractors PrintSetting PrintBQ ExportSubPackage".split(" ")),b.cell&&"filter"==b.cell.field&&(new D({subPackage:c})).show())):a.disableEditing?a.disableToolbarButtons(!0):a.disableToolbarButtons(!0,["Add"])}))},canEdit:function(a,b){var c=this;if("sub_packages-list"==this.type&&void 0!=a){var e=this.getItem(b);
if(e.locked[0]){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}}if("sub_packages-bill_item_list"==this.type&&void 0!=a&&(e=this.getItem(b),0>=e.id[0]||e.hasOwnProperty("type")&&(e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||e.type[0]==buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID||1>e.type[0]))){window.setTimeout(function(){c.edit.cancel();c.focus.setFocusIndex(b,a.index)},10);return}return this._canEdit},doApplyCellEdit:function(a,
b,c){var e=this,d=e.getItem(b),k=e.store,h=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."}),g=c.replace("rate-value-","");if(a!==d[c][0]){var p={id:d.id,attr_name:g,val:a,_csrf_token:d._csrf_token?d._csrf_token:null},t=this.updateUrl;"sub_packages-bill_item_list"==this.type&&l.mixin(p,{sid:this.subPackage.id});d.id==buildspace.constants.GRID_LAST_ROW&&(g=0<b?e.getItem(b-1):!1,l.mixin(p,{prev_item_id:g?g.id:0,relation_id:d.relation_id}),t=this.addUrl);var H=function(a,b){for(var c in a)d.hasOwnProperty(c)&&
c!=b._getIdentifierAttribute()&&b.setValue(d,c,a[c]);b.save()};h.show().then(function(){dojo.xhrPost({url:t,content:p,handleAs:"json",load:function(a){if(a.success){0<d.id?H(a.data,k):(k.deleteItem(d),k.save(),dojo.forEach(a.items,function(a){k.newItem(a)}),k.save(),e.disableToolbarButtons(!0));var g=e.getCellByField(c);window.setTimeout(function(){e.focus.setFocusIndex(b,g.index)},10);h.hide()}},error:function(a){h.hide()}})})}this.inherited(arguments)},dodblclick:function(a){this.onRowDblClick(a)},
onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(c,function(a,b){b=dojo.attr(a,"rowSpan");(!b||2>b)&&dojo.attr(a,"rowSpan",2)})}},contextMenu:function(a){var b=this.rowCtxMenu=new dijit.Menu;this.contextMenuItems(a);var c={target:a.target,coords:a.keyCode!==w.F10&&"pageX"in a?{x:a.pageX,y:a.pageY}:
null},e=this.getItem(a.rowIndex);b&&e&&(this.selection.isSelected(a.rowIndex)||a.rowNode&&html.hasClass(a.rowNode,"dojoxGridRowbar"))&&(b._openMyself(c),v.stop(a))},contextMenuItems:function(a){var b=this.getItem(a.rowIndex);this.rowCtxMenu.addChild(new dijit.MenuItem({label:f.addRow,iconClass:"icon-16-container icon-16-add",disabled:this.disableEditing?!0:!1,onClick:dojo.hitch(this,"addRow",a.rowIndex,"lala")}));0<b.id&&this.rowCtxMenu.addChild(new dijit.MenuItem({label:f.deleteRow,iconClass:"icon-16-container icon-16-delete",
disabled:this.disableEditing?!0:!1,onClick:dojo.hitch(this,"deleteRow",a.rowIndex)}))},addRow:function(a){m.curNode.blur();m.curNode=null;var b=this,c=buildspace.dialog.indeterminateProgressBar({title:f.addingRow+". "+f.pleaseWait+"..."}),e=b.store,d=b.getItem(a);if(0<d.id)var k={before_id:d.id,_csrf_token:d._csrf_token};else{var h=0<a?b.getItem(a-1).id:0;k={id:d.id,prev_item_id:h,relation_id:d.relation_id,_csrf_token:d._csrf_token}}c.show().then(function(){dojo.xhrPost({url:b.addUrl,content:k,handleAs:"json",
load:function(d){d.success&&dojo.forEach(d.items,function(c){0<c.id&&(c=e.newItem(c),e.save(),c=b.getItemIndex(c),b.rearranger.moveRows([c],a),b.selection.clear())});window.setTimeout(function(){b.selection.setSelected(a,!0);b.focus.setFocusIndex(a,1)},30);c.hide()},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);c.hide()}})})},deleteRow:function(a){var b=this,c=b.getItem(a),e=buildspace.dialog.indeterminateProgressBar({title:f.deleting+". "+f.pleaseWait+"..."});m.curNode.blur();
m.curNode=null;new buildspace.dialog.confirm(f.deleteSubPackageTitle,f.msgConfirmDeleteSubPackage,80,320,function(){e.show().then(function(){dojo.xhrPost({url:b.deleteUrl,content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(d){if(d.success){var k=d.items,h=b.store;if(void 0!=d.affected_nodes){d=d.affected_nodes;for(var g=0,f=d.length;g<f;++g)dojo.forEach(d[g],function(a){h.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var d in a)c.hasOwnProperty(d)&&d!=h._getIdentifierAttribute()&&
h.setValue(b,d,a[d])}})})}g=0;for(f=k.length;g<f;++g)h.fetchItemByIdentity({identity:k[g].id,onItem:function(a){h.deleteItem(a);h.save()}});k.length=0}e.hide();b.selection.clear();window.setTimeout(function(){b.focus.setFocusIndex(a,0)},10);b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null},error:function(a){b.selection.clear();b.disableToolbarButtons(!0);b.selectedItem=null;b.pasteOp=null;e.hide()}})})},function(){})},disableToolbarButtons:function(a,b){var c=dijit.byId("SubPackages-"+
this.contId+"-AddRow-button"),e=dijit.byId("SubPackages-"+this.contId+"-DeleteRow-button"),d=dijit.byId("SubPackages-"+this.contId+"-ImportResourceItemRow-button"),f=dijit.byId("SubPackages-"+this.contId+"-ImportScheduleOfRateItemRow-button"),h=dijit.byId("SubPackages-"+this.contId+"-ImportBillItemRow-button"),g=dijit.byId("SubPackages-"+this.contId+"-ImportDropDownRow-button"),l=dijit.byId("SubPackages-"+this.contId+"-AssignSubContractorsRow-button");applyToUnitBtn=dijit.byId("SubPackages-"+this.rootProject.id+
"-ApplyRow-button");pushToPostContractBtn=dijit.byId("SubPackages-"+this.rootProject.id+"-PushToPostContractRow-button");printSettingBtn=dijit.byId("SubPackages-"+this.contId+"-PrintSettingRow-button");exportSubPackageBtn=dijit.byId("SubPackages-"+this.contId+"-ExportSubPackageRow-button");printBQBtn=dijit.byId("SubPackages-"+this.contId+"-PrintBQRow-button");this.disableEditing?(c&&c._setDisabledAttr(!0),e&&e._setDisabledAttr(!0),d&&d._setDisabledAttr(!0),f&&f._setDisabledAttr(!0),h&&h._setDisabledAttr(!0),
g&&g._setDisabledAttr(!0),pushToPostContractBtn&&pushToPostContractBtn._setDisabledAttr(!0),applyToUnitBtn&&applyToUnitBtn._setDisabledAttr(a),printSettingBtn&&printSettingBtn._setDisabledAttr(a),printBQBtn&&printBQBtn._setDisabledAttr(a),exportSubPackageBtn&&exportSubPackageBtn._setDisabledAttr(a)):(c&&c._setDisabledAttr(a),e&&e._setDisabledAttr(a),d&&d._setDisabledAttr(a),f&&f._setDisabledAttr(a),h&&h._setDisabledAttr(a),g&&g._setDisabledAttr(a),applyToUnitBtn&&applyToUnitBtn._setDisabledAttr(a),
printSettingBtn&&printSettingBtn._setDisabledAttr(a),printBQBtn&&printBQBtn._setDisabledAttr(a),exportSubPackageBtn&&exportSubPackageBtn._setDisabledAttr(a),this.rootProject.status_id[0]!=buildspace.constants.STATUS_POSTCONTRACT?pushToPostContractBtn&&pushToPostContractBtn._setDisabledAttr(!0):pushToPostContractBtn&&pushToPostContractBtn._setDisabledAttr(a));l&&l._setDisabledAttr(a);if(a&&b instanceof Array){var m=this;dojo.forEach(b,function(a){(a=dijit.byId("SubPackages-"+m.contId+"-"+a+"Row-button"))&&
a._setDisabledAttr(!1)})}},createHeaderCtxMenu:function(){var a=this.structure.cells[0],b=this,c={headerMenu:new dijit.Menu};dojo.forEach(a,function(a,d){a.showInCtxMenu&&c.headerMenu.addChild(new dijit.CheckedMenuItem({label:a.name,checked:"undefined"===typeof a.hidden||!1===a.hidden?!0:!1,onChange:function(a){var c=!1;a&&(c=!0);b.showHideMergedColumn(c,d)}}))});this.plugins={menus:c}},showHideMergedColumn:function(a,b){this.beginUpdate();this.layout.setColumnVisibility(b,a);this.endUpdate()}});
return q("buildspace.apps.SubPackage.GridContainer",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;border:0px;width:100%;height:100%;",gutters:!1,stackContainerTitle:null,rootProject:null,subPackage:null,disableEditing:!1,gridOpts:{},type:null,postCreate:function(){var a=this;a.inherited(arguments);l.mixin(a.gridOpts,{rootProject:a.rootProject,disableEditing:a.disableEditing,contId:a.id,type:a.type,region:"center"});var b=this.grid=new I(a.gridOpts);if("sub_packages-bill_list"!=
a.type&&"sub_packages-resource_item_list"!=a.type&&"sub_packages-bill_element_list"!=a.type&&"sub_packages-bill_item_list"!=a.type){var c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({id:"SubPackages-"+a.id+"-AddRow-button",label:f.addRow,iconClass:"icon-16-container icon-16-add",disabled:-1<b.selection.selectedIndex&&!a.disableEditing?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.addRow(b.selection.selectedIndex)}}));
c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"SubPackages-"+a.id+"-DeleteRow-button",label:f.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<b.selection.selectedIndex&&!a.disableEditing?!1:!0,onClick:function(){-1<b.selection.selectedIndex&&b.deleteRow(b.selection.selectedIndex)}}));if("sub_packages-list"==a.type){c.addChild(new dijit.ToolbarSeparator);var e=new G({style:"display: none;"});e.addChild(new n({id:"SubPackages-"+a.id+"-ImportResourceItemRow-button",
label:f.resourceAnalysis,onClick:l.hitch(a,"openImportResourceDialog",b),disabled:-1<b.selection.selectedIndex&&!a.disableEditing?!1:!0}));e.addChild(new n({id:"SubPackages-"+a.id+"-ImportScheduleOfRateItemRow-button",label:f.scheduleOfRateAnalysis,onClick:l.hitch(a,"openImportScheduleOfRateDialog",b),disabled:-1<b.selection.selectedIndex&&!a.disableEditing?!1:!0}));e.addChild(new n({id:"SubPackages-"+a.id+"-ImportBillItemRow-button",label:f.bills,onClick:l.hitch(a,"openImportBillItemDialog",b),disabled:-1<
b.selection.selectedIndex&&!a.disableEditing?!1:!0}));c.addChild(new F({id:"SubPackages-"+a.id+"-ImportDropDownRow-button",label:f.extractBillItemFrom,iconClass:"icon-16-container icon-16-import",dropDown:e,disabled:-1<b.selection.selectedIndex&&!a.disableEditing?!1:!0}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"SubPackages-"+a.id+"-AssignSubContractorsRow-button",label:f.assignSubContractors,iconClass:"icon-16-container icon-16-messenger",disabled:-1<b.selection.selectedIndex?
!1:!0,onClick:function(c){var d=b.getItem(b.selection.selectedIndex);c=dojo.xhrGet({url:"subPackage/subPackageCompanyForm/id/"+d.id,handleAs:"json"});var e=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});e.show();r(c,function(c){e.hide();A({subPackage:d,rootProject:a.rootProject,subPackageGrid:b,disableEditing:a.disableEditing,formValues:c}).show()})}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"SubPackages-"+a.id+"-PrintSettingRow-button",
label:f.printSettings,iconClass:"icon-16-container icon-16-print",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(c){c=b.getItem(b.selection.selectedIndex);(new B({subPackage:c,rootProject:a.rootProject,subPackageGrid:b,disableEditing:a.disableEditing})).show()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({id:"SubPackages-"+a.id+"-PrintBQRow-button",label:f.printBQ,iconClass:"icon-16-container icon-16-print",disabled:-1<b.selection.selectedIndex?!1:!0,onClick:function(a){a=
b.getItem(b.selection.selectedIndex);(new C({subPackage:a})).show()}}));this.rootProject.status_id[0]==buildspace.constants.STATUS_POSTCONTRACT&&(c.addChild(new dijit.ToolbarSeparator),c.addChild(new dijit.form.Button({id:"SubPackages-"+a.rootProject.id+"-PushToPostContractRow-button",label:f.pushToPostContract,iconClass:"icon-16-container icon-16-indent",disabled:!0,onClick:function(c){var d=b.getItem(b.selection.selectedIndex);c=dojo.xhrGet({url:"subPackage/getSelectedSubConInfo/id/"+d.id,handleAs:"json"});
var e=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});e.show();r(c,function(c){e.hide();(new E({companyInfo:c,rootProject:a.rootProject,subPackageGrid:b,subPackage:d,url:"subpackage/applyToUnit"})).show()})}})))}a.addChild(c)}a.addChild(b);if(c=dijit.byId("SubPackages-"+a.rootProject.id+"-stackContainer"))e=document.createElement("div"),e=new dojox.layout.ContentPane({title:buildspace.truncateString(a.stackContainerTitle,30),id:a.pageId,executeScripts:!0},e),c.addChild(e),e.set("content",
a),l.mixin(e,{grid:b}),c.selectChild(a.pageId)},openImportResourceDialog:function(a){if(-1<a.selection.selectedIndex){var b=a.getItem(a.selection.selectedIndex);(new x({subPackage:b,subPackageGridStore:a.store})).show()}},openImportScheduleOfRateDialog:function(a){if(-1<a.selection.selectedIndex){var b=a.getItem(a.selection.selectedIndex);(new y({subPackage:b,subPackageGridStore:a.store})).show()}},openImportBillItemDialog:function(a){if(-1<a.selection.selectedIndex){var b=a.getItem(a.selection.selectedIndex);
(new z({subPackage:b,subPackageGridStore:a.store,rootProject:this.rootProject})).show()}}})});
