define("buildspace/apps/SubPackage/ImportResourceItemDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style buildspace/widget/grid/cells/Formatter dojox/grid/enhanced/plugins/IndirectSelection dojo/i18n!buildspace/nls/SubPackages".split(" "),function(k,p,q,l,w,x,y,t,u,m,z,e){var v=k("buildspace.apps.SubPackage.ImportResourceItemGrid",dojox.grid.EnhancedGrid,{type:null,itemId:0,dialogWidget:null,_csrf_token:null,itemIds:[],subPackageGridStore:null,
style:"border-top:none;",constructor:function(a){this.itemIds=[];this.connects=[];"tree"==a.type&&(this.urlGetDescendantIds="subPackage/getResourceDescendants",this.plugins={indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align: center;"}});this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){var a=this;a.inherited(arguments);"tree"==a.type&&p.after(this,"_onFetchComplete",function(){this.store.fetch({query:{selected:!0},queryOptions:{ignoreCase:!0},onComplete:this.markSelectedCheckBoxes,
scope:this})});this.on("RowClick",function(b){b=a.getItem(b.rowIndex);"tree"==a.type&&(b&&0<b.id?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0))});"tree"==this.type&&(this._connects.push(l.connect(this,"onCellClick",function(b){a.selectTree(b)})),this._connects.push(l.connect(this.rowSelectCell,"toggleAllSelection",function(b){a.toggleAllSelection(b)})))},dodblclick:function(a){this.onRowDblClick(a)},selectTree:function(a){a=a.rowIndex;var b=this.selection.selected[a];a=this.getItem(a);var c=
this,d=this.store;if(a.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER){var f=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});f.show();var g=-1;dojo.xhrGet({url:this.urlGetDescendantIds,content:{id:a.id},handleAs:"json",load:function(a){dojo.forEach(a.items,function(a){d.fetchItemByIdentity({identity:a.id,onItem:function(a){a&&(g=a._0,a.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM&&c.pushItemIdIntoGridArray(a,b),c.selection[b?"addToSelection":
"deselect"](g))}})});f.hide()},error:function(a){f.hide()}})}else a.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_WORK_ITEM&&this.pushItemIdIntoGridArray(a,b)},pushItemIdIntoGridArray:function(a,b){var c=dojo.indexOf(this.itemIds,a.id[0]);b?-1==c&&this.itemIds.push(a.id[0]):-1!=c&&this.itemIds.splice(c,1)},toggleAllSelection:function(a){var b=this,c=b.selection;a?(c.selectRange(0,b.rowCount-1),b.itemIds=[],b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id&&b.itemIds.push(a.id[0])})}})):
(c.deselectAll(),b.itemIds=[])},disableToolbarButtons:function(a){dijit.byId("SubPackages-ImportResourceItemsGrid-"+this.subPackage.id+"Import-button")._setDisabledAttr(a)},markSelectedCheckBoxes:function(a,b){for(var c=0;c<a.length;c++){var d=a[c]._0;this.pushItemIdIntoGridArray(a[c],!0);this.selection.setSelected(d,!0)}},"import":function(a){var b=this,c=e.removeAllResourceItemsFrom+" "+buildspace.truncateString(b.subPackage.name,25),d=e.areYouSureToRemoveAllResourceItemsUnderTrade+" <b>"+buildspace.truncateString(a.description,
40)+"</b>?",f=b.subPackageGridStore,g=b.itemIds,h=buildspace.dialog.indeterminateProgressBar({title:e.importing+". "+e.pleaseWait+"..."});h.show();var r={url:"subPackage/importResourceItems",content:{id:b.subPackage.id,ids:[g],tid:a.id,_csrf_token:b._csrf_token},handleAs:"json",load:function(a){a.success&&(f.fetchItemByIdentity({identity:b.subPackage.id,onItem:function(b){f.setValue(b,"est_amount",a.est_amount);f.setValue(b,"selected_amount",a.selected_amount);f.save()}}),b.selection.deselectAll(),
dojo.forEach(a.items,function(a){b.store.fetchItemByIdentity({identity:a.id,onItem:function(a){a&&b.selection.setSelected(a._0,!0)}})}));h.hide()},error:function(a){b.itemIds=[];h.hide();b.dialogWidget.hide()}};0<g.length?dojo.xhrPost(r):new buildspace.dialog.confirm(c,d,80,400,function(){dojo.xhrPost(r)},function(){h.hide()})},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,l.disconnect);delete this._connects}}),n=k("buildspace.apps.SubPackage.ImportResourceGridContainer",
dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,subPackage:null,stackContainerTitle:"",type:"default",trade:null,gridOpts:{},postCreate:function(){var a=this;this.inherited(arguments);q.mixin(a.gridOpts,{type:a.type,subPackage:a.subPackage,region:"center"});var b=this.grid=new v(a.gridOpts);if("tree"==a.type){var c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({id:"SubPackages-ImportResourceItemsGrid-"+
a.subPackage.id+"Import-button",label:e.importToSubPackage,iconClass:"icon-16-container icon-16-import",onClick:function(){b["import"](a.trade)}}));a.addChild(c)}a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}));if(c=dijit.byId("SubPackages-resource_items_import_"+a.subPackage.id+"-stackContainer")){var d=document.createElement("div"),d=new dojox.layout.ContentPane({title:buildspace.truncateString(a.stackContainerTitle,60),id:a.pageId,executeScripts:!0},d);c.addChild(d);
d.set("content",a);q.mixin(d,{grid:b});c.selectChild(a.pageId)}}});return k("buildspace.apps.SubPackage.ImportResourceItemDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:e.importResourceItems,subPackage:null,subPackageGridStore:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.title=e.importResourceItems+" :: "+buildspace.truncateString(this.subPackage.name,45);this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",
margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){a.keyCode==t.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.destroyRecursive()},createContent:function(){var a=this,b=new dijit.layout.BorderContainer({style:"padding:0px;width:850px;height:350px;",gutters:!1}),c=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;border:0px;"});c.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",
style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var d=new m,f=dojo.data.ItemFileWriteStore({url:"subPackage/getResourceList/id/"+this.subPackage.id,clearOnClose:!0}),d=this.makeGridContainer(n({stackContainerTitle:e.resources,pageId:"sub_packages_import-page_resource-"+this.subPackage.id,subPackage:this.subPackage,gridOpts:{store:f,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:d.rowCountCellFormatter},{name:e.name,field:"name",width:"auto"}],
onRowDblClick:function(b){b=this.getItem(b.rowIndex);0<b.id&&null!==b.name[0]&&a.createTradeGrid(b)}}}));b.addChild(c);b.addChild(d);return b},createTradeGrid:function(a){var b=this,c=m(),d=new dojo.data.ItemFileWriteStore({url:"subPackage/getTradeList/id/"+b.subPackage.id+"/rid/"+a.id,clearOnClose:!0});n({stackContainerTitle:a.name,pageId:"sub_packages_import-page_resource_trade-"+this.subPackage.id+"_"+a.id,subPackage:b.subPackage,gridOpts:{store:d,structure:[{name:"No.",field:"id",width:"30px",
styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:e.description,field:"description",width:"auto"}],onRowDblClick:function(c){c=this.getItem(c.rowIndex);0<c.id&&null!==c.description[0]&&b.createItemGrid(c,a)}}})},createItemGrid:function(a,b){var c=m(),d=new dojo.data.ItemFileWriteStore({url:"subPackage/getResourceItemList/id/"+this.subPackage.id+"/rid/"+b.id+"/tid/"+a.id,clearOnClose:!0});n({stackContainerTitle:a.description,pageId:"sub_packages_import-page_resource_item-"+this.subPackage.id+
"_"+a.id,subPackage:this.subPackage,type:"tree",trade:a,gridOpts:{store:d,dialogWidget:this,subPackageGridStore:this.subPackageGridStore,_csrf_token:a._csrf_token,structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:c.rowCountCellFormatter},{name:e.description,field:"description",width:"auto",formatter:c.treeCellFormatter},{name:e.type,field:"type",width:"80px",styles:"text-align:center;",formatter:c.typeCellFormatter},{name:e.unit,field:"uom_id",width:"70px",styles:"text-align:center;",
formatter:c.unitIdCellFormatter}]}})},makeGridContainer:function(a){var b=this.subPackage.id,c=dijit.byId("SubPackages-resource_items_import_"+b+"-stackContainer");c&&dijit.byId("SubPackages-resource_items_import_"+b+"-stackContainer").destroyRecursive();c=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"SubPackages-resource_items_import_"+b+"-stackContainer"});c.addChild(new dijit.layout.ContentPane({title:e.resources,content:a,grid:a.grid}));a=new dijit.layout.StackController({region:"top",
containerId:"SubPackages-resource_items_import_"+b+"-stackContainer"});var d=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});d.addChild(c);d.addChild(new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;border:0px;","class":"breadCrumbTrail",region:"top",content:a}));dojo.subscribe("SubPackages-resource_items_import_"+b+"-stackContainer-selectChild","",function(a){var c=dijit.byId("SubPackages-resource_items_import_"+
b+"-stackContainer");if(c){var d=c.getChildren(),e=dojo.indexOf(d,a);if(d.length>e+1){a.grid.store.save();a.grid.store.close();var f=p.after(a.grid,"_onFetchComplete",function(){f.remove();this.scrollToRow(this.selection.selectedIndex)});a.grid._refresh()}for(;d.length>e+1;)e+=1,c.removeChild(d[e]),d[e].destroyRecursive(!0)}});return d}})});
