define("buildspace/apps/PostContractSubPackageRemeasurement/RemeasurementContainer","dojo/_base/declare dojo/aspect ./RemeasurementGrid buildspace/widget/grid/cells/Formatter buildspace/apps/ProjectBuilder/BillManager/ScheduleOfQuantityGrid ./buildUpQuantitySummary ./buildUpQuantityGrid dojo/i18n!buildspace/nls/PostContractRemeasurement".split(" "),function(u,v,g,r,A,B,C,c){return u("buildspace.apps.PostContractSubPackageRemeasurement.RemeasurementContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;margin:0px;border:0px;height:100%;",
gutters:!1,project:null,subPackage:null,opt:null,postCreate:function(){var d=this;this.inherited(arguments);var b=new r,a=dojo.data.ItemFileWriteStore({url:"postContractSubPackageRemeasurement/getAllBills/subPackageId/"+d.subPackage.id+"/opt/"+d.opt,clearOnClose:!0}),b=new g({id:"post-contract-subpackage-remeasurement-grid-"+d.subPackage.id,stackContainerTitle:c.bill,pageId:"post-contract-subpackage-remeasurement-grid-"+d.subPackage.id,project:d.project,subPackage:d.subPackage,gridOpts:{store:a,structure:[{name:"No.",
field:"id",width:"40px",styles:"text-align:center;",formatter:b.rowCountCellFormatter},{name:c.bill,field:"title",width:"auto",formatter:b.analyzerDescriptionCellFormatter},{name:c.omission,field:"omission",width:"150px",styles:"text-align:right;color:red;",formatter:b.unEditableCurrencyCellFormatter},{name:c.addition,field:"addition",width:"150px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:c.nettAdditionOmission,field:"nettAdditionOmission",width:"150px",styles:"text-align:right;color:green;",
formatter:b.unEditableCurrencyCellFormatter}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.title[0]&&d.createBillTypesGrid(a)}}}),b=this.makeGridContainer(b,c.bill);this.addChild(b)},createBillTypesGrid:function(d){var b=this,a=new r,f=dojo.data.ItemFileWriteStore({url:"postContractSubPackageRemeasurement/getBillTypes/subPackageId/"+b.subPackage.id+"/bid/"+d.id+"/opt/"+b.opt,clearOnClose:!0});new g({id:"post-contract-subpackage-remeasurement-billtype"+b.subPackage.id,stackContainerTitle:d.title,
pageId:"post-contract-subpackage-remeasurement-billtype"+b.subPackage.id+"_"+d.id,project:b.project,subPackage:b.subPackage,gridOpts:{store:f,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:c.description,field:"name",width:"auto",formatter:a.analyzerDescriptionCellFormatter},{name:c.totalUnits,field:"quantity",width:"150px",styles:"text-align:right;",formatter:a.unEditableCurrencyCellFormatter},{name:c.omission,field:"omission",width:"150px",
styles:"text-align:right;color:red;",formatter:a.unEditableCurrencyCellFormatter},{name:c.addition,field:"addition",width:"150px",styles:"text-align:right;",formatter:a.unEditableCurrencyCellFormatter},{name:c.nettAdditionOmission,field:"nettAdditionOmission",width:"150px",styles:"text-align:right;color:green;",formatter:a.unEditableCurrencyCellFormatter}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);0<a.id&&null!==a.name[0]&&b.createElementGrid(a)}}})},createElementGrid:function(d){var b=
this,a=new r,f=dojo.data.ItemFileWriteStore({url:"postContractSubPackageRemeasurement/getElementList/subPackageId/"+b.subPackage.id+"/btId/"+d.id+"/opt/"+b.opt,clearOnClose:!0});new g({id:"post-contract-subpackage-remeasurement-element-"+b.subPackage.id,stackContainerTitle:d.name,pageId:"post-contract-subpackage-remeasurement-element-"+b.subPackage.id+"_"+d.id,project:b.project,subPackage:b.subPackage,gridOpts:{store:f,structure:[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},
{name:c.description,field:"description",width:"auto"},{name:c.omission,field:"omission",width:"150px",styles:"text-align:right;color:red;",formatter:a.unEditableCurrencyCellFormatter},{name:c.addition,field:"addition",width:"150px",styles:"text-align:right;",formatter:a.unEditableCurrencyCellFormatter},{name:c.nettAdditionOmission,field:"nettAdditionOmission",width:"150px",styles:"text-align:right;color:green;",formatter:a.unEditableCurrencyCellFormatter}],onRowDblClick:function(a){a=this.getItem(a.rowIndex);
0<a.id&&null!==a.description[0]&&b.createItemGrid(d,a)}}})},createItemGrid:function(d,b){var a=this;r();var f=new dojo.data.ItemFileWriteStore({url:"postContractSubPackageRemeasurement/getItemList/subPackageId/"+a.subPackage.id+"/btId/"+d.id+"/elementId/"+b.id+"/opt/"+a.opt,clearOnClose:!0});new g({id:"post-contract-subpackage-remeasurement-item-"+a.subPackage.id,stackContainerTitle:b.description,pageId:"post-contract-subpackage-remeasurement-item-"+a.subPackage.id+"_"+b.id,project:a.project,subPackage:a.subPackage,
gridOpts:{store:f,type:"item",billTypeId:d.id,updateUrl:"postContractSubPackageRemeasurement/remeasurementItemUpdate",onRowDblClick:function(b){var f=b.cell.field,e=this.getItem(b.rowIndex),l=this.store,n=d.id;editable=!1;if(0<e.id&&("omission-qty_per_unit"===f||"addition-qty_per_unit"===f)&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM&&
e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_LUMP_SUM_EXCLUDE&&e.type!=buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY&&("omission-qty_per_unit"!==f||void 0!=e["omission-has_build_up"]&&e["omission-has_build_up"][0]))if(0<e.uom_id[0]){if("addition-qty_per_unit"!==f||e.include[0]){b=dojo.xhrPost({url:"billBuildUpQuantity/getDimensionColumnStructure",content:{uom_id:e.uom_id[0]},handleAs:"json"});"addition-qty_per_unit"===f&&(editable=!0);var p=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+
"..."});p.show();b.then(function(b){a.createBuildUpQuantityContainer(f,editable,e,b,n,l);p.hide()})}}else buildspace.dialog.alert(c.buildUpQtyAlert,c.pleaseSetUOM,60,300)}}})},createBuildUpQuantityContainer:function(d,b,a,f,h,D){var e,l,n=b?!1:!0;"addition-qty_per_unit"===d?(e="postContractSubPackageRemeasurementBillBuildUpQuantity",l=a.sub_package_post_contract_bill_item_rate_id):(e="billBuildUpQuantity",l=a.id);var p=this,q=buildspace.constants.QUANTITY_PER_UNIT_ORIGINAL,g,t=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;outline:none;",
gutters:!1}),w=new dijit.layout.TabContainer({nested:!0,style:"padding:0;border:none;margin:0;width:100%;height:100%;",region:"center"}),k=new r;d=dojo.xhrGet({url:e+"/getLinkInfo/id/"+a.id+"/bcid/"+h+"/t/"+q,handleAs:"json"});var x=new dojo.data.ItemFileWriteStore({url:e+"/getBuildUpQuantityItemList/bill_item_id/"+l+"/bill_column_setting_id/"+h+"/type/"+q,clearOnClose:!0}),u=[buildspace.constants.SIGN_POSITIVE_TEXT,buildspace.constants.SIGN_NEGATIVE_TEXT],v=[buildspace.constants.SIGN_POSITIVE,buildspace.constants.SIGN_NEGATIVE],
y=!1,z=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});z.show();d.then(function(b){var d=[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:k.rowCountCellFormatter},{name:c.description,field:"description",width:"auto",editable:!n,cellType:"buildspace.widget.grid.cells.Textarea"},{name:c.factor,field:"factor-value",width:"100px",styles:"text-align:right;",editable:!n,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:k.formulaNumberCellFormatter}];
dojo.forEach(f,function(a){d.push({name:a.title,field:a.field_name,width:"100px",styles:"text-align:right;",editable:!n,cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:k.formulaNumberCellFormatter})});d.push({name:c.total,field:"total",width:"100px",styles:"text-align:right;",formatter:k.numberCellFormatter});d.push({name:c.sign,field:"sign",width:"70px",styles:"text-align:center;",editable:!0,cellType:"dojox.grid.cells.Select",options:u,values:v,formatter:k.signCellFormatter});var m=
new B({itemId:l,billColumnSettingId:h,type:q,container:t,billGridStore:D,buildUpGridStore:x,hasLinkedQty:b.has_linked_qty,_csrf_token:a._csrf_token,moduleName:e,locked:n});b.has_linked_qty&&(y=!0,g=new A({title:c.scheduleOfQuantities,BillItem:a,disableEditingMode:!0,stackContainerId:"postContractSubPackageRemeasurement-grid_"+p.subPackage.id+"-stackContainer",gridOpts:{qtyType:q,buildUpSummaryWidget:m,store:new dojo.data.ItemFileWriteStore({url:e+"/getScheduleOfQuantities/id/"+a.id+"/bcid/"+h+"/type/"+
q,clearOnClose:!0}),structure:[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:k.rowCountCellFormatter},{name:c.description,field:"description",width:"auto",formatter:k.treeCellFormatter},{name:c.type,field:"type",width:"70px",styles:"text-align:center;",formatter:k.typeCellFormatter},{name:c.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:k.unitIdCellFormatter},{name:c.qty,field:"quantity-value",width:"100px",styles:"text-align:right;",formatter:k.formulaNumberCellFormatter}]}}));
w.addChild(new C({title:c.manualQtyItems,region:"center",billColumnSettingId:h,BillItem:a,type:q,locked:n,gridOpts:{addUrl:e+"/buildUpQuantityItemAdd",updateUrl:e+"/buildUpQuantityItemUpdate",deleteUrl:e+"/buildUpQuantityItemDelete",pasteUrl:e+"/buildUpQuantityItemPaste",store:x,structure:d,buildUpSummaryWidget:m,currentBillLockedStatus:p.currentBillLockedStatus}}));y&&w.addChild(g);t.addChild(w);t.addChild(m);if(b=dijit.byId("postContractSubPackageRemeasurement-grid_"+p.subPackage.id+"-stackContainer"))m=
document.createElement("div"),m=new dojox.layout.ContentPane({title:buildspace.truncateString(a.description,60)+" ("+c.buildUpQuantity+" - "+a.uom_symbol+")",id:"buildUpQuantityPage-"+l,style:"padding:0px;border:0px;",executeScripts:!0},m),b.addChild(m),m.set("content",t),b.selectChild("buildUpQuantityPage-"+l);z.hide()})},makeGridContainer:function(d,b){var a=this.subPackage.id,c=dijit.byId("postContractSubPackageRemeasurement-grid_"+a+"-stackContainer");c&&dijit.byId("postContractSubPackageRemeasurement-grid_"+
a+"-stackContainer").destroyRecursive();var c=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"postContractSubPackageRemeasurement-grid_"+a+"-stackContainer"}),h=new dijit.layout.ContentPane({title:b,content:d,grid:d.grid});c.addChild(h);var h=new dijit.layout.StackController({region:"top",containerId:"postContractSubPackageRemeasurement-grid_"+a+"-stackContainer"}),h=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",
region:"top",content:h}),g=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});g.addChild(c);g.addChild(h);dojo.subscribe("postContractSubPackageRemeasurement-grid_"+a+"-stackContainer-selectChild","",function(b){var c=dijit.byId("postContractSubPackageRemeasurement-grid_"+a+"-stackContainer");if(c){var d=c.getChildren(),e=dojo.indexOf(d,b),e=e+1;if(d.length>e){for(;d.length>e;)c.removeChild(d[e]),d[e].destroyDescendants(),d[e].destroyRecursive(),
e+=1;if(b.grid){var f=b.grid.selection.selectedIndex;b.grid.store.save();b.grid.store.close();var g=v.after(b.grid,"_onFetchComplete",function(){g.remove();-1<f&&(this.scrollToRow(f),this.selection.setSelected(f,!0))});b.grid.sort()}}}});return g}})});
