define("buildspace/apps/PostContractRemeasurement/RemeasurementGrid","dojo/_base/declare dojo/_base/lang dojo/_base/connect dijit/TooltipDialog dijit/popup dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContractRemeasurement".split(" "),function(k,l,g,n,h,u,p,q,f){var t=k("buildspace.apps.PostContractRemeasurement.ResourceEnhancedGrid",dojox.grid.EnhancedGrid,{type:null,style:"border-top:none;",
rowSelector:"0px",region:"center",updateUrl:null,project:null,billTypeId:-1,escapeHTMLInData:!1,constructor:function(a){this.structure=a.structure;this.type=a.type;this.updateUrl=a.updateUrl;this.columnGroup=a.columnGroup;this.billTypeId=a.billTypeId;this.formatter=new q;"item"==this.type&&(this.setColumnStructure(),this.createHeaderCtxMenu());this.inherited(arguments)},canSort:function(a){return!1},postCreate:function(){var a=null;this.formulatedColumn=p(this,{});this.inherited(arguments);"item"===
self.type&&(this._connects.push(g.connect(this,"onCellMouseOver",function(c){var b=c.cell.field,d=c.rowIndex,e=this.getItem(d),b=b.replace("-value","");"undefined"!==typeof e[b+"-has_formula"]&&e[b+"-has_formula"][0]&&(e=e[b+"-value"][0],e=this.formulatedColumn.convertItemIdToRowIndex(e,d),null===a&&(a=new n({content:e,onMouseLeave:function(){h.close(a)}}),h.open({popup:a,around:c.cellNode})))})),this._connects.push(g.connect(this,"onCellMouseOut",function(){null!==a&&(h.close(a),a=null)})),this._connects.push(g.connect(this,
"onStartEdit",function(){null!==a&&(h.close(a),a=null)})))},canEdit:function(a,c){var b=this,d=this.getItem(c);if("item"===b.type){if(a)if(d&&0<d.id[0]){if(d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER||d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_HEADER_N||d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_NOID||d.type==buildspace.widget.grid.constants.HIERARCHY_TYPE_ITEM_RATE_ONLY){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);
return}if(!d.include[0]){window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c,a.index)},10);return}}else return;return this._canEdit}window.setTimeout(function(){b.edit.cancel();b.focus.setFocusIndex(c)},10)},doApplyCellEdit:function(a,c,b){var d=this,e=d.getItem(c),r=d.store,m=b.replace("-qty_per_unit","");if(e[b]&&a!==e[b][0]){var g=buildspace.dialog.indeterminateProgressBar({title:f.savingData+". "+f.pleaseWait+"..."});a||(a=0);var h=function(a,b){for(var c in a)e.hasOwnProperty(c)&&
c!=b._getIdentifierAttribute()&&b.setValue(e,c,a[c]);b.save()},k={url:d.updateUrl,content:{id:e.post_contract_bill_item_rate_id,attr_name:b,val:a,btId:d.billTypeId,_csrf_token:e._csrf_token?e._csrf_token:null},handleAs:"json",load:function(a){if(a.success){0<e.id&&h(a.item,r);var f=d.getCellByField(b);window.setTimeout(function(){d.focus.setFocusIndex(c,f.index)},10);g.hide()}},error:function(a){g.hide()}};void 0!=e[m+"-has_build_up"]&&e[m+"-has_build_up"][0]?(buildspace.dialog.confirm(f.confirmation,
"<div>"+f.detachAllBuildUpAndLink+"</div>",60,280,function(){g.show();dojo.xhrPost(k)}),d.doCancelEdit(c)):(g.show(),dojo.xhrPost(k),d.inherited(arguments))}else d.inherited(arguments)},setColumnStructure:function(){var a=this.formatter;"item"==this.type&&(this.structure={noscroll:!1,cells:[[{name:"No.",field:"id",width:"40px",styles:"text-align:center;",formatter:a.rowCountCellFormatter,rowSpan:2},{name:f.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,
hidden:!0,rowSpan:2,showInCtxMenu:!0},{name:f.description,field:"description",width:"auto",formatter:a.treeCellFormatter,rowSpan:2},{name:f.type,field:"type",width:"70px",styles:"text-align:center;",formatter:a.typeCellFormatter,rowSpan:2},{name:f.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:a.unitIdCellFormatter,rowSpan:2},{name:f.rate,field:"rate",width:"120px",styles:"text-align:right;",cellType:"buildspace.widget.grid.cells.FormulaTextBox",formatter:a.unEditableCurrencyCellFormatter,
rowSpan:2},{name:f.qtyPerUnit,field:"omission-qty_per_unit",width:"90px",headerClasses:"typeHeader1",formatter:a.postContractRemeasurementQuantityCellFormatter,styles:"text-align: right;",noresize:!0},{name:f.totalPerUnit,field:"omission-total_per_unit",width:"90px",headerClasses:"typeHeader1",formatter:a.unEditableCurrencyCellFormatter,styles:"text-align: right; color: red;",noresize:!0},{name:f.qtyPerUnit,field:"addition-qty_per_unit",width:"90px",headerClasses:"typeHeader1",formatter:a.postContractRemeasurementQuantityCellFormatter,
styles:"text-align: right;",noresize:!0,editable:!0,cellType:"buildspace.widget.grid.cells.FormulaTextBox"},{name:f.totalPerUnit,field:"addition-total_per_unit",width:"90px",headerClasses:"typeHeader1",formatter:a.unEditableCurrencyCellFormatter,styles:"text-align: right;",noresize:!0},{name:f.nettAdditionOmission,field:"nett_addition_omission",width:"100px",styles:"text-align: right; color: green;",formatter:a.unEditableCurrencyCellFormatter,rowSpan:2}],[{name:f.omission,styles:"text-align: center;",
headerClasses:"staticHeader typeHeader1",colSpan:2,noresize:!0},{name:f.addition,styles:"text-align: center;",headerClasses:"staticHeader typeHeader2",colSpan:2,noresize:!0}]]})},onHeaderCellClick:function(a){dojo.hasClass(a.cell.id,"staticHeader")||(a.grid.setSortIndex(a.cell.index),a.grid.onHeaderClick(a))},onHeaderCellMouseOver:function(a){dojo.hasClass(a.cell.id,"staticHeader")||dojo.addClass(a.cellNode,this.cellOverClass)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&
2<=a.node.children[0].children[0].rows.length){var c=a.node.children[0].children[0].rows[1],b=a.node.children[0].children[0].rows[0].children;c.parentNode.removeChild(c);dojo.forEach(b,function(a,b){var c=dojo.attr(a,"rowSpan");(!c||2>c)&&dojo.attr(a,"rowSpan",2)})}},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},editableCellDblClick:function(a){var c;c=1<this._click.length&&has("ie")?this._click[1]:1<this._click.length&&this._click[0].rowIndex!=
this._click[1].rowIndex?this._click[0]:a;this.focus.setFocusCell(c.cell,c.rowIndex);this.onRowClick(c);this.onRowDblClick(a)},dodblclick:function(a){if(a.cellNode)if(a.cell.editable)this.editableCellDblClick(a);else this.onCellDblClick(a);else this.onRowDblClick(a)},createHeaderCtxMenu:function(){if("undefined"!==typeof this.structure){var a=this.structure.cells[0],c=this,b={headerMenu:new dijit.Menu};dojo.forEach(a,function(a,e){a.showInCtxMenu&&b.headerMenu.addChild(new dijit.CheckedMenuItem({label:a.name,
checked:"undefined"===typeof a.hidden||!1===a.hidden?!0:!1,onChange:function(a){var b=!1;a&&(b=!0);c.showHideMergedColumn(b,e)}}))});this.plugins={menus:b}}},showHideMergedColumn:function(a,c){this.beginUpdate();this.layout.setColumnVisibility(c,a);this.endUpdate()},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,g.disconnect);delete this._connects}});return k("buildspace.apps.PostContractRemeasurement.RemeasurementGrid",dijit.layout.BorderContainer,{stackContainerTitle:"",
style:"padding:0px;width:100%;height:100%;",gutters:!1,project:null,gridOpts:{},pageId:0,postCreate:function(){this.inherited(arguments);l.mixin(this.gridOpts,{project:this.project});var a=this.grid=new t(this.gridOpts);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}));var c=dijit.byId("postContractRemeasurement-grid_"+this.project.id+"-stackContainer");if(c){var b=document.createElement("div"),b=new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,
60),id:this.pageId,executeScripts:!0},b);c.addChild(b);b.set("content",this);l.mixin(b,{grid:a});c.selectChild(this.pageId)}}})});
