define("buildspace/apps/ProjectBuilderReport/BillManager/buildUpFloorAreaDialog","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange buildspace/widget/grid/plugins/FormulatedColumn dojo/_base/event dojo/keys dojo/currency dijit/focus dojo/request dijit/PopupMenuItem buildspace/widget/grid/cells/Select buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/FormulaTextBox dojo/when dojo/html dojo/dom dojo/dom-style buildspace/widget/grid/cells/Formatter ./buildUpFloorAreaSummary ./PrintPreviewFormDialog dojo/i18n!buildspace/nls/BuildUpFloorArea".split(" "),
function(k,l,A,B,C,D,n,p,E,q,F,G,r,H,I,J,K,L,M,N,t,u,v,w,c){var y=k("buildspace.apps.ProjectBuilderReport.BillManager.BuildUpFloorArea.grid",dojox.grid.EnhancedGrid,{billColumnSettingId:null,style:"border-top:none;",selectedItem:null,keepSelection:!0,rowSelector:"0px",buildUpSummaryWidget:null,type:null,constructor:function(a){this.rearranger=n(this,{});this.formulatedColumn=p(this,{})},canSort:function(a){return!1},doApplyCellEdit:function(a,f,d){var b=this,e=b.getItem(f),c=b.store;if(a!==e[d][0]){var g=
d.replace("-value","");-1!==d.indexOf("-value")&&(a=this.formulatedColumn.convertRowIndexToItemId(a,f));var g={id:e.id,attr_name:g,val:a,type:b.type,_csrf_token:e._csrf_token?e._csrf_token:null},h=this.updateUrl;e.id==buildspace.constants.GRID_LAST_ROW&&(h=0<f?b.getItem(f-1):!1,l.mixin(g,{prev_item_id:h?h.id:0,relation_id:e.relation_id,bill_column_setting_id:b.billColumnSettingId}),h=this.addUrl);var x=function(a,b){for(var d in a)e.hasOwnProperty(d)&&d!=b._getIdentifierAttribute()&&b.setValue(e,
d,a[d]),dojo.forEach(a.affected_nodes,function(a){b.fetchItemByIdentity({identity:a.id,onItem:function(d){for(var c in a)e.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(d,c,a[c])}})});b.save()};dojo.xhrPost({url:h,content:g,handleAs:"json",load:function(a){if(a.success){0<e.id?x(a.data,c):(c.deleteItem(e),c.save(),dojo.forEach(a.items,function(a){c.newItem(a)}),c.save());b.updateTotalBuildUp(a.total_build_up);var g=b.getCellByField(d);window.setTimeout(function(){b.focus.setFocusIndex(f,
g.index)},10)}},error:function(a){console.log(a)}})}b.inherited(arguments)},updateTotalBuildUp:function(){this.buildUpSummaryWidget.refreshTotalFloorArea()}}),z=k("buildspace.apps.ProjectBuilderReport.BillManager.BuildUpFloorAreaGrid",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,billColumnSettingId:null,type:null,gridOpts:{},postCreate:function(){this.inherited(arguments);l.mixin(this.gridOpts,{billColumnSettingId:this.billColumnSettingId,region:"center",
type:this.type});var a=this.grid=new y(this.gridOpts);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,region:"center"}))}});return k("buildspace.apps.ProjectBuilderReport.BillManager.BuildUpFloorAreaDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",title:c.appName,billId:0,billColumnSettingId:0,columnSettingForm:null,unit:null,buildRendering:function(){var a=this.createContent();a.startup();this.content=a;this.inherited(arguments)},postCreate:function(){t.set(this.containerNode,
{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";this.inherited(arguments)},_onKey:function(a){key=a.keyCode;key==q.ESCAPE&&dojo.stopEvent(a)},onHide:function(){this.columnSettingForm.refreshColumn();this.destroyRecursive()},createContent:function(){var a=this,f=new dijit.layout.BorderContainer({style:"padding:0px;width:900px;height:450px;",gutters:!1}),d=new dijit.Toolbar({region:"top",style:"outline:none!important;padding:2px;overflow:hidden;"});d.addChild(new dijit.form.Button({label:c.print,
iconClass:"icon-16-container icon-16-print",style:"outline:none!important;",onClick:function(b){a.openPrintingDialog()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:c.close,iconClass:"icon-16-container icon-16-close",style:"outline:none!important;",onClick:dojo.hitch(this,"hide")}));var b=new u,e=[{name:"No",field:"id",styles:"text-align:center;",width:"40px",formatter:b.rowCountCellFormatter},{name:c.description,field:"description",width:"auto"},{name:c.factor,
field:"factor-value",width:"100px",styles:"text-align:right;",formatter:b.formulaNumberCellFormatter},{name:c.length,field:"length-value",width:"100px",styles:"text-align:right;",formatter:b.formulaNumberCellFormatter},{name:c.width,field:"width-value",width:"100px",styles:"text-align:right;",formatter:b.formulaNumberCellFormatter},{name:c.total,field:"total",width:"100px",styles:"text-align:right;",formatter:b.numberCellFormatter},{name:c.sign,field:"sign",width:"70px",styles:"text-align:center;",
formatter:b.signCellFormatter}],m=dojo.data.ItemFileWriteStore({url:"billBuildUpFloorArea/getBuildUpFloorAreaItemList/bill_column_setting_id/"+a.billColumnSettingId,clearOnClose:!0}),b=new v({billId:a.billId,billColumnSettingId:a.billColumnSettingId,container:f,columnSettingForm:a.columnSettingForm,buildUpGridStore:m}),e=new z({region:"center",billColumnSettingId:a.billColumnSettingId,gridOpts:{store:m,structure:e,buildUpSummaryWidget:b}}),e=this.makeGridContainer(e,c.appName);f.addChild(d);f.addChild(b);
f.addChild(e);return f},makeGridContainer:function(a,c){var d=this.billId,b=dijit.byId("billManager-buildUpFloorArea_"+d+"-stackContainer");b&&dijit.byId("billManager-buildUpFloorArea_"+d+"-stackContainer").destroyRecursive();var b=new dijit.layout.StackContainer({style:"width:100%;height:100%;border:0px;",region:"center",id:"billManager-buildUpFloorArea_"+d+"-stackContainer"}),e=new dijit.layout.ContentPane({title:c,content:a});b.addChild(e);var e=new dijit.layout.StackController({region:"top",containerId:"billManager-buildUpFloorArea_"+
d+"-stackContainer"}),e=new dijit.layout.ContentPane({style:"padding:0px;overflow:hidden;","class":"breadCrumbTrail",region:"top",content:e}),f=new dijit.layout.BorderContainer({style:"padding:0px;width:100%;height:100%;border:0px;",gutters:!1,region:"center"});f.addChild(b);f.addChild(e);dojo.subscribe("billManager-buildUpFloorArea_"+d+"-stackContainer-selectChild","",function(a){var b=dijit.byId("billManager-buildUpFloorArea_"+d+"-stackContainer");if(b){var c=b.getChildren();a=dojo.indexOf(c,dijit.byId(a.id));
for(a+=1;c.length>a;)b.removeChild(c[a]),c[a].destroyRecursive(!0),a+=1}});return f},openPrintingDialog:function(){var a=this,f=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});f.show();return r.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(d){d=new w({title:c.printFloorArea+" ("+a.unit+")",printURL:"billBuildUpFloorAreaPrinting/printFloorAreaReport",exportURL:"billBuildUpFloorAreaPrinting/exportFloorAreaReport",billColumnSettingId:a.billColumnSettingId,
_csrf_token:d._csrf_token});f.hide();return d.show()},function(a){return f.hide()})}})});
