define("buildspace/apps/ViewTendererReport/SupplyOfMaterialBillGrid","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/array dojo/dom-attr dojo/request dojo/aspect dojo/store/Memory dijit/Menu dojox/grid/enhanced/plugins/IndirectSelection dojo/number dojo/_base/event dojo/keys dijit/focus dojo/_base/html dojo/request/xhr dijit/PopupMenuItem dijit/MenuSeparator buildspace/widget/grid/cells/Textarea buildspace/widget/grid/cells/Formatter ./PrintPreviewDialog/PrintSelectedSupplyOfMaterialItemGridDialog dojo/i18n!buildspace/nls/TenderingReport dojo/on dojox/grid/_Grid dojox/widget/PlaceholderMenuItem buildspace/widget/grid/cells/TextBox".split(" "),
function(m,n,k,v,w,l,q,p,x,y,z,A,B,C,D,E,F,G,H,r,t,f,I){var u=m("buildspace.apps.ViewTendererReport.SupplyOfMaterialBillGrid",dojox.grid.EnhancedGrid,{type:null,billId:-1,elementId:0,itemId:-1,style:"border-top:none;",selectedItem:null,borderContainerWidget:null,keepSelection:!0,rowSelector:"0px",parentGrid:null,elementGridStore:null,updateUrl:null,project:null,constructor:function(a){this.type=a.type;this.tender_setting=a.tender_setting;this.tender_companies=a.tender_companies;this.currencySetting=
buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;var b=this.formatter=new r;this.companyColumnChildren=[{name:f.estimatedQty+"<br/>("+f.includeWastage+")<br />(A)",field_name:"estimated_qty",width:"85px",cellType:"buildspace.widget.grid.cells.TextBox",styles:"text-align:right;",editable:!0,formatter:b.currencyCellFormatter},{name:"% "+f.ofWastageAllowed,field_name:"percentage_of_wastage",width:"65px",cellType:"buildspace.widget.grid.cells.TextBox",
styles:"text-align:right;",editable:!0,formatter:b.currencyCellFormatter},{name:f.contractorRate+"<br />(X)",field_name:"contractor_supply_rate",width:"85px",cellType:"buildspace.widget.grid.cells.TextBox",styles:"text-align:right;",editable:!0,formatter:b.currencyCellFormatter},{name:f.difference+"<br />(B)=(Y)-(X)",field_name:"difference",width:"85px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:f.amount+" ("+this.currencySetting+")<br />(C)=(A)x(B)",field_name:"amount",
width:"85px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter}];this.setColumnStructure();this.plugins={indirectSelection:{headerSelector:!0,width:"40px",styles:"text-align: center;"}};this.inherited(arguments)},setColumnStructure:function(){var a=this.formatter,b="auto";if("tree"==this.type){0<this.tender_companies.length&&(b="500px");a=this.fixedColumns={noscroll:!1,width:57.8,cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,
noresize:!0,showInCtxMenu:!0,rowSpan:2},{name:f.description,field:"description",width:b,formatter:a.treeCellFormatter,noresize:!0,rowSpan:2},{name:f.type,field:"type",width:"70px",styles:"text-align:center;",formatter:a.typeCellFormatter,noresize:!0,rowSpan:2},{name:f.unit,field:"uom_id",width:"50px",editable:!1,styles:"text-align:center;",formatter:a.unitIdCellFormatter,noresize:!0,rowSpan:2},{name:f.supplyRate,field:"supply_rate",styles:"text-align:right;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,
noresize:!0,rowSpan:2}]]};b=[];var c=this.generateContractorRateColumn(a)}else 5<this.tender_companies.length&&(b="480px"),a=this.fixedColumns={noscroll:!1,width:"50",cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,noresize:!0},{name:f.description,field:"description",width:b,formatter:a.treeCellFormatter,noresize:!0}]]},b=this.generateContractorGrandTotalColumn(),c=a;dojo.forEach(b,function(a){c.cells[0].push(a)});this.structure=c},generateContractorRateColumn:function(a){var b=
this.companyColumnChildren,c=[],d=0;dojo.forEach(this.tender_companies,function(e){var g=b.length;d++;var h=e.awarded?'<span style="color:blue;">'+buildspace.truncateString(e.name,28)+"</span>":buildspace.truncateString(e.name,28);c.push({name:h,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+d,colSpan:g,headerId:e.id,hidden:!1});for(i=0;i<b.length;i++)g=e.id+"-"+b[i].field_name,g={field:g,columnType:"contractorColumn",companyId:e.id,headerClasses:"typeHeader"+d},n.mixin(g,b[i]),
a.cells[0].push(g)});a.cells.push(c);return a},generateContractorGrandTotalColumn:function(){var a=[],b=this.formatter,c=0;dojo.forEach(this.tender_companies,function(d){c++;var e=d.awarded?'<span style="color:blue;">'+buildspace.truncateString(d.name,28)+"</span>":buildspace.truncateString(d.name,28);a.push({name:e,field:d.id+"-total",styles:"text-align:right;",width:"120px",formatter:b.unEditableCurrencyCellFormatter,headerClasses:"typeHeader"+c,noresize:!0})});return a},canSort:function(a){return!1},
postCreate:function(){var a=this;a.inherited(arguments);storeName="tree"===a.type?"viewTendererSupplyOfMaterialItemPreviewStore":"viewTendererSupplyOfMaterialElementPreviewStore";q.after(a,"_onFetchComplete",function(){a.gridContainer.markedCheckBoxObject(a,a.gridContainer[storeName][a.billId])})},startup:function(){var a=this;a.inherited(arguments);this._connects.push(k.connect(this,"onCellClick",function(b){""===b.cell.name&&a.singleCheckBoxSelection(b)}));this._connects.push(k.connect(this.rowSelectCell,
"toggleAllSelection",function(b){a.toggleAllSelection(b)}))},singleCheckBoxSelection:function(a){var b=a.rowIndex;a=this.selection.selected[b];b=this.getItem(b);return a?"tree"===this.type?this.getAffectedElementAndBillsByItems(b,"add"):this.getAffectedItemsAndBillsByElement(b,"add"):"tree"===this.type?this.getAffectedElementAndBillsByItems(b,"remove"):this.getAffectedItemsAndBillsByElement(b,"remove")},toggleAllSelection:function(a){var b=this,c=this.selection;var d="tree"===b.type?"viewTendererSupplyOfMaterialItemPreviewStore":
"viewTendererSupplyOfMaterialElementPreviewStore";if(a)return c.selectRange(0,b.rowCount-1),b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id&&b.gridContainer[d][b.billId].put({id:a.id[0]})})}}),"tree"===b.type?b.getAffectedElementAndBillsByItems(null,"add"):b.getAffectedItemsAndBillsByElement(null,"add");c.deselectAll();return"tree"===b.type?(b.store.fetch({onComplete:function(a){dojo.forEach(a,function(a,c){0<a.id&&b.gridContainer[d][b.billId].remove(a.id[0])})}}),b.getAffectedElementAndBillsByItems(null,
"remove")):b.getAffectedItemsAndBillsByElement(null,"remove")},getAffectedItemsAndBillsByElement:function(a,b){var c=this,d=c.gridContainer.viewTendererSupplyOfMaterialElementPreviewStore[c.billId],e=[],g=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});g.show();a?(c.gridContainer.viewTendererSupplyOfMaterialElementPreviewStore[c.billId].put({id:a.id[0]}),e.push(a.id[0])):d.query().forEach(function(a){e.push(a.id)});l.post("viewTendererReporting/getAffectedSupplyOfMaterialBillsAndItems",
{handleAs:"json",data:{bill_id:c.billId,element_ids:JSON.stringify(c.borderContainerWidget.arrayUnique(e))}}).then(function(a){var d=dijit.byId("viewTenderer-bill-page-container-"+c.project.id);if("add"===b)for(var e in a)for(var h in a[e])for(var f in a[e][h])c.gridContainer.viewTendererSupplyOfMaterialItemPreviewStore[c.billId].put({id:a[e][h][f]});else for(e in a){for(h in a[e])for(f in c.gridContainer.viewTendererSupplyOfMaterialElementPreviewStore[c.billId].remove(h),a[e][h])c.gridContainer.viewTendererSupplyOfMaterialItemPreviewStore[c.billId].remove(a[e][h][f]);
d.store.fetchItemByIdentity({identity:e,onItem:function(a){if(a&&0===c.gridContainer.viewTendererSupplyOfMaterialElementPreviewStore[c.billId].data.length)return c.gridContainer.viewTendererBillPreviewStore.remove(e),d.rowSelectCell.toggleRow(a._0,!1)}})}g.hide()},function(a){g.hide();console.log(a)})},getAffectedElementAndBillsByItems:function(a,b){var c=this,d=[],e=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});e.show();a&&("remove"===b?c.gridContainer.viewTendererSupplyOfMaterialItemPreviewStore[c.billId].remove(a.id[0]):
c.gridContainer.viewTendererSupplyOfMaterialItemPreviewStore[c.billId].put({id:a.id[0]}));c.gridContainer.viewTendererSupplyOfMaterialItemPreviewStore[c.billId].query().forEach(function(a){d.push(a.id)});l.post("viewTendererReporting/getAffectedSupplyOfMaterialBillsAndElements",{handleAs:"json",data:{bill_id:c.billId,itemIds:JSON.stringify(c.borderContainerWidget.arrayUnique(d))}}).then(function(a){c.gridContainer.viewTendererBillPreviewStore=new p({idProperty:"id"});c.gridContainer.viewTendererSupplyOfMaterialElementPreviewStore[c.billId]=
new p({idProperty:"id"});c.updateElementAndBillGridSelectBox(a);e.hide()},function(a){e.hide();console.log(a)})},updateElementAndBillGridSelectBox:function(a){var b=this,c=dijit.byId("viewTenderer-bill-page-container-"+b.project.id),d=dijit.byId("viewTenderer-supplyOfMaterial-element-grid-"+b.billId);c.store.fetch({onItem:function(a){if(a)return c.rowSelectCell.toggleRow(a._0,!1)}});d.store.fetch({onItem:function(a){if(a)return d.rowSelectCell.toggleRow(a._0,!1)}});for(var e in a)for(var f in a[e])d.store.fetchItemByIdentity({identity:f,
onItem:function(a){if(a)return b.gridContainer.viewTendererSupplyOfMaterialElementPreviewStore[b.billId].put({id:f}),d.rowSelectCell.toggleRow(a._0,!0)}})},pushIntoStore:function(a,b){a&&a.id&&b.put({id:a.id[0]});return b},removeFromStore:function(a,b){a&&a.id&&b.remove(a.id[0]);return b},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;
b.parentNode.removeChild(b);dojo.forEach(c,function(a,b){b=dojo.attr(a,"rowSpan");(!b||2>b)&&dojo.attr(a,"rowSpan",2)})}},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,k.disconnect);delete this._connects}});return m("buildspace.apps.ViewTendererReport.SupplyOfMaterialBillGridBuilder",dijit.layout.BorderContainer,{pageId:"page-00",style:"padding:0px;border:none;width:100%;height:100%;",gutters:!1,stackContainerTitle:"",rootProject:null,billId:-1,elementId:0,itemId:-1,rowSelector:null,
gridOpts:{},type:null,postCreate:function(){this.inherited(arguments);var a=this,b=new dijit.Toolbar({region:"top",style:"outline:none!important; border-bottom:none; padding:2px; width:100%;"});b.addChild(new dijit.form.Button({label:f.print,iconClass:"icon-16-container icon-16-print",onClick:function(){a.openPreviewDialogForAllTenderers()}}));this.addChild(b);n.mixin(this.gridOpts,{billId:this.billId,project:this.rootProject,elementId:this.elementId,type:this.type,region:"center",borderContainerWidget:this});
b=this.grid=new u(this.gridOpts);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}));var c=dijit.byId("viewTendererReportBreakdown"+this.rootProject.id+"-stackContainer");if(c){var d=document.createElement("div");c.addChild(new dojox.layout.ContentPane({title:buildspace.truncateString(this.stackContainerTitle,60),id:this.pageId,content:this,grid:b},d));c.selectChild(this.pageId)}},openPreviewDialogForAllTenderers:function(){var a=this,b=a.gridOpts.tender_companies,
c=a.gridOpts.gridContainer.viewTendererSupplyOfMaterialItemPreviewStore[a.billId],d=[],e=[];a.gridOpts.builderContainer.selectedTenderers.query().forEach(function(a){d.push(a.id)});c.query().forEach(function(a){e.push(a.id)});var g=buildspace.dialog.indeterminateProgressBar({title:f.pleaseWait+"..."});g.show();l.post("viewTendererReporting/getSupplyOfMaterialItemRate",{handleAs:"json",data:{bill_id:a.billId,tendererIds:JSON.stringify(a.arrayUnique(d)),itemIds:JSON.stringify(a.arrayUnique(e))}}).then(function(c){(new t({project:a.rootProject,
title:f.supplyOfMaterial,companies:b,data:c,selectedTenderers:d,selectedItems:e,billId:a.billId,elementId:a.elementId})).show();g.hide()},function(a){console.log(a);g.hide()})},arrayUnique:function(a){return a.reverse().filter(function(a,c,d){return-1===d.indexOf(a,c+1)}).reverse()}})});
