var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var d=0;return function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,e){if(b==Array.prototype||b==Object.prototype)return b;b[d]=e.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<b.length;++d){var e=b[d];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,d){var e=$jscomp.propertyToPolyfillSymbol[d];if(null==e)return b[d];e=b[e];return void 0!==e?e:b[d]};
$jscomp.polyfill=function(b,d,e,f){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,d,e,f):$jscomp.polyfillUnisolated(b,d,e,f))};$jscomp.polyfillUnisolated=function(b,d,e,f){e=$jscomp.global;b=b.split(".");for(f=0;f<b.length-1;f++){var k=b[f];if(!(k in e))return;e=e[k]}b=b[b.length-1];f=e[b];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(b,d,e,f){var k=b.split(".");b=1===k.length;f=k[0];f=!b&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var p=0;p<k.length-1;p++){var t=k[p];if(!(t in f))return;f=f[t]}k=k[k.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?f[k]:null;d=d(e);null!=d&&(b?$jscomp.defineProperty($jscomp.polyfills,k,{configurable:!0,writable:!0,value:d}):d!==e&&(void 0===$jscomp.propertyToPolyfillSymbol[k]&&(e=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[k]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(k):$jscomp.POLYFILL_PREFIX+e+"$"+k),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[k],{configurable:!0,writable:!0,value:d})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(b){if(b)return b;var d=function(p,t){this.$jscomp$symbol$id_=p;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:t})};d.prototype.toString=function(){return this.$jscomp$symbol$id_};var e="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0,k=function(p){if(this instanceof k)throw new TypeError("Symbol is not a constructor");return new d(e+(p||"")+"_"+f++,p)};return k},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(b){if(b)return b;b=Symbol("Symbol.iterator");for(var d="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<d.length;e++){var f=$jscomp.global[d[e]];"function"===typeof f&&"function"!=typeof f.prototype[b]&&$jscomp.defineProperty(f.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return b},"es6",
"es3");$jscomp.iteratorPrototype=function(b){b={next:b};b[Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,d){b instanceof String&&(b+="");var e=0,f=!1,k={next:function(){if(!f&&e<b.length){var p=e++;return{value:d(p,b[p]),done:!1}}f=!0;return{done:!0,value:void 0}}};k[Symbol.iterator]=function(){return k};return k};
define("buildspace/apps/PostContract/VariationOrder/VariationOrderClaim","dojo/_base/declare dojo/_base/lang dojo/_base/html dijit/focus dojo/_base/event dojo/keys dojox/grid/EnhancedGrid buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/PostContract".split(" "),function(b,d,e,f,k,p,t,w,h){var x=function(c,a,g){a=this.grid.getItem(a);g.customClasses.push("disable-cell");return a&&!isNaN(parseInt(String(a.id)))?h.version+" "+h.no+" "+c:"&nbsp;"},y=function(c,a,g){if((a=this.grid.getItem(a))&&
!isNaN(parseInt(String(a.id))))return c?'<span class="icon-16-container icon-16-checkmark2" style="margin:0px auto; display:block;"></span>':'<a href="#" onclick="return false;">'+h.printThisRevision+"</a>";g.customClasses.push("disable-cell");return"&nbsp;"},z=function(c,a,g){a=this.grid.getItem(a);a.can_be_edited[0]||g.customClasses.push("disable-cell");return a&&!isNaN(parseInt(String(a.id)))?1==parseInt(c)?h.addendumProgressing:h.addendumLocked:"&nbsp;"},D=b("buildspace.apps.PostContract.VariationOrder.VariationOrderClaimEnhancedGrid",
t,{style:"border-top:none;",rowSelector:"0px",project:null,variationOrder:null,variationOrderItemContainer:null,region:"center",constructor:function(c){var a=new w,g=[h.addendumProgressing,h.addendumLocked],m=[{name:"No.",field:"id",width:"30px",styles:"text-align:center;",formatter:a.rowCountCellFormatter},{name:h.claimVersion,field:"revision",width:"auto",formatter:x}];parseInt(String(c.project.post_contract_type_id))==buildspace.constants.POST_CONTRACT_TYPE_NEW&&m.push({name:h.claimCertificateNumber,
field:"claim_cert_number",styles:"text-align:center;",width:"100px",noresize:!0});dojo.forEach([{name:h.currentPrintingRevision,field:"is_viewing",width:"140px",styles:"text-align: center;",formatter:y},{name:h.status,field:"status",width:"120px",styles:"text-align: center;",editable:!0,cellType:"dojox.grid.cells.Select",options:g,values:[1,2],formatter:z}],function(l){m.push(l)});this.structure=m},canSort:function(c){return!1},postCreate:function(){this.inherited(arguments);this.on("RowClick",function(c){(c=
this.getItem(c.rowIndex))&&!isNaN(parseInt(String(c.id)))&&c.can_be_deleted[0]?this.disableToolbarButtons(!1):this.disableToolbarButtons(!0)});this.on("CellClick",function(c){var a=c.cell.field;c=this.getItem(c.rowIndex);"is_viewing"!=a||!c||isNaN(parseInt(String(c.id)))||c.is_viewing[0]||this.changeCurrentViewingRevision(c)})},canEdit:function(c,a){var g=this;if(void 0==c||this.getItem(a).can_be_edited[0]&&!g.locked)return this._canEdit;window.setTimeout(function(){g.edit.cancel();g.focus.setFocusIndex(a,
c.index)},10)},doApplyCellEdit:function(c,a,g){var m=this,l=this.getItem(a),n=this.store,r=function(){var q=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});q.show().then(function(){dojo.xhrPost({url:"variationOrder/claimUpdate",content:{id:l.id,attr_name:g,val:c,_csrf_token:l._csrf_token?l._csrf_token:null},handleAs:"json",load:function(u){if(u.success){for(var v in u.data)l.hasOwnProperty(v)&&v!=n._getIdentifierAttribute()&&n.setValue(l,v,u.data[v]);n.save();2==l.status?dijit.byId("variationOrderClaim-"+
m.variationOrder.id+"AddRow-button")._setDisabledAttr(!1):1==l.status&&dijit.byId("variationOrderClaim-"+m.variationOrder.id+"AddRow-button")._setDisabledAttr(!0);var A=m.getCellByField(g);window.setTimeout(function(){m.focus.setFocusIndex(a,A.index)},10);dojo.xhrGet({url:"variationOrder/getClaimStatus",content:{id:m.variationOrder.id},handleAs:"json"}).then(function(B){dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}).then(function(C){m.variationOrderItemContainer.createVariationOrderItemGrid(C,
B,!1)})})}q.hide()},error:function(u){q.hide()}})})};c===l[g][0]||isNaN(parseInt(String(l.id)))||("status"==g&&2==c?buildspace.dialog.confirm(h.confirmSubmit,h.cannotBeUndone,60,200,function(){r()},function(){n.setValue(l,"status",1)}):r());this.inherited(arguments)},addNewClaim:function(c){f.curNode.blur();f.curNode=null;var a=this,g=buildspace.dialog.indeterminateProgressBar({title:h.addingRow+". "+h.pleaseWait+"..."}),m=this.store;dojo.xhrGet({url:"variationOrder/getClaimStatus",content:{id:a.variationOrder.id},
handleAs:"json"}).then(function(l){new buildspace.dialog.confirm(h.addNewClaim,0==l.count?h.confirmAddFirstNewClaimTitleMsg:h.confirmAddNewClaimTitleMsg,90,380,function(){g.show().then(function(){dojo.xhrPost({url:"variationOrder/claimAdd",content:{id:a.variationOrder.id,_csrf_token:c},handleAs:"json",load:function(n){n.success&&(m.close(),a._refresh(),dijit.byId("variationOrderClaim-"+a.variationOrder.id+"AddRow-button")._setDisabledAttr(!0),dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}).then(function(r){dojo.xhrGet({url:"variationOrder/getClaimStatus",
content:{id:a.variationOrder.id},handleAs:"json",load:function(q){a.variationOrderItemContainer.createVariationOrderItemGrid(r,q,!1)}})}));a.selection.clear();a.disableToolbarButtons(!0);g.hide()},error:function(n){a.selection.clear();a.disableToolbarButtons(!0);g.hide()}})})},function(){})})},deleteRow:function(){var c=this.getItem(this.selection.selectedIndex);f.curNode.blur();f.curNode=null;if(-1<this.selection.selectedIndex&&c&&!isNaN(parseInt(c.id[0]))&&c.can_be_deleted[0]){var a=this,g=this.store,
m=buildspace.dialog.indeterminateProgressBar({title:h.deleting+". "+h.pleaseWait+"..."}),l={url:"variationOrder/claimDelete",content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(n){n.success&&(g.close(),a._refresh(),dijit.byId("variationOrderClaim-"+a.variationOrder.id+"AddRow-button")._setDisabledAttr(!1),dojo.xhrGet({url:"variationOrder/getClaimStatus",content:{id:a.variationOrder.id},handleAs:"json"}).then(function(r){dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}).then(function(q){a.variationOrderItemContainer.createVariationOrderItemGrid(q,
r,!1)})}));m.hide();a.selection.clear();a.disableToolbarButtons(!0)},error:function(n){a.selection.clear();a.disableToolbarButtons(!0);m.hide()}};new buildspace.dialog.confirm(h.deleteVariationOrderClaimDialogBoxTitle,h.deleteVariationOrderClaimDialogBoxMsg,90,380,function(){m.show().then(function(){dojo.xhrPost(l)})},function(){})}},changeCurrentViewingRevision:function(c){var a=this,g=buildspace.dialog.indeterminateProgressBar({title:h.pleaseWait+"..."});f.curNode.blur();f.curNode=null;g.show().then(function(){dojo.xhrPost({url:"variationOrder/viewClaimRevision",
content:{id:c.id,_csrf_token:c._csrf_token},handleAs:"json",load:function(m){if(m.success){var l=a.store;dojo.forEach(m.items,function(n){l.fetchItemByIdentity({identity:n.id,onItem:function(r){for(var q in n)r.hasOwnProperty(q)&&q!=l._getIdentifierAttribute()&&l.setValue(r,q,n[q])}})});l.save();dojo.xhrGet({url:"variationOrder/getClaimStatus",content:{id:a.variationOrder.id},handleAs:"json"}).then(function(n){dojo.xhrGet({url:"variationOrder/getUnits",handleAs:"json"}).then(function(r){a.variationOrderItemContainer.createVariationOrderItemGrid(r,
n,!1)})})}g.hide();a.selection.clear();a.disableToolbarButtons(!0)},error:function(m){a.selection.clear();a.disableToolbarButtons(!0);g.hide()}})})},disableToolbarButtons:function(c){var a=dijit.byId("variationOrderClaim-"+this.variationOrder.id+"DeleteRow-button");a&&a._setDisabledAttr(c)}});return b("buildspace.apps.PostContract.VariationOrder.VariationOrderClaim",dijit.layout.BorderContainer,{style:"padding:0;margin:0;border:0px;width:100%;height:100%;",gutters:!1,project:null,variationOrder:null,
variationOrderItemContainer:null,claimStatus:null,claimCertificate:null,locked:!1,postCreate:function(){this.inherited(arguments);var c="variationOrder/getClaimList/id/"+this.variationOrder.id;this.claimCertificate&&(c+="/claimRevision/"+this.claimCertificate.post_contract_claim_revision_id);var a=new dojo.data.ItemFileWriteStore({url:c,clearOnClose:!0});c=this.claimStatus._csrf_token;a=new D({project:this.project,variationOrder:this.variationOrder,variationOrderItemContainer:this.variationOrderItemContainer,
claimCertificate:this.claimCertificate,store:a,locked:this.locked});if(!this.locked){var g=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});g.addChild(new dijit.form.Button({id:"variationOrderClaim-"+this.variationOrder.id+"AddRow-button",label:h.addNewClaim,iconClass:"icon-16-container icon-16-add",disabled:"true"==this.variationOrder.is_approved[0]&&this.claimStatus.can_add_new_claim?!1:!0,onClick:d.hitch(a,"addNewClaim",c)}));g.addChild(new dijit.ToolbarSeparator);
g.addChild(new dijit.form.Button({id:"variationOrderClaim-"+this.variationOrder.id+"DeleteRow-button",label:h.deleteRow,iconClass:"icon-16-container icon-16-delete",disabled:-1<a.selection.selectedIndex?!1:!0,onClick:d.hitch(a,"deleteRow")}))}g&&this.addChild(g);this.addChild(a)}})});
