(function(){define("buildspace/apps/RequestForQuotation/AssignProjectGrid","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/on dojo/request dojo/html dojo/dom dojo/keys dojo/dom-style dojo/dom-attr dojox/grid/enhanced/plugins/Menu dojox/grid/enhanced/plugins/Selector dojox/grid/enhanced/plugins/Rearrange dijit/layout/TabContainer dijit/layout/ContentPane dijit/layout/BorderContainer dijit/Toolbar dijit/form/Button buildspace/widget/grid/cells/Formatter dojo/i18n!../../nls/RequestForQuotation dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/Filter".split(" "),
function(f,v,w,x,k,y,z,l,m,g,A,B,n,C,D,p,q,h,r,c,E,t){var u=f("buildspace.apps.RequestForQuotation.RequestForQuotationProjectGrid",dojox.grid.EnhancedGrid,{style:"border:none;padding:0px;margin:0px;width:100%;height:100%;",selectionMode:"single",keepSelection:!0,rowSelector:"0px",region:"center",rfqForm:null,dialogContainer:null,plugins:{indirectSelection:{headerSelector:!1,width:"20px",styles:"text-align:center;"}},constructor:function(a){return this.rearranger=n(this,{})},canSort:function(a){return!1},
noDataMessage:c.noRequestForQuotationProjectAvailableInGrid,postCreate:function(){var a;this.inherited(arguments);a=this;this.connect(this.selection,"onDeselected",function(d){return a.disableToolbarButtons(!0)});return this.connect(this.selection,"onSelected",function(d){return(d=a.getItem(d))&&0<d.id[0]?a.disableToolbarButtons(!1):a.disableToolbarButtons(!0)})},select:function(){var a,d,b;b=this;a=this.getItem(this.selection.selectedIndex);d=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+
"..."});d.show();return k.get("requestForQuotation/getCurrentProjectRFQNo",{query:{projectStructureId:a.id},handleAs:"json"}).then(function(c){d.hide();dijit.byId("rfq-form-button-save").set("disabled",!1);b.rfqForm.assignProjectTitle.innerHTML=a.title[0];b.rfqForm.projectSiteAddress.innerHTML=a.site_address[0];b.rfqForm.currentRFQNo=c.rfqCount;b.rfqForm.countrySelect.set("value",a.region_id[0]);b.rfqForm.stateValue=a.subregion_id[0];b.rfqForm.rfqPrefix.set("value",c.rfqPrefix);c.rfqPrefix?b.rfqForm.rfqPrefix.set("readOnly",
!0):b.rfqForm.rfqPrefix.set("readOnly",!1);g.set(b.rfqForm.projectStructureIdInput,"value",a.id[0]);g.set(b.rfqForm.rfqCountInput,"value",c.rfqCount);b.rfqForm.updateFormView();return b.dialogContainer.hide()},function(a){return d.hide()})},disableToolbarButtons:function(a,c){var b=dijit.byId("requestForQuotationProjectSelectButton");b&&b.set("disabled",a)}});return f("buildspace.apps.RequestForQuotation.RequestForQuotationProjectGridDialog",dijit.Dialog,{title:c.rfqProjectSelectionGrid,style:"padding:0px;margin:0px;width:750px;height:450px;",
rfqForm:null,buildRendering:function(){var a;this.content=a=this.createContent();a.startup();return this.inherited(arguments)},postCreate:function(){m.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},createContent:function(){var a,d,b,e;b=this;a=new dojo.data.ItemFileWriteStore({url:"requestForQuotation/getProjectListings",clearOnClose:!0,urlPreventCache:!0});d=new u({structure:b.getGridLayout(),store:a,rfqForm:b.rfqForm,
dialogContainer:b});e=new q({region:"top",style:"outline:none!important;padding:2px;border:none;width:100%;"});e.addChild(new h({id:"requestForQuotationProjectSelectButton",label:c.select,iconClass:"icon-16-container icon-16-checkmark2",disabled:!0,onClick:function(){return d.select()}}));e.addChild(new dijit.ToolbarSeparator);e.addChild(new h({label:c.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.hide()}}));a=new p({style:"padding:0px;margin:0px;width:750px;height:420px;",
gutters:!1});a.addChild(new t({region:"top",editableGrid:!1,grid:d,filterFields:[{title:c.title,country:c.country,state:c.state}]}));a.addChild(e);a.addChild(d);return a},getGridLayout:function(){return[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:(new r).rowCountCellFormatter},{name:c.title,field:"title",width:"auto"},{name:c.country,field:"country",width:"100px",styles:"text-align: center;"},{name:c.state,field:"state",width:"100px",styles:"text-align: center;"},{name:c.createdAt,
field:"created_at",width:"80px",styles:"text-align: center;"}]},_onKey:function(a){if(a.keyCode===l.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()}})})}).call(this);
