define("buildspace/apps/Location/ProjectLocationManagement/BQLocation/BQLocationContainer","dojo/_base/declare dojo/dom-style dojo/_base/lang dojo/keys dojo/query dojo/on dojo/dom dojo/number dijit/Menu dijit/CheckedMenuItem dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/plugins/LocationFilter buildspace/widget/grid/plugins/UpdateAllColumn dojox/grid/enhanced/plugins/Menu buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/Location".split(" "),function(m,w,n,x,y,
z,A,p,q,r,B,C,D,E,t,b){var v=m("buildspace.apps.ProjectLocationManagement.BQLocation.Grid",dojox.grid.EnhancedGrid,{style:"border-top:none;",project:null,region:"center",postCreate:function(){this.inherited(arguments)},canSort:function(a){return!1},doApplyCellEdit:function(a,e,h){var f=this,d=this.getItem(e),k=this.store;if(a!==d[h][0]){var g=buildspace.dialog.indeterminateProgressBar({title:b.savingData+". "+b.pleaseWait+"..."}),c={id:d.id,attr_name:h,val:a,_csrf_token:d._csrf_token?d._csrf_token:
null},l=function(a,b){for(var c in a)d.hasOwnProperty(c)&&c!=b._getIdentifierAttribute()&&b.setValue(d,c,a[c]);b.save()};g.show().then(function(){dojo.xhrPost({url:"location/billItemQtyByLocationUpdate",content:c,handleAs:"json",load:function(a){if(a.success){isNaN(parseInt(d.id[0]))||l(a.data,k);var c=f.getCellByField(h);window.setTimeout(function(){f.focus.setFocusIndex(e,c.index)},10);g.hide()}},error:function(a){g.hide()}})})}this.inherited(arguments)},canEdit:function(a,b){if(void 0!=a){var e=
this.getItem(b);if(e&&isNaN(parseInt(e.id[0]))&&a.editable){var f=this;window.setTimeout(function(){f.edit.cancel();f.focus.setFocusIndex(b,a.index)},10);return!1}}return this._canEdit},doCancelEdit:function(a){this.inherited(arguments);this.views.renormalizeRow(a);this.scroller.rowHeightChanged(a,!0)},showHideColumn:function(a,b){this.beginUpdate();this.layout.setColumnVisibility(b,a);this.endUpdate()}});return m("buildspace.apps.Location.ProjectLocationManagement.BQLocation.BQLocationContainer",
dijit.layout.BorderContainer,{style:"padding:0;margin:0;width:100%;height:100%;",gutters:!1,project:null,baseApp:null,region:"center",postCreate:function(){this.inherited(arguments);this._selectedIds=[];var a=buildspace.dialog.indeterminateProgressBar({title:b.pleaseWait+"..."}),e=this;a.show().then(function(){dojo.xhrGet({url:"location/getLocationCodeLevels",handleAs:"json",preventCache:!0,content:{pid:e.project.id},load:function(b){e.renderContent(b);a.hide()},error:function(b){a.hide()}})})},renderContent:function(a){var e=
dijit.byId(this.project.id+"-BQLocation-main_grid_content");e&&e.destroyRecursive();var e=new t,h=function(a,b,c){if(a&&0<a.length)return a;c.customClasses.push("disable-cell");return"&nbsp;"},f=[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:e.rowCountCellFormatter},{name:b.bill,field:"bill_title",width:"280px",hidden:!0,showInCtxMenu:!0},{name:b.columnType,field:"column_name",width:"120px",styles:"text-align:center;",hidden:!0,showInCtxMenu:!0},{name:b.columnUnit,field:"column_unit",
width:"120px",styles:"text-align:center;",hidden:!0,showInCtxMenu:!0}],d=[];d.push({idx:3,widgetName:"dropdown",type:buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_TYPE,data:a.column_types});d.push({idx:4,widgetName:"dropdown",type:buildspace.constants.LOCATION_SEQUENCE_TYPE_COLUMN_UNIT,data:a.column_units});for(var k=[],g=4,c=0;c<parseInt(a.predefined_location_codes.length);c++){var l;switch(c){case buildspace.constants.PREDEFINED_LOCATION_CODE_TRADE_LEVEL:l=b.trade;break;case buildspace.constants.PREDEFINED_LOCATION_CODE_ELEMENT_LEVEL:l=
b.element;break;default:l=c>buildspace.constants.PREDEFINED_LOCATION_CODE_SUB_ELEMENT_LEVEL?b.subElement+" ("+(c-1)+")":b.subElement}f.push({name:l,field:c+"-predefined_location_code",width:"180px",formatter:h,styles:"text-align:center;"});g++;d.push({idx:g,widgetName:"dropdown",type:buildspace.constants.LOCATION_SEQUENCE_TYPE_TRADE,data:a.predefined_location_codes[c],level:c})}for(c=0;c<parseInt(a.project_structure_location_codes.length);c++)f.push({name:b.location+" "+(c+1),field:c+"-project_structure_location_code",
width:"180px",formatter:h,styles:"text-align:center;"}),g++,d.push({idx:g,widgetName:"dropdown",type:buildspace.constants.LOCATION_SEQUENCE_TYPE_LOCATION,data:a.project_structure_location_codes[c],level:c});f.push({name:b.billItem,field:"description",width:0<parseInt(a.project_structure_location_codes.length)&&0<parseInt(a.predefined_location_codes.length)?"640px":"auto"});g+=1;d.push({idx:g,widgetName:"textbox"});f.push({name:b.unit,field:"uom",width:"70px",styles:"text-align:center;",noresize:!0});
f.push({name:b.prorated+" %",field:"percentage",width:"120px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:function(a,b,c){a=p.parse(a);isNaN(a)||0==a||null==a?a="&nbsp;":(b=p.format(a,{places:2})+"%",a=0<=a?'<span style="color:blue;">'+b+"</span>":'<span style="color:#FF0000">'+b+"</span>");return a},noresize:!0});g+=2;k.push({idx:g});f.push({name:b.qty,field:"qty",width:"70px",styles:"text-align:right;",formatter:e.numberCellFormatter,noresize:!0});
f.push({name:b.prorated+" "+b.qty,field:"prorated_qty",width:"120px",styles:"text-align:right;",editable:!0,cellType:"buildspace.widget.grid.cells.Textarea",formatter:e.numberCellFormatter,noresize:!0});k.push({idx:g+2});var m=new q,u=this;dojo.forEach(f,function(a,b){a.hasOwnProperty("showInCtxMenu")&&a.showInCtxMenu&&m.addChild(new r({label:a.name,checked:!a.hasOwnProperty("hidden")||!1===a.hidden,onChange:n.hitch(u,"showHideHeaderColumn",b+1)}))});this.grid=new v({id:this.project.id+"-BQLocation-main_grid_content",
structure:f,plugins:{indirectSelection:{headerSelector:!0,width:"20px",styles:"text-align:center;"},menus:{headerMenu:m},buildspaceLocationFilter:{columns:d,gridStoreUrl:"location/getBillByLocations/pid/"+this.project.id,dropDownFilterUrl:"location/getLocationCodeLevels/pid/"+this.project.id,manualFilter:!0},buildspaceUpdateAllColumn:{columns:k,updateUrl:"location/qtyBulkUpdate",_csrf_token:String(this.project._csrf_token),onSuccess:n.hitch(this,"updateAllCallback")}},store:new dojo.data.ItemFileWriteStore({url:"location/getBillByLocations/pid/"+
this.project.id,clearOnClose:!0})});a=dijit.byId(this.project.id+"-BQLocation-main_toolbar");a||(a=new dijit.Toolbar({id:this.project.id+"-BQLocation-main_toolbar",region:"top",style:"border-bottom:none;outline:none!important;padding:2px;overflow:hidden;"}),a.addChild(new dijit.form.Button({label:b.removeFromLocations,iconClass:"icon-16-container icon-16-delete",style:"outline:none!important;",onClick:n.hitch(this,"removeFromLocations")})),a.addChild(new dijit.ToolbarSeparator),a.addChild(new dijit.form.Button({label:b.filterLocations,
iconClass:"icon-16-container icon-16-zoom",style:"outline:none!important;",onClick:n.hitch(this,"filterLocations")})),this.addChild(a));this.addChild(this.grid)},showHideHeaderColumn:function(a,b){this.grid.showHideColumn(b,a)},updateAllCallback:function(a,b){var e=this,f=this.grid,d=f.store;dojo.forEach(a,function(a){d.fetchItemByIdentity({identity:a.id,onItem:function(b){for(var c in a)b.hasOwnProperty(c)&&c!=d._getIdentifierAttribute()&&d.setValue(b,c,a[c])}})});d.save({onComplete:function(){f.focus.setFocusIndex(0,
b.cell.index);e.reloadLocationAssignmentItemGrid()}})},filterLocations:function(){this.grid.manualFilter()},removeFromLocations:function(){this._selectedIds=[];if(0<this.grid.selection.selected.length){for(var a in this.grid.selection.selected)if(this.grid.store._arrayOfAllItems.hasOwnProperty(a)&&String(this.grid.store._arrayOfAllItems[a].id)!=buildspace.constants.GRID_LAST_ROW){var e=String(this.grid.store._arrayOfAllItems[a].id).split("-");-1===this._selectedIds.indexOf(parseInt(e[0]))&&this._selectedIds.push(parseInt(e[0]))}if(0<
this._selectedIds.length){var h=this,f=this._selectedIds,d=this.baseApp,k=this.project,g=buildspace.dialog.indeterminateProgressBar({title:b.deleting+". "+b.pleaseWait+"..."});new buildspace.dialog.confirm(b.removeFromLocations,b.bulkRemoveLocationsMsg,90,320,function(){g.show().then(function(){dojo.xhrPost({url:"location/removeAssignedLocations",content:{ids:f.join(),_csrf_token:k._csrf_token},handleAs:"json",load:function(a){g.hide();a.success&&(d.resetBQLocationTab(!0),h.reloadLocationAssignmentItemGrid())},
error:function(a){g.hide()}})})})}}else buildspace.dialog.alert(b.noLocationSelected,b.pleaseSelectLocationToBeRemoved+".",90,320)},reloadLocationAssignmentItemGrid:function(){var a=dijit.byId("location_assignment-project_item_grid-"+this.project.id);a&&(a.store.save(),a.store.close(),a._refresh())}})});
