(function(){define("buildspace/apps/ProjectAnalyzerReport/ResourcePrintPreviewDialog/PrintSelectedResourceItemGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/ProjectAnalyzer".split(" "),function(e,p,q,r,t,u,v,h,k,l,w,m,n,c){var f,g;f=e("buildspace.apps.ProjectAnalyzerReport.ResourceSelectedItemRateGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1}});g=e("buildspace.apps.ProjectAnalyzerReport.ResourceSelectedItemRateGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,dialog:null,store:null,structure:null,billId:-1,resourceId:-1,projectId:-1,elementId:-1,selectedItems:[],type:null,postCreate:function(){var a,b,d;b=this;b.inherited(arguments);a=this.grid=
new f({store:b.store,structure:b.structure,selectedItems:b.selectedItems});d=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});d.addChild(new dijit.form.Button({label:c.print,iconClass:"icon-16-container icon-16-print",onClick:function(a){return b.openPrintingDialog()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:c.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(d);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",
content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+"..."});b.show();return l.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new m({title:a.dialog.title,selectedRows:a.selectedItems,printURL:"printReport/printSelectedResourceItem",exportURL:"exportExcelReport/exportSelectedResourceItem",billId:a.billId,resourceId:a.resourceId,projectId:a.projectId,elementId:a.elementId,
type:a.type,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return e("buildspace.apps.ProjectAnalyzerReport.ResourcePrintPreviewDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,billId:-1,projectId:-1,resourceId:-1,elementId:-1,data:null,selectedItems:[],type:null,buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){k.set(this.containerNode,{padding:"0px",margin:"0px"});
this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===h.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,b;a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});b=new g({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,selectedItems:this.selectedItems,structure:this.constructGridStructure(),billId:this.billId,resourceId:this.resourceId,
projectId:this.projectId,elementId:this.elementId,type:this.type});a.addChild(b);return a},constructGridStructure:function(a){var b;b=new n;a=[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:b.rowCountCellFormatter},{name:c.description,field:"description",width:"auto",formatter:b.printPreviewTreeCellFormatter,noresize:!0},{name:c.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:b.unitIdCellFormatter,noresize:!0},{name:c.rate,field:"rate",width:"120px",
styles:"text-align:right;",formatter:b.unEditableAnalyzerRateCellFormatter,noresize:!0},{name:c.wastage+" (%)",field:"wastage-value",width:"70px",styles:"text-align:right;",formatter:b.analyzerWastageCellFormatter,noresize:!0},{name:c.totalQty,field:"total_qty",width:"120px",styles:"text-align:right;",formatter:b.unEditableNumberCellFormatter,noresize:!0},{name:c.totalCost,field:"total_cost",width:"120px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter,noresize:!0}];this.type==
buildspace.constants.STATUS_POSTCONTRACT&&(a.push({name:c.claimedQty,field:"claim_quantity",width:"120px",styles:"text-align:right;",formatter:b.unEditableNumberCellFormatter}),a.push({name:c.claimedAmount,field:"claim_amount",width:"120px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter}));return a}})})}).call(this);
