define("buildspace/apps/ProjectBuilderReport/ProjectBreakdown","dojo/_base/declare dojox/grid/EnhancedGrid dojox/grid/enhanced/plugins/IndirectSelection buildspace/widget/grid/cells/Formatter dojo/request dijit/form/Button dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem ./PrintPreviewFormDialog dojo/i18n!buildspace/nls/ProjectBuilder".split(" "),function(e,h,u,k,l,m,n,p,q,r,c){var t=e("buildspace.apps.ProjectBuilderReport.ProjectBreakdownGrid",h,{rootProject:null,explorer:null,style:"border:none;",
region:"center",keepSelection:!0,rowSelector:"0px",constructor:function(a){var b=new k;this.currencySetting=buildspace.billCurrencyAbbreviation?buildspace.billCurrencyAbbreviation:buildspace.currencyAbbreviation;this.structure=[{name:"No.",field:"count",width:"30px",styles:"text-align:center;",formatter:g.rowCountCellFormatter},{name:c.description,field:"title",width:"auto",formatter:g.treeCellFormatter},{name:c.originalAmount,field:"original_total",width:"150px",styles:"text-align: right;",formatter:b.unEditableCurrencyCellFormatter},
{name:c.total+" "+c.markup+" (%)",field:"original_total",width:"100px",styles:"text-align: right;",formatter:b.elementTotalMarkupPercentageCellFormatter},{name:c.total+" "+c.markup+" ("+this.currencySetting+")",field:"original_total",width:"120px",styles:"text-align: right;",formatter:b.elementTotalMarkupAmountCellFormatter},{name:c.overallTotal,field:"overall_total_after_markup",width:"150px",styles:"text-align: right;",formatter:b.unEditableCurrencyCellFormatter},{name:"% "+c.project,field:"overall_total_after_markup",
width:"80px",styles:"text-align: center;",formatter:b.projectBreakdownJobPercentageCellFormatter}];this.inherited(arguments)},canSort:function(a){return!1},dodblclick:function(a){this.onRowDblClick(a)},onRowDblClick:function(a){a=this.getItem(a.rowIndex);switch(parseInt(a.type)){case buildspace.apps.ProjectBuilderReport.ProjectStructureConstants.TYPE_BILL:a.bill_status[0]==buildspace.apps.ProjectBuilderReport.ProjectStructureConstants.BILL_STATUS_OPEN&&this.explorer.initTab(a,{billId:a.id,billLayoutSettingId:a.billLayoutSettingId,
explorer:this.explorer,rootProject:this.rootProject})}}}),g={rowCountCellFormatter:function(a,c){return 0<a?a:""},treeCellFormatter:function(a,c){var b=this.grid.getItem(c),f=16*b.level;a=null==a?"&nbsp":a;b.type<buildspace.apps.ProjectBuilderReport.ProjectStructureConstants.TYPE_BILL&&(a="<b>"+a+"</b>");return'<div class="treeNode" style="padding-left:'+f+'px;"><div class="treeContent">'+a+"&nbsp;</div></div>"}};return e("buildspace.apps.ProjectBuilderReport.ProjectBreakdown",dijit.layout.BorderContainer,
{region:"center",style:"padding:0px;width:100%;height:100%;",gutters:!1,rootProject:null,explorer:null,grid:null,analysisStatus:null,postCreate:function(){this.inherited(arguments);var a=this,b=new dojo.data.ItemFileWriteStore({clearOnClose:!0,url:"projectBuilder/getProjectBreakdown/id/"+this.rootProject.id}),d=new dijit.Toolbar({region:"top",style:"border:none;padding:2px;width:100%;"}),b=this.grid=t({rootProject:this.rootProject,explorer:this.explorer,store:b}),f=new p({style:"display: none;"}),
e=this.analysisStatus;dojo.forEach(["resourceAnalysis","scheduleOfRateAnalysis"],function(b){var d=!0;"resourceAnalysis"==b&&!0===e.enable_resource_analysis?d=!1:"scheduleOfRateAnalysis"==b&&!0===e.enable_schedule_of_rate_analysis&&(d=!1);d=new q({id:b+"-"+a.rootProject.id+"-menuItem",label:c[b],disabled:d,onClick:function(){buildspace.app.launch({__children:[],icon:"project_analyzer",id:a.rootProject.id+"-project_analyzer",is_app:!0,level:0,sysname:"ProjectAnalyzerReport",title:c.projectAnalyzer},
{type:buildspace.constants.STATUS_PRETENDER,opt:b,project:a.rootProject})}});f.addChild(d)});d.addChild(new n({label:c.projectAnalyzer,iconClass:"icon-16-container icon-16-project_analyzer",style:"outline:none!important;",dropDown:f}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new m({label:c.printSummary,iconClass:"icon-16-container icon-16-print",style:"outline:none!important;",onClick:function(){a.openSelectedBillsPrintingFormDialog()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:c.subPackages,
iconClass:"icon-16-container icon-16-file",onClick:function(b){buildspace.app.launch({__children:[],icon:"project_sub_package",id:a.rootProject.id+"-project_sub_package",is_app:!0,level:0,sysname:"SubPackageReport",title:c.subPackages},{type:buildspace.constants.STATUS_PRETENDER,project:a.rootProject})}}));this.addChild(d);this.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))},openSelectedBillsPrintingFormDialog:function(){var a=this,b=buildspace.dialog.indeterminateProgressBar({title:c.pleaseWait+
"..."});b.show();return l.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(d){(new r({title:c.projectEstimateSummary,projectId:a.rootProject.id,printURL:"projectBuilderReport/printProjectEstimateSummary",exportURL:"projectBuilderReport/exportExcelProjectEstimateSummary",_csrf_token:d._csrf_token})).show();b.hide()},function(a){console.log(a);b.hide()})}})});
