(function(){define("buildspace/apps/ViewTendererReport/PrintPreviewDialog/PrintSelectedItemTotalGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/TenderingReport".split(" "),function(h,u,v,w,x,y,z,n,p,k,q,r,t,e){var l,m;l=h("buildspace.apps.TenderingReport.SelectedItemTotalGrid",dojox.grid.EnhancedGrid,{style:"border-top:none;",
region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1}});m=h("buildspace.apps.TenderingReport.SelectedItemTotalGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",billId:-1,elementId:-1,gutters:!1,dialog:null,store:null,structure:null,selectedTenderers:[],selectedItems:[],type:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new l({store:b.store,structure:b.structure,selectedItems:b.selectedItems});
c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:e.print,iconClass:"icon-16-container icon-16-print",onClick:function(a){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:e.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,
region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:e.pleaseWait+"..."});b.show();return k.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new r({title:a.dialog.title,selectedTenderers:a.selectedTenderers,selectedRows:a.selectedItems,type:a.type,printURL:null!==a.type?"printReport/printItemTotal":"printReport/printSelectedItemTotal",exportURL:null!==a.type?"exportExcelReport/exportItemTotal":
"exportExcelReport/exportSelectedItemTotal",billId:a.billId,elementId:a.elementId,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return h("buildspace.apps.TenderingReport.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,billId:-1,elementId:-1,companyId:-1,companyName:null,data:null,type:null,selectedTenderers:[],selectedItems:[],buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},
postCreate:function(){p.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===n.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,b,c;b={};a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});0<this.selectedTenderers.length&&this.type&&k("viewTendererReporting/getContractors",{sync:!0,
handleAs:"json",query:{id:this.project.id,type:this.type,contractorIds:q.stringify(this.selectedTenderers)}}).then(function(a){return b=a},function(a){return console.log(a)});c=new m({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,selectedTenderers:this.selectedTenderers,selectedItems:this.selectedItems,structure:this.constructGridStructure(b),billId:this.billId,elementId:this.elementId,type:this.type});a.addChild(c);return a},constructGridStructure:function(a,b,c){var g,d,f;null==
a&&(a=[]);null==b&&(b=this.type);null==c&&(c=this);d=new t;g=[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:d.rowCountCellFormatter},{name:e.billReference,field:"bill_ref",styles:"text-align:center; color: red;",width:"80px",noresize:!0,formatter:d.billRefCellFormatter},{name:e.description,field:"description",width:3<a.length?"380px":"auto",formatter:d.printPreviewTreeCellFormatter,noresize:!0}];if(b)for(f in b={name:e.estimate,field:"grand_total",styles:"text-align:right;color:blue;",
width:"100px",formatter:d.unEditableCurrencyCellFormatter,noresize:!0},g.push(b),a)c=a[f].awarded?"blue":"black",b=buildspace.truncateString(a[f].name,28),b={name:'<span style="color:'+c+'">'+b+"</span>",field:a[f].id+"-grand_total",styles:"text-align:right;color:"+c+";",width:"100px",formatter:d.printPreviewTendererCurrencyCellFormatter,noresize:!0},g.push(b);else for(f in b=[{name:e.estimate,field:"grand_total",styles:"text-align:right;color:blue;",width:"100px",formatter:d.unEditableCurrencyCellFormatter,
noresize:!0},{name:'<span style="color:blue;">'+c.companyName+"</span>",field:c.companyId+"-grand_total",styles:"text-align:right;color:blue;",width:"100px",formatter:d.unEditableCurrencyCellFormatter,noresize:!0},{name:e.difference+" %",field:c.companyId+"-difference_percentage",styles:"text-align:right;color:blue;",width:"100px",formatter:d.unEditablePercentageCellFormatter,noresize:!0},{name:e.difference+" "+buildspace.currencyAbbreviation,field:c.companyId+"-difference_amount",styles:"text-align:right;color:blue;",
width:"100px",formatter:d.unEditableCurrencyCellFormatter,noresize:!0}],b)a=b[f],g.push(a);return g}})})}).call(this);
