(function(){define("buildspace/apps/ViewTendererReport/PrintPreviewDialog/PrintPreviewFormDialog","dojo/_base/declare dojo/_base/lang dojo/keys dojo/parser dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/Toolbar dijit/form/Button dijit/layout/BorderContainer dijit/form/ValidationTextBox dijit/form/RadioButton dijit/form/SimpleTextarea dijit/registry dojo/dom-style dojo/dom-form dojo/request dojo/json dojox/validate/web dojox/form/Manager dojo/text!./templates/printPreviewForm.html dojo/i18n!buildspace/nls/TenderingReport".split(" "),
function(g,w,l,x,m,n,p,q,r,h,t,y,z,A,B,u,C,D,e,E,F,v,f){var k;k=g("buildspace.apps.ViewTendererReport.SupplierList.PrintPreviewForm",[m,n,p,q],{baseClass:"buildspace-form",templateString:v,region:"center",style:"overflow: auto;",default_title_input:null,billId:-1,elementId:-1,projectId:-1,printURL:null,exportURL:null,selectedTenderers:[],selectedRows:[],sortingType:null,_csrf_token:null,nls:f,dialogContainer:null,print:function(){var a,c,b;b=this.viewTendererReportingPrintForm;if(!b.validate())return!1;
c=dojo.formToObject(b.id);(b=document.getElementById("printingPreviewForm"))&&b.parentNode.removeChild(b);b=document.createElement("form");b.setAttribute("method","post");b.setAttribute("action",this.printURL);b.setAttribute("id","printingPreviewForm");b.setAttribute("target","formresult");a=document.createElement("input");a.setAttribute("name","printingPageTitle");a.setAttribute("value",c.fileName);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name",
"descriptionFormat");a.setAttribute("value",c.descriptionFormat);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","selectedRows");a.setAttribute("value",e.stringify(this.selectedRows));a.setAttribute("type","hidden");b.appendChild(a);0<this.elementId&&(a=document.createElement("input"),a.setAttribute("name","elementId"),a.setAttribute("value",this.elementId),a.setAttribute("type","hidden"),b.appendChild(a));0<this.billId&&(a=document.createElement("input"),
a.setAttribute("name","billId"),a.setAttribute("value",this.billId),a.setAttribute("type","hidden"),b.appendChild(a));0<this.projectId&&(a=document.createElement("input"),a.setAttribute("name","projectId"),a.setAttribute("value",this.projectId),a.setAttribute("type","hidden"),b.appendChild(a));this.sortingType&&(a=document.createElement("input"),a.setAttribute("name","sortingType"),a.setAttribute("value",this.sortingType),a.setAttribute("type","hidden"),b.appendChild(a));0<this.selectedTenderers.length&&
(a=document.createElement("input"),a.setAttribute("name","selectedTenderers"),a.setAttribute("value",e.stringify(this.selectedTenderers)),a.setAttribute("type","hidden"),b.appendChild(a));a=document.createElement("input");a.setAttribute("name","priceFormat");a.setAttribute("value",c.priceFormat);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","printNoCents");a.setAttribute("value",c.printNoCents);a.setAttribute("type","hidden");b.appendChild(a);
c=document.createElement("input");c.setAttribute("name","_csrf_token");c.setAttribute("value",this._csrf_token);c.setAttribute("type","hidden");b.appendChild(c);document.body.appendChild(b);window.open(null,"formresult");return b.submit()},"export":function(){var a,c,b;b=this.viewTendererReportingPrintForm;if(!b.validate())return!1;c=dojo.formToObject(b.id);(b=document.getElementById("printingPreviewForm"))&&b.parentNode.removeChild(b);b=document.createElement("form");b.setAttribute("method","post");
b.setAttribute("action",this.exportURL);b.setAttribute("id","printingPreviewForm");b.setAttribute("target","_self");a=document.createElement("input");a.setAttribute("name","printingPageTitle");a.setAttribute("value",c.fileName);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","descriptionFormat");a.setAttribute("value",c.descriptionFormat);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name",
"selectedRows");a.setAttribute("value",e.stringify(this.selectedRows));a.setAttribute("type","hidden");b.appendChild(a);0<this.elementId&&(a=document.createElement("input"),a.setAttribute("name","elementId"),a.setAttribute("value",this.elementId),a.setAttribute("type","hidden"),b.appendChild(a));0<this.billId&&(a=document.createElement("input"),a.setAttribute("name","billId"),a.setAttribute("value",this.billId),a.setAttribute("type","hidden"),b.appendChild(a));0<this.projectId&&(a=document.createElement("input"),
a.setAttribute("name","projectId"),a.setAttribute("value",this.projectId),a.setAttribute("type","hidden"),b.appendChild(a));this.sortingType&&(a=document.createElement("input"),a.setAttribute("name","sortingType"),a.setAttribute("value",this.sortingType),a.setAttribute("type","hidden"),b.appendChild(a));0<this.selectedTenderers.length&&(a=document.createElement("input"),a.setAttribute("name","selectedTenderers"),a.setAttribute("value",e.stringify(this.selectedTenderers)),a.setAttribute("type","hidden"),
b.appendChild(a));a=document.createElement("input");a.setAttribute("name","priceFormat");a.setAttribute("value",c.priceFormat);a.setAttribute("type","hidden");b.appendChild(a);a=document.createElement("input");a.setAttribute("name","printNoCents");a.setAttribute("value",c.printNoCents);a.setAttribute("type","hidden");b.appendChild(a);c=document.createElement("input");c.setAttribute("name","_csrf_token");c.setAttribute("value",this._csrf_token);c.setAttribute("type","hidden");b.appendChild(c);document.body.appendChild(b);
this.dialogContainer&&this.dialogContainer.hide();return b.submit()}});return g("buildspace.apps.ViewTendererReport.PrePrintFormDialog",dijit.Dialog,{style:"padding:0px;margin:0px;width:480px;height:210px;",printURL:null,exportURL:null,selectedTenderers:[],selectedRows:[],type:null,billId:-1,elementId:-1,projectId:-1,_csrf_token:null,buildRendering:function(){var a;this.content=a=this.createContent();a.startup();return this.inherited(arguments)},postCreate:function(){u.set(this.containerNode,{padding:"0px",
margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},createContent:function(a){var c,b,d;null==a&&(a=this);c=new t({style:"width:480px;height:210px;padding:0;margin:0;",gutters:!1});b=new k({default_title_input:a.title,dialogContainer:a,printURL:a.printURL,exportURL:a.exportURL,selectedTenderers:a.selectedTenderers,selectedRows:a.selectedRows,_csrf_token:a._csrf_token,billId:a.billId,elementId:a.elementId,projectId:a.projectId,sortingType:a.type});d=new r({region:"top",
style:"outline:none!important;padding:2px;overflow:hidden;"});null!=a.printURL&&(d.addChild(new h({label:f.print,iconClass:"icon-16-container icon-16-print",onClick:function(){return b.print()}})),d.addChild(new dijit.ToolbarSeparator));null!=a.exportURL&&(d.addChild(new h({label:f.exportToExcel,iconClass:"icon-16-container icon-16-spreadsheet",onClick:function(){return b["export"]()}})),d.addChild(new dijit.ToolbarSeparator));d.addChild(new dijit.form.Button({label:f.close,iconClass:"icon-16-container icon-16-close",
onClick:function(){return a.hide()}}));c.addChild(d);c.addChild(b);return c},_onKey:function(a){if(a.keyCode===l.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()}})})}).call(this);
