(function(){define("buildspace/apps/ViewTendererReport/PrintPreviewDialog/PrintSelectedItemRateAndTotalRevisionsGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/TenderingReport".split(" "),function(k,z,A,B,C,D,E,u,v,q,w,x,y,d){var r,t;r=k("buildspace.apps.TenderingReport.SelectedItemRateAndTotalRevisionsGrid",
dojox.grid.EnhancedGrid,{style:"border-top:none;",region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1},onHeaderCellMouseOver:function(a){dojo.hasClass(a.cell.id,"staticHeader")||dojo.addClass(a.cellNode,this.cellOverClass)},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],c=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(c,
function(a,c){var b=dojo.attr(a,"rowSpan");(!b||2>b)&&dojo.attr(a,"rowSpan",2)})}}});t=k("buildspace.apps.TenderingReport.SelectedItemRateAndTotalRevisionsGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,billId:-1,elementId:-1,dialog:null,store:null,structure:null,selectedTenderers:[],selectedItems:[],type:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new r({store:b.store,structure:b.structure,selectedItems:b.selectedItems});
c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",onClick:function(a){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",content:a,
region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return q.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new x({title:a.dialog.title,selectedTenderers:a.selectedTenderers,selectedRows:a.selectedItems,type:a.type,printURL:null,exportURL:"exportExcelReport/exportItemRateAndTotalRevisions",billId:a.billId,elementId:a.elementId,_csrf_token:c._csrf_token});
b.hide();return c.show()},function(a){return b.hide()})}});return k("buildspace.apps.TenderingReport.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,companyId:-1,companyName:null,billId:-1,elementId:-1,data:null,type:null,selectedTenderers:[],selectedItems:[],buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){v.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display=
"none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===u.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,b,c;b={};var d={};a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});0<this.selectedTenderers.length&&this.type&&q("viewTendererReporting/getContractors",{sync:!0,handleAs:"json",query:{id:this.project.id,type:this.type,contractorIds:w.stringify(this.selectedTenderers)}}).then(function(a){return b=
a},function(a){return console.log(a)});q("viewTendererReporting/getRevisions",{sync:!0,handleAs:"json",query:{id:this.project.id}}).then(function(a){return d=a.revisions},function(a){console.log(a)});c=new t({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,billId:this.billId,elementId:this.elementId,selectedTenderers:this.selectedTenderers,selectedItems:this.selectedItems,structure:this.constructGridStructure(b,d),type:this.type});a.addChild(c);return a},constructGridStructure:function(a,
b,c,m){var g,h,f,l,k,n=[],p=b.length-1;null==a&&(a=[]);c=new y;k=[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:c.rowCountCellFormatter},{name:d.billReference,field:"bill_ref",width:"80px",styles:"text-align:center; color: red;",formatter:c.billRefCellFormatter,noresize:!0},{name:d.description,field:"description",width:"auto",formatter:c.printPreviewTreeCellFormatter,noresize:!0},{name:d.unit,field:"uom_id",width:"70px",styles:"text-align:center;",formatter:c.unitIdCellFormatter,
noresize:!0},{name:d.quantity,field:"grand_total_quantity",width:"70px",scroll:!1,styles:"text-align:right;color:blue;",formatter:c.unEditableNumberAndTextCellFormatter,noresize:!0}];for(var e=0;e<=p;e++)l=b[e].revision,n.push({name:l+" "+d.rate,field:"rate_after_markup_revision-"+e,width:"100px",styles:"text-align:right;color:blue;",formatter:c.unEditableCurrencyCellFormatter,noresize:!0}),n.push({name:l+" "+d.total,field:"grand_total_revision-"+e,width:"100px",styles:"text-align:right;color:blue;",
formatter:c.unEditableCurrencyCellFormatter,noresize:!0});m=[];m.push({name:d.estimate,styles:"text-align:center;",headerClasses:"staticHeader",colSpan:2+2*p});for(h in a){f=a[h].awarded?"blue":"black";g=buildspace.truncateString(a[h].name,28);m.push({name:'<span style="color:'+f+'">'+g+"</span>",styles:"text-align:center;color:"+f+";",headerClasses:"staticHeader",colSpan:2+2*p});g=[];for(e=0;e<=p;e++)l=b[e].revision,g.push({name:'<span style="color:'+f+'">'+l+" "+d.rate+"</span>",field:a[h].id+"-rate-value_revision-"+
e,styles:"text-align:right;color:"+f+";",width:"100px",formatter:c.printPreviewTendererRateCellFormatter,noresize:!0}),g.push({name:'<span style="color:'+f+'">'+l+" "+d.total+"</span>",field:a[h].id+"-grand_total_revision-"+e,styles:"text-align:right;color:"+f+";",width:"100px",formatter:c.printPreviewTendererRateCellFormatter,noresize:!0});for(h in g)f=g[h],n.push(f)}return[{cells:[k],width:"560px",noscroll:!0},{cells:[n,m]}]}})})}).call(this);
