(function(){define("buildspace/apps/ViewTendererReport/PrintPreviewDialog/PrintSelectedSupplyOfMaterialItemGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/TenderingReport".split(" "),function(e,r,h,g,t,u,v,k,l,w,x,m,n,c){var p=e("buildspace.apps.TenderingReport.SelectedSupplyOfMaterialItemGrid",dojox.grid.EnhancedGrid,
{style:"border-top:none;",region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1},onStyleRow:function(a){this.inherited(arguments);if(a.node.children[0]&&2<=a.node.children[0].children[0].rows.length){var b=a.node.children[0].children[0].rows[1],d=a.node.children[0].children[0].rows[0].children;b.parentNode.removeChild(b);dojo.forEach(d,function(a,b){b=dojo.attr(a,"rowSpan");(!b||2>b)&&dojo.attr(a,"rowSpan",2)})}},destroy:function(){this.inherited(arguments);dojo.forEach(this._connects,
g.disconnect);delete this._connects}});var q=e("buildspace.apps.TenderingReport.SelectedSupplyOfMaterialItemGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,billId:-1,elementId:-1,dialog:null,store:null,structure:null,selectedTenderers:[],selectedItems:[],postCreate:function(){var a=this;a.inherited(arguments);var b=this.grid=new p({store:a.store,structure:a.structure,selectedItems:a.selectedItems});var d=new dijit.Toolbar({region:"top",
style:"padding:2px;border-bottom:none;width:100%;"});d.addChild(new dijit.form.Button({label:c.print,iconClass:"icon-16-container icon-16-print",onClick:function(b){return a.openPrintingDialog()}}));d.addChild(new dijit.ToolbarSeparator);d.addChild(new dijit.form.Button({label:c.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return a.dialog.hide()}}));a.addChild(d);return a.addChild(new dijit.layout.ContentPane({style:"width:100%",content:b,region:"center"}))},openPrintingDialog:function(a){return(new m({title:this.dialog.title,
selectedTenderers:this.selectedTenderers,selectedRows:this.selectedItems,exportURL:"exportExcelReport/exportSupplyOfMaterialItem",billId:this.billId})).show()}});return e("buildspace.apps.TenderingReport.PrintSelectedSupplyOfMaterialItemDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,companyId:-1,billId:-1,elementId:-1,data:null,companiesList:[],selectedTenderers:[],selectedItems:[],buildRendering:function(){var a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},
postCreate:function(){l.set(this.containerNode,{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===k.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});this.companiesList=[];for(b in this.companies)this.selectedTenderers.includes(this.companies[b].id)&&this.companiesList.push(this.companies[b]);
var b=new q({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,billId:this.billId,elementId:this.elementId,selectedTenderers:this.selectedTenderers,selectedItems:this.selectedItems,structure:this.getGridStructure()});a.addChild(b);return a},getGridStructure:function(){var a=this.formatter=new n,b="auto";0<this.selectedTenderers.length&&(b="500px");a=this.fixedColumns={noscroll:!1,width:57.8,cells:[[{name:"No",field:"id",styles:"text-align:center;",width:"30px",formatter:a.rowCountCellFormatter,
noresize:!0,showInCtxMenu:!0,rowSpan:2},{name:c.description,field:"description",width:b,formatter:a.treeCellFormatter,noresize:!0,rowSpan:2},{name:c.unit,field:"uom_id",width:"50px",editable:!1,styles:"text-align:center;",formatter:a.unitIdCellFormatter,noresize:!0,rowSpan:2},{name:c.supplyRate,field:"supply_rate",styles:"text-align:right;",width:"100px",formatter:a.unEditableCurrencyCellFormatter,noresize:!0,rowSpan:2}]]};var d=this.generateContractorRateColumn(a);dojo.forEach([],function(a){d.cells[0].push(a)});
return d},generateContractorRateColumn:function(a){var b=this.formatter,d=[],e=0,f=[{name:c.estimatedQty+"<br/>("+c.includeWastage+")<br />(A)",field_name:"estimated_qty",width:"85px",cellType:"buildspace.widget.grid.cells.TextBox",styles:"text-align:right;",editable:!0,formatter:b.currencyCellFormatter},{name:"% "+c.ofWastageAllowed,field_name:"percentage_of_wastage",width:"65px",cellType:"buildspace.widget.grid.cells.TextBox",styles:"text-align:right;",editable:!0,formatter:b.currencyCellFormatter},
{name:c.contractorRate+"<br />(X)",field_name:"contractor_supply_rate",width:"85px",cellType:"buildspace.widget.grid.cells.TextBox",styles:"text-align:right;",editable:!0,formatter:b.currencyCellFormatter},{name:c.difference+"<br />(B)=(Y)-(X)",field_name:"difference",width:"85px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter},{name:c.amount+" ("+this.currencySetting+")<br />(C)=(A)x(B)",field_name:"amount",width:"85px",styles:"text-align:right;",formatter:b.unEditableCurrencyCellFormatter}];
dojo.forEach(this.companiesList,function(b){var c=f.length;e++;var g=b.awarded?'<span style="color:blue;">'+buildspace.truncateString(b.name,28)+"</span>":buildspace.truncateString(b.name,28);d.push({name:g,styles:"text-align:center;",headerClasses:"staticHeader typeHeader"+e,colSpan:c,headerId:b.id,hidden:!1});for(i=0;i<f.length;i++)c=b.id+"-"+f[i].field_name,c={field:c,columnType:"contractorColumn",companyId:b.id,headerClasses:"typeHeader"+e},h.mixin(c,f[i]),a.cells[0].push(c)});a.cells.push(d);
return a}})})}).call(this);
