(function(){define("buildspace/apps/ViewTendererReport/PrintPreviewDialog/PrintSelectedScheduleOfRateItemGridDialog","dojo/_base/declare dojo/aspect dojo/_base/lang dojo/_base/connect dojo/when dojo/html dojo/dom dojo/keys dojo/dom-style dojo/request dojo/json ./PrintPreviewFormDialog buildspace/widget/grid/cells/Formatter dojo/i18n!buildspace/nls/TenderingReport".split(" "),function(e,q,r,t,u,v,w,k,l,f,m,n,p,d){var g,h;g=e("buildspace.apps.TenderingReport.SelectedScheduleOfRateItemGrid",dojox.grid.EnhancedGrid,
{style:"border-top:none;",region:"center",selectedItems:[],escapeHTMLInData:!1,canSort:function(){return!1}});h=e("buildspace.apps.TenderingReport.SelectedScheduleOfRateItemGridContainer",dijit.layout.BorderContainer,{style:"padding:0px;width:100%;height:100%;",region:"center",gutters:!1,billId:-1,elementId:-1,dialog:null,store:null,structure:null,selectedTenderers:[],selectedItems:[],type:null,postCreate:function(){var a,b,c;b=this;b.inherited(arguments);a=this.grid=new g({store:b.store,structure:b.structure,
selectedItems:b.selectedItems});c=new dijit.Toolbar({region:"top",style:"padding:2px;border-bottom:none;width:100%;"});c.addChild(new dijit.form.Button({label:d.print,iconClass:"icon-16-container icon-16-print",onClick:function(a){return b.openPrintingDialog()}}));c.addChild(new dijit.ToolbarSeparator);c.addChild(new dijit.form.Button({label:d.close,iconClass:"icon-16-container icon-16-close",onClick:function(){return b.dialog.hide()}}));b.addChild(c);return b.addChild(new dijit.layout.ContentPane({style:"width:100%",
content:a,region:"center"}))},openPrintingDialog:function(a){var b;null==a&&(a=this);b=buildspace.dialog.indeterminateProgressBar({title:d.pleaseWait+"..."});b.show();return f.get("viewTendererReporting/getPrintingInformation",{handleAs:"json"}).then(function(c){c=new n({title:a.dialog.title,selectedTenderers:a.selectedTenderers,selectedRows:a.selectedItems,type:a.type,printURL:null!==a.type?"printReport/printScheduleOfRateItem":"",exportURL:null!==a.type?"scheduleOfRateExportExcelReporting/exportScheduleOfRateTendererReport":
"",billId:a.billId,elementId:a.elementId,_csrf_token:c._csrf_token});b.hide();return c.show()},function(a){return b.hide()})}});return e("buildspace.apps.TenderingReport.GroupProjectAssignmentDialog",dijit.Dialog,{style:"padding:0px;margin:0px;",project:null,companyId:-1,companyName:null,billId:-1,elementId:-1,data:null,type:null,selectedTenderers:[],selectedItems:[],buildRendering:function(){var a;a=this.createContent();a.startup();this.content=a;return this.inherited(arguments)},postCreate:function(){l.set(this.containerNode,
{padding:"0px",margin:"0px"});this.closeButtonNode.style.display="none";return this.inherited(arguments)},_onKey:function(a){if(a.keyCode===k.ESCAPE)return dojo.stopEvent(a)},onHide:function(){return this.destroyRecursive()},createContent:function(){var a,b,c;b={};a=new dijit.layout.BorderContainer({style:"padding:0px;width:1280px;height:600px;",gutters:!1});0<this.selectedTenderers.length&&this.type&&f("viewTendererReporting/getContractorsScheduleOfRate",{sync:!0,handleAs:"json",query:{id:this.project.id,
type:this.type,contractorIds:m.stringify(this.selectedTenderers)}}).then(function(a){return b=a},function(a){return console.log(a)});c=new h({store:dojo.data.ItemFileWriteStore({data:this.data}),dialog:this,billId:this.billId,elementId:this.elementId,selectedTenderers:this.selectedTenderers,selectedItems:this.selectedItems,structure:this.constructGridStructure(b),type:this.type});a.addChild(c);return a},constructGridStructure:function(a,b,c){null==a&&(a=[]);null==b&&(b=this.type);b=!b;c=new p;basicStructure=
[{name:"No",field:"id",width:"30px",styles:"text-align: center;",formatter:c.rowCountCellFormatter},{name:d.description,field:"description",width:3<a.length?"380px":"auto",formatter:c.printPreviewTreeCellFormatter,noresize:!0},{name:d.unit,field:"uom_id",width:"50px",editable:!1,styles:"text-align:center;",formatter:c.unitIdCellFormatter,noresize:!0},{name:d.estimate,field:"estimation_rate",styles:"text-align:right;color:blue;",width:"100px",formatter:c.unEditableCurrencyCellFormatter,noresize:!0}];
if(!b)for(key in a)textColor=a[key].awarded?"blue":"black",companyName=buildspace.truncateString(a[key].name,28),tendererEstimateColumn={name:'<span style="color:'+textColor+'">'+companyName+"</span>",field:a[key].id+"-rate-value",styles:"text-align:right;color:"+textColor+";",width:"100px",formatter:c.printPreviewTendererRateCellFormatter,noresize:!0},basicStructure.push(tendererEstimateColumn);return basicStructure}})})}).call(this);
